### ISSUE TITLE
数据去重复

### ISSUE THREAD

**Issue by sy618** [racaljk/hosts#1007]
2 firebase.google.com
      4 gd2.line.naver.jp
      4 gd2w.line.naver.jp
      3 gw.line.naver.jp
      2 gww.line.naver.jp
     15 gwx.line.naver.jp
      2 lan.line.me
      3 obs-cn.line-apps.com
      3 obs-tw.line-apps.com
      2 obs.line-apps.com
     13 scdn.line-apps.com
      2 w.line.me
      2 xcdn-cn-prf.line-apps.com
      2 xcdn-cn-stk.line-apps.com
（行首数字代表重复次数）

**Comment by lrinQVQ** [comment]
你修改好开个PR如何233 谢谢啦～

**Comment by sy618** [comment]
还是由你直接编辑吧。

顺便把以下数据加上，

#pinterest   这是我抓包数据，你对比一下，有缺失的就添加。             
151.101.192.84 www.pinterest.com
151.101.192.84 pinterest.com
151.101.192.84 api.pinterest.com
151.101.192.84 nl.pinterest.com
151.101.192.84 s.pinimg.com
151.101.192.84 i.pinimg.com
151.101.192.84 v.pinimg.com
151.101.192.84 s-media-cache-ak0.pinimg.com
151.101.192.84 passets-cdn.pinterest.com
151.101.192.84 post.pinterest.com
151.101.192.84 trk.pinterest.com

#Ingress 一个游戏
54.241.32.8 appload.ingest.crittercism.com
54.241.32.8 api.crittercism.com
54.193.253.0 txn.ingest.crittercism.com
169.44.145.200 bootstrap.upsight-api.com
169.44.145.200 single.upsight-api.com
169.44.145.200 batch.upsight-api.com

**Comment by lrinQVQ** [comment]
ok

**Comment by imknown** [comment]
`54.241.32.8` 和 `54.193.253.0` 不行.

**Comment by sy618** [comment]
这两IP是亚马逊服务器IP，这些服务器一般都禁止ping，所以你才ping不通。但其实是可用的。你开游戏试试。

@lrinQVQ ingress游戏还需要加个域名，使用谷歌IP。
m-dot-betaspike.appspot.com

**Comment by lrinQVQ** [comment]
这个有了https://github.com/racaljk/hosts/blob/master/hosts#L566

**Comment by sy618** [comment]
这三个是重复了。
      2 api.pinterest.com
      2 s-media-cache-ak0.pinimg.com
      2 s.pinimg.com

以下四个都是与广告相关，建议去除。不然广告会被加载出来。
      2 syndication.twitter.com   推特广告
      2 www.googleadservices.com  谷歌广告相关
      2 www.googletagmanager.com
      2 apkpure.disqus.com    apkpure的广告

**Comment by lrinQVQ** [comment]
@sy618 广告去掉这个真心不好= = 别人也是要盈利的啊

**Comment by lrinQVQ** [comment]
syndication.twitter.com 有一个是cdn 2333

**Comment by lrinQVQ** [comment]
www.googleadservices.com我这就一个0.0

**Comment by paperbag** [comment]
syndication.twitter.com 不是广告吧
apkpure.disqus.com 这个是 Disqus 的评论 @sy618

**Comment by paperbag** [comment]
www.googletagmanager.com 这个也不是广告，这个是谷歌的代码管理器 @sy618

**Comment by Too-Naive** [comment]
![](https://cloud.githubusercontent.com/assets/16496671/20557321/f47b3c50-b1a5-11e6-8810-8edc50a65778.png)

**Comment by sy618** [comment]
@paperbag  @Too-Naive
OK，我重新验证了下，那几个确实不是广告。那么我会在AD hosts里去除。

**Comment by Ir1d** [comment]
原则上不进行屏蔽广告？

**Comment by lrinQVQ** [comment]
是的orz原则上仅提供被墙域名hosts 不屏蔽广告

**Comment by sy618** [comment]
这样专注于FQ的hosts挺好。
需要去广告的可以用vokins的源 。

**Comment by lrinQVQ** [comment]
是啊orz 个人觉得这个项目还是得有一个比较准确的定位
但是如果只有谷歌的hosts又太单一了
个人觉得还是做一个中国无法访问的所有网站的hosts比较好

**Comment by paperbag** [comment]
www.googletagmanager.com 这个其实可以移除，这个域名谷歌针对中国大陆用户是解析到它在北京和上海的 IP 地址，本身访问是没问题的

On March 14, 2017 8:21:53 AM GMT+08:00, sy618 <notifications@github.com> wrote:
>这样专注于FQ的hosts挺好。
>需要去广告的可以用vokins的源 。
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/racaljk/hosts/issues/1007#issuecomment-286284328

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
