### ISSUE TITLE
新建了一个Linux下更新hosts的页面

### ISSUE THREAD

**Issue by lishoujun** [racaljk/hosts#1015]
https://github.com/racaljk/hosts/wiki/Linux%E4%B8%8B%E6%9B%B4%E6%96%B0hosts
新建了一个Linux下更新hosts的页面，有不当之处请直接编辑

**Comment by imknown** [comment]
帮你 改进了一下 mkdn 格式..

**Comment by aofall** [comment]
wget https://raw.githubusercontent.com/racaljk/hosts/master/tools/lhosts | sh
