### ISSUE TITLE
googleapis.com net::ERR_CONNECTION_CLOSED

### ISSUE THREAD

**Issue by weilantian** [racaljk/hosts#1017]
![lalala](https://cloud.githubusercontent.com/assets/13176782/23939291/f9127862-099a-11e7-8ab0-93bfb860e912.PNG)

**Comment by imknown** [comment]
https://ajax.googleapis.com/ajax/libs/angularjs/1.4.5/angular.min.js
打不开?

**Comment by lrinQVQ** [comment]
能正常打开

**Comment by woyaojizhu8** [comment]
我也打不开

**Comment by lrinQVQ** [comment]
一切正常欸
