### ISSUE TITLE
tumblr 视频无法播放

### ISSUE THREAD

**Issue by Mao-jiawei** [racaljk/hosts#1018]
视频都成二级域名了

**Comment by lrinQVQ** [comment]
哇

**Comment by lrinQVQ** [comment]
没问题啊 都添加了的

**Comment by Mao-jiawei** [comment]
主页上的视频都没法播放
比如：aaa分享的视频   先会解析https://aaa.tumblr.com  然后再从vtt.tumblr.com或者vt.media.tumblr.com获取视频源

**Comment by lrinQVQ** [comment]
我看看啧

**Comment by lrinQVQ** [comment]
216.115.100.126 static.tumblr.com

**Comment by Mao-jiawei** [comment]
还是不行额(⊙o⊙)…  
连接
https://用户名.tumblr.com  时失败

总不能关注的所有人  加到hosts里吧

**Comment by Mao-jiawei** [comment]
static.tumblr.com  是做什么用的
 
这个域名怎么找到的

**Comment by lrinQVQ** [comment]
F12 Network @Mao-jiawei 估计真的得所有人都加 不能*

**Comment by 10089** [comment]
为什么非得用 hosts 访问呢？免费的爬梯一大堆   如GAE代理、蓝灯、谷歌一年的GCE 搭建SS，付费的自己搭建SS

**Comment by 10089** [comment]
话说此 hosts中的tumblr.com 早已废了 试试下面的 Yahoo 全家桶 还容易维护
_180.222.100.22    tw.money.yahoo.com
116.214.10.132    tw.bid.yahoo.com
27.123.201.252    tw.finance.yahoo.com
116.214.11.98     hk.mobi.yahoo.com
116.214.11.98     tw.mobi.yahoo.com
216.39.54.209     hk.knowledge.yahoo.com
216.39.54.209     tw.knowledge.yahoo.com
124.108.101.57    www.yahoo.com
124.108.101.57    video.yahoo.com
124.108.101.57    hk.finance.yahoo.com
124.108.101.57    hk.answers.yahoo.com
124.108.101.57    tw.answers.yahoo.com
124.108.101.57    hk.yahoo.com
124.108.101.57    tw.yahoo.com
124.108.101.57    hk.m.yahoo.com
124.108.101.57    tw.m.yahoo.com
124.108.101.57    hk.news.yahoo.com
124.108.101.57    tw.news.yahoo.com
124.108.101.57    y-flickr.yahoo.com
124.108.101.57    m.flickr.com
124.108.101.57    www.flickr.com
124.108.101.57    api.flickr.com
124.108.101.57    up.flickr.com
124.108.101.57    secure.flickr.com
124.108.101.57    bup.flickr.com
124.108.101.57    csync.flickr.com
124.108.101.57    csp.flickr.com
124.108.101.57    embedr.flickr.com
124.108.101.57    widgets.flickr.com
124.108.101.57    downloadr.flickr.com
124.108.101.57    developer.flickr.com
124.108.101.57    bup-resume.flickr.com
124.108.101.57    p1.staticflickr.com
124.108.101.57    p2.staticflickr.com
124.108.101.57    p3.staticflickr.com
124.108.101.57    p4.staticflickr.com
124.108.101.57    p5.staticflickr.com
124.108.101.57    p6.staticflickr.com
124.108.101.57    p7.staticflickr.com
124.108.101.57    p8.staticflickr.com
124.108.101.57    c1.staticflickr.com
124.108.101.57    c2.staticflickr.com
124.108.101.57    c3.staticflickr.com
124.108.101.57    c4.staticflickr.com
124.108.101.57    c5.staticflickr.com
124.108.101.57    c6.staticflickr.com
124.108.101.57    c7.staticflickr.com
124.108.101.57    c8.staticflickr.com
124.108.101.57    www.tumblr.com
124.108.101.57    api.tumblr.com
124.108.101.57    24.media.tumblr.com
124.108.101.57    25.media.tumblr.com
124.108.101.57    31.media.tumblr.com
124.108.101.57    33.media.tumblr.com
124.108.101.57    37.media.tumblr.com
124.108.101.57    38.media.tumblr.com
124.108.101.57    55.media.tumblr.com
124.108.101.57    56.media.tumblr.com
124.108.101.57    57.media.tumblr.com
124.108.101.57    58.media.tumblr.com
124.108.101.57    68.media.tumblr.com
124.108.101.57    90.media.tumblr.com
124.108.101.57    91.media.tumblr.com
124.108.101.57    92.media.tumblr.com
124.108.101.57    vt.media.tumblr.com
124.108.101.57    v.tumblr.com
124.108.101.57    vt.tumblr.com
124.108.101.57    vtt.tumblr.com
124.108.101.57    d.yimg.com
124.108.101.57    e.yimg.com
124.108.101.57    h.yimg.com
124.108.101.57    l.yimg.com
124.108.101.57    p.yimg.com
124.108.101.57    s.yimg.com
124.108.101.57    s1.yimg.com
124.108.101.57    s2.yimg.com
124.108.101.57    s3.yimg.com
124.108.101.57    sec.yimg.com
124.108.101.57    assets.tumblr.com
124.108.101.57    secure.assets.tumblr.com
69.147.76.173     downloads.flickr.com
69.147.76.173     flickr.com
106.10.137.23     static.flickr.com
106.10.137.23     farm1.staticflickr.com
106.10.137.23     farm2.staticflickr.com
106.10.137.23     farm3.staticflickr.com
106.10.137.23     farm4.staticflickr.com
106.10.137.23     farm5.staticflickr.com
106.10.137.23     farm6.staticflickr.com
106.10.137.23     farm7.staticflickr.com
106.10.137.23     farm8.staticflickr.com
106.10.137.23     farm9.staticflickr.com
192.0.79.32       code.flickr.com
66.6.33.31        tumblr.com
66.6.33.21        t.tumblr.com
66.6.33.21        staff.tumblr.com
66.6.33.21        support.tumblr.com
66.6.32.162       px.srvcs.tumblr.com
66.6.32.162       ls.srvcs.tumblr.com
66.6.32.162       saber.srvcs.tumblr.com
66.6.33.25        bf2.origin.tumblr.com
54.230.75.152     media.tumblr.com
54.230.75.152     platform.tumblr.com
54.230.75.152     static.tumblr.com
54.230.75.152     secure.static.tumblr.com
54.230.75.152     embed.tumblr.com
54.230.75.152     assets.txmblr.com
54.230.75.152     96.media.tumblr.com
192.229.237.98    40.media.tumblr.com
192.229.237.98    46.media.tumblr.com
192.229.237.98    49.media.tumblr.com
192.229.237.98    66.media.tumblr.com
192.229.237.98    97.media.tumblr.com
128.127.159.1     94.media.tumblr.com
184.51.15.142      95.media.tumblr.com
151.101.76.249    98.media.tumblr.com
209.197.3.20      99.media.tumblr.com
162.88.175.18     dyn.mx.tumblr.com
192.229.237.97    mx.tumblr.com_

**Comment by lrinQVQ** [comment]
啧并没有废了啊

**Comment by 10089** [comment]
多说无益，不用代理你试试这个视频
https://vt.tumblr.com/tumblr_oga4skPTYE1qgxh8k_480.mp4

**Comment by lrinQVQ** [comment]
@10089 无压力

**Comment by lrinQVQ** [comment]
@10089 = =LEDE + ChinaDNS + dns-forwarder 基本上不需要代理和hosts orz

**Comment by lrinQVQ** [comment]
216.115.100.126 t2.ycpi.vip.swb.yahoo.com
216.115.100.125 t1.ycpi.vip.swb.yahoo.com
216.115.100.126 vt.tumblr.com
效果挺好233

**Comment by 10089** [comment]
用贵项目中的 hosts 真的能打开上面的视频吗？
开来你的网络 Very good
这不是聊天室在此  [issue](https://github.com/racaljk/hosts/issues/1018) 中本人的最后一个回复

**Comment by lrinQVQ** [comment]
@10089 不啊 我自己修改的hosts

**Comment by Mao-jiawei** [comment]
@10089  hosts不用花钱啊  免费的梯子 没一个好用的

**Comment by Mao-jiawei** [comment]
@lrinQVQ   手机app 使用没问题  现在就web视频播放不行  应该是最近改动的   tumblr  使用的是nginx做的负载均衡

**Comment by Mao-jiawei** [comment]
@lrinQVQ   hosts不支持 通配符 要不然还是有的搞

**Comment by lrinQVQ** [comment]
是啊orz

**Comment by 10089** [comment]
再回复一次  @Mao-jiawei 我从来 没有说 Hosts 不好，只不过贵仓库中的 yahoo 存在颇多问题，如yahoo 的很多IP 被指定到美国，绕地球大半圈，本来去美国的线路就拥挤，导致丢包率大增，为什么不指定到台湾或韩国呢？有的Tumblr视频能播放很卡吧，部分视频没法观看吧，还有flickr 相册APP也没法同步吧？试试上面我发的   


 免费的梯子 没一个好用的？这个我不跟你争辩 ,论坛里很多大神笑而不语

**Comment by lrinQVQ** [comment]
@10089 okok我去换香港或者台湾ip 不要撕了==

**Comment by Mao-jiawei** [comment]
@lrinQVQ 哈哈   不用管这些挑刺的  我都是自己换成韩国的ip

**Comment by Too-Naive** [comment]
想要好用 不就得付钱吗。。。
不付钱怎么可能会有好用的东西
羊毛出在羊身上
天下没有免费的午餐

**Comment by Mao-jiawei** [comment]
是的是的

**Comment by summercoolronnie** [comment]
所以还是只有把所有的关注的人加上去啊？

**Comment by hetykai** [comment]
好像有个acrylic dns支持通配符hosts

**Comment by lrinQVQ** [comment]
来自instagram的视频也修复了xd

**Comment by lrinQVQ** [comment]
vtt.tumblr.com 的一直还能用
