### ISSUE TITLE
能给一个卡通农场的hosts吗

### ISSUE THREAD

**Issue by lupin92** [racaljk/hosts#1019]
就是游戏啊  hayday

**Comment by lupin92** [comment]
联通网有的时候 有问题   就进不去了   好卡啊

**Comment by lrinQVQ** [comment]
啧

**Comment by lupin92** [comment]
现在不卡了  就是有时候联通搞一下  麻烦的话  就别搞了  谢谢你哈

**Comment by lupin92** [comment]
我是转成surge用的hosts添加进surge上google那些，wifi网通好慢，用移动网就超级快  真是日了

**Comment by lrinQVQ** [comment]
抓包了一些 这是亚马逊EC2的服务器 你懂

**Comment by lupin92** [comment]
亚马逊EC2的服务器不懂  像hosts那样就会了。。。抓在哪呢   今天傍晚的时候进游戏又卡了

**Comment by lrinQVQ** [comment]
![screenshot_20170317-215745](https://cloud.githubusercontent.com/assets/12861134/24046229/d94717b2-0aef-11e7-9f94-0e11dca6a78b.png)
国内的EC2延迟超高不稳定而且时不时被gfw干扰

**Comment by lupin92** [comment]
不好意思啊     邮件没提示  来晚了
哦   原来这样啊

**Comment by lrinQVQ** [comment]
没事2333

**Comment by lupin92** [comment]
亲  还要麻烦你一下
我用手机4G网打开surge   DNs results里给力一些地址
我用全能扫描王扫出来了  转成surge用的
# hayday start
e.crashlytics.com = 23.21.245.236
settings.crashlytics.com = 184.73.203.162
service.supercell.net = 50.19.222.32,50
service.gc.apple.com = 17.173.254.50
supercell.helpshift.com = 50.18.188.144
1681.engine.mobileapptracking.com = 54.92.2.152
sp.itunes.apple.com = 223.111.212.157
events3alt.adcoIony.com = 34.194.90.39
init.itunes.apple.com = 120.221.65.233
iosads24.adcolony.com = 54.174.97.247
itunes.apple.com = 120.221.65.233
p50-buy.itunes.apple.com = 17.173.66.101
game.haydaygame.com = 54.161.225.210
# hayday end
添加进去用不卡了   还是很流利
【问】：
这些地址安全吗？不会看。。。

**Comment by lrinQVQ** [comment]
@lupin92 这些本来全是ec2服务器的
lrin@lrinQVQ  ~  tcpping e.crashlytics.com
seq 0: tcp response from ec2-107-22-184-200.compute-1.amazonaws.com (107.22.184.200) [open]  0.612 ms
seq 1: tcp response from ec2-107-22-180-95.compute-1.amazonaws.com (107.22.180.95) [open]  0.665 ms
seq 2: tcp response from ec2-23-21-57-50.compute-1.amazonaws.com (23.21.57.50) [open]  0.611 ms
seq 3: tcp response from ec2-174-129-13-10.compute-1.amazonaws.com (174.129.13.10) [open]  0.602 ms

**Comment by lupin92** [comment]
这玩意儿杂用

**Comment by lrinQVQ** [comment]
@lupin92 直接添加hosts里面去就好233

**Comment by lrinQVQ** [comment]
比如
23.21.245.236  e.crashlytics.com

**Comment by lupin92** [comment]
好的  谢谢
