### ISSUE TITLE
google 的ping值好高

### ISSUE THREAD

**Issue by still-ben** [racaljk/hosts#102]
更新了最新的hosts以后，打开google系的网站都要转好久才能打开。
ping主机发现延迟有点高啊。
可有良策，良辰先行谢过！

![_009](https://cloud.githubusercontent.com/assets/12825822/11265219/7ee48bde-8ed5-11e5-8aea-5a692f7c2f38.png)

**Comment by mklnz** [comment]
I have the same problem, can someone find a better IP for Google please? 
I wonder if anyone has some sort of script that automatically pings Google's subnets to find unblocked IPs.
Thanks.

**Comment by K-Guan** [comment]
@mklnz Well, just want to remove that *Thanks.* But then I realized that here's not StackOverflow.

**Comment by CNMan** [comment]
这个IP是美国东部的，ping高正常
![2015-11-19_180052](https://cloud.githubusercontent.com/assets/8692234/11267714/ebd38102-8ee7-11e5-95e2-5cd9a9e054c6.png)

**Comment by aofall** [comment]
@CNMan ……如果我没记错的话这个是官方俄罗斯的IP
从封锁趋势变严了之后你就该知道这是早晚要面对的事，要想速度快还得自己找代理。用着免费的东西还能求什么呢。
