### ISSUE TITLE
能否添加bitbucket.org的host？

### ISSUE THREAD

**Issue by yugasun** [racaljk/hosts#1025]
最近开始使用Bitbucket，但是家里访问巨慢，好多跟国外合作的项目都在bitbucket.org上面，拜托楼主帮帮忙~

**Comment by lrinQVQ** [comment]
0.0 我先看看

**Comment by yugasun** [comment]
感谢楼主这么晚还回复，没办法个人用github还行，但是客户用的bitbucket

**Comment by lrinQVQ** [comment]
@yugasun 没事233 我去看看

**Comment by lrinQVQ** [comment]
貌似Bitbucket和github类似...我去看看能不能找到好点的

**Comment by lrinQVQ** [comment]
https://confluence.atlassian.com/bitbucket/what-are-the-bitbucket-cloud-ip-addresses-i-should-use-to-configure-my-corporate-firewall-343343385.html

**Comment by yugasun** [comment]
@lrinQVQ 非常感谢

**Comment by lrinQVQ** [comment]
@yugasun 你可以一个一个测试下233

**Comment by lrinQVQ** [comment]
主站只有104.192.143.1
104.192.143.2
104.192.143.3
104.192.143.65
104.192.143.66
104.192.143.67
如果是客户端的话弄下API地址

**Comment by yugasun** [comment]
@lrinQVQ 是不是这些ip我都需要绑定到bitbucket.org?

**Comment by yugasun** [comment]
@lrinQVQ 好的，我自己测试绑定下

**Comment by yugasun** [comment]
@lrinQVQ 测试完了，选了两个相对快的ip，但是实际访问还是很慢，😂
```hosts
# Bitbucket
104.192.143.67 bitbucket.org
104.192.143.6 api.bitbucket.org
```

**Comment by lrinQVQ** [comment]
心疼233

**Comment by lrinQVQ** [comment]
@yugasun 这个就跟github一样233无法解决的

**Comment by xuexb** [comment]
心疼233

**Comment by yugasun** [comment]
@xuexb 已买vpn，有空了，自己再买个vps自己搭
