### ISSUE TITLE
disqus的部分二级域名访问不了

### ISSUE THREAD

**Issue by oilbottle** [racaljk/hosts#1027]
比如，***.disqus.com/admin

**Comment by imknown** [comment]
`243.185.187.39` 试试

**Comment by oilbottle** [comment]
访问速度变快，但是对于某些页面还是打不开。*代表在disqus上设置的自己网站的短名。

**Comment by lrinQVQ** [comment]
有哪些域名发一下= =

**Comment by oilbottle** [comment]
每个账号不一样啊，应该是除了www.disqus.com以外的其他二级域名都不行吧。如果找不到hosts的话就算了

**Comment by lrinQVQ** [comment]
*.digits.com的IP倒是有但是= =没法通配的

**Comment by lrinQVQ** [comment]
c.disquscdn.com
a.disquscdn.com
media.disquscdn.com
api.mixpanel.com
cdn.mxpnl.com
@oilbottle  F12看下是不是这些域名没法加载= =
