### ISSUE TITLE
tensorflow.org 的 ip 有错误

### ISSUE THREAD

**Issue by zepinglee** [racaljk/hosts#1029]
当我用该hosts时，点击 tensorflow.org 其他页面时经常会跳转出错；

注释掉 tensorflow.org 那一行后正常

**Comment by DDoSolitary** [comment]
我这里似乎没问题？
描述具体一点吧。。

**Comment by zepinglee** [comment]
我配置了该hosts，然后上tf，结果是一个过时的页面（传不上来，你可以注意到最上面一栏是 “get started, tutorials, how to, mobile...”）,而且如果我点击 [tutorials](https://www.tensorflow.org/tutorials)，它会跳转到 https://www.tensorflow.org/versions/r0.12/tutorials/index.html ，而且经常会出错。

而我用自己的vpn上tensorflow的时候，是 1.0 发布后的最新页面（最上面是“install, develop, api r1.0, deploy...”）

**Comment by DDoSolitary** [comment]
好像真的欸。。然而我并没有什么办法。。
