### ISSUE TITLE
你好，请问能否把https://play.google.com/music  hosts加上去啊。谢谢！

### ISSUE THREAD

**Issue by wh9007** [racaljk/hosts#1031]
你好，请问能否把https://play.google.com/music  hosts加上去啊。谢谢！

**Comment by DDoSolitary** [comment]
本来就有的啊。。
https://github.com/racaljk/hosts/blob/master/hosts#L914

**Comment by sy618** [comment]
他应该是说https://play.google.com/music这网站打开异常，我看了下，是因为域名缺失造成，加这个就好了。
61.91.161.217 play-music.gstatic.comt

**Comment by DDoSolitary** [comment]
@sy618 你说得有道理。。之前看的时候开着代理，所以没注意到。。

**Comment by wh9007** [comment]
可我电脑仍然打不开.说是地区受限!

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

发件人: DDoSolitary<mailto:notifications@github.com>
发送时间: 2017年3月25日 8:01
收件人: racaljk/hosts<mailto:hosts@noreply.github.com>
抄送: 陶醉<mailto:wh-9007@live.cn>; Author<mailto:author@noreply.github.com>
主题: Re: [racaljk/hosts] 你好，请问能否把https://play.google.com/music hosts加上去啊。谢谢！ (#1031)


本来就有的啊。。
https://github.com/racaljk/hosts/blob/master/hosts#L914

―

**Comment by DDoSolitary** [comment]
@wh9007 说明这个服务本来就是锁区的咯

**Comment by DDoSolitary** [comment]
@wh9007
Google Play的很多付费服务似乎都是有地区限制的，参见：https://support.google.com/googleplay/answer/2843119
我过上美国代理就能正常打开了

**Comment by DDoSolitary** [comment]
@wh9007 似乎挂上美国代理正常打开一次后，断掉代理用hosts访问也能上了。。有趣。。

**Comment by wh9007** [comment]
为什么我的还是不行呢.
能教教我如何自制hosts文件嘛!

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

发件人: DDoSolitary<mailto:notifications@github.com>
发送时间: 2017年3月26日 19:41
收件人: racaljk/hosts<mailto:hosts@noreply.github.com>
抄送: 陶醉<mailto:wh-9007@live.cn>; Mention<mailto:mention@noreply.github.com>
主题: Re: [racaljk/hosts] 你好，请问能否把https://play.google.com/music hosts加上去啊。谢谢！ (#1031)


@wh9007<https://github.com/wh9007> 似乎挂上美国代理正常打开一次后，断掉代理用hosts访问也能上了。。有趣。。

―

**Comment by DDoSolitary** [comment]
@wh9007 可是我这里可以啊，我还试了用美国代理访问一次以后再用其他不支持的地区的代理访问，也是可以的。。话说我这里开了代理以后会自动忽略hosts文件，不知道是不是这个缘故
hosts文件的制作听说@lrinQVQ近期会发教程

@lrinQVQ 我刚刚才发现您ID的第一个字母是l不是I。。非等宽字体毁一生啊。。

**Comment by lrinQVQ** [comment]
周二我去写完
