### ISSUE TITLE
今天开始google好像开始屏蔽国内IP了，chrome更新会显示由于在此国家/地区的访问权限遭到限制，安装失败。扩展也装不了，请问这个能解决吗

### ISSUE THREAD

**Issue by OneCanType** [racaljk/hosts#1036]
如题

**Comment by OneCanType** [comment]
但是google能正常访问

**Comment by OneCanType** [comment]
@imknown 请问要怎么设置呢，google的位置信息不是自动确定无法修改的吗

**Comment by imknown** [comment]
你尝试都改改 能改的都改一下试试 我也不确定 改完就会没问题额

**Comment by OneCanType** [comment]
@imknown 确定了一下，改不了位置的。。根本没有这个选项。。之前有听说在googleplay里非国区买东西后会锁在某个区里，不知道对帐号位置有没有影响。总之不太清楚谷歌到底是怎么确定位置的。。

**Comment by imknown** [comment]
Play 买东西只改 hosts 应该是不行. 但是 Chrome 插件商店 我这里确实没有这个 区域校验.

**Comment by XiGou** [comment]
我也是啊 ，教育网，v6 ，今天刚发现不能更新以及下载插件。
由于在此国家/地区的访问权限遭到限制，安装失败。（错误代码为：7: 0x80040806 -- system level）

**Comment by DDoSolitary** [comment]
我用的是英文版，显示的是Download interrupted
应该和账号的地区设置没关系，我的Google账号是不久前才注册的，我没记错的话地区相关我都选US的

**Comment by DDoSolitary** [comment]
挂上代理似乎就没问题了

**Comment by lrinQVQ** [comment]
貌似因为泰国的问题

**Comment by jianghao1123** [comment]
我也是添加扩展程序 老是Download interrupted

**Comment by imknown** [comment]
为啥我可以 😭

**Comment by sy618** [comment]
https://www.v2ex.com/t/350378#reply32
似乎是谷歌在服务器端对中国地区限制的。

**Comment by lrinQVQ** [comment]
kStatusRestrictedExportCountry

**Comment by wolfan** [comment]
嘤嘤，难怪今天重装系统后Chrome安装不上，最后跑百度下了个，同步插件又不行，我还以为是度娘家下的有问题。


这下方了，没得插件办事困难啊。。


另外，问下是不是aws的github不稳定，怎么我从git-scm下载总是不行。。

**Comment by derekwei** [comment]
目前可以采用下载[离线安装包](https://www.google.com/chrome/browser/desktop/index.html?system=true&standalone=1)的方式手动更新

**Comment by laodcn** [comment]
据说谷歌因为赛门铁克发布了3万个错误证书 将其限制访问，根据测试，除了使用运营商反代才可以更新、安装插件，谷歌自家ip目前不行，鉴于本项目只容许用官方ip，我只在这里列出，安全性自行需要的自取：
219.76.4.14 tools.google.com
219.76.4.14 clients2.google.com

**Comment by OneCanType** [comment]
@laodcn 
今天测试已经完全正常了。而且还没有用到你刚才提供的两个IP，应该是官方修复了该问题
