### ISSUE TITLE
https://laod.cn/hosts/2017-google-hosts.html 这个老D博客和你们什么关系？

### ISSUE THREAD

**Issue by zhuweijia** [racaljk/hosts#1043]
https://laod.cn/hosts/2017-google-hosts.html
发现上面的博客里使用的hosts，是取自这里的，不知道是不是属于非法盗用了，你们知道这个情况吗

**Comment by laodcn** [comment]
😊

**Comment by lrinQVQ** [comment]
怎么说呢2333
laod hosts里面没有删除掉项目的声明 版权等等
楼上laod本人也在为本项目做贡献
并且博文中也有
"致谢：
Github项目维护者 @racaljk @andytimes @Too-Naive @K-Guan @imcaffrey @smounives @lautis0503 @aofall @davymai  @Ignotus-CN @cw881014 等等…
感谢网上那些无名的英雄们！感谢那些批评、指责、攻击、帮助、支持过老D博客的人们！"
按照本项目的协议

本项目的hosts，README.MD，wiki等资源基于 CC BY-NC-SA 4.0 这意味着你可以拷贝、并再发行本项目的内容，
但是你将必须同样提供原作者信息以及协议声明。同时你也不能将本项目用于商业用途，按照我们狭义的理解
(增加附属条款)，凡是任何盈利的活动皆属于商业用途。

laod的博文中有捐赠链接 这点上和最后一条有一些歧义

**Comment by laodcn** [comment]
捐赠链接，每个月二三十，也不够我服务器的支出，如果你不喜欢，我可以去掉。

**Comment by lrinQVQ** [comment]
@laodcn 没必要的啦2333 我只是客观分析 你服务器也是需要钱来维护的

**Comment by imknown** [comment]
issues 里面好有好多~黑历史~ =_ =...

**Comment by lrinQVQ** [comment]
@imknown 关于laod的挺多的233

**Comment by laodcn** [comment]
然而网上还有好多不署名的有木有

**Comment by lrinQVQ** [comment]
确实233

**Comment by zhuweijia** [comment]
好的，这个怪我，没了解清楚。多多包含

**Comment by lrinQVQ** [comment]
没事233搞懂就行233

**Comment by Too-Naive** [comment]
→_→一個無關的話題 老D居然有備案！

**Comment by Ir1d** [comment]
@zhuweijia 感谢反馈
