### ISSUE TITLE
请求  https://github-cloud.s3.amazonaws.com 的支持

### ISSUE THREAD

**Issue by wolfan** [racaljk/hosts#1047]
重作系统，没留备份，现在下个Git都下不到，嘤嘤……

**Comment by lrinQVQ** [comment]
欸有啊 https://github.com/racaljk/hosts/blob/master/hosts#L43

**Comment by wolfan** [comment]
@lrinQVQ 可是俺这总是丢，看来我还是度娘家随便拖个回家先用着好了……

果然下回要装个Linux……

**Comment by lrinQVQ** [comment]
@wolfan 心疼你QAQ 不过国内亚马逊是真的无解

**Comment by Too-Naive** [comment]
用代理

**Comment by fuzhaohao** [comment]
`https://npm.taobao.org/mirrors/git-for-windows`
针对git-for-windows，可以用淘宝镜像 :blush:

**Comment by lightjameslyy** [comment]
我也遇到这个问题了，用这个解决的：
https://www.mobibrw.com/2017/6047

**Comment by wolfan** [comment]
@lightjameslyy 实测有效。

**Comment by lrinQVQ** [comment]
友情提示
219.76.4.4不是官网IP
