### ISSUE TITLE
这个项目的分组 该整理整理 合并合并?

### ISSUE THREAD

**Issue by imknown** [racaljk/hosts#1049]
例如:
https://github.com/racaljk/hosts/blob/master/hosts#L900
https://github.com/racaljk/hosts/blob/master/hosts#L2357-L2359
https://github.com/racaljk/hosts/blob/master/hosts#L2874

~~强迫症的~~ 我 感觉有点分散了..

**Comment by lrinQVQ** [comment]
233好主意

**Comment by racaljk** [comment]
我懒癌晚期了，等一个好心人

**Comment by imknown** [comment]
怎么个维度是好, 是按照 `单纯域名` 排序, 还是 `网站相关性` 组合?

**Comment by racaljk** [comment]
我倾向于后者

**Comment by DDoSolitary** [comment]
感觉有点乱+1，然而类似地方好像很多，总觉得是有生之年系列。。

**Comment by lrinQVQ** [comment]
正在整理orz
https://github.com/racaljk/hosts/commit/452d834069f5c5d4e2593a0951a758d7016537dc
你们看看这样如何满足相关性和字母顺序@racaljk
@imknown 
@DDoSolitary

**Comment by ARROWBOW** [comment]
# 大神是怎么把这些地址给整合到一起的#

**Comment by imknown** [comment]
@ARROWBOW https://github.com/racaljk/hosts/issues/1142 参考一下这个
