### ISSUE TITLE
很好奇这些ip是如何扫出来的？

### ISSUE THREAD

**Issue by out0fmemory** [racaljk/hosts#1051]
你好，有2点比较好奇
1、这些ip是如何扫出来的？
2、好奇这些ip是否全是官方ip？？是否存在某些镜像站，比如一个转发实现的facebook镜像（如果存在，这种方式的访问其实是不安全的）

**Comment by lrinQVQ** [comment]
IP WHOIS查IP 关于获取IP有点忙 忙完了放出教程

**Comment by out0fmemory** [comment]
thks，因为按照目前的情况，gfw基本上是组合拳了，dns污染、ip封锁，数据监听修改各种方法都用的，理论上只处理dns污染问题已经不能解决问题了

**Comment by coalchan** [comment]
期待

**Comment by racaljk** [comment]
ISSUE LIST有一堆，可以参见 #685 
另外 @lrinQVQ 可以教你，快去找他！

**Comment by out0fmemory** [comment]
哪些issuse没有解决问题呀。。。。。。。就这个有必要这么藏着掖着？授之以鱼不如授之以渔。。。。。。而且，如何保证这里的ip不是有人挂来钓鱼的（mirror + 监听）？？？
