### ISSUE TITLE
请在youtube部分增加redirector.googlevideo.com

### ISSUE THREAD

**Issue by gonel001** [racaljk/hosts#1052]
redirector.googlevideo.com只需要使用跟youtube 一样的ip即可。
这样再配合dnscrypt 就能正确解析redirector.googlevideo.com返回的视频地址。

**Comment by mraandtux** [comment]
建议找到IP后添加至dnsmasq配置文件

**Comment by gonel001** [comment]
感觉你误解了我的意思，我的意思是在您这相项目的hosts 中增加一条redirector.googlevideo.com的ip如附件中图片的样式

2017-03-31 16:12 GMT+08:00 Mr a <notifications@github.com>:

**Comment by ZhyMC** [comment]
试了一下,会返回带googlevideo的地址,这个地址就算泛解析到youtube.com一样的ip也无法看视频

**Comment by gonel001** [comment]
并不是不可以播放，而是返回的这个带googlevideo的地址，一般是s1---dnq7v.googlevideo.com
这类的地址，需要配合dnscrypt就可以正确解析，就可以播放。

2017-04-02 3:11 GMT+08:00 ZhengHuaiYu <notifications@github.com>:

**Comment by ZhyMC** [comment]
@gonel001 我正在写工程,看到类似这样的地址s1---dnq7v.googlevideo.com,怎么搞都无法正确播放.有兴趣一起研究吗

**Comment by gonel001** [comment]
我对这个问题也很感兴趣，因为我发现在youtube上一个视频对应的这类地址并不只一个，*.googlevideo.com
这类地址，应该是起类似CDN的作用，网页版的youtube在通过redirector返回的*.googlevideo.com
不能播放时，会重新请求返回另一个不同的*.googlevideo.com
的地址，配合dnscrypt使用时，大多时候是可以播放的。具体还没有深入的跟踪研究。

2017年4月2日星期日，ZhengHuaiYu <notifications@github.com> 写道：

**Comment by ZhyMC** [comment]
@gonel001 我发现一个黑科技,http://www.cutedns.cn/,这个dns就是解决googlevideo的问题了,换完dns直接全面翻墙,4k流畅,有点夸张

**Comment by gonel001** [comment]
这个站竟然不提供https访问，估计也很快就会被墙掉吧。赶紧先收藏下。此站最好赶紧加入dnscrypt，这样比较保险。

2017-04-02 21:14 GMT+08:00 ZhengHuaiYu <notifications@github.com>:

**Comment by ZhyMC** [comment]
@gonel001 有没有QQ,我昨晚nodejs写了个dns,用的这个工程的hosts,就是没解决googlevideo问题.可以一起研究一下

**Comment by gonel001** [comment]
不好意思，最好还是邮件吧。

2017年4月2日星期日，ZhengHuaiYu <notifications@github.com> 写道：

**Comment by zhqiao** [comment]
cutedns.cn这个DNS安全性怎么样? 万一DNS干起坏事就全乱套了

**Comment by gonel001** [comment]
cutedns.cn已经挂了，转行做vpn了

2017-04-13 20:43 GMT+08:00 zhqiao <notifications@github.com>:
