### ISSUE TITLE
hosts+（bind/dnsmasq....)

### ISSUE THREAD

**Issue by tianrking** [racaljk/hosts#1053]
有没有什么方案可以将dnsmasq与这个hosts结合起来 开放25端口做公共DNS服务器运行在外国VPS上供终端上网? 自己尝试过 但是效果不理想 ，总是使用几次后便在国内无法完成解析

**Comment by Too-Naive** [comment]
#660 #394

**Comment by CNMan** [comment]
等unbound 下个版本支持[dnscrypt](https://github.com/Cofyc/dnscrypt-wrapper)协议了，就可以用 https://github.com/racaljk/hosts/issues/930 的方法建在国外VPS了，目前还是需要建在国内VPS上
