### ISSUE TITLE
请把 Github 相关的 host 移除，不使用 host 访问 Github 反而更快。

### ISSUE THREAD

**Issue by mcxinyu** [racaljk/hosts#1055]
请把 Github 相关的 host 移除，不使用 host 访问 Github 反而更快。

**Comment by imknown** [comment]
就 一个 `gist.github.com` 吧?

**Comment by Too-Naive** [comment]
https://github.com/racaljk/hosts/blob/master/hosts#L43-L44

**Comment by erDaren** [comment]
gist.github.com 不用host 是无法访问的

**Comment by Wows233** [comment]
亚马逊的是不能直接访问的。github不需要用hosts，也没有这个条目。gist.github.com被封杀了
