### ISSUE TITLE
为啥输入11不行了呢

### ISSUE THREAD

**Issue by dreamchaser123** [racaljk/hosts#1056]
请问刚才我在choose里先输了4，然后等他reset成功后，又输了11，就用不了了，重启也没用
![250831543937130807](https://cloud.githubusercontent.com/assets/26835325/24577808/b13f2f42-1707-11e7-972e-a05704263505.png)
可以打开，但是一输入11就不行

**Comment by dreamchaser123** [comment]
而且输入9也出现这样的情况

**Comment by Too-Naive** [comment]
....你不应该到程式写的地方来提issue吗。。

**Comment by Too-Naive** [comment]
我看了以下代码。。原因很简单 我没有把11改成12..

**Comment by imknown** [comment]
@Too-Naive 应该 把 https://github.com/racaljk/hosts/tree/master/tools 删掉, 然后用 `git submodule` 引入.

**Comment by Too-Naive** [comment]
![](https://cloud.githubusercontent.com/assets/16496671/20557321/f47b3c50-b1a5-11e6-8810-8edc50a65778.png)歷史問題

**Comment by dreamchaser123** [comment]
@Too-Naive 没看懂您在说什么，是在说要输入12么

**Comment by Too-Naive** [comment]
是 沒法輸12... 要改代碼然後重新編譯

**Comment by dreamchaser123** [comment]
@Too-Naive 不明觉厉，谢谢了
