### ISSUE TITLE
建议出DNSMasq格式的hosts

### ISSUE THREAD

**Issue by zhqiao** [racaljk/hosts#1058]
建议同时出DNSMasq格式的hosts, 可以大大简化hosts数据和条目,乃至hosts维护工作量.
好处 1: 
同IP的次级域名都可简化成一条. 目前上万条的列表用几百条就可以完全囊括.
比如有几百条的: 61.91.161.217  *.googleusercontent.com,
可简化成一条: address=/.googleusercontent.com/61.91.161.217.
同理n条61.91.161.217  *.l.google.com可简化成一条address=/.google.com/61.91.161.217.

好处 2:
dnsmasq 可直接放到在路由器上, 这样局域网内的所有机器(PC和手机等)都直接使用, 无需每台机器再逐一作任何修改.  linux OS终端也支持dnsmasq.

下面目前我个人简化的hosts, 基本包含了所需, 可见多简单:
address=/.archive.org/207.241.224.22
address=/.box.com/74.112.184.70
address=/.bundlestars.com/23.253.146.21
address=/.bandwagonhost.com/104.20.6.63
address=/.disqus.com/151.101.100.134
address=/db.tt/110.4.24.178
address=/dropbox.com/110.4.24.178
address=/dropboxapi.com/110.4.24.178
address=/dropboxstatic.com/110.4.24.178
address=/dropboxusercontent.com/110.4.24.178
address=/flipboard.com/54.225.64.251

address=/facebook.com/157.240.3.35
address=/fb.me/157.240.3.35
address=/fbcdn.net/157.240.3.35
address=/thefacebook.com/157.240.3.35
address=/fbsbx.com/157.240.3.35
address=/facebook.net/157.240.3.35
address=/fb.com/157.240.3.35
address=/fbcdn.net/157.240.3.35

#  google
address=/google-analytics.com/127.0.0.1
address=/gmail.com/61.91.161.217
address=/googlemail.com/61.91.161.217
address=/google.com/61.91.161.217
address=/gcr.io/61.91.161.217
address=/com.google/61.91.161.217
address=/googlegroups.com/61.91.161.217
address=/gmodules.com/61.91.161.217
address=/googlestore.com/61.91.161.217
address=/google.com.hk/61.91.161.217
address=/googlechinawebmaster.com/61.91.161.217
address=/google.com.tw/61.91.161.217
address=/google.co.jp/61.91.161.217
address=/google.com.sg/61.91.161.217
address=/googlemashups.com/61.91.161.217
address=/blogger.com/61.91.161.217
address=/googleblog.com/61.91.161.217
address=/blogblog.com/61.91.161.217
address=/textcube.com/61.91.161.217
address=/blogspot.com/61.91.161.217
address=/blogspot.hk/61.91.161.217
address=/appspot.com/61.91.161.217
address=/googlecode.com/61.91.161.217
address=/googlesource.com/61.91.161.217
address=/googledrive.com/61.91.161.217
address=/googlewave.com/61.91.161.217
address=/domains.google/61.91.161.217
address=/registry.google/61.91.161.217

address=/ggpht.com/61.91.161.217
address=/googleapis.com/61.91.161.217
address=/googleusercontent.com/61.91.161.217
address=/getmdl.io/61.91.161.217
address=/googlehosted.com/61.91.161.217
address=/feedburner.com/61.91.161.217
address=/golang.org/61.91.161.217
address=/goo.gl/61.91.161.217
address=/g.co/61.91.161.217
address=/google.org/61.91.161.217
address=/recaptcha.net/61.91.161.217
address=/webmproject.org/61.91.161.217
address=/data-vocabulary.org/61.91.161.217
address=/googleinsidesearch.com/61.91.161.217
address=/teachparentstech.org/61.91.161.217
address=/thinkwithgoogle.com/61.91.161.217
address=/oneworldmanystories.com/61.91.161.217
address=/withgoogle.com/61.91.161.217

address=/googleapps.com/61.91.161.217
address=/googlezip.net/61.91.161.217
address=/polymer-project.org/61.91.161.217
address=/certificate-transparency.org/61.91.161.217
address=/abc.xyz/61.91.161.217

address=/nianticlabs.com/61.91.161.217
address=/googlepages.com/61.91.161.217
address=/toggleable.com/61.91.161.217
address=/webrtc.org/61.91.161.217
address=/chrome.com/61.91.161.217
address=/chromestatus.com/61.91.161.217
address=/chromercise.com/61.91.161.217
address=/chromium.org/61.91.161.217
address=/gwtproject.org/61.91.161.217
address=/html5rocks.com/61.91.161.217
address=/webmproject.org/61.91.161.217
address=/20thingsilearned.com/61.91.161.217
address=/creativelab5.com/61.91.161.217
address=/agoogleaday.com/61.91.161.217
address=/gosetsuden.jp/61.91.161.217
address=/thegooglepuzzle.com/61.91.161.217
address=/thegobridgeoglepuzzle.com/61.91.161.217
address=/googlezeitgeist.com/61.91.161.217
address=/dartlang.org/61.91.161.217
address=/madewithcode.com/61.91.161.217
address=/androidexperiments.com/61.91.161.217
address=/orkut.com/61.91.161.217
address=/getmdl.io/61.91.161.217
address=/urchin.com/61.91.161.217
address=/googlesyndication.com/61.91.161.217

address=/youtube.com/61.91.161.217
address=/youtube-nocookie.com/61.91.161.217
address=/youtu.be/61.91.161.217
address=/ytimg.com/61.91.161.217
address=/googlevideo.com/61.91.161.217
address=/tensorflow.org/61.91.161.217
address=/gvt0.com/61.91.161.217
address=/gvt1.com/61.91.161.217
address=/youtube.co/61.91.161.217

address=/duckduckgo.com/50.18.192.250
address=/mega.nz/154.53.224.150
address=/apkpure.com/104.20.82.194
address=/medium.com/104.16.120.127
address=/nytimes.com/170.149.159.135
address=/nyt.com/184.84.127.110
address=/twitter.com/104.244.45.250
address=/t.co/185.45.5.47
address=/twitpic.com/104.244.43.20
address=/twimg.com/104.244.43.167
address=/tweetdeck.com/104.244.42.196

address=/w3schools.com/66.29.212.110
address=/wikipedia.org/198.35.26.96
address=/smartdnsproxy.com/103.28.248.96
address=/startpage.com/43.249.39.38
address=/ixquick.com/43.249.39.49
address=/logmein.com/74.201.74.193

address=/yahoo.com/98.138.253.109
address=/yimg.com/119.160.254.215
address=/yahoo.net/50.18.192.250
address=/login.yahoo.com/106.10.193.20
address=/flickr.com/208.71.44.31
address=/api.flickr.com/119.161.10.150
address=/staticflickr.com/69.147.88.13
address=/.tumblr.com/66.6.33.193
address=/tumblr.co/66.6.32.4
address=/media.tumblr.com/66.6.44.4
address=/assets.tumblr.com/119.161.4.10
address=/cynicallys.tumblr.com/192.229.237.97
address=/srvcs.tumblr.com/66.6.32.162
address=/vt.tumblr.com/54.182.6.6

address=/soundcloud.com/72.21.91.127
address=/sndcdn.com/72.21.91.96
address=/telegram.org/149.154.167.99
address=/fastly.net/151.101.76.249
address=/pinterest.com/151.101.64.84
address=/vimeo.com/104.156.85.217
address=/vimeocdn.com/151.101.73.133
address=/fastly.net/103.245.222.249
address=/imgur.com/151.101.100.193
address=/instagram.com/31.13.70.52
address=/cdninstagram.com/31.13.70.52
address=/issuu.com/52.72.26.162

address=/kobo.com/204.87.189.92
address=/kobobooks.com/204.87.189.51

**Comment by DDoSolitary** [comment]
并不是所有人都会搭dnsmasq啊。。

**Comment by zhqiao** [comment]
很多路由器固件支持dnsmasq, 比如openwrt, dd-wrt类, 安装量很大, 很多品牌的官方固件也支持dnsmasq. 
dnsmasq无需再搭建, 进入路由器web管理界面可以直接复制文本粘贴. 内网终端都不用再改hosts了.

很多人不会dnsmasq, 其实只是不知道. 学起来很简单, 跟学会修改hosts差不多. 顺便当推动一下dnsmasq普及.

dnsmasq和hosts一样也可用于过滤, 
address=/.so.com/127.0.0.1
address=/lianmeng.360.cn/127.0.0.1
address=/wangmeng.sogou.com/127.0.0.1
address=/alog.umeng.com/127.0.0.1

**Comment by DDoSolitary** [comment]
然而我家的路由器换了两次都不支持openwrt。。都怪我爸挑便宜的买。。
参考一下我的提案：#960，这个提案通过的话类似问题（之前还有人要求surge、bind之类的）都可以解决了，而且也不用专门花心思去维护

**Comment by lychichem** [comment]
至今还不会玩这个dnsmasq，虽然我路由器连ipv6科技都开了

**Comment by guqikay** [comment]
我以前用openwrt现在用meilin，dnsmasq都可以直接用hosts，配合脚本自动更新hosts，一点都不操心。。换格式是否会增加一点效率？现在几千条对路由没什么压力

**Comment by lychichem** [comment]
@guqikay dnsmasq格式的优势是通配符，可以大大减少工作量，更新起来比较方便。
只是我至今没学会如何写出有效的可以在路由器上用的dnsmasq格式hosts

**Comment by zhqiao** [comment]
@lychichem , ddwrt在首页DCHP里启用dnsmasq, 然后在"服务"里可自定义dnsmasq, 粘贴hosts即可. 
![1](https://cloud.githubusercontent.com/assets/26898114/25004906/2fddb1d6-2089-11e7-8cf6-0273254c1c42.jpg)
openwrt里也有一个类似的选项.

**Comment by 523860169** [comment]
@lychichem dnsmasq的类似hosts功能就是address=/域名/ip这样，域名可以写为google.com和.google.com，区别是，前者只包括google.com这个一级域名，排除二级域名，后者就是既包括google.com的一级域名，也包括drive.google.com等二级域名

**Comment by channelho** [comment]
赞同，每次我都需要手动转换配置到路由器中，有点费劲，后来都干脆直接做连接了
addn-hosts=hosts文件绝对路径

**Comment by DDoSolitary** [comment]
@zhqiao
只提供dnsmasq显然是不行的，hosts相比dnsmasq对于小白要友好得多。单独维护dnsmasq的话也没人来做。而且毕竟这个项目的名字就叫hosts啊。
现在项目已经提供了dnsmasq配置文件了，但是没有利用它的通配符功能，是和hosts一起用脚本生成的
。
