### ISSUE TITLE
希望增加sublimetext3的支持

### ISSUE THREAD

**Issue by wolfan** [racaljk/hosts#1064]
墙高之后 packagecontrol.io 的访问好似开始不稳定了起来。

**Comment by DDoSolitary** [comment]
但是人家只有一个IP啊（50.116.34.243），是linode的美国服务器，延迟200+ms算正常吧。。国内也没有被DNS污染。。

**Comment by wolfan** [comment]
@DDoSolitary 也是，可是我这最近高是丢包，看来也是没办法了。。。

**Comment by wilon** [comment]
其实可以制定包加载地址，我就自己弄了个GitHub的地址。方法如下：

打开命令面板 Ctrl(Command)+Shift+p
找到并打开：Preferences: Package Control sublime Settings - User
添加一行"channels"字段：
```
"channels":
[
	"https://wilon.github.io/static/channel_v3.json"
],
```
