### ISSUE TITLE
这一类的 'Google 二级域名' 是否有规律?

### ISSUE THREAD

**Issue by imknown** [racaljk/hosts#1065]
类似这种 https://0d9321c1-a-db1c6dfe-s-sites.googlegroups.com/a/android.com/tools/tech-docs/new-build-system/build-workflow/Android%20Build%20Process.png?attachauth=ANoY7crcX6OI2hnVBpXkyRWq3GXqoiEsxSLrzkGD9ejITmfE0zpt66fvcGDdwXYlwTDxu5G0opVQsCcALkkvI1oJq2T_Ukh8UuaAXcqPTdqEYVIeA5heLRBJ6a__uFO-pypXo9MLjNpTqIWYyJBZDStKgbD_cttwClPgs-_jL6NklnoAKEis2YAC898P4BixKfmMPKyKPHDu0-YOaRo0Te_qaSAtEXGE9YSwCUwdrZ7ipkoE6E_N15y2sH1mC9T34Vr76hoORMSwh0W_MS7zNAv9UN4kiB9Veg%3D%3D&attredirects=1

**Comment by aofall** [comment]
/ # nslookup chinajjjjfupf.googlegroups.com                 
    Server:    127.0.0.1
    Address 1: 127.0.0.1 localhost.localdomain
    
    Name:      chinajjjjfupf.googlegroups.com
    Address 1: 108.177.97.137 tm-in-f137.1e100.net
    Address 2: 2404:6800:4008:c00::89 tm-in-x89.1e100.net

Google直接在 googlegroups.com 域名下做了泛解析，所以我觉得没有推出来的方法，而且协作平台除了谷歌自身还有其他网站在用，就算可推这地址也跟blogspot一样收集不完的
之前关于YouTube视频地址和谷歌云盘的下载地址知道规律的基础就是他们不是用的泛解析，域名不存在的话就不返回结果了，所以只需要大量无脑的查询就可以发现规律

**Comment by imknown** [comment]
@aofall ty
