### ISSUE TITLE
Facebook的手机版Messenger功能问题

### ISSUE THREAD

**Issue by 1900forever** [racaljk/hosts#1074]
在网页版可以正常使用，iOS版的Messenger始终不断在连接和断开，无法正常收发信息。

**Comment by wolfan** [comment]
矣，为什么我这的fb全面沦陷？

**Comment by 1900forever** [comment]
补充：电信环境

**Comment by lrinQVQ** [comment]
不用IOS不知道欸xd

**Comment by DDoSolitary** [comment]
https://www.messenger.com
你们是说这只东西吗？
这个好像国内连DNS解析都解析不出来，我来加一下吧。。

**Comment by DDoSolitary** [comment]
手机版我就没法测试了，至少网页版功能正常了。。
