### ISSUE TITLE
dropbox证书错误

### ISSUE THREAD

**Issue by Wows233** [racaljk/hosts#1075]
直接连接dropbox，chrome提示隐私设置错误
![image](https://cloud.githubusercontent.com/assets/24245520/25060249/63331b00-21cb-11e7-87ea-0e7612ed2d27.png)
![image](https://cloud.githubusercontent.com/assets/24245520/25060258/7e10abf4-21cb-11e7-9669-f5b4fe73850b.png)
好奇怪这个证书是什么鬼。。

**Comment by Wows233** [comment]
162.125.2.1 是我远程解析到的IP，但是好像被封了。。。

**Comment by ChinaYGL** [comment]
地址栏不要输入www.dropbox.com而是dropbox.com就能打开，可能是DNS污染。

**Comment by sy618** [comment]
我看了一下，52.29.64.168这个IP是亚马逊服务器的，可能会出问题。
改换成官方IP即可解决证书问题。
162.125.3.1 dropbox.com
162.125.3.1 www.dropbox.com

（来个人把hosts改一下。顺便问下大家，手机端安卓有什么工具可以方便的发Pull requests的吗？）

**Comment by DDoSolitary** [comment]
@sy618 #931 大概是`52.29.64.168`本来dropbox在用，后来关了吧。。
`162.125.3.1`可用的样子

**Comment by DDoSolitary** [comment]
@sy618 但这个ip似乎只能用于www.dropbox.com，其他域名不行

**Comment by sy618** [comment]
这个证书问题确实很坑。
从IP的证书看，是支持
DNS:www.dropbox.com, DNS:dropbox.com, DNS:support.dropbox.com, DNS:live.dropbox.com, DNS:opensource.dropbox.com, DNS:linux.dropbox.com, DNS:texter.dropbox.com
但实际上却不支持dropbox.com，不按套路来。

**Comment by Wows233** [comment]
可以访问了！谢谢大家
