### ISSUE TITLE
youtube视频无法播放

### ISSUE THREAD

**Issue by qzd1989** [racaljk/hosts#1091]
RT,你们可以吗?

**Comment by DDoSolitary** [comment]
https://github.com/racaljk/hosts/wiki/The-hosts-FAQ#%E4%B8%BA%E4%BB%80%E4%B9%88-hosts-%E6%97%A0%E6%B3%95%E6%92%AD%E6%94%BE-youtube-%E8%A7%86%E9%A2%91
