### ISSUE TITLE
medium 失效

### ISSUE THREAD

**Issue by whinamp** [racaljk/hosts#1092]
medium似乎已经失效，坐标重庆，校园网。麻烦修复一下，谢谢。😔

**Comment by sy618** [comment]
试试我的数据：
#medium
104.16.121.127 medium.com
104.16.121.145 api.medium.com
104.16.121.145 cdn-static-1.medium.com
104.16.121.145 cdn-static-2.medium.com
104.16.117.145 cdn-images-1.medium.com
151.101.44.101 cdn-images-2.medium.com

没问题就更新一下项目。

**Comment by whinamp** [comment]
@sy618 IP有效！非常感谢！

**Comment by DDoSolitary** [comment]
@whinamp medium用的是cloudflare的CDN，这个CDN在电信下的访问效果本来就不好，不过目前还没被封。项目中的IP我看了一下也都是正常的。
@sy618 cdn-static-2.medium.com这个域名是不存在的哦

**Comment by lrinQVQ** [comment]
已加入hosts close
