### ISSUE TITLE
请求新功能

### ISSUE THREAD

**Issue by huiyang-work** [racaljk/hosts#1095]
有部分ip地址需要手动设置屏蔽,可以在程序中设置一下,让hosts更新后,自动添加需要手动屏蔽的内容.那就太方便了.还可以默认50条hosts后删除.
非常感谢,我研究下你的源码.哈哈

**Comment by Ir1d** [comment]
本项目的hosts工具在更新时是以定位点为参照依据的
在本项目的内容前添加自定义内容即可

另 我其实没看懂你在说什么

**Comment by imknown** [comment]
你应该 fork 一份 自己的 repo, 保留 自己的修改, 定期同步上游代码. 需要的话 也许可以考虑自己写一个 脚本/软件 记住自己的 修改??

**Comment by huiyang-work** [comment]
非常感谢回复,在最前面添加需要屏蔽的IP,这个方法有效.

发件人: imknown J. Kimu [mailto:notifications@github.com]
发送时间: 2017年4月28日 10:26
收件人: racaljk/hosts <hosts@noreply.github.com>
抄送: huiyang-work <huiyangwork@outlook.com>; Author <author@noreply.github.com>
主题: Re: [racaljk/hosts] 请求新功能 (#1095)


你应该 fork 一份 自己的 repo, 保留 自己的修改, 定期同步上游代码. 需要的话 也许可以考虑自己写一个 脚本/软件 记住自己的 修改??
