### ISSUE TITLE
dropbox 无效

### ISSUE THREAD

**Issue by delta000** [racaljk/hosts#1097]
请问能否修复dropbox host?

**Comment by lrinQVQ** [comment]
dropbox基本上gg

**Comment by ptpt52** [comment]
dropbox 无效，证书不正确！！如果没有可能地址，建议移除

**Comment by lrinQVQ** [comment]
最后的尝试ing

**Comment by lrinQVQ** [comment]
fix now https://github.com/racaljk/hosts/commit/e40e76fa5f916404e439f116241cf4bc4cb4d13a

**Comment by lrinQVQ** [comment]
dropbox的IP还有很多请诸位放心

**Comment by delta000** [comment]
thanks!

**Comment by lrinQVQ** [comment]
@delta000 捕捉夜猫子*1 233小意思啦
