### ISSUE TITLE
Facebook视频还是有问题呀

### ISSUE THREAD

**Issue by whinamp** [racaljk/hosts#1098]
video.xx.fbcdn.net的IP失效。特此报告。

**Comment by lrinQVQ** [comment]
啧CDN

**Comment by wolfan** [comment]
@lrinQVQ 为什么你们都能访问fb呐…… 嘤嘤嘤。

**Comment by lrinQVQ** [comment]
23333待解决 有点忙不过来

**Comment by lrinQVQ** [comment]
然后就是facebook orz找IP去了

**Comment by ptpt52** [comment]
图片显示也有问题 返回 403
https://scontent.xx.fbcdn.net/v/t1.0-9/18198583_1875452709146871_532442974538557974_n.jpg?oh=718aadadd34ac22eb8fcc2b5d0ac4749&oe=5977C9A4

**Comment by whinamp** [comment]
慢慢来，不着急。😁
