### ISSUE TITLE
linux 自动更新脚本

### ISSUE THREAD

**Issue by lstoars** [racaljk/hosts#11]
#!/bin/bash
dir="$( cd "$( dirname "$0"  )" && pwd  )"
cd $dir
rm hosts.bak
rm hosts
wget "https://raw.githubusercontent.com/racaljk/hosts/master/hosts"
cp /etc/hosts ./hosts.bak
echo -e \\n >> hosts
echo "127.0.0.1 "`hostname` >> hosts
cp ./hosts /etc/hosts
echo "Success"

**Comment by racaljk** [comment]
感谢提供，你可以pull request推送这个脚本到本项目
