### ISSUE TITLE
仍然无法打开网页www.dropbox.com

### ISSUE THREAD

**Issue by ptpt52** [racaljk/hosts#1103]
wget -O- https://www.dropbox.com/static/serviceworker/serviceworker-prod.js
这个返回 404
导致页面连接成功，显示空白内容。

**Comment by lrinQVQ** [comment]
我这里能够正常打开欸

**Comment by lrinQVQ** [comment]
wget -O- https://108.160.172.238/static/serviceworker/serviceworker-prod.js
开了ss,官网默认解析的服务器中也没有这个文件

**Comment by ptpt52** [comment]
你好，登录后，就无法显示啦！

**Comment by lrinQVQ** [comment]
@ptpt52 欸 我就是登录丫

**Comment by ptpt52** [comment]
我清除cookies退出登录，就没事，能显示页面，但是登录后，就是那个样子了

**Comment by lrinQVQ** [comment]
啧 好神奇

**Comment by lrinQVQ** [comment]
突然我也这样了2333

**Comment by ptpt52** [comment]
而且我发现，ssl证书也不一样

**Comment by lrinQVQ** [comment]
2333这几段貌似是官方的老服务器

**Comment by lrinQVQ** [comment]
只能祭出最后一个IP了xd

**Comment by lrinQVQ** [comment]
为了避免那整段IP都被屏蔽orz等我再找找

**Comment by lrinQVQ** [comment]
必须得先处理google系列IP了

**Comment by andytimes** [comment]
这条域名 www.dropbox.com 不能指向证书是 *.dropbox.com 的 IP，证书是 ww.dropbox.com 才
完全可用。

以下任选一条：
`108.160.173.239        www.dropbox.com`
`162.125.32.14        www.dropbox.com`

@lrinQVQ  顺便说一句，我之前就提到过最好不要在这个项目里加那么多网站，不是每个公司都有
谷歌那么庞大的资源，你看dropbox失效这么久都没人管，最终费时费力去更新的就只有你们几个人。
别人好心来提 issue 又解决不了，长期下去，反馈的积极性估计就没那么高了。

**Comment by lrinQVQ** [comment]
@andytimes 233嘛尽力去维护吧

**Comment by lrinQVQ** [comment]
@andytimes 233其实你看看facebook 的issue有人等了半个月的2333 大家还算有耐心的

**Comment by lrinQVQ** [comment]
个人觉得的话orz 我去找了一个域名的IP这个域名所有有效IP我都能get不少 所以2333多域名还是能维护过来的

**Comment by lrinQVQ** [comment]
应该ok了吧0.0
