### ISSUE TITLE
google.golang.org can't connect

### ISSUE THREAD

**Issue by tfzxyinhao** [racaljk/hosts#1106]
74.125.28.14	google.golang.org

**Comment by lrinQVQ** [comment]
dig @114.114.114.114 google.golang.org

; <<>> DiG 9.10.3-P4-Ubuntu <<>> @114.114.114.114 google.golang.org
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 18796
;; flags: qr rd ra; QUERY: 1, ANSWER: 3, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;google.golang.org.		IN	A

;; ANSWER SECTION:
google.golang.org.	86400	IN	CNAME	golang.org.
golang.org.		300	IN	CNAME	golang-consa.l.google.com.
golang-consa.l.google.com. 300	IN	A	216.239.37.1

;; Query time: 131 msec
;; SERVER: 114.114.114.114#53(114.114.114.114)
;; WHEN: Fri May 05 19:08:25 CST 2017
;; MSG SIZE  rcvd: 104

**Comment by lrinQVQ** [comment]
172.217.11.81 更好一些貌似是被国内DNS解析到被强IP了

**Comment by tfzxyinhao** [comment]
thanks for your share new ip

**Comment by lrinQVQ** [comment]
@tfzxyinhao 都是国人说中文好伐2333

**Comment by DDoSolitary** [comment]
说英文也挺好的，然而注意语法啊。。

**Comment by lrinQVQ** [comment]
2333333楼上强迫症

**Comment by Too-Naive** [comment]
![](https://cloud.githubusercontent.com/assets/16496671/20557321/f47b3c50-b1a5-11e6-8810-8edc50a65778.png)

**Comment by tfzxyinhao** [comment]
💯 装逼失败了! 尴尬 💯

**Comment by imknown** [comment]
Ref: #1110
