### ISSUE TITLE
Android 免 root 使用 hosts 的解决方案

### ISSUE THREAD

**Issue by PeratX** [racaljk/hosts#1115]
[Daedalus](https://github.com/iTXTech/Daedalus)
内置 DNS 自定义，【hosts自定义】和【DNSMasq自定义（不完全）】。
走 VpnService，不需要 root。
希望能加入 README。
如涉及政治明感，请忽略。（知乎如此提示）

**Comment by Ir1d** [comment]
个人认为可以加入wiki而不是readme

**Comment by tsln1998** [comment]
这个目前没有开源实现吧，Vp*Service传出的ip包必须要经过还原，而现在普遍的做法是用tun2socks转成socks5协议。然后代理，这样的话难度就加大了

**Comment by tsln1998** [comment]
如果不用tun2socks之类的实现，它的ip包就要自己去分析，难免会出各种问题

**Comment by PeratX** [comment]
详见源代码，仅仅route了dns服务器的ip，也就是说其他的包都不经过vpn服务。hosts解析基于一个HashMap实现。

**Comment by lrinQVQ** [comment]
xd 看看源代码

**Comment by PeratX** [comment]
@lrinQVQ 见issue头部链接，谢谢。

**Comment by Too-Naive** [comment]
![](https://cloud.githubusercontent.com/assets/16496671/20557321/f47b3c50-b1a5-11e6-8810-8edc50a65778.png)幹嘛

**Comment by PeratX** [comment]
![](https://cloud.githubusercontent.com/assets/16496671/20557321/f47b3c50-b1a5-11e6-8810-8edc50a65778.png) 吃我滑稽

**Comment by Too-Naive** [comment]
![](https://cloud.githubusercontent.com/assets/16496671/20557321/f47b3c50-b1a5-11e6-8810-8edc50a65778.png)哎呀 寫就寫嘛 提交個pr就好了 我要去洗澡了
