### ISSUE TITLE
instagram失效，广东电信

### ISSUE THREAD

**Issue by channelho** [racaljk/hosts#1116]
如题，前几星期勉强还能开，偶尔速度还挺快的，这几天开始几乎都是无法打开的，一直都是loading状态，望大神更新，谢谢

**Comment by channelho** [comment]
31.13.95.48全部都死掉了，求更新instagram大神

**Comment by lrinQVQ** [comment]
蒙蔽 先收录 一个一个来

**Comment by lrinQVQ** [comment]
貌似大多数可用欸

**Comment by channelho** [comment]
前段时间又可以了，不过广州电信经常超时丢包，网页一直都在loading，今天又开始出现同样一直loading的情况

**Comment by jishuzhain** [comment]
广西联通谷歌失联，

**Comment by channelho** [comment]
近两天还算比较稳定，偶尔就出现之前噶情况，但Tumblr的66.6.32.31好像就真的全挂了，ping的情况全国都是超时的

**Comment by lrinQVQ** [comment]
ok

**Comment by lrinQVQ** [comment]
修复了xd
