### ISSUE TITLE
Still unable to access Twitter after IP changed today

### ISSUE THREAD

**Issue by charlesdong** [racaljk/hosts#1125]
I mean, after Twitter's IP in `hosts` changed to 104.244.45.253 this afternoon, it's still not accessible. Blocked websites, like Facebook, YouTube, Instagram are all accessible, but only Twitter isn't.

**Comment by charlesdong** [comment]
Location: 广东东莞

**Comment by lrinQVQ** [comment]
http://ping.chinaz.com/104.244.45.253

**Comment by charlesdong** [comment]
@IrinQVQ 能ping通，但就是上不了（https也不行）

**Comment by lrinQVQ** [comment]
@charlesdong 咦 没有刷新缓存咩

**Comment by lrinQVQ** [comment]
我这确实没问题欸0.0
![2017-05-13 23-20-18](https://cloud.githubusercontent.com/assets/12861134/26026704/ef859934-3832-11e7-8d9c-95cce700c9ae.png)

**Comment by charlesdong** [comment]
@lrinQVQ 怎么刷新缓存？（Windows）ipconfig /flushdns吗？

**Comment by lrinQVQ** [comment]
@charlesdong 是啊~ 或者断网重开

**Comment by myguybetter** [comment]
Yeah, that ip can be accessed through ping, but tcping its 443 port shows time out. CTC.
![image](https://cloud.githubusercontent.com/assets/11470065/26031041/70e375c2-3898-11e7-93ae-e00ea30d18db.png)

**Comment by lrinQVQ** [comment]
woc 这速度

**Comment by myguybetter** [comment]
@lrinQVQ Maybe different ISPs have different rules...

**Comment by lrinQVQ** [comment]
@myguybetter yes orz twitter is Unstable

**Comment by SerCom-KC** [comment]
Hunan Unicom is still unaccessible, neither 253 nor 250.
We still have no new IP range yet?

**Comment by lrinQVQ** [comment]
有是有xd 但是估计效果一样 推特最近抽风严重

**Comment by lrinQVQ** [comment]
现在稳定啦~

**Comment by SerCom-KC** [comment]
还是不行啊😂
看来我这儿成了重灾区了Orz

**Comment by lrinQVQ** [comment]
@SerCom-KC 欸 惊了23333

**Comment by lrinQVQ** [comment]
QAQ我去试试其他IP段好了

**Comment by lrinQVQ** [comment]
貌似得献祭...最后的2段IP了

**Comment by lrinQVQ** [comment]
有空的试下今天104.244.45.253 104.244.45.250是否能行 再不行的话我就启用新的IP段了

**Comment by charlesdong** [comment]
So, does this have anything to do with the GFW? I've heard that GFW has many ways to block sites, not only DNS pollution...
Anyway, I CAN'T LET THE GFW RUIN MY SWEET LIFE WITH THE LOVELY BLUE BIRD (TWITTER)!

**Comment by lrinQVQ** [comment]
@charlesdong GFW block the twitter 2333

**Comment by lrinQVQ** [comment]
@charlesdong can you try 104.244.45.253 104.244.45.250 104.244.45.254 104.244.45.249 and 104.244.45.255 for twitter~ these ip all work for me xd

**Comment by charlesdong** [comment]
现在我在广州，253、254和249都ping的通，其中249最快，但连不上。253根本ping不通。

**Comment by lrinQVQ** [comment]
@charlesdong 知道了orz 换IP段吧

**Comment by lrinQVQ** [comment]
@charlesdong 104.244.42.3试试

**Comment by charlesdong** [comment]
@lrinQVQ 104.244.42.3 unavailable! Ping failed!

**Comment by lrinQVQ** [comment]
@charlesdong 是的2333 gg了 我又去找找

**Comment by charlesdong** [comment]
@lrinQVQ 现在在广州的一个中学里，104.244.45.249能上去了。Thanks! Merci!

**Comment by charlesdong** [comment]
@lrinQVQ 周一能上一会，但是tweet时提示internal server error

**Comment by charlesdong** [comment]
@lrinQVQ But `t.co`'s IP address `185.45.5.47` is no longer accessible!

**Comment by SerCom-KC** [comment]
索性试了一下，246-255只有250用不了

**Comment by lrinQVQ** [comment]
soga get

**Comment by lrinQVQ** [comment]
@charlesdong 欸 估计还得换

**Comment by SerCom-KC** [comment]
mmp
我这246-255封得只剩一个可用了（
> 这是蜜罐吗woc

**Comment by charlesdong** [comment]
现在又回到东莞了，253、250、254、249都ping的通，250最快，但还是上不了

**Comment by lrinQVQ** [comment]
xd 心疼你们 其他段的IP我还在看看

**Comment by SerCom-KC** [comment]
全灭确认，我要不要自己弄个 sniproxy 试试会不会被封😂

**Comment by lrinQVQ** [comment]
哇团灭了吗

**Comment by SerCom-KC** [comment]
似乎又全部正常了
（真TM是抽风啊woc
（还是最近有事（（

**Comment by lrinQVQ** [comment]
线路抽风而已啦xd

**Comment by laodcn** [comment]
最近推特抽风严重，而可用的ip没几个了，试别的也是一样 0.0

**Comment by lrinQVQ** [comment]
xd 最后的２个ip段 貌似也在抽风

**Comment by lrinQVQ** [comment]
https://github.com/racaljk/hosts/issues/1349
