### ISSUE TITLE
报告大王，twitter又双叒叕挂了！

### ISSUE THREAD

**Issue by dawangjiaowolaifatie** [racaljk/hosts#1128]
联通的。

**Comment by lrinQVQ** [comment]
xd 我也是联通啊https://github.com/racaljk/hosts/issues/1125#issuecomment-301288683

**Comment by EricQLi** [comment]
+1

**Comment by lrinQVQ** [comment]
现在稳定啦

**Comment by lrinQVQ** [comment]
有空的试下今天104.244.45.253 104.244.45.250是否能行 再不行的话我就启用新的IP段了

**Comment by lrinQVQ** [comment]
Xd 没人理系列

**Comment by Too-Naive** [comment]
![](https://cloud.githubusercontent.com/assets/16496671/20557321/f47b3c50-b1a5-11e6-8810-8edc50a65778.png)

**Comment by lrinQVQ** [comment]
@Too-Naive 滑稽日常

**Comment by dawangjiaowolaifatie** [comment]
全部能用。

**Comment by dawangjiaowolaifatie** [comment]
又全部挂咧！

**Comment by dawangjiaowolaifatie** [comment]
又能用咧！

**Comment by lrinQVQ** [comment]
2333不稳定

**Comment by mingxianwei** [comment]
还是不能用啊

**Comment by EricQLi** [comment]
移动又停了

**Comment by lrinQVQ** [comment]
xd 一会能用一会不能用

**Comment by imknown** [comment]
花点钱 买个安心, 不稳定 太遭罪

**Comment by EricQLi** [comment]
+1

**Comment by lrinQVQ** [comment]
orz其实vpn被封了还是一个效果xd 还有流量限制

**Comment by lychichem** [comment]
@lrinQVQ 现在项目里的这组ip可用率基本是废了，手机的推这两天我就刷开过一次，但是神奇的是推发到我邮箱的邮件推送里，各种资源加载都是正常的，估计是主页的某个ip出问题了

**Comment by lrinQVQ** [comment]
昂在换吧

**Comment by lrinQVQ** [comment]
http://ping.chinaz.com/104.244.45.250
解封?

**Comment by wmjan** [comment]
电信也上不了

2017-05-28 16:40 GMT+08:00 lrin <notifications@github.com>:

**Comment by lychichem** [comment]
我这边校园网就是走电信线路


在 2017年5月28日，16:53，wmjan <notifications@github.com<mailto:notifications@github.com>> 写道：

电信也上不了

2017-05-28 16:40 GMT+08:00 lrin <notifications@github.com<mailto:notifications@github.com>>:

**Comment by lrinQVQ** [comment]
orz 在找

**Comment by lychichem** [comment]
@lrinQVQ twitter啥时候能上ipv6啊……这么搞迟早💊啊，你看隔壁fb都有v6了……
能不能找到v6的sni，我不在乎用sni的（只是不确定iPhone twitter客户端能不能用）

**Comment by lrinQVQ** [comment]
欸twitter有ipv6啊

**Comment by lychichem** [comment]
> 欸twitter有ipv6啊
我用google public dns的ipv6地址查询过解析记录，twitter没部署ipv6，其他网站查询的结果也是主站没v6，邮件系统有

**Comment by lrinQVQ** [comment]
200:2:2e52:ae44:: @lychichem

**Comment by lychichem** [comment]
@lrinQVQ 只有ip ULA吗？完整的ipv6不应该这样啊

**Comment by lrinQVQ** [comment]
@lychichem 等下啊 我去弄一个可用的出来orz

**Comment by lrinQVQ** [comment]
震惊我的6炸了

**Comment by lychichem** [comment]
@lrinQVQ 你那里v6也是双栈校园网么？还是外面的运营商的，反正我这里直插网线的话v6质量很好，不过如果在寝室里路由器上搞的话可能就会偶然断线（据说是学校交换机承载力有限人一多v6就炸了orz）

**Comment by lrinQVQ** [comment]
@lychichem 我是6to4的啦~

**Comment by lychichem** [comment]
@lrinQVQ 唔

> Q & A
Q: 为什么没有 Twitter？
A: 首先 Twitter 不支持 IPv6，网上流传的地址并不是官方 IPv6 地址； 其次针对 Twitter 采取了 DNS 污染和 IP 封锁等多重封禁手段， 仅靠 hosts+HTTPS 并不能正常访问。
Q: 为什么又有了 Twitter？
A: 因为找到了没有被封的 IP。 XD 
从隔壁lennylxx那里转过来的，我去看过了那个ip也是v4的，真正的v6 ip恐怕只能sni了

**Comment by lrinQVQ** [comment]
@lychichem 2606:1F80::/32 以前一个一个的试过orz 有两个可用的 唔不过估计挺麻烦的现在

**Comment by EricQLi** [comment]
+1

**Comment by lrinQVQ** [comment]
gfw 很聪明的干扰了twitter的443端口
![2017-05-30 05-51-13](https://cloud.githubusercontent.com/assets/12861134/26562760/0220c890-44fc-11e7-913f-f7b3bdf5603d.png)
延迟和丢包率直接上天
出国前走的是北京联通219.158.3.178
出国后直达美国129.250.8.25 - 129.250.6.144 这两个ip都很稳定并且延迟低于100 - 到了104.244.45.250经常丢包 并且这应该不是线路的锅,明显的干扰443端口

**Comment by lychichem** [comment]
试图用ipv4映射位址发现好像还是走了v4通道……没办法了……

**Comment by lrinQVQ** [comment]
新ip丢包有点高orz不过还是能打开

**Comment by EricQLi** [comment]
+1

**Comment by LGA1150** [comment]
@lrinQVQ 哪个 IPv6 可用？

**Comment by lrinQVQ** [comment]
https://github.com/racaljk/hosts/issues/1349
