### ISSUE TITLE
建议支持http://download.lineageos.org/

### ISSUE THREAD

**Issue by WeihuaGu** [racaljk/hosts#1136]
您好，感谢您开 Issue 来反馈信息，在提交前，请确保您已经检查了以下内容!
- 如有关 "Google无法连接" / "YouTube视频无法播放" / "GitHub访问慢" 等问题 请参阅[常见问题解答](https://github.com/racaljk/hosts/wiki/The-hosts-FAQ)
- 已经阅读了 [Wiki 页面](https://github.com/racaljk/hosts/wiki)
- 已经搜索过之前的相关 [Issues](https://github.com/racaljk/hosts/search?type=Issues)
- 如果是报告问题，请确认问题可以复现并且没有重复报告同一个问题；如果是向 hosts 提供新的信息，请确认所提供信息的来源以及相关许可协议；欢迎使用 Pull Requests 功能（可以通过[直接编辑文件](https://github.com/racaljk/hosts/edit/master/hosts)的方式来提交）

如果您有其他附言，例如问题只在某个页面发生，或者是一般性讨论、提出新功能，请一定注明

或者您也可以卖个萌

我们同时有一个 [Gitter Room](https://gitter.im/racaljk/hosts)，以及一个[在 Coding 上的镜像](https://coding.net/u/scaffrey/p/hosts)

lineage os 是cm的继任者，比较优秀的第三方安卓rom。
http://download.lineageos.org/ 是lineageos 的rom下载页面。lineageos.org没有被墙，但是它的下载页面被墙了。

**Comment by imknown** [comment]
居然被wall了

**Comment by lrinQVQ** [comment]
lineageos的下载服务器只有一台的xd,没钱买更多了

**Comment by lrinQVQ** [comment]
要么IPv6 2600:3c01::f03c:91ff:febc:a6e4
要么只能代理了QAQ

**Comment by laodcn** [comment]
可以使用国内 中国科学技术大学开源软件镜像服务器下载：http://centos.ustc.edu.cn/lineageos/full/

**Comment by laodcn** [comment]
PS：我这里能打开官网呀（我确定我没开VPN）

**Comment by lrinQVQ** [comment]
@laodcn 官网和下载服务器不是同一个

**Comment by WeihuaGu** [comment]
@laodcn 感谢。我发现清华的源也有:https://mirrors.tuna.tsinghua.edu.cn/lineage-rom/full/
