### ISSUE TITLE
似乎无法成功修改host, 修改后仍然打不开维基中文

### ISSUE THREAD

**Issue by 123ysys** [racaljk/hosts#1138]
如题，我在host文件上加上了几个维基中文的ip，还有一个FB的ip地址，也释放了DNS缓存，却总是打不开这两个网站。求助。

**Comment by 123ysys** [comment]
截图待会儿再加

**Comment by 123ysys** [comment]
![img_20170518_144428](https://cloud.githubusercontent.com/assets/27964272/26192836/bd4fd478-3be5-11e7-9312-0dda313ded72.jpg)

**Comment by 123ysys** [comment]
![img_20170518_141553](https://cloud.githubusercontent.com/assets/27964272/26192876/dcab7692-3be5-11e7-81ad-c15ff7daa802.jpg)

**Comment by 123ysys** [comment]
这是我的ping值
![Uploading IMG_20170518_144631.jpg…]()

**Comment by 123ysys** [comment]
![img_20170518_144631](https://cloud.githubusercontent.com/assets/27964272/26192937/1565eefe-3be6-11e7-960d-b3d15080802f.jpg)

**Comment by lrinQVQ** [comment]
= =维基百科的域名和相关域名不止这么一点啊xd

**Comment by lrinQVQ** [comment]
推荐你全部加上2333

**Comment by 123ysys** [comment]
其实是文件名错误。
