### ISSUE TITLE
翻墙作用有限，

### ISSUE THREAD

**Issue by xingxing9688** [racaljk/hosts#1139]
这个翻墙智能谷歌搜索一些资料不能真正的翻墙

**Comment by dawangjiaowolaifatie** [comment]
本来也没人说能上所有的网站啊，咋这么不懂事呢，对一个长期维护的免费服务说这说那的。赶紧关了吧。

**Comment by lrinQVQ** [comment]
嘛～这不是代理啦 所以肯定有限制 我们不可能收集到所有的网站啊
