### ISSUE TITLE
atom编辑器 下载链接能不能hosts

### ISSUE THREAD

**Issue by livingvirus** [racaljk/hosts#114]
都跳转到这个链接 https://github-cloud.s3.amazonaws.com.
非常感谢

**Comment by racaljk** [comment]
这个你可以自行添加到本地hosts

下载链接 跳转链接

**Comment by owenyaa** [comment]
大神。。有软件的exe文件么。。@racaljk

**Comment by whinamp** [comment]
最新这一版Facebook似乎无效，其他各位再试试。

**Comment by andytimes** [comment]
我刚刚搜索了一下 Atom 编辑器，是 Github 发布的，这个和 hosts 项目无关，你不应该发到这里来，应该发到提供给你下载链接的地方，或者联系提供下载链接的人。

还有，你提的问题是
"atom编辑器 下载链接能不能hosts"
至少也要给个下载链接吧，你这样的提问，什么问题也解决不了。
