### ISSUE TITLE
建议添加Telegram连接解析

### ISSUE THREAD

**Issue by xmattyboi** [racaljk/hosts#1141]
今天用上了这里提供的host 但是有一个问题Telegram连接不上收不了消息 Instagram Stroies速度也不是很好 不能正常加载视频 虽然刷Instagram速度也差不到哪去吧 如果因部分原因不能实现Instagram Stroies 但最起码要支持Telegram连接解析 希望能够加入支持 谢谢作者大大

**Comment by lrinQVQ** [comment]
Telegrams是网页版还是?

**Comment by EMLVIRUS** [comment]
TG只有网页版能用得到hosts

**Comment by xmattyboi** [comment]
那意思说是不可实现咯了?好吧略可惜

**Comment by xmattyboi** [comment]
不是网页端 是客户端

**Comment by lrinQVQ** [comment]
TG客户端走IP的 无解xd
