### ISSUE TITLE
【公告】各位collaborator、contributor戳进来看一下

### ISSUE THREAD

**Issue by DDoSolitary** [racaljk/hosts#1142]
我提出的提案（#960）现已实现，今后大家请修改hosts-source分支下的[hosts.yml](https://github.com/racaljk/hosts/blob/hosts-source/hosts.yml)而不是之前的`hosts`，否则会被**覆盖**。`hosts.yml`修改后会自动生成并提交`hosts`。
`hosts.yml`的格式我想已经非常self explaining了吧，不清楚的问我。

@racaljk @Ir1d @imknown @lrinQVQ @laodcn @Too-Naive @aofall @andytimes

**Comment by racaljk** [comment]
了解

**Comment by racaljk** [comment]
可以在README.MD增加关于贡献的小标题解释一下

**Comment by DDoSolitary** [comment]
@racaljk 嗯，正打算搞呢

**Comment by DDoSolitary** [comment]
@racaljk 加了 52ddcd593c1af330218c657aa91e42cfeac74be8 6f8a8b09b12cc1662066284e890bcf86260bac0e

**Comment by lrinQVQ** [comment]
知道啦～

**Comment by imknown** [comment]
了解. thx.

**Comment by andytimes** [comment]
2017-05-20 11:32 GMT+08:00 DDoSolitary <notifications@github.com>:

> 我提出的提案（#960）现已实现，今后大家请修改hosts-source分支下的hosts.yml而不是之前的hosts，否则会被覆盖。hosts.yml修改后会自动生成并提交hosts。
> hosts.yml的格式我想已经非常self explaining了吧，不清楚的问我。
>
> @racaljk @Ir1d @imknown @lrinQVQ @laodcn @Too-Naive @aofall @andytimes


没有任何异议，另外，既然有能自动生成指定格式的工具了，tools/checkhosts.sh 和
tools/Hindent 就不需要了。

Andy

**Comment by PeratX** [comment]
道理我都懂，但是没有泛解析的dnsmasq配置文件和咸鱼有什么区别？

**Comment by DDoSolitary** [comment]
<del>看起来很厉害</del>

**Comment by laodcn** [comment]
有点不习惯了，感觉好麻烦的样子

**Comment by lrinQVQ** [comment]
@laodcn 很简单的啦~ ip:
                                     ip适用的域名:

**Comment by lrinQVQ** [comment]
其实还方便了很多欸~

**Comment by Too-Naive** [comment]
Roger

**Comment by aofall** [comment]
已经很久没给项目push过任何代码了，未来也没有push的打算。

技巧我想你们都掌握了，需要注意的地方也在wiki或者各个issue里说明了。有类似 #1065 的issue可以 @ 我乐意解答，其他就没什么必要了。

**Comment by andytimes** [comment]
> 道理我都懂，但是没有泛解析的dnsmasq配置文件和咸鱼有什么区别？

@PeratX @DDoSolitary 下午尝试过从 hosts.yml 生成泛解析这个方案，但想了一下，感觉是个坑，
于是作罢。

我是这样考虑的，因为之前看到过 dnsmasq.conf 泛解析的例子：
https://github.com/racaljk/hosts/issues/135#issuecomment-166209688

一开始感觉很简单，基本就是把相同IP的域名收集起来，求这些域名字符串倒序的最大交集。然后
觉得这个方法行不通，因为这样做，可能会出现类似下面的情况：

```conf
address=/dropbox.com/0.0.0.2
address=/dropbox.com/0.0.0.1
```

好吧，这么一想，我大概就知道 @DDoSolitary 为什么没做泛解析了，因为不对配置文件做干预，
要求泛解析时，基本只能手写，否则后遗症会很多。

最近在学 Python，加上一段时间都没怎么好好写代码了。本来想借这个机会实践一下，看到配置
文件是用 js 来生成的，而且自己又没什么好的想法，只能就此作罢。

```python
#!/usr/bin/python
# -*- coding: UTF-8 -*-

a1 =        'a.linux.arm.if.not.true.then.true'
a2 = 'b.test.windows.brm.if.not.true.then.true'

# reverse a1
ra1 = a1[::-1]
# reverse a2
ra2 = a2[::-1]

for x in range(min(len(ra1), len(ra2))):
    if ra1[x] == ra2[x]:
        continue
    else:
        tmp = ra1[:x]
        break

common_domain = tmp[::-1].split('.', 1)[-1]

print(common_domain)

```

上面是求公共域名的大致思路，感觉好简陋、、、主要之前shell写习惯了，一点数据结构的概念
都没有了。不过，总算能用 Python 做一些事情了，顺便 at 一下很久都没出现过的人 @K-Guan 

对泛解析有什么好的想法，大家都可以积极发言，顺便求指教、、、

**Comment by Ir1d** [comment]
求这些域名字符串倒序的最大交集
最长公共后缀？
那这样写似乎够了？

**Comment by andytimes** [comment]
> 求这些域名字符串倒序的最大交集
> 最长公共后缀？

对，就是最长公共后缀，一开始没想到合适的词。

> 那这样写似乎够了？

我不知道指的是哪方面，如果是指泛解析，这样做似乎还不够，可能需要进一步修改 hosts.yml，或者
在生成 dnsmasq.conf 的脚本中指定需要泛解析的域名（不建议，因为脚本改动可能滞后 hosts.yml）。
暂时没有好的想法。如果有，可以提出。

如果指用 "最长公共后缀" 描述这个脚本的作用，那确实够了。

**Comment by DDoSolitary** [comment]
@andytimes @Ir1d
感觉很有趣，我也想想有什么好的方案吧
这个另开issue讨论？

**Comment by DDoSolitary** [comment]
这个公告大家应该都知道了吧，close了
