### ISSUE TITLE
请求添加lineageos的hosts

### ISSUE THREAD

**Issue by JingweiWang** [racaljk/hosts#1143]
`https://download.lineageos.org/ `

以上网址在国内始终进不去，求添，谢谢

**Comment by lrinQVQ** [comment]
xd 没钱买多的服务器 IP只有一个
要么国内镜像源:http://centos.ustc.edu.cn/lineageos/full/
https://mirrors.tuna.tsinghua.edu.cn/lineage-rom/full/
要么用IPv6:2600:3c01::f03c:91ff:febc:a6e4
要么代理服务器
https://github.com/racaljk/hosts/issues/1136
