### ISSUE TITLE
唉……，youtube可以用IPv4播放喵。

### ISSUE THREAD

**Issue by wolfan** [racaljk/hosts#1145]
刚刚无聊的倒了半小时，测试到一个ipv4能播放youtube。
不过，反正，哦，好像只成功一个视频。

```
https://www.youtube.com/watch?v=aZmtyZGgk_A
74.125.10.60  r6---sn-npoe7n7y.googlevideo.com
```

但是其它的好像都不行。。
```
74.125.10.59  r5---sn-npoe7n7y.googlevideo.com
74.125.10.58  r4---sn-npoe7n7y.googlevideo.com
```
都加载失败。这是为什么呐~~~~

**Comment by lrinQVQ** [comment]
每个SN 编码域名对应的IP不同啦~

**Comment by lychichem** [comment]
sn编码一大堆，v4地址又封太快，要真想看还是vpn或者ipv6最稳

**Comment by wangchunming** [comment]
可以，指向代理就行，我这边的可以放视频。 https://github.com/wangchunming/2017hosts

**Comment by lrinQVQ** [comment]
我争取利用特殊的办法完成一下233

**Comment by lrinQVQ** [comment]
咩 差不多可以了 正在逐步添加https://github.com/racaljk/hosts/commit/1ec400d21436ba80680f083ea5e660ac84c34f03

**Comment by Too-Naive** [comment]
![](https://user-images.githubusercontent.com/16496671/27985622-113e44a8-6421-11e7-81c4-9abe2f494ffc.png)

**Comment by lrinQVQ** [comment]
2333可以

**Comment by Too-Naive** [comment]
![](https://cloud.githubusercontent.com/assets/16496671/20557321/f47b3c50-b1a5-11e6-8810-8edc50a65778.png)

**Comment by DDoSolitary** [comment]
有趣，也许可以给GitHub反映一下。。

**Comment by lrinQVQ** [comment]
+1

**Comment by lrinQVQ** [comment]
我继续弄好google video你们反馈下吧2333

**Comment by DDoSolitary** [comment]
我来反馈吧

**Comment by lrinQVQ** [comment]
好233交给你啦

**Comment by DDoSolitary** [comment]
搞定

![github-contact](https://user-images.githubusercontent.com/25856103/27986055-8447b9fc-642b-11e7-9293-6733a22a508c.png)

**Comment by lrinQVQ** [comment]
2333 ok

**Comment by lrinQVQ** [comment]
搞定很多了咩
