### ISSUE TITLE
google mvn for android studio 3.0

### ISSUE THREAD

**Issue by JingweiWang** [racaljk/hosts#1147]
`https://maven.google.com/`

Please add.

**Comment by lrinQVQ** [comment]
ok

**Comment by lrinQVQ** [comment]
有的啊 https://github.com/racaljk/hosts/blob/hosts-source/hosts.yml#L107

**Comment by imknown** [comment]
这是我加的. 看完 谷歌 io 2017 android 场 我就加了.

**Comment by lrinQVQ** [comment]
2333 soga
