### ISSUE TITLE
Nasa.gov

### ISSUE THREAD

**Issue by hrimfaxi** [racaljk/hosts#1149]
（联通）国内解析地址68.142.107.84打开困难。换成208.111.179.103后可迅速打开。

**Comment by lrinQVQ** [comment]
貌似不同运行商效果不同 ping出来两个ip在全国情况差不多

**Comment by DDoSolitary** [comment]
正如@lrinQVQ所说，两个IP情况差不多，而且此域名没有被墙，先close了
