### ISSUE TITLE
黑龙江联通已无法访问谷歌

### ISSUE THREAD

**Issue by Chinese-User** [racaljk/hosts#1150]
您好，感谢您开 Issue 来反馈信息，在提交前，请确保您已经检查了以下内容!
- 如有关 "Google无法连接" / "YouTube视频无法播放" / "GitHub访问慢" 等问题 请参阅[常见问题解答](https://github.com/racaljk/hosts/wiki/The-hosts-FAQ)
- 已经阅读了 [Wiki 页面](https://github.com/racaljk/hosts/wiki)
- 已经搜索过之前的相关 [Issues](https://github.com/racaljk/hosts/search?type=Issues)
- 如果是报告问题，请确认问题可以复现并且没有重复报告同一个问题；如果是向 hosts 提供新的信息，请确认所提供信息的来源以及相关许可协议；欢迎使用 Pull Requests 功能（可以通过[直接编辑文件](https://github.com/racaljk/hosts/edit/master/hosts)的方式来提交）

如果您有其他附言，例如问题只在某个页面发生，或者是一般性讨论、提出新功能，请一定注明

或者您也可以卖个萌

我们同时有一个 [Gitter Room](https://gitter.im/racaljk/hosts)，以及一个[在 Coding 上的镜像](https://coding.net/u/scaffrey/p/hosts)

**Comment by lrinQVQ** [comment]
看全国ping貌似现在没问题了欸

**Comment by wolfan** [comment]
@lrinQVQ 感觉回滚之前的google更快，反正换新之后访问经常出错。

**Comment by wangchunming** [comment]
欢迎去 https://github.com/wangchunming/2017hosts瞧瞧，可以播放视频也涵盖了好多这边没有的网站。

**Comment by DDoSolitary** [comment]
SNI proxy吧

**Comment by lrinQVQ** [comment]
xd反正我还是尽量别SNI

**Comment by sunui** [comment]
北京联通也无法访问

**Comment by Zobeta** [comment]
我这更新了最新hosts后访问谷歌很奇怪。经常莫名其妙就不能访问了，奇怪的是https://www.google.com/ncr这个地址一直没问题，只要打开它一次，其他就会都恢复正常一会儿……

**Comment by lrinQVQ** [comment]
咦奇怪了
ncr是无国别跳转所以不会被污染
是不是你的安全软件搞的鬼＝　＝

**Comment by Zobeta** [comment]
@lrinQVQ 没有装安全软件呀，只有win10自带defender = =

**Comment by Chinese-User** [comment]
@Zobeta 刷新DNS缓存

**Comment by Zobeta** [comment]
@Chinese-User 早就弄过了没用，不过现在google hosts好像都挂掉了，只能等更新了

**Comment by lrinQVQ** [comment]
已修复搜索服务,以及旗下的Google账户服务

**Comment by Chinese-User** [comment]
现已可以访问
