### ISSUE TITLE
谷歌已挂

### ISSUE THREAD

**Issue by cjkzwe** [racaljk/hosts#1152]
谷歌已挂，非国别也不行，尽快fix吧。。。。
万恶的。。。。

**Comment by cjkzwe** [comment]
对，山东联通的。

**Comment by Chinese-User** [comment]
黑龙江联通也一样

**Comment by luopingquan** [comment]
我是南京教育网，Google挂掉了，Facebook，twitter，instagram正常。

**Comment by Zobeta** [comment]
辽宁联通也挂了

**Comment by copie** [comment]
河南联通也挂了

**Comment by lrinQVQ** [comment]
get orz

**Comment by lrinQVQ** [comment]
全力fix ing

**Comment by lrinQVQ** [comment]
一会更新

**Comment by lrinQVQ** [comment]
已修复搜索服务,以及旗下的Google账户服务

**Comment by Zobeta** [comment]
@lrinQVQ 我这似乎能访问了，感谢大佬

**Comment by lrinQVQ** [comment]
@Zobeta 又复活了嘛2333小意思

**Comment by laodcn** [comment]
都是联通的问题...

**Comment by Chinese-User** [comment]
@lrinQVQ 已经可以访问。

**Comment by 0915240** [comment]
还是不行哈？

南京电信：https://www.google.com/ncr

**Comment by testcaoy7** [comment]
ERR_CONNECTION_TIMED_OUT

**Comment by poorcai** [comment]
原来都不行了啊，而且大部分都是联通，我也是。

**Comment by lrinQVQ** [comment]
看新IP的issue

**Comment by lizi0815** [comment]
四川电信一切正常

**Comment by wmjan** [comment]
google正常，twitter倒是打不开

2017-05-28 16:15 GMT+08:00 lizi0815 <notifications@github.com>:

**Comment by lrinQVQ** [comment]
twitter有些麻烦orz忙死了

**Comment by edidada** [comment]
广东联通，目前访问不了google.com.hk和google.com

**Comment by lrinQVQ** [comment]
http://ping.chinaz.com/104.244.45.250
貌似twitter解封?

**Comment by Chinese-User** [comment]
@lrinQVQ 无法访问Twitter……然而FB正常

**Comment by lrinQVQ** [comment]
@Chinese-User 2333解决ing

**Comment by wangchunming** [comment]
山东联通这边有点烦人，单独连接ip是通的，但是一旦改ip到hosts再次尝试打开，原先通的ip立马就不通了。

**Comment by cjkzwe** [comment]
fix的 google不稳定啊，见光死了？
万恶的GFW。。。。>_<

**Comment by blindlf** [comment]
北京联通不行

**Comment by imknown** [comment]
联通五月份开始几乎就是一直不能用.. 电信没问题. 但是电信下载太慢...

**Comment by lrinQVQ** [comment]
修复了咩
