### ISSUE TITLE
关于新IP

### ISSUE THREAD

**Issue by lrinQVQ** [racaljk/hosts#1153]
此IP为谷歌官方的IP
如果之前IP可用的用户可以不用更新,不可用的用户可以测试下

**Comment by lrinQVQ** [comment]
见光死了= =

**Comment by laodcn** [comment]
202.86.162.172
联通用户可以用这个澳门电信运营商（CTM）紧急

**Comment by wangchunming** [comment]
还有还有存活的！
220.152.33.230
188.116.219.15
113.171.242.242
103.59.200.142

**Comment by wangchunming** [comment]
49.44.67.218
49.44.67.219
49.44.67.215

**Comment by wangchunming** [comment]
现在运营商可以根据ip返回的证书杀ip，联通和移动最近用这种方法封ip在我这封了很多了，ping能通，但是一传输数据以后，再ping就不通了。

**Comment by lrinQVQ** [comment]
嘛 我准备找个稳定点的官网ip了(已经有 但是稳定性还在测试

**Comment by wangchunming** [comment]
@lrinQVQ 现在最缺的是 *.googleusercontent.com *.googleapis.com 的ip，没有这些证书的ip的话，手机用户是无法在手机上正常使用某些google服务的。（安卓6.0以下）

**Comment by wangchunming** [comment]
要照顾这袭人，就要多费点心思。

**Comment by lrinQVQ** [comment]
等下 我回去更新这些域名

**Comment by lrinQVQ** [comment]
@wangchunming 好像目前项目里面的就可以用的0.0

**Comment by laodcn** [comment]
@wangchunming 谷歌存活的ip我这里有一大推，但是非常不稳定... 有的网络用不了（联通、移动）
像你上面列出的220.152.33.230、188.116.219.15 我这里就不行（电信）其它没试。

**Comment by lrinQVQ** [comment]
有几段三大运营商延迟都在50左右的orz 目前观望稳定2天继续观望下

**Comment by wangchunming** [comment]
@laodcn 老D博主啊，电脑上的话用SNIproxy其实也是可以的，手机上就不行，chromeos笔记本电脑也是不行，苹果设备可以。

**Comment by wangchunming** [comment]
如果手机上需要用SNIproxy的话，说实话极端情况下也行，但是有这么几个域名，就是不能用sniproxy：
android.clients.google.com
www.googleapis.com
googleapis.com
lh*.googleusercontent.com

**Comment by wangchunming** [comment]
电信的话出国慢也是个困扰hosts作者的问题。

对了，老D博主，你hosts里有好多google的域名都没有。
mclients.googleapis.com （play音乐联网验证）
cloudconfig.googleapis.com （google设置联网同步）
web.google.com （手机上谷歌应用部分button是从这里调用的）
等等等等。。。。。。

**Comment by wangchunming** [comment]
googlecloud控制台域名缺失：
ssh.cloud.google.com （计算实例控制台相关）
google相册缺失：（照片分类自动整理）
people-pa.clients*（1到6）.google.com
手机版chrome新闻通知：（对，就是下拉chrome出现的新闻）
chromecontentsuggestions-pa.googleapis.com
谷歌的opensource：
opensource.google.com

还有几个google的官方博客，也有必要添加（全国大部分地区解析不正常）：
china,googleblog.com （google中国博客）
developers.googleblog.com （google中国开发者博客）
admob.googleblog.com （google广告博客，有些人会看）
opensource.googleblog.com （google opensource博客，dev们会看）

还有大量域名你这边hosts项目里都没有，我这边早都抓包添加上了，你的hosts项目有名气，我担心别人用着不舒服全都跑了，其中也不乏一些小白，所以就把我这边的更改全都告诉你吧。

**Comment by wangchunming** [comment]
还有一些事实上看似不需要但是影响某些强迫症患者体验的域名：
pubads.g.doubleclick.net （youtube页面顶部视频广告）
web.googleapis.com （google 网页某些元素会引用这里的域名）

**Comment by wangchunming** [comment]
有些人需要line，但是line官方ip很难找，这是完整的line域名列表我发在这里吧，你看看合适的话就找找ip添加上。（我这里写一个219.76.4.76是为了你以后添加的时候直接使用替换就行了，没有其他意思）



219.76.4.76	gd2.line.naver.jp
219.76.4.76	gd2.line.naver.jp
219.76.4.76	gd2w.line.naver.jp
219.76.4.76	gd2w.line.naver.jp
219.76.4.76	gw.line.naver.jp
219.76.4.76	gw.line.naver.jp
219.76.4.76	gw.line.naver.jp
219.76.4.76	gww.line.naver.jp
219.76.4.76	gww.line.naver.jp
219.76.4.76	gwx.line.naver.jp
219.76.4.76	lan.line.me
219.76.4.76	lcp-checkout.line.me
219.76.4.76	line.me
219.76.4.76	obs.line-apps.com
219.76.4.76	obs.line-apps.com
219.76.4.76	obs-cn.line-apps.com
219.76.4.76	obs-cn.line-apps.com
219.76.4.76	obs-tw.line-apps.com
219.76.4.76	scdn.line-apps.com
219.76.4.76     static.line.naver.jp
219.76.4.76	scdn.line-apps.com
219.76.4.76	w.line.me
219.76.4.76	xcdn-cn-prf.line-apps.com
219.76.4.76	xcdn-cn-shp.line-apps.com
219.76.4.76	xcdn-cn-stk.line-apps.com
219.76.4.76	gd2w.line.naver.jp
219.76.4.76	dl.profile.line.naver.jp
219.76.4.76	dl.stickershop.line.naver.jp
219.76.4.76	gd2.line.naver.jp
219.76.4.76	gd2g.line.naver.jp
219.76.4.76	gd2i.line.naver.jp
219.76.4.76	gd2k.line.naver.jp
219.76.4.76	gd2w.line.naver.jp
219.76.4.76	gd2w.line.naver.jp
219.76.4.76	gd2s.line.naver.jp
219.76.4.76	gd2u.line.naver.jp
219.76.4.76	gd2v.line.naver.jp
219.76.4.76	obs-cn.line-apps.com
219.76.4.76	xcdn-cn-stk.line-apps.com
219.76.4.76	xcdn-cn-prf.line-apps.com

**Comment by wangchunming** [comment]
chrome云加速ip是时候也得换换了（几个ip我看速度都不错）：
108.177.97.211
216.58.200.12

**Comment by lrinQVQ** [comment]
@wangchunming 非常感谢啦 
*.googleusercontent.com *.googleapis.com这些IP我稍后提供给你2333有一堆的

**Comment by huangjiasingle** [comment]
61.91.161.217 443不通，但是能ping通，因为我要下载镜像：docker pull  gcr.io/xxxxx 老是报超时

**Comment by wangchunming** [comment]
哈萨克斯坦电信CN2还有几个：
121.59.17.7
121.59.17.8
121.59.17.9
121.59.17.10

**Comment by lrinQVQ** [comment]
@wangchunming 实测了下应该不是运营商通过证书封杀 毕竟2333好多*.google.com的ip现在还没封

**Comment by wangchunming** [comment]
@lrinQVQ 是 google.com的证书会被封。

**Comment by lrinQVQ** [comment]
@wangchunming 欸64.233.160.110存活挺久的0.0

**Comment by sy618** [comment]
这个哈萨克斯坦IP可用于小鸟

**Comment by Lynchie** [comment]
--
