### ISSUE TITLE
请求添加a248.e.akamai.net的hosts

### ISSUE THREAD

**Issue by fatloong** [racaljk/hosts#1159]
这个是Akamai的CDN域名，被DNS污染，导致Apple、微软等不少网站内容无法完全加载。希望开发者能在hosts中加入这个域名，谢谢！

参考：http://bbs.kafan.cn/thread-1800094-1-1.html
http://429006.com/article/technology/3635.htm

**Comment by wangchunming** [comment]
额。
其实即使添加了，在网页解析的过程中也不会调用。

**Comment by lrinQVQ** [comment]
虽然讨厌IOS但是还是加了咩 https://github.com/racaljk/hosts/blob/master/hosts#L362
