### ISSUE TITLE
请教你这个hosts是如何创建的？使用什么工具找ip

### ISSUE THREAD

**Issue by cuthead** [racaljk/hosts#116]
请教生成的原理，授人以渔

**Comment by andytimes** [comment]
cuthead <notifications@github.com>于2015-11-28 18:32 周六写道：

> 请教生成的原理，授人以渔
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/racaljk/hosts/issues/116>.
>
@cuthead 首先，我想说，如果您懂得一些互联网相关的知识，会用 Google 搜索，自己学习生成 hosts，寻找 IP
这些是不成问题，这里只是维护 hosts 的地方。
我们没有义务教阁下该如何去生成，Google 上随便一搜，一堆教程，如果您 hosts 原理, ping,  nslookup
工具都不会用，就不该问这个问题 (没有那么多时间一个工具一个工具解释，Google 既然能上为什么不自己去研究呢？)。
我们几个基本都是高三党，没有多少时间一个解释，以前 issue 区就有很多类似问题。
我相信能来到 Github.com 的，至少找资料的能力不会差的。
你要是单纯找 Google IP，用 Windows 下 用 Google Tester，Linux 下可以找找 Github 里相关项目。

https://www.google.com.hk

**Comment by K-Guan** [comment]
@Andy's comment is enough to answer is question, so I closed it.
