### ISSUE TITLE
使用Surge的配置文件dnsmasq.conf和surge.conf时显示“无效（配置文件必须以[section]形式开始“

### ISSUE THREAD

**Issue by yongtongyanyi** [racaljk/hosts#1166]
使用Surge的配置文件dnsmasq.conf和surge.conf时显示“无效（配置文件必须以[section]形式开始“

**Comment by digicolor** [comment]
你是只替换了你自己的surge.conf中的 host部分吗

**Comment by DDoSolitary** [comment]
我这边没有iOS设备用于测试，有人能确认一下吗

**Comment by yongtongyanyi** [comment]
[screen record.zip](https://github.com/racaljk/hosts/files/1050440/screen.record.zip)

**Comment by Too-Naive** [comment]
`https://raw.githubusercontent.com/racaljk/hosts/master/surge.conf` is not equal `https://github.com/racaljk/hosts/blob/master/surge.conf`

**PLEASE USING RAW LINK TO GET THE CONFIG FILE**
