### ISSUE TITLE
twitter是不是挂了？

### ISSUE THREAD

**Issue by yangmengli** [racaljk/hosts#1169]
RT

**Comment by lrinQVQ** [comment]
更新一个死一个orz

**Comment by PW-Chen** [comment]
@lrinQVQ 为啥我觉得 twitter好像被墙的速度特别快?
tumblr facebook 感觉也没那么频繁
还有twitter的主机相对于facebook 的主机量 好像少很多

**Comment by lrinQVQ** [comment]
_(:з」∠)_twitter就5个255的段啊

**Comment by lychichem** [comment]
主机这么少再不给v6真的完了

**Comment by wangchunming** [comment]
郭文贵事件导致的。
https都被干扰，这个没办法解决。

**Comment by lrinQVQ** [comment]
没有挂2333 也有可用IP但是等风声过了在更新

**Comment by xingxuanma** [comment]
也是，这段时间就先用vpn将就一下吧

**Comment by lrinQVQ** [comment]
@xingxuanma 感谢理解啦~

**Comment by 123ysys** [comment]
@lrinQVQ 真的只是暂时的吗？

**Comment by lrinQVQ** [comment]
@123ysys 恩啊 我已经在开始更新了啊233

**Comment by yangmengli** [comment]
@lrinQVQ 我们现在是不是还没有添加Twiter的Periscope直播的hosts?

**Comment by lrinQVQ** [comment]
是啊233

**Comment by yangmengli** [comment]
@lrinQVQ 有添加计划么,有的直播还是挺像看的哈哈

**Comment by lrinQVQ** [comment]
咩你提供域名我就能加2333

**Comment by jerossh** [comment]
只要谷歌能用就好拉。百度的搜索质量真的是和百度公司一样混乱。

**Comment by yangmengli** [comment]
@lrinQVQ 我是要通过抓包获取到直播都访问了哪些host么。。。

**Comment by lrinQVQ** [comment]
F12 Network 233

**Comment by DDoSolitary** [comment]
我看了一下，只是DNS污染的样子，我来做吧

**Comment by yangmengli** [comment]
@DDoSolitary 给力

**Comment by DDoSolitary** [comment]
@yangmengli 加了

**Comment by yangmengli** [comment]
@DDoSolitary 收到3Q,我把这个issues关掉吧,好几个twitter的issues
