### ISSUE TITLE
iOS修改hosts问题

### ISSUE THREAD

**Issue by Grox-Ni** [racaljk/hosts#1172]
在iOS(9.3.2越狱）修改Hosts后越狱失效，整个手机处于半越狱的状态，拍照都不能拍。（手机的Limbo状态233）

手动恢复出厂失败（TATSU declined to authorize this image on this device for this user）

搜了谷歌貌似没有和我一样问题的人

**Comment by Too-Naive** [comment]
修改hosts和越獄沒有直接的聯繫吧

**Comment by Grox-Ni** [comment]
对于越狱的app，iPhone显示无法验证（它说要通过一个apple的服务器验证，但现在这个服务器是“无法验证的”）
此外很多要上网的软件（不是Web）都是不能上网的，比如阴阳师
但Facebook意外的好用

**Comment by lychichem** [comment]
不是说移动设备不建议用hosts么

**Comment by DDoSolitary** [comment]
hosts中没有任何与Apple服务器有关的内容，应该不关hosts的事

**Comment by lrinQVQ** [comment]
项目里面基本上都是官网ip2333 除了IOS对反代的支持不太好以外 Andorid/WP貌似都ok的
