### ISSUE TITLE
谷歌挂 

### ISSUE THREAD

**Issue by cjkzwe** [racaljk/hosts#1173]
一直挂，什么情况？
山东联通

**Comment by lrinQVQ** [comment]
https://github.com/racaljk/hosts/commit/632ac8c8858389cb825d59b79913f80b0f2318c0

**Comment by 0915240** [comment]
挂的受不了了 先找了个SS救急下 _(:зゝ∠)_

**Comment by Too-Naive** [comment]
近期掛比較正常 過一段時間會好一點

**Comment by wangchunming** [comment]
重启路由器重新拨号后如果还无法访问那就是谷歌真的挂了，用SNI吧。。。。
Twitter最近无法访问的原因是因为郭文贵事件原因导致的大面积https干扰。（谁说的墙不可以根据返回证书杀ip的）

**Comment by wangchunming** [comment]
如果这里的不能用的话你也可以来这里看看，我也是山东的，我在莱芜联通和移动下面测试过都能用的，说不定也能满足你部分需求。https://github.com/wangchunming/2017hosts

**Comment by lrinQVQ** [comment]
2333确实是不能的呀 twitter的ip依然还有的 只是我不Push了

**Comment by wilon** [comment]
#1183 试试换个IP

**Comment by p0mp0k0** [comment]
北京，移动、联通和电信均不行

**Comment by lrinQVQ** [comment]
fix now
