### ISSUE TITLE
求修复dropbox

### ISSUE THREAD

**Issue by delta000** [racaljk/hosts#1175]
有大约一周了，173.239无法连接, connect refused.但是能PING通

**Comment by wangchunming** [comment]
Hi
这里的hosts因为是官方ip缘故，所以更新非常慢（找ip费事），如果这里的不能用的话你也可以来这里看看，说不定也能满足你部分需求。https://github.com/wangchunming/2017hosts

**Comment by lrinQVQ** [comment]
orz并不是慢也不是费事 现在继续更新IP就是等于作死= =

**Comment by delta000** [comment]
谢谢，的确感觉这里有可能被盯上了，放出来的IP不久就会失效
