### ISSUE TITLE
Can't ping atom.io

### ISSUE THREAD

**Issue by TonyZZX** [racaljk/hosts#1176]
atom.io ping不通（不加https），希望能加入到list中

**Comment by lrinQVQ** [comment]
服务器禁ping而已 sudo hping3 -S -p 443 atom.io     
[sudo] lrin 的密码：
HPING atom.io (enp0s31f6 23.21.51.84): S set, 40 headers + 0 data bytes
len=46 ip=23.21.51.84 ttl=228 DF id=0 sport=443 flags=SA seq=0 win=26883 rtt=263.8 ms
len=46 ip=23.21.51.84 ttl=228 DF id=0 sport=443 flags=SA seq=1 win=26883 rtt=255.7 ms
len=46 ip=23.21.51.84 ttl=228 DF id=0 sport=443 flags=SA seq=2 win=26883 rtt=255.6 ms
len=46 ip=23.21.51.84 ttl=228 DF id=0 sport=443 flags=SA seq=3 win=26883 rtt=271.5 ms
