### ISSUE TITLE
Google Blogger无法访问，希望加入！

### ISSUE THREAD

**Issue by aishangll** [racaljk/hosts#1177]

**Comment by lychichem** [comment]
blogger的话，如果能用dnsmasq当然最好，不然每个博客都写一条早就累死了，你可以自行把需要访问的博客地址指定到blogspot的ip上

**Comment by imknown** [comment]
谷歌自己开的 blogger 还是 别人注册的?

**Comment by wangchunming** [comment]
别人注册的没办法，但是谷歌的blogger那改了访问不了那就没办法了，只能等待换ip。

**Comment by DDoSolitary** [comment]
hosts没有泛解析能力，无解。。

**Comment by lychichem** [comment]
@DDoSolitary 咱们这个项目里有dnsmasq的配置文件啊2333

**Comment by DDoSolitary** [comment]
@lychichem 是用脚本生成的，目前并没有办法支持泛解析
#1213
