### ISSUE TITLE
您好，请合并以下提交

### ISSUE THREAD

**Issue by huangsen365** [racaljk/hosts#1179]
#Update hosts
#Add below records
61.91.161.217	domains.google
61.91.161.217	environment.google

https://github.com/huangsen365/hosts/commit/9d22d8efa0aa7899057128304e386b7551987804

**Comment by yangmengli** [comment]
61.91.161.217这个ip好像都是超时啊

**Comment by wangchunming** [comment]
这个ip已经不能用了，新的ip正在找。

**Comment by lrinQVQ** [comment]
orz 等风声过后我在更新

**Comment by lrinQVQ** [comment]
话说这个是做什么用的xd

**Comment by Ir1d** [comment]
Google卖域名的和保护环境的？

**Comment by lrinQVQ** [comment]
应该是的咩233

**Comment by lrinQVQ** [comment]
添加了

**Comment by huangsen365** [comment]
lrinQVQ  您好，为什么你们不是通过我的链接去commit https://github.com/huangsen365/hosts/commit/9d22d8efa0aa7899057128304e386b7551987804

**Comment by huangsen365** [comment]
@lrinQVQ

**Comment by huangsen365** [comment]
@lrinQVQ 在这个开源项目里，我们作为 contributors 其中一员，为什么我们的 commit 动作不能正式呈现在 https://github.com/racaljk/hosts/commits/master 这里呢？

**Comment by lrinQVQ** [comment]
@huangsen365 欸除非你提交PR否则我们是无法合并你的提交啊xd 而且现在项目要求在hosts-source进行更新您直接在master分支进行了修改 orz会被替换的啊 所以我就直接手动修改提交了抱歉咳咳

**Comment by lrinQVQ** [comment]
2333要不要我直接撤销了您重新提交一下

**Comment by huangsen365** [comment]
这次就这样先吧，没事的，我只是觉得你们作为项目相关管理者可以好好引导contributors去遵循这些commit原则就行了，只有这样的项目才能获得更高的活跃度，才能有更多机会给墙内同胞们跨越长城

**Comment by lrinQVQ** [comment]
23333我的锅啦orz 主要是您发的不是PR 而且README里面有详细的介绍啊～ https://github.com/racaljk/hosts/tree/master#如何贡献
如果是要保留您的commit信息请发PR
如果是issues请求添加orz我要是一个一个问得等到猴年马月啊xd 我就默认为其他人手动添加了

**Comment by Ir1d** [comment]
@huangsen365 您好
在您开issue的时候有这样一段话
>* 欢迎使用 Pull Requests 功能（可以通过[直接编辑文件](https://github.com/racaljk/hosts/edit/master/hosts)的方式来提交）

**Comment by DDoSolitary** [comment]
`git remote add`加上`git merge`就可以不用PR主动merge了吧

**Comment by huangsen365** [comment]
@Ir1d 是的，我当时没怎么看到这句话，你们可以把那句话加粗或者稍微调整一下描述字句的层次结构么？比如针对不同role的人士，在句前做个提醒。
谢谢你们了！

**Comment by huangsen365** [comment]
@DDoSolitary 下次我试试，thanks!

**Comment by Ir1d** [comment]
@DDoSolitary 可是有冲突了吧

**Comment by DDoSolitary** [comment]
有冲突也可以merge的吧。。
