### ISSUE TITLE
无法连接到chorme， 是不是有问题了

### ISSUE THREAD

**Issue by DC-Joney** [racaljk/hosts#1180]

**Comment by wangchunming** [comment]
这里的hosts因为是官方ip，更新非常慢（找ip费事），如果这里的不能用的话你也可以来这里看看，说不定也能满足你部分需求。https://github.com/wangchunming/2017hosts

**Comment by lrinQVQ** [comment]
orz并不是慢也不是费事 现在继续更新IP就是等于作死= =

**Comment by DC-Joney** [comment]
好的，因为以前总是用这里的hosts文件而且以前的hosts文件上google是没问题的 所以才在这里提问的，谢谢各位

**Comment by lrinQVQ** [comment]
小意思啦~ 这两天确实有些异常 看我这里的监控情况 估计周五能有所缓解

**Comment by DC-Joney** [comment]
收到，非常感谢您这么长时间以来提供的帮助，谢谢

**Comment by lrinQVQ** [comment]
感谢大家啦2333这个项目是大家一起维护的

**Comment by DC-Joney** [comment]
:1st_place_medal: :+1:

**Comment by Too-Naive** [comment]
@racaljk 建議 
![](https://user-images.githubusercontent.com/16496671/26875100-e538b1d0-4bb2-11e7-8900-bec8bc2bc596.png)

**Comment by lrinQVQ** [comment]
@racaljk

**Comment by lrinQVQ** [comment]
123.147.85.224
在下周以前如果急用orz可以试下 只能解决谷歌基础服务/Youtube部分视频/DNS污染的域名

**Comment by racaljk** [comment]
转眼已经到周末了

**Comment by lrinQVQ** [comment]
233333是的

**Comment by lrinQVQ** [comment]
@racaljk 现在不用停用啦orz 貌似干扰已经在减少了

**Comment by lrinQVQ** [comment]
443干扰已经停止了 可以开始更新了

**Comment by lrinQVQ** [comment]
已经修复咩
