### ISSUE TITLE
Gmail的smtp服务器地址被删除

### ISSUE THREAD

**Issue by lxylxy123456** [racaljk/hosts#1182]
我在中国尝试手动给gmail.com的地址写电子邮件，但是相关地址被屏蔽了。
几个月前这个项目中还有`gmail-smtp-in.l.google.com`的记录，但是现在好像被删除了。
希望添加以下五个域名的记录，目标和google.com的记录(64.233.188.27)相同即可。
`gmail-smtp-in.l.google.com`
`alt1.gmail-smtp-in.l.google.com`
`alt2.gmail-smtp-in.l.google.com`
`alt3.gmail-smtp-in.l.google.com`
`alt4.gmail-smtp-in.l.google.com`
附：目前gmail.com的mx记录为
    `gmail.com	mail exchanger = 10 alt1.gmail-smtp-in.l.google.com.`
    `gmail.com	mail exchanger = 40 alt4.gmail-smtp-in.l.google.com.`
    `gmail.com	mail exchanger = 30 alt3.gmail-smtp-in.l.google.com.`
    `gmail.com	mail exchanger = 5 gmail-smtp-in.l.google.com.`
    `gmail.com	mail exchanger = 20 alt2.gmail-smtp-in.l.google.com.`

**Comment by lrinQVQ** [comment]
感谢啦～合并了
