### ISSUE TITLE
更快的 Google IP 地址

### ISSUE THREAD

**Issue by wilon** [racaljk/hosts#1183]
由于本项目 `hosts` 访问 Google 有点卡，所以找了些快点的 Google IP 地址。
  使用方法：将`hosts` 内 Google 的 IP 替换换为下列 IP 之一，保存到本机host文件。

```
    172.217.24.209
    172.217.24.201
    172.217.24.56
    216.58.200.13
    172.217.24.195
    172.217.24.220
    172.217.24.53
    172.217.24.200
    216.58.200.1
    172.217.24.61
    216.58.200.29
    216.58.200.30
    172.217.24.214
    172.217.24.216
    216.58.200.15
    216.58.200.22
    172.217.24.50
    172.217.24.43
    172.217.24.202
```

----
以上IP经北京联通测试Google可用打开。有不可用的回复下我会删除。

**Comment by lrinQVQ** [comment]
....这几天风声紧啊...周五以后在来更新好不好QwQ

**Comment by laodcn** [comment]
最近见光死，建议下周再更！

**Comment by lrinQVQ** [comment]
+1

**Comment by wilon** [comment]
@lrinQVQ 还真是封的频繁啊，那就 close 这个 issue 吧。

那之后此项目更新能不能维护一个 `host.back-up`，分分流，大家都用那个IP，上Google太慢啦。

**Comment by wangchunming** [comment]
在山东移动这里，你的ip没有一个可用的。
建议你找ip的时候，找些在线ping工具放进里面测试看看，只要超过两个地方超时，那么这ip就是都不可以用的了。

**Comment by lrinQVQ** [comment]
@wilon 如果此项目下周更新还是见光死的话orz 可能就...

**Comment by tikdik** [comment]
这里面虽然很多地址可以ping通，但端口80和443并没打开

**Comment by tikdik** [comment]
刚刚用上一个ip，没到2分钟端口就不通了，这是啥子鸟情况

**Comment by lrinQVQ** [comment]
线路问题(●—●)
