### ISSUE TITLE
请求添加steam相关hosts

### ISSUE THREAD

**Issue by zyf2008Neptune** [racaljk/hosts#1184]
最近steam经常连不上，请求添加steam相关hosts，谢谢！

**Comment by lrinQVQ** [comment]
orz 是的steam也被墙了

**Comment by lrinQVQ** [comment]
下周一起更新

**Comment by lrinQVQ** [comment]
之前DNS污染好像orz

**Comment by zyf2008Neptune** [comment]
电信的网，经常连接重置，之前用贴吧里的host解决了，现在又连接重置了。

**Comment by lrinQVQ** [comment]
DNS污染了咩

**Comment by LGA1150** [comment]
http://www.17ce.com/site/http/201706_3283a980aeaf9259ee09a44ab24c6c48.html 
其实是电信国际出口的问题，延迟高的几乎都是电信

**Comment by zyf2008Neptune** [comment]
关键电信还把几个延迟低的hosts连接重置了。

**Comment by LGA1150** [comment]
中国电信，世界加钱可及

**Comment by lychichem** [comment]
steam的话，我今天在微博看到的最新说法是有人搞事，贴吧也有人说了：https://tieba.baidu.com/p/5164041299?pn=0&

**Comment by lrinQVQ** [comment]
@lychichem 其实orz 真的只是DNS污染

**Comment by lrinQVQ** [comment]
104.115.141.219 store.steampowered.com

**Comment by zyf2008Neptune** [comment]
这个会触发关键词过滤，但是电信确实墙的死死的，部分hosts倒是一直能用。

**Comment by lrinQVQ** [comment]
没问题了我就关了咩0.0

**Comment by adoyle-h** [comment]
所以改 host 到底能不能连上 steam？

**Comment by Too-Naive** [comment]
不是已经给你一个hosts条目了吗
