### ISSUE TITLE
MediaFire IP

### ISSUE THREAD

**Issue by CrackFileso** [racaljk/hosts#1186]
AES Public key:  U2FsdGVkX1+f9aZCTCKqzrmYYFkgFMYZC2HJsfwGZwY=
(Decryption key: SS)

防止暴毙，加密了，请原谅

**Comment by lrinQVQ** [comment]
thanks 2333,突然有个想法 把ip加密如何

**Comment by lrinQVQ** [comment]
其实xd 怎么都没用

**Comment by laodcn** [comment]
加密有什么用，你能加密别人就能解密

**Comment by EMLVIRUS** [comment]
OpenPGP 算法没有私钥，要暴力解，有点难度吧。。。

**Comment by zyf2008Neptune** [comment]
加密也没用啊，毕竟必须公开才能使用。

**Comment by DDoSolitary** [comment]
关键在于如何分发密钥啊。。

**Comment by DDoSolitary** [comment]
@CrackFileso 话说你这AES加密的cipher mode也没说，padding mode也没说，叫我怎么解密啊。。我用ECB解出来是乱码，别的cipher mode的话你也没提供IV。。
而且mediafire并没有被墙吧。。
