### ISSUE TITLE
HumbleBundle商店提示安全证书存在问题

### ISSUE THREAD

**Issue by Observateurs** [racaljk/hosts#1188]
询问了几个好友，都有这样的问题
希望大佬能解决
![20170610204010](https://user-images.githubusercontent.com/13134143/27002820-5e74ecaa-4e1d-11e7-949b-785686df96f3.png)
![20170610204234](https://user-images.githubusercontent.com/13134143/27002821-5e795222-4e1d-11e7-8344-c590151f8a24.png)

**Comment by 123ysys** [comment]
可以试々换浏览器或关掉防火墙。
