### ISSUE TITLE
建议添加一些游戏的Hosts

### ISSUE THREAD

**Issue by Observateurs** [racaljk/hosts#1189]
来源：[SteamCN](https://steamcn.com/t141196-1-1)

H1Z1 (解决封锁大陆IP无法登入)
`172.245.126.217 lpj.daybreakgames.com`
绝地求生 (解决游戏进入/退回主界面时连接困难)
`172.245.126.217 front.battlegroundsgame.com`

**Comment by SerCom-KC** [comment]
我记得这个IP不是官方服务器而是某个人自己搭的服务器吧
仅凭这一点就已经进不了这个项目了……

**Comment by lrinQVQ** [comment]
52.85.82.129 front.battlegroundsgame.com或许可以的?

**Comment by ARROWBOW** [comment]
个人搭服务器怎么赢利啊

**Comment by DDoSolitary** [comment]
两个不同游戏的服务器用同一个IP，显然是非官方的吧
@ARROWBOW 为什么非要盈利，你看这个hosts项目盈利吗？
