### ISSUE TITLE
twitter挂了

### ISSUE THREAD

**Issue by leixinstar** [racaljk/hosts#1193]
RT

**Comment by DDoSolitary** [comment]
+1

**Comment by lrinQVQ** [comment]
twitter怕是有点伤了_(:з」∠)_

**Comment by lychichem** [comment]
推封得太快了

**Comment by lrinQVQ** [comment]
今天修了太多了... 明天在来继续xd

**Comment by XiGou** [comment]
最近管的太紧了，赵老爷们该不会把电缆炸了吧

**Comment by lrinQVQ** [comment]
23333不敢的

**Comment by lrinQVQ** [comment]
mmp twitter杀得太狠了

**Comment by hillwoodroc** [comment]
我找出来的 IP 都被封了。

**Comment by wangchunming** [comment]
twitter最近因为老郭这事情闹得真是很那啥。

**Comment by lrinQVQ** [comment]
+1 xd真的麻烦

**Comment by ARROWBOW** [comment]
汤不热也不管用了，希望大神能够修复吧
这个真心不错，原来用的泰国的hosts都没这个快
github真心是个好组织  赞赞赞赞赞赞

**Comment by Cyoudgax** [comment]
可能是这个月在twitter搞大新闻搞太多被往死里打。

**Comment by percysanchez** [comment]
今天更新完twitter访问不了的替换成这个：
121.59.17.8	twitter.com
121.59.17.8	www.twitter.com
219.76.4.75	t.co
121.59.17.8	api.twitter.com
121.59.17.8	caps.twitter.com
121.59.17.8	mobile.twitter.com
121.59.17.8	support.twitter.com
121.59.17.8	upload.twitter.com
121.59.17.8	tweetdeck.twitter.com
121.59.17.8	syndication.twitter.com
121.59.17.8	platform.twitter.com
121.59.17.8	about.twitter.com
121.59.17.8	blog.twitter.com
121.59.17.8	betastream.twitter.com
121.59.17.8	dev.twitter.com
121.59.17.8	pic.twitter.com
121.59.17.8	search.twitter.com
121.59.17.8	status.twitter.com
121.59.17.8	assets0.twitter.com
121.59.17.8	assets1.twitter.com
121.59.17.8	assets2.twitter.com
121.59.17.8	assets3.twitter.com
121.59.17.8	assets4.twitter.com
121.59.17.8	static.twitter.com
121.59.17.8	help.twitter.com
121.59.17.8	ton.twitter.com
121.59.17.8	s.twitter.com
121.59.17.8	analytics.twitter.com
121.59.17.8	urls-real.api.twitter.com
121.59.17.8	userstream.twitter.com
121.59.17.8	sitestream.twitter.com
121.59.17.8	stream.twitter.com
121.59.17.8	tdweb.twitter.com
121.59.17.8	cdn.syndication.twitter.com
121.59.17.8	apps.twitter.com
121.59.17.8	debates.twitter.com
121.59.17.8   ads.twitter.com
121.59.17.8 *twitter.com
104.244.46.244	twitpic.com
104.244.46.244	m1.twitpic.com
104.244.46.244	web1.twitpic.com
104.244.46.244	web10.twitpic.com
104.244.46.244	web2.twitpic.com
104.244.46.244	web3.twitpic.com
104.244.46.244	web4.twitpic.com
104.244.46.244	web5.twitpic.com
104.244.46.244	web6.twitpic.com
104.244.46.244	web7.twitpic.com
104.244.46.244	web8.twitpic.com
104.244.46.244	web9.twitpic.com
104.244.46.244	*.twitpic.com
104.244.46.71	a0.twimg.com
104.244.46.71	a1.twimg.com
104.244.46.71	a2.twimg.com
104.244.46.71	a3.twimg.com
104.244.46.71	a4.twimg.com
104.244.46.71	a5.twimg.com
104.244.46.71	video.twimg.com
104.244.46.71	abs.twimg.com
104.244.46.71	g.twimg.com
104.244.46.71	hca.twimg.com
104.244.46.71	o.twimg.com
104.244.46.71	p.twimg.com
104.244.46.71	r.twimg.com
104.244.46.71	ma.twimg.com
104.244.46.71	pbs.twimg.com
104.244.46.71	pbs-h2.twimg.com
104.244.46.71	ton.twimg.com
104.244.46.71	syndication.twimg.com
104.244.46.71	syndication-o.twimg.com
104.244.46.71	image-proxy-origin.twimg.com
104.244.46.71	cdn.syndication.twimg.com
104.244.46.71	*.twimg.com
104.244.45.246	tweetdeck.com
104.244.45.246	api.tweetdeck.com
104.244.45.246	web.tweetdeck.com
104.244.45.246	www.tweetdeck.com
104.244.45.246	downloads.tweetdeck.com

**Comment by lrinQVQ** [comment]
https://github.com/racaljk/hosts/issues/1349
