### ISSUE TITLE
请提供win版本的host

### ISSUE THREAD

**Issue by sky5454** [racaljk/hosts#1196]
你好，Linux与Windows换行符不同
希望提供一下win版本的host，这样方便我用以下脚本获取：

`@echo off`
`cd /d %~dp0`
`wget -t 5 -w 120 -nv -O hosts -a wget.log https://coding.net/u/scaffrey/p/hosts/git/raw/master/hosts`
`move /y hosts %SystemRoot%\System32\drivers\etc\hosts >> wget.log`
`echo ^.^ >> wget.log`

这个方法需要管理员运行，并且可以将其加到Windows计划任务中

**Comment by lrinQVQ** [comment]
https://github.com/HostsTools

**Comment by sky5454** [comment]
我不是要这个，我要的是已经转换好换行符的hosts文件

**Comment by lrinQVQ** [comment]
https://github.com/racaljk/hosts/blob/master/hosts这个就是啊0.0

**Comment by sky5454** [comment]
你好，Linux的换行符是LF，Windows的换行符是CRLF，不一样的。用对应的换行符才能使hosts生效。

**Comment by lrinQVQ** [comment]
这没有影响啊xd

**Comment by lrinQVQ** [comment]
用Win自带的Notepad打开得确会混乱但是LF也好CRLF也好CR也好,hosts并不会因此受到影响啊xd 除非是编码问题,你可以用Notepad++打开看看就知道了 @sky5454

**Comment by sky5454** [comment]
那应该是谷.歌ip挂了

**Comment by lrinQVQ** [comment]
IP挂的确实orz 我还在忙着找
