### ISSUE TITLE
surge配置文件有问题

### ISSUE THREAD

**Issue by digicolor** [racaljk/hosts#1201]
surge不认“app.box.com,api.box.com,account.box.com,upload.box.com,m.box.com = 107.152.25.197”，显示“illegal hostname”，需要手动修改才行

**Comment by lrinQVQ** [comment]
我的锅 我手残xd 改好了

**Comment by lrinQVQ** [comment]
https://github.com/racaljk/hosts/commit/93965d4c57a31c1911d56d5547a2c38f60aa9b10
