### ISSUE TITLE
求能上雅虎！！！！！！！！！！！

### ISSUE THREAD

**Issue by dingminghbut** [racaljk/hosts#1206]
好想都上不了雅虎！！！！

**Comment by lrinQVQ** [comment]
啧雅虎炸了0.0

**Comment by 123ysys** [comment]
雅虎不是可以上的么？

**Comment by dingminghbut** [comment]
雅虎一直上不了》》》？？？


2017-06-16 17:16 GMT+08:00 123ysys <notifications@github.com>:

**Comment by wangchunming** [comment]
https://github.com/wangchunming/2017hosts

**Comment by lrinQVQ** [comment]
@wangchunming = = 不要太过分了啊

**Comment by DDoSolitary** [comment]
@wangchunming 你要宣传你的项目没问题，但是你这样反复在这里发是不是不太好呢，毕竟issue不是用来干这种事的地方

**Comment by 123ysys** [comment]
@lrinQVQ 要不直接close算了。

**Comment by lrinQVQ** [comment]
@123ysys 我稍后修复咩在close吧2333

**Comment by lrinQVQ** [comment]
发现IP没问题啊= =close好了
