### ISSUE TITLE
google fit 貌似连不上

### ISSUE THREAD

**Issue by woshidani** [racaljk/hosts#1210]
Google fit 提示无法同步账号信息。
换回默认hosts挂vpn后可以连接上，
但是不换回默认hosts挂vpn也连不上。

(新手不太会用github，抱歉抱歉~

**Comment by lrinQVQ** [comment]
0.0 我看看

**Comment by Ir1d** [comment]
如何同步账号信息……？
看起来没什么异常
或许是宽带症？

**Comment by woshidani** [comment]
![s70618-155825](https://user-images.githubusercontent.com/28482699/27414062-93148646-56c4-11e7-80df-954f78ef51a2.jpg)
就是这个样子，账号信息什么的加载不出来。。

**Comment by Ir1d** [comment]
阿
我看的是网页版正常233
可以抓一下包吗

**Comment by lrinQVQ** [comment]
+1 2333

**Comment by woshidani** [comment]
用哪个工具来抓呢？(´･ω･`)

**Comment by lrinQVQ** [comment]
咩～来来来

**Comment by lrinQVQ** [comment]
你需要一个Paacket Capture~ @woshidani

**Comment by lrinQVQ** [comment]
干脆我来好了咩2333

**Comment by lrinQVQ** [comment]
lax28s01-in-f10.1e100.net

**Comment by lrinQVQ** [comment]
@woshidani 你看看你是不是这个域名咩0.0

**Comment by woshidani** [comment]
![s70622-105323](https://user-images.githubusercontent.com/28482699/27415363-46e701b0-56cc-11e7-91e7-1e74e572d24a.jpg)
好像是这个样子。。

**Comment by lrinQVQ** [comment]
2333打开尝试同步下 @woshidani

**Comment by woshidani** [comment]
还是刚才那个样子(ㄒoㄒ)

**Comment by lrinQVQ** [comment]
没事没事咩～我添加了你试试

**Comment by woshidani** [comment]
嗯嗯嗯，谢谢大佬(*´∀`)~♥

**Comment by lrinQVQ** [comment]
2333小意思啦～ 等编译好了试试吧

**Comment by lrinQVQ** [comment]
@woshidani 好了咩更新试下吧2333

**Comment by lrinQVQ** [comment]
感觉应该是有规律的域名咩2333

**Comment by woshidani** [comment]
(⊙o⊙)哇这么快，，我试试

**Comment by lrinQVQ** [comment]
233嗯嗯试试吧生成文件而已啦2333很快的

**Comment by lrinQVQ** [comment]
真的是随机域名呢咩 我想想怎么破2333

**Comment by lrinQVQ** [comment]
tsa03s01-in-f10.1e100.net还是有规律可循的咩

**Comment by woshidani** [comment]
我这里可以连上了(≧∇≦)/

**Comment by lrinQVQ** [comment]
wow太好啦～恭喜你

**Comment by lrinQVQ** [comment]
机场三字代码+数字+s+01+-in-f10.1e100.net

**Comment by lrinQVQ** [comment]
我去把它补全吧23333333

**Comment by woshidani** [comment]
好复杂(((ﾟДﾟ;)))

**Comment by lrinQVQ** [comment]
是哒2333超级复杂呢

**Comment by woshidani** [comment]
辛苦了辛苦了～(^з^)-☆

**Comment by lrinQVQ** [comment]
小意思啦～2333
