### ISSUE TITLE
YouTube视频求测试咩

### ISSUE THREAD

**Issue by lrinQVQ** [racaljk/hosts#1211]

**Comment by lrinQVQ** [comment]
我这里是可用的 求大家测试

**Comment by lrinQVQ** [comment]
本地测试了30个视频已可行 2333

**Comment by lrinQVQ** [comment]
219.76.4.11的证书适用于*.googlevideo.com 而且此类ip很多啊

**Comment by lrinQVQ** [comment]
woc172.217.11.174瞬间443干扰

**Comment by sy618** [comment]
你才知道？/手动滑稽
https://raw.githubusercontent.com/sy618/hosts/master/y

**Comment by lrinQVQ** [comment]
@sy618 等下咩我卖萌了 这不是官网的xd

**Comment by sy618** [comment]
看视频的官方IP就不用试了。
即使那个官方IP没被墙，由于YouTube最近被大炮攻击，谷歌也把大陆IP封了。

**Comment by lrinQVQ** [comment]
@sy618 不会的2333

**Comment by lrinQVQ** [comment]
咩你可以做等打脸了2333

**Comment by lrinQVQ** [comment]
mmp 这个线路有毒 104.237.160.153时好时坏的==

**Comment by sy618** [comment]
YouTube视频的IP是必须对应sn机场编码地区。
https://github.com/lennylxx/ipv6-hosts/wiki/YouTube#4-sn-%E7%BC%96%E7%A0%81%E5%9C%B0%E5%9D%80

**Comment by sy618** [comment]
也就是说，除非解除IP封锁与DNS污染，不然只能通过代理或反代来实现YouTube视频播放功能。

**Comment by lrinQVQ** [comment]
这个问题到时候我会解释的23333
