### ISSUE TITLE
部分配置文件的泛解析方案

### ISSUE THREAD

**Issue by DDoSolitary** [racaljk/hosts#1213]
https://github.com/racaljk/hosts/issues/1142#issuecomment-309207639

**Comment by DDoSolitary** [comment]
大概想了一下，单纯自动生成泛解析条目已经想到基于树形DP的算法了
但是问题在于对于以下的情况，没有人工维护恐怕是无法解决的

---
若有三个域名
```
a.foo.com -> ip1
b.foo.com -> ip1
c.foo.com -> ip2
```
现`a.foo.com`和`b.foo.com`被封锁，需在hosts中指向`ip3`，那么就会生成`*.foo.com -> ip3`的条目，这时就会影响到本不想重定向的`c.foo.com`

**Comment by mewsf** [comment]
感觉随着hosts的复杂度的增加，用hosts就越来越不如用dnsmasq和bind这类软件，可是hosts又是最简单的办法 ，很让人纠结

**Comment by lrinQVQ** [comment]
如果说加上一个flag呢 让维护者定义需要范解析的使用范解析 其实就比如twitter的platform.twitter.com就不能使用*.twitter.com的ip

**Comment by lrinQVQ** [comment]
泛解析的话 在不人工维护的情况下的确很难
就像DDoSolitary说的那样 有可能a.foo.com和b.foo.com指向的是ip1 c.foo.com指向的是ip2 如果进行泛解析c.foo.com就会受影响 而且在dnsmasq中addn-hosts中的配置文件优先级会大于address
如果说我们把可以泛解析的域名单独提出来
我们进行对比
比如
-----------------------------------
a.foo.com 1.1.1.1
b.foo.com 1.1.1.1
c.foo.com 2.2.2.2
那么把a.foo.com 以及1.1.1.1提取出来
假设1=a.foo.com
1-ip=1.1.1.1
2=b.foo.com
2-ip=1.1.1.1
3=c.foo.com
3-ip=2 2.2.2
以.为界限 先判断域名在判断ip(回家在写xd)只是一个想法昂

**Comment by DDoSolitary** [comment]
我的意思是说如果`c.foo.com`没有被封锁，不需要加到hosts中的话，就比较麻烦了

**Comment by lrinQVQ** [comment]
是啊xd

**Comment by lrinQVQ** [comment]
我的想法也是这样

**Comment by lrinQVQ** [comment]
所以我说 我们把可以泛解析的域名单独提出来23333不过貌似xd也是手动

**Comment by sy618** [comment]
确实比较麻烦，dnsmasq的泛解析确实强大，不过误伤也厉害。
只能独立出来手动维护与优化才行。
http://right.com.cn/forum/thread-216155-1-1.html
我自己做了个规则，部署在路由器上用了一阵子感觉很爽。

**Comment by lrinQVQ** [comment]
https://github.com/racaljk/hosts/issues/1349
