### ISSUE TITLE
silly question--“无法解析主机”

### ISSUE THREAD

**Issue by CaptShaw** [racaljk/hosts#1216]
刚入门linux，/bin/sh 成功运行了脚本lhosts，可以正常翻墙，再次运行发现/bin/sh: 0:Can't open ./lhosts
重启以后发现无法解析主机，上网功能不受影响。
请问有人可以解答一下嘛q_q
btw GitHub也是第一次用，不知道在这儿提问对不对0_0 @racaljk @Too-Naive

**Comment by lrinQVQ** [comment]
咩0.0 手动加下127.0.0.1 用户名

**Comment by Ir1d** [comment]
#962
