### ISSUE TITLE
Opera mini (Android) 无法使用

### ISSUE THREAD

**Issue by emaryix** [racaljk/hosts#1222]
Connection seems to be blocked 🔗🚫
Please add [this file](https://github.com/racaljk/hosts/files/1090232/opera-mini.zip) to the host 📁➕

**Comment by lrinQVQ** [comment]
These ip is SNI ?0.0

**Comment by emaryix** [comment]
Yes, These IP is SNI

**Comment by lrinQVQ** [comment]
These domains only DNS contamination,we can use official ip~
such as:107.167.115.253 mini5.opera-mini.net

**Comment by emaryix** [comment]
OK, Please add official IP to the host.

**Comment by lrinQVQ** [comment]
Ok~ I add ing

**Comment by lychichem** [comment]
@IrinQVQ your English…

**Comment by lrinQVQ** [comment]
@lychichem 23333

**Comment by lrinQVQ** [comment]
@lychichem china english

**Comment by lychichem** [comment]
@lrinQVQ 我按你的意思重新翻译一下回复……
These IPs are SNI?
These domains are only DNS polluted. 
I'm adding.
所以我们还是用中文回复吧……不然这样实在感觉有点丢脸……

**Comment by lrinQVQ** [comment]
23333欸 说不定啊老外我才用英文的啊

**Comment by lrinQVQ** [comment]
加好了2333
