### ISSUE TITLE
Youtube videos not loading

### ISSUE THREAD

**Issue by Mo101ali** [racaljk/hosts#1224]
hello, youtube videos are not loading and i don't know to fix it. is there any solution for this?

**Comment by atreeyang** [comment]
co ask

**Comment by qq274936784** [comment]
co ask.

**Comment by Too-Naive** [comment]
https://github.com/racaljk/hosts/wiki/The-hosts-FAQ#%E4%B8%BA%E4%BB%80%E4%B9%88-hosts-%E6%97%A0%E6%B3%95%E6%92%AD%E6%94%BE-youtube-%E8%A7%86%E9%A2%91

**Comment by lrinQVQ** [comment]
咱们来个英文版吧xd 挺多国外友人的2333

**Comment by Too-Naive** [comment]
外国人should use VPN?

**Comment by Mo101ali** [comment]
现在我在大学。i tried a lot of hosts including this one. but everything works except youtube videos. they keep loading and buffering. i also tried cleaning my DSN and a lot of stuffs but still not working

**Comment by lrinQVQ** [comment]
@Mo101ali Because Youtube's SN encoding domain name (encoding rules) is fixed IP, and these IP has been basically blocked, so even if you can open the Youtube home page, it can not load the video

**Comment by Ir1d** [comment]
You should use vpn instead.
