### ISSUE TITLE
dropbox 问题

### ISSUE THREAD

**Issue by saitofun** [racaljk/hosts#1226]
dropbox出现403错误
环境: MacOSX Safari 
commit 39c30847e6f48ff50dfd8f1243238037c29b6c6d (HEAD -> master, origin/master, origin/HEAD)
Author: lrinQVQ <cqlrin@gmail.com>
Date:   Thu Jun 22 04:06:43 2017 +0000

    fix typo

**Comment by GengTianyu** [comment]
windows ，同样出现403问题

**Comment by Pictor** [comment]
Dropbox 的 hosts 条目提供了 4 个 IP，其中：

- 指向 Dropbox 首页的 108.160.173.239 返回 403 Forbidden 错误；

- 反复使用的 108.160.173.193 是个不可用的 IP；

- 162.125.3.6 可用，但是 162.125.2.6 更快一些；

- 104.16.100.29 只能对应 cfl.dropboxstatic.com，用在其他域名上将导致证书错误。

我查询了 hosts 中的各个域名所解析出的 IP，选取了其中延迟最低的，结果如下：

`162.125.248.1	dropbox.com`
`162.125.248.1	www.dropbox.com`
`162.125.32.9	db.tt`
`162.125.32.14	www.v.dropbox.com`
`162.125.7.1	www.dropbox-dns.com`
`162.125.82.7	api.dropbox.com`
`162.125.32.5	api-d.dropbox.com`
`162.125.82.7	api.dropboxapi.com`
`162.125.32.13	api.v.dropbox.com`
`162.125.32.13	api-notify.dropbox.com`
`162.125.1.8	api-content.dropbox.com`
`162.125.2.5	api-content-photos.dropbox.com`
`52.85.12.34	blogs.dropbox.com`
`162.125.32.2	block.dropbox.com`
`162.125.34.133	block.v.dropbox.com`
`162.125.18.133	bolt.dropbox.com`
`162.125.2.3	client.dropbox.com`
`162.125.32.12	client.v.dropbox.com`
`162.125.80.3	client-lb.dropbox.com`
`162.125.2.3	client-cf.dropbox.com`
`162.125.80.3	client-web.dropbox.com`
`162.125.32.5	d.dropbox.com`
`162.125.32.5	d.v.dropbox.com`
`162.125.2.6	dl.dropbox.com`
`162.125.80.6	dl-doc.dropbox.com`
`162.125.2.6	dl-web.dropbox.com`
`34.197.94.108	dl-debug.dropbox.com`
`52.85.12.7	forums.dropbox.com`
`54.192.136.115	linux.dropbox.com`
`162.125.32.9	m.dropbox.com`
`52.85.12.227	marketing.dropbox.com`
`162.125.17.131	notify.dropbox.com`
`162.125.32.15	photos.dropbox.com`
`162.125.80.5	photos-1.dropbox.com`
`162.125.80.5	photos-2.dropbox.com`
`162.125.80.5	photos-3.dropbox.com`
`162.125.80.5	photos-4.dropbox.com`
`162.125.80.5	photos-5.dropbox.com`
`162.125.80.5	photos-6.dropbox.com`
`162.125.80.5	photos-thumb.dropbox.com`
`162.125.18.129	photos-thumb.x.dropbox.com`
`52.85.12.41	status.dropbox.com`
`52.85.12.72	snapengage.dropbox.com`
`162.125.2.6	dl.dropboxusercontent.com`
`162.125.32.10	www.dropboxstatic.com`
`104.16.100.29	cfl.dropboxstatic.com`
`54.230.125.126	cf.dropboxstatic.com`
`162.125.32.10	dbxlocal.dropboxstatic.com`
`162.125.32.6	log.getdropbox.com`

我不会用 GitHub，请 @lrinQVQ 将上述内容做个 commit 吧。

**Comment by GengTianyu** [comment]
登陆上去了，谢谢大神

在 2017-06-26 18:44:11，"Roy Ray" <notifications@github.com> 写道：


Dropbox 的 hosts 条目提供了 4 个 IP，其中：

指向 Dropbox 首页的 108.160.173.239 返回 403 Forbidden 错误；

反复使用的 108.160.173.193 是个不可用的 IP；

162.125.3.6 可用，但是 162.125.2.6 更快一些；

104.16.100.29 只能对应 cfl.dropboxstatic.com，用在其他域名上将导致证书错误。

我查询了 hosts 中的各个域名所解析出的 IP，选取了其中延迟最低的，结果如下：

162.125.248.1 dropbox.com
162.125.248.1 www.dropbox.com
162.125.32.9 db.tt
162.125.32.14 www.v.dropbox.com
162.125.7.1 www.dropbox-dns.com
162.125.82.7 api.dropbox.com
162.125.32.5 api-d.dropbox.com
162.125.82.7 api.dropboxapi.com
162.125.32.13 api.v.dropbox.com
162.125.32.13 api-notify.dropbox.com
162.125.1.8 api-content.dropbox.com
162.125.2.5 api-content-photos.dropbox.com
52.85.12.34 blogs.dropbox.com
162.125.32.2 block.dropbox.com
162.125.34.133 block.v.dropbox.com
162.125.18.133 bolt.dropbox.com
162.125.2.3 client.dropbox.com
162.125.32.12 client.v.dropbox.com
162.125.80.3 client-lb.dropbox.com
162.125.2.3 client-cf.dropbox.com
162.125.80.3 client-web.dropbox.com
162.125.32.5 d.dropbox.com
162.125.32.5 d.v.dropbox.com
162.125.2.6 dl.dropbox.com
162.125.80.6 dl-doc.dropbox.com
162.125.2.6 dl-web.dropbox.com
34.197.94.108 dl-debug.dropbox.com
52.85.12.7 forums.dropbox.com
54.192.136.115 linux.dropbox.com
162.125.32.9 m.dropbox.com
52.85.12.227 marketing.dropbox.com
162.125.17.131 notify.dropbox.com
162.125.32.15 photos.dropbox.com
162.125.80.5 photos-1.dropbox.com
162.125.80.5 photos-2.dropbox.com
162.125.80.5 photos-3.dropbox.com
162.125.80.5 photos-4.dropbox.com
162.125.80.5 photos-5.dropbox.com
162.125.80.5 photos-6.dropbox.com
162.125.80.5 photos-thumb.dropbox.com
162.125.18.129 photos-thumb.x.dropbox.com
52.85.12.41 status.dropbox.com
52.85.12.72 snapengage.dropbox.com
162.125.2.6 dl.dropboxusercontent.com
162.125.32.10 www.dropboxstatic.com
104.16.100.29 cfl.dropboxstatic.com
54.230.125.126 cf.dropboxstatic.com
162.125.32.10 dbxlocal.dropboxstatic.com
162.125.32.6 log.getdropbox.com

我不会用 GitHub，请 @lrinQVQ 将上述内容做个 commit 吧。

**Comment by Pictor** [comment]
刚才忘记提，www.v.dropbox.com 指向的 162.125.32.14 是无法访问的，不知道还有没有别的 IP 可用。我先前查询过，没明白这个域名有何作用。

**Comment by lrinQVQ** [comment]
感谢啦~www.v.dropbox.com只是作为指向www.dropbox.com的解析用域名2333和www.dropbox.com指向相同即可

**Comment by Pictor** [comment]
dropbox.com 启用了 HSTS，将 www.v.dropbox.com 也指向 162.125.248.1 时会出现错误，因为证书不包含该域名。如果 www.v.dropbox.com 没啥重要作用的话那就忽略好了。

**Comment by lrinQVQ** [comment]
2333我说错了

**Comment by Pictor** [comment]
嗯，就麻烦你看看了。要么删除那一项，要么换个 IP，要么就不作修改。除那一项以外，其余的 IP 是可以访问的。

**Comment by lrinQVQ** [comment]
好的233 感谢啦

**Comment by lrinQVQ** [comment]
解决啦
