### ISSUE TITLE
今天更新完hosts无法访问的解决方法

### ISSUE THREAD

**Issue by percysanchez** [racaljk/hosts#1227]
替换成这个，又快又稳定：
121.59.17.8	twitter.com
121.59.17.8	www.twitter.com
219.76.4.75	t.co
121.59.17.8	api.twitter.com
121.59.17.8	caps.twitter.com
121.59.17.8	mobile.twitter.com
121.59.17.8	support.twitter.com
121.59.17.8	upload.twitter.com
121.59.17.8	tweetdeck.twitter.com
121.59.17.8	syndication.twitter.com
121.59.17.8	platform.twitter.com
121.59.17.8	about.twitter.com
121.59.17.8	blog.twitter.com
121.59.17.8	betastream.twitter.com
121.59.17.8	dev.twitter.com
121.59.17.8	pic.twitter.com
121.59.17.8	search.twitter.com
121.59.17.8	status.twitter.com
121.59.17.8	assets0.twitter.com
121.59.17.8	assets1.twitter.com
121.59.17.8	assets2.twitter.com
121.59.17.8	assets3.twitter.com
121.59.17.8	assets4.twitter.com
121.59.17.8	static.twitter.com
121.59.17.8	help.twitter.com
121.59.17.8	ton.twitter.com
121.59.17.8	s.twitter.com
121.59.17.8	analytics.twitter.com
121.59.17.8	urls-real.api.twitter.com
121.59.17.8	userstream.twitter.com
121.59.17.8	sitestream.twitter.com
121.59.17.8	stream.twitter.com
121.59.17.8	tdweb.twitter.com
121.59.17.8	cdn.syndication.twitter.com
121.59.17.8	apps.twitter.com
121.59.17.8	debates.twitter.com
121.59.17.8   ads.twitter.com
121.59.17.8 *twitter.com
104.244.46.244	twitpic.com
104.244.46.244	m1.twitpic.com
104.244.46.244	web1.twitpic.com
104.244.46.244	web10.twitpic.com
104.244.46.244	web2.twitpic.com
104.244.46.244	web3.twitpic.com
104.244.46.244	web4.twitpic.com
104.244.46.244	web5.twitpic.com
104.244.46.244	web6.twitpic.com
104.244.46.244	web7.twitpic.com
104.244.46.244	web8.twitpic.com
104.244.46.244	web9.twitpic.com
104.244.46.244	*.twitpic.com
104.244.46.71	a0.twimg.com
104.244.46.71	a1.twimg.com
104.244.46.71	a2.twimg.com
104.244.46.71	a3.twimg.com
104.244.46.71	a4.twimg.com
104.244.46.71	a5.twimg.com
104.244.46.71	video.twimg.com
104.244.46.71	abs.twimg.com
104.244.46.71	g.twimg.com
104.244.46.71	hca.twimg.com
104.244.46.71	o.twimg.com
104.244.46.71	p.twimg.com
104.244.46.71	r.twimg.com
104.244.46.71	ma.twimg.com
104.244.46.71	pbs.twimg.com
104.244.46.71	pbs-h2.twimg.com
104.244.46.71	ton.twimg.com
104.244.46.71	syndication.twimg.com
104.244.46.71	syndication-o.twimg.com
104.244.46.71	image-proxy-origin.twimg.com
104.244.46.71	cdn.syndication.twimg.com
104.244.46.71	*.twimg.com
104.244.45.246	tweetdeck.com
104.244.45.246	api.tweetdeck.com
104.244.45.246	web.tweetdeck.com
104.244.45.246	www.tweetdeck.com
104.244.45.246	downloads.tweetdeck.com

**Comment by percysanchez** [comment]
@版主
快更新

**Comment by lychichem** [comment]
本项目原则上不接受sni的

**Comment by percysanchez** [comment]
今天无法更新hosts，显示405 not allowed，点击几十次成功一次

**Comment by percysanchez** [comment]
更新完twitter就炸了

**Comment by lrinQVQ** [comment]
本项目原则上不接受sni+1

**Comment by percysanchez** [comment]
我知道了

**Comment by percysanchez** [comment]
我知道了+1

**Comment by percysanchez** [comment]
客户端怎么无法更新hosts了？

**Comment by Makebignew** [comment]
这个sni 有点不一样 是走的新疆出口CN2 直连哈萨克斯坦

**Comment by lychichem** [comment]
@Makebignew 一说感觉更危险了233有点蜜罐的感觉（幸好我只关注原画师和女优
