### ISSUE TITLE
客户端更新服务又无法使用了😭

### ISSUE THREAD

**Issue by percysanchez** [racaljk/hosts#1228]
但不是405
是request api of this month has reached to limit

**Comment by lychichem** [comment]
API每月请求数有限制吧，最近一个月更新太多次然后就炸了（好在我只手动从github复制粘贴我要用的部分）

**Comment by MSONIT** [comment]
确实挂了

**Comment by percysanchez** [comment]
今天更新哪部分了

**Comment by trendsoa** [comment]
不能用了吧

**Comment by wilon** [comment]
哪个客户端？
`请求api本月已经达到限制`，过几天就下月了，别担心👨‍👨‍👧‍👦

**Comment by MSONIT** [comment]
还不能用！！

**Comment by lychichem** [comment]
估计是托管api的服务器所在国家还没到7月

**Comment by DDoSolitary** [comment]
说到底这到底时什么东西的api啊。。
而且就错误信息来看不是hosts的锅

**Comment by wilon** [comment]
估计是`https://api.github.com/repos/racaljk/hosts/commits`，判断此项目有`commit`就自动更新，这个接口有限制。

**Comment by lychichem** [comment]
想起当年的12306刷票脚本直接把github刷d了233

雷驰 浙江大学化学系

在 2017年7月3日，17:32，Weilong Wang <notifications@github.com<mailto:notifications@github.com>> 写道：


估计是https://api.github.com/repos/racaljk/hosts/commits，判断此项目有commit就自动更新，这个接口有限制。

**Comment by DDoSolitary** [comment]
这样的话是不可抗力啊。。并没有什么办法的。。
