### ISSUE TITLE
请加入Lineage OS

### ISSUE THREAD

**Issue by cyp0633** [racaljk/hosts#1229]
就是个Android的第三方ROM官网 也不知道何时被墙了
我这儿有几个IP
219.76.4.11 lineageos.org
219.76.4.11 www.lineageos.org
219.76.4.11 download.lineageos.org

**Comment by lrinQVQ** [comment]
xd 不接受SNI哦 没办法

**Comment by daoxunchen** [comment]
不知道发这儿合适不合适
不接受sni这句话是什么意思？
只在这里看到了sni的相关资料[为什么不推荐在移动设备上使用 hosts？](https://github.com/racaljk/hosts/wiki/%E4%B8%BA%E4%BB%80%E4%B9%88%E4%B8%8D%E6%8E%A8%E8%8D%90%E5%9C%A8%E7%A7%BB%E5%8A%A8%E8%AE%BE%E5%A4%87%E4%B8%8A%E4%BD%BF%E7%94%A8hosts%EF%BC%9F)
hosts里那一堆同样ip的google域名不算SNI么

**Comment by lrinQVQ** [comment]
咩那是谷歌的官方IP哦 SNI指的是非官方(第三方)配置的反向代理服务器

**Comment by daoxunchen** [comment]
@lrinQVQ   哦哦哦明白了  刚查了下1楼那个ip确实不是官方的 是个电信公司的   
谢谢大佬解惑
