### ISSUE TITLE
google-drive

### ISSUE THREAD

**Issue by GengTianyu** [racaljk/hosts#1230]
请问为什么google drive mac的桌面安装程序下载不下来啊https://tools.google.com/dlpage/drive/thankyou.html?hl=zh-CN，而用网页的drive能打开。

**Comment by GengTianyu** [comment]
补充一下：dl.google.com/drive/installgoogledrive.dmg 。是这个一直无法下载

**Comment by imknown** [comment]
二楼地址可以下. 我是联通.

**Comment by wangchunming** [comment]
把这个指向203.208.41.33 就行。

**Comment by DDoSolitary** [comment]
`dl.google.com`目前没有被墙，如果实在无法访问的话用@wangchunming的方法吧
