### ISSUE TITLE
求添加新的域名services.googleapis.cn

### ISSUE THREAD

**Issue by haygcao** [racaljk/hosts#1231]
本来非国行的手机改了hosts就可以使用Google play了 现在换了国行就不行了 求添加域名 services.googleapis.cn 到Google IP 这样就可以正常访问了

**Comment by wangchunming** [comment]
这个域名可以被正常dns解析的，应该不用添加。

**Comment by wpp214** [comment]
我之前遇到了和你一样的情况，https://aenes.com/post/794.html按照这个解决了，但是ip很快就被封掉了。。。。

**Comment by DDoSolitary** [comment]
此域名并没有被墙
