### ISSUE TITLE
Yahoo 的 hosts 更新

### ISSUE THREAD

**Issue by peridot** [racaljk/hosts#1232]
原 hosts 文件中 Yahoo 的条目有部分 IP 目前访问速度不理想，还包含一些没必要添加的域名，因此我做了一个更新。

除了 flickr.com 及其子域名以外，Yahoo 的大多数域名都能够正常访问。不过其中许多域名在国内会被解析到美国或者英国的 IP 地址，而不是速度较快的香港、台湾、新加坡的 IP，因此有时会导致部分网页打开缓慢甚至连接超时。于是相关 hosts 条目还是有存在的必要。

删除部分解析完全正常的条目：
`c.staticflickr.com ~ c8.staticflickr.com`
`c9.staticflickr.com` （不存在）
`*.farm*.staticflickr.com`
`www.yahoo.com`
`sp.analytics.yahoo.com`
`de.yahoo.com`
`hsrd.yahoo.com`
`mg.mail.yahoo.com`
`hk-mg61.mail.yahoo.com`
`overview.mail.yahoo.com`
`geo.query.yahoo.com`
`lh.secure.yahoo.com`
`us.yahoo.com`
`yimg.com` （原文件中被写成了 ying.com）
`*.yimg.com`

增添缺失的条目，有些是被关照了，有些是解析不理想：
`code.flickr.net`
`answers.yahoo.com`
`hk.answers.yahoo.com`
`tw.answers.yahoo.com`
`tw.bid.yahoo.com`
`tw.mall.yahoo.com` （不是 mail 是 mall）
`hk.mobi.yahoo.com`
`news.yahoo.com`
`search.yahoo.com`
`hk.search.yahoo.com`
`tw.search.yahoo.com`

修改后的 hosts 内容如下：
`119.161.14.17	flickr.com`
`119.161.14.17	www.flickr.com`
`119.161.14.17	api.flickr.com`
`192.0.79.32	code.flickr.com`
`192.0.79.32	code.flickr.net`
`76.13.28.196	downloadr.flickr.com`
`119.161.14.17	heartbeat.flickr.com`
`119.161.14.17	m.flickr.com`
`119.161.14.17	secure.flickr.com`
`106.10.231.23	static.flickr.com`
`119.161.14.17	up.flickr.com`
`106.10.231.23	farm1.staticflickr.com`
`106.10.231.23	farm2.staticflickr.com`
`106.10.231.23	farm3.staticflickr.com`
`106.10.231.23	farm4.staticflickr.com`
`106.10.231.23	farm5.staticflickr.com`
`106.10.231.23	farm6.staticflickr.com`
`106.10.231.23	farm7.staticflickr.com`
`106.10.231.23	farm8.staticflickr.com`
`106.10.231.23	farm9.staticflickr.com`
`106.10.178.36	yahoo.com`
`202.43.194.205	c5.ah.yahoo.com`
`202.43.194.205	edit.yahoo.com`
`202.43.194.205	na.edit.yahoo.com`
`202.43.194.205	sa.edit.yahoo.com`
`203.84.197.27	geo.yahoo.com`
`202.43.194.205	login.yahoo.com`
`202.43.194.205	open.login.yahoo.com`
`202.43.194.205	mail.yahoo.com`
`203.188.200.67	hk.yahoo.com`
`203.188.200.67	tw.yahoo.com`
`203.84.197.27	answers.yahoo.com`
`203.84.197.27	hk.answers.yahoo.com`
`203.84.197.27	tw.answers.yahoo.com`
`116.214.10.132	tw.bid.yahoo.com`
`203.84.197.27	finance.yahoo.com`
`203.84.197.27	hk.finance.yahoo.com`
`124.108.112.57	tw.finance.yahoo.com`
`119.160.242.137	tw.mall.yahoo.com`
`116.214.11.98	hk.mobi.yahoo.com`
`116.214.11.98	tw.mobi.yahoo.com`
`106.10.160.45	news.yahoo.com`
`180.222.100.23	hk.news.yahoo.com`
`180.222.100.23	tw.news.yahoo.com`
`27.123.200.67	search.yahoo.com`
`27.123.200.67	hk.search.yahoo.com`
`27.123.200.67	tw.search.yahoo.com`
`50.18.192.250	duckduckgo-owned-server.yahoo.net`

此外，昨天 @lrinQVQ 你改动的 Dropbox 条目将最后一行的 162.125.32.6 误写成了 162.25.32.6，难道是在手动输入 IP？

**Comment by lrinQVQ** [comment]
是啊手打的xd

**Comment by Pictor** [comment]
……无法理解。为什么要手动输入而不是复制粘贴呢？

**Comment by lrinQVQ** [comment]
//2333格式要重新编排啊

**Comment by lrinQVQ** [comment]
有些IP适用于多域名2333 有些适用于单域名都需要重新改的

**Comment by Pictor** [comment]
@lrinQVQ 你逗我。格式编排也是复制粘贴，以及插入、删除、换行，没了。我很怀疑 ying.com 的 typo 是不是也是你的杰作？因为是手打的所以 m 就变成了 n？我看到最近编辑历史里面有你 fix typo 的一条记录，不过你那 typo 可一点都不小。所以你应该改个名叫 TypoQVQ

**Comment by lrinQVQ** [comment]
@Pictor xd 推荐你试试手动编辑整个文件 你就知道了

**Comment by lrinQVQ** [comment]
还有就是我没有维护过Yahoo相关的域名请不要诽谤 如果你觉得我容易打错233请自己动手丰衣足食

**Comment by Pictor** [comment]
@lrinQVQ 我倒是知道这项目好像要求改 .yaml 文件，不过这个主要也就是换个排版。我自己编辑 hosts 文件的。之前 Dropbox 和 Yahoo 的 hosts 条目也是我在你们给出的内容寄出上修改的。

**Comment by Pictor** [comment]
@lrinQVQ Yahoo 那个 typo 我是开个玩笑。抱歉让你觉得冒犯。

**Comment by lrinQVQ** [comment]
2333你可以试试改.yml文件 我等你开PR

**Comment by lrinQVQ** [comment]
没事啦233

**Comment by lrinQVQ** [comment]
昂要我先修改嘛2333 一会你在看看有没有出错

**Comment by Pictor** [comment]
我查了一下，你是指 pull request？GitHub 我搞不明白，我无权修改，倒是我可以 fork 一下自己改了自己用，不过这样一来我就不如本机上弄了。我不是程序员，GitHub 的最大特色在我看来好像就是版本控制？这对我没有吸引力。

**Comment by lrinQVQ** [comment]
你可以fork这个项目然后切换到hosts-source分支 在网页上打开hosts.yml接着在网页上进行编辑233 编辑完成之后编辑commit信息然后点击New pull request发起PR就好了 @Pictor

**Comment by lrinQVQ** [comment]
好的咩233小意思啦 对了昂

**Comment by lrinQVQ** [comment]
我写下修改流程吧xd

**Comment by Pictor** [comment]
如果他人也有需要的话可以麻烦你写一个。如果只是为了我的话倒是不用，我虽然几乎不会写代码，学学使用 GitHub 倒不是问题。只是因为我日常用不到 GitHub，单单为了一个 hosts 项目而学习感觉不值。不过我刚才看了一下，不难，我下次就自己动手吧。有无法解决的问题再请教你。

**Comment by lrinQVQ** [comment]
好的2333 挺多人不会用的我写下吧

**Comment by laodcn** [comment]
额 好久没来了，刚想更新flickr图片域名 farm*.staticflickr.com

**Comment by peridot** [comment]
@laodcn 就麻烦你更新一下吧，顺便把以下三项也加入。谢谢。

`119.161.14.17	csp.flickr.com`
`202.43.194.205	api.login.yahoo.com`
`106.10.137.175	geo.query.yahoo.com`

**Comment by laodcn** [comment]
@lrinQVQ 帮忙弄下，顺便问下，有联系方式么？

**Comment by lrinQVQ** [comment]
@laodcn 2333你要什么联系方式 我明天回家弄

**Comment by DDoSolitary** [comment]
@laodcn #900 😆

**Comment by DDoSolitary** [comment]
@lrinQVQ https://github.com/racaljk/hosts/issues/1232#issuecomment-311372861 pictor躺枪 😄 
帮你改了

**Comment by DDoSolitary** [comment]
在时隔一个月后，家里终于又有网了，于是一激动就处理了好多issue，现在感觉身体被掏空。。
这个issue交给你们了 @lrinQVQ @laodcn

**Comment by wolfan** [comment]
Yahoo什么时候也上墙了？

**Comment by lrinQVQ** [comment]
啊 xd 有网了我来吧
