### ISSUE TITLE
twitter  ip  (104.244.42.131) 无法访问

### ISSUE THREAD

**Issue by lwjRes** [racaljk/hosts#1236]
希望更新下此IP. 谢谢

**Comment by lrinQVQ** [comment]
get 明天来弄

**Comment by EricQLi** [comment]
+1

**Comment by wangchunming** [comment]
大哥，twitter因为某人的原因，早就在国内被https连接重置了好不好？无论任何国外ip，只要携带twitter的域名，都会被链接重置。

**Comment by lychichem** [comment]
甚至sni也最多只能撑半周，前两天有人发哈萨克的sni我用了不过4天就不行了

**Comment by dawangjiaowolaifatie** [comment]
真是相顾无言，惟有泪千行。

**Comment by lrinQVQ** [comment]
有不返回twitter.com证书的可用IP,类似于谷歌的233

**Comment by laodcn** [comment]
@lrinQVQ 过一两周再使出吧..233  最近太和谐

**Comment by lrinQVQ** [comment]
@laodcn +1 23333

**Comment by lrinQVQ** [comment]
@laodcn 教程我马上发给你2333

**Comment by ldm2060** [comment]
@lrinQVQ 能不能给萌新发一份教程....😭

**Comment by lrinQVQ** [comment]
https://github.com/racaljk/hosts/issues/1349
