### ISSUE TITLE
twitter又挂了

### ISSUE THREAD

**Issue by percysanchez** [racaljk/hosts#1239]
dalao怎么抓的hosts啊，教教我呗

**Comment by 10069** [comment]
http://www.williamlong.info/archives/3878.html

http://www.williamlong.info/archives/3891.html

现在除了 Facebook、Twitter、Google、Dropbox 等需要找IP‚ 其他网站解决DNS污染就Ok

**Comment by wangchunming** [comment]
tumblr也是被墙ip的。。。。。

**Comment by kobeking** [comment]
一个郭文贵把共党弄得人心惶惶

_使用 [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github) 从我的 OnePlus ONEPLUS A3000 发送_

**Comment by liguge** [comment]
我现在也是不能登录推特了~

**Comment by sky8964** [comment]
# 无需翻墙可以直接播放郭文贵视频音频
【追求民主宪政】
https://github.com/sky8964/home/wiki

在右边导航的“郭文贵视频与音频” 栏目 进入
郭文贵视频、音频、文字版

请推广此网站，传播文贵视频、音频，谢谢。
