### ISSUE TITLE
报告Facebook失效

### ISSUE THREAD

**Issue by wolfan** [racaljk/hosts#124]

**Comment by BROBIRD** [comment]
twitter也是一样 连接被重置

**Comment by cdroad** [comment]
一切正常，除了Facebook。

**Comment by wsdjeg** [comment]
facebook twitter 连接重置

**Comment by exia336** [comment]
12.9还是上不了。

**Comment by stanzhou** [comment]
还有youtube

**Comment by Roller44** [comment]
YouTube 通过修改 hosts 文件也是不能看的，还得挂 VPN 。


 

-------- 原始邮件 --------
发件人：stanzhou <notifications@github.com>
时间：周三 12月9日 22:30
收件人：racaljk/hosts <hosts@noreply.github.com>
主题：Re: [hosts] 报告Facebook失效 (#124)
