### ISSUE TITLE
可否加入 cdn.rawgit.com

### ISSUE THREAD

**Issue by chutsetien** [racaljk/hosts#1240]
7 月 3 日晨 9 时测得在新疆、四川、云南、贵州、湖南、广西、江西、山西、河南、河北、北京、天津、山东、辽宁几乎不可访问。此情况已多日。
似乎寻得一可用 IP 为 198.232.125.81, 只是不知道是否该网站有更多其它地址（且指向不同 IP）？

**Comment by DDoSolitary** [comment]
确实被墙了

**Comment by DDoSolitary** [comment]
Fixed 4110a2b234399897282b942bf0bf8abf1b7c83e6
