### ISSUE TITLE
这个是用来干什么的？免费翻墙么？修改了hosts就不用vpn吗？

### ISSUE THREAD

**Issue by zouhuigang** [racaljk/hosts#1243]

**Comment by DDoSolitary** [comment]
翻墙用的，但并不能支持所有网站，如果你要用的网站没有在这里被支持的话还是得用VPN这类的方案

**Comment by wangchunming** [comment]
咳。
如果是单纯用来翻墙的话，欢迎你点我头像去用我那边的hosts，那边的hosts网址更全，支持的网站也更多，但是无法在手机上完美使用。

**Comment by lrinQVQ** [comment]
xd 有人来把楼上屏蔽下嘛

**Comment by lrinQVQ** [comment]
@racaljk 能不能帮忙屏蔽下xd 警告过了xd 过分了@wangchunming

**Comment by racaljk** [comment]
@lrinQVQ github没有屏蔽功能把，如果是做推广你是collaborator应该可以直接删comment

**Comment by hhhaiai** [comment]
鄙视广告的

**Comment by Too-Naive** [comment]
@racaljk 直接block
![](https://user-images.githubusercontent.com/16496671/27813755-9cd3a064-60aa-11e7-8054-ddbada878d08.png)

**Comment by racaljk** [comment]
Blocked

**Comment by dawangjiaowolaifatie** [comment]
这是一种高科技秘密武器，学名“候斯特通道”，它比VPN强大一万倍。如果说VPN是秘密地下道的话，那么候斯特通道就是建立空中通讯管道。有了候斯特通道，你就可以通过卫星通讯，接收来自地球任何一个地方的数据。候斯特通道最早是在二战期间由英国科学家候斯特发明而得名，那时采用的还是原始的热气球形式，不过它在盟军的胜利过程中发挥了巨大作用。冷战期间，美苏不断更新候斯特通道技术，让人造卫星成为它的坚固载体，并应用在间谍战中。进入21世纪，候斯特通道技术已经全面成熟，并推广到民用，进入了千家万户。

**Comment by wolfan** [comment]
😂瞬间变知乎

**Comment by lrinQVQ** [comment]
@dawangjiaowolaifatie 我可以把它加到wiki里面吗2333

**Comment by dawangjiaowolaifatie** [comment]
@lrinQVQ 可以可以，不胜荣幸！

**Comment by tikdik** [comment]
@dawangjiaowolaifatie 没见过扯犊子这么一脸诚意的，我竟然相信了:joy:

**Comment by DDoSolitary** [comment]
这个close了吧。。

**Comment by zouhuigang** [comment]
哈哈 ，关闭了干嘛，主要用来当科普啊~~

**Comment by DDoSolitary** [comment]
科普扔wiki啊

**Comment by Too-Naive** [comment]
![](https://cloud.githubusercontent.com/assets/16496671/20557321/f47b3c50-b1a5-11e6-8810-8edc50a65778.png)
