### ISSUE TITLE
Google Play Music 烂了

### ISSUE THREAD

**Issue by percysanchez** [racaljk/hosts#1245]
如题

**Comment by DDoSolitary** [comment]
具体点啊。。我这里正常

**Comment by percysanchez** [comment]
黑龙江这边不管什么运营商，都上不了

**Comment by DDoSolitary** [comment]
是网页根本打不开还是有错误？谷歌其他服务能上吗？

**Comment by percysanchez** [comment]
就音乐网页和软件全烂了，其他正常

**Comment by DDoSolitary** [comment]
所以怎么样叫做“烂了” 😫

**Comment by xinyushijian** [comment]
就是登录不了的意思呗。。。哈哈哈

**Comment by DDoSolitary** [comment]
我忽然对我的交流能力失去了信心。。

**Comment by lrinQVQ** [comment]
23333333

**Comment by xinyushijian** [comment]
哈哈哈哈，我竟然以为是我自己说的，讲真前两天我是和你说过一样的话的




Outlook for Android







On Fri, Jul 7, 2017 at 12:47 PM +0800, "DDoSolitary" <notifications@github.com> wrote:












我忽然对我的交流能力失去了信心。。

**Comment by xinyushijian** [comment]
没毛病的老铁，我前两天在图书馆要的一姑娘的联系方式。。。加了好友却不知道叫什么23333333




Outlook for Android







On Fri, Jul 7, 2017 at 12:47 PM +0800, "DDoSolitary" <notifications@github.com> wrote:












我忽然对我的交流能力失去了信心。。

**Comment by lrinQVQ** [comment]
233333心疼你们两个

**Comment by Too-Naive** [comment]
![](https://cloud.githubusercontent.com/assets/16496671/20557321/f47b3c50-b1a5-11e6-8810-8edc50a65778.png) Hi 美女

**Comment by lrinQVQ** [comment]
口意2333

**Comment by xinyushijian** [comment]
🌝🌝🌝毕竟英语口语过了好几级的人


发自我的 iPad

**Comment by xinyushijian** [comment]
Hi girl 能不能留个联系方式让我聊一聊。。。我他吗。。。gouhub上怎么会有妹纸。。。2333:

发自我的 iPad

**Comment by Too-Naive** [comment]
![](https://cloud.githubusercontent.com/assets/16496671/20557321/f47b3c50-b1a5-11e6-8810-8edc50a65778.png)

**Comment by xinyushijian** [comment]
哎嘿😜




Outlook for Android

**Comment by yangmengli** [comment]
github最大的屌丝聚集地,怎么会有妹子哈哈哈
