### ISSUE TITLE
Mozilla那一段导致AMO上不去

### ISSUE THREAD

**Issue by 4679** [racaljk/hosts#125]
去掉就能上了

**Comment by K-Guan** [comment]
就是从[2177](https://github.com/racaljk/hosts/blob/master/hosts#L2117)行开始，到[2138](https://github.com/racaljk/hosts/blob/master/hosts#L2138)行结束的那部分？AMO是哪个网站？

**Comment by 4679** [comment]
addons.mozilla.org
#Mozilla 那一段

**Comment by K-Guan** [comment]
按理说……Mozilla没被墙吧？应该可以直接删掉的。

**Comment by 4679** [comment]
我我是这样认为的

**Comment by K-Guan** [comment]
我完成了，现在的情况？

**Comment by 4679** [comment]
没问题了

**Comment by makunhappy** [comment]
http://mozilla.com.cn/forum.php?mod=viewthread&tid=320536&extra=page%3D2%26filter%3Dtypeid%26typeid%3D8
这里边的hosts可以用
