### ISSUE TITLE
关于FB的一些页面，不知道可不可以提？要是不合适就关了吧。

### ISSUE THREAD

**Issue by 123ysys** [racaljk/hosts#1250]
![img_20170706_190506](https://user-images.githubusercontent.com/27964272/27908859-71bc1924-6280-11e7-8239-f3fb80546c56.jpg)
如图，前面的身份验证都可以，但这里点了“确定”后死死没有反应。
不知道是我网速的问题还是FB的bug，如果有谁可以解决的话请告诉一声。如果不合适这种提问的话……close吧。

**Comment by DDoSolitary** [comment]
我看看是不是hosts的问题

**Comment by 123ysys** [comment]
谢了。@DDoSolitary

**Comment by DDoSolitary** [comment]
我开了个小号试了一下好像没问题欸。。
要不你验证的时候开F12看看

**Comment by DDoSolitary** [comment]
话说Facebook好像如果输入的人名和已有账号重复的话会要求上传照片欸。。之前搞了半天一直被要求上传照片。。

**Comment by 123ysys** [comment]
以前有过上传证件的经历，虽然烦但还提交得了。这次密码输错太多了，它让我输入一串发到手机上的六位数验证码，可是根本就提交不了，真是奇怪。
感觉是网络的问题，外国的网站这里很多上不去。
心累。/(ㄒoㄒ)/~~

**Comment by lrinQVQ** [comment]
23333心疼
