### ISSUE TITLE
今天gohosts客户端更新hosts后黑龙江twitter不可用

### ISSUE THREAD

**Issue by percysanchez** [racaljk/hosts#1251]
如题

**Comment by DDoSolitary** [comment]
目前Twitter确实是挂了的，你没看见有好多关于Twitter的issue吗。。

**Comment by kobeking** [comment]
现在hosts能上Twitter的只有gohosts了吧

_使用 [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github) 从我的 OnePlus ONEPLUS A3000 发送_

**Comment by lrinQVQ** [comment]
Twitter我估计下周给出你们IP 因为某些原因
