### ISSUE TITLE
Google Video 讨论issues

### ISSUE THREAD

**Issue by lrinQVQ** [racaljk/hosts#1255]
如果发现有失效的域名
请F12 - Network - F5
将失效的域名粘贴回复一下
*---sn-i3j5cax-i3bs.googlevideo.com
*---sn-juh-h4hs.googlevideo.com
*---sn-juh-h4hz.googlevideo.com
*---sn-npoeen7r.googlevideo.com
待处理ing 233

**Comment by sy618** [comment]
目测你会被累死～

**Comment by lrinQVQ** [comment]
23333不怕 写了脚本

**Comment by sy618** [comment]
既然你不怕累，那么可以参考https://raw.githubusercontent.com/sy618/hosts/master/y
这个列表里的域名，用脚本去生成一个。
另外建议YouTube 的数据单独存放，别合并到主数据里。
有需求的人再订阅一个就行了。

**Comment by lrinQVQ** [comment]
不不不他的域名不对xd

**Comment by lrinQVQ** [comment]
这段IP已经存活了快一年了 稳定性无压力的2333

**Comment by sy618** [comment]
我曾经试过找可ping通的官方IP来实现YouTube播放。
虽然IP没被封，但并不一定就能正常播放。

我随便测试了一个，
74.125.102.124	r6---sn-i3b7kn7d.googlevideo.com
虽然能ping通，但你可能没测试Ping 443端口，结果是无法ping通。so ...

**Comment by lrinQVQ** [comment]
不不不

**Comment by lrinQVQ** [comment]
只是会丢包而已233

**Comment by lrinQVQ** [comment]
HPING 74.125.102.124 (enp0s31f6 74.125.102.124): S set, 40 headers + 0 data bytes
len=46 ip=74.125.102.124 ttl=54 id=2719 sport=443 flags=SA seq=2 win=28640 rtt=99.7 ms

**Comment by lrinQVQ** [comment]
Youtube会不断重试连接至服务器
HPING 74.125.102.124 (enp0s31f6 74.125.102.124): S set, 40 headers + 0 data bytes
len=46 ip=74.125.102.124 ttl=55 id=11598 sport=443 flags=SA seq=0 win=28640 rtt=99.8 ms
len=46 ip=74.125.102.124 ttl=54 id=12463 sport=443 flags=SA seq=1 win=28640 rtt=99.7 ms
len=46 ip=74.125.102.124 ttl=54 id=17885 sport=443 flags=SA seq=10 win=28640 rtt=102.7 ms

**Comment by lrinQVQ** [comment]
所以哪怕有丢包也是无所谓的

**Comment by lrinQVQ** [comment]
对了基于这个东西我还要把谷歌的1e100域名补全,这样子就能比较完美的解析了2333

**Comment by lrinQVQ** [comment]
https://www.17ce.com/ 你可以ping 74.125.102.124:443
全国不错啊2333

**Comment by DDoSolitary** [comment]
然而并无办法测试，因为YouTube主页都上不去。。

**Comment by lrinQVQ** [comment]
咦我这ok的啊

**Comment by lrinQVQ** [comment]
你们用不了嘛欸！！！我换个IP

**Comment by lrinQVQ** [comment]
我解释一下我为什么要添加Google Video相关域名,首先Youtube的视频是从多个源地址获取的.
而且Youtube是视频的加载中会不断的重试,所以即使ip存在丢包的问题也是可以加载出来的

**Comment by lrinQVQ** [comment]
@DDoSolitary 解决首页了

**Comment by lrinQVQ** [comment]
你们可以测试下https://www.youtube.com/watch?v=TIrxyVt4jvQ

**Comment by lrinQVQ** [comment]
大概等了10秒 你们可以开F12看下 如果无法连接上 Youtube会无限的重试
![2017-07-09 15-20-29](https://user-images.githubusercontent.com/12861134/27991985-25dfaf1a-64bb-11e7-94fd-e0b7314fa4f9.png)

**Comment by lrinQVQ** [comment]
对了!!redirector.googlevideo.com我没有更新

**Comment by lrinQVQ** [comment]
![screenshot_20170709-153437](https://user-images.githubusercontent.com/12861134/27992039-97efdab6-64bc-11e7-980b-82b5c5676a50.png)
手机流量无任何代理 无任何解决DNS污染 直接播放

**Comment by lrinQVQ** [comment]
只要redirector.googlevideo.com存活 那么此方案就是可用状态

**Comment by lrinQVQ** [comment]
@DDoSolitary https://gitter.im/racaljk/hosts?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge已经有人可用了233

**Comment by lrinQVQ** [comment]
没什么疑问我就关掉了啊xd

**Comment by DDoSolitary** [comment]
@lrinQVQ 不好意思，刚刚补课去了。。
还是不行欸。。
208.117.229.244能ping通，但tcping 80、443端口都不通。。

**Comment by lrinQVQ** [comment]
不不不 不能ping

**Comment by lrinQVQ** [comment]
你可以试试sudo apt install hping3
sudo hping3 -S -p 443 208.117.229.244
丢包巨大但是Youtube在加载Video的时候会不断的从服务器获取数据,只要连上一次即可稳定通讯

**Comment by lrinQVQ** [comment]
sudo hping3 -S -p 443 208.117.229.244
HPING 208.117.229.244 (enp0s31f6 208.117.229.244): S set, 40 headers + 0 data bytes
len=46 ip=208.117.229.244 ttl=50 id=53801 sport=443 flags=SA seq=1 win=29200 rtt=419.7 ms
DUP! len=46 ip=208.117.229.244 ttl=50 id=54054 sport=443 flags=SA seq=1 win=29200 rtt=711.7 ms
len=46 ip=208.117.229.244 ttl=51 id=55812 sport=443 flags=SA seq=4 win=29200 rtt=427.6 ms
DUP! len=46 ip=208.117.229.244 ttl=51 id=55882 sport=443 flags=SA seq=4 win=29200 rtt=719.5 ms
len=46 ip=208.117.229.244 ttl=51 id=56379 sport=443 flags=SA seq=5 win=29200 rtt=427.4 ms
DUP! len=46 ip=208.117.229.244 ttl=51 id=56438 sport=443 flags=SA seq=5 win=29200 rtt=735.5 ms

**Comment by DDoSolitary** [comment]
然而我youtube首页打不开啊 😭

**Comment by lrinQVQ** [comment]
我更新了啊欸！！！

**Comment by lrinQVQ** [comment]
还是不行嘛0.0

**Comment by DDoSolitary** [comment]
就是用你更新的那个啊。。
> 208.117.229.244能ping通，但tcping 80、443端口都不通。。

**Comment by lrinQVQ** [comment]
啧

**Comment by lrinQVQ** [comment]
等待10-30秒啦233

**Comment by lrinQVQ** [comment]
因为计划用谷歌的新策略IP,所以貌似对某些网络不太友好xd

**Comment by DDoSolitary** [comment]
然而网页打不开啊。。
![youtube-failed](https://user-images.githubusercontent.com/25856103/27992934-06e0a5bc-64d2-11e7-8bd7-6a592b004d24.png)

**Comment by DDoSolitary** [comment]
不知所措。。

**Comment by lrinQVQ** [comment]
啧 心疼你 那等我下233 我换一个全国情况好一些的

**Comment by lrinQVQ** [comment]
不要怕233 我来处理下

**Comment by helfee** [comment]
最近几天单位铁通网打不开谷歌了,ping不通host的ip  :(

**Comment by lrinQVQ** [comment]
咦铁通嘛

**Comment by lrinQVQ** [comment]
有用https://www.google.com/ncr嘛

**Comment by lautis0503** [comment]
啊，添加googlevideo了啊。
然而youtube打不开……

**Comment by lautis0503** [comment]
这些ip都是几十次中有一次通的样子，等待好久以后确实可以播放。
嗯…原来这些ip没有完全封啊。

**Comment by lautis0503** [comment]
随手丢一个
*---sn-a8au-a5me.googlevideo.com

**Comment by lrinQVQ** [comment]
@lautis0503 忘了说233解决啦

**Comment by SerCom-KC** [comment]
要不要考虑一下把 Google Drive 的在线播放也弄上去
我记得是 *.c.drive.google.com

**Comment by lrinQVQ** [comment]
这个可用IP好像挺多的欸

**Comment by SerCom-KC** [comment]
那就很爽了……
对了问个问题，如果是直播的话，为了不卡顿是不是redirector最好不要丢包？

**Comment by lrinQVQ** [comment]
是的233

**Comment by SerCom-KC** [comment]
捣鼓了一阵，大致搞明白了
只要redirector能在缓冲吃完之前吐出一个新地址，怎么丢包都好
但如果新地址IP不可用就会GG一段时间了w
（我开了DNS防污染，结果不在hosts里的IP大多都是封死的233

**Comment by lrinQVQ** [comment]
@SerCom-KC 真聪明咩2333 给你一个大红花

**Comment by lrinQVQ** [comment]
https://github.com/racaljk/hosts/issues/1349
