### ISSUE TITLE
Google Video 域名失效报告issues

### ISSUE THREAD

**Issue by lrinQVQ** [racaljk/hosts#1256]
如果发现有失效的域名
请F12 - Network - F5
将失效的域名粘贴回复一下
还有部分域名没有添加完毕

**Comment by derekwei** [comment]
r*---sn-4g57knz7.googlevideo.com
是这种格式？

**Comment by lrinQVQ** [comment]
是的咩233

**Comment by SerCom-KC** [comment]
r*---sn-qxo7sn7e.googlevideo.com
r*---sn-nja7sn7l.googlevideo.com
r*---sn-vgqseney.googlevideo.com
r*---sn-qxo7sn7z.googlevideo.com
r*---sn-axq7sn7l.googlevideo.com
r*---sn-qxo7sn7l.googlevideo.com
r*---sn-vgqsenls.googlevideo.com
r*---sn-qxo7snel.googlevideo.com
听说你缺域名？![#(滑稽)](https://cloud.githubusercontent.com/assets/16496671/20557321/f47b3c50-b1a5-11e6-8810-8edc50a65778.png)

**Comment by lrinQVQ** [comment]
lai lai lai 2333

**Comment by Too-Naive** [comment]
![](https://cloud.githubusercontent.com/assets/16496671/20557321/f47b3c50-b1a5-11e6-8810-8edc50a65778.png)

**Comment by ldm2060** [comment]
r*---sn-npoeen7r.googlevideo.com

**Comment by SerCom-KC** [comment]
继续![#(滑稽)](https://cloud.githubusercontent.com/assets/16496671/20557321/f47b3c50-b1a5-11e6-8810-8edc50a65778.png)
r*---sn-a5mlrn76.googlevideo.com

**Comment by lrinQVQ** [comment]
23333可以

**Comment by SerCom-KC** [comment]
r*---sn-30a7yn7d.googlevideo.com
（反正是谷翔吐出来的）

**Comment by SerCom-KC** [comment]
r*---sn-30a7yne7.googlevideo.com

**Comment by lrinQVQ** [comment]
https://github.com/racaljk/hosts/issues/1349
