### ISSUE TITLE
一些计划

### ISSUE THREAD

**Issue by lrinQVQ** [racaljk/hosts#1257]
- [ ] Google 1e100(以防万一) 域名
- [ ] Google Video全部支持
- [ ] Google Play
- [ ] Twitter
- [ ] 更换hosts里的域名为不返回证书的IP (稍后详细解释)
- [ ] 替换丢包严重的IP

**Comment by hhhaiai** [comment]
是工具获取？还是其他方法获取？

**Comment by lrinQVQ** [comment]
手动2333

**Comment by hhhaiai** [comment]
有群吗？  申请加入。一期鼓捣

**Comment by hhhaiai** [comment]
一起造起来~

**Comment by dawangjiaowolaifatie** [comment]
大王英明！
候斯特大法就是好！就是好来就是好！

**Comment by lrinQVQ** [comment]
欸群 没有欸

**Comment by Ir1d** [comment]
要不使用trello？

**Comment by Too-Naive** [comment]
trello 太慢了

**Comment by lrinQVQ** [comment]
看你们233

**Comment by lychichem** [comment]
v6看管表示十分安逸，等你上手搞推（毕竟辣鸡推只有v4）

**Comment by lrinQVQ** [comment]
推特已经有啦但是不敢公开暂时

**Comment by jerossh** [comment]
谷歌最近被干了，好难受。

**Comment by lrinQVQ** [comment]
谷歌没事啊欸

**Comment by hhhaiai** [comment]
哈哈

**Comment by DaleXiao** [comment]
表示愿意加群一起捣鼓，另外能Twitter能列入计划不？大神们

**Comment by lrinQVQ** [comment]
推特已经有IP 2333但是不敢放

**Comment by DaleXiao** [comment]
求私信分享dale.rangers@gmail.com

**Comment by spyhole** [comment]
建议建立 slack 或者 QQ 群。

**Comment by lychichem** [comment]
qq群的你是搞笑吗，腾讯又不瞎…

**Comment by dawangjiaowolaifatie** [comment]
telegram群可以考虑

**Comment by lrinQVQ** [comment]
Twitter 不返回正常证书的可用IP就一个 还是想先测试一下是不是真的根据证书进行封锁xd

**Comment by spyhole** [comment]
用 trello 也是一个相当不错的选择

**Comment by mewsf** [comment]
1e100和gvs的编码可以参考这个repo：[https://github.com/lennylxx/ipv6-hosts](url)

另外楼上说hosts好的吃我dnsmasq和bind9

**Comment by lrinQVQ** [comment]
IPv6的无法用在4上 而且太不全面了2333 bind9如果要公开给别人用始终会被DNS污染影响 dnsmasp 也是需要有基础的2333

**Comment by dawangjiaowolaifatie** [comment]
@mewsf 这位道友你让我吃你dnsmasq和bind9，我一脸懵B呀。你先告诉我这俩是什么玩意好不好

**Comment by spyhole** [comment]
用 trello 也是一个相当不错的选择

**Comment by Too-Naive** [comment]
要不 telegram 群吧

**Comment by Too-Naive** [comment]
没什么问题的话 我已经创好了( https://t.me/joinchat/DsyANURF7FK5TFpRvJcSVA

**Comment by lrinQVQ** [comment]
神速2333 一会加

**Comment by sy618** [comment]
确实需要一个组织。

**Comment by lrinQVQ** [comment]
@sy618 对了咩0.0 你的Youtube hosts里面有缺少的哦
https://github.com/racaljk/hosts/commit/25e9ec7774d28686147f0d0ca78cac80a2cc664e
https://github.com/racaljk/hosts/commit/006479fffa332371c69b2776818e886e888f99d0

**Comment by sy618** [comment]
如果要收集全YouTube，那么至少有几万条。没什么必要添加那么多。

我刚用无污染DNS来解析YouTube视频，虽然IP正确但是10个视频有8个打不开，干扰严重，稳定性实在太差～
so，我放弃搞官方IP版的YouTube hosts！

**Comment by lrinQVQ** [comment]
23333 你用的SNI啊 无污染DNS也没用的啦 Youtube的解析依赖的是redirector.googlevideo.com 如果这个域名有问题 那么基本上GG的233

**Comment by sy618** [comment]
我是在非sni环境下测试的

**Comment by lrinQVQ** [comment]
欸xd 看你啦看你啦 我指的是这个文件https://github.com/sy618/hosts/blob/master/y 233

**Comment by sy618** [comment]
redirector.googlevideo.com
manifest.googlevideo.com
这两个域名都指向sni了，只是没放在y里

**Comment by lrinQVQ** [comment]
我指的...
25e9ec7
006479f
加入到
https://github.com/sy618/hosts/blob/master/y

**Comment by aofall** [comment]
https://github.com/wangchunming/2017hosts

README有惊喜

**Comment by lychichem** [comment]
已经有issue讨论过了而且issue已经关了，这哥们也是太跳

发送自我的iPhone

在 2017年7月14日，16:11，aofall <notifications@github.com<mailto:notifications@github.com>> 写道：


https://github.com/wangchunming/2017hosts

README有惊喜
