### ISSUE TITLE
关于Twitter

### ISSUE THREAD

**Issue by lrinQVQ** [racaljk/hosts#1259]
GFW没有针对IP的证书进行过滤只是针对www.twitter.com域名本身进行封锁xd
首先:
我拿到一个本来没有被封锁的国外IP:216.58.192.76
![2017-07-10 10-37-44](https://user-images.githubusercontent.com/12861134/28001712-5240590a-6561-11e7-9c5d-4eddab5b983c.png)

并且将twitter的所有域名修改为此ip,打开twitter
它本来443端口没有被封锁,然后瞬间GG
![2017-07-10 11-09-10](https://user-images.githubusercontent.com/12861134/28001824-6551e242-6562-11e7-9101-70eaecf91406.png)
![2017-07-10 11-16-48](https://user-images.githubusercontent.com/12861134/28001832-743ac56c-6562-11e7-800e-3ed5a6124135.png)
 过了一会自动恢复 如果是这种情况的话xd 哪怕是无证书的ip也无法访问twitter了 思考解决方案ing
PS:中国/香港等的IP貌似是不会出现这种情况的,本想利用这个炸了百度,然后发现百度的IP都是在香港/中国的 xd

**Comment by kobeking** [comment]
可以参考 go hosts 里面的 Twitter ip

**Comment by lrinQVQ** [comment]
2333 试过了直接重置

**Comment by lrinQVQ** [comment]
sudo hping3 -S -p 443 219.76.4.14
HPING 219.76.4.14 (enp0s31f6 219.76.4.14): S set, 40 headers + 0 data bytes
^C
--- 219.76.4.14 hping statistic ---
7 packets transmitted, 0 packets received, 100% packet loss
round-trip min/avg/max = 0.0/0.0/0.0 ms

**Comment by lrinQVQ** [comment]
同样也是打开了一下233直接重置

**Comment by sy618** [comment]
我有个反代的IP可用。
不过为避免被封锁，不建议用在此项目里。

**Comment by lrinQVQ** [comment]
2333没用的 封锁域名 反代我也用过了的

**Comment by sy618** [comment]
我在6月十六号修改的，已经正常用了26天了。
不过我看已经用不了多久就会被封杀，因为已经被人抄袭并广泛传播出去了。

感觉有些人为了盈利，特别积极的传播。

**Comment by lrinQVQ** [comment]
+1 2333  我试了一个下午 只要是twitter.vom 除了香港/中国的IP段一律重置 10多秒之后又恢复

**Comment by lrinQVQ** [comment]
短时间内xd 我不会公开找IP的方案了 GFW已经在利用了

**Comment by DDoSolitary** [comment]
@lrinQVQ 你不觉得XD的D小写的话形状完全走样了吗。。

**Comment by lrinQVQ** [comment]
@DDoSolitary 是欸!!!!!!!

**Comment by baihech** [comment]
@lrinQVQ 会不会被查水表

**Comment by lrinQVQ** [comment]
不会233333

**Comment by Makebignew** [comment]
GFW 是通过SNI Hello 会明文传输域名地址来检测*.twitter.com 的证书，一旦发现就阻断链接，是根据证书匹配的，理论上可以用来屏蔽任何SSL 站点

**Comment by lrinQVQ** [comment]
不不不不

**Comment by lrinQVQ** [comment]
twitter有学习google 将ip修改为无效证书的ip 但是根据我的测试就已经知道 哪怕ip是google的也会马上进行屏蔽

**Comment by vida-shamp** [comment]
一言蔽之，就是还能不能上twitter？？

**Comment by lrinQVQ** [comment]
很难了

**Comment by wan-qy** [comment]
>twitter有学习google 将ip修改为无效证书的ip

请问这样做用意何在

**Comment by vida-shamp** [comment]
twitter前天能上了，昨天和今天又挂了。今天YOUTUBE也挂了，地标，广州，长城宽带。

**Comment by lindexi** [comment]
youtube 一直都会挂，我自己搭建了ss

**Comment by lrinQVQ** [comment]
@vida-shamp 你可以试试刚刚的两个commit中的IP

**Comment by lrinQVQ** [comment]
https://github.com/racaljk/hosts/commit/9c35f7573cb5b23f147435838c9d227c50e5b34a 针对联通/电信

https://github.com/racaljk/hosts/commit/189a139b5cb7b46121a017ce16f637cf001b8791 针对移动被NAT用户

**Comment by Makebignew** [comment]
@lrinQVQ  173.194.223.202 已經黑洞

**Comment by ReturnPi** [comment]
我感觉Twitter受到这么严重的干扰是因为郭总的爆料。你们觉得呢？

**Comment by Sharkkkk** [comment]
@lrinQVQ @Makebignew 为什么只检测了twitter.com 的证书，Google的不检查？加多一条应该不难吧，Google IP这么多，直接这样简单多了

**Comment by lrinQVQ** [comment]
https://github.com/racaljk/hosts/issues/1349
