### ISSUE TITLE
难道就我一个人访问不了了吗？

### ISSUE THREAD

**Issue by ananas-xxj** [racaljk/hosts#1262]
昨天就开始了，看看有没有人跟我一样，还是我自己的问题吗？  昨天以前还好好的

**Comment by dawangjiaowolaifatie** [comment]
访问不了哪个网站

**Comment by ananas-xxj** [comment]
@dawangjiaowolaifatie google 你能访问吗  不开其他

**Comment by dawangjiaowolaifatie** [comment]
@ananas-xxj 谷歌能访问啊 没问题啊

**Comment by ananas-xxj** [comment]
@dawangjiaowolaifatie 那应该是我自己这边的问题了  好像昨天清了下cookies什么的 就不行了

**Comment by uchen1225** [comment]
试试这个https://www.google.com/ncr

**Comment by lrinQVQ** [comment]
线路抽风而已 已可用
