### ISSUE TITLE
作者小心！！！

### ISSUE THREAD

**Issue by Guanrenfu** [racaljk/hosts#1263]
小心不要被查水表了
现在查的越来越厉害了
https://github.com/wangchunming/2017hosts

**Comment by DDoSolitary** [comment]
提供一个防止被查的方案：统一使用一个bot账号来进行操作，各位collaborator持有该账号的SSH key

**Comment by lychichem** [comment]
我记得这人十分招摇啊，果然进去了

**Comment by EMLVIRUS** [comment]
我在想我要不要也低调点。。。毕竟我好像容易被群殴。。。

**Comment by sy618** [comment]
如果没有进行过盈利行为，那么应该没事的。最多就是交罚款

**Comment by EMLVIRUS** [comment]
@sy618 然而我穷 连罚款都交不起

**Comment by DDoSolitary** [comment]
我被叫去派出所的话我爸妈会伤心的。。 😆

**Comment by kobeking** [comment]
好的 项目会有人自发捐款交赎金

**Comment by dawangjiaowolaifatie** [comment]
我们大王那么萌，谁敢抓？

**Comment by lrinQVQ** [comment]
我是不怕的2333 要抓就来吧233

**Comment by kusion** [comment]
fuck......

**Comment by Ir1d** [comment]
Best Wishes.

**Comment by imknown** [comment]
希望这里没有不理智的人.
