### ISSUE TITLE
你们最近有没有遇到间歇式的连接失败/缓慢？

### ISSUE THREAD

**Issue by jimmyshjj** [racaljk/hosts#1265]
一个小时前访问谷歌缓慢，后来好了，现在又连不上了
ping 了一下，连接率很低
不知道是不是电信网络的问题

**Comment by jimmyshjj** [comment]
![default](https://user-images.githubusercontent.com/26865145/28063570-15ad04e4-6664-11e7-8ff6-0df11828d528.png)

**Comment by zhenhappy** [comment]
我压根就没连接成功过

**Comment by lrinQVQ** [comment]
请使用https://www.google.com/ncr无国别跳转防止链接被重置

**Comment by lrinQVQ** [comment]
电信得确出国难的说xd

**Comment by jimmyshjj** [comment]
![2](https://user-images.githubusercontent.com/26865145/28066298-024aa95a-666f-11e7-8cf6-a8c9bb4eec2c.png)
一直用ncr，但是也不行
twitter也是挂的，但facebook、zh.wikipedia.org是好的
看样子是电信的问题

**Comment by lrinQVQ** [comment]
xd Google丢包严重计划更换

**Comment by blindlf** [comment]
上个月还是很快的，这个月时不时连不上

**Comment by imknown** [comment]
电信坑

**Comment by lrinQVQ** [comment]
线路抽风xd
