### ISSUE TITLE
【无法访问报告】G*o*o*g*l*e 无法访问

### ISSUE THREAD

**Issue by xfqz86** [racaljk/hosts#1267]
北京电信、河南郑州BGP等多地均无法访问Google。
Chrome浏览器提示：
无法访问此网站
网址为 https://www.google.com/ncr 的网页可能暂时无法连接，或者它已永久性地移动到了新网址。
ERR_CONNECTION_ABORTED

**Comment by lrinQVQ** [comment]
soga 得确证书被换了的说

**Comment by xfqz86** [comment]
额。。。已经清除Cookie访问依旧不行呢，多地测试结果都不行。。😓
最后，直接用自己写的工具访问，依旧不行。。。。
感觉是IP完蛋了。😱

**Comment by Sayinore** [comment]
无法连接Google+1，电信

**Comment by DDoSolitary** [comment]
我这边也挂了。。之前一直挂着代理没发现。。

**Comment by dawangjiaowolaifatie** [comment]
我的google chrome都不正常了。。

**Comment by Sayinore** [comment]
我这边可以ping通，但是就是不能访问，https也不行

**Comment by lrinQVQ** [comment]
准备更换咩

**Comment by lrinQVQ** [comment]
线路抽风xd 没问题了
