### ISSUE TITLE
(2017/07/11)Google访问被重置更新hosts文件

### ISSUE THREAD

**Issue by gcrepository** [racaljk/hosts#1268]
`(IP:216.58.200.33) -> (IP:172.217.27.68)。`

可以收藏此网站：[https://asm.ca.com/en/ping.php](url)

**Comment by lrinQVQ** [comment]
172.217.0.0/24段的IP稳定性感人xd

**Comment by sy618** [comment]
我试了几十个谷歌IP，刚开始连接很顺畅，一旦成功连接后就出现丢包现象，这过程大概持续3～5分钟，然后IP彻底gg。
现在墙已经开足马力，一旦探测到谷歌证书会先干扰后封锁了。

今天下午很多谷歌vps都挂了。

**Comment by lrinQVQ** [comment]
所以这就是我计划更新所有域名ip为不返回证书ip

**Comment by lrinQVQ** [comment]
线路抽风而已不影响 已经恢复

**Comment by lrinQVQ** [comment]
然后又抽风了
