### ISSUE TITLE
可否增加cloudfront.net的host？

### ISSUE THREAD

**Issue by zhangdong92** [racaljk/hosts#127]
开发者您好，如果可能，能否增加cloudfront.net的host？
主要原因是，访问Trello（https://trello.com ）时，放在CDN d78fikflryjgj.cloudfront.net/上的js和css文件全部无法获取，导致trello不能正常使用（例如 获取https://d78fikflryjgj.cloudfront.net/js/2ee0211a4b507f799343d465bc126dfb/snowplow.js 时，调试工具中查看情况是 failed net::ERR_TIMED_OUT，超时了），如果这个CDN能够加入到host中，或许就可以解决。
本人尝试过，寻找cloudfront.net对应的IP，但查到对应多个IP，尝试了数个IP加入到host均无效。
多谢！

**Comment by wlbksy** [comment]
北京地区可以打开网页的
你要不试试下面几个ip?

Name:	d78fikflryjgj.cloudfront.net
Address: 204.246.164.220
Name:	d78fikflryjgj.cloudfront.net
Address: 204.246.164.133
Name:	d78fikflryjgj.cloudfront.net
Address: 54.192.151.211
Name:	d78fikflryjgj.cloudfront.net
Address: 204.246.164.239
Name:	d78fikflryjgj.cloudfront.net
Address: 204.246.164.75
Name:	d78fikflryjgj.cloudfront.net
Address: 204.246.164.118
Name:	d78fikflryjgj.cloudfront.net
Address: 204.246.164.14
Name:	d78fikflryjgj.cloudfront.net
Address: 204.246.164.240

**Comment by zhangdong92** [comment]
也在北京地区，我发完之后测试，也可以打开了……准确地说是不稳定。
非常感谢，等下次不稳定时我测试一下
