### ISSUE TITLE
蛤蛤蛤并不能连接Google

### ISSUE THREAD

**Issue by baihech** [racaljk/hosts#1272]
大王，证书错误，chrome拒绝连接

**Comment by baihech** [comment]
This page cannot be loaded using Chrome Data Saver. Try reloading the page.

Debug info: GET lu5lWaXnJIPjiQP3q4zwDg

**Comment by lyonye** [comment]
同样的问题

**Comment by CKrome** [comment]
Firefox提示：
This Connection is Untrusted

You have asked Firefox to connect securely to www.google.com, but we can't confirm that your connection is secure.
What Should I Do?

If you usually connect to this site without problems, this error could mean that someone is trying to impersonate the site, and you shouldn't continue.
Technical Details

www.google.com uses an invalid security certificate. The certificate is only valid for the following names: googlezip.net, *.googlezip.net Error code: SSL_ERROR_BAD_CERT_DOMAIN

**Comment by lrinQVQ** [comment]
2333知道 在处理

**Comment by EricQLi** [comment]
+1

**Comment by baihech** [comment]
并不能。。。

**Comment by lrinQVQ** [comment]
啊 xd 又死了

**Comment by lrinQVQ** [comment]
现在已经不存在证书问题
寻找ip 中
