### ISSUE TITLE
Your connection is not private

### ISSUE THREAD

**Issue by lyonye** [racaljk/hosts#1273]
无法访问。
NOT SECURE:https://www.google.com/ncr

Your connection is not private

Attackers might be trying to steal your information from www.google.com (for example, passwords, messages, or credit cards). NET::ERR_CERT_COMMON_NAME_INVALID

或者出现：
This page cannot be loaded using Chrome Data Saver. Try reloading the page.

Debug info: GET kO5lWc7VIZuSiAP_nb3QAQ

**Comment by lrinQVQ** [comment]
处理Ing

**Comment by TroyBug** [comment]
联通 能 ping通 油管，但打不开主页。

**Comment by lrinQVQ** [comment]
2333 这段基本上炸了 另寻ING

**Comment by forever342** [comment]
win10,chrome，Firefox，IE都无法访问google.com.hk，查看证书，证书的域名是googlezip.com

**Comment by lrinQVQ** [comment]
咩瞬间切换证书

**Comment by lrinQVQ** [comment]
现在已经不存在证书问题
寻找ip 中
