### ISSUE TITLE
google访问被拒绝

### ISSUE THREAD

**Issue by Cnzw** [racaljk/hosts#1275]
安卓Flyme6 MX6 firefox53.0.2 和yandex都提示连接被拒绝
而另一部emui5.1 firefox却可以正常访问
win10 chrome59也可以正常访问，不过很多图片都加载不出来

**Comment by lrinQVQ** [comment]
谷歌在不断更新证书 所以时不时能用 我在寻找其他ip

**Comment by Cnzw** [comment]
谢谢解答，因为我的其他设备都可以上google还以为魅族坏了呢:）

**Comment by laodcn** [comment]
@lrinQVQ 我这里有一枚，不过很多人说216.58.200.33这个还能用，速度还不错...所以我没换

**Comment by mycompanycomputer** [comment]
@laodcn  那个ip只有chrome能用。fx，edge，ie都不行

**Comment by p0mp0k0** [comment]
用修正了google的版本，google仍然全线不能访问
打开www.google.com，就提示
This page cannot be loaded using Chrome Data Saver. Try reloading the page.

Debug info: GET EQdnWc6EAdmZiQP9iLbwBw

**Comment by lrinQVQ** [comment]
@laodcn 谷歌最近在疯狂换证书一会可用一会不可用的xd

**Comment by p0mp0k0** [comment]
修正google后的还是不能用

**Comment by lrinQVQ** [comment]
fix now
