### ISSUE TITLE
无法访问https://www.google.com，证书错误

### ISSUE THREAD

**Issue by ashareye** [racaljk/hosts#1279]
当我下载并置换hosts之后，出现以下错误：

www.google.com 使用了无效的安全证书。

该证书仅对下列域名有效：
  googlezip.net, *.googlezip.net  

错误代码: SSL_ERROR_BAD_CERT_DOMAIN

此网站采用了 HTTP 严格传输安全（HSTS）机制，要求 Firefox 只能与其建立安全连接。正因如此，您也不能将此证书加入例外列表。所以无法使用

**Comment by tupunco** [comment]
一样的问题

**Comment by 2puT** [comment]
同样的问题

**Comment by 2puT** [comment]
![screenshot_20170713_084856](https://user-images.githubusercontent.com/20620098/28145860-20ecc840-67a8-11e7-865f-3bfd250b8538.png)
google失败

**Comment by laodcn** [comment]
谷歌在换SSL

**Comment by hupan508** [comment]
有解决办法没有？

**Comment by HakureiMarisa** [comment]
等大佬有时间更新啊，不要急噻

**Comment by qxhy123** [comment]
一样的问题

**Comment by lrinQVQ** [comment]
昨天有些不舒服 今天来处理ing
谷歌在疯狂换证书 不知道怎么了

**Comment by lrinQVQ** [comment]
啧找了N多IP证书有效期都只有2个月

**Comment by longqi293** [comment]
@lrinQVQ 慢慢来，这个估计也不是技术上的问题，应该是更高层面的原因了

**Comment by lrinQVQ** [comment]
现在已经不存在证书问题
寻找ip 中

**Comment by laodcn** [comment]
@lrinQVQ  i@laod.top 我刚刚用gmail测试了下，正常收信呀 0.0

你是不是地址弄错了？

**Comment by lrinQVQ** [comment]
@laodcn 咦我直接说了吧xd git push hosts hosts-source
