### ISSUE TITLE
求Dropbox的hosts呀

### ISSUE THREAD

**Issue by wangchi** [racaljk/hosts#128]
有可以用的Dropbox的hosts么？

**Comment by cdroad** [comment]
不是一直可以用么……

**Comment by wang950312** [comment]
为什么youtube上的视频看不了，能进网站

**Comment by wangchi** [comment]
还是用[Google Drive](https://www.google.com/intl/zh-CN/drive/download/)吧，这里的hosts直接就可以用，还是挺快的.
