### ISSUE TITLE
This page cannot be loaded using Chrome Data Saver. Try reloading the page.  Debug info: GET gMFmWdOMFMaDiwORi5HICA

### ISSUE THREAD

**Issue by Alicealpha** [racaljk/hosts#1280]
打开所有的Google地址页面全是这种提示：
This page cannot be loaded using Chrome Data Saver. Try reloading the page.

Debug info: GET gMFmWdOMFMaDiwORi5HICA （注：有些页面的debug可能不同）

**Comment by excellenttank** [comment]
从昨天就开始出现这样的问题，今天变成不是私密连接了

**Comment by Alicealpha** [comment]
真是奇了怪啊，，，Google所有的地址不能连接了。。。好像是什么证书问题？访问YouTube的很慢的

2017-07-13 9:09 GMT+08:00 excellenttank <notifications@github.com>:

**Comment by p0mp0k0** [comment]
访问google.com就是这个错误，访问其他的google地址就全部不能访问，用的是fix了google.com后的版本，依然是这样的问题

**Comment by Alicealpha** [comment]
有没有更好的结局办法，其他浏览器也试了

2017-07-13 13:40 GMT+08:00 p0mp0k0 <notifications@github.com>:

**Comment by lrinQVQ** [comment]
昨天有些不舒服 今天来处理ing

**Comment by Alicealpha** [comment]
😎

2017-07-13 14:11 GMT+08:00 lrin <notifications@github.com>:

**Comment by lrinQVQ** [comment]
现在已经不存在证书问题
寻找ip 中

**Comment by super3H** [comment]
同问！！！
