### ISSUE TITLE
不是私密连接

### ISSUE THREAD

**Issue by mattholy** [racaljk/hosts#1281]
访问Google出现了不是私密连接的问题

**Comment by sure-one** [comment]
同出现此错误：

您的连接不是私密连接

攻击者可能会试图从www.google.com.hk窃取您的信息（例如：密码、通讯内容或信用卡信息）。 NET::ERR_CERT_COMMON_NAME_INVALID

**Comment by excellenttank** [comment]
怎么解决

**Comment by ykfq** [comment]
我也是遇到同样的问题：

This page cannot be loaded using Chrome Data Saver. Try reloading the page.

Debug info: GET NM9mWdiIGMqciAPok72IBQ

**Comment by Luzhixing** [comment]
This page cannot be loaded using Chrome Data Saver. Try reloading the page.
2017/7/13 10:31  发生了什么QAQ

**Comment by ViK0L** [comment]
解决了没有？遇到相同的问题

**Comment by sheepbao** [comment]
<img width="1440" alt="screen shot 2017-07-13 at 10 43 16 am" src="https://user-images.githubusercontent.com/13062034/28148244-1f1a8f10-67b8-11e7-98b6-da65b104e51c.png">
一样

**Comment by yangzheng1994** [comment]
+1

**Comment by LYZName** [comment]
+1,我的从昨天开始就不能用了

**Comment by beckhamwjc** [comment]
+1 Is it because the upcoming conference in China? 我很惶恐啊

**Comment by lrinQVQ** [comment]
昨天有些不舒服 今天来处理ing

**Comment by longqi293** [comment]
同样遇到了这个问题，+1

**Comment by lrinQVQ** [comment]
fix now
