### ISSUE TITLE
host缺失

### ISSUE THREAD

**Issue by CrackFileso** [racaljk/hosts#1282]
lh3.googleusercontent.com
ssl.google-analytics.com
fonts.googleapis.com
csi.gstatic.com

**Comment by Makebignew** [comment]
除了lh3.googleusercontent.com这个域名，剩下三个都是解析到谷歌大陆服务器，可以直接访问

**Comment by lrinQVQ** [comment]
https://github.com/racaljk/hosts/issues/1349
