### ISSUE TITLE
The certificate for this server is invalid. 

### ISSUE THREAD

**Issue by eternalyean** [racaljk/hosts#1283]
The certificate for this server is invalid. You might be connecting to a server that is pretending to be “tools.google.com” which could put your confidential information at risk. [NSURLErrorDomain:-1202] (The certificate for this server is invalid. You might be connecting to a server that is pretending to be “tools.google.com” which could put your confidential information at risk. [kCFErrorDomainCFNetwork:-1202])
KSServerUpdateRequest fetch failed. (productID: com.google.Chrome) [com.google.UpdateEngine.CoreErrorDomain:702 - 'https://tools.google.com/service/update2?cup2hreq=7c0a42bdc4669969ef35dbe454b5e05e545328293e32927d24c7a37c397f6a3a&cup2key=7:1303156458'] (The certificate for this server is invalid. You might be connecting to a server that is pretending to be “tools.google.com” which could put your confidential information at risk. [NSURLErrorDomain:-1202])
Could not connect to the server. [NSURLErrorDomain:-1004] (Could not connect to the server. [kCFErrorDomainCFNetwork:-1004])
KSServerUpdateRequest fetch failed. (productID: com.google.Chrome) [com.google.UpdateEngine.CoreErrorDomain:702 - 'http://tools.google.com/service/update2?cup2hreq=7c0a42bdc4669969ef35dbe454b5e05e545328293e32927d24c7a37c397f6a3a&cup2key=7:1333149416'] (Could not connect to the server. [NSURLErrorDomain:-1004])

**Comment by lrinQVQ** [comment]
昨天有些不舒服 今天来处理ing

**Comment by eternalyean** [comment]
@lrinQVQ dalao注意身体

**Comment by lrinQVQ** [comment]
谷歌在疯狂换证书xd

**Comment by lrinQVQ** [comment]
Expires on: 2017年9月27日
Current date: 2017年7月13日
有效期仅两个月

**Comment by hhhaiai** [comment]
我天呢.  @lrinQVQ  拉群吧  认证后的 工作人员一个群.  几个人维护太费劲

**Comment by eternalyean** [comment]
更新OK了

**Comment by lrinQVQ** [comment]
呼部分能用了

**Comment by lrinQVQ** [comment]
https://t.me/joinchat/DsyANUJc-sKXYa2NZ-rNVA新的群
