### ISSUE TITLE
改完host访问失败

### ISSUE THREAD

**Issue by onewesong** [racaljk/hosts#1285]
打开提示证书过期
![image](https://user-images.githubusercontent.com/17920822/28159646-387353ec-67f0-11e7-8b7e-770e2c4945cf.png)
点击继续访问后提示
![image](https://user-images.githubusercontent.com/17920822/28159663-43eafa36-67f0-11e7-8ce9-5a17064c90e1.png)
This page cannot be loaded using Chrome Data Saver. Try reloading the page.

Debug info: GET 4DxnWYzFMcqdiwOJg4fADw

请问这是什么问题？

**Comment by HzDSN** [comment]
这几天谷歌服务器一直在被干扰，建议使用科学上网。

**Comment by onewesong** [comment]
这种方式不行了吗？那要怎么科学上网

**Comment by lrinQVQ** [comment]
更新了 应该OK

**Comment by lrinQVQ** [comment]
不是谷歌服务器被干扰啦xd 是谷歌在换证书

**Comment by lcdlyxrqy** [comment]
@lrinQVQ 新的hosts里的ip甚至都ping不通了嘤……

**Comment by lrinQVQ** [comment]
2333不哭不哭 干扰严重xd 继续换吧

**Comment by reflexit** [comment]
电信，google无法ping通……

**Comment by lrinQVQ** [comment]
win下需要加-t 丢包严重xd

**Comment by dawangjiaowolaifatie** [comment]
大王今天身体不舒服，你们不要搞这么多issue，大王都快被炸晕了。

**Comment by lrinQVQ** [comment]
2333没事没事 这两天谷歌应该在维护 稳定性基本上感人

**Comment by lslzl3000** [comment]
更新后的ip ping不通~ 
先休息吧，等有时间再弄

**Comment by lrinQVQ** [comment]
ping确实丢包感人昂 时间现在还是有的啦2333 就是大多数IP都在换证书很伤xd

**Comment by chenjia1949** [comment]
大王辛苦了

**Comment by lrinQVQ** [comment]
小问题啦xd 先做饭吃继续搞

**Comment by derekwei** [comment]
感觉最近每上一个ip阵亡率都特别感人

**Comment by onewesong** [comment]
好奇ip是怎么get的

**Comment by xuelianhan** [comment]
辛苦辛苦 ，问ip怎么搞的问题都有可能是在钓鱼，不要问太多，也不要回答

**Comment by lrinQVQ** [comment]
fix now
