### ISSUE TITLE
TUMBLR怎么访问用户界面

### ISSUE THREAD

**Issue by ws69** [racaljk/hosts#1286]
在TUMBLR访问他人用户界面时，二级域名会变成用户名称，然后就不能访问，

如
-www.tumblr.com
会变成
- blabla.tumblr.com

估计是HOSTS里没有对应的，请问怎么解决呢？

**Comment by DDoSolitary** [comment]
自己加相关hosts条目

**Comment by ws69** [comment]
关键是IP要怎么拿到

**Comment by DDoSolitary** [comment]
```
66.6.32.21
66.6.33.21
66.6.33.149
```
