### ISSUE TITLE
貌似新IP 172.217.11.68 又躺了

### ISSUE THREAD

**Issue by ykfq** [racaljk/hosts#1287]
从北京、成都等地telnet 443端口不通
[root@computer01 ~]# telnet 172.217.11.68 443
Trying 172.217.11.68...
telnet: connect to address 172.217.11.68: Connection timed out
[root@computer01 ~]# date
Fri Jul 14 00:03:47 CST 2017
[root@computer01 ~]#

**Comment by lrinQVQ** [comment]
a XD

**Comment by XhstormR** [comment]
对的，又躺了。。。

**Comment by excellenttank** [comment]
躺，躺，躺，躺了，了，了

**Comment by Makebignew** [comment]
@lrinQVQ   118.193.28.254 香港云IDC 联通绕美国
电信绕日本 延迟170+速度还行

**Comment by excellenttank** [comment]
@Makebignew 目前比较稳定

**Comment by ykfq** [comment]
好人一生平安

**Comment by laodcn** [comment]
@lrinQVQ 
hosts文件 第3921行   203.84.197.27	hk.finance.yahoo.com0
域名后面多了个0，请修正下

**Comment by PW-Chen** [comment]
#1290  @laodcn

**Comment by lrinQVQ** [comment]
@laodcn 来来来 来TG 我发了邮箱好像你收不到欸xd

**Comment by lrinQVQ** [comment]
ps:本项目不用sni

**Comment by lrinQVQ** [comment]
fix now

**Comment by laodcn** [comment]
@lrinQVQ 改邮箱了，发到top后缀

**Comment by lrinQVQ** [comment]
@laodcn 2333发了也不行啊

**Comment by superewe** [comment]
255x200 ∴ telnet 172.217.11.68 443
Trying 172.217.11.68...
Connected to 172.217.11.68.
Escape character is '^]'.
