### ISSUE TITLE
看来是修不好了，大家刷版聊天吧

### ISSUE THREAD

**Issue by baihech** [racaljk/hosts#1288]
乳体

**Comment by hhhaiai** [comment]
我去.

**Comment by liu35118665** [comment]
特别厉害，我刚找了连个ip，telnet能通，一改hosts，访问一下，立马就不通了。这技术太牛逼了

**Comment by gcrepository** [comment]
我找到一个不太稳定（216.58.206.68）。

**Comment by Makebignew** [comment]
118.193.28.254 香港云IDC 联通绕美国
电信绕日本 延迟170+速度还行 不会秒封

**Comment by baihech** [comment]
已经上ss了

**Comment by gcrepository** [comment]
北京联通，亲测。118.193.28.254可用。备用216.58.206.68。

**Comment by WeihuaGu** [comment]
@gcrepository 能用，但是我这里慢成狗（陕西的）

**Comment by baihech** [comment]
上海电信，不能用

**Comment by CKrome** [comment]
现在只有老D那个13号的hosts能用，其余都挂了

**Comment by noname007** [comment]
@CKrome  能给个连接吗？

**Comment by gcrepository** [comment]
@WeihuaGu @baihech @CKrome 

`C:\Users\Administrator>ping 118.193.28.254

正在 Ping 118.193.28.254 具有 32 字节的数据:
来自 118.193.28.254 的回复: 字节=32 时间=212ms TTL=46
来自 118.193.28.254 的回复: 字节=32 时间=211ms TTL=46
来自 118.193.28.254 的回复: 字节=32 时间=211ms TTL=46
来自 118.193.28.254 的回复: 字节=32 时间=211ms TTL=46

118.193.28.254 的 Ping 统计信息:
    数据包: 已发送 = 4，已接收 = 4，丢失 = 0 (0% 丢失)，
往返行程的估计时间(以毫秒为单位):
    最短 = 211ms，最长 = 212ms，平均 = 211ms

C:\Users\Administrator>ping 216.58.206.68

正在 Ping 216.58.206.68 具有 32 字节的数据:
来自 216.58.206.68 的回复: 字节=32 时间=292ms TTL=48
来自 216.58.206.68 的回复: 字节=32 时间=296ms TTL=48
来自 216.58.206.68 的回复: 字节=32 时间=297ms TTL=48
来自 216.58.206.68 的回复: 字节=32 时间=291ms TTL=48

216.58.206.68 的 Ping 统计信息:
    数据包: 已发送 = 4，已接收 = 4，丢失 = 0 (0% 丢失)，
往返行程的估计时间(以毫秒为单位):
    最短 = 291ms，最长 = 297ms，平均 = 294ms`

我这边情况很不错。延迟也不高。

**Comment by baihech** [comment]
@gcrepository 这个ip可以的，非常感谢

**Comment by excellenttank** [comment]
#1287 里面有个地址，替换一下，目前我这里比较稳定

**Comment by HakureiMarisa** [comment]
来啊 相亲啊

**Comment by WeihuaGu** [comment]
@gcrepository 恩。我这边是不稳定，刚试了下速度可以，再试又不行。用mtr看了下，是在两个节点上丢的太厉害。一个120.192.227.81(西安） Loss 87%，一个221.183.21.198 loss 98.3% 
感谢，反正等一等还是可以用的：）

**Comment by WeihuaGu** [comment]
@HakureiMarisa 这里难道有女生？……

**Comment by baihech** [comment]
@HakureiMarisa 难道我上的是假的GaytHub，这不是全球最大的同性交友网站么？

**Comment by excellenttank** [comment]
我这里又不行了

**Comment by CKrome** [comment]
@noname007 laod.cn

**Comment by HakureiMarisa** [comment]
@WeihuaGu @baihech 哈哈，家里的姐姐妹妹也拿出来相一波啊。做不成恋人可以做亲戚啊

**Comment by djldhc** [comment]
大家去用老d的那个吧

**Comment by programmer-ma** [comment]
目前来说老d可用

**Comment by xmdhs** [comment]
老d的IP 216.58.200.192

**Comment by yym0924** [comment]
@xmdhs 这个能用，不过好慢啊

**Comment by qxhy123** [comment]
@WeihuaGu 这么巧, 我也是西安的

**Comment by WeihuaGu** [comment]
@qxhy123 我铜川的……。你算大西安

**Comment by qxhy123** [comment]
@WeihuaGu 都是大陕西的

**Comment by WeihuaGu** [comment]
@qxhy123 恩，大陕西的。

**Comment by WeihuaGu** [comment]
@HakureiMarisa 我家就我一个，没有姐姐妹妹哥哥弟弟，会孤独终老的……

**Comment by sighsmile** [comment]
@WeihuaGu 这里为什么不能有女生 - -

**Comment by eternalyean** [comment]
怕不是女装dalao

**Comment by WeihuaGu** [comment]
@sighsmile 太少了，况且对于github来说也是狼多肉少，竞争太大。
