### ISSUE TITLE
7月14刚刚更新的hosts仍然无法使用

### ISSUE THREAD

**Issue by CKrome** [racaljk/hosts#1292]
还是证书问题
This Connection is Untrusted

You have asked Firefox to connect securely to www.google.com, but we can't confirm that your connection is secure.
What Should I Do?

If you usually connect to this site without problems, this error could mean that someone is trying to impersonate the site, and you shouldn't continue.
Technical Details

www.google.com uses an invalid security certificate. The certificate is only valid for the following names: googlezip.net, *.googlezip.net Error code: SSL_ERROR_BAD_CERT_DOMAIN

**Comment by CKrome** [comment]
但7月13的hosts能用，就是速度有点慢

**Comment by lrinQVQ** [comment]
== 又换证书跟我有仇吗

**Comment by HakureiMarisa** [comment]
好像确实不行，我这显示的是
您的连接不是私密连接

攻击者可能会试图从www.google.com窃取您的信息（例如：密码、通讯内容或信用卡信息）。 NET::ERR_CERT_COMMON_NAME_INVALID
Subject: googlezip.net
Issuer: Google Internet Authority G2
Expires on: 2017年9月27日
Current date: 2017年7月14日

大佬加油

**Comment by lrinQVQ** [comment]
啊xd 果然plan b 只能给部分人用 我继续看看xd

**Comment by zhiblin** [comment]
我也是不能用，好奇怪啊

**Comment by lrinQVQ** [comment]
![2017-07-14 17-29-29](https://user-images.githubusercontent.com/12861134/28206813-01512a40-68ba-11e7-89bf-745657364ee7.png)
内心贼崩溃贼

**Comment by HakureiMarisa** [comment]
chrome

**Comment by lrinQVQ** [comment]
xd 我也是Chrome

**Comment by TaskForce86** [comment]
google.com/ncr连不上. win10(chrome ff opera) MIUI(chrome).
chrome的报错是一样的"This page cannot be loaded using Chrome Data Saver. Try reloading the page."根本就没开data saver

**Comment by zhiblin** [comment]
ip 不一样
 
ping google.com.hk
PING google.com.hk (172.217.11.68): 56 data bytes
Request timeout for icmp_seq 0
Request timeout for icmp_seq 1
Request timeout for icmp_seq 2
Request timeout for icmp_seq 3
Request timeout for icmp_seq 4
Request timeout for icmp_seq 5
Request timeout for icmp_seq 6
Request timeout for icmp_seq 7
Request timeout for icmp_seq 8

**Comment by lrinQVQ** [comment]
打开科学上网和关闭科学上网后的反应不同 目前在判断是gfw搞事情还是谷歌问题

**Comment by racaljk** [comment]
7.10-hosts表示用的美滋滋,没有问题

**Comment by wallena3** [comment]
咋回事腻 😘

**Comment by lrinQVQ** [comment]
现在看看0.0

**Comment by Sayinore** [comment]
还是证书问题；开fg之后没问题

**Comment by CKrome** [comment]
不稳定，时能用时不能用

**Comment by lrinQVQ** [comment]
昂 情况不同你们可以把Youtube的新ip 替换上去

**Comment by lrinQVQ** [comment]
fix now
