### ISSUE TITLE
youtube更新之后还是无法打开

### ISSUE THREAD

**Issue by liguge** [racaljk/hosts#1293]
youtube更新之后还是无法打开啊 广电的网络~

**Comment by lrinQVQ** [comment]
广电嘛2333 有点悲伤咳咳

**Comment by Deercyan** [comment]
奇怪，我U2b客户端打开了一下，然后只能打开网页了

**Comment by lrinQVQ** [comment]
https://github.com/racaljk/hosts/issues/1349
