### ISSUE TITLE
最新的hosts还是无法访问google

### ISSUE THREAD

**Issue by reflexit** [racaljk/hosts#1294]
昨晚更新的hosts仍无法访问google，确保是用https://www.google.com/ncr
上海电信网，仅能够ping通。

(昨天看到关于google的issue都close了，不知道是不是我个人的问题……)

**Comment by XiaolinZHONG** [comment]
我的也是这种情况，上海电信

**Comment by auoong** [comment]
我的也是不行，山东电信。

**Comment by swwind** [comment]
我改成121.59.17.10就好了

**Comment by swwind** [comment]
浙江电信

**Comment by zyf2008Neptune** [comment]
上海电信+1

**Comment by 111116** [comment]
江苏电信+1

**Comment by ZhongyangQian** [comment]
河南联通＋1

**Comment by yalong1221** [comment]
浙江电信 121.59.17.10可用

**Comment by wolfan** [comment]
扶南联通也是一样~

**Comment by SerCom-KC** [comment]
121.59.17.10 显然不是官方IP = =
风险自负）

**Comment by lrinQVQ** [comment]
xd 这个段不稳定但是是没有频繁更换证书的段

**Comment by huangjiasingle** [comment]
北京联通+1

**Comment by wolfan** [comment]
难道与刘**挂掉有关？

**Comment by CKrome** [comment]
@wolfan 不是，貌似从11号下午就开始了，XXX联合ISP暴力干掉了一些IP

**Comment by lrinQVQ** [comment]
现在大多数用户拨号都是在三层NAT下 都没有公网IP的 GFW 和 ISP配合封锁还是容易的

**Comment by lslzl3000** [comment]
北京移动一样上不去，请大家再找找新的替换ip

**Comment by yalong1221** [comment]
查看历史hosts 会找到可用的

**Comment by Makebignew** [comment]
@reflexit @huangjiasingle @XiaolinZHONG @111116
61.153.20.229   可用

**Comment by reflexit** [comment]
上面2个ip地址我这边均可用

**Comment by wukent** [comment]
直通google海底光缆，61.153.20.229。

**Comment by zhiblin** [comment]
61.153.20.229 可以用

**Comment by lrinQVQ** [comment]
fix now
