### ISSUE TITLE
为什么下载youtube视频的那个网址不在了，求大神在给出链接，忘记保存了。

### ISSUE THREAD

**Issue by zdiank** [racaljk/hosts#1295]

**Comment by Ir1d** [comment]
https://github.com/racaljk/hosts/search?q=%E4%B8%8B%E8%BD%BDyoutube%E8%A7%86%E9%A2%91&type=Issues&utf8=%E2%9C%93

#879

**Comment by feixia5712** [comment]
我说的是你们提供的一个网址，只需要吧youtube的视频链接放进去，就可以下载了，哪个网站，你们删除了在wiki里面。不知道为什么，能在提供下吗？谢谢

**Comment by Ir1d** [comment]
如果你搜索都不能搜的话
如果我提供了一个链接你都点不了的话
我还能说什么呢

visit #879 and you'll find https://www.onlinevideoconverter.com

**Comment by lrinQVQ** [comment]
xd 对了 我在wik里面删除掉了 果咩

**Comment by feixia5712** [comment]
谢谢
