### ISSUE TITLE
怎么弄这个自动生成Hosts的东西

### ISSUE THREAD

**Issue by aoxiangtianji** [racaljk/hosts#1296]
请问您是怎么弄这个自动更新Hosts的东西的？
我也想弄一个，能否教教我？

**Comment by aoxiangtianji** [comment]
@racaljk

**Comment by Too-Naive** [comment]
问题表意不明

**Comment by lslzl3000** [comment]
自己看readme去… 很多方法…

**Comment by aoxiangtianji** [comment]
因为README说hosts程序自动生成的，所以我想学一学怎么弄的

**Comment by lrinQVQ** [comment]
xd 只有hosts是程序自动生成的 这部门是由 @DDoSolitary 实现的 你要是学过Node.js自己看代码就能看懂2333

**Comment by DDoSolitary** [comment]
@aoxiangtianji 数据还是人工获取的，只是自动转换为不同的格式而已

**Comment by lrinQVQ** [comment]
是的2333
