### ISSUE TITLE
hosts v4的地址好像都失效了，只能用v6了

### ISSUE THREAD

**Issue by sbw983** [racaljk/hosts#1297]
RT
自己用gogotest搜了一些v4的ip，能ping通，但是一连就reset了，这次gfw估计在大抽风。v6的也只能搜到有限的几个
下面是我搜到的一些v4的ip，你们也试一下
这些ip估计放GoAgent里可能有用，但是放hosts里就无效
108.177.97.148   0175   *.doubleclick.net
 216.58.197.158   0185   *.google.com
    64.9.229.77   0198   *.google.com
08.177.112.110   0244   google.com
 216.58.193.199   0244   *.mail.google.com
 108.177.104.91   0245   *.google.com
108.177.104.119   0245   edge-static.google.com
 209.85.145.119   0247   edge-static.google.com
 172.217.12.158   0247   *.google.com
  172.217.8.127   0247   *.google.com
 108.177.103.84   0247   accounts.google.com
 209.85.147.119   0249   edge-static.google.com
 172.217.10.210   0249   *.unicast.metric.gstatic.com
 172.217.26.207   0249   upload.video.google.com
 108.177.96.202   0250   misc-sni.google.com
 172.217.22.132   0251   www.google.com
108.177.120.98   0275   *.google.com
 172.217.17.157   0276   *.google.com
 173.194.198.81   0276   sandbox.google.com
108.177.119.142   0277   *.au.doubleclick.net
  108.177.10.81   0278   sandbox.google.com
  209.85.234.90   0281   cert-test.sandbox.google.com
 172.217.11.175   0281   upload.video.google.com
 108.177.13.120   0282   *.gstatic.com
108.177.112.149   0283   *.doubleclick.net
  172.217.12.87   0283   google.com
  66.102.12.220   0284   *.google.com
  209.85.144.90   0381   cert-test.sandbox.google.com
 64.233.178.107   0388   www.google.com
 172.217.23.125   0389   *.google.com
 74.125.132.195   0391   google.com
 172.217.28.210   0393   *.unicast.metric.gstatic.com
  172.217.30.67   0393   google.com
  172.217.30.47   0394   upload.video.google.com
  209.85.235.31   0399   *.google.com
 172.217.22.210   0400   *.unicast.metric.gstatic.com
 172.217.28.184   0528   *.google.com
  172.217.8.152   0532   *.google.com
 216.58.204.153   0546   *.google.com
  172.217.5.218   0559   *.google.com
 64.233.165.110   0607   google.com
 216.58.207.103   0634   *.mail.google.com

**Comment by sbw983** [comment]
现在最省事的办法还是走代理或者vpn，hosts越来越难弄了

**Comment by lrinQVQ** [comment]
如果楼主有去了解Google新的证书/Google服务器的新协议 就不会这么说了XD
楼主给出的IP我都能够通过明文得到证书2333 基本上没救

_Sent from my Xiaomi MI 5s for dandan using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by sbw983** [comment]
不好意思，我不清楚，毕竟我不是程序员（只给工控的plc写过程序）楼上有介绍吗？

**Comment by lrinQVQ** [comment]
2333 是这样子的 Google的部分IP已经不再返回明文证书 就是不能直接看到IP对应证书的域名,在这种情况下GFW是无能为力的

**Comment by Makebignew** [comment]
@sbw983  61.153.20.229 宁波电信  这个IP不受gfw干扰

**Comment by Sayinore** [comment]
表示hosts没换，前两天有问题，现在好了……

**Comment by Ir1d** [comment]
Thx for sharing.XD

**Comment by sbw983** [comment]
@lrinQVQ 也就是说以后用gogotest扫到的IP都不能用了？这也太杯具了把

**Comment by lrinQVQ** [comment]
v6 gfw还没办法进行很完善的干扰2333 我的办法暂时不说XD 公开平台危险

**Comment by lrinQVQ** [comment]
fix now
