### ISSUE TITLE
Google地址过期以及新地址

### ISSUE THREAD

**Issue by jokin1999** [racaljk/hosts#1298]
2017-07-14中的google地址过期，最新可用：202.171.252.103

**Comment by XiaolinZHONG** [comment]
这个 可以用 上海电信

**Comment by lrinQVQ** [comment]
此IP为SNI 非官网IP

**Comment by wukent** [comment]
61.153.20.229，直通google海底光缆。

**Comment by lrinQVQ** [comment]
61.153.20.229 还是SNI啊
inetnum: 61.153.20.224 - 61.153.20.231
netname: I-WIFI
country: CN
descr: i-ningbo
descr:
admin-c: HR499-AP
tech-c: CN13-AP
mnt-irt: IRT-CHINANET-ZJ
status: ASSIGNED NON-PORTABLE
changed: zjnoc_ip_6@163.com 20150610
mnt-by: MAINT-CN-CHINANET-ZJ-NB
source: APNIC
非官网IP啊 2333

**Comment by wukent** [comment]
大部分google都是自己的sni，这个授权的，看证书。

**Comment by lrinQVQ** [comment]
有个/24段的IP都能拿到授权==

**Comment by wukent** [comment]
很奇怪，非官方的官方授权？

**Comment by wukent** [comment]
关键时刻总会冒出一个这样的ip，上次是泰国的。

**Comment by lrinQVQ** [comment]
不啊2333 是官方授权啊

**Comment by wukent** [comment]
不懂细节，但证书是有的。

**Comment by lrinQVQ** [comment]
昂反正我是不会根据证书来评定的暂时

**Comment by wukent** [comment]
开放体系，没那么敢骗人吧？总比其他的sni靠谱。

**Comment by lrinQVQ** [comment]
等下我给你个地址就知道了

**Comment by lrinQVQ** [comment]
https://isp.google.com/iwantggc
@wukent 如果你有一个/24的IP段你也可以申请的

**Comment by wukent** [comment]
好，要能找出猫腻，就可以防止受骗了。

**Comment by lrinQVQ** [comment]
2333这个差不多随便谁都能申请的说

**Comment by wukent** [comment]
我看了一下，是GGC服务代理的申请。
说明是开放的，显然也受 GGC Team的监督吧。

**Comment by lrinQVQ** [comment]
不受监督的xd

**Comment by wukent** [comment]
感觉，光明正大的东西对一般的老百姓的隐私要求应该可以保障的，特别要求除外。

**Comment by lrinQVQ** [comment]
是的咩2333

**Comment by wukent** [comment]
主要也就上google，且都是https传输，方便就好。

**Comment by lrinQVQ** [comment]
PS:SNI提供商能在服务器后台LOG查看你访问的内容

**Comment by wukent** [comment]
看来只有自己架设的好点，但youtube没有sni就无法用了。很无奈，安全重要，但能出去更重要，要靠网友自己把握了。

**Comment by lrinQVQ** [comment]
youtube的话不需要SNI也可以用了233

**Comment by lrinQVQ** [comment]
只要redirector.googlevideo.com存活就能正常获取N个播放地址

**Comment by wukent** [comment]
谢谢，好，我试试。还有安卓的googleplay的gvt1，有什么方法？

**Comment by lrinQVQ** [comment]
@wukent 在计划内 有办法的

**Comment by wukent** [comment]
好，期待。

**Comment by Makebignew** [comment]
@wukent @lrinQVQ 这个IP不是sni也不是ggc，这是有人做了一个 port forwarding,表现是当你使用IP时，Google侦测到的IP是这个服务器的IP，但与sni不同，它只是转发某个特定服务器的某个特定端口。
https://www.google.com/#sclient=psy-ab&hl=en&safe=off&site=&source=hp&q=what+is+my+ip&oq=what+is+my+ip&gs_l=hp.3..0l4.382.1419.0.1766.13.11.0.0.0.0.247.1565.3j6j2.11.0.les%3B..0.0...1c.1.4.psy-ab.Sx1O8IFWjRw&pbx=1&fp=1&biw=1440&bih=720&bav=on.2,or.r_gc.r_pw.r_qf.&cad=b
这样就可以看到Google检测到的IP位址

**Comment by lrinQVQ** [comment]
2333 soga原来是做了端口转发

**Comment by xuanjia** [comment]
这样的端口转发，是否安全？

**Comment by lrinQVQ** [comment]
基本上 0安全性 @xuanjia

**Comment by Makebignew** [comment]
@lrinQVQ   redirector.googlevideo.com
可以使用Google北京上海機房IP，如203.208.40.137
或者任意gvs，不需要用gws

**Comment by xiaolongyuan** [comment]
南京电信 不能用

**Comment by lrinQVQ** [comment]
@Makebignew 才回家一会去调整下XD 确实基本上通用 不过之前强迫症2333保持IP一致性

_Sent from my Xiaomi MI 5s for dandan using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
