### ISSUE TITLE
Youtube

### ISSUE THREAD

**Issue by Pesdestrian** [racaljk/hosts#1299]
Youtube无法观看视屏。

**Comment by lrinQVQ** [comment]
咩 现在项目的IP在美国处已经炸了 还在找ing

_Sent from my Xiaomi MI 5s for dandan using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by sbw983** [comment]
youtube只能代理或者vpn，用hosts得走v6，不过电信走v6很卡，，开网页没事，视频就不要想了，除非直接解析了下视频离线看，要在线还不如走代理

**Comment by lrinQVQ** [comment]
然而我已经添加了在线观看的支持

**Comment by sy618** [comment]
然而官方IP在线看十个视频里只有一个能正常看，跟抽奖一样～

**Comment by lrinQVQ** [comment]
233不会啊 至少在我支持的域名内是无压力的

_Sent from my Xiaomi MI 5s for dandan using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by lrinQVQ** [comment]
fix now
