### ISSUE TITLE
google失效

### ISSUE THREAD

**Issue by zhonghuajia** [racaljk/hosts#130]
google失效

**Comment by K-Guan** [comment]
刚刚测试了，飞快。

**Comment by 4679** [comment]
我这一样 全线阵亡

**Comment by 4679** [comment]
是我傻了 刷机之后没改hosts
但是google drive的api接口确实挂了

**Comment by lszxw1234** [comment]
刚刚试了一下，google.com失效了

**Comment by nikoohp** [comment]
很快

**Comment by 4679** [comment]
地区问题吗？

Sent using CloudMagic Email
[https://cloudmagic.com/k/d/mailapp?ct=pi&cv=7.4.8&pv=7.1.2&source=email_footer_2]
On 周六, 12月 19, 2015 at 13:54, racaljk/hosts
<reply@reply.github.com>
wrote:
很快

—
Reply to this email directly or view it on GitHub
[https://github.com/racaljk/hosts/issues/130#issuecomment-165951067] .[https://github.com/notifications/beacon/AB77RL_QT4wiGvBmt-BV9C4lIskuS9jQks5pROiYgaJpZM4G4ArU.gif]

**Comment by lszxw1234** [comment]
坐标上海. 尝试ping IP 失败

C:\Users\lszxw>ping 216.239.38.125 /t

正在 Ping 216.239.38.125 具有 32 字节的数据:
请求超时。
请求超时。
请求超时。
请求超时。

**Comment by K-Guan** [comment]
@lszxw1234 我们正在用的Google hosts的IP是`64.233.160.90`。
