### ISSUE TITLE
google还是无法访问，有几天了

### ISSUE THREAD

**Issue by pengchin** [racaljk/hosts#1300]
专门注册了用户名来感谢开发者。我一直在用您的hosts，谢谢您提供的便利。这几天打不开google。。。我在北京，用的是移动宽带。

**Comment by haroldduan** [comment]
+1

**Comment by ykfq** [comment]
太快了，更新了hosts 几分钟后就被封

**Comment by lrinQVQ** [comment]
2333感谢支持 因为目前的IP在美国抽风 我在计划更换

**Comment by haroldduan** [comment]
正如楼上所言，我的是今天刚刚 失效的，目测是更新没多久就被封了

**Comment by cjkzwe** [comment]
我这里谷歌反而*以前*的ip用在手机上没事，电脑和路由都不行

**Comment by lrinQVQ** [comment]
233恭喜你的手机数据网络没有被NAT

**Comment by zhangshuo-test** [comment]
google,google plus 进不去

**Comment by lrinQVQ** [comment]
修仙5天准备先睡觉了XD

**Comment by sbw983** [comment]
如果能用v6的话试一下v6优先把，v6好像可以用，我走v6能上google

**Comment by cedarice** [comment]
我这儿还能用，好像是昨天更新的版本，今天还没有更新新版本

**Comment by kobeking** [comment]
Twitter能上吗


_使用 [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github) 从我的 OnePlus ONEPLUS A3000 发送_

**Comment by Rayzworld** [comment]
中午刚换的 晚上就gg

**Comment by p0mp0k0** [comment]
持续不能用啊，北京电信，北京联通都不行

**Comment by laodcn** [comment]
已有一枚可用的，但是证书只有2个月

**Comment by lrinQVQ** [comment]
有一堆可用的XD但是全国稳定性感人

**Comment by liguge** [comment]
我这里更新了新版的又不能用了 之前还可以使用的~现在都不大敢更新了~

**Comment by hhhaiai** [comment]
v6更新和V4一样吗?

**Comment by lrinQVQ** [comment]
咩 现在的更新是针对于挺多被NAT了的用户233 能够直接获取公网IP的不用太担心的说2333

**Comment by hhhaiai** [comment]
弱弱问下,老D的和你更新的,方式一致么?

**Comment by chutsetien** [comment]
这几天就算了吧。。。太多敏感的事情堆叠在一起了。。。

**Comment by lrinQVQ** [comment]
xd laod也是这个项目的贡献者啊 @hhhaiai

**Comment by lrinQVQ** [comment]
也还好XD 不过确实敏感

**Comment by chutsetien** [comment]
唉……主要是近期那个整天放炮的傻逼……
没见过他这么能得瑟的。有能耐去投 WikiLeaks 啊（
弄得昨晚 YouTube 都遭受大量 DDoS 攻击，发课

**Comment by hhhaiai** [comment]
好的.  有时间建群吧.让更多人参与

**Comment by Hancoson** [comment]
最新的又被封了吗

**Comment by lrinQVQ** [comment]
@hhhaiai TG群已经建了看README

**Comment by lrinQVQ** [comment]
确实啊XD 每天都DDOS

**Comment by chutsetien** [comment]
我这里是山东联通，发现 172.217.*.* 下面还是有几个能用的。虽然不知道能维持多久。
（不过我早就上 SS 了现在近 10 万条的 hosts 主要是屏蔽广告……

**Comment by lrinQVQ** [comment]
172.217下还有274个233

**Comment by chutsetien** [comment]
楼上这么精准。。。我才刚刚开始扫（

**Comment by lrinQVQ** [comment]
北美用完了还有欧洲存活2000个
非洲还有300多个

**Comment by lrinQVQ** [comment]
2333嘛 谷歌的IP段我是全部GET了的

**Comment by chutsetien** [comment]
嗯……专业……

**Comment by lrinQVQ** [comment]
2333一般啦 今天晚上计划修复一波

**Comment by lrinQVQ** [comment]
fix now
