### ISSUE TITLE
twitter又挂了

### ISSUE THREAD

**Issue by percysanchez** [racaljk/hosts#1301]
如题

**Comment by lrinQVQ** [comment]
XD忙死了 一个一个处理

**Comment by LGA1150** [comment]
twitter不要指望了

**Comment by lrinQVQ** [comment]
咩不至于不要指望 不过这两天得确太特殊了

_Sent from my Xiaomi MI 5s for dandan using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by percysanchez** [comment]
谷歌全家桶（含YouTube）又崩了

**Comment by percysanchez** [comment]
go hosts 22点的版本YouTube不可用，play商店下不了应用

**Comment by percysanchez** [comment]
twitter继续尿崩，烂的更严重

**Comment by percysanchez** [comment]
twitter正常，Google尿崩，YouTube无法看视频

**Comment by percysanchez** [comment]
snapchat也不行了，messenger连接慢

**Comment by lrinQVQ** [comment]
XD 很麻烦

**Comment by DDoSolitary** [comment]
> go hosts 22点的版本YouTube不可用，play商店下不了应用
gohosts和这里什么关系啊。。

**Comment by percysanchez** [comment]
racaljk不是go hosts的hosts维护者吗？
这不是racaljk的github吗？

**Comment by Crystal-RainSlide** [comment]
racaljk 是 racaljk hosts 的维护者，不是闭源软件 go hosts 的 hosts 的维护者，也没有义务为 go hosts 维护 hosts，也没有义务处理“崩了烂了”而不是无法、难以连接这样的问题。

**Comment by lrinQVQ** [comment]
楼上+1 go hosts使用的源我们不清楚 也不知道它的IP怎么回事2333

_Sent from my Xiaomi MI 5s for dandan using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by percysanchez** [comment]
他们好像只用你们的源，每次你们好用他们就好用，你们不能用他们就不能用

**Comment by Crystal-RainSlide** [comment]
这样啊
那，可能又多了一个违反开源协议使用开源项目的国产软件。看看go host上有没有说明…
没有的话…建议你卸载并去用Android Hosts-L，这个应用做得不太完美，有点乱，但有讲清hosts来源
更推荐用可以自定义hosts源的 AdAway ，因为它会屏蔽应用内广告，已被谷歌从Play下架，官方现在在F Droid市场发布它。不想去找它官网的话，直接在 https://fdroid.org/packages/ 第一页就能找到它
…我怎么背得出这个
（…我猜AdAway官网就是https://adaway.org

**Comment by lrinQVQ** [comment]
https://github.com/racaljk/hosts/issues/1349
