### ISSUE TITLE
对部分域名的IP更新

### ISSUE THREAD

**Issue by Makebignew** [racaljk/hosts#1303]
现在
www.gstatic.com   ssl.gstatic.com  已经解析到谷歌中国服务器，且没有被DNS污染，可以直接访问。建议从host列表中删除，因为国内服务器速度更快更稳定

一个静态资源地址测试
https://ssl.gstatic.com/gb/images/a/3a1e625196.png

**Comment by lrinQVQ** [comment]
我看看欸2333

**Comment by lrinQVQ** [comment]
ok 确实

**Comment by Makebignew** [comment]
@lrinQVQ  补充一下，
connectivitycheck.gstatic.com
g0.gstatic.com
g1.gstatic.com
g2.gstatic.com
g3.gstatic.com
都用了大陆服务器

**Comment by sy618** [comment]
刚测试了一下，不止以上域名。
*.gstatic.com 所有都解析到国内服务器了。

**Comment by SerCom-KC** [comment]
懒得开新 issue 不过 www.recaptcha.net 似乎也可以移除了？
http://ping.chinaz.com/www.recaptcha.net 似乎还可以的说

**Comment by lrinQVQ** [comment]
咩～TG更了过后在发出来

**Comment by SerCom-KC** [comment]
哈，打算一起更吗w

**Comment by lrinQVQ** [comment]
是啊2333 因为某些原因
