### ISSUE TITLE
Gmail -IMAP/SMTP能否帮忙多找几个可用IP备用？

### ISSUE THREAD

**Issue by lyonye** [racaljk/hosts#1304]
您好。
我经常需要用邮件客户端接受GMAIL邮件。网页端可以正常打开，但是客户端IMAP估计IP不能用，经常不能登陆失败无法连接。
目前使用最新的HOSTS。其IMAP和SMTP的IP如下。
64.233.189.108	imap.gmail.com
64.233.189.108	smtp.gmail.com

谢谢！

**Comment by lrinQVQ** [comment]
可以啊咩 吃个饭我丢5个备用的出来

_Sent from my Xiaomi MI 5s for dandan using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by Makebignew** [comment]
@lyonye  108.177.97.109 TW
74.125.200.108 SG
速度延迟都很好

**Comment by p0mp0k0** [comment]
你们的gmail网页可用？我这边跟google相关的网页都打不开

**Comment by yutaowx** [comment]
现在有新的可用的吗？貌似上面的速度也很慢

**Comment by lyonye** [comment]
没有可用的，最近我也上不去。大佬们最近都没更新呢

**Comment by lrinQVQ** [comment]
https://github.com/racaljk/hosts/issues/1349
