### ISSUE TITLE
Whatsapp已沦陷

### ISSUE THREAD

**Issue by Gneplee** [racaljk/hosts#1305]
您好，感谢您开 Issue 来反馈信息，**为了节省您及维护者的时间**，在提交前，请确保您已经检查了以下内容!
- 如有关 "Google无法连接" / "GitHub访问慢" 等问题 请参阅[常见问题解答](https://github.com/racaljk/hosts/wiki/The-hosts-FAQ)
- 已经阅读了 [Wiki 页面](https://github.com/racaljk/hosts/wiki)
- 已经搜索过之前的相关 [Issues](https://github.com/racaljk/hosts/search?type=Issues)
- 如果是报告问题，请确认问题可以复现并且**没有重复报告同一个问题**；如果是向 hosts 提供新的信息，请确认所提供信息的来源以及相关许可协议；欢迎使用 **Pull Requests** 功能（可以通过[直接编辑文件](https://github.com/racaljk/hosts/edit/master/hosts)的方式来提交）

如果您有其他附言，例如问题只在某个页面发生，或者是一般性讨论、提出新功能，请一定注明

或者您也可以卖个萌

我们同时有一个 [Gitter Room](https://gitter.im/racaljk/hosts)，以及一个[在 Coding 上的镜像](https://coding.net/u/scaffrey/p/hosts)

**Comment by Gneplee** [comment]
请求支援

**Comment by lrinQVQ** [comment]
欸

_Sent from my Xiaomi MI 5s for dandan using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by Makebignew** [comment]
@lrinQVQ  简单说一下 whatsapp 传送文本信息的域名有这些，不同平台有些不同   e1.whatsapp.net 
往下依次到 e20.whatsapp.net  但是注意whatsapp监听的是这些域名的 5222 端口，GFW对某些IP port 5222做了干扰，需要手工找正常IP

**Comment by lrinQVQ** [comment]
https://github.com/racaljk/hosts/issues/1349
