### ISSUE TITLE
刚刚更新，google依然上不去

### ISSUE THREAD

**Issue by hjs0512** [racaljk/hosts#1306]
如题

**Comment by hjs0512** [comment]
楼上用最新的hosts可用？不会只有我不行吧。。。

**Comment by tingbob** [comment]
浙江电信上不去。。。

**Comment by frank-lu** [comment]
用以前的吧，https://laod.cn/hosts/2017-google-hosts.html

**Comment by lrinQVQ** [comment]
commit历史里面有

_Sent from my Xiaomi MI 5s for dandan using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by naivor** [comment]
google 不行

**Comment by KalelCooper** [comment]
@Makebignew 这个sni不能用啊

**Comment by wilon** [comment]
`108.177.97.200  www.google.com`

北京联通测试可用，不知道能用几天...

**Comment by lrinQVQ** [comment]
fix now
