### ISSUE TITLE
删

### ISSUE THREAD

**Issue by Sharkkkk** [racaljk/hosts#1307]

**Comment by frank-lu** [comment]
新IP貌似有问题，下载以前的能用：https://laod.cn/hosts/2017-google-hosts.html
这个是7月13日的，亲测好用

**Comment by frank-lu** [comment]
最新文件中的173.194.223.202这个IP无法访问

**Comment by lrinQVQ** [comment]
开始慢慢加入Google Play了

**Comment by lrinQVQ** [comment]
https://github.com/racaljk/hosts/issues/1349
