### ISSUE TITLE
请求移除我的 collaborator 身份

### ISSUE THREAD

**Issue by Ir1d** [racaljk/hosts#1309]
@racaljk tl;dr 烦请……

---

话说起来，成为项目的维护者已经521天了。
这些天里大部分的时间是在咸鱼，后期已经没有给 Irin 和项目的整体有什么贡献了。
挂着这个名头，却帮不上啥忙，很是惭愧。
再加上由于个人原因，接下来的时间更无法投入更多的精力在这上边，还是请 Racaljk 帮忙撤了吧……

最后说一些私货，
很是担心项目里大家的努力被一些人利用，
包括但不限于卖 ss ，甩锅，泼脏水。举个栗子就是[酱紫](https://github.com/racaljk/hosts/issues/1301#issuecomment-316232514)。
希望接下来的日子有心的同学能在这方面做些功课解决这类问题。

**我还是希望更多朋友用 hosts 来学习，不要做多余的事情 

[希望您能在遇到互联网上的各种言论和见解时，不要不加思考地、情绪一度被煽动而不能克制地、盲目地相信这些片面或者歪曲事实的东西，而是要事实求是地思考，要摆脱情绪绑架的怪诞思维去理解。](https://github.com/racaljk/hosts/wiki/%E5%85%B3%E4%BA%8E%E4%B8%AD%E5%9B%BD%E7%9A%84%E4%BA%92%E8%81%94%E7%BD%91)

[当然啦，大部分用户才不会管这些，他们不会分析你是不是真的安全，也不会做道德判断，只要他们觉得好用就行。所以可以看到，这种环境下开源其实并没有什么优势，只不过为一些人抄袭提供了便利。这种环境下最后留下来的都是这些人。](https://github.com/shadowsocks/shadowsocks-windows/issues/293#issuecomment-132253168)**

---

最后，
2016.2.13 - 2017.7.19， // ref: #214
谢谢一路的你们。
就不一一@了. XD

**Comment by lrinQVQ** [comment]
XD QwQ

**Comment by sy618** [comment]
十分同意你的观点！

**Comment by sure-one** [comment]
收费能不能解决部分问题？

**Comment by Ir1d** [comment]
@sure-one 有点门槛虽然好，但是收费不是我们所追求的

**Comment by chenjia1949** [comment]
之前通过同事的推荐，一直使用楼主的hosts，最近几天看到的情况，作为一个小白
表示十分感谢为该项目作出贡献的同学，注册一个号来表示感谢！

**Comment by Rodney2012** [comment]
你们能不能不要太张扬，hosts 用的越多，被封掉速度越快

**Comment by Ir1d** [comment]
@Rodney2012 哪里太张扬，您的观点是自己用上了别人就不应该用上？

**Comment by racaljk** [comment]
done

感谢你的贡献

**Comment by racaljk** [comment]
最近风声的确紧..虽然不确定信息是否可靠,尽量低调些.. 😺 
![qq 20170720124004](https://user-images.githubusercontent.com/5010047/28400882-a0fb2568-6d48-11e7-8004-3d0ab983c1a2.jpg)

**Comment by lrinQVQ** [comment]
关于ss昂 我自己朋友深圳 有在公司用有在家里用的 用了两年了 并没有受到任何影响
但是大多数人应该都是用的pip 安装的ss-python 版本为2.8.2 因为pip源没有更新 所以出问题的可能性是有的

_Sent from my Xiaomi MI 5s for dandan using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by beckhamwjc** [comment]
之前一直用host自动更新服务，很方便，离开google搜索都不不知道怎么办好了。感恩！

**Comment by sheepbao** [comment]
用hosts仅用来学习，项目很赞

**Comment by PW-Chen** [comment]
感覺  有微微的洋蔥

**Comment by Too-Naive** [comment]
新闻是fake

**Comment by Too-Naive** [comment]
leave就好了。。完全没必要开issue

**Comment by Ir1d** [comment]
Whatever
