### ISSUE TITLE
新的计划

### ISSUE THREAD

**Issue by lrinQVQ** [racaljk/hosts#1310]
到底出什么事情了 大家也应该看到了的https://github.com/racaljk/hosts/issues/1309 这个issues
明天开始政治因素也应该没这么大了
明天更新不变2333
非常感谢那些在issues里面留下IP的人 虽然大多是SNI或者端口转发之类的 为了安全考虑我不会放进项目里面,但是很感谢你们的分享 希望能够和大家一起维护这个项目咩~加油吧

这些计划不变,但是可能会推出一些有趣的小博客之类的233 到时候再说吧
- [ ] Google 1e100(以防万一) 域名
- [ ] Google Video全部支持
- [x] Google Play
- [ ] Twitter
- [x] 更换hosts里的域名为不返回证书的IP (稍后详细解释)
- [ ] 替换丢包严重的IP

**Comment by xueyatou** [comment]
期待着更新。我也只放心官方的IP。

**Comment by SerCom-KC** [comment]
GV全部666
不过到底是直接拉未污染的DNS结果还是你另外有秘方？我记得GV是一个域名对应一个IP的？
如果是前者的话我这边测试某些IP还是不可用）

**Comment by lrinQVQ** [comment]
2333是这样的 Youtube的IP还有很多是没有放出公开解析

**Comment by lystrosaurus** [comment]
感谢分享~
没google，搜索真心不方便

**Comment by phodal** [comment]
我有个想法，这个 hosts 应该是敌我双方都是知道的。所以，更新变快可能不能解决问题。

**Comment by SerCom-KC** [comment]
@lrinQVQ 也就是说还有很多隐藏服务器的意思吗www 不过redirector没法返回这些域名的话也是头疼）

**Comment by beckhamwjc** [comment]
感恩！也想贡献一份力量

**Comment by starsight** [comment]
貌似已经好了?

**Comment by ARROWBOW** [comment]
上午好了，又不能用了

**Comment by ARROWBOW** [comment]
hub会挂不会

**Comment by lrinQVQ** [comment]
一般github不会挂

**Comment by digicolor** [comment]
好像又不行了。。但是奇怪ip能ping通就是上不去google

**Comment by lrinQVQ** [comment]
有用https://www.google.com/ncr

**Comment by DDoSolitary** [comment]
能上，就是有点不稳定。。

**Comment by TurnOffNOD** [comment]
#1309 这个issue怎么了？

**Comment by digicolor** [comment]
https://www.google.com/ncr不行，杭州电信和杭州移动都不行，

**Comment by lrinQVQ** [comment]
咦杭州居然不行

_Sent from my Xiaomi MI 5s for dandan using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by lrinQVQ** [comment]
最后说一些私货，
很是担心项目里大家的努力被一些人利用，
包括但不限于卖 ss ，甩锅，泼脏水。举个栗子就是 酱紫 。
这部分

_Sent from my Xiaomi MI 5s for dandan using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by sy618** [comment]
这个项目辛辛苦苦维护数据还没有一个软件的名声大与经济收益。

本来说hosts应该是低调使用才能长久。但有些人从一开始就带着盈利目的，甚至要商业化，所以很积极的推广软件。

此人从来就没为开源社区贡献过任何数据。这样就逼得别人只能闭源了。
这其中的黑历史，不说也罢。只希望这种人越来越少！

**Comment by Iwbtone** [comment]
上海电信adsl，上海移动4g， 试了下最新的依然不行

**Comment by KalelCooper** [comment]
北京网通还是不行

**Comment by lrinQVQ** [comment]
突然觉得可以让你们见识下以前的见光死了2333

**Comment by liguge** [comment]
@lrinQVQ  youtube和推特还是不行~

**Comment by ananas-xxj** [comment]
北京网通不行  都好几天了，从#1262这就开始不能用了

**Comment by lrinQVQ** [comment]
- [ ] 修复Google apis等
XD对开发者友好一些

TG群有惊喜哦

**Comment by lrinQVQ** [comment]
https://github.com/racaljk/hosts/issues/1349
