### ISSUE TITLE
这形势越来越不对了啊

### ISSUE THREAD

**Issue by u3u** [racaljk/hosts#1311]
> ShadowsocksR news:
警告：已确认深圳市大面积启动精准 SS 协议识别技术
所识别的宽带用户均停用宽带强行接受批评教育，并要求写下保证书

听说某个人的 VPS 的 IP 被单独黑名单了 推特上也有人宽带被停机被请去喝茶了
现在比较担心 GayHub 和这个项目被禁了 没有了 GayHub 以后还怎么搞基=。=

**Comment by Ir1d** [comment]
未确认消息

**Comment by lrinQVQ** [comment]
未确认消息

**Comment by DDoSolitary** [comment]
vps被单独黑名单不是很正常吗。。
