### ISSUE TITLE
关于新建hosts organization的打算

### ISSUE THREAD

**Issue by racaljk** [racaljk/hosts#1312]
很早前就此打算，加之现在hosts-related的东西越来越多了，GUI、脚本、博客(dev)等，放到一个项目里面有点冗杂，再加之众多collaborators、contributors无私的奉献着，越来越感觉这不是一个人的项目。
两方面考虑，希望大家能明确寻找自己需要的相关内容，而不是README导航。更重要的是，我希望这个项目能以organization的形式存在，让他不属于任何个人。这是开源贡献者们共同的努力，理应归于众人:)

希望听听大家的意见

**Comment by lrinQVQ** [comment]
赞同organization

**Comment by DennisWong** [comment]
不错 发自网易邮箱大师 在2017年07月20日 20:17，Cthulhu 写道： 很早前就此打算，加之现在hosts-related的东西越来越多了，GUI、脚本、博客(dev)等，放到一个项目里面有点冗杂，再加之众多collaborators、contributors无私的奉献着，越来越感觉这不是一个人的项目。 两方面考虑，希望大家能明确寻找自己需要的相关内容，而不是README导航。更重要的是，我希望这个项目能以organization的形式存在，让他不属于任何个人。这是开源贡献者们共同的努力，理应归于众人:) 希望听听大家的意见 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by DDoSolitary** [comment]
+1

**Comment by Too-Naive** [comment]
@googlehosts

**Comment by EMLVIRUS** [comment]
我之前转过组织 https://github.com/AmazingApps

办法大概有两个：
* 创建新组织，所有项目全部 transfer
* 将 owner 账号转为 组织账号

无论如何，必须由 owner 账号操作

**Comment by Too-Naive** [comment]
组织transfer吧。。反正也就只有这个组织了 要么和 @hoststools 合并一下
组织的owner是我

**Comment by DaleXiao** [comment]
我也觉得邀请制/成员制比较好

**Comment by kinglijin1** [comment]
提高一些门槛，对于存活有好处

**Comment by themorethe** [comment]
口意

**Comment by andytimes** [comment]
hosts 文件可以不必移动，不然后遗症比较多。其他的可以考虑放 organization

**Comment by lrinQVQ** [comment]
分开commit太麻烦了吧…

_Sent from my Xiaomi MI 5s for dandan using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by andytimes** [comment]
@lrinQVQ 你可能没理解我的意思，和 hosts 文件相关的部分可以不要迁移。其他的放 organization。

hosts 文件的更新，要不要分开 commit，完全看拆分合不合理了。

**Comment by DDoSolitary** [comment]
@andytimes 应该不会有后遗症的吧，GitHub会自动配置跳转的（HTTP 301）

**Comment by TurnOffNOD** [comment]
@Too-Naive 还是别“合并”了，要么作为两个紧密相关的独立组织，要么“吞并”了对方。
毕竟hosts是核心，别的工具什么的都是福利而已。

**Comment by Too-Naive** [comment]
@TurnOffNOD 那就单独放着 也无妨

**Comment by digicolor** [comment]
但是不是说gfw封锁了google的证书吗，那再怎么host是不是都没用了

**Comment by lrinQVQ** [comment]
XD不至于拿不出方案的

**Comment by digicolor** [comment]
那很好 同意！

**Comment by lrinQVQ** [comment]
来TG有惊喜

**Comment by OuYancey** [comment]
注意了各位，**organization** 是犯冲的东西。还是不要玩火了吧？

**Comment by EMLVIRUS** [comment]
@OuYancey 什么叫犯冲。。。求解释

**Comment by OuYancey** [comment]
@EMLVIRUS 犯了太上老爷的忌讳啦。。。自己玩玩无所谓，顶多见一个IP封一个IP。
但是，**聚众**、**organization**、**组织**，这些词在我大中华范围内是不是只在**某些关键地方**见过？
手动滑稽。

**Comment by OuYancey** [comment]
可能是我太小心了，但是还是好心提醒一下。毕竟你们已经1W5 star了。。。:mask::mask::mask:

**Comment by EMLVIRUS** [comment]
@OuYancey 黑人问号.jpg 要是这样 ss/SSR怎么来的 而且原在美国的服务器你查个甚

**Comment by EMLVIRUS** [comment]
![](http://i.imgur.com/pafX5Cf.png)
居然删评论。。。

**Comment by OuYancey** [comment]
@EMLVIRUS 
:mask: 哈哈，不好意思，多嘴了

**Comment by OuYancey** [comment]
留着也没事喔，只是觉得自己碍事了。所以删了。:mask::mask::mask:

**Comment by OuYancey** [comment]
@EMLVIRUS 
对了，其实 ss org里面并没有**public** member，如果你们真要做，可以参考一下

**Comment by sorenchiron** [comment]
这个...树大了不会招风吗？

**Comment by DDoSolitary** [comment]
其实只是便于管理了而已，并没有真正以上的“组织“。。
