### ISSUE TITLE
最新版google上不去ip 216.58.220.192

### ISSUE THREAD

**Issue by vincentchen** [racaljk/hosts#1314]
如题

**Comment by lrinQVQ** [comment]
见光死的威力

_Sent from my Xiaomi MI 5s for dandan using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by xueyatou** [comment]
+1.上海长宽

**Comment by wangyw15** [comment]
同样上不去，上海电信

**Comment by hillwoodroc** [comment]
在线工具测试，全国阵亡。自己找的 IP 倒是没事。应该是被盯上了。

**Comment by ding33211** [comment]
封的特别快

**Comment by DaleXiao** [comment]
感觉有卧底

**Comment by lrinQVQ** [comment]
webhook既可 不需要派人

**Comment by gino2010** [comment]
webhook 需要后台配置吧？ 定时扫描即可，虽然消耗点资源。

**Comment by lychichem** [comment]
放个robot.txt之类的禁止爬虫？

**Comment by DDoSolitary** [comment]
@lychichem 
首先，github没法放robots.txt。
而且，robots.txt是基于爬虫自觉的并不是强制性措施。

**Comment by jojolfy** [comment]
同样ping不通，应该是被监控了

**Comment by zhangkuantian** [comment]
+1 上海电信

**Comment by zhangkuantian** [comment]
替换成 216.58.221.174 后可以了

**Comment by guoyf** [comment]
楼上IP北京电信不好用

**Comment by Wenchao21** [comment]
讲道理，应该是被盯上了吧？更新再快，也不行啊。

**Comment by ancin** [comment]
216.58.220.192版本的上不去啊。

**Comment by szhielelp** [comment]
同问

**Comment by haoxingxing** [comment]
我有老版的，那时的还可以用
有人需要吗？

**Comment by lrinQVQ** [comment]
git reste --hard commit id即可啊- -

**Comment by DDoSolitary** [comment]
@lrinQVQ 大概没几个人为了用这个装git吧。。

**Comment by lrinQVQ** [comment]
23333确实

**Comment by iVitan** [comment]
封太快了

**Comment by Sayinore** [comment]
还有能用的

**Comment by noname007** [comment]
以前的ip 是有可以用的，慢慢翻翻，替换下最新的可用。

**Comment by Leridy** [comment]
216.58.200.33   这个ip 还可用

**Comment by SamsungGoogle3** [comment]
怎么更新SSR软件

_使用 [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github) 从我的 LeEco Le X820 发送_

**Comment by SamsungGoogle3** [comment]
怎么更新ssr软件

**Comment by lrinQVQ** [comment]
楼上 ssr不是删库了嘛0.0

**Comment by SamsungGoogle3** [comment]
不明白。是官方停止更新吗？shadowsocksR android 3.3.5版本太低了。想更 。大神拜托了

**Comment by noname007** [comment]
最近圈内太乱了。全是因为衍生的问题吵吵吵。。。。


-----
http://blog.soul11201.com

2017-07-28 13:50 GMT+08:00 lrin <notifications@github.com>:

**Comment by SamsungGoogle3** [comment]
@lrinQVQ   不明白了。

**Comment by noname007** [comment]
@SamsungGoogle3 破娃酱被人肉威胁了。然后删repo 了。

**Comment by lrinQVQ** [comment]
昂不做评价 只能说太还是太年轻了 至于下载链接 我去看下

**Comment by SamsungGoogle3** [comment]
@noname007  不好意思 因为 我不会 不懂

**Comment by SamsungGoogle3** [comment]
@lrinQVQ 谢谢 希望官方的软件

**Comment by lrinQVQ** [comment]
@SamsungGoogle3 https://github.com/shadowsocksr-backup/shadowsocksr-android/releases/download/3.4.0.6.6/shadowsocksr-release.3.4.0.6.6.apk 根据备份这个版本应该是最新的?不太清楚2333

**Comment by SamsungGoogle3** [comment]
你们是怎么翻墙的。vpn  SSR 还是hosts

**Comment by Leridy** [comment]
@SamsungGoogle3  DNS 翻

**Comment by SamsungGoogle3** [comment]
DNS不是不安全吗？大神请问如何制作hosts文件

**Comment by Leridy** [comment]
@SamsungGoogle3 DNS 是自己服务器搭建的，应该还是可信的吧

**Comment by lrinQVQ** [comment]
https://github.com/racaljk/hosts/issues/1349
