### ISSUE TITLE
提供一个新有效思路

### ISSUE THREAD

**Issue by Makebignew** [racaljk/hosts#1315]
首先需要chrome QUIC协议 在chrome://flags 找到Experimental QUIC protocol 选择启用
GFW对于某些gws采用了不黑洞，只封锁TCP端口的策略，与目前封锁gvs的策略相同。
比如 172.217.25.14 这个IP Port 443 80都不通，但可以ping，我们使用这个IP在配合quic协议，就可以愉快的使用Google了，而且由于443端口已被封锁，gfw也无法进行有效的阻断。
局限就是必须使用chrome。

**Comment by Makebignew** [comment]
https://en.m.wikipedia.org/wiki/QUIC
关于QUIC协议的介绍

**Comment by lrinQVQ** [comment]
这个协议我早已发现 但是不适合于大众用户

_Sent from my Xiaomi MI 5s for dandan using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by lrinQVQ** [comment]
目前发现在最新Chromium源码中有Google SSL标记 研究ing

_Sent from my Xiaomi MI 5s for dandan using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by lrinQVQ** [comment]
sudo hping3 --udp -p 443 172.217.25.14
HPING 172.217.25.14 (enp3s0 172.217.25.14): udp mode set, 28 headers + 0 data bytes
^C
--- 172.217.25.14 hping statistic ---
5 packets transmitted, 0 packets received, 100% packet loss
round-trip min/avg/max = 0.0/0.0/0.0 ms

PING 172.217.25.14 (172.217.25.14) 56(84) bytes of data.
64 bytes from 172.217.25.14: icmp_seq=1 ttl=51 time=91.3 ms
64 bytes from 172.217.25.14: icmp_seq=2 ttl=51 time=92.0 ms
^C
--- 172.217.25.14 ping statistics ---
3 packets transmitted, 2 received, 33% packet loss, time 2002ms
rtt min/avg/max/mdev = 91.375/91.690/92.005/0.315 ms

UDP 443

**Comment by lrinQVQ** [comment]
sudo hping3 -S --udp -p 443 172.217.25.14
HPING 172.217.25.14 (enp3s0 172.217.25.14): udp mode set, 28 headers + 0 data bytes
444: ^C
--- 172.217.25.14 hping statistic ---
8 packets transmitted, 0 packets received, 100% packet loss
round-trip min/avg/max = 0.0/0.0/0.0 ms

**Comment by lrinQVQ** [comment]
ping 172.217.25.14
PING 172.217.25.14 (172.217.25.14) 56(84) bytes of data.
64 bytes from 172.217.25.14: icmp_seq=2 ttl=51 time=92.3 ms
64 bytes from 172.217.25.14: icmp_seq=3 ttl=51 time=93.0 ms
64 bytes from 172.217.25.14: icmp_seq=5 ttl=51 time=90.9 ms
^C
--- 172.217.25.14 ping statistics ---
5 packets transmitted, 3 received, 40% packet loss, time 4027ms
rtt min/avg/max/mdev = 90.971/92.131/93.059/0.868 ms
ping是通的

**Comment by Makebignew** [comment]
@lrinQVQ  172.217.24.14 我这里是通的  另外172.217.26.14 172.217.27.14没试过

**Comment by lrinQVQ** [comment]
2333那你运气不错的 移动方面早已大面积清杀UDP

**Comment by lrinQVQ** [comment]
sudo hping3 -S --udp -p 443 172.217.24.14
HPING 172.217.24.14 (enp3s0 172.217.24.14): udp mode set, 28 headers + 0 data bytes
^C
--- 172.217.24.14 hping statistic ---
4 packets transmitted, 0 packets received, 100% packet loss
同咩

**Comment by Too-Naive** [comment]
实践证明…quic协议在某些特定情况下可能导致网页根本打不开

**Comment by Too-Naive** [comment]
呃 修正一下 是load很久 切换到页面之后才能载出来
测试环境: 台湾 Hinet
