### ISSUE TITLE
Akamai Sureroute解封德国之声

### ISSUE THREAD

**Issue by Makebignew** [racaljk/hosts#1316]
我们可以利用 Akamai Sureroute Ip来解封一些被 http reset的新闻网站
这里只举一例德国之声移动版
183.61.147.31 m.dw.com
223.119.220.122 commons.dw.com
这样原本被Reset 的网站通过hosts也能访问了。
其中 183.61.147.31 就是一组 akamai sureroute IP，通过这组IP可以解决所有使用akamai加速，被http Reset的网站，如法广，苹果日报等。因为服务器在境内，所以可以规避封锁
关于Sureroute https://developer.akamai.com/learn/Optimization/SureRoute.html

**Comment by lrinQVQ** [comment]
get 2333

**Comment by Makebignew** [comment]
@lrinQVQ  是的，都是akamai搭建的服务器，为了减少延迟所以在中国搭服务器。。

**Comment by lrinQVQ** [comment]
soga 2333

**Comment by Makebignew** [comment]
@lrinQVQ cn.rfi.fr m.cn.rfi.fr 法广中文
www.chinatimes.com 中国时报
另外还有些资源域名需要注意，要不然页面加载不全。判断的话，解析一下cname都是 *.*.akamai.net 就是用了akamai的CDN

**Comment by zyf2008Neptune** [comment]
最近对akamai的CDN的攻击导致steam商店都不能正常登

**Comment by LGA1150** [comment]
发现能用来打开Tumblr子域名
另外发现一北京移动IP： 221.179.212.31

**Comment by lrinQVQ** [comment]
https://github.com/racaljk/hosts/issues/1349
