### ISSUE TITLE
关于不能上YOUTUBE的想法

### ISSUE THREAD

**Issue by vida-shamp** [racaljk/hosts#1319]
我花了钱买SS的账号，就是为了能翻墙，这个软件已经废了那么长时间竟然没人出来解释，我想知道为什么。我花了钱！

**Comment by lrinQVQ** [comment]
？？？？？？？？？

_Sent from my Xiaomi MI 5s for dandan using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by BROBIRD** [comment]
？？？？？？？？

**Comment by DDoSolitary** [comment]
<del>我现在很闲啊。。要不你给我发email，我们来聊聊人生吧。。</del>

**Comment by lrinQVQ** [comment]
23333厉害了

**Comment by vida-shamp** [comment]
我去，他们给的技术支持网站就是这里。现在又转到其他的网站去了，真不知道是不是买了假的SS。
https://github.com/shadowsocks/shadowsocks-windows/
花钱买了一年，现在刚刚好一个月。

![default](https://user-images.githubusercontent.com/30122157/28498364-31ed9722-6fce-11e7-92a6-bce3f88606ed.png)

**Comment by BROBIRD** [comment]
……你这一看就是被骗了啊

**Comment by lrinQVQ** [comment]
可怜...被骗了

**Comment by DDoSolitary** [comment]
想我这样没钱的好处就是不会被骗。。

**Comment by Too-Naive** [comment]
![](https://cloud.githubusercontent.com/assets/16496671/20557321/f47b3c50-b1a5-11e6-8810-8edc50a65778.png)
