### ISSUE TITLE
封的特别快阿

### ISSUE THREAD

**Issue by iVitan** [racaljk/hosts#1320]
封的也太快了

**Comment by sugov5** [comment]
同感

**Comment by nxtreaming** [comment]
不是封的快，而是之前懒得封而已，IP一出来，如果想封锁，还不是秒级的速度。

这个项目目前俨然成了一个免费获取需要封锁的IP的快速通道了。

-----------------------------------------
Productive. Reliable. Fast.

**Comment by DaleXiao** [comment]
Make the repo private, can only be accessed by authorized people.

**Comment by hhhaiai** [comment]
个人感觉也是 授权制吧.

**Comment by hhhaiai** [comment]
稍微提高点门槛.  可以提高门槛,可以征收更多贡献者

**Comment by hillwoodroc** [comment]
GFW 现在由换新方法了，指定封锁 Google 的 SSL 证书。这个项目应该可以停止了。

**Comment by ylxiong** [comment]
日，我就说今天怎么上不了了，浏览器一直提示https证书认证的问题。

**Comment by hillwoodroc** [comment]
不是你说的问题。如果某个 ip 能从 client 段 ping 通 server，那么当 client 开始通过 443 端口访问 server 时，连接立即完全中断，大概在5分钟后又可以 ping 通。

**Comment by ptpt52** [comment]
GFW 现在又换新方法了，指定封锁 Google 的 SSL 证书。这个项目应该可以停止了。

**Comment by HakureiMarisa** [comment]
oh no! 我还准备敲碗催更呢

**Comment by lrinQVQ** [comment]
XD不至于拿不出方案的

**Comment by powerLambda** [comment]
咋整啊  同志们    拨VPN好烦的说  好怀念修改host文件的日子.
楼上的意思是今后不能靠修改host文件翻墙了?

**Comment by fwk1010** [comment]
没得玩了。。我才刚刚使用hosts

**Comment by effzmt** [comment]
这以后可怎么办呀？项目组可有新的阵地吗？

**Comment by lrinQVQ** [comment]
@effzmt TG

**Comment by hillwoodroc** [comment]
用 VPN 的话记得用 obfs 混淆一下流量，不然狠容易挂。

**Comment by cedarice** [comment]
哦买嘎嘎

**Comment by lrinQVQ** [comment]
XD 来TG有惊喜

**Comment by HakureiMarisa** [comment]
@lrinQVQ TG也是被墙的么?都打不开官网下载。。

**Comment by whinamp** [comment]
@IrinQvQ telegram哪里啊？username？channel？还是group？

**Comment by lrinQVQ** [comment]
readme 里面有2333

**Comment by lrinQVQ** [comment]
TG的话昂IP被封了的说

**Comment by jesusRUi** [comment]
话说，是不是aws配置的免费vpn也被封了啊

**Comment by beckhamwjc** [comment]
我从北京连到我们学校的VPN也被干扰了，不懂为什么国内对国内的vpn也要被搞

**Comment by EMLVIRUS** [comment]
@beckhamwjc 无法区别

**Comment by nxtreaming** [comment]
> 我从北京连到我们学校的VPN也被干扰了，不懂为什么国内对国内的vpn也要被搞

因为并不是仅仅在国际出口上部署了检测系统，在某些核心城市的网络出口也部署了同样的检测系统。

**Comment by percysanchez** [comment]
咱们应该喷一波工信部了
这个死方滨兴，没他就没有GFW

**Comment by fuerpeng** [comment]
要不要到工信局搞一次游行示威 ！！ ！

**Comment by DDoSolitary** [comment]
@fuerpeng 分分钟把你抓起来。。

**Comment by nxtreaming** [comment]
你难道不知道游行是需要先要得到朝廷允许才可以的吗？

-----------------------------------------
Productive. Reliable. Fast.

**Comment by lrinQVQ** [comment]
https://github.com/racaljk/hosts/issues/1349
