### ISSUE TITLE
使用ip+https的hosts不能翻墙了

### ISSUE THREAD

**Issue by NzKSO** [racaljk/hosts#1322]
您好，感谢您开 Issue 来反馈信息，**为了节省您及维护者的时间**，在提交前，请确保您已经检查了以下内容!
- 如有关 "Google无法连接" / "GitHub访问慢" 等问题 请参阅[常见问题解答](https://github.com/racaljk/hosts/wiki/The-hosts-FAQ)
- 已经阅读了 [Wiki 页面](https://github.com/racaljk/hosts/wiki)
- 已经搜索过之前的相关 [Issues](https://github.com/racaljk/hosts/search?type=Issues)
- 如果是报告问题，请确认问题可以复现并且**没有重复报告同一个问题**；如果是向 hosts 提供新的信息，请确认所提供信息的来源以及相关许可协议；欢迎使用 **Pull Requests** 功能（可以通过[直接编辑文件](https://github.com/racaljk/hosts/edit/master/hosts)的方式来提交）

如果您有其他附言，例如问题只在某个页面发生，或者是一般性讨论、提出新功能，请一定注明

或者您也可以卖个萌

我们同时有一个 [Gitter Room](https://gitter.im/racaljk/hosts)，以及一个[在 Coding 上的镜像](https://coding.net/u/scaffrey/p/hosts)

**Comment by lrinQVQ** [comment]
嘛～你可以来TG群玩玩

**Comment by p0mp0k0** [comment]
TG连不上，连注册都完成不了

**Comment by bkfrd** [comment]
老哥，用词要注意啊，这么骂政府Github迟早要完。

**Comment by digicolor** [comment]
把这条删掉吧，已经风声紧了，还打敏感词

**Comment by noname007** [comment]
不要怕，该说的还是要说的。大不了关闭了。

**Comment by Deercyan** [comment]
我觉得github不可能完，不然就真的闭关suo国了，国内好多东西就是无脑大众化，还tm的有理

**Comment by HakureiMarisa** [comment]
删了吧，没事找事么这不是

**Comment by frank-lu** [comment]
不行了，肯定是被盯上了，赶紧换个发布渠道吧，网盘了啥的，给个加密的压缩包也行，不能直接给内容了

**Comment by chutsetien** [comment]
我第一次听说「共产鬼子」这个词，哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈，让我笑一会儿。

**Comment by chutsetien** [comment]
@Deercyan GitHub 被封也是迟早的事，而且之前又不是没封过。这有什么好奇怪的。

**Comment by laodcn** [comment]
@lrinQVQ TG群连接发来

**Comment by lrinQVQ** [comment]
@laodcn https://t.me/googlehosts

**Comment by wilon** [comment]
`172.217.27.149   www.google.com`
北京联通测试可以，不知道能坚持几天。

**Comment by wolfan** [comment]
@lrinQVQ Tg都没路去了，好伤心。。。。

**Comment by lrinQVQ** [comment]
欸 心疼你qwq 弄下tg好了

**Comment by wolfan** [comment]
@IrinQVQ 重点是要能接到验证码喵(^･ｪ･^)

**Comment by craftsmann** [comment]
丧心病狂啊 - -，ho@sts都不能用了...

**Comment by lifeidle** [comment]
@irinqvq tg收不到验证码哎。。。

**Comment by lrinQVQ** [comment]
https://github.com/racaljk/hosts/issues/1349
