### ISSUE TITLE
已经用不了

### ISSUE THREAD

**Issue by ddok520** [racaljk/hosts#1325]
这么快就挂了？

**Comment by lrinQVQ** [comment]
tg? 咩如果不是tg用不了进TG有惊喜233

**Comment by effzmt** [comment]
@lrinQVQ 那么问题来了，TG群号到底是什么，在整个项目下都找不到啊？

**Comment by oneone1995** [comment]
@effzmt readme第二行那么大的TG群放在那.....
[Telegram群](https://t.me/googlehosts)
```http
https://t.me/googlehosts
```

**Comment by VictorChiong** [comment]
怎么进TG群？
网页显示“无法理解该地址，可能需要安装其他软件才能打开该地址”。

**Comment by oneone1995** [comment]
@VictorChiong 是的，你可能需要安装其他软件

**Comment by littlebeandog** [comment]
tg也挂了呀...

**Comment by ddok520** [comment]
换了一个才能用，这hosts封的也太TM快了吧

**Comment by VictorChiong** [comment]
@oneone1995 具体是安装什么软件呢？
这个需要私聊么？

**Comment by oneone1995** [comment]
@VictorChiong 你安装了Telegram之后，浏览器应该是能识别这种链接并提示你用Telegram打开的。所以你有安装Telegram嘛？

**Comment by VictorChiong** [comment]
@oneone1995 了解了，之前并没有安装Telegram, 期待TG群里的惊喜。THX

**Comment by oneone1995** [comment]
@VictorChiong 
大概只有女装惊喜。

**Comment by ft3727754** [comment]
问下这个邮件怎么取消订阅？

________________________________
Sent from YoMail<http://www.yomail.com/?utm_source=signature>

发件人： oneone1995<mailto:notifications@github.com>
发送时间： 2017-08-02 15:13:52
收件人：  racaljk/hosts<mailto:hosts@noreply.github.com>
抄送：  Subscribed<mailto:subscribed@noreply.github.com>
主题： Re: [racaljk/hosts] 已经用不了 (#1325)

@VictorChiong<https://github.com/victorchiong>
大概只有女装惊喜。

**Comment by oneone1995** [comment]
@ft3727754 
右上角Not Watching

**Comment by ft3727754** [comment]
他老把你们的对话发到邮箱里，有没有其他办法只取消邮箱订阅

**Comment by oneone1995** [comment]
@ft3727754
在你个人设置中可以设置Notifications的选项，[https://github.com/settings/notifications](https://github.com/settings/notifications)

**Comment by ft3727754** [comment]
[cid:_emc.1_3205e21e6aa6758914354d1ccf979218]
刷新后依旧如此

[cid:_emc.1_8f6c50999f3370165940f85651818fc0]
________________________________
Sent from YoMail<http://www.yomail.com/?utm_source=signature>

发件人： oneone1995<mailto:notifications@github.com>
发送时间： 2017-08-02 15:29:15
收件人：  racaljk/hosts<mailto:hosts@noreply.github.com>
抄送：  ft3727754<mailto:ft3727754@hotmail.com>; Mention<mailto:mention@noreply.github.com>
主题： Re: [racaljk/hosts] 已经用不了 (#1325)

@ft3727754<https://github.com/ft3727754>
在你个人设置中可以设置Notifications的选项，https://github.com/settings/notifications

**Comment by ft3727754** [comment]
搞定了谢谢

**Comment by ft3727754** [comment]
@oneone1995
谢谢

**Comment by lrinQVQ** [comment]
https://github.com/racaljk/hosts/issues/1349
