### ISSUE TITLE
Google gg了？

### ISSUE THREAD

**Issue by 123ysys** [racaljk/hosts#1327]
这是怎么回事？我加了最新的hosts, FB都能上，google用不了了？

**Comment by 123ysys** [comment]
大佬们打算怎么解决？

**Comment by ARROWBOW** [comment]
这个链接好像被报毒了，似乎很多人举报

**Comment by lrinQVQ** [comment]
知道咩什么叫见光死嘛

**Comment by lrinQVQ** [comment]
差不多就是北方靠近北京的可用性极低
整个南方电信/联通/移动问题都不大

**Comment by ARROWBOW** [comment]
什么原理

**Comment by 123ysys** [comment]
而我恰恰是南方的。

**Comment by lrinQVQ** [comment]
2333那就心疼了咩 我用现在所有提供全国ping的网站 测了20多个IP 昂 基本上 北方偏向北京全体阵亡 南方好好的

**Comment by 123ysys** [comment]
也不知是什么命。

**Comment by lrinQVQ** [comment]
@123ysys 或许你可以试试209.85.144.31

**Comment by 123ysys** [comment]
好的

**Comment by lrinQVQ** [comment]
除了那南方城市能用偏向北京的基本bomm

**Comment by 123ysys** [comment]
@ARROWBOW  举报的都什么心态啊？

**Comment by 123ysys** [comment]
似乎没用。

**Comment by lrinQVQ** [comment]
心疼max 2333

**Comment by 123ysys** [comment]
求用win xp的该怎么保存？

**Comment by EricInBj** [comment]
216.58.195.236

**Comment by cyp0633** [comment]
山东联通表示Google相册挂了……关键时刻掉链子

**Comment by 123ysys** [comment]
北方似乎都很不好。

**Comment by lxsazl** [comment]
我的突然又可以用了

**Comment by EricInBj** [comment]
216.58.206.215
216.58.206.221
 216.58.206.250
 216.58.206.223
216.58.206.254
216.58.206.249
216.58.206.222


来来来，不能用的试试这几个呢。

**Comment by xuchao1213** [comment]
能ping通，但网页死活打不开

**Comment by lrinQVQ** [comment]
不如来TG 女装啊～ (TG惊喜日常)
