### ISSUE TITLE
有一个不情之请：请各位dalao不要把github当聊天工具，实在是产生太多没有的邮件了

### ISSUE THREAD

**Issue by seniorcandy** [racaljk/hosts#1328]
我知道大家都很关心这个project，都想为其贡献自己的力量，本人虽然没有做出什么贡献，但也一直默默关注着。
自认为伸手党没资格说这张话，也不是针对某个人，但我想应该也有不少朋友有这样的感觉，那就是github会把所有关注的项目的动态都实时发邮件通知，如果同时关注了几个活项目，每天都会收到不少这种邮件，这的确会让人产生不少麻烦和困扰，尤其是一些没有实际贡献意义，甚至是讨论意义的内容。说实话，我关注过的项目从来没有想这个项目这么活跃的。我也知道这种“活跃”是好事，大家都想为fanqiang这件事多出一份力。
所以，各位发在issues发言时，请意识到一点，你发的这条消息，是会产生**1790**封邮件发给每一个关注的人的。如果在一个公司中，要发一封有这么多收件人的邮件，那么它的重要性一定是不小的。
所以还请各位发言前，稍微考虑一下下。

各位大佬在上，小弟如有得罪，请多包涵

**Comment by lrinQVQ** [comment]
欸多XD 还是推荐你不要订阅邮箱提示昂233 因为现在大多数闲聊已经转到TG了咩 而且XD 经常也要说下最近的情况公开出来分析 项目的自身情况之类的233 虽然我希望issues是用来解决技术问题的 但是同时我也希望大家能够一起说出各自发现的问题一起解决2333 所以可能讨论起来邮件就真的很多了XD

**Comment by peterzane** [comment]
哈哈我刚刚取消订阅，又少一个

**Comment by lrinQVQ** [comment]
觉得邮件太烦取消好啦2333 反正邮件每天都是几千封XD 习惯了

**Comment by DDoSolitary** [comment]
Watching关闭邮件提示，只留Participating就好。。
