### ISSUE TITLE
移除 www.recaptcha.net？

### ISSUE THREAD

**Issue by SerCom-KC** [racaljk/hosts#1330]
~~算了还是开个 issue 吧~~
理由同 #1303 
http://ping.chinaz.com/www.recaptcha.net 祖国江山一片~~绿~~啊
现在 hosts 里的那个我这边反而上不了 Orz

**Comment by yuan252525** [comment]
我的也是这样打不开!

**Comment by lrinQVQ** [comment]
果然全部切换谷祥了2333

**Comment by SerCom-KC** [comment]
@lrinQVQ 是啊，这下国内使用 reCAPTCHA 不存在问题了，换个地址的事w
谷翔好样的（x

**Comment by lrinQVQ** [comment]
+1 23333 等稳定了一波push

**Comment by SerCom-KC** [comment]
@lrinQVQ 话说谷翔没给上传系的域名（比如
 Google Drive 的 clients*.google.com）开后门吗）

**Comment by lrinQVQ** [comment]
//你觉得可能没开咩

**Comment by SerCom-KC** [comment]
反正我直接套已知 IP 还是 404 😂

**Comment by SerCom-KC** [comment]
无聊，还是写在这个 issue 下吧
www.google-analytics.com
fonts.gstatic.com
redirector.gvt1.com
的解析也转到谷翔了
