### ISSUE TITLE
不知道 有没有用...

### ISSUE THREAD

**Issue by ziyua** [racaljk/hosts#1331]
173.194.25.109  r8---sn-o097znes.googlevideo.com
4.53.202.140    r1---sn-a8au-nh4e.googlevideo.com
4.53.202.143    r4---sn-a8au-nh4e.googlevideo.com
4.53.202.142    r3---sn-a8au-nh4e.googlevideo.com
74.125.170.149  r16---sn-n4v7knel.googlevideo.com
74.125.170.235  r5---sn-n4v7sn76.googlevideo.com
4.53.202.147    r8---sn-a8au-nh4e.googlevideo.com
173.194.25.199  r2---sn-o097zned.googlevideo.com
4.53.202.145    r6---sn-a8au-nh4e.googlevideo.com
74.125.170.72   r2---sn-a5mekned.googlevideo.com
74.125.157.72   r3---sn-n4v7kn7z.googlevideo.com
173.194.25.138  r5---sn-o097znez.googlevideo.com
4.53.202.141    r2---sn-a8au-nh4e.googlevideo.com
74.125.157.112  r11---sn-n4v7kn7d.googlevideo.com

**Comment by SerCom-KC** [comment]
直接把域名发到 #1256 不就好了hhh
@lrinQVQ 会处理的）

**Comment by lrinQVQ** [comment]
https://github.com/racaljk/hosts/issues/1349
