### ISSUE TITLE
goo.,9le间歇性抽风，上午能用，中午挂了，下午我满地找替代ip，结果自己好了，这是什么情况。

### ISSUE THREAD

**Issue by mycompanycomputer** [racaljk/hosts#1334]
您好，感谢您开 Issue 来反馈信息，**为了节省您及维护者的时间**，在提交前，请确保您已经检查了以下内容!
- 如有关 "Google无法连接" / "GitHub访问慢" 等问题 请参阅[常见问题解答](https://github.com/racaljk/hosts/wiki/The-hosts-FAQ)
- 已经阅读了 [Wiki 页面](https://github.com/racaljk/hosts/wiki)
- 已经搜索过之前的相关 [Issues](https://github.com/racaljk/hosts/search?type=Issues)
- 如果是报告问题，请确认问题可以复现并且**没有重复报告同一个问题**；如果是向 hosts 提供新的信息，请确认所提供信息的来源以及相关许可协议；欢迎使用 **Pull Requests** 功能（可以通过[直接编辑文件](https://github.com/racaljk/hosts/edit/master/hosts)的方式来提交）

如果您有其他附言，例如问题只在某个页面发生，或者是一般性讨论、提出新功能，请一定注明

或者您也可以卖个萌

我们同时有一个 [Gitter Room](https://gitter.im/racaljk/hosts)，以及一个[在 Coding 上的镜像](https://coding.net/u/scaffrey/p/hosts)

**Comment by simplerxing** [comment]
我的谷歌所有的网站沦陷

**Comment by cjkzwe** [comment]
#me too...

**Comment by wolfan** [comment]
我这刚刚也能用了Google了~

扶南联通

**Comment by Leridy** [comment]
我的晚上不能用白天能用，9mail  一直在抽风，客户端也不能更新邮件了

**Comment by mycompanycomputer** [comment]
@lrinQVQ  tele 。gram？我也连接不上

**Comment by wolfan** [comment]
@mycompanycomputer 想上tg还是乘乘用ss吧。

如果要用tg webapp 要不开ss上telegram.im 要不自己搭个反代。

**Comment by zhangkuantian** [comment]
上海电信换成 218---254---1---15 之后就可以了，防止被屏蔽，点换成---了

**Comment by min-shui** [comment]
61——91——161——217应该也能用

**Comment by min-shui** [comment]
作者没更新维护了

**Comment by lrinQVQ** [comment]
TG群咩

**Comment by nanshihui** [comment]
@求TG群明细

**Comment by lrinQVQ** [comment]
https://t.me/googlehosts

**Comment by simplerxing** [comment]
这个hosts是不是不更新了，有没有能用的hosts了

**Comment by lrinQVQ** [comment]
https://github.com/racaljk/hosts/issues/1349
