### ISSUE TITLE
Chrome应用店

### ISSUE THREAD

**Issue by wolfan** [racaljk/hosts#1337]
Chrome应用店还需要大佬的恢复啊。

**Comment by lrinQVQ** [comment]
//23333 你要是在TG群就知道了

**Comment by wolfan** [comment]
@lrinQVQ 嘤嘤嘤，问题是人家没有SS上不了TG啊。。。中科大的服务又451了显然是不打算恢复的样。。。。。。

**Comment by lrinQVQ** [comment]
好吧QwQ 等我过两天开个issues你就明白了 心疼你qwq

**Comment by wolfan** [comment]
@lrinQVQ 那个下次更新能不能把naver的那个加上去~

**Comment by lrinQVQ** [comment]
https://github.com/racaljk/hosts/issues/1349
