### ISSUE TITLE
172.217.6.127 无法连接

### ISSUE THREAD

**Issue by WeiLDavid** [racaljk/hosts#1339]
Google, Android绑定的172.217.6.127已封 请更新IP地址

================================
四川电信网络,执行 "ping 172.217.6.127" 结果:

正在 Ping 172.217.6.127 具有 32 字节的数据:
请求超时。
请求超时。
请求超时。
请求超时。

172.217.6.127 的 Ping 统计信息:
    数据包: 已发送 = 4，已接收 = 0，丢失 = 4 (100% 丢失)，

第二次执行 "ping -n 10 172.217.6.17" 结果

正在 Ping 172.217.6.127 具有 32 字节的数据:
请求超时。
请求超时。
请求超时。
请求超时。
请求超时。
请求超时。
请求超时。
请求超时。
请求超时。
请求超时。

172.217.6.127 的 Ping 统计信息:
    数据包: 已发送 = 10，已接收 = 0，丢失 = 10 (100% 丢失)，

**Comment by lzh984294471** [comment]
同样遇到

**Comment by NathanLi** [comment]
一样

**Comment by ze00** [comment]
+1

**Comment by lyg50358** [comment]
+1

**Comment by xpc0938** [comment]
成都+1

**Comment by xpc0938** [comment]
臣附议

**Comment by wyh2004** [comment]
172.217.6.127不能访问，用以前的216.58.200.33可以

**Comment by lrinQVQ** [comment]
https://github.com/racaljk/hosts/issues/1349
