### ISSUE TITLE
This issus was marked as junk.

### ISSUE THREAD

**Issue by Thisisnotgoingpublished** [racaljk/hosts#1340]
`This message was removed as junk.`

**Comment by lrinQVQ** [comment]
Hosts高于dns 高于VPN 请自行了解基础知识
IP全为官方IP IP WHOIS可查

**Comment by oneone1995** [comment]
兄弟你是有被迫害妄想症嘛。

**Comment by EMLVIRUS** [comment]
mdzz。。。。

**Comment by DDoSolitary** [comment]
@Thisisnotgoingpublished 那你用的VPN会不会是公安提供的？

**Comment by SerCom-KC** [comment]
公安部根本就不用搞这么麻烦，直接通知网络服务提供商提供你的上网记录，然后和这里的 hosts 记录一对比不就完了。真是……

**Comment by lrinQVQ** [comment]
对了2333这可能是微软的阴谋 因为hosts本身不是我们写的2333 我们只是提供配置

**Comment by Too-Naive** [comment]
![](https://cloud.githubusercontent.com/assets/16496671/20557321/f47b3c50-b1a5-11e6-8810-8edc50a65778.png)我没有笑

**Comment by Thisisnotgoingpublished** [comment]
I just nervous, cuz I found out that Linux Ubuntu Chinese mirror source contains no vpn vpnc openvpn.

**Comment by DDoSolitary** [comment]
@Thisisnotgoingpublished The does have a openvpn package... See http://cn.archive.ubuntu.com/ubuntu/pool/main/o/openvpn/
And from http://cn.archive.ubuntu.com/ubuntu/dists/zesty/main/binary-amd64/Packages.gz
```
Package: openvpn
Priority: optional
Section: net
Installed-Size: 1148
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Original-Maintainer: Alberto Gonzalez Iniesta <agi@inittab.org>
Architecture: amd64
Version: 2.4.0-4ubuntu1
Depends: debconf (>= 0.5) | debconf-2.0, libc6 (>= 2.15), liblz4-1 (>= 0.0~r113), liblzo2-2, libpam0g (>= 0.99.7.1), libpkcs11-helper1 (>= 1.11), libssl1.0.0 (>= 1.0.2~beta3), libsystemd0, init-system-helpers (>= 1.18~), iproute2, lsb-base (>= 3.0-6)
Suggests: openssl, resolvconf, easy-rsa
Filename: pool/main/o/openvpn/openvpn_2.4.0-4ubuntu1_amd64.deb
Size: 488054
MD5sum: 4f32c0d30e9d43e0500e880cc2c52fae
SHA1: befee6d80e3e0bb8aa917be6d0f16d6a24e40d7d
SHA256: 7f304977c2c3467b4c83817f197ff72f761b8f038dc5ccc04b78e9cd34c16cd5
Description: virtual private network daemon
Homepage: http://www.openvpn.net/
Description-md5: 2ebe91e411d46309a61861db507e5c2f
Bugs: https://bugs.launchpad.net/ubuntu/+filebug
Origin: Ubuntu
Supported: 9m
Task: ubuntu-desktop, ubuntu-usb, edubuntu-desktop, edubuntu-usb, ubuntu-touch-core, ubuntu-touch, ubuntu-mate-core, ubuntu-mate-desktop
```

**Comment by Thisisnotgoingpublished** [comment]
@DDoSolitary But I really was unable to get it via apt-get indeed... I am not lying. I really saw no Vpnc no Openvpn in the Linux distribution nor its default Chinese mirror site. So, maybe I just suffering from a very bad luck at that time?

**Comment by SerCom-KC** [comment]
@Thisisnotgoingpublished
If you're using HTTP (I think this is your case here), blame your ISP for that. Consider using HTTPS to do  _anything_ today, if possible.

**Comment by Thisisnotgoingpublished** [comment]
@DDoSolitary And also, if you don't mind, would you please remove the message about GongAn above. It is kinda make me nervous. I know that it is okay if I just take all these as nothing. But I believe that believing something or being careful is better than believing in nothing and being careless. There is a Chinese saying says that "You can not let down your guard". We're here not quirt so anonymous-like. Praise the Party, praise it as it could stop our lives.

**Comment by Thisisnotgoingpublished** [comment]
@SerCom-KC Actually I was doubt the provider of these IPs in the files. No free pie comes from the sky above, this is an another saying by old men.

**Comment by SerCom-KC** [comment]
@Thisisnotgoingpublished 
If this is your opinion, then I can disprove you with Linux - You ARE using Ubuntu anyway, aren't you?
Linux is **free and open-source**, almost every server in production use it. There might be some security problems, but they'll be fixed immediately after being noticed.
hosts **in this project** is also **free**, and while **open-source** is not applicable here, like @lrinQVQ said, you can verify its authority by performing a IP WHOIS query. That's something equivalent to open-source.
So, if you trust Ubuntu/Linux, why doubt this project? Just check the "code" if you think this "software" is not safe.

Also, a side note: this project at racaljk/hosts has abandoned. We have moved to googlehosts/hosts

**Comment by Thisisnotgoingpublished** [comment]
@SerCom-KC I just made a brainstorm, supposing if this project in under control of a group of government genius and elite --  a trap. But as far as i read, maybe the corruption and inaction would make this highly-unlikely.

**Comment by lrinQVQ** [comment]
@Thisisnotgoingpublished Is you mean Google in under control of a group of government genius and elite ?

**Comment by Thisisnotgoingpublished** [comment]
Ok, you are right, I just delete my reply again

**Comment by SerCom-KC** [comment]
@Thisisnotgoingpublished 

> supposing if this project in under control of a group of government genius and elite

If you really insist this opinion, then remember: it's also YOUR RESPONSIBILITY to do all the review stuff.
You have doubts? Sure, either ask politely or just don't use it at all. Obviously your way of asking hurts all the maintainers.
IMO, **this project is as safe as Linux, because it can be openly reviewed.**

**Comment by Thisisnotgoingpublished** [comment]
@lrinQVQ  I mean that this could be under @$%@#$^. I never say anything about google.

**Comment by Thisisnotgoingpublished** [comment]
@SerCom-KC  how to delete this issue?

**Comment by lrinQVQ** [comment]
@Thisisnotgoingpublished ... But all google dominos ip of this project all come from google

**Comment by SerCom-KC** [comment]
@Thisisnotgoingpublished Just delete anything you can delete, and edit anything you can edit
Then ask @racaljk to either delete this issue or lock the conversation.

**Comment by lrinQVQ** [comment]
@SerCom-KC 233 Ok

**Comment by Too-Naive** [comment]
我每次都想说一句话，不信任就不要用，彼此节约时间
