### ISSUE TITLE
hosts 不更新了吗？已经10天没有更新了

### ISSUE THREAD

**Issue by wlos** [racaljk/hosts#1345]
非常感谢作者的贡献。但是最近的hosts 已经无法打开Google，请问一般多久更新一次？

**Comment by KeithChou** [comment]
我最近也打不开了:(

**Comment by lrinQVQ** [comment]
咩TG群会更新

**Comment by potatohai** [comment]
如何入群？

**Comment by lrinQVQ** [comment]
https://t.me/googlehosts

**Comment by p0mp0k0** [comment]
TG都打不开，没法下载更新啊

**Comment by wolfan** [comment]
@lrinQVQ 话说，tg群更这是说BB不要在用的意思了喵？

**Comment by shenthought** [comment]
_(:з)∠)_

**Comment by lrinQVQ** [comment]
//233其实我和ddos他们准备换组织去更新啦XD https://github.com/googlehosts/hosts

**Comment by wolfan** [comment]
围观吃瓜子

**Comment by KeithChou** [comment]
这个hosts不会再更新了吗@IrinQVQ

**Comment by wolfan** [comment]
@KeithChou 感觉是项目组内部发生了什么不可描述的事，来吃个瓜子我们围观~

**Comment by guoyf** [comment]
到底神马情况啊，围观好几天了，总是让进tg，但是tg用不了啊

**Comment by lrinQVQ** [comment]
咩XD2333也不是不可描述啦

**Comment by star887012** [comment]
tg是什么东西？

**Comment by tupunco** [comment]
发现 8-5 的可以用了.

**Comment by xinyi1091** [comment]
大概是6月份的ip还可以访问google，现在又用不了了

**Comment by simplerxing** [comment]
tg是什么？

**Comment by wolfan** [comment]
@simplerxing Telegram 和扣扣一样的通信工具

**Comment by powerLambda** [comment]
此项目已死 有事烧纸

**Comment by lrinQVQ** [comment]
move to https://github.com/googlehosts/hosts

**Comment by lrinQVQ** [comment]
https://github.com/racaljk/hosts/issues/1349
