### ISSUE TITLE
新的 hosts 可以打开 gmail 网页版，但是邮件客户端连不上

### ISSUE THREAD

**Issue by noirchen** [racaljk/hosts#1347]
看了一下，并没有任何 gmail smtp 服务器的 ip，而在过去的 hosts 中是有的，不过那些已经失效了。

**Comment by noirchen** [comment]
是用的 https://github.com/googlehosts/hosts

**Comment by lrinQVQ** [comment]
= =还没有写完XD

**Comment by tutukill** [comment]
我是从8月1好就再也上不了，怎么更新都不好使
