### ISSUE TITLE
hosts导致在公司局域网无法访问任何网页

### ISSUE THREAD

**Issue by hzgoin** [racaljk/hosts#1348]
这个问题只是在公司网络复现，自己宽带并没有出现这个问题。
在公司，使用了这套host配置之后，是可以正常访问网页的，但是一般一天之后，电脑就会无法访问网页，公司邮箱服务器也链接不上，但是qq是可以正常使用。
之前遇到这种情况，就是重启电脑来解决，后来发现是这个hosts导致的，因为把hosts中追加那些内容删去之后，一会就可以访问了。
搞不清楚为什么，怀疑是host的配置影响了电脑访问公司网络的认证系统，难道是ipv6那个配置影响的？还在摸索中

**Comment by DDoSolitary** [comment]
你这么说我怎么知道是什么问题啊。。
hosts中没有任何会有这类影响的内容。。

**Comment by lrinQVQ** [comment]
+1 XD 我们不可能得知你们公司网络认证系统的域名吧啧 IPV6就不清楚了欸0.0

**Comment by uchen1225** [comment]
我想问一下以下三个有什么不同。
add address=127.0.0.1 name=localhost
localhost＝127.0.0.1
127.0.0.1 localhost
我看有人说手机要用第二种格式，所以来问问https://github.com/lennylxx/ipv6-hosts/issues/135

**Comment by DDoSolitary** [comment]
@uchen1225 用什么格式取决于你用什么软件配置hosts，与用什么设备无关
另外，不同的问题请另开issue询问，不要在无关issue下问，这样有助于后来者搜索。
