### ISSUE TITLE
强烈建议添加dnsmasq文件

### ISSUE THREAD

**Issue by yech1990** [racaljk/hosts#135]
我是通过修改dnsmasq进行科学上网的, hosts文件每次得自己手动改成dns格式, 请问能否考虑增加dnsmasq.conf文件

**Comment by K-Guan** [comment]
那个……这玩意什么格式？

**Comment by yech1990** [comment]
像这样 三行搞定google

```json
address=/.google.com/216.239.38.125
address=/.google.cn/216.239.38.125
address=/.google.com.hk/216.239.38.125

```

**Comment by K-Guan** [comment]
哦，那为什么不直接用hosts就好？这玩意表示真没玩过，不知道其他的Collaborator对这个是否了解。

**Comment by andytimes** [comment]
@yech1990
我个人认为，大部分人还是在用 Windows，你对这个 conf 感兴趣，你可以去写 wiki。如果项目加上这个配置文件，以后肯定还会有人推荐诸如 py 的跨平台脚本，这样 hosts 更新就很繁琐了，还会冒出很多奇怪的 issue

我只是提供建议，你还是得去问 @racaljk ，让他去定夺。

**Comment by lautis0503** [comment]
hosts通用，dnsmasq也能读取hosts，不必另外添加。

**Comment by gitaiQAQ** [comment]
dnsmasq 使用比较麻烦，对普通用户不友好

在部分Android上还会出现奇怪的问题，而相对应的hosts在兼容性上已经碾压

不过 dnsmasq 对Google的SN域名系统实用性极好

至于单独使用。。。
每次就改3个IP而已，你完全可以自己维护一个dnsmasq的源

**Comment by guqikay** [comment]
dnsmasq一样能用hosts文件，不需要另外conf

**Comment by 0x01f7** [comment]
* dnsmasq 支持 hosts 文件，相關選項是 addn-hosts
* 如果需要統一放置在 cond-dir，可能需要此種格式，轉換命令如下：
    
    ```Bash
    dos2unix < hosts | awk '$1 ~ /^[0-9]/ { printf("address=/%s/%s\n", $2, $1) }' > hosts.dnsmasq
    ````

**Comment by yech1990** [comment]
@0x01f7
虽然基本能实现，可是没有兼并啊

**Comment by yech1990** [comment]
@0x01f7感觉得加上split $2

**Comment by racaljk** [comment]
可以考虑新建branch或者直接建立一个dnsmasq文件，关键是日后的维护问题

**Comment by guqikay** [comment]
@yech1990   openwrt上面dnsmasq可以直接读HOSTS文件的啊，你是什么环境
