### ISSUE TITLE
【解决方案】关于 iOS 的 hosts 文件限制

### ISSUE THREAD

**Issue by ElfSundae** [racaljk/hosts#1350]
hosts 文件越来越大，在 iOS 上直接应用本项目的 hosts 文件会导致整个网络连接失败，适当删减条目（减小文件体积）后就可以正常使用了。

经本人反复测试发现，iOS 上的限制不是 hosts 文件尺寸，而是 hosts 文件的行数。我用脚本将相同 IP 的条目合并成一行，即便文件超过 1M 也可以正常使用。

**Comment by iikira** [comment]
为什么我的ios7就没有限制

**Comment by DDoSolitary** [comment]
@iikira 似乎是8还是9才开始限制的

**Comment by DDoSolitary** [comment]
@ElfSundae 项目中有大量内容是关于googlevideo.com的，那些内容不同域名都是指向不同ip的，所以就算合并以后，hosts行数还是很大。。

**Comment by ElfSundae** [comment]
@DDoSolitary 这个项目下的 hosts 是 5217 行，合并后是 1225 行，减少了 76.5% 行。我觉得行数大不大无所谓，只要可用就行。

**Comment by DDoSolitary** [comment]
@ElfSundae 所以说1000+就可用了咯，我还以为不行的说。。
我增加了合并后的文件：https://github.com/googlehosts/hosts/blob/master/hosts-files/hosts-compact，不过有2000+行，你试试行不行。。

**Comment by ElfSundae** [comment]
@DDoSolitary 刚试了下，原 hosts 和 hosts-compact 都可用。目测 4400 行内就可用。

**Comment by DDoSolitary** [comment]
有趣。。既然解决了，那我就close了。。
