### ISSUE TITLE
ipv6 的 localhost 导致 v4 的 localhost 不可访问

### ISSUE THREAD

**Issue by iahu** [racaljk/hosts#1351]
你好，这个项目非常好，我一直在使用。但是最近更新后老是会导致我的localhost不能访问的情况。
原因是更新的hosts里有下面几行ip v6的localhost覆盖了v4的localhost
```
::1	localhost
::1	ip6-localhost
::1	ip6-loopback
```
能否可以兼容到两个版本？

**Comment by lrinQVQ** [comment]
XD不会影响啊 https://github.com/googlehosts/hosts/blob/master/hosts-files/hosts#L11 hosts里两个都有欸
顺便PS我们转移到新repo了
