### ISSUE TITLE
developers.google.com显示链接错误

### ISSUE THREAD

**Issue by turnerguo** [racaljk/hosts#136]
64.233.162.83	developers.google.com

这个IP是 `hosts.huhamhire.com` 提供的，目前是可用的（偶尔会掉线），可以参考一下。

    # 216.239.38.125	cloudssh.developers.google.com
    64.233.162.83	console.developers.google.com
    # 64.233.160.90		console.developers.google.com
    # 216.239.38.125	source.developers.google.com

**Comment by K-Guan** [comment]
测试了，确实403。那么其他的：

     503 216.239.38.125  cloudssh.developers.google.com
     504 64.233.160.90   console.developers.google.com
     505 216.239.38.125  source.developers.google.com 

没问题吗？

**Comment by nieruibo** [comment]
216.239.38.125  developers.google.com 
403

**Comment by aofall** [comment]
>64.233.160.90 cloudssh.developers.google.com
64.233.160.90 console.developers.google.com
64.233.162.82 source.developers.google.com

以上全凭以前的经验，没有经过验证。如果64.233.160.90不行的话换成64.233.162.82

**Comment by nieruibo** [comment]
@aofall  都不能访问developers.google.com

**Comment by turnerguo** [comment]
@K-Guan  只有 64.233.160.90 console.developers.google.com 可以访问，还有些cloud、events之类的也有问题（403或者跳转到google.com）还好不常用，但developers挺重要的，很多资料都在这里面。

**Comment by andytimes** [comment]
@nieruibo @turnerguo hosts 规则更新后，要刷新 DNS 缓存才能生效。
关于 216 这个 IP 的问题，还有极少部分的 Google 服务没有支持。虽然 ping 不稳定还有瑕疵，但是速度挺快的而且不支持 Appspot。所以一直用它。

你们要是有人求稳定，可以自己扫 *.google.com 这个泛域名 IP，这种 IP 有一大堆，一般都是会支持你们要访问的那个网址。

对于把资料放在 Google 上的情况，最好自己搭一个 SS。网上有教程，云主机也不贵。你们要实在是自己弄不好，就问问 @aofall  ，如果他乐意且有空闲时间，你可以付点费给他，让他帮你搭一个。

最后说一个无关这个 issue  的话，看到这个项目有 1800+ 的 star 了，我还是希望更多朋友用 hosts 来学习，不要做多余的事情。
老共在国外也真心不好过。我每个周末用 Google 搜索新闻，基本上都能在第一页看到 BBC 对中国的歧视。
虽然 G||||FW 做法比较恶心，还是配合一点，先学好知识，才能改变我们的环境。
