### ISSUE TITLE
习近平是卖国贼

### ISSUE THREAD

**Issue by leighana** [racaljk/hosts#1360]
習近平是獨裁竊國賊

中共十八大之後，習近平在王岐山的得力協助下，大力反貪。
他們真是反貪嗎？
有人概括得好，那叫：「以貪反貪，以黑反貪，以警反貪」，都是為了實現習近平「攫取中國最高絕對權力和財富」的目的。
不然，習近平用不著用「以貪反貪，以黑反貪，以警反貪」下三濫手段，消除異己，獨霸全權，任人唯親，專橫跋扈。
不然，習近平用不著極力掩蓋2016年「巴拿馬文件」揭示出的習近平家族藏匿在海外的巨額資產的事實。
不然，習近平用不著極力迴避2017年揭露出來的劉呈傑可能是他私生子的身份和劉呈傑在海內外坐擁萬億財富的真相。
甚至，不惜在海外動用死亡去威脅知情人、爆料人。
甚至，像我這樣的74歲退休者在海外的Email、Facebook每發有關習近平的敏感話題時，都有人用特種手段控制、或者屏蔽、封鎖。

善良的人們千萬不要以為毛澤東反過貪殺過官，習近平打過虎也拍過蒼蠅，他們自己就兩袖清風、一塵不染。
恰恰相反！
歷史事實表明，一般中共官員貪的是權和利。然而，毛澤東、習近平貪的、竊的是作為「公器」的國！
共產黨毛澤東把中國變成共產黨的私產，習近平的共產黨則是把中國變成了習近平的私產。
中國現在一切（包括外企）都要姓黨，中國共產黨又姓習；那中國不姓習，姓什麼！
他X的！更有甚者，他一度竟然誘導全國人民稱他為「大大，即爸爸」。流毒至今！
亙古未聞啊！！！過去的皇帝老兒也不敢啊！！！千古霸帝也！！！
竟然許多人不以為然，甘毒如飴，至今如此！你說這是不是個王八蛋的兲朝？！

毛澤東、習近平才是中國的巨貪竊國賊！

其實這些來自習近平父親的「真傳」：一是「隱忍等待」；二是「共產黨並不可信，習家除了讓習近平等待出頭，其他人能夠出國就出國避險、同時藏匿錢財——陝北老財式的算計」。

其實這些來自習近平母親的「家教」，更只是一條：「做了共產黨，就不要有人性；沒有了人性，在共產黨里，才能做大、做穩」。大雨中13歲的「逃犯」習近平飢腸轆轆，也得不到母親一聲憐愛和一口吃食，反而遣送回少管所。在常人看來這還算是母親嗎？還算是人嗎？

從此，習近平得到了做共產黨員和居帝位的真傳。所以現在身居帝位的習近平諳父母深意、報父母深情。

同時，想想也令人扼腕，毛賊東文革的年代，少年的傷痛、絕望是怎樣地鍛造出了一個獨裁者冷酷的心：記得我第二次（1998-2012）入獄，在看電視時看到——彭麗媛素面朝天在廈門、或是福州家中接受採訪，習近平破門而入，機敏的記者拿著麥克風、鏡頭對準他突然發問：習（省長？）當您看到彭麗媛在舞台上光彩奪目地出現時，您有什麼感受？習近平撇著他那特有的嘴型、操著一口京片子，不屑、粗橫地脫口而出：瞧她那份（兒）熊德行！當時，彭麗媛只有苦笑以對。
一下子，讓我看透了習近平的心！
少年的苦難，不一定會讓每一位親歷者都變得善良、曠達；往往令人狠毒、偏狹和多疑。後者的可怕、恐怖，令人毛骨悚然！

可是，特會裝的習近平這些年口口不離「初心」，忽悠了許許多多人幼稚的心。
可是，究其實質，習近平的「初心」就是堅持所謂共產主義、社會主義的邪惡，就是烏托邦、就是騙子主義的共產主義和社會主義。
所以，黨，是我習共的；你們，也是我習共的；全世界，也歸我習共！
習近平的「初心」就是——「有了最高權力才可能有一切，『我才不會像我大大（老爸）被毛賊東欺辱成那慫樣』；一朝權在握，我決不心慈手軟，哪怕身後洪水滔天！」

所以，習近平不但要有絕對的權力和服從，還要海量的資產和安全的藏匿地。
他少年起沒有的安全感，現今更沒有。
他現在走到哪裡，就戒嚴到哪裡；一齣「十九大」，北京成了軍營；去一趟「一大」老巢，300米內沿線的兩側清空；他恨不得隨護的保鑣，把他的座駕圍得水洩不通。
他居然還號稱「自信王」，真是笑掉世人的大牙。
所以，他「大撒幣」的本質有二：除了籌劃在全世界建立所謂紅色帝國；就是在海外洗錢和轉移巨額資產，以備不時之需。

習近平曾經對蘇聯四分五裂時，沒有一人是男兒而忿忿不平、或者不齒，也騙了不少的人。

現如今：
習近平在政界對反對派、異見人士趕盡殺絕；
習近平在學界「七不准」，動輒開除；
習近平在法界縱容酷刑和電視示眾；
習近平在軍界建立習家軍，絕對忠誠，不得妄議；
習近平自己主持的黨的會議，他都要當「話霸」，一霸就是三個半小時；常常還要霸《人民日報》的首全版；
……
習近平，不正在製造中國無男兒嗎？！
假惺惺忿忿不平的習近平在「中國製造無男兒」，目的就是一個：讓習近平他自己成為中國唯一可以竊國的賊！而且天下誰也不敢對他的竊國行徑說一個「不」字，直至終身、世襲，你說習近平霸道不霸道？！
時至今日，居然還有人在鼓吹習近平集權是為了自由民主和憲政的幻象；習近平五年來，有一點點自由民主和憲政的影子嗎？！
這些人（不包括違心者），也不怕習近平的霸王風，扇掉你的舌頭。

物極必反。事態發展恰恰會和習近平的如意算盤相反，習近平帝王思想竊國野心的大暴露，反而一定促使更多的中國人覺醒、奮起，成為結束中共一黨專制和習近平專制獨裁竊國的基本力量。

中共十九大上，準備再加冕的習近平宣布了一條看似利國利民的「樓市習49（死就）字」，比毛澤東的話還靈，真是一句頂一萬句，高虛的中國樓市應聲倒了下來、狂潟……
那麼連帶的建材業的虛空倒不倒？建築業的虛空倒不倒？農民工的虛空倒不倒？中產階級的虛空倒不倒？房地產的虛空倒不倒？金融業的虛空倒不倒？……
中國大陸幾十年GDP的虛空倒不倒？
九千萬中共的虛空倒不倒？
習近平有本事製造、啟動第一張「多米諾骨牌」的倒下，他有本事止住「多米諾骨牌」的全部倒下嗎？讓我們拭目以待……
當然，會有人辯解：既然知道有虛空，那麼消除虛空，有什麼不好？可是，這些擁躉想過沒有：本來就靠烏托邦、虛空起家的中國共產黨經得起虛空的全面坍塌嗎？！

狂妄的前蘇聯「十月革命」100週年、習近平期盼2個100年之際：
看它樓起，看它樓塌！

**Comment by lrinQVQ** [comment]
请不要再Github发布政治敏感,人身攻击内容,谢谢
