### ISSUE TITLE
杭州地区google失效

### ISSUE THREAD

**Issue by qiuyuntao** [racaljk/hosts#137]
￼￼￼￼google失效，无法访问

**Comment by topcheer** [comment]
电信线路，时好时坏

**Comment by jackBaozz** [comment]
武汉电信很好的路过。

**Comment by andytimes** [comment]
确保你本地的 hosts 是最新的，检查换行符，是否刷新过 DNS 缓存 (最简单的方法就是断网一次)。

如果上述方式都不行，去 issue #133 找我提到的那个 IP 试试。

**Comment by Eamonnzhang** [comment]
武汉地区，同样时好时坏，几分钟断一次，google可以访问，但是github、stackoverflow等类似网站总是几分钟断一次，再过几分钟又可以连接。
hosts最新，dns缓存已经刷新，断网也试过，

**Comment by aofall** [comment]
两种原因

1.国际出口带宽不足，优先满足数据中心的流量 https://v2ex.com/go/bb

2.墙的间歇性阻断

@K-Guan  看见这种issue自己本地用nmap和tcping的测试一下443端口，如果端口开放且响应时间正常的话直接close issue。

**Comment by K-Guan** [comment]
@aofall *I didn't install both of them, is it my blame?*

**Comment by aofall** [comment]
Debain/Ubuntu 
sudo apt-get install nmap
CentOS/Fedora/Redhat
sudo yum install nmap

>nmap -p 443 216.239.38.125


tcping是Windows下的。
>tcping 216.239.38.125 443

ArchLinux没试过不知道有什么不同。

@K-Guan 二选一就可以了

**Comment by K-Guan** [comment]
@aofall For Arch:

    pacman -S nmap

But the problem is that I don't want install it since I don't like install any programs if I don't use them **everyday** :P
