### ISSUE TITLE
网址ip查询

### ISSUE THREAD

**Issue by sunxu3074** [racaljk/hosts#141]
问网址的 是不是去这查下就行了？
http://ip.chinaz.com/
换成ip然后填加到hosts中.

**Comment by imcaffrey** [comment]
给出的大部分IP被墙了啊

**Comment by racaljk** [comment]
可以去查 ，但不是放到hosts可以了，否则这个开源项目就没有存在的必要。

**Comment by Ignotus-CN** [comment]
绝大部分被墙网站不仅仅是DNS污染，还有IP封锁。
Hosts 的意义是在本机将域名解析到可用的、暂未封锁的IP。
