### ISSUE TITLE
Stars over 2k Celebration

### ISSUE THREAD

**Issue by K-Guan** [racaljk/hosts#142]
> To celebrate that our project's stars over 2k, this issue will be closed in one week.

为庆祝我们的hosts项目Stars到达两千，特开此Issue，为让大家也放松下。  

所以诸位维护本项目也都辛苦了，我刚刚看了下Commits也到达了200，大家在本Issue里面想说什么就说什么吧（But please don't trash this celebration or let it on fire, just relax）。

祝大家愉快。

**Comment by racaljk** [comment]
然而到我的comment发出之时还没到2000更不用说2048了

**Comment by K-Guan** [comment]
*这不快了嘛，正好我有闲心。大概今天到是没问题了。*

**Comment by racaljk** [comment]
@K-Guan 要不换个google logo XD

**Comment by K-Guan** [comment]
@racaljk Good idea, also celebrate Xmas ;)

**Comment by K-Guan** [comment]
不过好像大了点……

**Comment by K-Guan** [comment]
截止本comment，我们的：

- Stars: 2,004
- Commits: 204

-------------------

再次感谢各位对我们的项目持续的维护和支持！

**Comment by K-Guan** [comment]
[And Merry Christmas!](https://isitchristmas.com/)

**Comment by leehz** [comment]
。。。。。
