### ISSUE TITLE
Commands in README can overwrite the current hosts

### ISSUE THREAD

**Issue by lgfng** [racaljk/hosts#143]
The command show in the README will  override my own hosts and all my native setting is losing.

I attempt to use command `sudo cat /tmp/hosts >> /etc/hosts`, but it will make the hosts file bigger and bigger  after times of update.

**Comment by K-Guan** [comment]
Yeah, that's why we have host tools...I should mention this in README...

**Comment by racaljk** [comment]
覆盖是不可避免的，因为不知道哪些内容是于你而言重要的，append()又可能出现duplicate,所以用户需要使用前备份。

**Comment by 0x01f7** [comment]
* Wrap the hosts content with two lines which contain some pattern strings, just substitute it when doing an update task. [sample code written in Python](https://github.com/txthinking/google-hosts/blob/master/tools/fuckGFW.py). 

* Maintain you own hosts file, like `my-hosts`, use following command to update:

    ```
    $ mv /etc/hosts /etc/hosts.bak
    $ cat my-hosts hosts-in-this-repo > /etc/hosts
    ```
