### ISSUE TITLE
对于我们的getHosts.py的几点建议

### ISSUE THREAD

**Issue by K-Guan** [racaljk/hosts#147]
@racaljk，建议如下：

1. `import` 语句建议放在最上方，为什么在一个`class`之后？
2. NO CAPS VARIABLE NAME SINCE IT ISN'T READABLE LIKE THIS LINE.
3. 表示建议只用requests代替urllib，更加方便解决版本兼容的问题。
4. 等等，你的脚本现在是2和3通用的？那为什么还写：

    > For running this script,you need install python environment(v2.7).

5. [建议使用`str.format()`代替`%s`](https://pyformat.info/)
6. 刚刚发现还有很多地方可以改写。比如这个function：

        def __getattr__(self, attr):
            if attr=='get':
                return _Executable(self._gh, 'GET', self._name)
            if attr=='put':
                return _Executable(self._gh, 'PUT', self._name)
            if attr=='post':
                return _Executable(self._gh, 'POST', self._name)
            if attr=='patch':
                return _Executable(self._gh, 'PATCH', self._name)
            if attr=='delete':
                return _Executable(self._gh, 'DELETE', self._name)
            name = '%s/%s' % (self._name, attr)
            return _Callable(self._gh, name)

    可以直接改成：

        def __getattr__(self, attr):
            if attr in ['get', 'put', 'post', 'patch', 'delete']:
                return _Executable(self._gh, attr.upper(), self._name)
            return _Callable(self._gh, '/'.join([self._name, attr]))

    现在请告诉我你为什么要写那么复杂……

7. 代码不遵守PEP8，比如上面的例子中 `attr=='get'`, `==` 两边应各有一个空格。建议装个`autopep8`或是`yapf`之类的研究研究。

8. 有没有觉得你的代码太复杂，可读性很差，实用性不高？

**Comment by racaljk** [comment]
你提的大多数问题的原因是我仅仅把GITHUB OFFICAL LIBRARY PAGE中提供的github api for python(即之前的gihub.py)和getHosts.py合并在一起

剩下一个不用requests的原因是这么lightweight的脚本没必要

**Comment by K-Guan** [comment]
@racaljk *那么Github写的什么破脚本……*

**Comment by denglj** [comment]
@K-Guan @racaljk 

1. gihub.py 并非是github官方写的，可见 [这里] (https://developer.github.com/libraries/)，而是放在第三方库中的，也许github根本没对第三方库的质量作审核，只看star数量和fork数量认为该库还能用。

2. 写得不好，有人指出来，虚心接受，增长的是自己的知识能力。

3. github说到底是个社区，followers 数量并不一定是能力的体现。

4. requests也足够lightweight吧。不说框架本身，就是单单说大小，最新release的版本不足700K，况且这不需要打包至项目代码，requirements里多加一行的事。

5. 上面举例的那段代码来自 [这里](https://github.com/michaelliao/githubpy/blob/master/github.py#L144), 廖雪峰写的。
其他的我不知道，我只知道我python群里，两年多时间，入门新手提问关于学习廖的python教程中遇到的某个问题，应该不下500次。90%以上都被坑了，要么是表述不清，要么是连概念性的东西阐述都有偏差，要么是示例代码有误或书写有误。

**Comment by K-Guan** [comment]
@denglj 原来如此。廖的教程也是我的入门教程，也是从头看到尾了。我其实Python才学了不到一年，不过个人认为进展还不错。另外感谢说明。

**Comment by andytimes** [comment]
我说为什么对这位老师的名字如此熟悉，原来之前看过他的 Git 教程。

**Comment by K-Guan** [comment]
@andytimes 说起这个呀，这位老师的教程确实不错。我学Python和Git都是看的他的入门教程。基本很全面。最近学JavaScript时也把他的教材翻出来看了看，可是后来经过一对比不如一位法国人推荐的[You Don't Know JS](https://github.com/getify/You-Dont-Know-JS/)，就转学You Don't Know JS了（好吧我承认，英语还是有些吃力的，不过有翻译在手生词什么的完全不成问题）。

**Comment by andytimes** [comment]
@K-Guan 嗯嗯，一本好书能让人少走弯路。

而国内的编程教科书，实在是不敢恭维。

你去百度贴吧 "C语言" 这个吧，能看到删都删不完的"大神救救我"和求带之类的帖子。
我觉得这种现象不仅是人的问题，和教科书的质量也有关。

**Comment by K-Guan** [comment]
@andytimes 实际吧，我认为还是和人的能力与性格有很大关系的。

有些人呢，我认为天生就缺乏搜索能力。明明很容易就能通过Google找到答案的问题结果非得去问问。

还有些人呢，直接就想伸手……好吧也是有区别的，How can I foo the bar 总归来说比 How can I write an OS 强……

类似的问题我在StackOverflow，全世界最专业的问答站点上也看过太多了……多数直接delete。至少也是close。至于那些 A question which lacks a research，一般都早已被问过了，直接close as duplicate。


*有关什么样的问题是垃圾问题……举个例子：*

![screenshot from 2016-01-04 19-51-10](https://cloud.githubusercontent.com/assets/13862535/12089171/e5cb8ed6-b31c-11e5-84e5-92e15bd2b444.png)

**Comment by andytimes** [comment]
@K-Guan 确实，现在大多数人想要的东西太多了，求最好求最快，却不想想自己当前的能力可以接收什么。不顺应规律，自然会出问题。

关于我说的教科书问题。
看网络小说，看了几百万字，和看一本《红楼梦》相比。看几百万字不能说不"努力"，也不能说一点东西都学不到，但两者在内涵上，就是有本质区别的。
可能我这个例子举得不好，你会意就行了。也不继续讨论了，给你看个知乎答案
https://www.zhihu.com/question/24549965/answer/72870055

ps: 记得 SO 上对重复问题是直接封杀的，而且貌似只要问题有正确答案，就不会再有人继续讨论了。

**Comment by K-Guan** [comment]
@andytimes 嗯嗯，那我去看看去。
