### ISSUE TITLE
dl.google.com

### ISSUE THREAD

**Issue by leehz** [racaljk/hosts#149]
216.239.38.125	dl.google.com

pls add this. for gooler download android sdk & chrome so on

**Comment by imcaffrey** [comment]
:+1:

**Comment by K-Guan** [comment]
Please post a [pull request here](https://github.com/racaljk/hosts/pulls) if you think it's useful and have tested it.

**Comment by wsdjeg** [comment]
最近的hosts对github是不是不友好了，push 7次才成功

**Comment by leehz** [comment]
是因为 国内网络对 github 支持不好， 经常不能访问， 短线， 很正常
