### ISSUE TITLE
最新的hosts对本地网络支持不太好

### ISSUE THREAD

**Issue by wsdjeg** [racaljk/hosts#150]
我访问 baidu 腾讯 新浪 等本土网络 变得非常慢

**Comment by K-Guan** [comment]
这个……话说我没问题……确定不是本地网络或电脑的问题？

**Comment by wsdjeg** [comment]
不太可能，我同样的无线网，手机手机访问很快

**Comment by K-Guan** [comment]
刚刚尝试了下Youku，速度还是可以的。还是看看其他人的情况吧。

**Comment by meteoral** [comment]
我这里也没问题，查了下路由并不会影响新浪腾讯等
你traceroute一下你访问慢的网络看看是不是其他地方出了问题

**Comment by wsdjeg** [comment]
![2016-01-03 19-04-48](https://cloud.githubusercontent.com/assets/13142418/12078430/e96de4c4-b24c-11e5-87ab-0b5204b5fa3b.png)
什么都没有

**Comment by wsdjeg** [comment]
晕死 又一切正常了

**Comment by fluviusmagnus** [comment]
��������������������������������������������������������������

**Comment by racaljk** [comment]
和hosts无关
