### ISSUE TITLE
有没有可能增加 Gradle 的 IP ？

### ISSUE THREAD

**Issue by Roller44** [racaljk/hosts#151]
请问一下，有没有可能增加 Gradle 的 IP ? 挂 VPN 也挺慢的。

**Comment by K-Guan** [comment]
http://gradle.org/? 表示能直接开，不过感觉好像是挺慢的。

**Comment by Roller44** [comment]
是的，所有 Android Studio 的配置都建议挂 VPN 。不过话说回来，就算有了 IP 
，访问速度也不会变快，对吗？因为这好像不是 IP 被封掉的问题。

**Comment by Ignotus-CN** [comment]
Greatfire 显示该站并未被屏蔽，应该是该站CDN对中国支持不佳的缘故。
