### ISSUE TITLE
Android的sdk更新不了,这次的hosts,Android studio也更新不了了

### ISSUE THREAD

**Issue by weinierfei** [racaljk/hosts#153]
Android的sdk更新不了,这次的hosts,Android studio也更新不了了

**Comment by leehz** [comment]
https://github.com/racaljk/hosts/pull/154 look at this

**Comment by Roller44** [comment]
是不是还没有合并上去？刚才我更新了一下 host ，还是不能更新 Android SDK 。

**Comment by leehz** [comment]
现在还没合并上去， 你可以临时修改一下 使用，


在sl-ssl.google.com
下面加入 dl.google.com就行；  2行的IP地址一样
 
------------------ Original ------------------

**Comment by K-Guan** [comment]
#154 Merged by me just now.

**Comment by weinierfei** [comment]
ok了,可以了,貌似速度没以前快了

**Comment by Roller44** [comment]
Thanks.


 

-------- 原始邮件 --------
发件人：Kevin Guan <notifications@github.com>
时间：周一 1月4日 13:18
收件人：racaljk/hosts <hosts@noreply.github.com>
抄送：Yao ShuMin <roller44@163.com>
主题：Re: [hosts] Android的sdk更新不了,这次的hosts,Android studio也更新不了了 (#153)
