### ISSUE TITLE
hi~ new found

### ISSUE THREAD

**Issue by leehz** [racaljk/hosts#155]
http://www.micae.top/Under/Gip/index.html : :+1: 
这个网站有几个google 可以用的IP；

目前我发现本项目的有些hosts 解析有问题；

http://dl.micae.top/dl/hosts.txt
这是那边网站做出的hosts 解析， 希望能对本项目有帮助；
最起码可以融合整理一下， 方便大家使用吧

**Comment by K-Guan** [comment]
Excellent,  but what about create a Pull request?

**Comment by leehz** [comment]
我试一下吧， 还有个问题， Ad 广告 过滤的部分要不要的问题？
@recaljk
https://github.com/K-Guan

**Comment by K-Guan** [comment]
*Don't look at me, I don't know don't know don't know.*

**Comment by racaljk** [comment]
广告过滤也可以保留，但是考虑到这个是部分用户的需求，所以准备为广告过滤hosts新建一个文件和README FILE,你看如何？

**Comment by andytimes** [comment]
转载最好先问问维护这个 http://dl.micae.top/dl/hosts.txt 的人。

广告过滤、、这貌似是个填不完的坑。

**Comment by leehz** [comment]
主要是 今天google 检索好用的hosts的时候，找到的， 因为本项目维护的 几个IP 指向不正确了， 比较明显的是 android SDK 和 developer 网站； 小修小改是可以的（修复本项目的几个过期的ip）；

**Comment by K-Guan** [comment]
所以鉴于我提交了079f895，这个issue也是可以Close了？
