### ISSUE TITLE
Can you provide a npm host?

### ISSUE THREAD

**Issue by qiuyuntao** [racaljk/hosts#160]
Nowadays, more and more web develop need ```node```. But ```npmjs.com ``` has a low speed to visit, and sometimes can't visit.

So can you provide a npm host for us?

**Comment by K-Guan** [comment]
Just tried and the speed isn't so slow as you said. Let's see:

```
kevin@Arch ~> ping npmjs.com -c 20
PING npmjs.com (52.27.70.152) 56(84) bytes of data.
64 bytes from ec2-52-27-70-152.us-west-2.compute.amazonaws.com (52.27.70.152): icmp_seq=2 ttl=44 time=333 ms
64 bytes from ec2-52-27-70-152.us-west-2.compute.amazonaws.com (52.27.70.152): icmp_seq=3 ttl=44 time=333 ms
64 bytes from ec2-52-27-70-152.us-west-2.compute.amazonaws.com (52.27.70.152): icmp_seq=6 ttl=44 time=1005 ms
64 bytes from ec2-52-27-70-152.us-west-2.compute.amazonaws.com (52.27.70.152): icmp_seq=7 ttl=44 time=338 ms
64 bytes from ec2-52-27-70-152.us-west-2.compute.amazonaws.com (52.27.70.152): icmp_seq=8 ttl=44 time=332 ms
64 bytes from ec2-52-27-70-152.us-west-2.compute.amazonaws.com (52.27.70.152): icmp_seq=9 ttl=44 time=334 ms
64 bytes from ec2-52-27-70-152.us-west-2.compute.amazonaws.com (52.27.70.152): icmp_seq=10 ttl=44 time=336 ms
64 bytes from ec2-52-27-70-152.us-west-2.compute.amazonaws.com (52.27.70.152): icmp_seq=11 ttl=44 time=331 ms
64 bytes from ec2-52-27-70-152.us-west-2.compute.amazonaws.com (52.27.70.152): icmp_seq=12 ttl=44 time=332 ms
64 bytes from ec2-52-27-70-152.us-west-2.compute.amazonaws.com (52.27.70.152): icmp_seq=13 ttl=44 time=333 ms
64 bytes from ec2-52-27-70-152.us-west-2.compute.amazonaws.com (52.27.70.152): icmp_seq=14 ttl=44 time=334 ms
64 bytes from ec2-52-27-70-152.us-west-2.compute.amazonaws.com (52.27.70.152): icmp_seq=15 ttl=44 time=473 ms
64 bytes from ec2-52-27-70-152.us-west-2.compute.amazonaws.com (52.27.70.152): icmp_seq=16 ttl=44 time=786 ms
64 bytes from ec2-52-27-70-152.us-west-2.compute.amazonaws.com (52.27.70.152): icmp_seq=17 ttl=44 time=1182 ms
64 bytes from ec2-52-27-70-152.us-west-2.compute.amazonaws.com (52.27.70.152): icmp_seq=18 ttl=44 time=530 ms
64 bytes from ec2-52-27-70-152.us-west-2.compute.amazonaws.com (52.27.70.152): icmp_seq=19 ttl=44 time=590 ms
64 bytes from ec2-52-27-70-152.us-west-2.compute.amazonaws.com (52.27.70.152): icmp_seq=20 ttl=44 time=367 ms

--- npmjs.com ping statistics ---
20 packets transmitted, 17 received, 15% packet loss, time 19028ms
rtt min/avg/max/mdev = 331.593/486.953/1182.815/254.765 ms, pipe 2
```

**Comment by qiuyuntao** [comment]
Visit this site is very instability, somethimes it will visit, but sometimes it will not. So, I hopes you can provide to visit.

**Comment by K-Guan** [comment]
You know, I don't dig hosts. I only push some updates which maked by others; close, reply issues; and merge pull requests. So I can't help, but others can if they also this that it's a problem.

**Comment by qiuyuntao** [comment]
@K-Guan ok, thank you!

**Comment by andytimes** [comment]
这个网站应该是没有 CDN 加速的，所以要缓解这个访问问题。最好挂 V|||PN 或 SS。

**Comment by imcaffrey** [comment]
@qiuyuntao you may want to use http://npm.taobao.org/ as a mirror.

**Comment by imcaffrey** [comment]
@K-Guan maked --> made? = =

**Comment by K-Guan** [comment]
@imcaffrey *sigh, just a typo.*

**Comment by K-Guan** [comment]
@andytimes *Let's make all comments here in English (Collaborators can edit comments! Is this an abuse of Collaborator's ability? :P)*

**Comment by imcaffrey** [comment]
@K-Guan if you comment on SO with a typo, people will also correct you.

**Comment by K-Guan** [comment]
@imcaffrey Sure, so you also have an account on SO BTW? I'd like to know :)

**Comment by imcaffrey** [comment]
I am newbie= = Got the Badge - Peer Pressure.
You needn't know my account.D

**Comment by K-Guan** [comment]
Hey that doesn't matter ;). BTW I haven't got that badge yet. :D

**Comment by imcaffrey** [comment]
I wish you don't.= =

**Comment by K-Guan** [comment]
Well, however when you delete your post you can get your rep back. How many rep do you have now? :)

**Comment by imcaffrey** [comment]
Only to find out that I've got 1 rep.D

**Comment by K-Guan** [comment]
Try to get more! Well actually it's easy to get rep, check mine: https://stackoverflow.com/users/5299236/kevin-guan?tab=reputation :D

**Comment by imcaffrey** [comment]
:+1: You're good at this. Thanks.

**Comment by K-Guan** [comment]
Yeah, now let's not spam this issue via comments :P

**Comment by andytimes** [comment]
English is better than Chinese in Github, but all users are Chinese here.
Using Chinese is very benefit, friendly.

Of course, just enjoy talk in English, It's very cool and professional.

**Comment by K-Guan** [comment]
@andytimes  Indeed. But since I almost use English everyday (on the Internet), so I like talk in English rather than use Chinese.

But sure, as you can see, I sometimes also speak Chinese here since I know not everyone's English is good.

**Comment by aofall** [comment]
@K-Guan close issue
