### ISSUE TITLE
使用 Hozz 作为我们的官方 hosts 管理工具

### ISSUE THREAD

**Issue by K-Guan** [racaljk/hosts#164]
我个人认为这个决定还是不错的。[**Hozz**](http://ppoffice.github.io/Hozz)是一款具有图形界面的hosts管理工具，由@ppoffice设计。

@racaljk 在 #72 [提到过](https://github.com/racaljk/hosts/issues/72#issuecomment-169683522)，我还写了一个基础的评测（[扔在了Github Gist](https://gist.github.com/K-Guan/baea864203036e226061)）。

大家意见如何？

**Comment by andytimes** [comment]
那天早上醒来，我就看过你发的那篇测评了。
我觉得大部分人到这里，主要是求一个 hosts，对其他的应该都比较随意了。
好看好用，用起来比较欢快就行。

说一个和本 Issue 无关的内容。
我推荐一个很欢快的 Github 项目给大家看看
https://github.com/MrMEEE/bumblebee-Old-and-abbandoned/commit/a047be85247755cdbe0acce6 
至于为什么很欢快，看上面 commit 里的评论。
中午刷知乎看到的，还是很多年前的事情了
https://www.zhihu.com/question/39021759/answer/79439279
以及
http://coolshell.cn/articles/4875.html
收录了上面 commit 里的很多图片。

看到这张 ![](https://camo.githubusercontent.com/f4d49d11139bd8f9c20b78d3179b3d848b0ed552/687474703a2f2f7777342e73696e61696d672e636e2f6c617267652f35353663316363377477316469646c7432316634646a2e6a7067) 后，已经笑得不行了、、、

**Comment by K-Guan** [comment]
@andytimes lol，`rm -rf /usr`

**Comment by andytimes** [comment]
@K-Guan 由此可见，备份文件的重要性。
以及，
软件还是要通过测试，才能 release，不然、、、

**Comment by imcaffrey** [comment]
在那个commit下面能看到好多熟人。。。

**Comment by K-Guan** [comment]
@andytimes 正解，不过这么玩真的好么……

1. Spamming that project.
2. 不是吧？就这点事情至于么……[甚至有人说道](https://github.com/MrMEEE/bumblebee-Old-and-abbandoned/commit/a047be85247755cdbe0acce6#commitcomment-602672):

    > WOW! Github added "Disable email notifications for this commit" feature! Bye, bye my friends!

**Comment by qwe14789cn** [comment]
用一个host就够了 没事天天换host太麻烦  hozz多此一举

**Comment by aofall** [comment]
说到 rm -rf /usr
我想到那个最难调的BUG的问题。“借同事手机来测试获取微信昵称，但不管怎么改获取结果都是null，第二天才知道同事的微信昵称就叫null”

**Comment by aofall** [comment]
还有我建议修改一下README的Linux部分：如果我没记错的话notepad++是Windows only的（不包括其它人做的移植），难道不应该使用dos2unix吗

**Comment by andytimes** [comment]
@aofall 那个段子好像听过，听说同事后来被他打死了。
README 那部分的意思应该是，先在 Windows 上转换，再放到移动设备上。不过，Linux 在里面就不知道是什么情况了。还有没必要也不存在转换文本编码这回事。
基本上每个文本编辑器都有换行符转换，随便找一个来修改就行了。hosts 传上来就是 CRLF 换行符，Windows 应该无问题。我想用 *nix 的人，应该知道怎么转换。

**Comment by fluviusmagnus** [comment]
其实也可以考虑发布的时候就做两套吧，节省用户的时间。

**Comment by K-Guan** [comment]
@andytimes Linux平台没问题，直接下载下来就能用。

**Comment by zt515** [comment]
@K-Guan 我觉得更应该考虑的是定时更新而不是管理工具。
unix下可以使用crontab，windows下似乎缺少这样的一个工具。

**Comment by guqikay** [comment]
@zt515 Windows下也可以设置计划任务跑。我公司电脑一直这么更新的
