### ISSUE TITLE
Can we add a hosts for pastebin?

### ISSUE THREAD

**Issue by K-Guan** [racaljk/hosts#165]
So we already have the hosts for Github Gist, I wonder if we can have hosts for pastebin? It's also a famous paste service but seems we don't have hosts for it and it's banned here (ShanDong).

**Comment by imcaffrey** [comment]
:+1: Banned in Liaoning.

**Comment by aofall** [comment]
pastebin.com？
It use CloudFlare CDN
You can try it
>162.159.208.33 pastebin.com

**Comment by K-Guan** [comment]
@aofall Yep, but that doesn't work:

> ERR_CONNECTION_RESET

**Comment by andytimes** [comment]
可以参考 https://zh.wikipedia.org/wiki/%E4%B8%AD%E5%8D%8E%E4%BA%BA%E6%B0%91%E5%85%B1%E5%92%8C%E5%9B%BD%E8%A2%AB%E5%B0%81%E9%94%81%E7%BD%91%E7%AB%99%E5%88%97%E8%A1%A8 
虽然更新有些滞后。

pastebin.com 用 nslookup 能探测到两个 IP，

```````````
root@android:/ # nslookup pastebin.com 8.8.4.4
Server:    8.8.4.4
Address 1: 8.8.4.4 google-public-dns-b.google.com

Name:      pastebin.com
Address 1: 104.20.64.56
Address 2: 104.20.63.56
``````````````
但是我这里不能访问，可能是运营商屏蔽了，或者 G|||FW 用其他方式屏蔽

用 Gist 吧

**Comment by K-Guan** [comment]
@andytimes Ah, says:

> - Pastebin（3月曾解封）

**Comment by aofall** [comment]
@K-Guan 如果网站不支持https访问且被加入关键词Reset列表则无解。
这种情况只能联系网站管理员让TA支持https

**Comment by aofall** [comment]
Ps：162.159.208.33 是CloudFlare Global Anycast

**Comment by K-Guan** [comment]
@aofall 啊，那好吧。

**Comment by andytimes** [comment]
@aofall 感谢分享经验！
