### ISSUE TITLE
以下为重复内容，请去除。

### ISSUE THREAD

**Issue by vokins** [racaljk/hosts#168]
216.239.38.125 video.google.com
216.239.38.125 video-stats.video.google.com
216.239.38.125 upload.video.google.com
216.239.38.125 video.google.com.hk
216.239.38.125 video.google.com.tw
216.239.38.125 uploads.stage.gdata.youtube.com
216.239.38.125 0.gvt0.com
216.239.38.125 1.gvt0.com
216.239.38.125 2.gvt0.com
216.239.38.125 3.gvt0.com
216.239.38.125 4.gvt0.com
216.239.38.125 5.gvt0.com
216.239.38.125 www3.l.google.com
216.239.38.125 sslvideo-upload.l.google.com
216.239.38.125 video.l.google.com
216.239.38.125 video-stats.l.google.com
216.239.38.125 video-analytics.l.google.com
216.239.38.125 video-thumbnails.l.google.com
216.239.38.125 youtube-ui.l.google.com
216.239.38.125 yt-video-upload.l.google.com
216.239.38.125 ytimg.l.google.com
216.239.38.125 ytstatic.l.google.com
216.239.38.125 youtube-ui.l.google.com
216.239.38.125 www3.l.google.com
216.239.38.125 video-stats.l.google.com
216.239.38.125 ytimg.l.google.com
216.239.38.125 yt-video-upload.l.google.com
216.239.38.125 uploads.stage.gdata.youtube.com
216.239.38.125 yt-video-upload.l.google.com
216.239.38.125 video-analytics.l.google.com
216.239.38.125 ytimg.l.google.com
216.239.38.125 ytstatic.l.google.com
216.239.38.125 video.google.com
216.239.38.125 video.l.google.com
216.239.38.125 video.google.com.hk
216.239.38.125 video.google.com.tw
216.239.38.125 0.gvt0.com
216.239.38.125 video-thumbnails.l.google.com
216.239.38.125 1.gvt0.com
216.239.38.125 2.gvt0.com
216.239.38.125 3.gvt0.com
216.239.38.125 4.gvt0.com
216.239.38.125 5.gvt0.com
216.239.38.125 upload.video.google.com
216.239.38.125 sslvideo-upload.l.google.com
216.239.38.125 video-stats.video.google.com
208.80.154.224 www.wikipedia.org
208.80.154.224 ja.wikipedia.org
208.80.154.224 ja.wikipedia.org
208.80.154.224 pl.wikipedia.org
208.80.154.224 pl.wikipedia.org
208.80.154.224 pt.wikipedia.org
208.80.154.224 pt.wikipedia.org
208.80.154.224 www.wikipedia.org

**Comment by vokins** [comment]
也希望能将包含
googlesyndication
googleadservices
的内容去除掉。
比如：

**Comment by K-Guan** [comment]
好，我马上去改。可是为什么要将包含`googlesyndication`和`googleadservices`的去掉？

**Comment by vokins** [comment]
主要是googlesyndication和googleadservice一般都是广告调用的，这个是google的广告域名。
只去处这些不去处 www.googleadservices.com的话并不影响登录查看后台和使用的。还有像admob，doubleclick都是广告域名，没必要加入。
216.239.38.125 partner.googleadservices.com
216.239.38.125 pagead.google.com
216.239.38.125 pagead2.googleadservices.com
216.239.38.125 buttons.googlesyndication.com

**Comment by vokins** [comment]
ps，能否把firefox的一些域名也加入，最近ff扩展中心，墙的厉害，真是太慢了。
目前我自己用的是：
54.68.16.226 addons.mozilla.org
54.230.244.252 addons.cdn.mozilla.net
93.184.215.191 mozorg.cdn.mozilla.net
54.192.100.115 download-installer.cdn.mozilla.net

**Comment by vokins** [comment]
虽然安卓不能识别windows换行符，但是windows却可以识别安卓的换行符。
如果想hosts通用，可以用unix的换行符，来编辑文件，几大系统通用。

**Comment by K-Guan** [comment]
有关广告域名方面我不敢定夺，需要听下其他人的意见。另外几点相同。所以等我在去开几个新的issues。

**Comment by K-Guan** [comment]
^ 完成，感谢建议。

**Comment by vokins** [comment]
OK
