### ISSUE TITLE
删除广告hosts域名

### ISSUE THREAD

**Issue by K-Guan** [racaljk/hosts#169]
如 @vokins 在 #168 所说：

> 主要是googlesyndication和googleadservice一般都是广告调用的，这个是google的广告域名。
只去处这些不去处 www.googleadservices.com 的话并不影响登录查看后台和使用的。还有像admob，doubleclick都是广告域名，没必要加入。

>        216.239.38.125 partner.googleadservices.com
>        216.239.38.125 pagead.google.com
>        216.239.38.125 pagead2.googleadservices.com
>        216.239.38.125 buttons.googlesyndication.com

诸位意见如何？

**Comment by aofall** [comment]
删删删 或者移动到Google CN并注释掉

**Comment by K-Guan** [comment]
@aofall 嗯……我暂时先给禁用了。这个issue暂时先不急着close，看看他人的说法，实在没用我再直接删了就行。

**Comment by aofall** [comment]
为什么要注释？
因为Google ADS业务在华还是有运营的，虽然搜索退出大陆了但公告一直没退出。中国大陆地区解析到了谷歌中国（北京）服务器，而不是国外服务器。
我建议移动到Google CN下是因为指不定哪天公告退出后还得一个一个的收集域名。
Ps：doubleclick.net 也是公告域名

**Comment by K-Guan** [comment]
原来如此，了解！
