### ISSUE TITLE
添加有关Firefox的hosts

### ISSUE THREAD

**Issue by K-Guan** [racaljk/hosts#170]
如我们在 #168 所说：

    54.68.16.226 addons.mozilla.org
    54.230.244.252 addons.cdn.mozilla.net
    93.184.215.191 mozorg.cdn.mozilla.net
    54.192.100.115 download-installer.cdn.mozilla.net

**Comment by aofall** [comment]
慎加 
Mozilla 都快穷死了（开玩笑）服务器可没Google那么好。有些地方可能速度不错，有些地方（确切地说不是分地区而是分ISP，因为各ISP的出国线路不一样），则可能是减速。
解释一下ISP的出国线路：

电信：
>省骨干网-国际出口-去往各地
>但只有少数流量是直接去往各地的，大部分绕美国NTT，一到高峰期线路就炸了，优先满足商业机房，民用宽带则被直接丢包。这就是为什么电信会被吐槽

移动：出国线路中规中矩，国内线路就可以开喷了
>省骨干网-北京骨干网-国际出口-去往各地

去东南亚香港美国日本等地基本是直连，但是流量一大就丢包断流，几秒或几分钟内恢复

**Comment by K-Guan** [comment]
@aofall 感谢解释。

我倒是在想，要是能有自动测试hosts的速度，并自动调整禁用或启用的软件就好了。


@vokins 既然如此的话，您还是先直接用您现有的吧。毕竟 *大家的情况不同* ，不能加上后本来有部分人本来很快的，结果还慢了。

**Comment by aofall** [comment]
Mozilla服务这回用了Amazon Cloudfront
官网mozilla.org则用了Cloudflare
但移动铁通对于这两个cdn则干扰的非常积极，对此我深有体会。
你也可以看看 https://v2ex.com/t/235183#reply12

**Comment by K-Guan** [comment]
嗯，我明白了。感谢解释。
