### ISSUE TITLE
直接使用Unix换行符代替Windows换行符

### ISSUE THREAD

**Issue by K-Guan** [racaljk/hosts#171]
From #168 :

> 虽然安卓不能识别windows换行符，但是windows却可以识别安卓的换行符。
> 如果想hosts通用，可以用unix的换行符，来编辑文件，几大系统通用。

**Comment by aofall** [comment]
需要的人自行转换。
连个换行符都懒得转，你用哪门子免费的东西啊

**Comment by dequn** [comment]
这么说 也不对，既然为大家服务，用unix换行符能够实现通用，也没必要让用户去折腾，比如我这种小白就不会弄。

**Comment by K-Guan** [comment]
@aofall 然而方便他人同样也方便我们呀，要是是Unix换行符可以直接通用的话我们也能省下不少麻烦。

> 总之呢，我可不想看到有时候某些小白来开个issue问怎样改换行符。

**Comment by Sasasu** [comment]
win下用unix换行符的话文件会变的很难看，不如在readme里告诉windows怎么改换行符。
我觉得会去改host并且不知道怎么改换行符的windows用户应该很少吧。

ps：现在是unix换行符了吗？

**Comment by K-Guan** [comment]
@Sasasu 好像还是Win的换行符。

如果是如此的话，我还是觉得使用Windows的换行符为好。不过好像Linux也可以直接使用。
（主要，Windows用户的平均水平毕竟低于Linux用户对吧？）

**Comment by andytimes** [comment]
@K-Guan 貌似用记事本打开会像 @Sasasu 说的那样，Notepad++ 之类的不会。

我觉得 @aofall 说得不错，还是别改动了。能替换 hosts ，一般也都会改换行符，吧。

**Comment by andytimes** [comment]
@Sasasu 现在是 win 换行符

看 .gitattributes 的内容，可以作出判断。

**Comment by K-Guan** [comment]
@andytimes 嗯……既然如此也好，避免更改后又出现什么其他的毛病。
