### ISSUE TITLE
passwords.google.com 不可用

### ISSUE THREAD

**Issue by xubin990510** [racaljk/hosts#173]
$ ping passwords.google.com
    PING www3-china.l.google.com (74.125.204.102) 56(84) bytes of data.
    ^C
    --- www3-china.l.google.com ping statistics ---
    3 packets transmitted, 0 received, 100% packet loss, time 1999ms

正确的应该是：

    $ ping google.com
    PING google.com (216.239.38.125) 56(84) bytes of data.
    64 bytes from chatenabled.mail.google.com (216.239.38.125): icmp_seq=1 ttl=52 time=48.3 ms
    64 bytes from chatenabled.mail.google.com (216.239.38.125): icmp_seq=2 ttl=52 time=48.1 ms
    64 bytes from chatenabled.mail.google.com (216.239.38.125): icmp_seq=3 ttl=52 time=51.2 ms
    ^C
    --- google.com ping statistics ---
    3 packets transmitted, 3 received, 0% packet loss, time 2002ms
    rtt min/avg/max/mdev = 48.116/49.246/51.230/1.430 ms

**Comment by xubin990510** [comment]
显然不应该解析到`www3-china.l.google.com`的啊。。

**Comment by andytimes** [comment]
@xubin990510 刚刚用文本编辑器搜索了一下，passwords.google.com 不在这个 hosts 列表里。

刚刚访问了这个网址，应该是用来登录 Google 的，具体我不大清楚。
如果只是用来登录 Google ，可以访问 https://accounts.google.com 
如果你有其他用途，可以去请教 @aofall

**Comment by aofall** [comment]
@K-Guan 加一条
>216.239.38.125 passwords.google.com

CNAME到www3-china.l.google.com并没有什么奇怪的，只要IP正确即可。
就像我的博客 blog.aofall.xyz 我CNAME到jx.yge.me上一样。
还有我做的另一个东西 chromeba.com 也是CNAME，这个放在SAE上了。
你需要补充一些域名解析的知识。

**Comment by xubin990510** [comment]
@andytimes 具体来说是用来管理存储在google服务器上的密码的。
（另外应该用

    216.239.38.125 passwords.google.com

而不是

>216.239.38.125 passwords.google.com

)
@aofall 本人才疏学浅请不要在意。。

**Comment by xubin990510** [comment]
@andytimes 
on https://support.google.com/chrome/answer/95606?hl=en:

## See saved passwords
# On the web
You can see your saved passwords on any browser by visiting passwords.google.com if:

    you’ve signed in to Chrome and saved passwords or
    you’re using Google Smart Lock for Passwords on Android

Find out more about managing saved passwords from the web.

**Comment by aofall** [comment]
然而hosts并不是代码
用引用或者代码并没有什么区别

**Comment by K-Guan** [comment]
[1st stage - denial.](http://www.thwink.org/sustain/glossary/CycleOfAcceptance.htm)

**Comment by xubin990510** [comment]
ok, it works now. Thanks!
