### ISSUE TITLE
[hosts无关内容] 百度贴吧的相关讨论

### ISSUE THREAD

**Issue by andytimes** [racaljk/hosts#176]
周末在家里看 CCTV 新闻，看到 "国家互联网信息办"约谈百度负责人的新闻

今天上知乎一搜，全是相关内容。以前偶尔会用百度搜中文，现在改用必应了。所谓的店大欺客，就是这种感觉吧。

知乎一答案的链接
> 百度贴吧的血友病吧被卖了，原吧主小吧主突然间全部被拿下，如何看待百度这样的行为？ - 回答作者：藤本烈 http://zhihu.com/question/39322261/answer/80910125

虽然不知道是否可信，如果百度一半收入都来源于此，实在是恐怖。
还有最后的贴吧文章的用户协议，实在是无耻。

**Comment by imcaffrey** [comment]
可信、
然而这里开这样的issue好吗。。

**Comment by andytimes** [comment]
@imcaffrey 嗯嗯，这里喜欢广泛的讨论问题，比如
https://github.com/racaljk/hosts/pull/84 
当然，如果不合适我会关 Issue

**Comment by andytimes** [comment]
百度贴吧的权利声明
> 第三章 权利声明

第20条 用户在任何时间段在百度贴吧发表的任何内容的著作财产权，用户许可百度公司在全世界范围内免费地、永久性地、不可撤销地、可分许可地和非独家地使用的权 利，包括但不限于：复制权、发行权、出租权、展览权、表演权、放映权、广播权、信息网络传播权、摄制权、改编权、翻译权、汇编权以及《著作权法》规定的由 著作权人享有的其他著作财产权利。并且，用户许可百度公司有权利就任何主体侵权而单独提起诉讼，并获得全部赔偿。
 
http://tb1.bdstatic.com/tb/eula.html

**Comment by denglj** [comment]
这都多久了，太后知后觉了吧。还是不讨论这些问题为好。到底是“这里喜欢广泛地讨论问题” 还是 “你喜欢在这里广泛地讨论问题”，这需要查实一下。

**Comment by sosp** [comment]
百度没有下限，给病人家庭雪上加霜
2016年1月19日 1:59 PM，"Andy Deng" <notifications@github.com>写道：

**Comment by andytimes** [comment]
@denglj 
> “你喜欢在这里广泛地讨论问题”

你说的没错，确实是我喜欢讨论的缘故。
对于这件事也确实后知后觉了，感觉比较气愤，不过确实也会影响他人心情。不讨论了

**Comment by andytimes** [comment]
@sosp 以前百度觉得没这么恶劣，觉得它是一个不错的技术性公司。现在这些做法确实让人反感了。
唉，期待这次教训之后能够改过。

**Comment by FrankHB** [comment]
然而更大的问题是根本就不醒目（虽然比起携程什么的也不算太坑）、TL;DR、以及有变化根本就不通知（但非百度专利）。
根据[中文维基词条](https://zh.wikipedia.org/wiki/知乎#.E8.B4.9F.E9.9D.A2.E8.AF.84.E4.BB.B7)，知乎在早些年的协议中也有几乎一样的条款，我怀疑就是抄百度的。

**Comment by Ignotus-CN** [comment]
←_←前几个月曾有过建立百度贴吧的替代品的想法，甚至连后端软件和名称都想好了。然而对 web 开发一窍不通，又面临大考，只好作罢。

**Comment by K-Guan** [comment]
别急着关呀，我这两天忙着完善[我在SO的一个答案](http://stackoverflow.com/q/34835951/5299236)，忘了看看这边了。

**Comment by K-Guan** [comment]
@Ignotus-CN 同想过好多次，也试过好多次，然而最终还是作罢。

**Comment by K-Guan** [comment]
@FrankHB Hiya!!! Long time no see :D

**Comment by K-Guan** [comment]
对于此事，鉴于我已经 **完全退吧** 一个多月了，这些事情我的消息并不是很灵通，也不想去关注。不过我还是好奇，也愿意参与讨论。

之前当我还在混贴吧的时候，就有说“钢琴吧被卖，吧主空降”一事。算下来，这是两个月左右前的事情：
![screenshot from 2016-01-19 22-58-18](https://cloud.githubusercontent.com/assets/13862535/12422187/abfe8196-bf00-11e5-9d45-a43873054d27.png)

当时算是如火如荼了。经过我的简单核实，发现确有此事。然而我当时并未在意，既然从来被听说过钢琴吧（不弹钢琴嘛），也就没去管。

----------------

接下来，“C++吧”一天之间吧主全部被刷。有传言道：“C++吧也给空降了”。
赞扬下Google的搜索能力：

> [C++吧已经被空降，这个吧还会远吗？_linux吧_百度贴吧](http://tieba.baidu.com/p/4174886885)

当时身为Linux吧的小吧主，又有这么个贴 ^，确实有和大家商量迁移一事。可是前思后想，有说自己搭，有说自己写，有说迁移别的网站（国内如知乎等，国外如Reddit等）。最后基本都快订好了，还是因为意见不合而作罢。

之后我也实在受不了百度了，还是选择了辞职走人。感谢SO的管理制度，现在作为[**SOCVR**](http://stackoverflow.com/teams/11/socvr)的一员，表示我在SO混的还是可以的……好像跑题了。

------------------

我的话是说完了，各位有和建议？

**Comment by racaljk** [comment]
贴吧药丸...然而诸如此类言论可类比末日预言

**Comment by andytimes** [comment]
@K-Guan 其实 Google 无法回归，不完全是 ZF 的问题。不过，ZF 对外如此敏感，而对内的恶性竞争，却如此放纵。感觉真的不好，虽然我们现在求稳求发展，也不能缺乏监管的力度。

一开始我是有点生气，我比较喜欢讨论，所以想发上来看看你们的想法 (因为没有其他地方能讨论)。其实以前那些贴吧空降吧主，百度竞价排名之类的早有耳闻，只是不太关注。现在都闹到上中央电视台的程度了。

本来 C C++ 这两个吧大多都是小白，如果给人买走了吧主，估计能骗走不少学生的钱。以前对贴吧的不喜，只是看不惯太多伸手不思考的人，现在来了个花钱买来的官方吧主，那不是坑人吗？那些不知道 SO, Quora, 知乎的学生，在骗子的引导下，我估计 《21 天精通 C++》 之类的东西又要出来了。

我下午上体育课看了知乎有关血友病吧的问题，百度不仅一开始空降官方吧主，后来，还删了所有的原吧务人员和他们总结的经验帖 (不知是骗子所为，还是百度贴吧所为)。

百度搜索和 Google 一样，都是靠卖广告收益。在知乎上看过一个回答，Google 有用户搜索商品，购物带来的广告收入。而国内因为有淘宝，所以百度在这一方面的收入一般。
我不知道真实数据是怎么样的，但无论如何也不是干这种坑人，延误病人治疗的理由。

希望百度能吸取教训吧。
以前看到亲戚朋友浏览器主页的 hao123 ，再看到百度那简洁的首页，真心是挺喜欢百度的。

*百度一下，你就知道* 
现在用它搜出来的东西大多都是垃圾广告，如何让人知道？

我一个朋友学编程，想找 Visual Studio 官网，用百度搜出来，第一页全是自称官网的网站，当时我也试着搜了一下，都是国内某软件站。刚刚我用百度搜索了，还不错，至少把 Visual Studio 官网放在前面了。能改正就是好事。

现在用百度搜索 血友病 这个关键字，竟看不到道歉，而是
> 百度回应“出卖血友病吧”:疾病吧全面停止商业合作

实在是失望，我表示开始转移百度云资料到 Dropbox，尽管有些不便，也暂时不愿用百度的产品了

有些人说人家免费给你提供服务还嫌弃，可能我们看到的广告之类的推广内容，都被他们忽视了吧，看到百度提供的广告就是在付费了。
其实，关 Issue 不是想去争论，而是不想影响别人心情。表示本来昨天挺欢快的，看了知乎知道这件事的细节，一下子心情就不平静了。

其实没必要删评论啊，那个同学说的没错，我确实挺喜欢讨论一些无关内容的，然而，能讨论的地方实在是太少了，还是和你们几个交流比较愉快。

**Comment by andytimes** [comment]
@racaljk 赞同，毕竟贴吧那么多的用户。不过，百度继续这样店大欺客，倒是有可能预言成真。

**Comment by andytimes** [comment]
@FrankHB 刚刚看过相关内容了。互联网企业能真正把用户当作朋友看待，就不会这样做了。现在知乎就很好，虽然也经常看到有争执 ("互联网" 话题)，也因为自己提简单问题被人恶意修改侮辱过。
不过，至少我举报后，知乎团队一会儿就处理了。
而贴吧多靠消耗热心网友的精力去管理，百度还这样做，无论事情或轻或重，都实在太令人失望。

**Comment by FrankHB** [comment]
要讨论区的替代品多的是，但多数是针对少数个别专业吧的特定用户的替代论坛（比如[1](chaoli.club)[2](chikyuuschool.com)[3](cpp.ra2diy)），而不是整个贴吧。易来来死了几年了？

为什么没法替代？因为不同用户的需求集不一致。而贴吧接近 lowest common denominator 。如果你要统战而不是放弃现有的一些其他用户，要么就用贴吧，要么就抄一个类似贴吧的东西。然而：

* 你想要什么样的用户和你讨论？你确定你能搞清楚要明确不欢迎的什么用户这点上能和*所有人*达成共识？
  * 当然不可能。这也一样只能取 lowest common denominator 。在不太毒菜的策略下这可以通过吧规实现。
  * 但这是贴吧。就算你自己抄个贴吧，吧规制定得再合理，也可能第二天就没什么人了。毕竟没人有义务替你活跃，你的服务不是必需和不可替代品，而你的引流和推广是干不过包括百度在内的任何有些规模的内容站点的。（如果你觉得你能是反例……壕作友？）所以注定只能当小圈子的备胎。
* 还有一些并非任何个别站点的锅。
  * 比如，我不喜欢这种限制在域名之下没法流动的“户籍制度”。登录 id 多了管理起来也麻烦。
    * 当然，你可以实现单点登录，但那又有更多技术和非技术上的破事。

SO（包括各种 exchange ）在这里的问题是作为技术问答网站的刻板定位，不适合一般讨论；另外就是大部分地方你只能使用英语，否则没什么人能鸟你。

知乎的根本的问题是漏洞百出的集权管理机制——某种意义上还不如空降吧主友善，也就比百度百科这种没智商还强行审核所有内容的逗比好点了；搜索什么的笑话或许倒是还能随着时间改进。另外如果真的想要当替代，贴吧化 不 可 避。

我其实不太在乎“互联网企业能真正把用户当作朋友看待”（其实和企业不企业无关），反正除了圈子内给脸（当然百度这样的规模也不需要）外，都只剩下一种契约关系罢了。百度这几年来一直在恶心用户（比如离谱的广告投放）；所以我就是不按百度的意思出牌（比如屏蔽广告），就是使用免费的服务而不使它获得预期的收益，那也就是反过来恶心百度了。于我而言鉴定什么服务是白送的成本接近于零，所以以我的立场上也算平衡了，没什么好优越的。（这个套路当然也不只限于适用百度。）

空降吧主是另一回事。我仍然不信百度作为整体会二到这个层次上；总得来说，看起来仅仅下作惯了的运营团队“十动然拒”阳奉阴违起作用，“事情没有闹大”罢了。另一方面，放任不管你同样弱势：你不可能隔离信仰百度的逗比；于是出于公益考虑，脏活总是要有人做——至少得做到多数人不会盲信百度为止。另外，现阶段百度还是装作要脸的，不敢把卖吧作为基本政策，会“虚心”接受强烈的抵制而暂时放弃卖个别吧，所谓“合伙人”也不敢直接全权代表百度贴吧官方的意见，所以还有肛一下的余地。

**Comment by FrankHB** [comment]
关于网盘的问题我顺便说两点。
首先是作为存储服务。这里我和 RMS 一样[不信 SaaSS](http://www.gnu.org/philosophy/who-does-that-server-really-serve.en.html) 。所有此类服务，只要整体上不是你能直接控制生死的，都有完全失控的风险；所以只要在乎数据安全性，就*只能当备胎*——可选的冗余备份。异地冗余备份能降低整个系统的风险，但如果你自己不保留一份确保关键时刻的可用性，那往往还不如不备份。在这里，除非你备份的内容会被审查机关盯上，放在哪的差别并不大。
其次是作为共享和传播手段。这里又分为几个方面：

* 和存储服务的类似性质
  * 容量
  * 故障率
* 传输是否方便
  * 最基本的，上传下载稳定且足够快
  * 用户环境的可移植性（比如是否只能在操作系统上使用）
* 是否能保证稳定的接口访问
  * 内容是否容易被审查而导致失效
  * 共享链接/提取码等接口是否容易失效或需要不断维护

百度云的优势来自于相对比较容易最大限度地满足直接的需求。尽管广义上最终还是依赖百度的财大气粗，抵制百度云理论上能带来那么些影响（减少付费率），但实际上个别行为可以忽略。而在没形成垄断却也没有其它完全能替代产品的情况下，需要这些服务的用户会有净损失是肯定的；而没被百度日过的傻多速反倒不受影响。所以相比起来我不觉得这有卵用。

靠信仰反对和兹瓷同样不靠谱，只不过是成本较低的做法之一罢了。要拿意识形态做文章在统战的意义上则是效率低下的过于粗放的手段。（否则 RMS 也早就一桶浆糊了。）

**Comment by K-Guan** [comment]
@andytimes 是呀，能认真讨论东西的地方实在太少了。既然有那么个话题，我也希望大家能认真在一起探讨下。删评论嘛……是我（个人）不喜欢这类“无用”的Comments（在SO，有个专门的说法叫“Noise（噪音）”。所谓同问题无关，Thanks，Can you help me please?之类的都是这一范畴）。

现在想想好像是有点冲动了，我也给各位道个歉。

**Comment by K-Guan** [comment]
@FrankHB 

SE方面，确实。如果你随便发点什么无关的东西的话，甚至可以被当成“Spam”对待。我们对于Spam是这样处理的：

> #### What happens when I flag something as *spam* or *abusive*?
> The spam and abusive flags are designed to automatically eliminate truly disruptive posts through the collaboration of the community.
>
> - 3 flags -- post is banished from the front page.
> - 6 flags -- post is locked, deleted, and the owner loses 100 reputation.

不过也不是没有开放的地方，比如Chat。随手找了两个有趣的Bookmarked conversations：

- http://chat.stackoverflow.com/rooms/41570/conversation/what-does-sht-mean
- http://chat.stackoverflow.com/rooms/41570/conversation/mods

--------------------

语言倒是个大障碍，实际不是没讨论过中文版的SO（现有俄语，葡萄牙语等），但是好像是因为编码的问题而废止了。

倒是Chat Room自由，语言什么的完全不限制（需要注意的是一个脏字不能有就是了，具体见上面的第一个conversation）。只是有个rep限制：https://stackoverflow.com/help/privileges/chat

（虽然我一天拿个一百多rep都不成问题，但是对于有些人，还是很麻烦了）

---------------------------

然后，其实还有这个问题：

- http://meta.stackoverflow.com/questions/267715/is-stack-overflow-accessible-in-china

不过hosts是可以解决的，但是对于他人嘛……哦，也不错。可以给我们提高知名度。

**Comment by K-Guan** [comment]
网盘问题我已经转Gmail了，百度云好像不用客户端下载死慢，还不让wget下载……

**Comment by denglj** [comment]
1. 删掉我的评论是否不妥？
2. Github是技术交流社区
3. 当利用github讨论敏感话题这真的对github发展好吗？
4. 当风气形成，不管你github是不是技术交流，不管是否还有当初的IT界合力发声，github离彻底被墙估计不远了。到时又去那里放你们所谓的hosts呢？
5. 既然都学会翻墙了，谈论某些话题怎么会说没地方？一些翻墙入门引导的网站上，列了一大堆吧？
6. 即或找不到别的地方谈论这些话题，你们这么感兴趣，又有技术，半天时间一个国内外友人都可访问的论坛必然可以搭建起来吧？
7. 怕担责？怕担责就要为自己负责。

**Comment by K-Guan** [comment]
关于管理方面，我十分喜欢SO的管理制度：

首先，使用upvotes和downvotes，让别的用户来评价你的答案与问题。可是如果你是一个新用户的话，你却并不能upvote或downvote别人的问题，[你需要取得足够的reputation (rep)](https://stackoverflow.com/help/whats-reputation)。

而rep的用处，除了可以upvote和downvote之外，还可以[“flag”一个post](https://stackoverflow.com/help/privileges/flag-posts)，然后等到了3k，还可以[“vote to close or reopen a question”](https://stackoverflow.com/help/privileges/close-questions)，到了10k，还可以[“vote to delete or undelete a questoin”](https://stackoverflow.com/help/privileges/moderator-tools)等等。

SO最高权限的用户是[**Moderator**](https://stackoverflow.com/help/site-moderators)，他们是由用户选举出来的。

虽然他们不是SO的工作人员，然而他们却同有最大的权限，如删除任何posts，users等等。为什么SO能开放给用户如此之高的权限？是个值得探讨的问题。

虽然贴吧有吧主一说，然而全然不考虑用户的决定。只是看谁适合就给谁。这样真的好吗？

**Comment by K-Guan** [comment]
1. 是，我向你道歉。可是我希望你的语气也可以好一点。毕竟大家在这里均为朋友，请不要用太过“尖锐”的语气。
2. 是，但是我们在讨论的，难道和技术/IT业无关吗？
3. 这个话题，就我认为，已经是烂大街的话题了，根本算不上敏感（鉴于贴吧和知乎已经吵翻天了）。对于Github，我觉得并无大碍。毕竟本来hosts也就是个敏感的东西，我们连hosts都敢放在这儿，又何谈讨论这么点所谓的“敏感话题”呢？难道讨论GFW还不比这个“敏感”吗？
4. 如果我们不这样做，不关注每件大事，而是统统视而不见，岂不是更加放纵国内的企业与政府的行为？
5. （6同）然而这还是用户的问题。比如我现在去创了个论坛，如果不在这儿说一声，大家怎么能找到呢？可是如果这样，和直接在这里讨论，又有和不同呢？所以百度方面也是这样，即使大家都去了一个自创的论坛，还是会有小白陆陆续续去贴吧的。结果然后，又会有一波人在讨论是不是应该创建个新论坛……然而还是一样？如果不能直接改变，想自己创建一个地方来代替，然而还是没有用处的。
7. 何谈怕担责任？既然我们为hosts做贡献，既然我们还待在这个国家，又何来的“责任”可言？

**Comment by denglj** [comment]
1. 并没要求谁道歉，我根本不知道是谁删的。
2. 百度贴吧不正当的商业化运营问题确实与技术无直接关系。
3. hosts文件彻底的只是一个操作系统用于存储IP和主机的映射关系，DNS技术的前身。它哪里敏感？是你们敏感了。
4. 关注大事，不一定非要在技术社区，一个以源码分享为主导的社区来讨论。
    能在这里看到你们讨论此类事情的人，在对待某些问题上，都差不多的价值取向。一个说，是不是这样，另一个举点例子说，嗯是这样。意义何在呢？还不如回去给自己的三姑六婆七舅八爷的手机浏览器默认搜索引擎换成必应之类的。还不如在百度贴吧里去写点真材实料的帖子告诉小白哪里的资源更好。
5. 你们谈过了，被坑的更多的是“不知中国特色国情”的用百度贴吧，百度知道之类的小白，然而，这里聚集的主流是他们吗？所以要让他们知道什么信息，比如你有没有什么平台，是不是某群，某吧群发点私信更精准更快更有影响力？
6. 人生轮回，世事往复，本就是那样，总有一波又一波的人会去做相同的不论是好的还是坏的事。难道在github上说了，就不会有小白前仆后继地被坑吗？
7. hosts 这套技术，已经很成熟了，几乎没有改进的余地，不需要人做贡献。对于让墙内的人更方便地访问互联网，诸位可以做些什么的，也是正在做的。不怕担责任，那么牵头做一个类似“大X元”之类的平台岂不是影响力更大。
8. github的issue是用于给项目源码提出改善建议和反馈问题的。issue的评论区，不是网易新闻、腾讯新闻、凤凰网、新浪新闻、强国论坛、YouTube、Nytimes、Reuters 这类的评论区，还是区分开为好。

**Comment by aofall** [comment]
说是没有什么可改进的
实际上我还可以给某些网站做加速（比如live.com 、 steam）， 更改使用错误的ip 
但是因为这个项目太乱我看不下去就一直没动手
我倒是想知道贴吧上央视有什么敏感的，作死就会死，这不是再正常的了嘛。

**Comment by racaljk** [comment]
@andytimes  唔..实际上我指的是囿于当前互联网环境说百度药丸无异作末日预言，结果是百度运营得好好的。说到底还是国内搜索市场被百度几乎垄断，其他产品缺乏竞争力。

**Comment by racaljk** [comment]
@K-Guan  "在SO，有个专门的说法叫“Noise（噪音）"

noise可不是他们的专用

**Comment by denglj** [comment]
@racaljk 不愧作为此项目的主要贡献者，更明白事理，在下佩服。源码社区就该以源码为主讨论其技术相关问题，而在这里讨论时政话题实属Github之噪音。 

若此处都理所当然成为可以讨论“时政”话题的避风港，那Github的意义又何在。类比起来岂不是SO上也可以提提这类问题，SO能容忍这类话题吗？ Github 和SO都被这种内容所染的话，哪里还有技术净地。点开最下方的“Terms” 可以看到，里面写的很清楚每个人应该为自己在github上所发表的内容付什么责任，哪些内容是Github禁止的。

虽然Github条款里写明了规矩，但并未得到强制执行，Github的用户群体也不需要被强制监管的。作为Github的用户应承担起使之发展越来越好的责任。**为技术保留一片净地吧，为别人，也为自己。**

此网页已截图存留，用于联系Github提改进内容质量的建议。也希Github能早日用上 “Noise（噪音）”  this kind（这种）mechanism（机制）。为广大技术人员提供更好的技术交流环境。

**Comment by andytimes** [comment]
@denglj 您的这番话看似说的是
> 作为Github的用户应承担起使之发展越来越好的责任。

实际不就是在说我开的这个 Issue 污染你的眼了。我看你写了这么大一堆也挺累的，你这样没事找事是不是吃饱了撑的。

我一开始关了 Issue 是因为觉得会影响别人心情，这里很多人都是挺聊的来的朋友了，喜欢就讨论，不喜欢也没有强求点进来。客观理性是很好，但人不能没有人情味。既然现在有朋友想讨论了，继续讨论有何不可。

没有人能要求别人做的一切事都是正确的，而且我不觉得开这个 Issue 有什么错的，你截图也实在没必要，非要影响你自己的心情又何必。

影响您的心情实在抱歉，把项目的 Notifications 设置成 Ignore 就不会收到这些内容了。看到自己不能接收的东西就反驳实在没必要。
另外，多说无益，欢迎贡献 hosts 规则

**Comment by K-Guan** [comment]
好了好了，所以呢？为了这么点小事，就吵起来？

@andytimes 同身为Collaborator，还是注意下语气，冷静。

@denglj 我上面说过了，评论是我删的。

我不否认我有时做事会不征求他人的意见而武断行事。然而说截图什么的，好像是太过了点吧？
同样，愚以为，SO的政策并不能直接全部应用到Github来。我有一次看到一个Comment写：

> [...] If you don't know the answer to my question, just go away.

然后呢？我Flag这个评论为Offensive，然后评论迅速被删除。是不是，我们也可以将我们在这里所说的，也都Flag为Offensive（包括我的Comments）？

---------------------

我再重申一句，我不希望我们为这么一点小事而争吵。请不要继续下去了。
