### ISSUE TITLE
host tool的cpp无法编译，请问有没有编译好的exe文件

### ISSUE THREAD

**Issue by PowerOlive** [racaljk/hosts#177]
求你们那exe文件 我hozz不会用

**Comment by K-Guan** [comment]
Hozz用法并不难，具体可参考我写的评测：https://gist.github.com/K-Guan/baea864203036e226061

不会编译的话嘛……@racaljk 交给你了。

**Comment by racaljk** [comment]
使用qt5环境编译即可。

唔...我认为hozz已经简单易懂至极了吧...怎么会...

**Comment by K-Guan** [comment]
@racaljk Hozz的最大问题在于全英文，而且并没有一个 [**简明的（中文）使用说明**](https://gist.github.com/K-Guan/baea864203036e226061)。

**Comment by racaljk** [comment]
@K-Guan  ..这我也无解了

**Comment by Ignotus-CN** [comment]
亲测 Hozz 新版已有简体中文界面语言。

**Comment by K-Guan** [comment]
@Ignotus-CN 哦？那不错。 cc @racaljk ^

**Comment by PowerOlive** [comment]
qt5编译成功谢谢

**Comment by PowerOlive** [comment]
@racaljk 我擦，无法运行，vs2015怎么那么难弄。qt5creater坏了吗？请问你能不能发个exe，zhengyihan11a11@gmail.com

**Comment by andytimes** [comment]
@PowerOlive 目前，最好去用 VS 2013，VS 2015 太新了，很多库不兼容

比如，我以前用 SDL2 绘图，VS 2015 就要从源码编译 SDL2，还要修改部分源码才能编译通过。

**Comment by PowerOlive** [comment]
@andytimes ok

**Comment by PowerOlive** [comment]
zhenyihan is my small cert.
