### ISSUE TITLE
玩Youtube还是太麻烦了

### ISSUE THREAD

**Issue by OneNewLife** [racaljk/hosts#178]
想想办法怎么解决Youtube这个梗吧？不可能每次看都打开那个链接去看，太麻烦了

**Comment by imcaffrey** [comment]
https://github.com/racaljk/hosts/wiki/%E6%9B%B4%E6%94%B9hosts%E5%90%8E%E8%BF%98%E6%98%AF%E6%97%A0%E6%B3%95%E4%BD%BF%E7%94%A8Google,Facebook,Twitter%E7%AD%89%E6%9C%8D%E5%8A%A1%E6%80%8E%E4%B9%88%E5%8A%9E%EF%BC%9F

**Comment by OneNewLife** [comment]
请问你是看不懂人话么兄弟？都说了这样很麻烦

**Comment by racaljk** [comment]
即便如此你的话对于有心提醒你的人来说也是很不礼貌的

就hosts来说没有更简便的方法了

**Comment by imcaffrey** [comment]
现在hosts解决不了这个问题
你还要来玩youtube

看得懂人话的人自然知道是怎么回事咯

**Comment by OneNewLife** [comment]
好吧，请问那个Youtube的视频是什么原因无法加载？

**Comment by OneNewLife** [comment]
好吧，请问那个Youtube的视频是什么原因无法加载？

**Comment by illuspas** [comment]
https能解决youtube页面加载问题，但视频实际上是访问的
https://r3---sn-i3b7kn76.googlevideo.com/***** 
这一类规则很乱的二级域名上去，这个无法通过hosts匹配，

**Comment by OneNewLife** [comment]
好吧，谢了
