### ISSUE TITLE
怎样用你的代码来创建工程呀

### ISSUE THREAD

**Issue by nanmuyao** [racaljk/hosts#185]
我想使用您的代码来创建工程，如果可以的话希望您指导一下谢谢 QQ：1558249222

**Comment by K-Guan** [comment]
创建工程？什么工程？

**Comment by nanmuyao** [comment]
创建一个vs工程来运行你的代码

**Comment by K-Guan** [comment]
哦，你是说的hosts GUI管理工具吧？这你得问 @racaljk 。

**Comment by racaljk** [comment]
双击.pro文件

如果你有qtcreator ide的话

**Comment by wtry** [comment]
11天没更新了..以后还更新吗..?

**Comment by nanmuyao** [comment]
最近天朝又封了一次，现在的hosts已经不能用了

**Comment by nanmuyao** [comment]
十分感谢您的指导，我回去会试试下载个qtcreator，看看可不可以创建运行项目谢谢

**Comment by PowerOlive** [comment]
@nanmuyao 你编译好后能不能给我发一个，谢谢zhengyihan11a11@gmail.com编译不出啊。。。

**Comment by nanmuyao** [comment]
周末我会试一下，如果搞定的话我会给你发@PowerOlive

**Comment by nanmuyao** [comment]
我尝试了一下但是提示
Could not find qmake configuration file default.
Error while parsing file /Users/hanzhiqiang/Desktop/Han_WorkSpace/hosts/HostsTool/hosts_tool.pro. Giving up.
上网查了一下感觉是qt的自己的错误，需要个更高版本的qt不知道作者用的什么版本的qt@nanmuyao

**Comment by andytimes** [comment]
你是 win 还是 *nix 系统？

哦，是 win 下，这个我不太懂，你可以自行 Google 啊

http://www.kuqin.com/qtdocument/qmake-manual-2.html
你可以看看这个链接，不知道对你编译有没有用
