### ISSUE TITLE
how about adding 'dev.android.com' just as the short of 'developer.android.com' ?

### ISSUE THREAD

**Issue by imknown** [racaljk/hosts#194]
how about add the `dev.android.com` just as the short of url `developer.android.com` ?
now i manual redirect that to the final website above.

**Comment by K-Guan** [comment]
（英语不好就直接说中文嘛……）

Well, yeah. Seems that also works.

**Comment by imknown** [comment]
好, 谢谢

; ]

**Comment by racaljk** [comment]
可以添加
不过之前full URL的也需要保留

**Comment by andytimes** [comment]
我这里访问 http://dev.android.com 是直接重定向到
http://developer.android.com/index.html 这里的

**Comment by aofall** [comment]
@K-Guan 
220.255.2.153 dev.android.com

**Comment by imknown** [comment]
@andytimes 然而我这里 直接挂了
