### ISSUE TITLE
最新hosts Google仍不能使用

### ISSUE THREAD

**Issue by xuexin** [racaljk/hosts#195]
四川联通
网页一直打不开

    正在 Ping www.google.com [64.233.162.82] 具有 32 字节的数据:
    请求超时。
    请求超时。
    来自 64.233.162.82 的回复: 字节=32 时间=450ms TTL=41
    来自 64.233.162.82 的回复: 字节=32 时间=452ms TTL=41

**Comment by K-Guan** [comment]
山东电信，还是可以打开的。

**Comment by xuexin** [comment]
那就纠结了....我先挂着代理吧~~

**Comment by sjtu-lyj** [comment]
问一下，现在哪个免费的vpn可用？谢谢

**Comment by xuexin** [comment]
现在可以正常访问了
@K-Guan

**Comment by K-Guan** [comment]
@xuexin http://shouldiblamecaching.com/
