### ISSUE TITLE
可以添加 twitch.tv 的 hosts 嗎

### ISSUE THREAD

**Issue by Garfield550** [racaljk/hosts#197]
希望看 twitch 的時候可以快一點，不過不清楚 twitch 的 CDN 是不是對尋找 ip 產生影響

**Comment by nxtreaming** [comment]
twitch.tv 没有被block, 不可能被添加。

**Comment by Garfield550** [comment]
说的有道理

**Comment by Garfield550** [comment]
询问一个技术问题。
如果一个域名对应多个 IP ，但 Hosts 都是 1 域名对应 1 IP 的，那么这怎么做呢？
比如下表的 streams.twitch.tv ，流式视频网站是不是不好做呢？

----------

| URL | IP |
------------ | ------------
|www-cdn.jtvnw.net | 8.254.194.140|
|www.twitch.tv | 8.254.243.221|
|web-cdn.ttvnw.net | 120.52.73.136 120.52.73.138 120.52.73.135	120.52.73.137 120.52.73.139|
|video31.lax01.hls.ttvnw.net | 199.9.254.137|
|video30.lax01.hls.ttvnw.net | 199.9.254.140|
|twitchmediagroup.com|198.185.159.144|
|twitch.tv|192.16.71.180 192.16.71.189 192.16.71.168|
|telegraph.twitch.tv|199.9.252.25 199.9.249.207 199.9.248.103	199.9.249.242	199.9.252.9	199.9.253.7	199.9.251.181	199.9.251.183|
|streams.twitch.tv|54.69.231.84	54.149.206.252	54.201.71.218	52.26.206.34	52.24.224.122	52.89.218.38|
|static-cdn.jtvnw.net|8.254.194.140|
|spade.twitch.tv|52.32.67.130 52.33.100.91 52.34.169.195 52.26.216.131	52.26.11.124	52.35.188.194 52.25.15.142 52.33.184.222|
|s.jtvnw.net|8.254.194.140|
|player.twitch.tv|54.192.116.107|
|music.twitch.tv|174.143.139.219|
|minixperiment.twitch.tv|205.128.88.253|
|help.twitch.tv|50.18.63.159|
|countess.twitch.tv|54.68.183.197	54.149.180.1|
|blog.twitch.tv|174.143.139.219|
|api.twitch.tv|52.24.43.31|

**Comment by amphineko** [comment]
@Garfield550 As the answer to the question mentioned in this following page, assigning multiple addresses to one host is not supported: [linux - Assign multiple IPs to 1 Entry in hosts file - Server Fault](http://serverfault.com/questions/429839/assign-multiple-ips-to-1-entry-in-hosts-file/)

**Comment by aofall** [comment]
可以，但twitch的子域太多了，加入不现实
而且仅限联通和移动铁通的用户，电信因为没有发现缓存服务器没法玩

**Comment by K-Guan** [comment]
@aofall 所以到底加不加呢？

**Comment by aofall** [comment]
不加
1.没有被屏蔽，只是国内直连速度很慢
2.不同运营商要用的IP不同，而且电信无法加速

**Comment by K-Guan** [comment]
@aofall 所以早说嘛。
