### ISSUE TITLE
彻底整顿README和Wiki计划

### ISSUE THREAD

**Issue by K-Guan** [racaljk/hosts#198]
我也觉得，只是整理下主目录下的README有些不够完美。所以我打算彻底整理下Wiki和README。如 #192 ，接下来，我会对每个Wiki page进行更改，以及审核每个README。

我的目标是：

> 让所有的帮助文档更明了、清晰。删去无用内容; 修改过时内容; 强调重要内容。

如果大家有什么疑问或意见，欢迎在本Issue中说明或在相对应的Commit中。

-------------------------------------

目前已经完成的步骤：

1. From 0b32846, to e28d492.

    > 主要是将我们所有的Hosts tools放到一个目录下，另外用README代替Wiki page。

2. From [`a292136`](https://github.com/racaljk/hosts/wiki/%E6%AC%A2%E8%BF%8E%E6%9D%A5%E5%88%B0%E6%9C%AC%E9%A1%B9%E7%9B%AE%E7%9A%84Wiki%E9%A1%B5%E9%9D%A2%EF%BC%81/a29213629cfd8c3742165da4e6b9c50a3bc27f82), to [`9ebaf04`](https://github.com/racaljk/hosts/wiki/%E6%AC%A2%E8%BF%8E%E6%9D%A5%E5%88%B0%E6%9C%AC%E9%A1%B9%E7%9B%AE%E7%9A%84Wiki%E9%A1%B5%E9%9D%A2%EF%BC%81/9ebaf04a367482c4396d5b38e28a43ae22491c06) (Wiki page).

    > 重新整理、布局Wiki的Main page，部分文章待补充。

**Comment by K-Guan** [comment]
cc @racaljk

**Comment by racaljk** [comment]
on your side

**Comment by K-Guan** [comment]
Thanks

**Comment by imcaffrey** [comment]
:+1:

**Comment by Ignotus-CN** [comment]
支持。

**Comment by sjtu-lyj** [comment]
支持。

**Comment by K-Guan** [comment]
感谢各位的支持。因为新年临近嘛，我的进展可能会有些缓慢。我计划在两周内基本完成，最晚一个月内全部完善。

**Comment by blue840357737** [comment]
终于让我在这里逮到你了哈哈

**Comment by idvr** [comment]
blue840357737  是哪位大神？

**Comment by G-BlueSummer** [comment]
好吧Guanrenfu你贴吧也不上总算让我在这里逮到你了哈哈#(手动滑稽)

**Comment by aofall** [comment]
https://github.com/dmtspoint/OpenGG/blob/master/Hall-of-shame.md

要不要考虑这个类似的东西，你要说从哪找？百度上搜索Google hosts ，第一页都是。统统是转载不注明来源的

**Comment by imcaffrey** [comment]
@aofall 滋磁

我看laod还在那号召捐款真是被他恶心到了

**Comment by K-Guan** [comment]
@G-BlueSummer 哦，原来是你呀。好久不见。

**Comment by K-Guan** [comment]
@aofall *falls of the chair*

**Comment by coolrc136** [comment]
@K-Guan   还是不要这样，laod的那个google和咱们的ip不同，我把google换成了laod的ip能用，这个不能用。不知道是不是他自己找的。而且人家也注明原作者了，就是要捐款有点恶心。

**Comment by Ignotus-CN** [comment]
@coolrc136 这种行为已经违反了 CC BY-NC-SA 4.0 的“非商业性使用”条款。

**Comment by aofall** [comment]
所谓ip不同根本就是个笑话
64.233.162.0/24 我在这里说过N次了，谁都可以下载然后批量替换
这段IP是谷歌俄罗斯的，要绕道欧洲然后才去俄罗斯，丢包比较严重
Ps:他的站要打的话很简单，但他用的是虚拟主机，我如果打了，会影响到同一台机器上的其他人

**Comment by coolrc136** [comment]
好吧。。。

**Comment by K-Guan** [comment]
@Ignotus-CN 反正呀，你就是去告也没人理你。在国内哪儿还有个版权一说。更何况呢，我们的hosts本来就是“国家禁止产品”。

**Comment by Ignotus-CN** [comment]
@K-Guan 强调一下 laod 的侵权罢了。毕竟不大可能让那家伙撤下广告停止要求捐款。

**Comment by aofall** [comment]
如果不管，笑话永远只是个笑话
那个OpenGG是Chrome上一款屏蔽视频广告的扩展，但服务器资源被人盗用后由于流量过大而下线了
后来就有了耻辱柱这一东西，由于博客被DDoS，他便把扩展源码连通耻辱柱一同搬到Github上
虽然说他现在删除了整个repo，但因为fork还是存在。
当然，这些盗源码盗服务器资源的人最后还是有道歉的。
我想说：如果不行动不追究，那么在中国谈License永远只是个笑话

**Comment by K-Guan** [comment]
@aofall 那么你的想法是？

**Comment by andytimes** [comment]
@K-Guan 我也来支持下。
能把 README 写得简洁明了，对代码维护是大有脾益的。所以，这是件利人利己之事

**Comment by andytimes** [comment]
@coolrc136 Google 不能用，是因为我 push 了一个错误 IP 上来。其实，缘由是我觉得 64.233.162.0/24 速度太慢，原本这里用的是 64.233.162.82 这个 IP


hosts 文件用的授权是 CC BY-NC-SA 4.0  https://creativecommons.org/licenses/by-nc-nd/4.0/deed.zh 

简单来说就是 hosts 文件要署名，非商业性使用，禁止演绎

捐款之类的倒不是商业行为，但是我刚刚看了 laod.cn 的 hosts ，里面加入了他的博客地址，这就是 **演绎** 了 hosts 文件，算是侵权了。

喜欢违规转载的人，内心是没有雨伞道德的
 (附上一篇我个人很喜欢的文章 《论雨伞道德》 http://site.douban.com/247757/widget/notes/17929589/note/475763036/#!/i!/ckDefault )

程序员处事态度是对事不对人的。
你就是宇宙级的好人，做违规转载之类的事情，也是不道德的。

**Comment by andytimes** [comment]
@K-Guan 对了，今天我更新 Android 上的 busybox ，我看到里面自带了 dos2unix ，记得 @aofall 说过
> 为什么不用 dos2unix

你可以把考虑 README 里面的 Notepad++ 换掉，dos2unix 用起来更方便。只要能装 busybox 的系统都能用 dos2unix

**Comment by K-Guan** [comment]
@andytimes 

```
kevin@Arch ~> uname -a
Linux Arch 4.3.3-3-ARCH #1 SMP PREEMPT Wed Jan 20 08:12:23 CET 2016 x86_64 GNU/Linux
kevin@Arch ~> dos2unix
fish: Unknown command 'dos2unix'
```

好吧我还是可以使用`pacman`安装的。

实际呢，我们的Hosts可以直接在我的Arch Linux上使用。如果是换行符是Win的换行符的话在Vim中会显示类似于`^M`之类的东东的。

我并不知道是怎么回事，也并未在其他系统上测试，所以不敢妄言。可是我认为，如果有必要的话，一行命令应该是可以解决的。不管是用`sed`还是Python还是其他的什么工具的。

**Comment by andytimes** [comment]
@K-Guan vim 显示 ^M 就是 win 换行符造成的。

我用过的一些 Linux 发行版都是自带 busybox 的，里面一般都有 dos2unix ，ArchLinux 我没用过，不知道有没有自带 busybox

sed 能替换换行符，只不过略微复杂，py 肯定也能实现。
既然有专门的工具，还是用专门的工具最好。

**Comment by coolrc136** [comment]
sed -i 's/^M$/^$/g' hosts

**Comment by andytimes** [comment]
@K-Guan vim 显示 ^M 就是 win 换行符造成的。

我用过的一些 Linux 发行版都是自带 busybox 的，里面一般都有 dos2unix ，ArchLinux 我没用过，不知道有没有自带 busybox

sed 能替换换行符，只不过略微复杂，py 肯定也能实现。
既然有专门的工具，还是用专门的工具最好。

**Comment by coolrc136** [comment]
额，这个好像不行

**Comment by Ignotus-CN** [comment]
@andytimes License 链接给错了……本项目使用的 CC BY-NC-SA 4.0 是署名-非商业性使用-相同方式共享，不是禁止演绎。

**Comment by coolrc136** [comment]
sed -e 's/^M//'g hosts > hosts

**Comment by coolrc136** [comment]
^M  != ^+M, 而是先按CTRL+V,接着按CTRL+SHIFT+M

**Comment by andytimes** [comment]
@Ignotus-CN 感谢指正，已修改。

**Comment by andytimes** [comment]
@coolrc136 反正我是不会用 sed 替换换行符的，用 tr  都不会用它的。刚刚搜了一下相关内容
http://www.cyberciti.biz/faq/howto-unix-linux-convert-dos-newlines-cr-lf-unix-text-format/

@K-Guan

**Comment by K-Guan** [comment]
@andytimes 唉？`tr`好像挺方便的哦。我之前专门学过`sed`，所以咯。

Arch好像确实不自带`busybox`，但是dos2unix可以直接安装的。

**Comment by K-Guan** [comment]
@andytimes 另外，laod到底是不是侵权？

**Comment by K-Guan** [comment]
> The new update: **Clear the wiki/README stage 2**

@aofall @andytimes and someone else: 那篇“hosts翻墙原理”你们谁写？我对这方面虽然了解，但是毕竟懂的少。对了，顺便欢迎完善我的Wiki。

**Comment by imcaffrey** [comment]
@K-Guan 我认为是
现在怎样我不知道
但是有一段时间它是直接全文复制过去当成自己的
而且号召给他捐款是始终存在的

**Comment by K-Guan** [comment]
@imcaffrey  #205。 我希望各位可以删掉Comments然后在那边再发一次。毕竟本issue是有关整顿README & Wiki的，不是侵权相关的。

**Comment by andytimes** [comment]
@K-Guan 没在这儿写过 wiki，我对 Network 方面知识也不是很懂。

**Comment by K-Guan** [comment]
@andytimes 哦，没问题。大不了我想办法。

**Comment by K-Guan** [comment]
> The new update: **Clear the wiki/README stage 3+4+5+6....**

总之基本整合了大部分的 Wiki pages 和 README 中可以整合的内容了。基本再努力两天这个计划就可以完成了。

**Comment by K-Guan** [comment]
感谢 @dasuan [更新了 Wiki 的链接](https://github.com/racaljk/hosts/wiki/Home/_compare/68488a3%5E...68488a3)。既然这样，我的计划也就基本是完成了。我以后会继续更新 FAQ ，也欢迎大家踊跃提交更新！
