### ISSUE TITLE
貌似 *.google.com SSL证书有问题啊

### ISSUE THREAD

**Issue by xixilive** [racaljk/hosts#199]
禁用`/etc/hosts`，改用VPN则一切正常。

> Commit: 7fca0f645f2fbec360dd493303e9115c6cfc781e

**Comment by tp4azo1** [comment]
Your connection is not secure

The owner of gmail.com has configured their website improperly. To protect your information from being stolen, Firefox Developer Edition has not connected to this website.

This site uses HTTP Strict Transport Security (HSTS) to specify that Firefox Developer Edition only connect to it securely. As a result, it is not possible to add an exception for this certificate.

**Comment by p0mp0k0** [comment]
好像SSL连接建立不了，更新andorid SDK的时候dl.google.com连接不能成功，提示的就是SSL的证书有问题，无法建立SSL连接
