### ISSUE TITLE
issue-100

### ISSUE THREAD

**Issue by hualishiri** [racaljk/hosts#2]
google ip was valid.

**Comment by racaljk** [comment]
try to use https://github.com/LGA1150/Acrylated-imouto.host/blob/master/AcrylicHosts.txt

**Comment by hualishiri** [comment]
Thank you so much, it really does work.

On Tue, Jan 27, 2015 at 12:42 PM, Cthulhu <notifications@github.com> wrote:

> try to use
> https://github.com/LGA1150/Acrylated-imouto.host/blob/master/AcrylicHosts.txt
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/racaljk/hosts/issues/2#issuecomment-71589008>.
>



-- 
            yours sincerely

(曹丙章)Bingzhang Cao
Office: Room 409, Building B,Wuhan National Laboratory for Optoelectronics,
Huazhong University of Sicence and Technology(HUST)
Email: h <caobingzhang@hust.edu.cn>ualishiri@gmail.com
Affiliation: School of Computer Science and Technology(CS)
Mobile Phone: 13296625543
