### ISSUE TITLE
play商店无法访问

### ISSUE THREAD

**Issue by imbear** [racaljk/hosts#200]
android手机
twitter、facebook、维基，还有google的搜索、邮件、plus都可以使用，就是play商店无法使用，即便开了代理也不行，提示“请检查网络连接”，很奇怪

不知play商店相关的域名是哪些，我想手工把它先剔除了再说

**Comment by imbear** [comment]
刚才看了一下readme，貌似是因为【GooglePlay这个App不支持SNI】

难道只能在使用商店时再临时把hosts给改回来？还真是麻烦

**Comment by aofall** [comment]
除非找到对应证书的IP，不然没法解决
@K-Guan 可以close issue了
