### ISSUE TITLE
可否同步生成 dnsmasq 配置文件？

### ISSUE THREAD

**Issue by Undirectlookable** [racaljk/hosts#203]
利用 dnsmsaq  的配置文件，hosts 可以得到精简，比如
```
address=/.ytimg.com/1.2.3.4
address=/.google.com/1.2.3.4
```
这样所有主域及子域都会生效，在路由器上部署也比较方便。

写了一段 python 代码进行转换，但是没有合并子域名的功能：

```python
#!/usr/bin/env python
# ^3^ encoding: utf-8 ^3^

import re
import urllib2

print 'fetching gfw hosts...'
url = 'https://github.com/racaljk/hosts/raw/master/hosts'
res = urllib2.urlopen(url).read()
lines = res.splitlines(True)

filename = 'gfw-hosts-dnsmasq.conf'
conf = open(filename, 'w')
conf.write('# Dnsmasq Format\n\n\n')

ippat = re.compile('^\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}$')
dmpat = re.compile('^[a-zA-Z\d-]{,63}(\.[a-zA-Z\d-]{,63})*$')

print 'parsing file...'
for line in lines:
    line = line.strip()
    if line.startswith('#'):
        conf.write(line + "\n")
    else:
        if len(line) > 0:
            if line.find('localhost') < 0 and line.find('255.255.255.255') < 0:
                (ip, dm) = line.split()[:2]
                if ippat.match(ip) and dmpat.match(dm):
                    conf.write('address=/' + dm + '/' + ip + "\n")
        else:
            conf.write("\n")

conf.close()
print 'done, please use ' + filename
```

**Comment by K-Guan** [comment]
#135

**Comment by K-Guan** [comment]
对了，建议：

    #!/usr/bin/env python
    # ^3^ encoding: utf-8 ^3^

    import re
    import requests

    print('fetching gfw hosts...')
    url = 'https://github.com/racaljk/hosts/raw/master/hosts'
    res = requests.get(url).text

    lines = res.splitlines()

    filename = 'gfw-hosts-dnsmasq.conf'

    with open(filename, 'w') as f:
        f.write('# Dnsmasq Format\n\n\n')

        ippat = re.compile('\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}')
        dmpat = re.compile('[a-zA-Z\d-]{,63}(\.[a-zA-Z\d-]{,63})*')

        print('parsing file...')

        for line in lines:
            if line.startswith('#'):
                f.write(line + "\n")
            else:
                if line:
                    if all(i not in line for i in ('localhost', '255.255.255.255')):
                        (ip, dm) = line.split()[:2]
                        if ippat.match(ip) and dmpat.match(dm):
                            f.write('address=/{}/{}\n'.format(dm, ip))
                else:
                    f.write("\n")

    print('done, please use ' + filename)
