### ISSUE TITLE
有关hosts侵权一事的讨论

### ISSUE THREAD

**Issue by K-Guan** [racaljk/hosts#205]
> *Please don't "spam" my #198 as well.*

列位有关某些人对于我们hosts的“复制并发表却不表明原作者，或构成侵权一事”的问题还是在这里讨论吧。

**Comment by imcaffrey** [comment]
@K-Guan 我认为laod是侵权的
现在怎样我不知道
但是有一段时间它是直接全文复制过去当成自己的
而且号召给他捐款是始终存在的

**Comment by ycraurora** [comment]
@K-Guan 的确如此，BC一比较就知晓了，完全就是拿过去改了改google ip
博客中只字未提racaljk

**Comment by Ignotus-CN** [comment]
说 laod 没有侵权未免太过绝对，我认为 laod 连“署名”都没有合格履行。CC BY-NC-SA 4.0 要求给予“适当表彰”并“说明是否进行更改”，laod 在其发布页面则完全未提及原项目，俨然自己成了创作者。

laod 在 hosts 文件里保留了 license 和原项目链接，这倒是比百度搜索首页其他转载者厚道一些。然并×，根本没有人会看那个

**Comment by K-Guan** [comment]
@Ignotus-CN 唉？laod还在hosts文件里保留了本项目的链接？

**Comment by imcaffrey** [comment]
@K-Guan 保留了

我们就是感觉它要捐款而且宣称是自己更新的好多次很恶心

FYI：laod.cn/hosts/2016-google-hosts.html

**Comment by K-Guan** [comment]
@imcaffrey 我的天，README都直接抄过去了……

建议：README改成“为打击严重‘盗窃’问题，暂时停止更新一个月”。And then...别当真我开玩笑的。

**Comment by guqikay** [comment]
我是在他的介绍里看到说是同步这里的，然后就直接过来了。现在他好像又删掉了

**Comment by naodai** [comment]
晕，看了这个我才知道laod和这个不是一回事的呀，我是通过laod上的注释，追到这的，当时还挺疑惑的呢，现在也明了。
以前有比较多的说明，现在刚看了下，如下

> # Copyright (c) 2014-2016, racaljk.
# https://github.com/racaljk/hosts
# Last updated: 2016-02-01

# This work is licensed under a CC BY-NC-SA 4.0 International License.
# https://creativecommons.org/licenses/by-nc-sa/4.0/

# http://laod.cn/hosts/2016-google-hosts.html

# Localhost (DO NOT REMOVE)

**Comment by K-Guan** [comment]
@naodai 哦？感谢提供。话说laod的更新还是很快的嘛。这看来是我们最近才换的新的Head：#196

**Comment by imcaffrey** [comment]
@K-Guan +1最开始不知道Github上有hosts
后来用了laod的近半年发现前面是这个项目的链接，就直接过来了= =顿时感觉好恶心

**Comment by K-Guan** [comment]
@imcaffrey 听起来到也不错嘛，反倒顺便给咱们宣传了。

**Comment by CNMan** [comment]
拿别人的劳动成果获取不明真相的群众捐赠的行为很令人不齿

有人愿意一起维护unbound版hosts么？
https://github.com/CNMan/unbound.conf

**Comment by imcaffrey** [comment]
@K-Guan 然而尴尬的是很少有人会去看hosts内容吧，反而是当作他自己搞的，把他给捧起来了

突然想起来一段话：https://github.com/shadowsocks/shadowsocks-windows/issues/293#issuecomment-132253168

**Comment by K-Guan** [comment]
@CNMan 这玩意……听上去好麻烦……

**Comment by CNMan** [comment]
@K-Guan 因为用了dnscrypt，能保证解析到的IP都是正确的，从根本上解决了DNS污染和劫持。
unbound.local-zone.hosts.conf主要解决IP被墙的问题，其次是本地解析这些域名，加快速度
unbound官方也有hosts转localzone的perl脚本
http://unbound.nlnetlabs.nl/svn/trunk/contrib/build-unbound-localzone-from-hosts.pl

**Comment by K-Guan** [comment]
@imcaffrey （嗯……这人头像很“眼熟”嘛……）

有点长，就不看了。反正内容我是可以想象的。不过……也对也对。可是现在没有解决方案呀。

**Comment by K-Guan** [comment]
@CNMan 嗯……高端。就是没有hosts方便。

**Comment by Usb233** [comment]
话说他的页面现在加了这么一句了http://laod.cn/hosts/2016-google-hosts.html

**Comment by aofall** [comment]
昨天已经有小分队跑去跟laod说话了……已经改了，就不要再计较了。
百度首页上还有其他的，你们别光顾着找laod啊

**Comment by imcaffrey** [comment]
@aofall 看到你了

很奇怪如果我把这个项目的链接一发出来就会被删评论

@K-Guan laod提到你啦

**Comment by K-Guan** [comment]
@aofall 

1. 倒是先说声呀……
2. 列个单子如何？

**Comment by K-Guan** [comment]
@imcaffrey （毕竟Collaborator，提一提是应该的，应该的 :P）看到诸位在那边的评论了，感谢大家的努力。

@aofall 语气尽量“和蔼”些。毕竟是在讨论，又在“别人的地盘”。别总拿老D当敌人看。

**Comment by racaljk** [comment]
我更新了版权说明，你们看看还有什么需要增删的

**Comment by gisphm** [comment]
@racaljk 弱弱地提一句，感觉标点用得不规范，中英文混用了。

**Comment by gisphm** [comment]
@racaljk 这个可以做个参考。。[中文文案排版指北](https://github.com/sparanoid/chinese-copywriting-guidelines)

**Comment by K-Guan** [comment]
@gisphm 我的更新如何？

**Comment by racaljk** [comment]
@gisphm 虽然很规范但是太麻烦..

**Comment by K-Guan** [comment]
@gisphm 那个“指北”是个好东西。对了，lol：

> 使用 gｲんĤЦ8 登錄

**Comment by K-Guan** [comment]
@racaljk 习惯就好了。我觉得文章规范的话对于可读性是很有帮助的。

**Comment by aofall** [comment]
1.那个小分队不是我，我也管不了，还是让 官人妇 你管吧（滑稽
2.
>http://blog.my-eclipse.cn/host-google.html
http://guanhuo.wang/?p=42
http://www.findspace.name/res/72

这只是随手一搜的结果。其中还有在贴吧里水过的吧友，看见他们这么做实在是难过啊。

**Comment by gisphm** [comment]
@racaljk 不错。。对于有强迫症的我来说，很好看了。。:smiley:

@K-Guan 也是在写东西的过程发现的，用 Vim 的话还有 [PanGu.vim](https://github.com/hotoo/pangu.vim) 直接用来规范化。

**Comment by K-Guan** [comment]
@gisphm 用不到啦。我一般只用Vim写代码，而且我本身就有让文章规范化的习惯。

**Comment by K-Guan** [comment]
@aofall 去，少叫我这个垃圾外号。（:P）

**Comment by imcaffrey** [comment]
有些地区Github被墙了………………所以才会有需求到别的地方找

**Comment by Ignotus-CN** [comment]
@imcaffrey 并不是墙的问题，而是百度搜索引擎不收录 GitHub 项目。

**Comment by imcaffrey** [comment]
@Ignotus-CN 你说的也是原因…………我只是突然发现好多人和我说打不开Github………………

**Comment by outnnn** [comment]
哈哈，要ip可以找我，我有一些

**Comment by redapple0204** [comment]
@imcaffrey  真的，没法打开，现在要用vpn才行了

**Comment by imcaffrey** [comment]
@outnnn what?
@redapple0204 hosts文件里有Github的规则，于是造了个<del>用来上Github的</del>coding上的镜像

**Comment by outnnn** [comment]
@imcaffrey  他搞捐赠就是不对的，我ping到一些可用的ip
172.217.20.67
172.217.19.110

**Comment by imcaffrey** [comment]
@outnnn Thx....

**Comment by byhongda** [comment]
@imcaffrey 有没有跟老D直接沟通过,感觉他是那种职业的站长. 基本逻辑就是集聚用户,然后刷流量赚一笔到模式.  他的侧重点在运营上,建个门户官网,然后将开源社区到资源拿去盈利,至于基本道德甚至合法性都不用考虑太多.
建议你们直接沟通下,看能不能把你们的贡献特别提出来,而不是"向所有的贡献者致敬"一句完事了.

**Comment by imcaffrey** [comment]
@byhongda 感谢，我认为**现在**laod处理得还是比较到位的，百度上的更多无名转载者才是令人心寒啊

**Comment by lrinQVQ** [comment]
== 不知道为什么搜到了这个issues 不过2333用这个项目强行修改为自己的挺多的 一搜一堆Orz

**Comment by 2Broear** [comment]
没事就好
