### ISSUE TITLE
伪基百科无法访问？

### ISSUE THREAD

**Issue by redapple0204** [racaljk/hosts#206]
英文版可以，但这是中文就不行了

**Comment by K-Guan** [comment]
“伪基” or “维基”？

**Comment by Ignotus-CN** [comment]
@K-Guan http://cn.uncyclopedia.wikia.com http://uncyclopedia.tw

**Comment by K-Guan** [comment]
@Ignotus-CN 哦，这个我知道。只是因为我们并没有提供此网站的hosts，好奇是不是打错了。

**Comment by redapple0204** [comment]
@K-Guan  嗯，两个都无法访问耶

**Comment by aofall** [comment]
第一个没问题，只是图片无法加载
第二个被Reset，需要使用https打开
如果不行自己加
162.159.208.33 uncyclopedia.tw
