### ISSUE TITLE
报告facebook又挂了。

### ISSUE THREAD

**Issue by wolfan** [racaljk/hosts#207]
早上起就不行了。
湖南联通

**Comment by racaljk** [comment]
常态,只要Google不挂问题都不大.

如果急着用Facebook可以考虑[使用shadowsocks](http://level.gq/code.php)(个人立场)
[`Invite code: 41YTMzMDYwN2Q3Njc5NmIzNWM2`]()

**Comment by LGA1150** [comment]
现在Facebook IP基本上见光死

**Comment by wolfan** [comment]
难道是因为帝吧的事？

**Comment by LGA1150** [comment]
一直都这样

**Comment by hwk603** [comment]
@racaljk 邀请码已无效
