### ISSUE TITLE
能否提供更多IP

### ISSUE THREAD

**Issue by idlesysman** [racaljk/hosts#21]
发现很多域名使用同一个IP，只要这个IP不可用，所有的都不能用了。
能否尽量保证不同域名，不同IP呢

**Comment by racaljk** [comment]
这些ip大都是软件跑出的，找到一个就share了，还真没什么精力跑多个ip给不同域名

**Comment by SMoUNiVeS** [comment]
目前的情况是，对于Google来说，能找到一个可用的IPv4地址已经是非常幸运的事情了…所以不要要求太多，过段时间也许会无限期停止更新，因为无IPv4地址可用了…
