### ISSUE TITLE
弱弱的问一句，这个是不是youtube能打开，却放不了视频？

### ISSUE THREAD

**Issue by WeihuaGu** [racaljk/hosts#210]
第一次用，youtube视频托动那个进度条有预览，可是放不了视频。

**Comment by imcaffrey** [comment]
是的
https://github.com/racaljk/hosts/wiki/%E6%9B%B4%E6%94%B9hosts%E5%90%8E%E8%BF%98%E6%98%AF%E6%97%A0%E6%B3%95%E4%BD%BF%E7%94%A8Google,Facebook,Twitter%E7%AD%89%E6%9C%8D%E5%8A%A1%E6%80%8E%E4%B9%88%E5%8A%9E%EF%BC%9F

**Comment by racaljk** [comment]
是的
