### ISSUE TITLE
现在hosts存在的问题

### ISSUE THREAD

**Issue by deeptcl** [racaljk/hosts#214]
该hosts能够正常访问google，但是为什么不能正常同步chrome的书签？以及在chrome中通过chrome自带的google服务将英文网页翻译为中文网页。原来提供的hosts后能用这两个功能的。

**Comment by imcaffrey** [comment]
辽宁电信可以同步的、可以翻译的
泥是不是设置有问题

**Comment by racaljk** [comment]
@imcaffrey 感谢长期的答疑。有没有兴趣加入collaborator帮助我们管理hosts project？

**Comment by andytimes** [comment]
建议在浏览器上重新登录 Google 帐号，如果还有问题，再具体分析

**Comment by Roller44** [comment]
发现在 Twitter 上打开不了大部分短链。


 

-------- Original message --------
Sender: Andy Deng <notifications@github.com>
Time: Sat 2/13 08:43
To: racaljk/hosts <hosts@noreply.github.com>
 Subject: Re: [hosts] 现在hosts存在的问题 (#214)

**Comment by imcaffrey** [comment]
@racaljk Been an honor, Thanks.

**Comment by LGA1150** [comment]
@Roller44 
没有强制HTTPS或目标网站被墙
