### ISSUE TITLE
是否可以将这个自动获取hosts的bat放到Host Tools 里？

### ISSUE THREAD

**Issue by redapple0204** [racaljk/hosts#215]
```
%1 %2 
ver|find "5.">nul&&goto :st 
mshta vbscript:createobject("shell.application").shellexecute("%~s0","goto :st","","runas",1)(window.close)&goto :eof 
:st 

copy "%~0" "%windir%\system32\" 
cls
@REM HostsGet Version0.2

@echo off
del %temp%\download.vbs > nul
cd /d %~dp0
echo 初始化中...

echo iLocal=LCase("c:\hosts") >> %temp%\download.vbs
echo iRemote=LCase("https://raw.githubusercontent.com/racaljk/hosts/master/hosts") >> %temp%\download.vbs

echo Set xPost=createObject("Microsoft.XMLHTTP") 'Set Post = CreateObject("Msxml2.XMLHTTP") >> %temp%\download.vbs
echo xPost.Open "GET",iRemote,0 >> %temp%\download.vbs
echo xPost.Send() >> %temp%\download.vbs
echo set sGet=createObject("ADODB.Stream") >> %temp%\download.vbs
echo sGet.Mode=3 >> %temp%\download.vbs
echo sGet.Type=1 >> %temp%\download.vbs
echo sGet.Open() >> %temp%\download.vbs
echo sGet.Write xPost.ResponseBody >> %temp%\download.vbs
echo sGet.SaveToFile iLocal,2 >> %temp%\download.vbs

echo 初始化完成...请稍后...
ping 127.0.0.1 > nul
echo 开始从github中下载hosts
%temp%\download.vbs
echo 请稍后...
del %temp%\download.vbs /s /q
ping 127.0.0.1 > nul
echo 正在备份原hosts...
move %windir%\system32\drivers\etc\hosts %windir%\
set filename=%date:~0,4%%date:~5,2%%date:~8,2%%time:~0,2%%time:~3,2%%time:~6,2%
ren %windir%\hosts %filename%.bak
echo %filename%.bak >> hostbak.txt

echo hosts文件已经备份到%windir%，名字为当前的时间，例如20160212182118.bak ，备份的文件名称保存在hostsbak.txt.

move c:\hosts %windir%\system32\drivers\etc\
echo hosts替换完成.
ipconfig /flushdns
echo 按任意键访问google.com.hk进行测试，如取消，请直接关闭本窗口
pause >nul
start https://www.google.com.hk
echo 已经帮你访问google.com.hk 如可以访问则替换成功.

echo 按任意键关闭
pause >nul
```

**Comment by imcaffrey** [comment]
:+1:

**Comment by redapple0204** [comment]
还有一些完整版本http://pan.baidu.com/s/1dDNEvRF

**Comment by redapple0204** [comment]
对不起，上面的搞错了，应该是这个
-----------代码开始--------

@echo 开始替换！

echo iLocal=LCase("c:\hosts") >> download.vbs
echo iRemote=LCase("https://raw.githubusercontent.com/racaljk/hosts/master/hosts") >> download.vbs

echo Set xPost=createObject("Microsoft.XMLHTTP") 'Set Post = CreateObject("Msxml2.XMLHTTP") >> download.vbs
echo xPost.Open "GET",iRemote,0 >> download.vbs
echo xPost.Send() >> download.vbs
echo set sGet=createObject("ADODB.Stream") >> download.vbs
echo sGet.Mode=3 >> download.vbs
echo sGet.Type=1 >> download.vbs
echo sGet.Open() >> download.vbs
echo sGet.Write xPost.ResponseBody >> download.vbs
echo sGet.SaveToFile iLocal,2 >> download.vbs
cd /d %~dp0
ping 127.0.0.1 > nul
 download.vbs


ping 127.0.0.1 > nul
ping 127.0.0.1 > nul

ping 127.0.0.1 > nul
move C:\WINDOWS\system32\drivers\etc\hosts c:\windows
set filename=%date:~0,4%%date:~5,2%%date:~8,2%%time:~0,2%%time:~3,2%%time:~6,2%
ren C:\windows\hosts %filename%.bak
@echo %filename%.bak >> hostbak.txt
pause
@echo hosts文件已经备份到c盘windows，名字为当前的时间，例如20160212182118.bak ，而且保存到了hostsbak.txt里

move c:\hosts C:\WINDOWS\system32\drivers\etc\
@echo hosts替换成功
ipconfig /flushdns
pause
start https://www.google.com.hk
-------------------代码结束--------------------

**Comment by qwerty258** [comment]
你要先fork本repo，然后加上你的下载，然后Pull requests到本repo的master branch。
@redapple0204

**Comment by redapple0204** [comment]
@qwerty258 请问是像现在这样吗

**Comment by imcaffrey** [comment]
@redapple0204 没有看到你开的PR

**Comment by redapple0204** [comment]
@imcaffrey  我无法开pr，按钮是灰的

**Comment by redapple0204** [comment]
@imcaffrey 请问这样可以了吗

**Comment by imcaffrey** [comment]
@redapple0204 你要在这个repo里开PR……不是你fork的那个

**Comment by K-Guan** [comment]
@redapple0204 Do some research, for example "How can I open a pull request on GitHub".

> 有关不能访问 https://raw.githubusercontent.com/racaljk/hosts/master/hosts ，应该是你的网络问题。挂 VPN 试试看？

**Comment by K-Guan** [comment]
@redapple0204 不过在此之前……你的新程序比起 [**我们现有的那个**](https://github.com/racaljk/hosts/blob/master/hosts_tools/scripts/script_tool_for_windows.bat) 有什么特别、改进的地方吗？

**Comment by redapple0204** [comment]
@K-Guan  我看了下以前的那个，好像并没有下载hosts，只是echo了项目的地址，只有备份功能，我自己执行了一下，在最后一步的时候出现了系统找不到指定的文件。的说法

**Comment by redapple0204** [comment]
@K-Guan  我看了下以前的那个，好像并没有下载hosts，只是echo了项目的地址，只有备份功能，我自己执行了一下，在最后一步的时候出现了系统找不到指定的文件。的说法

**Comment by qwerty258** [comment]
看了下你issue里的bat代码，居然用绝对路径来表示系统盘……遇上个逗比系统装D盘咋办。
“在最后一步的时候出现了系统找不到指定的文件”，这个问题能描述具体点么？
@redapple0204

**Comment by K-Guan** [comment]
@redapple0204 3嗯……我不懂 bat ，没有发言权。

**Comment by K-Guan** [comment]
@qwerty258 唉，这点有道理。我有一次装系统就给稀里糊涂的装到了D盘。话说，不是有“环境变量”么？

**Comment by lautis0503** [comment]
用%windir%这个环境变量就好了
@qwerty258  @redapple0204 @K-Guan

**Comment by K-Guan** [comment]
@redapple0204 不过虽然如此，我还是有几个问题（建议）要提的：

1. 既然已经用了 `@echo off` ，为何有些行还是以 `@` 开头呀？
2. 那些 `ping 127.0.0.1 > nul` 是干嘛用的？为什么要 ping 这个 127.0.0.1 呢？
3. 我发现你在使用 `echo` 和“重定向符 `>`”来创建 `download.vbs` ，难道 bat 没有 “heredoc” ?

**Comment by redapple0204** [comment]
@K-Guan 1.这个也可以省略·，ping 127.0.0.1 > nul是延时

**Comment by redapple0204** [comment]
@qwerty258 这个嘛我正在想办法修改

**Comment by K-Guan** [comment]
@lautis0503 嗯，这个我知道。

**Comment by K-Guan** [comment]
@redapple0204 仍然没有发言权。不过按照 ***Pythonic*** 的原则，**省略所有不必要的代码**。

**Comment by redapple0204** [comment]
@lautis0503 @K-Guan @qwerty258 修改了一下，听取了@lautis0503 的建议，@K-Guan 3.windows貌似没有heredoc

**Comment by K-Guan** [comment]
`@echo hosts文件已经备份到C:\windows`……这个……还需要修改才是。

**Comment by lizongzeshunshun** [comment]
我是 @redapple0204 的该bat协作者。我认为此bat应该分多文件，比如download.vbs应该单独为一个文件，不需要临时创建，否则对程序效率影响极大.

**Comment by K-Guan** [comment]
@lizongzeshunshun 唉？那你怎么不早点过来？欢迎！

对于此事，我倒是想……让用户使用脚本前一次下载两个文件……而目的只是自动备份和下载一个hosts……是不是有点麻烦了？

固然，我承认这样做比较好，可是这样确实不会影响程序效率，但是会影响用户的效率呀。与其如此，手动下载hosts、备份的功夫都有了。要知道，我们的小工具就是为了“方便用户”的。

本来，这就是个小程序。创建个文件、再删除。我觉得不会需要多用几秒。所以……啊，我也只是提个建议，你们自己商量着办吧。

**Comment by K-Guan** [comment]
对了，如果要创建这个 `download.vbs` 的话，我不建议在当前目录下。Windows 不是有 `%TEMP%` 吗？就是它了。

**Comment by redapple0204** [comment]
@K-Guan 这样子做还有一个坏处是，如果用户没有执行完bat（就是知识替换完hosts）关闭了本窗口，那么下次再执行会导致重复写入，vbs无法执行

**Comment by lizongzeshunshun** [comment]
@K-Guan 这个建议不错，可以改一下

**Comment by redapple0204** [comment]
@K-Guan 保存目录已经改成temp，前面的那些是获取管理员权限的（因为在vista以上的版本不用管理员无法替换），并且在xp，vista上测试成功

**Comment by K-Guan** [comment]
@redapple0204 你就不会先尝试删除该文件，再写入？

**Comment by imcaffrey** [comment]
@redapple0204 你这样一天 @ echo， 人家echo怎么想……

**Comment by redapple0204** [comment]
@imcaffrey 好吧.0

**Comment by redapple0204** [comment]
@K-Guan 这样一打开就提示找不到文件，用户还以为出错了呢，现在执行完文件还没有复制hosts就删除了

**Comment by lizongzeshunshun** [comment]
@redapple0204 好像可以通过`del %temp%\download.vbs >nul `来隐藏这个操作过程。还没测试过

**Comment by lizongzeshunshun** [comment]
搞定了，可以通过`del %temp%\download.vbs >nul 2>nul`来隐藏操作过程.

**Comment by redapple0204** [comment]
@lizongzeshunshun
好的

**Comment by K-Guan** [comment]
@lizongzeshunshun 没错没错。在 Linux 下，只需： `command 2&> /dev/null` 。

**Comment by redapple0204** [comment]
@K-Guan 原来如此啊
