### ISSUE TITLE
可否添加steam的hosts

### ISSUE THREAD

**Issue by G-BlueSummer** [racaljk/hosts#216]
😄

**Comment by 1670338677** [comment]
steam ke yi fang wen

2016-02-14 10:46 GMT+08:00 纯丶蓝Se <notifications@github.com>:

**Comment by imcaffrey** [comment]
@G-BlueSummer 辽宁电信可以访问

https://github.com/racaljk/hosts/pull/161

**Comment by G-BlueSummer** [comment]
访问是可以呀，但是很多人无法加载图片，据说被墙了

**Comment by aofall** [comment]
仅移动铁通及小运营商墙了
解决方法：换宽带

**Comment by Ignotus-CN** [comment]
@aofall 江苏移动 Steam 访问相当流畅……

**Comment by aofall** [comment]
cdn.akamai.steamstatic.com 会被Rst

**Comment by d-bluedreams** [comment]
表示自己也是移动宽带，一直也被图片显示不了问题烦扰，自从在github看到有hosts，我就下决心把手机和电脑上的浏览器全换了chrome，chrome有个插件HTTPS Everywhere，开启后就能显示图片了，然后发现steam客户端也能显示图片了（还没确定是不是steam直接调取了chrome里缓存的图片）

**Comment by imcaffrey** [comment]
@d-bluedreams 这意思是不是强制https就好了…………

**Comment by d-bluedreams** [comment]
@imcaffrey 是的，但是目前已知大部分国内浏览器不能使用chrome的HTTPS Everywhere插件。所以用其他浏览器还是无法显示图片。（我电脑现在三浏览器IE，搜狗，chrome。只有chrome可以，所以不清楚steam客户端是怎么能显示图片的）

**Comment by Ignotus-CN** [comment]
@d-bluedreams Chromium 内核浏览器貌似都可以通过访问 chrome://net-internals#hsts 并添加域名强制 HTTPS 访问，但应该无法在浏览器外奏效。我一直很疑惑为什么江苏移动 Steam 图片显示得好好的。

**Comment by d-bluedreams** [comment]
@imcaffrey 谷歌内核的搜狗试过不行。你那边好好的，应该是你附近这片区域有人向本地移动公司投诉，解禁了cdn.akamai.steamstatic.com ，虽然同属于移动铁通，但每个区域有每个区域自己的墙策略，这和移动手机卡分区一样的（江苏区，浙江区等，不同的区，给10086发指令短信也不一定对应的同功能）

**Comment by Ignotus-CN** [comment]
@d-bluedreams 大概是吧……

**Comment by imcaffrey** [comment]
我不是移动的…………这什么鬼阿

**Comment by CNMan** [comment]
有需求的自己添加啊
https://github.com/racaljk/hosts/commit/f119501cfc19be26e48ddf02f8ade96ec53a1308

**Comment by LGA1150** [comment]
http://steamcn.com/t162687-1-1

**Comment by aofall** [comment]
@LGA1150  发布在这就离内网限制不远了吧？那个广东移动的我这已经Forbidden了

**Comment by LGA1150** [comment]
@aofall 那个好像本来就不能用

**Comment by aofall** [comment]
现在已经不想再在这个repo里公布反代和ggc了，封的太快了

**Comment by G-BlueSummer** [comment]
@d-bluedreams chrome装了那个插件就可以了吗，为何chrome可以加载图片了，steam内置浏览器还是不行

**Comment by d-bluedreams** [comment]
@G-BlueSummer 是的。我这边steam客户端是能显示图片的，我也弄不清楚原因，上面也是猜测。你可以试试在所有的浏览器里都清空一次浏览器缓存。

**Comment by HengtianPan** [comment]
以前是有steam的hosts的，而且我维护过，因为我也有这个问题，后面之所以删掉了，是发现其实steam不能访问的问题主要是因为steam使用国外CDN访问慢的问题。
我尝试过清理缓存，但没有解决；改dns可以暂时的解决问题，但过一会就没有用了，最后我的解决方式是重装系统，然后问题就解决了。。。。。。。。。。

**Comment by aofall** [comment]
@K-Guan 这个也可以 close issue了
电信和联通是没有问题的，只有移动屏蔽了。

>https://v2ex.com/t/259865

至于那个122开头的ip是铁通的缓存服务器（现在移动和铁通在合并为中移铁通，所以才不会经过移动的墙中墙），如果加入的话原本打得开的电信联通会减速甚至打不开
