### ISSUE TITLE
在脚本里添加自动下载hosts是否有必要？

### ISSUE THREAD

**Issue by qwerty258** [racaljk/hosts#217]
一般来说来能玩GIT的，都是clone repo的，本来就带了hosts，再下载是多余的。
如果是独立发布的脚本，那是要下载功能。

**Comment by K-Guan** [comment]
参考下 #215 ？

**Comment by redapple0204** [comment]
建议要，要不怎么叫自动配置脚本

**Comment by lizongzeshunshun** [comment]
@redapple0204 同意。因为不一定所有用这个hosts的都会git.很多只是想fq的使用这个脚本会方便一些。
