### ISSUE TITLE
hosts_tools的README.md的一个错误

### ISSUE THREAD

**Issue by lizongzeshunshun** [racaljk/hosts#221]
hosts_tools的最后一栏贡献者貌似写反了.

> script_tool_for_windows.bat: Windows 环境下的 hosts 一键部署脚本，由 @SMoUNiVeS 贡献。
script_tool_for_linux.bash: Linux 环境下的 hosts 一键部署脚本，由 @redapple0204 与 @lizongzeshunshun 贡献。

这里写反了.

建议更改：

> script_tool_for_windows.bat: Windows 环境下的 hosts 一键部署脚本，由 @redapple0204 与@lizongzeshunshun贡献。
script_tool_for_linux.bash: Linux 环境下的 hosts 一键部署脚本，由@SMoUNiVeS贡献。

**Comment by K-Guan** [comment]
Ahhhhh, my bad. Changing...

**Comment by smounives** [comment]
并没有错啊，Windows的bat就是我写的……

**Comment by K-Guan** [comment]
@smounives RIP your script. :)
