### ISSUE TITLE
HostsGeter.bat问题

### ISSUE THREAD

**Issue by qwerty258** [racaljk/hosts#222]
1. HostsGeter.bat编码为UTF8，中文直接乱码，转ANSI正常，建议全英文。
2. 备份不正常，并无时间戳。
3. 备份就放在etc下就行了，干嘛转到Windows文件夹下，乱乱的。

**Comment by K-Guan** [comment]
cc @redapple0204 @lizongzeshunshun @lideming

**Comment by lizongzeshunshun** [comment]
我测试一下

**Comment by lizongzeshunshun** [comment]
@qwerty258 
问题1.这个还要和@redapple0204商量一下要不要改全英文。
问题2.我这边测试是成功的，另外，文件名不是时间戳，是日期-时间。
问题3.这个放在Windows下确实很乱，但是放在etc里也未必清楚，我认为可以在etc中建立一个备份文件夹储存备份文件.

**Comment by qwerty258** [comment]
@lizongzeshunshun 
我不知道你什么系统，我WIN 10 1511下就是一个hosts文件，没有日期时间。

**Comment by redapple0204** [comment]
@qwerty258 会不会是你的系统时间错乱？

**Comment by lizongzeshunshun** [comment]
@qwerty258 这个bat最高在Windows Vista系统测试过。没有在Win7+以上测试，能截个图或者错误描述具体一些吗？

**Comment by qwerty258** [comment]
再来一个问题：
4. 你不能保证用户一定有个C盘，所以类似“C:\hosts”的绝对路径有可能出问题。
@redapple0204 @lizongzeshunshun

**Comment by lizongzeshunshun** [comment]
@qwerty258 我们用的是 %windir%

**Comment by redapple0204** [comment]
@qwerty258 我们用的是%windir% hosts下载保存到c盘是正确的，有的电脑没有很多个盘（例如 mac，无法分多个区，分了多个区会导致磁盘变成动态磁盘，然后无法开机，就要重装。。。扯远了）

**Comment by qwerty258** [comment]
我指的是第17行：echo iLocal=LCase("c:\hosts")

**Comment by redapple0204** [comment]
@qwerty258 好的，我们会去看看

**Comment by lideming** [comment]
@redapple0204 @lizongzeshunshun 
我曾经想过让bat脚本通过vbs把自身从UTF-8转为ANSI(GBK)， 但是我没有写过vbs，就没有做……

**Comment by lautis0503** [comment]
pull request #224 备份原hosts那条命令……
