### ISSUE TITLE
建议移除的条目

### ISSUE THREAD

**Issue by smounives** [racaljk/hosts#226]
RockStar 和 osu 并非防火墙认证的条目，当初加入只是为了GTA5和osu两个游戏能加速连接，算是历史遗留问题，现在时间过了这么久有些CDN可能IP都变了，不建议加入w

**Comment by K-Guan** [comment]
既然如此，反正你也是 Collaborator ，就叫给你好了。

**Comment by smounives** [comment]
_(:3」∠)_ 重装了Windows 7，还没装Git环境

**Comment by racaljk** [comment]
好久不见～

😫我的大gta被删了
(虽然问题不大

**Comment by smounives** [comment]
好久不见 _(:3」∠)_

**Comment by lautis0503** [comment]
围观楼上二位
@smounives 我最初是跟着你的hosts跑过来的
