### ISSUE TITLE
部分fb域名疑问

### ISSUE THREAD

**Issue by CNMan** [racaljk/hosts#227]
```
static.ak.fbcdn.net    act.channel.facebook.com
static.ak.fbcdn.net    0-act.channel.facebook.com
static.ak.fbcdn.net    1-act.channel.facebook.com
static.ak.fbcdn.net    2-act.channel.facebook.com
static.ak.fbcdn.net    3-act.channel.facebook.com
static.ak.fbcdn.net    4-act.channel.facebook.com
static.ak.fbcdn.net    5-act.channel.facebook.com
static.ak.fbcdn.net    6-act.channel.facebook.com
static.ak.fbcdn.net    origincache-ai-01-05-ash3.fbcdn.net
static.ak.fbcdn.net    inyour-slb-01-05-ash3.facebook.com
static.ak.fbcdn.net    origincache-starfacebook-ai-01-05-ash3.facebook.com
```
这几条怎么用了域名而不是域名对应的A记录？

```
184.28.188.153    static.ak.fbcdn.net
```

**Comment by Ignotus-CN** [comment]
#213 Facebook 有关内容可能搬运自 [Netsh](http://serve.netsh.org/pub/ipv4-hosts/)。不知道会不会有什么纠纷发生……

**Comment by imcaffrey** [comment]
@Ignotus-CN Netsh提供的Facebook段没有用域名阿

**Comment by racaljk** [comment]
@Ignotus-CN
根据他的声明来看应该没问题

**Comment by lautis0503** [comment]
Netsh原文件如此，应该是制作时的疏忽，Pull request吧

**Comment by imcaffrey** [comment]
@lautis0503 你说的是什么意思阿？

**Comment by lautis0503** [comment]
@imcaffrey hosts不支持CNAME record，我在Win7测试过了，所以应改为A record

**Comment by imcaffrey** [comment]
@lautis0503 gotcha

**Comment by Ignotus-CN** [comment]
@imcaffrey 我的想法是将 Facebook 有关条目回滚到合并 #213 之前，只替换失效的IP。

**Comment by imcaffrey** [comment]
#213 好恶心………………

**Comment by CNMan** [comment]
落掉了后面3个...

**Comment by lautis0503** [comment]
@imcaffrey 同上
https://github.com/racaljk/hosts/blob/b8843ba9e42bdf4dc9d72735222c92ceac300200/hosts#L158
https://github.com/racaljk/hosts/blob/b8843ba9e42bdf4dc9d72735222c92ceac300200/hosts#L160
https://github.com/racaljk/hosts/blob/b8843ba9e42bdf4dc9d72735222c92ceac300200/hosts#L161

**Comment by imcaffrey** [comment]
QAQ, 我的锅.
