### ISSUE TITLE
新的Google相关服务网址

### ISSUE THREAD

**Issue by RARLABGmbH** [racaljk/hosts#23]
eduproducts.withgoogle.com
www.gwtproject.org
toolbox.googleapps.com
感谢维护者！

**Comment by SMoUNiVeS** [comment]
got it! Thanks

**Comment by RARLABGmbH** [comment]
回馈：
www.gwtproject.org不能用现有的IP访问，可能要dig新IP。
新增可收录Google服务网址：
r2---sn-cg07luel.c.pack.google.com
发现https://cache.pack.google.com/edgedl/googletalk/googletalkplugin/3.15.2.12038/googletalkpluginaccel.msi 
这一网址会像YouTube一样随机跳转到类似于r2---sn-cg07luel.c.pack.google.com的网址。编码规则或可参照YouTube。当然，编码后网址可能非常多，是否全部加入还需要作者进一步权衡。
