### ISSUE TITLE
gmail转发配置时跳转到一个链接，域名无法跳转

### ISSUE THREAD

**Issue by mbcc2006** [racaljk/hosts#231]
mail-settings.google.com

**Comment by imcaffrey** [comment]
404 Not Found

**Comment by mbcc2006** [comment]
![Uploading QQ截图20160123163201.png…]()

**Comment by imcaffrey** [comment]
我是跳转到about:blank了…………

**Comment by lautis0503** [comment]
直接加上就好，IP地址相同

**Comment by imcaffrey** [comment]
@lautis0503 泥试过好使吗……我还是blank

**Comment by K-Guan** [comment]
@imcaffrey 我是用的VPN：

![screenshot from 2016-02-16 19-51-27](https://cloud.githubusercontent.com/assets/13862535/13075731/6d0d4b4a-d4e8-11e5-9368-c64d429f87c6.png)

**Comment by imcaffrey** [comment]
哦那应该差不多就加上一行和Google一样的IP好了？

**Comment by lautis0503** [comment]
@imcaffrey 我这里加上那一行就好了，不用我用的是64.233.162.84的IP
@K-Guan 我加上那行IP后，直接打开网址也是404，但是Gmail中的设置已经正常了。

**Comment by K-Guan** [comment]
@lautis0503 它要不是 404 那就见鬼了，要知道我也是挂的 VPN 访问呀。很简单，这个网址不接受 GET 请求，不然返回 404 。

**Comment by K-Guan** [comment]
@imcaffrey 新的更新就交给你吧。更新完后，给这个 issue 加一个 `status-completed` lable ，然后 close  就好了。
