### ISSUE TITLE
求问啦如何上Youtube

### ISSUE THREAD

**Issue by G-BlueSummer** [racaljk/hosts#233]
可以进入网页，但是播放视频无限加载

**Comment by K-Guan** [comment]
我的 Wiki 看来是白写了 :( 

> https://github.com/racaljk/hosts/wiki/The-hosts-FAQ#%E6%97%A0%E6%B3%95%E8%A7%82%E7%9C%8B-youtube-%E8%A7%86%E9%A2%91%E7%9A%84%E8%A7%A3%E5%86%B3%E6%96%B9%E6%A1%88
