### ISSUE TITLE
HostsGeter.bat的编码问题似乎没有得到解决...

### ISSUE THREAD

**Issue by lizongzeshunshun** [racaljk/hosts#234]
刚刚试了一下windows下的自动更新bat: _hosts/hosts_tools/scripts/script_tool_for_windows.bat_

我使用了3种方式下载，结果分别如下：

1.Github网页的Download Zip

> E:\TV\hosts-master\hosts-master\hosts_tools\scripts>script_tool_for_windows.bat
'verterPath' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
命令语法不正确。

这个错误很奇怪，貌似是源于.bat中的

> echo inputpath="%~0" >%Con**verterPath**%
echo outputpath="%ConverterOutput%" >>%Con**verterPath**%
echo set stm2=createobject("ADODB.Stream") >>%Con**verterPath**%

下面还有许多这样的 

> ****** >> %ConverterPath%

2.在浏览器打开Github中的script_tool_for_windows.bat并且复制到本地改名为.bat

结果：运行时中文全部变成“?????"

在我用Notepad++更改编码为UTF-8后，终于恢复正常

3.使用git clone指令下载
结果：和 1 的结果一样.

说明：测试环境为Windows 10 正式版.

**Comment by K-Guan** [comment]
试过我放在 README 中的直接下载链接吗？

> https://cdn.rawgit.com/racaljk/hosts/6124a493a7720633840d9dadec13c5311639145e/hosts_tools/scripts/script_tool_for_windows.bat

**Comment by lizongzeshunshun** [comment]
@K-Guan 
这个直连同样出现错误，错误类型和 1 一样

> E:\TV\hosts-master\hosts-master\hosts_tools\scripts>script_tool_for_windows.bat
'verterPath' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
命令语法不正确。

**Comment by lizongzeshunshun** [comment]
刚刚看到bat前面有两行设置环境变量的
`
set ConverterPath=%temp%\HostsGeter_CodeConverter.vbs

set ConverterOutput=%temp%\HostsGeter_GBK.bat
`

可能这里出错了

**Comment by redapple0204** [comment]
我直接打开bat闪退（vista），打开看是编码问题，一坨堆在那里

**Comment by redapple0204** [comment]
实验证明，在vista下报的错误和@lizongzeshunshun 的基本一致

**Comment by K-Guan** [comment]
好吧，那么这个问题交给你们了。我是无能为力。

**Comment by lautis0503** [comment]
关于类型1和3的错误……这我就得说几句了。Windows用的bat竟然换行符用的是UNIX格式？！

**Comment by K-Guan** [comment]
@lautis0503 哦，我还纳闷怎么我的 VIM 说文件是 `utf-8[unix]` 呢：

![screenshot from 2016-02-19 12-14-23](https://cloud.githubusercontent.com/assets/13862535/13166445/feeb838a-d702-11e5-8c77-732b682d1b21.png)

**Comment by lautis0503** [comment]
@K-Guan 所以才会出现那样莫名其妙的错误

**Comment by lizongzeshunshun** [comment]
@K-Guan ...这字体好漂亮，想问一下是什么字体，大小多少
另外，下面这一栏是什么插件做到的
![feeb838a-d702-11e5-8c77-732b682d1b21](https://cloud.githubusercontent.com/assets/10304206/13167788/782bcac6-d711-11e5-8b81-911a8932158e.png)

在此先行谢过

**Comment by lautis0503** [comment]
@K-Guan  #235  已Pull request

**Comment by K-Guan** [comment]
@lizongzeshunshun 原来你的注意力都放到那边去了 :P 

字体是 Arch 下的 GNOME Ternimal 默认字体 Monospace （据说可能实际是 Ubuntu Font）。下面是 Vim-Airline 。Airline 的样式不少，一般会跟着 Vim 的主题改。不过这个是指定的 `serene`。

vimrc 内有关 Airline 的配置 如下：

```vim
let g:airline_powerline_fonts = 1
let g:airline_theme='serene'
```

**Comment by K-Guan** [comment]
@lautis0503 Already merged. 大家可以测试下是否有用，如果没问题的话这个 issue 就可以 close 了。

**Comment by redapple0204** [comment]
@K-Guan 原来如此啊，谢谢了

**Comment by redapple0204** [comment]
@K-Guan 那么这些主题在别的linux下是否可以用呢

**Comment by lizongzeshunshun** [comment]
@K-Guan 
1.OK.谢谢

2. .bat 可以使用了,close吧

**Comment by K-Guan** [comment]
@redapple0204 你是说 Vim 的主题？自然。

**Comment by lizongzeshunshun** [comment]
@K-Guan 

使用Vundle安装Airline后无法启动Airline
我已经添加
```
let g:airline_powerline_fonts = 1
let g:airline_theme='serene'
```
 to .vimrc

在vim安装代码是：
`:PluginInstall 'vim-airline/vim-airline'`

vim显示“Done”但不行...

**Comment by lideming** [comment]
我邮箱被 GitHub 轰炸了:joy:

**Comment by lizongzeshunshun** [comment]
..............
![screenshot from 2016-02-19 16-55-19](https://cloud.githubusercontent.com/assets/10304206/13170788/a3ac69a4-d729-11e5-92cf-89ca3f491e2a.png)

**Comment by K-Guan** [comment]
@lizongzeshunshun 首先……如果你想用我在用的主题的话，你需要下载这个：https://raw.githubusercontent.com/vim-airline/vim-airline-themes/master/autoload/airline/themes/serene.vim

然后放到 airline 的主题文件夹内。Vim-Pathogen 的话只需要：

     ~/.vim/bundle/vim-airline/autoload/airline/themes/serene.vim

表示不知道 Vundle 怎么做。


然后，你得安装 `powerline` 。不知道你的源里有没有。

最后， `powerline` 需要几个特殊的字体。命令如下：

```bash
 wget 'https://raw.githubusercontent.com/powerline/powerline/develop/font/10-powerline-symbols.conf' -O /usr/share/fonts/OTF/10-powerline
 wget 'https://raw.githubusercontent.com/powerline/powerline/develop/font/PowerlineSymbols.otf' -O /usr/share/fonts/OTF/PowerlineSymbols.
 
 cp /usr/share/fonts/OTF/10-powerline-symbols.conf /etc/fonts/conf.d/10-powerline-symbols.conf
```

**Comment by lideming** [comment]
@K-Guan 真麻烦，你看我用 Visual Studio 就不用这么折腾（逃

**Comment by K-Guan** [comment]
@lideming *看来你是没听说过传说中的 Emacs 。*

**Comment by redapple0204** [comment]
@K-Guan 原来如此，我下次试试

**Comment by lizongzeshunshun** [comment]
@K-Guan 
My Sunpinyin does not work...
and the Vim plguin... 

:PluginInstall 'vim-airline/vim-airline', then , VIM showed 'Done'
I ran ':help airline' , Vim showed me Help-File
but after I restart VIM and ran ':help airline' , it showed me ' E149: 抱歉，没有 airline 的说明 '

**Comment by gisphm** [comment]
@lizongzeshunshun 你得把插件写入 vimrc 或者是其他 vimrc 有 source 的文件里，不然 vim 不会自动加载 airline

**Comment by K-Guan** [comment]
@lizongzeshunshun 话说…… Airline 的帮助是那么调用的么？试试看有没有 `AirlineTheme` 这个命令。

**Comment by lizongzeshunshun** [comment]
@K-Guan 教程告诉我是那么调用的，稍后试试.

**Comment by lizongzeshunshun** [comment]
@gisphm 好的我查查

**Comment by lautis0503** [comment]
@K-Guan 你又把换行符改回去了……
https://github.com/racaljk/hosts/commit/b6ea514b9e13432870d3289fc249ddc826f47494#diff-b41d33ad6dab1a499c5e6a530e0949fb
没发现bat整个文件都显示改动么……还好我当时也改了.gitattributes

**Comment by K-Guan** [comment]
@lautis0503 等等，我并没……难道说，我的 git 会自动将所有文件的换行符改为 Linux 的？这样难怪了……

**Comment by lizongzeshunshun** [comment]
@K-Guan 
可以了，谢谢！挺漂亮
只是 Airline的箭头要不就是不能显示，要不就是箭头歪的，但是并无大碍.

**Comment by lizongzeshunshun** [comment]
分享一下方法

1.首先需要一个Vim，推荐Gvim （包含Vim和Gvim） 。*Gvim是图形化的Vim，具有更强的颜色表现力，功能及配置文件相同。

`>>sudo pacman -S gvim`

可能会提示与_Vim_冲突，选择删除_Vim_并且继续安装

2.安装_Pathogen_
下载[_Pathogen_](https://github.com/tpope/vim-pathogen)
_Pathogen_是一个单独的Vim文件，将_Pathogen.vim_放入_~/.vim/autoload_  (如果没有请创建)

3.激活_Pathogen_
`>>vim ~/.vimrc`
并且加入
```
call pathogen#infect()  
syntax on  
filetype plugin indent on
```

然后`:wq`

3.安装_Airline_字体
```
>>wget 'https://raw.githubusercontent.com/powerline/powerline/develop/font/10-powerline-symbols.conf' -O /usr/share/fonts/OTF/10-powerline
>>wget 'https://raw.githubusercontent.com/powerline/powerline/develop/font/PowerlineSymbols.otf' -O /usr/share/fonts/OTF/PowerlineSymbols.otf
>>cp /usr/share/fonts/OTF/10-powerline-symbols.conf /etc/fonts/conf.d/10-powerline-symbols.conf
```

4.安装Airline
*确保安装了git
`>>git clone https://github.com/bling/vim-airline ~/.vim/bundle/vim-airline`

--------------------------------THE-END--------------------------------

**Comment by K-Guan** [comment]
@lizongzeshunshun 那个嘛……话说我以前也有过这样，但是安装完字体应该就没问题了呀？

（顺便一提，表示从不用Gvim）
