### ISSUE TITLE
facebook无法访问

### ISSUE THREAD

**Issue by wolfan** [racaljk/hosts#24]
Facebook 好像无法访问，回滚上一版吧。。。

**Comment by racaljk** [comment]
常有的事，也懒得回滚了  而且这个项目主要目的是提供访问google的ip

当然如果楼主有特殊必要可以直接访问之前可用的版本

**Comment by SMoUNiVeS** [comment]
@racaljk 你这一改，改的乱七八糟的(扶额 ，我之前删掉的那些无效的IP你全加上来了，Youtube也是那个反代服务器已经挂了，加上那一大堆Google Video的完全没意义，强行加上非GVS的IP没又法看，建议我重新改一下你看如何

**Comment by racaljk** [comment]
@SMoUNiVeS 随你意思吧  我当时也只是想找找个可用的google ip也就没顾忌那么多...
