### ISSUE TITLE
21 日更新后Google 服务异常，请在此反馈

### ISSUE THREAD

**Issue by andytimes** [racaljk/hosts#241]
统计 Google IP [222.251.134.108|222.251.134.113] 的可用性

若上述 IP 均无法正常访问 Google 服务
替换为
`220.255.2.153` 或 `64.233.162.85`

**Comment by Satoshi-t** [comment]
上述ip [222.251.134.108|222.251.134.113]无法使用
四川广元电信

**Comment by ycraurora** [comment]
[222.251.134.108|222.251.134.113]可以使用
黑龙江哈尔滨教育网
晚上回家试电信

**Comment by dxh** [comment]
今天更新后，4个IP均无法使用。
浙江省杭州市 电信

**Comment by andytimes** [comment]
@dxh 测试下刚刚更新的 ip

**Comment by dxh** [comment]
@andytimes 刚刚未更新，可以使用了，速度不错。赞~

**Comment by ChineseTaipei** [comment]
中国联通广东珠海地区无法登录Google搜索网页

**Comment by ChineseTaipei** [comment]
目前问题已解决，但速度缓慢。
2016-2-28 PM9:22，"Andy Deng" <notifications@github.com>写道：
