### ISSUE TITLE
能否添加 appspot.com  和 slideshare.net

### ISSUE THREAD

**Issue by liuyutao** [racaljk/hosts#243]

**Comment by imcaffrey** [comment]
appspot.com 是不是Google阿？

**Comment by liuyutao** [comment]
是的。用chrome 远程调试手机网页时，需要用到这个站点

**Comment by liuyutao** [comment]
对不起，slideshare的域名竟然写错了。抱歉。

**Comment by lautis0503** [comment]
appspot的二级域名很多，需要使用的话自己添加就好，IP同Google

**Comment by aofall** [comment]
@imcaffrey Appspot是Google App Engine提供的二级域名，类似于国内BAE、SAE之类的平台。有少部分Google服务会用到。
至于slideshare，不支持https，而且被加入关键字了，无解
chrome-devtools-frontend.appspot.com加上后就可以close issue了，ip一样

**Comment by wsdjeg** [comment]
为什么不可以加slideshare支持呀, 不太明白GFW原理呀,什么是加入关键字?
