### ISSUE TITLE
使用mac更新工具出现异常

### ISSUE THREAD

**Issue by hhhaiai** [racaljk/hosts#244]
和priview操作一致但是报错，错误如下：
The document “hosts” could not be opened. HostsTool cannot open files in the “data” format.

**Comment by hhhaiai** [comment]
工具更新后是不是 以后官方自己不更新host了，以后用户用tool自己更新？

**Comment by chy9002** [comment]
我直接运行也会更新失败，sudo下就没问题了，应该是权限问题。

**Comment by racaljk** [comment]
在Github上还是会更新

工具只是提供了一种稍微方便点的方法来获取hosts

**Comment by imcaffrey** [comment]
@hhhaiai 更新工具是说可以更方便地获取Github上的hosts

**Comment by iHongRen** [comment]
@chy9002 请问能详细说明下吗？

**Comment by chy9002** [comment]
终端里面`sudo path/HostsTool.app/Contents/MacOS/HostsTool`. 而且我发现直接`sudo open HostsTool.app`也会更新失败.

**Comment by iHongRen** [comment]
@chy9002 恩，谢谢。之前用sudo open HostsTool.app 更新也是失败。。。。    使用sudo path/HostsTool.app/Contents/MacOS/HostsTool 试了一下成功了。

**Comment by hhhaiai** [comment]
好的 多谢大家
