### ISSUE TITLE
有能上YouTube的host嘛？

### ISSUE THREAD

**Issue by sundyloveme** [racaljk/hosts#247]
这个host能实现翻墙嘛？

**Comment by K-Guan** [comment]
hosts 是无法实现观看 YouTube 视频的。不过您可以参考这个方案：

> https://github.com/racaljk/hosts/wiki/The-hosts-FAQ#%E6%97%A0%E6%B3%95%E8%A7%82%E7%9C%8B-youtube-%E8%A7%86%E9%A2%91%E7%9A%84%E8%A7%A3%E5%86%B3%E6%96%B9%E6%A1%88

**Comment by sundyloveme** [comment]
谢谢

**Comment by iamshenhua** [comment]
https://github.com/racaljk/hosts/blob/master/hosts

这个就可以~~~~~~

**Comment by imcaffrey** [comment]
@iamshenhua 

hosts 是无法实现观看 YouTube 视频的。不过您可以参考这个方案：

> https://github.com/racaljk/hosts/wiki/The-hosts-FAQ#%E6%97%A0%E6%B3%95%E8%A7%82%E7%9C%8B-youtube-%E8%A7%86%E9%A2%91%E7%9A%84%E8%A7%A3%E5%86%B3%E6%96%B9%E6%A1%88

**Comment by outnnn** [comment]
曾经试过只加载到图片就出不来了，需要挂vpn才可以代理访问

**Comment by kgfw** [comment]
这里有个 [hosts翻墙](https://github.com/bannedbook/fanqiang/wiki/hosts%E7%BF%BB%E5%A2%99)  ，可以看youtube

**Comment by baoqiaoze** [comment]
https://raw.githubusercontent.com/sy618/hosts/master/FQ

不用谢我  不过近几天不行了 等更新
