### ISSUE TITLE
这里是hosts更新最及时的地方吗？

### ISSUE THREAD

**Issue by Edenharder** [racaljk/hosts#249]
我看 http://laod.cn/hosts/2016-google-hosts.html 也是用的你的hosts，然而有时上面注明的更新日期却比这里早。比如，现在这里的版本是2016-2-22，那里的版本却是2016-2-25.

**Comment by imcaffrey** [comment]
说到laod.cn阿……嘿嘿嘿

**Comment by lautis0503** [comment]
对比本项目当前[hosts]: https://raw.githubusercontent.com/racaljk/hosts/54ab970cc87fc80a1a1536f869477fabfca8211d/hosts
以及[laod.cn]: http://laod.cn/hosts/2016-google-hosts.html 最新hosts即20160225版本
laod增加了少量内容
android-review.googlesource.com
        ->此行可用，本项目遗漏
slideshare
        ->本项目中有issue请求，但laod的hosts在我这里无效
cn.edit.yahoo.com
        ->不清楚该网址作用，可能有误
accounts-flickr.yahoo.com
        ->我这里原本是正常的，使用laod的hosts导致访问该网站会跳转到Yahoo首页

**Comment by Edenharder** [comment]
嗯，謝謝你們的回覆！
