### ISSUE TITLE
hosts下载后打开排列混乱

### ISSUE THREAD

**Issue by Henta1** [racaljk/hosts#25]
不是一行一个IP的，都是混在一起

**Comment by liuruiruide** [comment]
换个高级的编辑器打开，能显示换行符的，unix(linux)结尾是LF,windows换行是CRLF ，windows记事本不识别LF，并不影响使用。这个不是问题



发自我的小米手机在 Henta1 <notifications@github.com>，2015年8月26日 下午12:35写道：不是一行一个IP的，都是混在一起

**Comment by smounives** [comment]
LS+1，换个高级点的编辑器或者直接使用浏览器打开https://raw.githubusercontent.com/racaljk/hosts/master/hosts
然后全选复制，粘贴到你想要的位置

**Comment by reaCodes** [comment]
我能说这个hosts里边的google IP非常慢吗？基本鸡肋，希望更新一些愉快点的IP

**Comment by Henta1** [comment]
appriciate
