### ISSUE TITLE
Google host not work

### ISSUE THREAD

**Issue by bluestein** [racaljk/hosts#250]
Everything works fine but Google host :disappointed:

**Comment by p0mp0k0** [comment]
嗯，google全部失效了

**Comment by imcaffrey** [comment]
之前的版本里有IP是好用的……我现在搞不清是哪一个但确实是有…………不要慌

**Comment by suixudongi8** [comment]
建议将加Tag，这样可以回滚到原来的版本，我年前的版本可以用。

**Comment by bluestein** [comment]
My solution was replaced it by the old one

**Comment by imcaffrey** [comment]
Last update: 2016.2.13 available

**Comment by leehz** [comment]
216.58.218.238	Y		
216.58.212.38	Y		
64.233.162.85	Y		
216.239.38.125	Y		
203.208.48.154	Y		
216.58.222.44	Y		
173.194.4.94	Y		
74.125.212.60	Y		
66.102.1.14	Y		
74.125.5.158	Y		
203.208.41.7	Y		
213.81.154.129	N		
74.125.21.109	Y		
208.187.128.34	N

可用的一些 google IP 地址

**Comment by leehz** [comment]
估计 最近防x火x墙 封锁更严了， 限制了 海外出口的流量速度，同时还封锁了很多的途径。。。诶。。。

**Comment by liuyutao** [comment]
@leehz ,谢谢你的这个列表。

**Comment by hhhaiai** [comment]
HEAD detached at b403635日期是2016.02.05是OK的

commit b4036358fa07e1a3eea995f804d2dc522e5f2172
Author: Andy Deng <theandy.deng@gmail.com>
Date:   Fri Feb 5 00:13:43 2016 +0800

    hosts: update google ip
    
    If you have connect problem, please open an issue at https://github.com/racaljk/hosts

**Comment by lautis0503** [comment]
我一直用64.233.162.84，几乎没挂过

**Comment by hhhaiai** [comment]
我草 这么叼

2016-02-29 20:21 GMT+08:00 Lautis Sun <notifications@github.com>:

**Comment by imcaffrey** [comment]
希望大家说话的时候注意一下言辞XD
不要过度的情绪化

**Comment by wolfan** [comment]
fb也阵亡了。。。

**Comment by luoye-fe** [comment]
64.233.162.84 可用

**Comment by Roller44** [comment]
有些地方不行。

在 2016-03-01 09:29:33，"骆也" <notifications@github.com> 写道：


64.233.162.84 可用

**Comment by coderSmallEars** [comment]
全部阵亡了  64.233.162.84部分可用

**Comment by hhhaiai** [comment]
呵呵 OK

2016-02-29 23:06 GMT+08:00 SCaffrey <notifications@github.com>:

**Comment by redapple0204** [comment]
我也用不了了，深圳

**Comment by imcaffrey** [comment]
已更新

**Comment by hhhaiai** [comment]
我还是不能正常使用 地区北京 网络是网通

2016-03-01 19:14 GMT+08:00 SCaffrey <notifications@github.com>:
