### ISSUE TITLE
提个建议

### ISSUE THREAD

**Issue by hhhaiai** [racaljk/hosts#251]
大家是否把更新hosts的方法，就是获取IP的方法，整理下，然后使用者自己可以push代码
这样大家会有更多的IP，速度也将进一步优化

**Comment by hhhaiai** [comment]
很简单的，比如一些地址访问youtube 可以看到播放的，而部分访问youtube是不能看到播放的。

**Comment by lautis0503** [comment]
然后GFW照着本项目封IP？

**Comment by hhhaiai** [comment]
好吧

2016-02-29 20:25 GMT+08:00 Lautis Sun <notifications@github.com>:

**Comment by imcaffrey** [comment]
个人感觉这个建议其实不错……调动大家的力量咯

**Comment by wolfan** [comment]
@hhhaiai youtube的IPv6好像是可以播放的。不过上去也没什么好看的，而且总是收到都是一大堆轮子大法的，我还是想要fb的更好于玩。

要找IP不难，难是难在花费时间上，记得以前那个ss的作者写过一次教材的，你找找吧。

**Comment by hhhaiai** [comment]
其实，众人拾柴火焰高，不怕GFW

2016-02-29 23:07 GMT+08:00 SCaffrey <notifications@github.com>:

**Comment by hhhaiai** [comment]
啊，有么，私聊我，共享下 sanbo.xyz#gmail.com

在 2016年3月1日 上午12:28，wolfan <notifications@github.com>写道：

**Comment by hhhaiai** [comment]
我的还是不行 还是不能访问

**Comment by potatohai** [comment]
确实又挂了，google 用今天的host还是无法访问 包括gmail

**Comment by imcaffrey** [comment]
我这里也挂了……更新之后10min内还是好用的……

**Comment by hhhaiai** [comment]
兄弟们，能不能建个邮件群，大家可以共享最新获取IP的方法

2016-03-01 21:33 GMT+08:00 SCaffrey <notifications@github.com>:

**Comment by imcaffrey** [comment]
mailing list?

**Comment by hhhaiai** [comment]
邮件  交流hosts更新的规则

2016-03-02 12:33 GMT+08:00 SCaffrey <notifications@github.com>:

**Comment by hhhaiai** [comment]
就我一个人其他人没参与

2016-03-02 13:57 GMT+08:00 sanbo x <sanbo.xyz@gmail.com>:

**Comment by hhhaiai** [comment]
我们现在只更新IPV4的地址，也可以同时融入IPV6的地址

2016-03-02 13:58 GMT+08:00 sanbo x <sanbo.xyz@gmail.com>:

**Comment by hhhaiai** [comment]
<sanbo.xyz#gmail.com>

**Comment by imcaffrey** [comment]
@hhhaiai 
不知道你在说什么、希望你能把话说得详细一点
如果你说的是希望能共享hosts更新的策略，我想这个出发点还是好的

**Comment by hhhaiai** [comment]
我的意思是分享下hosts更新的策略。 并且多不同网络的策略进行融合

**Comment by hhhaiai** [comment]
同时也想更多人参与更新校正hosts更新策略

**Comment by hhhaiai** [comment]
我的意思就是上面说的

在 2016年3月2日 下午7:21，SCaffrey <notifications@github.com>写道：

**Comment by imcaffrey** [comment]
:+1:

**Comment by OsmanthusTree** [comment]
两会在即,请大家珍重...

**Comment by K-Guan** [comment]
不知道我新开的 issue 是不是您的意思，如果不是的话请说明，如果没错的话还请 Close 本 issue。

**Comment by hhhaiai** [comment]
恩 两会了，大家注意点也好。  有愿意加入规则讨论的   请和我联系  sanbo.xyz#gmail.com

2016-03-03 7:47 GMT+08:00 Kevin Guan <notifications@github.com>:
