### ISSUE TITLE
想请问我如何能成为HOSTS的贡献者

### ISSUE THREAD

**Issue by JavaProgrammerLB** [racaljk/hosts#256]
我想知道如何能找到可用的Google的IP地址，
在项目里好像只看到你们不断的更新README和HOSTS，想知道你们是如何获取到那些IP的？

**Comment by imcaffrey** [comment]
其实……修改README是因为之前有一堆typo……以及一些格式什么的在改

**Comment by hhhaiai** [comment]
还是建议大家，组建个邮件群组，交流规则变更等信息。这样更新代码的人就会增加
