### ISSUE TITLE
[关于hosts的小问题] Hosts conversions: Talk - Ask - Suggest - Improve

### ISSUE THREAD

**Issue by K-Guan** [racaljk/hosts#258]
鉴于 #251 ，我认为开一个专门的 issue 供大家讨论与交流 hosts 相关的东西应该可以让大家更方便些。同时大家如果有什么关于 hosts 的小问题也就可以直接在这里问，而避免开多个 issues 了。

本 issue 的目的及注意事项：

1. 主要是供大家讨论与交流 hosts ，所有围绕 hosts 的话题均可在本 issue 提出。
2. 如果有新的 hosts ，请提交一个 [**Pull request**](https://github.com/racaljk/hosts/pulls) （而不是在这里提出）。
3. 本 issue 长期有效，欢迎大家交流与探讨。

> 上述仅是我的想法。如有问题，欢迎在下面提出建议 / 关闭本 issue / 编辑本 issue 。

**Comment by imcaffrey** [comment]
+#256

**Comment by hhhaiai** [comment]
赞一个

**Comment by imcaffrey** [comment]
"因为有一些网站不在这个hosts里面，我想能不能自己找到这些网站的可用IP呢？"

**Comment by showerying** [comment]
请问这些IP是怎么收集出来的呢？

**Comment by AlexDialga** [comment]
好吧这里为小白一枚= =
把之前的issue关掉了...
关于https://vimeo.com
原本没有被墙过，然而今天想进去的时候就是没得开，这个问题可以通过hosts解决吗？可以的话求解决或告知如何解决，谢谢各位！

**Comment by techstay** [comment]
加入一些IPV6的hosts如何，这样的话校园网用户更方便了（我前两天发现了YouTube的ipv6地址，现在爽的不要不要的）

**Comment by andytimes** [comment]
@techstay https://github.com/lennylxx/ipv6-hosts

**Comment by K-Guan** [comment]
Since we already have [a chat room on Gitter](https://gitter.im/racaljk/hosts?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) hence I closed this issue.
