### ISSUE TITLE
Facebook access restricted

### ISSUE THREAD

**Issue by lautis0503** [racaljk/hosts#262]
It says 'You are trying to access Facebook from an IP (Internet Protocol) address that's associated with a misconfigured ISP (Internet Service Provider) or abusive behavior.'

**Comment by Ignotus-CN** [comment]
主动屏蔽中国大陆 IP 的一天最终还是到来了……

**Comment by imcaffrey** [comment]
QAQ

**Comment by 769344359** [comment]
悲伤

**Comment by 769344359** [comment]
为什么会被主动屏蔽````````

**Comment by aofall** [comment]
@imcaffrey 不要随便把缓存服务器或者反代拿来用
1.不安全 随时可以中间人攻击
2.未授权 都没跟别人说一声就这样跑别人流量真的好吗？

**Comment by imcaffrey** [comment]
All my pot.

**Comment by lautis0503** [comment]
It works fine now. But it may get down some day.

**Comment by racaljk** [comment]
常态
