### ISSUE TITLE
时不时的上不了Google、Twitter、github等

### ISSUE THREAD

**Issue by KFAaron** [racaljk/hosts#263]
我更改hosts文件，重启之后，还是经常会上不了Google、Twitter，stackoverflow经常进入首页，点登陆的时候就不行了，github也时不时上不了，或者很卡，这是跟网有关么？（上百度之类的没问题）

**Comment by imcaffrey** [comment]
我这里也是不稳定……然而能用就行吧…………

**Comment by KFAaron** [comment]
忘了把原始hosts文件备份了········

**Comment by qwerty258** [comment]
貌似谷歌邮箱的IMAP服务器的IP也不行了，我发现客户端体积小的邮件能收到，体积大的就收不到了，而且是连上后就断了。我TRACERT了一下，总是要到北京去一下才到美国，真你嘛恶心，有本事就物理断网。

**Comment by nxtreaming** [comment]
我们团队是自己搭建代理服务器，从来不用这个[hosts]中的IP，不为别的，就是为了稳定，少浪费时间，我个人觉得很值得。

很想知道为什么很多人愿意用这种修改host的方式来翻墙，？自己弄台VPS一个月也就是几十块钱，最贵的也不过一百多块，这点钱绝大部分人应该能承受的起，省下的时间所获得价值，远远超过这点支出了。

2016-03-05 19:39 GMT+08:00 qwerty258 <notifications@github.com>:

**Comment by imcaffrey** [comment]
作为一个不赚钱的学生……不知道怎么回答您的问题

**Comment by K-Guan** [comment]
@nxtreaming 虽然不想冒犯，但是真的觉得您的评论有些无用：

- 所以您是推荐我们放弃本项目？

- 还是推荐其他人不使用本项目？

另外我也是使用 VPN 的（[**The Private Internet Access**](https://www.privateinternetaccess.com/)），所以我也可以理解 VPN 的好处。但是，我们的项目是免费的，（大家使用本项目的原因）仅此而已。对于没有经济收入的人群，就是一分钱也是无法支出的 - 何况几十元呢？

**Comment by nxtreaming** [comment]
2016-03-06 11:06 GMT+08:00 Kevin Guan <notifications@github.com>:

> @nxtreaming <https://github.com/nxtreaming> 虽然不想冒犯，但是真的觉得您的评论有些无用：
>
我觉得的你的理解力有问题或者智商有问题，同样我也不想冒犯您。

>
>    -
>
>    所以您是推荐我们放弃本项目？
>
> 我推荐有收入的程序员不要使用该项目，我关注的点是足够的便利性和稳定性，而不是免费。

>
>    -
>
>    还是推荐其他人不使用本项目？
>
> 别人是否使用本项目由其本人决定。本项目有益处，我肯定推荐需要者继续使用。

>
>
> 另外我也是使用 VPN 的（*The Private Internet Access*
> <https://www.privateinternetaccess.com/>），所以我也可以理解 VPN
> 的好处。但是，我们的项目是免费的，（大家使用本项目的原因）仅此而已。对于没有经济收入的人群，就是一分钱也是无法支出的 - 何况几十元呢？
>
理解，对于学生党本项目还是很有价值的，这是我在上一封邮件中没有考虑到的用户群。

**Comment by imcaffrey** [comment]
@K-Guan 你好像想多了， 可以理解成@nxtreaming 应该只是在分享他自己团队的解决方案，其他人选择怎样的方案也不是他推荐怎样就能左右的。

**Comment by K-Guan** [comment]
@imcaffrey 如果这么说的话到也没错。 @nxtreaming 下次请描述清楚些，即让大家可以明白您的意思，也可避免误会。我向您道歉。

**Comment by redapple0204** [comment]
@nxtreaming 这样做让一些高中生或者以下没有银行卡的人群怎么办|？

**Comment by nxtreaming** [comment]
> @imcaffrey 如果这么说的话到也没错。 @nxtreaming 下次请描述清楚些，即让大家可以明白您的意思，也可避免误会。我向您道歉。

不需要道歉，因为你的出发点是好的，是我表达不清楚导致理解偏差。
