### ISSUE TITLE
hosts tools似乎仍然没有解决

### ISSUE THREAD

**Issue by redapple0204** [racaljk/hosts#269]
仍然出现了中文字符无法显示，变成`？？`的形式（编码问题）

**Comment by K-Guan** [comment]
你觉得问题应该是什么？

**Comment by redapple0204** [comment]
@K-Guan 我觉得是编码问题，还是建议改成英文，要不的话让使用者用起来很不方便

**Comment by andytimes** [comment]
@redapple0204 https://github.com/racaljk/hosts/tree/master/hosts_tools/HostsTool 是这个 HostsTool 吗？

**Comment by imcaffrey** [comment]
@andytimes 我猜他说的应该是他合作写的scripts...https://github.com/racaljk/hosts/tree/master/hosts_tools/scripts

**Comment by andytimes** [comment]
@imcaffrey 那应该是这个 https://github.com/racaljk/hosts/blob/master/hosts_tools/scripts/script_tool_for_windows.bat

中文版 Windows CMD 是默认 GBK 编码，我查了下这个脚本是 UTF-8 不知道是不是这个原因。
但里面写了编码转换，具体是怎么回事就不清楚了，反正 bat 最好不要用 UTF-8 编码。

**Comment by redapple0204** [comment]
@K-Guan @andytimes @imcaffrey 建议还是回滚成老的版本，要不根本没法用
