### ISSUE TITLE
https://vimeo.com没法用啦...

### ISSUE THREAD

**Issue by AlexDialga** [racaljk/hosts#270]
https://vimeo.com
原本没有被墙过，然而今天想进去的时候就是没打开，这个问题可以通过hosts解决吗？

**Comment by K-Guan** [comment]
实际吧，类似这样的问题应该单独开一个 issue 。所以我再次打开了本 issue 并移除了您在 #258 的评论。

**Comment by AlexDialga** [comment]
@K-Guan 感谢！
不过我想知道Vimeo会不会和Youtube一样应用二级域名然后看不到Video...如果其为真，就要考虑怎么在Vimeo里面下载。

**Comment by imcaffrey** [comment]
"在Vimeo里面下载?"

https://github.com/soimort/you-get

**Comment by AlexDialga** [comment]
@imcaffrey 哦哦~~看起来的确有料啊━(ﾟ∀ﾟ)━!
届时hosts开放时就可以继续搬运视频啦，谢谢！

**Comment by aofall** [comment]
主域被DNS污染了，其他的子域不知道怎么样。这些是在官网上捕获到的子域
@imcaffrey 

    104.156.85.217 vimeo.com
    43.249.72.143 i.vimeocdn.com
    43.249.72.143 f.vimeocdn.com
    103.245.222.249 vimeo-hp-videos.global.ssl.fastly.net

**Comment by lautis0503** [comment]
@aofall 需要添加域名click.email.vimeo.com，注册验证使用

**Comment by aofall** [comment]
198.245.92.39 click.email.vimeo.com

@imcaffrey
