### ISSUE TITLE
无法通过TGP登录LOL

### ISSUE THREAD

**Issue by XieEDeHeiShou** [racaljk/hosts#271]
RT，换了Hosts后就蛋疼的没法通过TGP登录LOL了，显示网络连接异常。。。
还得开个Lantern才能上LOL了。。。

另，这里跟http://laod.cn/hosts/2016-google-hosts.html 这个老D博客是啥关系啊。。。（完全没关系？

**Comment by imcaffrey** [comment]
"""
我们是creator
原则上只要是符合license的拷贝我们都不认为是侵权，或者更狭义的理解只要署上原作者之名以及保留原作者声明的注释的拷贝我们不反对，但若是以此寻求捐款诸如此类的与盈利有关的行为我只觉得莫名厌恶。
"""
# 205
以及你可以尝试一下在laod的评论区提供本项目的链接

**Comment by racaljk** [comment]
你可以把之前hosts中的内容复制到新hosts中

**Comment by imcaffrey** [comment]
看laod没有及时更新Google IP……下面评论区那些一脸茫然的小伙伴感觉好可怜………………

**Comment by XieEDeHeiShou** [comment]
然而我并没有保留旧的hosts_(:зゝ∠)_

**Comment by imcaffrey** [comment]
@XieEDeHeiShou https://github.com/racaljk/hosts/commits/master

**Comment by aofall** [comment]
想都不用想跟hosts无关
但是你要注意你本地的hosts有没有被其他的软件编辑过

**Comment by qwerty258** [comment]
哎呦，看这位玩LOL的，问题不在这里的hosts，是你DNS的问题，我也碰到过，换个DNS就好了，我偶尔玩CODOL的。

**Comment by XieEDeHeiShou** [comment]
@qwerty258  谢啦~看来是DNS的锅。。。
