### ISSUE TITLE
谷歌IP突然不行了

### ISSUE THREAD

**Issue by qwerty258** [racaljk/hosts#273]
谷歌IP：216.58.217.251貌似被封了

125.119.7.236 浙江省杭州市 电信

PS C:\> ping 216.58.217.251

Pinging 216.58.217.251 with 32 bytes of data:
Request timed out.
Request timed out.
Request timed out.
Request timed out.

Ping statistics for 216.58.217.251:
    Packets: Sent = 4, Received = 0, Lost = 4 (100% loss),

PS C:\> TRACERT.EXE 216.58.217.251

Tracing route to chatenabled.mail.google.com [216.58.217.251]
over a maximum of 30 hops:

  1    10 ms     1 ms    <1 ms  192.168.10.1
  2     2 ms     3 ms     3 ms  125.119.0.1
  3     *        *        *     Request timed out.
  4     4 ms     6 ms     3 ms  61.164.22.149
  5     9 ms    12 ms     6 ms  202.97.82.21
  6    53 ms    55 ms    64 ms  202.97.33.26
  7     *        *        *     Request timed out.
  8   179 ms   179 ms   179 ms  202.97.52.46
  9   169 ms   175 ms   172 ms  ix-2-3-3-0.tcore1.LDN-London.as6453.net [80.231.60.53]
 10   331 ms   334 ms   335 ms  72.14.217.89
 11   338 ms   330 ms   316 ms  72.14.235.75
 12   321 ms   325 ms   327 ms  209.85.250.140
 13   253 ms   252 ms   249 ms  209.85.254.251
 14   336 ms   365 ms   381 ms  216.239.48.154
 15   351 ms   352 ms   343 ms  216.239.48.151
 16   277 ms   280 ms   289 ms  209.85.143.201
 17     *        *        *     Request timed out.
 18     *        *        *     Request timed out.

**Comment by imcaffrey** [comment]
confirmed in #272 . closed as duplicate.

**Comment by K-Guan** [comment]
@imcaffrey 一般来说，接下来会有少说七八个，多有十数个的类似 issue 。你可要做好准备哦。

**Comment by imcaffrey** [comment]
@K-Guan 话说你现在也不在上学吗XD

**Comment by babylon882004** [comment]
替换成220.255.2.153
