### ISSUE TITLE
May I ask you how you find the valid google ip address every time?

### ISSUE THREAD

**Issue by naoziwatele** [racaljk/hosts#276]
I am wondering if you can share the method and then more people could contribute to this repo? Thank you

**Comment by imcaffrey** [comment]
I used GoGo Tester....

**Comment by imcaffrey** [comment]
@K-Guan Maybe you should define what kind of things should go into #258

**Comment by naoziwatele** [comment]
@imcaffrey Thank you

**Comment by K-Guan** [comment]
@imcaffrey Actually, some questions like this one. 

I mean, if an issue isn't about **[hosts-request]**, **[hosts-broken]**, and it also isn't about our **hosts_tools** and licence. Then, 258.

**Comment by K-Guan** [comment]
@naoziwatele So as I said, please re-post your question [here](https://github.com/racaljk/hosts/issues/258) and close this question.

**Comment by imcaffrey** [comment]
on your side.
