### ISSUE TITLE
加一些IPV6的hosts如何

### ISSUE THREAD

**Issue by techstay** [racaljk/hosts#277]
有些网站比如YouTube有IPV6的地址，这样的话校园网用户就可以免登陆免流量直接连接某些网站。

**Comment by LGA1150** [comment]
这个有现成的项目，没必要重复劳动

**Comment by techstay** [comment]
要不把两个项目拼起来，这样两种hosts都有了，多方便

**Comment by imcaffrey** [comment]
这怎么拼起来= =

本身就是各取所需的事情

**Comment by techstay** [comment]
好吧，我还想着如果有一个工具直接同时更新ipv4和v6然后拼成一个hosts，用起来多简单

**Comment by LGA1150** [comment]
直接复制粘贴即可，v6在前，v4在后
