### ISSUE TITLE
CONTRIBUTING.md needed?

### ISSUE THREAD

**Issue by imcaffrey** [racaljk/hosts#278]
If we add this file, a notice will appear when someone attempts to fire an issue.

So we could add things like these:

```
I mean, if an issue isn't about [hosts-request], [hosts-broken], and it also isn't about our hosts_tools and licence. Then, #258.
```

Wonder if we needs this.XD

**Comment by K-Guan** [comment]
*Good, copied my comment into your issue and didn't ask me...agreed anyway*.

**Comment by imcaffrey** [comment]
Just an example. Dont be mad.

**Comment by K-Guan** [comment]
Changed *a bit*: 

> Make sure the issue you're going to post haven't posted yet. Have you tried search your question on Google, [the issue searching feature of GitHub](https://help.github.com/articles/searching-issues/), and checked our [Wiki](https://github.com/racaljk/hosts/wiki) already?  
>
> <sub>*Yes, no #258 in it*</sub>

Actually, the #258 is just a temporary plan, I didn't want to *really use it*.  I mean, if the **discussion** is really very important to the hosts project, why don't we find a better place rather than just within issues?

**Comment by imcaffrey** [comment]
gitter would be nice for discussions.

**Comment by K-Guan** [comment]
@imcaffrey https://gitter.im/? Didn't hear about it but looks cool. Maybe it's a good idea.

**Comment by imcaffrey** [comment]
拼错了……是CONTRIBUTING.....
@K-Guan 我不知道我写的合不合适啊……
https://github.com/racaljk/hosts/blob/master/CONTRIBUTING.md

**Comment by andytimes** [comment]
@imcaffrey 最好用中文写。

**Comment by imcaffrey** [comment]
是……等会改下

**Comment by K-Guan** [comment]
No #258. It's not needed anymore.

**Comment by imcaffrey** [comment]
Hmm, I see

**Comment by racaljk** [comment]
我觉得没什么用，几乎不会有人主动去看。

**Comment by 4679** [comment]
一群中国人先用英语一本正经的交谈 然后突然用中文 好喜感(*ﾟ∇ﾟ)

**Comment by imcaffrey** [comment]
我是因为在学校的机器上没装中文输入法………………

**Comment by Roller44** [comment]
这个项目下一般都是中文交流的。

**Comment by imcaffrey** [comment]
No. we don't need this. No one takes a look.
