### ISSUE TITLE
Linux 的更新脚本

### ISSUE THREAD

**Issue by Roller44** [racaljk/hosts#284]
新的脚本更新之后，每次以 sudo 身份运行的时候就会有一个提示“sudo: unable to resolve host xxxxx”，虽然可能在功能上有影响，但看着还是不舒服啦，希望能加回去。
我还没掌握 git 的用法，不知道怎么添加，有劳了。

**Comment by qwerty258** [comment]
The script here just remove old lines between "# Copyright (c) 2014" and "# Modified hosts end" in /etc/hosts, then cat new lines of this hosts to your /etc/hosts.

This shouldn't change your original hosts content (the importent line: "127.0.0.1 $(hostname)") unless your manually replace the /etc/hosts with other hosts and then use this script.

**Comment by imcaffrey** [comment]
比如你的terminal里叫kevin@Arch
你就加上 127.0.0.1 kevin@Arch就好咯

**Comment by Roller44** [comment]
If just simply add the hosts content from the hosts in this page, the lines would be "127.0.0.1 localhost" instead of "127.0.0.1 $(hostname)", and that curse system reported error.

**Comment by qwerty258** [comment]
@Roller44 
You can try:
`sudo echo "127.0.0.1 $(hostname)" >> /etc/hosts`
and see next time the system will report that error or not.

**Comment by K-Guan** [comment]
@imcaffrey Ahh...why don't use your host name as the example?

**Comment by K-Guan** [comment]
@qwerty258 Nah, `echo` is a shell built-in command. `sudo` doesn't work in this case.

**Comment by qwerty258** [comment]
@Roller44 @K-Guan 
Use root user and echo:
`$ sudo su`
`# echo "127.0.0.1 $(hostname)" >> /etc/hosts`

**Comment by K-Guan** [comment]
@qwerty258 Yeah, that works in most cases.

**Comment by imcaffrey** [comment]
@K-Guan updated. XD
Because I didn't use linux at that time and I searched in this repo. So I found your hostname.

**Comment by Roller44** [comment]
So I have to type this command each time I flush hosts file through script?


 

-------- Original message --------
Sender: qwerty258 <notifications@github.com>
Time: Tue 3/15 11:50
To: racaljk/hosts <hosts@noreply.github.com>
Cc: Yao ShuMin <thisisyaoshumin@gmail.com>
 Subject: Re: [hosts] Linux 的更新脚本 (#284)

**Comment by imcaffrey** [comment]
At this moment, YES

**Comment by Roller44** [comment]
Thanks.


 

-------- Original message --------
Sender: SCaffrey <notifications@github.com>
Time: Tue 3/15 12:49
To: racaljk/hosts <hosts@noreply.github.com>
Cc: Yao ShuMin <thisisyaoshumin@gmail.com>
 Subject: Re: [hosts] Linux 的更新脚本 (#284)

**Comment by K-Guan** [comment]
@imcaffrey It's no longer needed now ^

**Comment by qwerty258** [comment]
@K-Guan 
The blanks around == will cause error:
`./script_tool_for_linux.sh: 1: [: ==: unexpected operator`
`Permission denied, are you root?`

**Comment by imcaffrey** [comment]
@qwerty258  @K-Guan 
ec1c48f8a6913ff32ed5e874fd1f373c802eeb68

**Comment by K-Guan** [comment]
@qwerty258 Ahh...That's because I was editing an old version (forgot `git pull`, yeah). But that still works for me, so I forgot about it and pushed.

**Comment by xiaoping378** [comment]
* 最小系统安装是没有wget的....

```
sh -c "curl -L https://raw.githubusercontent.com/racaljk/hosts/master/hosts > /etc/hosts && echo '127.0.0.1 $(hostname)' >> /etc/hosts"
```

* #313 关于不要默认替换127的, 你自己可以在脚本后面加上啊...

**Comment by imcaffrey** [comment]
curl does the best job. XD
