### ISSUE TITLE
Github 的域名部分能增加么

### ISSUE THREAD

**Issue by Ritchie1108** [racaljk/hosts#286]
国内访问 Github 真的太慢了……能考虑把这部分IP加入么？也方便用 HostsTool 直接覆盖文件更新。

> Start: github 
192.30.252.131 github.com 
192.30.252.129 github.com 
192.30.252.128 github.com 
185.31.17.133 raw.github.com 
185.31.18.133 raw.github.com 
103.245.222.133 raw.github.com 
204.13.250.16 raw.github.com 
208.78.70.4 raw.github.com 
192.30.252.143 gist.github.com 
192.30.252.141 gist.github.com 
192.30.252.142 gist.github.com 
185.31.17.133 developer.github.com 
185.31.18.133 developer.github.com 
103.245.222.133 developer.github.com 
204.13.250.16 developer.github.com 
208.78.70.4 developer.github.com 
192.30.252.139 api.github.com 
204.13.250.16 api.github.com 
204.13.251.16 api.github.com 
185.31.18.184 github.global.ssl.fastly.net 
103.245.222.185 github.global.ssl.fastly.net 
185.31.17.184 github.global.ssl.fastly.net 
185.31.17.133 documentcloud.github.com 
185.31.18.133 documentcloud.github.com 
103.245.222.133 documentcloud.github.com 
204.13.250.16 documentcloud.github.com 
208.78.70.4 documentcloud.github.com 
185.31.17.133 help.github.com 
185.31.18.133 help.github.com 
103.245.222.133 help.github.com 
199.27.79.133 help.github.com 
204.13.250.16 help.github.com 
192.30.252.145 nodeload.github.com 
192.30.252.147 nodeload.github.com 
204.13.250.16 nodeload.github.com 
54.147.173.45 status.github.com 
23.20.32.221 status.github.com 
54.161.104.27 status.github.com 
23.235.47.133 training.github.com 
185.31.17.133 training.github.com 
103.245.222.133 training.github.com 
204.13.250.16 training.github.com 
208.78.70.4 training.github.com

**Comment by racaljk** [comment]
可以访问镜像
https://coding.net/u/scaffrey/p/hosts/git

**Comment by Ritchie1108** [comment]
不是的，你理解错我的意思了，我是说国内上 Github 很慢，并不是特指这个hosts项目 (T T)
目前我自己的解决方法是在 Hosts Tool 的 QT 代码里用 QString::replace() 把

> 192.30.252.141        gist.github.com

这一行替换成我上面给的那些……嗯解决方法是有点蠢……

**Comment by imcaffrey** [comment]
@Ritchie1108 You can open a PR for this.
Thx.

**Comment by Ritchie1108** [comment]
@imcaffrey 不是很会用 Github，见谅，已经请求合并分支了。

**Comment by aofall** [comment]
除了 Github gist被DNS污染
Amazonaws S3连不上的
都不建议添加 因为Github自己做了分地区最优调节
很慢的原因 你得去找你的运营商了 具体原因你可以看看V2EX的这个版块

> https://v2ex.com/go/bb

**Comment by imcaffrey** [comment]
Hmm, guess you're right.
