### ISSUE TITLE
Can you fix to watch youtube video?

### ISSUE THREAD

**Issue by ntycle** [racaljk/hosts#290]
I can go on youtube but can not play any video.... Can you fix that problem? :) so that is perfect

**Comment by Roller44** [comment]
You can't watch video simply just changing the hosts file cause video stream is come from a static address.


 

-------- Original message --------
Sender: ntycle <notifications@github.com>
Time: Thu 3/17 03:43
To: racaljk/hosts <hosts@noreply.github.com>
 Subject: [hosts] Can you fix to watch youtube video? (#290)

**Comment by Too-Naive** [comment]
Is your problem? I can watch video.

**Comment by imcaffrey** [comment]
@Too-Naive please elaborate. 
@ntycle At this moment, it seems that there's no way to watch youtube by changing hosts.

**Comment by Too-Naive** [comment]
In this website: [github blog](https://github.com/blog/broadcasts)

**Comment by Too-Naive** [comment]
In another website, It said that watch youtube must use proxy server

**Comment by K-Guan** [comment]
[Self-note: Think about destroy the Wiki since nobody'd check it.](https://github.com/racaljk/hosts/wiki/The-hosts-FAQ#%E6%97%A0%E6%B3%95%E8%A7%82%E7%9C%8B-youtube-%E8%A7%86%E9%A2%91%E7%9A%84%E8%A7%A3%E5%86%B3%E6%96%B9%E6%A1%88)
