### ISSUE TITLE
可否添加Filpboard国际版可用的hosts

### ISSUE THREAD

**Issue by Zhu-Zhi-Hao** [racaljk/hosts#294]
### FilpBoard中国版可访问，Filpboard国际版不可访问
* 应该是服务器不同吧！能否通过hosts来解决国际版无法访问问题，我不是太懂这方面...

**Comment by LGA1150** [comment]
beacon.flipboard.com
fbprod.flipboard.com

**Comment by aofall** [comment]
@imcaffrey 

    54.225.64.251 domains

**Comment by aofall** [comment]
@imcaffrey ……
还没加啊，ip在楼上，域名在二楼啊

**Comment by imcaffrey** [comment]
我看到了……在学校的时候想着回家加……回家又给忘了………………
话说69days left,你加油啊

**Comment by Zhu-Zhi-Hao** [comment]
卧槽，谢谢，还有69days就高考了..我现在好方...

**Comment by Too-Naive** [comment]
我也好方............

**Comment by Zhu-Zhi-Hao** [comment]
感觉大专已经在向我招手了，还有69days我就成不读书的社会青年了，为了脱单，为了未来的女朋友，我要努力努力努力...

**Comment by Too-Naive** [comment]
也没啥好慌 其实有自招 不过离本一线也是。。。有点远阿

**Comment by Zhu-Zhi-Hao** [comment]
自主招生怎么搞，我不懂啊....考不上大学我就去劳动密集型企业打工，去富士康吧，说不定还可以找个女朋友....

**Comment by Too-Naive** [comment]
当然要有什么xx竞赛的获奖咩..................

**Comment by Zhu-Zhi-Hao** [comment]
没有咋办...我爸妈没让我去竞赛....

**Comment by Too-Naive** [comment]
有什么创新的论文发表 或者专利什么的。。

**Comment by tktik** [comment]
最新host文件更新之后，还是上不去Google
