### ISSUE TITLE
关于ip 失效

### ISSUE THREAD

**Issue by NIGHT-CORE** [racaljk/hosts#295]
相关域名
# Google:gcm Start
64.233.188.188       mobile-gtalk.l.google.com
64.233.188.188	mtalk.google.com
64.233.188.188	gcm.googleapis.com
64.233.188.188	gcm.l.google.com
64.233.188.188	gcm-xmpp.googleapis.com
64.233.188.188	gcm-preprod.l.google.com
64.233.188.188	gcm-preprod.googleapis.com
# Google:gcm End

问题：
【64.233.188.188】 该ip在某些地区无法连接

**Comment by andytimes** [comment]
@NIGHT-CORE "某些地区"是哪些地区？

**Comment by Too-Naive** [comment]
network-tools.com ![](http://i12.tietuku.cn/0d0dbdcad0da7375.png) 

my computer ![](http://i12.tietuku.cn/6293c677cfd19c89.png)

my ip:120.42.*.*

**Comment by andytimes** [comment]
@Too-Naive PC 不需要 GCM。

关于 GCM，国内 Android 应用都是自己用一套推送机制 （所以很混乱），所以在没有谷歌服务套件的 Android 上也是没有影响的。有需要的可以自己 ping IP

**Comment by NIGHT-CORE** [comment]
@andytimes 原来是正常的，无法连接发生在前5天左右，将近一个礼拜了。
请问该如何获取这些ip呢？

**Comment by NIGHT-CORE** [comment]
@andytimes 
我捡到了一个ip ，希望能将进去
74.125.198.188

**Comment by Too-Naive** [comment]
(我的意思是..........同样的网络情况下 能不能ping通也是一样的吧....... @andytimes

**Comment by andytimes** [comment]
把 64.233.188.188 替换成
64.233.187.188
你测试下行不行

获取 IP 需要用到一些网络工具，具体你可以 Google

NIGHT-CORE <notifications@github.com>于2016年3月20日周日 下午11:22写道：

**Comment by andytimes** [comment]
@NIGHT-CORE 能用就好，Good luck

NIGHT-CORE <notifications@github.com>于2016年3月20日周日 下午11:28写道：

**Comment by NIGHT-CORE** [comment]
@andytimes 
64.233.187.188 这个连不上，话说我似乎发现规律了2333

**Comment by LGA1150** [comment]
某些地区会丢ICMP，但是TCP没有问题
试试访问 https://64.233.188.188:5228 
如果出现证书错误，这IP就可用，不用去理ping丢包
