### ISSUE TITLE
请求移除我的 collaborator 身份

### ISSUE THREAD

**Issue by K-Guan** [racaljk/hosts#298]
这个嘛……自从用 VPN 代替 hosts 以后，还是觉得 VPN 方便的多， hosts 也完全不用了。感觉吧既然不用 hosts 了还在这儿挂着个 collaborator 我自己都感觉有点奇怪了。

所以今天想想，@racaljk 还是请帮忙撤了吧。

> <sub>*By the way, @imcaffrey is a good collaborator I think.*</sub>

**Comment by imcaffrey** [comment]
I suppose this is not a valid issue. :smile:

**Comment by racaljk** [comment]
请允悲

**Comment by K-Guan** [comment]
@imcaffrey I know but I don't know if there're other ways to post a request like this...as a pull request isn't good I think =p

**Comment by K-Guan** [comment]
@racaljk （那么……话说为什么现在这个 Collaborator 的牌子还挂在我的身上？）

**Comment by lautis0503** [comment]
这里闲人路过……

**Comment by imcaffrey** [comment]
I wanted to close this issue. It's sad when we might say good bye to someone else.
Anyway, look forward to seeing you around.

**Comment by K-Guan** [comment]
@imcaffrey I will still here around, but will not be so active as before. So don't and no need be sad.
