### ISSUE TITLE
hosts文件被Kaspersky报告为可能包含病毒

### ISSUE THREAD

**Issue by ningfc** [racaljk/hosts#299]
hosts文件被Kaspersky报告为可能包含病毒

**Comment by Moriaty911** [comment]
因为更改hosts文件涉及到修改系统文件，因此有些杀毒软件出于安全原因会提示包含病毒文件。请忽略并允许所有操作。EIS不会对您的电脑造成任何影响。

EIS
2016年3月22日 09:41，"ningfc" <notifications@github.com>写道：

**Comment by ningfc** [comment]
我也是这么想的，不过出于安全考虑需要澄清一下。 谢谢！

**Comment by ningfc** [comment]
谢谢！
