### ISSUE TITLE
挪用别人的hosts也不说一声

### ISSUE THREAD

**Issue by LGA1150** [racaljk/hosts#3]
本人的项目中大量使用了“*”、“?”等通配符
系统的hosts是不支持这些通配符的！
看看我的Readme里是不是写着"for Acrylic DNS Proxy"？

**Comment by racaljk** [comment]
抱歉,没看到你提供LICENSE文件&有时没有使用你的hosts就没有给你打招呼，如果你不同意我可以删除

至于正则我的确没有看见...

**Comment by LGA1150** [comment]
@racaljk 
我说的就是通配符的问题

**Comment by yb3616** [comment]
不是我吧？？我没发什么代码啊！来自我的华为手机-------- 原始邮件 --------主题：Re: [hosts] 挪用别人的hosts也不说一声 (#3)发件人：LGA1150 收件人：racaljk/hosts 抄送：@racaljk 
我说的就是通配符的问题

**Comment by ylvict** [comment]
@racaljk
我基于贵项目的hosts，自己做了一个自动更新的windows服务[[Link](https://github.com/ylvict/syncracaljkhost)]，可以肯定开源且不用于商业用途。
请问是否会和贵项目的License要求产生不符合，如果有License上的不合适，我会即刻删除。

**Comment by Too-Naive** [comment]
@ylvict 愿意合并到项目中来吗..

**Comment by imknown** [comment]
我好像错过了什么

**Comment by ylvict** [comment]
@Too-Naive OK，请问告知贵项目提交第三方工具的合适位置，我会提交pull request过来。

**Comment by Too-Naive** [comment]
您需要fork還是直接遷移到 github.com/HostsTools 中來呢...
