### ISSUE TITLE
for window bat 闪退

### ISSUE THREAD

**Issue by baichi** [racaljk/hosts#300]
双击闪退，管理员身份运行也如此。

在cmd下运行提示：

```
C:\Users\xixihaha>D:\download\script_tool_for_windows.bat
'verterPath' 不是内部或外部命令，也不是可运行的程序
```

**Comment by Moriaty911** [comment]
您好 请先解压文件再运行

EIS
2016年3月22日 11:11，"baichi" <notifications@github.com>写道：

**Comment by lautis0503** [comment]
这样的错误应该是编码问题

**Comment by Moriaty911** [comment]
应该不会是编码错误的，你是第一个遇到这个问题的人。如果可以的话请附图发给我看一下

EIS
2016年3月22日 12:49，"Lautis Sun" <notifications@github.com>写道：

**Comment by K-Guan** [comment]
cc @redapple0204

**Comment by redapple0204** [comment]
这个嘛，编码问题自从发布上去一直没得到解决，请使用老版本的bat，



%1 %2
ver|find "5.">nul&&goto :st
mshta vbscript:createobject("shell.application").shellexecute("%~s0","goto :st","","runas",1)(window.close)&goto :eof
:st
copy "%~0" "%windir%\system32\"
cls
@REM HostsGet Version0.3.1
@echo off
del %temp%\download.vbs >nul2 > nul
cd /d %~dp0
echo Starting...
echo iLocal=LCase("%windir%\hosts") >> %temp%\download.vbs
echo iRemote=LCase("https://raw.githubusercontent.com/racaljk/hosts/master/hosts") >> %temp%\download.vbs
echo Set xPost=createObject("Microsoft.XMLHTTP") 'Set Post = CreateObject("Msxml2.XMLHTTP") >> %temp%\download.vbs
echo xPost.Open "GET",iRemote,0 >> %temp%\download.vbs
echo xPost.Send() >> %temp%\download.vbs
echo set sGet=createObject("ADODB.Stream") >> %temp%\download.vbs
echo sGet.Mode=3 >> %temp%\download.vbs
echo sGet.Type=1 >> %temp%\download.vbs
echo sGet.Open() >> %temp%\download.vbs
echo sGet.Write xPost.ResponseBody >> %temp%\download.vbs
echo sGet.SaveToFile iLocal,2 >> %temp%\download.vbs
echo Please wait...
ping 127.0.0.1 > nul
echo Downloading Hosts file from github...
%temp%\download.vbs
ping 127.0.0.1 > nul
echo Please wait...
del %temp%\download.vbs /s /q
ping 127.0.0.1 > nul
echo Backing up...
move %windir%\system32\drivers\etc\hosts %windir%\system32\drivers\etc\
set filename=%date:~0,4%%date:~5,2%%date:~8,2%%time:~0,2%%time:~3,2%%time:~6,2%
ren %windir%\system32\drivers\etc\hosts %filename%.bak
echo Hosts file in:%windir%\drivers\etc, named : %filename% 
move %windir%\hosts %windir%\system32\drivers\etc\
echo Finish
ipconfig /flushdns
echo Press any key to start google.com.hk
pause >nul
start https://www.google.com.hk
echo Press any key to close
pause >nul
保存成bat

**Comment by racaljk** [comment]
如@redapple0204所说（其实我没用过bat script （逃

**Comment by baichi** [comment]
嗯，我也不用了，运行了还需要提升权限，还需要关闭杀毒软件监控，下载下来的vbs还需要添加白名单。hozz了
