### ISSUE TITLE
facebook 挂掉了

### ISSUE THREAD

**Issue by NIGHT-CORE** [racaljk/hosts#301]
facebook 挂掉了
希望，更新或者移除

**Comment by Moriaty911** [comment]
Facebook无法访问问题已修复，请及时更新hosts文件。

EIS
2016年3月22日 19:46，"NIGHT-CORE" <notifications@github.com>写道：

**Comment by imcaffrey** [comment]
solved?

**Comment by DaleXiao** [comment]
Not yet, the current host of fb seemingly does not work.
