### ISSUE TITLE
facebook doesn't work

### ISSUE THREAD

**Issue by DaleXiao** [racaljk/hosts#302]
Please kindly fix.

**Comment by imcaffrey** [comment]
honestly, wontfix facebook IP at this moment. QAQ

**Comment by DaleXiao** [comment]
how come?

**Comment by Moriaty911** [comment]
Use this:

www.nflseis.com
2016年3月23日 13:07，"Dale Xiao" <notifications@github.com>写道：

**Comment by DaleXiao** [comment]
Thanks, let me try this out.

**Comment by DaleXiao** [comment]
The host for FB from www.nflseis.com works only with browser, not with FB Client app on iOS.

**Comment by imcaffrey** [comment]
南外太强啦%%%

**Comment by Too-Naive** [comment]
Orz..
