### ISSUE TITLE
Try this hosts for Facebook

### ISSUE THREAD

**Issue by Moriaty911** [racaljk/hosts#303]
This is from www.nflseis.com

# Facebook start
182.239.95.136	fb.me
31.13.66.14	video.xx.fbcdn.net
31.13.66.9	scontent.xx.fbcdn.net
31.13.66.9	scontent-a.xx.fbcdn.net
31.13.66.9	scontent-b.xx.fbcdn.net
31.13.66.9	scontent-c.xx.fbcdn.net
31.13.66.9	scontent-d.xx.fbcdn.net
23.63.99.242	fbexternal-a.akamaihd.net
23.67.255.208	fbcdn-creative-a.akamaihd.net
23.63.99.186	fbcdn-video-a-a.akamaihd.net
23.63.99.171	fbcdn-video-b-a.akamaihd.net
23.63.99.120	fbcdn-video-c-a.akamaihd.net
23.63.99.144	fbcdn-video-d-a.akamaihd.net
23.63.99.131	fbcdn-video-e-a.akamaihd.net
23.63.99.160	fbcdn-video-f-a.akamaihd.net
23.63.99.171	fbcdn-video-g-a.akamaihd.net
23.63.99.130	fbcdn-video-h-a.akamaihd.net
23.63.99.145	fbcdn-video-i-a.akamaihd.net
23.63.99.178	fbcdn-video-j-a.akamaihd.net
23.63.99.201	fbcdn-video-k-a.akamaihd.net
23.63.99.170	fbcdn-video-l-a.akamaihd.net
23.63.99.136	fbcdn-video-m-a.akamaihd.net
23.63.99.169	fbcdn-video-n-a.akamaihd.net
23.63.99.171	fbcdn-video-o-a.akamaihd.net
23.63.99.144	fbcdn-video-p-a.akamaihd.net
23.63.99.123	fbcdn-vthumb-a.akamaihd.net
182.239.95.136	mqtt.facebook.com
77.67.4.11	fbcdn-sphotos-a-a.akamaihd.net
77.67.4.64	fbcdn-sphotos-b-a.akamaihd.net
77.67.4.74	fbcdn-sphotos-c-a.akamaihd.net
77.67.4.73	fbcdn-sphotos-d-a.akamaihd.net
77.67.4.74	fbcdn-sphotos-e-a.akamaihd.net
77.67.4.10	fbcdn-sphotos-f-a.akamaihd.net
23.63.99.56	fbcdn-sphotos-g-a.akamaihd.net
23.63.99.88	fbcdn-sphotos-h-a.akamaihd.net
2.16.162.11	fbcdn-profile-a.akamaihd.net
23.213.58.87	s-static.ak.facebook.com
23.213.58.87	profile.ak.facebook.com
184.28.188.154	static.ak.facebook.com
184.28.188.154	b.static.ak.facebook.com
182.239.95.136	graph.facebook.com
182.239.95.136	ssl.facebook.com
182.239.95.136	api.facebook.com
182.239.95.136	secure-profile.facebook.com
182.239.95.136	secure.facebook.com
182.239.95.136	zh-cn.facebook.com
182.239.95.136	login.facebook.com
182.239.95.136	m.facebook.com
108.166.120.82	messages-facebook.com
182.239.95.136	attachments.facebook.com
182.239.95.136	touch.facebook.com
182.239.95.136	facebook.com
182.239.95.136	www.facebook.com
182.239.95.136	apps.facebook.com
182.239.95.136	upload.facebook.com
182.239.95.136	developers.facebook.com
182.239.95.136	fbcdn.net
165.254.42.232	profile.ak.fbcdn.net
173.252.71.184	vpn.tfbnw.net
184.28.188.240	vthumb.ak.fbcdn.net
184.28.188.152	photos-a.ak.fbcdn.net
184.28.188.154	photos-b.ak.fbcdn.net
184.28.188.171	photos-c.ak.fbcdn.net
184.28.188.171	photos-d.ak.fbcdn.net
184.28.188.153	photos-e.ak.fbcdn.net
184.28.188.153	photos-f.ak.fbcdn.net
184.28.188.171	photos-g.ak.fbcdn.net
184.28.188.146	photos-h.ak.fbcdn.net
184.28.188.171	creative.ak.fbcdn.net
184.28.188.153	external.ak.fbcdn.net
184.28.188.153	b.static.ak.fbcdn.net
184.28.188.153	static.ak.fbcdn.net
184.28.188.153	act.channel.facebook.com
184.28.188.153	0-act.channel.facebook.com
184.28.188.153	1-act.channel.facebook.com
184.28.188.153	2-act.channel.facebook.com
184.28.188.153	3-act.channel.facebook.com
184.28.188.153	4-act.channel.facebook.com
184.28.188.153	5-act.channel.facebook.com
184.28.188.153	6-act.channel.facebook.com
184.28.188.153	origincache-ai-01-05-ash3.fbcdn.net
184.28.188.153	inyour-slb-01-05-ash3.facebook.com
184.28.188.153	origincache-starfacebook-ai-01-05-ash3.facebook.com
69.171.246.7	beta-chat-01-05-ash3.facebook.com
69.171.235.9	static.thefacebook.com
69.171.246.16	channel-ecmp-05-ash3.facebook.com
69.171.246.17	channel-staging-ecmp-05-ash3.facebook.com
69.171.246.18	channel-testing-ecmp-05-ash3.facebook.com
182.239.95.136	0-edge-chat.facebook.com
182.239.95.136	1-edge-chat.facebook.com
182.239.95.136	2-edge-chat.facebook.com
182.239.95.136	3-edge-chat.facebook.com
182.239.95.136	4-edge-chat.facebook.com
182.239.95.136	5-edge-chat.facebook.com
182.239.95.136	6-edge-chat.facebook.com
182.239.95.136	api-read.facebook.com
182.239.95.136	attachment.fbsbx.com
182.239.95.136	bigzipfiles.facebook.com
182.239.95.136	check4.facebook.com
182.239.95.136	check6.facebook.com
182.239.95.136	code.facebook.com
182.239.95.136	connect.facebook.com
182.239.95.136	edge-chat.facebook.com
182.239.95.136	pixel.facebook.com
182.239.95.136	star.c10r.facebook.com
182.239.95.136	star.facebook.com
182.239.95.136	zh-tw.facebook.com
173.252.74.27	b-api.facebook.com
173.252.74.27	b-graph.facebook.com
104.78.23.174	connect.facebook.net
23.32.248.41	creative.ak.fbcdn.net
173.252.102.13	d.facebook.com
31.13.95.12	ent-a.xx.fbcdn.net
31.13.95.12	ent-b.xx.fbcdn.net
31.13.95.12	ent-c.xx.fbcdn.net
31.13.95.12	ent-d.xx.fbcdn.net
31.13.95.12	ent-e.xx.fbcdn.net
72.246.188.82	fbcdn-photos-a.akamaihd.net
72.246.188.19	fbcdn-photos-e-a.akamaihd.net
23.205.168.10	fbcdn-sphotos-a.akamaihd.net
23.63.99.209	fbstatic-a.akamaihd.net
192.168.52.23	ldap.thefacebook.com
173.252.88.128	orcart.facebook.com
31.13.70.7	scontent-a-lax.xx.fbcdn.net
31.13.79.251	scontent-a-sin.xx.fbcdn.net
31.13.70.7	scontent-b-lax.xx.fbcdn.net
183.111.23.18	scontent-b-sin.xx.fbcdn.net
31.13.82.7	scontent-c.xx.fbcdn.net
31.13.95.7	scontent-d.xx.fbcdn.net
31.13.79.224	scontent-e.xx.fbcdn.net
31.13.86.4	scontent-mxp.xx.fbcdn.net
23.207.122.24	s-external.ak.fbcdn.net
23.34.45.177	s-static.ak.fbcdn.net
118.214.29.177	s-static.facebook.com
69.171.235.49	vupload.facebook.com
69.171.235.49	vupload2.vvv.facebook.com
# Facebook end

Enjoy

**Comment by DaleXiao** [comment]
works with browser but not for FB client app on iOS.

**Comment by imcaffrey** [comment]
Thanks for sharing.

**Comment by racaljk** [comment]
thx

**Comment by aofall** [comment]
#ba99772

182.239.95.136是中国移动香港的反代，人一多就挂

**Comment by imcaffrey** [comment]
和上回我加错的是一个性质吧
https://github.com/racaljk/hosts/issues/262#issuecomment-192783341

**Comment by DaleXiao** [comment]
The first time login to FBclient on iOS need VPN, then you can switch the VPN off and use FB directly. Fxxk gfw.
