### ISSUE TITLE
为什么要把默认换行符设置成crlf？

### ISSUE THREAD

**Issue by alienhjy** [racaljk/hosts#305]
在.gitattributes中发现了如下配置：
`hosts eol=crlf`
但是git的默认设置（根据本地平台自动转换）或者采用用户手动配置明显更合理。希望去除这一配置。

**Comment by alienhjy** [comment]
我发现之前的issue就有关于换行符的讨论。但是我并不是想要讨论那个换行符更优，而是觉得，能否直接设置成自动转换到本地换行符？
原因有如下几点：
1、用户使用git客户端的情况下：设置成本地换成符后，只要是用git客户端获取的hosts文件，都会被转换到本地换行符，并不会有哪个平台的用户为此感到困扰。反之，在.gitattributes中设置CRLF换行符的话却会给安卓用户和某些Linux用户带来困扰，因为安卓无法识别CRLF格式的hosts文件。
2、用户不使用git客户端的情况下：不管在.gitattributes设置成何种换行符，以目前的现状，直接在github上通过RAW按钮或者说通过https://raw.githubusercontent.com链接获取到的hosts文件，都会是Unix换行符，这一行为并不受.gitattributes影响。所以在.gitattributes中强制设置为windows换行符对于没有安装git客户端的用户并不会有什么影响。

**Comment by imcaffrey** [comment]
Thanks for informing.

**Comment by andytimes** [comment]
@alienhjy 确实是有这个问题，可以把 `hosts eol=crlf` 去除。

**Comment by imcaffrey** [comment]
我们要不要去除呢？

**Comment by andytimes** [comment]
一开始添加 .gitattribute 是为了防止 hosts 里面同时出现 CRLF 和 LF 换行符，既然有问题，还是去掉最好。
`* text=auto`
已有的这段代码可以把 hosts 的换行符归一化，所以可以放心去除。

SCaffrey <notifications@github.com>于2016年3月27日周日 下午9:27写道：

**Comment by andytimes** [comment]
顺便在 .gitattributes 最后加一句
*.gif binary

SCaffrey <notifications@github.com>于2016年3月27日周日 下午9:27写道：
