### ISSUE TITLE
更改hosts后对Chrome无效

### ISSUE THREAD

**Issue by Edenharder** [racaljk/hosts#309]
系统是Mac OS，修改hosts后safari生效但对Chrome无效。应该怎么解决呢？

**Comment by imcaffrey** [comment]
restart ?

**Comment by Edenharder** [comment]
@imcaffrey 重启系统依然无效。

**Comment by LGA1150** [comment]
Mac的换行符是\r，Win是\r\n

**Comment by Edenharder** [comment]
@LGA1150 谢谢，的确和换行有关系。已解决。

**Comment by imcaffrey** [comment]
求科普……那为啥Chrome会gg呢？

**Comment by Edenharder** [comment]
@imcaffrey 会gg什么意思？

**Comment by imcaffrey** [comment]
啊……我想问一下为啥换行会影响到chrome……

**Comment by Edenharder** [comment]
@imcaffrey 同样问题，Safari就没问题。

**Comment by Edenharder** [comment]
@imcaffrey 我之前是用[Isystem](https://github.com/royJang/iSystem)管理hosts的，时而会出现吞掉换行符的问题，然后chorme就不能用的。Safari能用不知道是缓存还是其他原因。我现在是直接从这里抓取然后替换hosts文件了，这样就不会出现换行符被吞掉的情况了。你如果还有什么疑问，我可以去测试一下。谢谢你维护这个项目。

**Comment by imcaffrey** [comment]
@Edenharder 嗯解决了就好，谢谢你的反馈
