### ISSUE TITLE
怎么用Hozz管理？

### ISSUE THREAD

**Issue by abellee** [racaljk/hosts#311]
把hosts文件的链接添加进去就OK吗？为啥下不下来

**Comment by imcaffrey** [comment]
@ppoffice

**Comment by ppoffice** [comment]
名称也是必填项

**Comment by Edenharder** [comment]
@ppoffice mac没有提供最新版，而且从本地升到最新版总会出现网络状况。

**Comment by ppoffice** [comment]
@Edenharder 因为升级包是托管到了GitHub的release上（AWS），国内可能连接性不好。你可以手动下载core.zip然后解压到`/Applications/Hozz.app/Contents/Resources/app`文件夹下面，即可升级到最新版。
