### ISSUE TITLE
Youtube视频看不了

### ISSUE THREAD

**Issue by yonbin** [racaljk/hosts#312]
Youtube视频看不了

**Comment by fluviusmagnus** [comment]
本来就不能。

这个问题已经被问过无数次了，有点不能忍：
#233 #247 #210 ……

请参考 wiki 里的解释说明：https://github.com/racaljk/hosts/wiki/The-hosts-FAQ#%E6%97%A0%E6%B3%95%E8%A7%82%E7%9C%8B-youtube-%E8%A7%86%E9%A2%91%E7%9A%84%E8%A7%A3%E5%86%B3%E6%96%B9%E6%A1%88

-------------------------
另外，既然如此是否可以考虑把这个问题放到更显眼的位置上去？总是这样也不是办法。

**Comment by imcaffrey** [comment]
@fluviusmagnus Thanks.

这种问题吧，帮我们区分出来了谁对Github比较熟练XD
