### ISSUE TITLE
hosts_tools/scripts/script_tool_for_linux.sh  中建议不默认替换所有127.0.0.1项

### ISSUE THREAD

**Issue by zhyingx** [racaljk/hosts#313]
在[ec1c48f8](https://github.com/racaljk/hosts/commit/ec1c48f8a6913ff32ed5e874fd1f373c802eeb68) 版的[linux脚本](https://github.com/racaljk/hosts/blob/master/hosts_tools/scripts/script_tool_for_linux.sh#L16) 中第16行
`  sed -i '/127.0.0.1/d' /etc/hosts ` 可能会将原 hosts 中用户设置的用来屏蔽某些域名的项覆盖掉，建议取消该行操作。

**Comment by imcaffrey** [comment]
@K-Guan 我感觉这个https://github.com/racaljk/hosts/blob/master/hosts#L9 不删掉应该没有问题吧

**Comment by racaljk** [comment]
README.MD已经提醒了注意可能覆盖原有内容所以注意备份

**Comment by qwerty258** [comment]
我也PR过一个script_tool_for_linux.sh来修复sudo can not resolve，只是替换本hosts里的127.0.0.1，结果K-Guan commit了一个他自己写的来修复 #284 的问题，我也不说什么了，把我的PR关了。

**Comment by imcaffrey** [comment]
@qwerty258 Thanks anyway.

先替换掉再加进原有的hosts是不是就好了

**Comment by K-Guan** [comment]
@qwerty258 应该是我当时没有看到吧……

不管怎么说，这个问题确实存在。怪我当时没有考虑到。

@imcaffrey  Solve this problem, as soon as possible. As you said, we can just remove the 16 line in the script as well.

**Comment by imcaffrey** [comment]
Hope this is fixed now.
