### ISSUE TITLE
[Not an issue] To laod.cn

### ISSUE THREAD

**Issue by Moriaty911** [racaljk/hosts#314]
I am the founder of EIS project (www.nflseis.com). I built this website in order to help my school mates and teachers and other people outside the school to use Google and other websites. I have included some certain websites just for our IB students such as IBO, CIE and so on. However, I found these in your website, including the facebook hosts that I posted several days ago here. I am not sure if you wrote these or cited from mine. If it is a citation, please add EIS as acknowledgement. Thank you for your cooperation.
我是EIS项目的发起人。我建立这个网站的目的是帮助我的同学，老师和校园以外的人使用谷歌等其他网站。我在我的hosts文件中加入了对于IB国际文凭课程学生经常访问的网站的解析（如IBO，CIE等），但是我却在您的网站中发现了这些一般人不会访问的网址。并且，您的网站中关于facebook的解析列表也是我前两天自己整理并发表在这里的。我不确定这是贵网站自己写的hosts还是从我的网站的引用。如果是引用的话，请在网站中标明来自于www.nflseis.com。希望我们可以互相理解，将各自的网站做得更好，谢谢！

**Comment by imcaffrey** [comment]
1. **This is not laod.cn**
2. Facebook comes from 6aa0f5cec49fd28c18608a8025baa1a91f93991d.
3. @Moriaty911 From your file I can see acknowledgement to laod.cn. Ironically https://github.com/racaljk/hosts/search?q=laod.cn&type=Issues&utf8=%E2%9C%93.
4. 被人倒打一耙的事是第一次撞见

@racaljk 弱鸡我不会处理这种事了

**Comment by imcaffrey** [comment]
Excited.

**Comment by Moriaty911** [comment]
好吧 我之前确实言辞有问题。我现在只是高二的学生 我做这个项目也只是想帮助周围的人。只是看到自己写的有些东西被别人使用之后没有附上我的网站后感到有那么一点点不爽。谢谢指点，以后会注意的

**Comment by imcaffrey** [comment]
请你确认**“是你自己写的有些东西”**

**Comment by Moriaty911** [comment]
是的 有些例如telegram openwrt 等待

**Comment by imcaffrey** [comment]
我说的是这个hosts，你检查一下自己的项目里的前几行

**Comment by Moriaty911** [comment]
行 我的错 很抱歉打扰了

**Comment by imcaffrey** [comment]
For further reference:

From hosts
```
# Copyright (c) 2014-2016, racaljk.
# https://github.com/racaljk/hosts
# https://github.com/liuker0x007/hosts
# Last updated: 2016-3-16

# This work is licensed under a CC BY-NC-SA 4.0 International License.
# https://creativecommons.org/licenses/by-nc-sa/4.0/

# https://www.nflseis.com/

# Localhost (DO NOT REMOVE)
127.0.0.1    localhost
255.255.255.255    broadcasthost
::1    localhost
fe80::1%lo0    localhost

# Modified hosts start
```

From readme.txt
```
鸣谢：
    http://www.micae.top/Under/Hjx/index.html
    http://www.laod.cn
@Moriaty911（邮箱：lqx980911@gmail.com）
@曼株沙华
```

**Comment by racaljk** [comment]
so...@imcaffrey辛苦了。

**Comment by aofall** [comment]
#205

不知道为什么看见这个issue很想笑
