### ISSUE TITLE
是否能添加github的hosts

### ISSUE THREAD

**Issue by redapple0204** [racaljk/hosts#316]
我这里无法访问，要挂vpn才可以

**Comment by imcaffrey** [comment]
这里的github的hosts失效了？
地区？

**Comment by aofall** [comment]
#286

**Comment by redapple0204** [comment]
@imcaffrey 深圳

**Comment by redapple0204** [comment]
@aofall 诶，似乎不错，我试试看

**Comment by aofall** [comment]
不是 
我的意思是不需要添加，除非你的DNS有问题
还有，我想吐槽你用的什么破网络，你所开的issue，在我这里移动电信双线路下 都无法重现。
你该查查DNS是不是有问题了，当然 如果是长城宽带 彭博士 宽带通 这类的就不用费力去查了，直接换宽带
