### ISSUE TITLE
工信部官网：公开征求对《互联网域名管理办法（修订征求意见稿）》的意见

### ISSUE THREAD

**Issue by imcaffrey** [racaljk/hosts#317]
http://www.miit.gov.cn/n1146295/n1652858/n1653100/n3767755/c4683125/content.html

**Comment by ergouge** [comment]
是不是意味着我党进一步收紧

**Comment by aofall** [comment]
做梦
CCTV、阿里巴巴、百度等公司的域名就是在国外注册的，你懂的。

**Comment by DaleXiao** [comment]
ClientHold

**Comment by fluviusmagnus** [comment]
但是完全可以采用黑名单变白名单的策略。

2016/03/28 23:52、aofall <notifications@github.com> のメッセージ:

**Comment by imcaffrey** [comment]
https://github.com/ericls/vote_against_37

**Comment by racaljk** [comment]
明面上的征求

**Comment by DaleXiao** [comment]
you can not vote actually.

**Comment by cjsoft** [comment]
只要方教授不搞新技术，该吃吃，该睡睡
