### ISSUE TITLE
google搜索不能用了么，用的是刚刚更新的hosts【gmail邮箱还可以

### ISSUE THREAD

**Issue by hwk603** [racaljk/hosts#320]
来自四川省成都市 教育网

**Comment by imcaffrey** [comment]
教育网是不是有特别的方法啊…………？

**Comment by LGA1150** [comment]
如果有IPv6，你应该使用这个 https://github.com/lennylxx/ipv6-hosts

**Comment by hwk603** [comment]
切换到成都电信后，还是不行【现在只有gmail能用

**Comment by DaleXiao** [comment]
google is fxxked by gfw, need new ip...

**Comment by Eamonnzhang** [comment]
google不能访问了，已更新为最新的Host

**Comment by potatohai** [comment]
google不能访问了，已更新为最新的Host
+1

**Comment by Ritchie1108** [comment]
更新完29号的，所有服务已跪……

**Comment by imwillhayes** [comment]
同跪

**Comment by izhangzhihao** [comment]
更新完今天的host后上不去google了

**Comment by DaleXiao** [comment]
You may global change the google ips to 64.233.162.84 or 64.233.162.83, it could work.

The current ones with 64.233.162.85/64.233.162.86 have been fxxked by gfw.

**Comment by ycraurora** [comment]
https://github.com/racaljk/hosts/blob/b4036358fa07e1a3eea995f804d2dc522e5f2172/hosts
哈尔滨教育网测试通过

**Comment by imcaffrey** [comment]
Fixed in f1944e475737439128f7ad3110da00f1f231b727. Sorry for trouble caused.

**Comment by hwk603** [comment]
我发现原来的我的问题是chrome导致的，更新到版本 49.0.2623.110 m就可以了

之前的hosts一直没有在chrome中生效，可以ping通，但无法访问。直到我用edge打开了Google，才发现问题。

【虽然我并不知道为什么chrome突然就出问题的原因】
