### ISSUE TITLE
请求添加一个通用的windows console程序来替换和下载hosts文件

### ISSUE THREAD

**Issue by Too-Naive** [racaljk/hosts#321]
RT
如果需要 我会推PR

**Comment by redapple0204** [comment]
不是有了吗

**Comment by Ritchie1108** [comment]
我用的是 tools 里头的 QT 工程修改来的，顺便把 highsea 的源扔了进去。

**Comment by Too-Naive** [comment]
讲道理 没编译器用户是不是只能用麻烦的bat阿 @redapple0204

**Comment by HarveyTvT** [comment]
@Too-Naive powershell比bat简单不少

**Comment by Ritchie1108** [comment]
@Too-Naive bat全程自动处理，有什么可麻烦的？唯一麻烦的一点就是每次生成备份文件了吧。

**Comment by Too-Naive** [comment]
@Ritchie1108 #300

**Comment by imcaffrey** [comment]
@Too-Naive Thanks.

**Comment by Too-Naive** [comment]
@imcaffrey 能推吗.............

**Comment by imcaffrey** [comment]
@Too-Naive  think opening PR is available for everyone.

**Comment by qwerty258** [comment]
有翻墙需要的基本是有相关知识的，什么编码问题、脚本问题基本不是问题。
有时间的可以搞个C的console字符界面程序，通吃win和Linux，Http请求下载hosts直接自己socket写个，自动判断操作系统转换编码和换行符。

**Comment by Too-Naive** [comment]
1. 不会写linux的socket 
2. 没有测试环境

如果愿意 我可以弄成windows服务版 每次启动都检查hosts文件的更新

**Comment by Ritchie1108** [comment]
@Too-Naive 闪退这个是编码问题，你这边提到 bat 的时候我就去试了一下（一直用的是 QT 编译的工具，没用过批处理），一开始闪退，用 ST 打开设置了下编码格式保存，再打开就正常了。很抱歉在通用性上我确实没把这个考虑进去。#滑稽

**Comment by Too-Naive** [comment]
@Ritchie1108 目前bat的短板就是这个 然后。。。没有编译器的用户却只能用bat

**Comment by Too-Naive** [comment]
我已经写好了。。等晚上把我这的无法自动合并弄下 就提交PR

**Comment by SatanSec** [comment]
自己写了几行python脚本用来更新linux下的hosts

**Comment by luoye-fe** [comment]
https://github.com/luoye-fe/myhosts
自己写的node平台下的更新脚本，全平台，如果安装了node的话。。。

**Comment by Too-Naive** [comment]
@luoye-fe 还是得有前提阿.....

**Comment by Too-Naive** [comment]
@SatanSec 也是要有python阿。。。。

**Comment by luoye-fe** [comment]
哈哈 那没办法，node的安装算简单的了。。

**Comment by Too-Naive** [comment]
@luoye-fe 讲道理...其实要能直接运行的文件 就好像script一样 只要符合系统就好

**Comment by Too-Naive** [comment]
@imcaffrey PR已经写好 可以合并了

**Comment by Too-Naive** [comment]
果然我还是太天真了 忘记写文件判断了

**Comment by imcaffrey** [comment]
你冷静

**Comment by Too-Naive** [comment]
嘿嘿嘿 在补 顺便找找还有没有不完善的bug

**Comment by Too-Naive** [comment]
真·Ready to merge.

**Comment by qwerty258** [comment]
1. 修复GNU可变参数宏语法和微软编译器语法不兼容问题。
2. 修复welcomeShow宏乱码问题。
3. 增加VS工程文件。
#341
关于提权到管理员，查了下有个Manifest Files，但一时半会没搞明白，以后再开PR。
@Too-Naive @imcaffrey

**Comment by qwerty258** [comment]
要使程序启动时就请求管理员权限，貌似只能用VS来编译程序，在"Project Property - Linker - Manifest File - UAC Execution Level"中设置，这样就不用ShellExecute来提权了。
@Too-Naive

**Comment by imcaffrey** [comment]
Good Job.

**Comment by Too-Naive** [comment]
@qwerty258 你的代码我还没看 所以我只说一点 程序的目的 特别是控制台程序 应当每一个编译器的效果编译出来都应一样才对吧 并不是所有人都用得起vs(手动微笑)

**Comment by Too-Naive** [comment]
代码生而平等 而不应不可移植

**Comment by qwerty258** [comment]
加宏判断，有_MSC_VER的就不走Shellexecute，再说除了程序员谁会拿源码来自己编译，伸手党肯定拿release里的exe。
说到移植性，我也不说什么了。

**Comment by Too-Naive** [comment]
@imcaffrey 我晚些时候会推PR 做关键更新

**Comment by imcaffrey** [comment]
恭喜你俩都找到了<>的头像

**Comment by Too-Naive** [comment]
smg @imcaffrey

**Comment by Too-Naive** [comment]
@qwerty258 事实上。。。不需要用VS编译。。。加一个.manifest文件就好了........

**Comment by Too-Naive** [comment]
@imcaffrey 应该可以标记为status-completed? 我关了这个issue吧....
