### ISSUE TITLE
Google IP 64.233.162.85 失效

### ISSUE THREAD

**Issue by chy9002** [racaljk/hosts#322]
上海电信无法通过64.233.162.85访问Google

$ ping www.google.com
PING www.google.com (64.233.162.85): 56 data bytes
Request timeout for icmp_seq 0
Request timeout for icmp_seq 1
Request timeout for icmp_seq 2
Request timeout for icmp_seq 3
Request timeout for icmp_seq 4
Request timeout for icmp_seq 5
^C
--- www.google.com ping statistics ---
7 packets transmitted, 0 packets received, 100.0% packet loss

**Comment by DaleXiao** [comment]
try 64.233.162.83 or 64.233.162.84

**Comment by imcaffrey** [comment]
Fixed in f1944e475737439128f7ad3110da00f1f231b727. Sorry for trouble caused.

**Comment by DaleXiao** [comment]
not your fault at all, let's fxxk GFW harder.

**Comment by chy9002** [comment]
@imcaffrey 没有别的意思，只是单纯的发现问题，提交issue。😊

**Comment by imcaffrey** [comment]
@chy9002 窝也没有别的意思啊
