### ISSUE TITLE
吐槽

### ISSUE THREAD

**Issue by imcaffrey** [racaljk/hosts#326]
1. nflseis的全文引用以及`中国领先的免费域名解析服务提供者`/`全网首发` && #314
2. 在我的不懈努力下，laod已经在评论区屏蔽了`https://github.com/racaljk/hosts`
 #249 #271 #84 https://github.com/racaljk/hosts/issues/181#issuecomment-176087770 
3. 
```
那是自然的咯。这边加了什么功能，它马上扒过去合并了。它那边加了什么却不会贡献出来给其他人用，久而久之，不就是它那边功能更多了吗。

一直以来我什么都没说是因为我对他还有点希望，所以得给他一点面子不是。一开始我还只是纳闷他为什么不发 pull request，过了一段时间我才明白，这个世界上也有这一类的人。不尊重 GPL 就算了，把作者名字换成自己的，还在主页上加上官方的字样。为什么我们这边反而不说官方呢？因为我希望这个项目是没有官方的，人人都是贡献者。想不到这个社会人人都围着官转，人人都巴不得当官 。

既然他没有尊重别人劳动成果的意愿，那他那些不开源的理由想必也只是借口。说因为加了一些试验性功能会不兼容所以暂不开源。他弄了一个混淆 TCP 协议头功能，在界面上标注提升安全性，吸引用户打开，然后安装他自己的不兼容服务端。然而我分析了一下之后发现这个功能的设计就是想当然，用得多了以后反而会增加特征。如果你真有什么试验性功能，不是更应该开放出来让所有人帮你分析么，大家一起讨论么？在加密算法领域，只有经过足够多人和机构的审视的算法，才能视作是安全的，闭门造出来的怎么能用。。

当然啦，大部分用户才不会管这些，他们不会分析你是不是真的安全，也不会做道德判断，只要他们觉得好用就行。所以可以看到，这种环境下开源其实并没有什么优势，只不过为一些人抄袭提供了便利。这种环境下最后留下来的都是这些人。

我一直想象的那种大家一起来维护一个项目的景象始终没有出现，也没有出现的迹象。维护这个项目的过程中，遇到 @chenshaoju 这样主动分享的同学并不多。很多来汇报问题的人是以一种小白求大大解决问题，解决完就走人的方式来的，然而既不愿提供足够的信息，也不愿写一些自己尝试的过程供后人参考。互帮互助的气氛就是搞不起来。对比下国外的社区差好远。

最适合这个民族的其实是一群小白围着大大转，大大通过小白的夸奖获得自我满足，然后小白的吃喝拉撒都包给大大解决的模式。通过这个项目我感觉我已经彻底认识到这个民族的前面为什么会有一堵墙了。没有墙哪来的大大。所以到处都是什么附件回帖可见，等级多少用户组可见，一个论坛一个大大供小白跪舔，不需要政府造墙，网民也会自发造墙。这尼玛连做个翻墙软件都要造墙，真是令人叹为观止。这是一个造了几千年墙的保守的农耕民族，缺乏对别人的基本尊重，不愿意分享，喜欢遮遮掩掩，喜欢小圈子抱团，大概这些传统是改不掉了吧。

现在维护这些项目已经越来越让我感到无趣。我还是努力工作，好好养家，早日肉翻吧。
```

-----

`1. nflseis的全文引用以及中国领先的免费域名解析服务提供者/全网首发 && #314`
--> 1. **之前**`nflseis`的全文引用以及`中国领先的免费域名解析服务提供者`/`全网首发` && #314
3. 这里面这段话是大家很熟悉的一位前辈说的吧

**Comment by Too-Naive** [comment]
买流量D?  或者来个分布式的？

**Comment by imknown** [comment]
理性 辩证 :earth_americas:

**Comment by DaleXiao** [comment]
Please do not stop maintaining the project, it means a lot to us.

**Comment by DaleXiao** [comment]
Just noticed that the guy LaoD even blocked the key word '抄袭' in the comment area of his blog, what a real mother fxxker!

**Comment by fluviusmagnus** [comment]
那些学生向来的傲气我是知道的，单纯只是 naïv 的话也就算了。

至于“小白求问”之类的，这都算是普遍存在的“伸手党”吧，这些人帐号往往是新的。以（或许只是自我认定的）能力不足为掩护，堂堂进行着懒惰或自私的活动。而那些商人们正好迎合上去促成这廉价的交易，满足自己（或许只是自我认定的）优越感。买卖者的时间都是如此廉价，好让这种交易遍地发生。作为规则的制定者、实践者、受益者，他们自然维护这种秩序的存在。然而其中并没有任何东西被创造出来，作为群体总量的精力却白白耗费了，这也就是其悲哀之处。当然我们不应该宣扬什么强者逻辑，但事实上的能力不足者占多时、成为“乌合之众”时，我们究竟应该怎么做，应该如何守护开源的精神，这确实是当下一大值得思考的问题。

就事论事。其实很多来 GitHub 开各种 issue 来问（或许）幼稚问题的已经是“小白”中的强者了，他们已经懂得追本溯源地探求一个问题，或者被人介绍过来，但在最后一步被打回原形，以为这里的运作逻辑是一样的。这或许不完全是他们的错，而与 GitHub 这个环境本身的特点有关。这个网站，或者放大了说，整个开源世界，其主要面向的用户都是开发者而不是最终用户，而二者的行为模式是不同的。开发者会有意识地查看 wiki，一些对于他们而言常识性的东西在文档中也许就不会写，开 issue 讨论的问题通常都不会是关于使用方法的疑惑，而最终用户的行为可能与之恰恰相反。为了分离这两类用户，减少维护的负担，有条件的有大量交流需求的大中型项目都会面向广大公众另外再建一个网站。抛开问题的实际回答者是否最具发言权的问题不谈，这确实是容易想到的一种良好出路，然而对于小型项目或者在内容上不太适合的项目而言，其风险和成本就太大了。关于这一点，我也没有想明白，且一直带着无解的隐忧。

言辞可能有不当之处，欢迎各位继续讨论。

**Comment by DaleXiao** [comment]
Big thanks to all the contributors anyway, we can't stop people from stealing things, but we can show our respect to the ones who has been helping us.

**Comment by lautis0503** [comment]
向各位貢獻者致敬

**Comment by Edenharder** [comment]
致敬。自己小白，能做的就是把问题状况写清楚吧。

**Comment by 1dot75cm** [comment]
是否应该把 laod 写入 Wiki，然后在贴吧宣传一下？ 虽然我知道贴吧迟早药丸。

**Comment by racaljk** [comment]
@fluviusmagnus :+1: 一切都是因为Github面向对象不同所致，与不同行为特征的群体讨论版权真的意义不大

**Comment by imcaffrey** [comment]
@1dot75cm 其实仔细想想没有必要吧

**Comment by DaleXiao** [comment]
It's hard to change the other people, all what we could do is to make ourselves a little better, which might eventually make the this world a tiny tiny tiny tiny better, thanks to all.

**Comment by imcaffrey** [comment]
I can see that our closest friend has appeared with #334. Welcome.

Thanks to everyone.

**Comment by Too-Naive** [comment]
那些人很重视自己的权利保护 但是却选择性无视别人的权利被侵犯(手动滑稽)

**Comment by outnnn** [comment]
@imcaffrey 老d这人做人很差，建议公开一下，让我知道他是谁，为什么用hosts搞捐赠，弄的自己很辛苦一样

**Comment by outnnn** [comment]
@fluviusmagnus  hosts以前有使用过，后来觉得不方便，自己搭建了vpn，很多小白确实是伸手党，思维模式跟玩qq空间的那种一样，碰巧让laod遇见。所以他们各有索取，没有合作互助的和共同解决问题的精神。

也许这就是真正的“”墙”希望这是一个过渡。

**Comment by fluviusmagnus** [comment]
@outnnn 我觉得此事暂且就这样吧，“**现在**laod处理得还是比较到位的” (#205)。

况且，我们在这里能做的其实只是一点微小的工作，如果让事情超出**具体问题**自身的话，可是拿不出所谓的**解决方案**的啊。

**Comment by imcaffrey** [comment]
感谢大家！
