### ISSUE TITLE
报告，Fb扑街

### ISSUE THREAD

**Issue by wolfan** [racaljk/hosts#330]
报告，新的FbHosts扑街了，还是要回滚前前次的才行。

**Comment by imcaffrey** [comment]
@wolfan 前前次是哪一次呢……？

**Comment by SmattCheng** [comment]
这两天Google和Fb都不稳定啊

**Comment by wolfan** [comment]
@imcaffrey (￣▽￣|||) 好像是我机器上的缓存……不过我吃晚饭的时候用的还是17号的，能正常访问Fb，但是码完字后Google挂了换新的后就不行了。。

**Comment by andytimes** [comment]
已更新
