### ISSUE TITLE
能ping 得通，设了hosts 确还是不能上google？求解

### ISSUE THREAD

**Issue by IssaTan1990** [racaljk/hosts#337]
如题

![qq 20160401214439](https://cloud.githubusercontent.com/assets/10755797/14208651/026bec90-f853-11e5-8d26-d271195e6eac.png)

**Comment by Too-Naive** [comment]
是不是`ERROR_CONNECTION_RESET`(`ERROR_CONNECTION_ABORT`)阿…… 在前面加`https://`

**Comment by lavender1203** [comment]
一般情况几个问题要注意：用火狐或谷歌浏览器，地址前面加https://   地址后面加/ncr  比如https://www.google.com/ncr

**Comment by imcaffrey** [comment]
以及刷新dns

**Comment by TylerYang** [comment]
@lavender1203  感谢，为啥加ncr 就可以？

**Comment by lavender1203** [comment]
@TylerYang 如果谷歌检测到你是外国或外地的用户,它会自动转到你所在区域的谷歌页面.这对大部分人来说是合理的,但是,如果所在区域谷歌页面被禁了或不存在就不行,加ncr就是使用国际版的页面不进行跳转.

**Comment by TylerYang** [comment]
@lavender1203 原来如此...

**Comment by fish4j** [comment]
Safari 可以改google search的默认URL吗？Chrome实在是太耗电了

**Comment by TylerYang** [comment]
@fish4j 

Open Safari, go to Safari menu > Preferences > General, and put Google as the homepage. Then, choose Google as your default search engine. (来自苹果官网)

**Comment by fish4j** [comment]
@TylerYang 
我也搜到了这个，一直设置不成功。
最后找到个方法，需要先把默认的search改成非google，然后去General里面设置google为主页，最后再把search改成google就可以了。如果改主页之前search是google，重新设置了主页也不生效。
