### ISSUE TITLE
可以上GMail，但是上不了Google首页

### ISSUE THREAD

**Issue by pdcxs** [racaljk/hosts#342]
无法打开：www.google.com以及www.google.com.hk

**Comment by imcaffrey** [comment]
1. https
2. https://www.google.com/ncr
3. flushdns
4. try 114.114.114.114, etc
5. restart
6. Qrz

**Comment by pdcxs** [comment]
https works. Thanks a lot.

**Comment by imcaffrey** [comment]
Congrats.
