### ISSUE TITLE
supl.google.com 已挂

### ISSUE THREAD

**Issue by LGA1150** [racaljk/hosts#349]
7276端口不通

**Comment by aofall** [comment]
好像是 和216.239.38.12x 一样被TCP Drop了

**Comment by aofall** [comment]
还有一系列的Stun server
64.233.177.127 19305端口不通

**Comment by lautis0503** [comment]
陕西联通，7276不通，19305正常

**Comment by andytimes** [comment]
国内最好别用 supl.google.com，速度很慢。可以用 Nokia 的 supl 服务器替代
supl.nokia.com

**Comment by ygqsgm** [comment]
@andytimes 能直接改hosts实现吗？把supl.google.com 指向 supl.nokia.com?

**Comment by LGA1150** [comment]
@ygqsgm 
不行，端口不一样

**Comment by aofall** [comment]
Google的A-GPS应该是通过重定向才用的7276端口吧（猜测）
还没给这个项目贡献hosts前我扫过192的端口 同时开放80和7272
后来改成7276了 80还是开的
再者轻易改端口会导致旧版软件无法正常使用

------

最大的问题应该是服务端绑定了域名，非绑定域名不返回正常结果
