### ISSUE TITLE
host地址打不开

### ISSUE THREAD

**Issue by cikichen** [racaljk/hosts#352]
https://raw.githubusercontent.com/racaljk/hosts/master/hosts 打不开

**Comment by lautis0503** [comment]
打不开的时候可访问coding的镜像
https://coding.net/u/scaffrey/p/hosts/git/raw/master/hosts

**Comment by imcaffrey** [comment]
Github好像今天不太顺畅= =

**Comment by Too-Naive** [comment]
爆炸= = 主要原因是访问不了`https://assets-cdn.github.com`

![](http://i4.piimg.com/3e2dfb80df8ed713.png)

**Comment by andytimes** [comment]
我这里打开 Github， 所有图片无法显示。查实是 @Too-Naive 所说的原因

**Comment by Too-Naive** [comment]
@andytimes GG 对了 上次说的提权 我把.manifest嵌入可执行文件之后就可以直接提权不用调用`ShellExecute`了

**Comment by andytimes** [comment]
@Too-Naive Windows 平台编程不懂，没学过相关知识。日后如果有机会学习，可以继续深入讨论 : )

**Comment by BROBIRD** [comment]
@Too-Naive 
https://assets-cdn.github.com/*
https://*.githubusercontent.com/*
连接被重置，不知道是不是因为GFW

**Comment by Too-Naive** [comment]
@BROBIRD 感觉是dn污染 中午用电脑解析地址看看 除了头像以外 我这其他都正常了

**Comment by BROBIRD** [comment]
@Too-Naive 我这还是不行 连接被重置

**Comment by andytimes** [comment]
应该不是 G||FW 的问题，昨晚十点左右的一段时间无法登陆 Github，可能是被 DDOS 攻击 （个人猜测）。刚刚出现的问题和 DDOS
攻击后的状况大致相同。

assets-cdn.github.com/* 我这里已经可以访问。
**.githubusercontent.com <http://githubusercontent.com/> 还是直接丢包。*

TooSimple <notifications@github.com>于2016年4月6日周三 上午11:42写道：

**Comment by BROBIRD** [comment]
@andytimes 你用Wireshark看一下，我这边确实是链接重置，不是丢包，ping是可以ping通的

**Comment by andytimes** [comment]
@BROBIRD 恩，不是丢包，是链接重置。

**Comment by BROBIRD** [comment]
@andytimes 坑爹的FireFox死活加载不了PAC，搞得我加了规则也用不了，真TM坑，有谁知道怎么处理么

**Comment by Too-Naive** [comment]
@BROBIRD 还是连不上github吗。。。我这边时稳定时不稳定 可以把github.com的地址都写入hosts里面..

**Comment by Too-Naive** [comment]
昨天是github机房断线来着

**Comment by andytimes** [comment]
@BROBIRD 可能是你的获取 PAC 规则更新的地址无法访问，可以替换成 https://raw.githubusercontent.com/gfwlist/gfwlist/master/gfwlist.txt

不过目前这个地址暂不可用，你可以去
https://github.com/gfwlist/gfwlist 拷贝源文件，或者做一个镜像。

**Comment by Too-Naive** [comment]
@andytimes 可用。。其实 把raw*塞进去hosts就可用了....

**Comment by Too-Naive** [comment]
想求一个联系github官方的方式来反映他们解析ip出来的问题...

**Comment by BROBIRD** [comment]
@andytimes 不是的，我用的SSR，如果用GFWList那个PAC，火狐就加载不了PAC，用其他的可以，我也不知道怎么回事
贴个错误信息看看有没有人知道为什么
`PAC Execution Error: mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create []
PAC Execution Error: uncaught exception: out of memory []
PAC file failed to install from http://127.0.0.1:1080/pac?t=201604061314295770`

**Comment by BROBIRD** [comment]
@Too-Naive https://github.com/contact    https://help.github.com/

**Comment by Too-Naive** [comment]
你们用的ip都是`114.114.114.114`? 我觉得这个dns有毒

**Comment by Too-Naive** [comment]
临时解决方案:
```

23.235.44.133 assets-cdn.github.com
23.235.44.133 raw.githubusercontent.com
23.235.44.133 avatars2.githubusercontent.com
23.235.44.133 avatars0.githubusercontent.com
23.235.44.133 camo.githubusercontent.com
```

以下是解析的ip列表:
```
github.map.fastly.net		A	199.27.79.133	30s
github.map.fastly.net		A	23.235.46.133	30s
github.map.fastly.net		A	23.235.44.133	30s
github.map.fastly.net		A	23.235.43.133	30s
github.map.fastly.net		A	185.31.18.133	30s
github.map.fastly.net		A	23.235.47.133	30s
github.map.fastly.net		A	23.235.33.133	30s
github.map.fastly.net		A	185.31.17.133	30s
github.map.fastly.net		A	23.235.39.133	30s
github.map.fastly.net		A	185.31.19.133	30s
github.map.fastly.net		A	23.235.37.133	30s
github.map.fastly.net		A	199.27.76.133	30s
github.map.fastly.net		A	23.235.40.133	30s
github.map.fastly.net		A	103.245.222.133	30s
```

**Comment by andytimes** [comment]
@Too-Naive 感谢，已提交进 hosts。

**Comment by andytimes** [comment]
github.map.fastly.net    103.245.222.133
链接重置应该是解析到这个 IP 的原因。

**Comment by BROBIRD** [comment]
@andytimes  是的

**Comment by Too-Naive** [comment]
我 换 了 一 个 DNS 问 题 就 解 决 了 

114.114.114.114有毒

**Comment by BROBIRD** [comment]
@Too-Naive  诡异的是电信解析到这个IP好像没问题

**Comment by BROBIRD** [comment]
@Too-Naive 你是哪一个DNS？我看了一下主流的Public DNS解析出来都是103.245.222.133

**Comment by fluviusmagnus** [comment]
可能是 GitHub 自己的问题吧，最近感觉各种不正常。参见 https://status.github.com/messages

**Comment by Too-Naive** [comment]
`218.85.157.99`

**Comment by BROBIRD** [comment]
@Too-Naive 福建电信？算了，先用hosts吧……

**Comment by Too-Naive** [comment]
@BROBIRD 我之前用114阿。。。 用了218后腰不酸腿不疼了

**Comment by lcqghb** [comment]
我不知道怎么订阅的racaljk/hosts，现在邮箱总是收到邮件，现在很烦恼，请问下怎么才可以取消






在2016年04月06 14时18分, "Andy Deng"<notifications@github.com>写道:



github.map.fastly.net    103.245.222.133
链接重置应该是解析到这个 IP 的原因。

**Comment by lcqghb** [comment]
我不知道怎么订阅的racaljk/hosts，现在邮箱总是收到邮件，现在很烦恼，请问下怎么才可以取消






在2016年04月06 13时20分, "BROBIRD"<notifications@github.com>写道:



@Too-Naivehttps://github.com/contact    https://help.github.com/

**Comment by lautis0503** [comment]
似乎正常了

**Comment by imcaffrey** [comment]
@lcqghb 停止watch 或者到settings里设置自己的提醒设置
https://github.com/settings/notifications

**Comment by BROBIRD** [comment]
@andytimes @imcaffrey 103.245.222.133 已经恢复正常

**Comment by andytimes** [comment]
@BROBIRD 已经处理。

**Comment by lautis0503** [comment]
陕西联通， raw.githubusercontent.com 不定时出现链接重置，更换IP无效，还有 reddit 也如此。最近审查加强了？

**Comment by Too-Naive** [comment]
按道理说github应该不在屏蔽的范围 @lautis0503

**Comment by imcaffrey** [comment]
"按道理说"

**Comment by Too-Naive** [comment]
@imcaffrey 不讲道理！！

**Comment by BROBIRD** [comment]
@Too-Naive 居然换了头像……

**Comment by Too-Naive** [comment]
@BROBIRD qwq难道您喜欢原来的那个吗...

**Comment by imcaffrey** [comment]
你俩说的显然不是同一个【

**Comment by BROBIRD** [comment]
@Too-Naive 不不不，我表达一下惊讶……（不是很懂你们二次元）

**Comment by imcaffrey** [comment]
“你根本就不是司机！”

**Comment by BROBIRD** [comment]
GitHub开车指日可待？

**Comment by Too-Naive** [comment]
@BROBIRD github有举报功能噢~

**Comment by Too-Naive** [comment]
老司机无所畏惧 @imcaffrey @BROBIRD

**Comment by imcaffrey** [comment]
Now please stop spam this issue. XD
