### ISSUE TITLE
Hosts Tool for Windows console problem.

### ISSUE THREAD

**Issue by Too-Naive** [racaljk/hosts#354]
In windows xp,  Install service success but unable to download hosts file.
`GetLastError()` returned value: 183

**Comment by racaljk** [comment]
其实大可不必考虑xp

话说那个东西不是你弄的么...

**Comment by Too-Naive** [comment]
是我做的....不过我找不出错误何在 所以开issue看看有没有高人指点.....
其实代码本来就是兼容的 我想 既然是自己写的代码 就把它尽可能完善咯

**Comment by andytimes** [comment]
@Too-Naive 加上 -g，-O0 编译，用 GDB 调试。

**Comment by andytimes** [comment]
@Too-Naive 貌似 XP 很多人还在用。上次我拜访一位长辈，给她装了 Chrome，把 IE 从桌面删除了，后来用不惯 Chrome，还主动给我打电话问我怎么把 IE 图标放到桌面。

**Comment by lautis0503** [comment]
https://msdn.microsoft.com/en-us/library/windows/desktop/aa363858(v=vs.85).aspx

**Comment by racaljk** [comment]
连我爸妈那样的老古董都在用win7...

**Comment by imcaffrey** [comment]
中考计算机考的是xp系统……于是学校都是xp= =

**Comment by Too-Naive** [comment]
@andytimes 正常状态正常。 服务模式的时候就出错

**Comment by Too-Naive** [comment]
@lautis0503 不是`CreateFile`是`InternetOpenUrl` 好不容易跟到。。

**Comment by Too-Naive** [comment]
我开始郁闷了阿。。
我看了一下`CreateFile`可能会返回183
但是...............
```c++

	if (!(hWeb=InternetOpen(___userAgent,INTERNET_OPEN_TYPE_PRECONFIG,NULL,NULL,0))) return false;
	if (!(hRequest=InternetOpenUrl(hWeb,url,NULL,0,INTERNET_FLAG_DONT_CACHE,0))){
		InternetCloseHandle(hWeb);
		return false;
	}
	if ((hdFile=CreateFile(file,GENERIC_WRITE,0,NULL,CREATE_ALWAYS,FileAttributes,NULL))==INVALID_HANDLE_VALUE){
		InternetCloseHandle(hWeb);
		InternetCloseHandle(hRequest);
		return false;
	}
```
按道理说应该不会导致程序失败吧。。。。。 而且 在win7是正常的..

**Comment by aofall** [comment]
讲道理 XP的支持和兼容性就不该被考虑
即使他在中国的占有率依旧很大
可以加速更新系统的进度

**Comment by andytimes** [comment]
@aofall 讲个题外话，很多人根本不 care 他们的 PC 装的是什么系统、、、

回归正题，
@Too-Naive 我记得在 Windows 安装 VS 2015 的时候，XP 的 SDK 独立的，不知道是不是 API 有差异，毕竟 XP 的权限管理不太一样。还有安全软件有没有可能阻止写入 hosts 都可以考虑考虑。



一开始就只维护一个跨平台的多好，也就没这么麻烦了。

**Comment by Too-Naive** [comment]
@aofall 因为我本身就是在winxp下编程的………所以我要着重考虑winxp 毕竟在我看来xp不好的的话 别的平台也好不到哪里去(我在学校没有别的平台测试)
@andytimes  权限无所谓 manifest都是通用的 这个我试过(早些版本的代码有区分xp和xp以上的行为) 而我的程序 既然不是用新型API就应该把他能做到全平台通用 (如果能帮我测试我那个程序就更好了qwq)
BTW,此issue反馈的问题暂时已经解决 @imcaffrey 可标记为status-completed 了
