### ISSUE TITLE
Youtube官网能打开 但是无法播放里面的视频

### ISSUE THREAD

**Issue by mingweiLIU** [racaljk/hosts#357]
您好，发现最新的host虽然能打开youtube.com，但是无法播放里面的视频，是不是还有部分其他的ip没有被包含？

**Comment by andytimes** [comment]
@mingweiLIU Youtube 缓存视频的 IP，不能用 hosts 重定向，看视频请挂代理。

**Comment by mingweiLIU** [comment]
额 好的 谢谢
