### ISSUE TITLE
请求添加feedly相关域名和IP

### ISSUE THREAD

**Issue by whinamp** [racaljk/hosts#36]
如题，为啥这一版取消了对feedly的支持？

**Comment by andytimes** [comment]
feedly并没有被墙，可能是你的地区问题;
PING feedly.com (198.41.247.160) 56(84) bytes of data.
64 bytes from 198.41.247.160: icmp_seq=1 ttl=127 time=874 ms
64 bytes from 198.41.247.160: icmp_seq=2 ttl=127 time=356 ms
64 bytes from 198.41.247.160: icmp_seq=3 ttl=127 time=325 ms
64 bytes from 198.41.247.160: icmp_seq=4 ttl=127 time=416 ms
64 bytes from 198.41.247.160: icmp_seq=5 ttl=127 time=311 ms
^C
--- feedly.com ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 10065ms
rtt min/avg/max/mdev = 311.568/456.911/874.359/211.843 ms

如果还是无法访问，试着像


whinamp <notifications@github.com>于2015年9月8日周二 下午10:55写道：

**Comment by dodopeng** [comment]
feedly的确没有被墙，依然能够访问。






发自 Windows 邮件





发件人: Andy Deng
发送时间: ‎2015‎年‎9‎月‎9‎日 ‎星期三 ‎9‎:‎30
收件人: racaljk/hosts




feedly并没有被墙，可能是你的地区问题; 
PING feedly.com (198.41.247.160) 56(84) bytes of data. 
64 bytes from 198.41.247.160: icmp_seq=1 ttl=127 time=874 ms 
64 bytes from 198.41.247.160: icmp_seq=2 ttl=127 time=356 ms 
64 bytes from 198.41.247.160: icmp_seq=3 ttl=127 time=325 ms 
64 bytes from 198.41.247.160: icmp_seq=4 ttl=127 time=416 ms 
64 bytes from 198.41.247.160: icmp_seq=5 ttl=127 time=311 ms 
^C 
--- feedly.com ping statistics --- 
5 packets transmitted, 5 received, 0% packet loss, time 10065ms 
rtt min/avg/max/mdev = 311.568/456.911/874.359/211.843 ms 

如果还是无法访问，试着像 


whinamp <notifications@github.com>于2015年9月8日周二 下午10:55写道：
