### ISSUE TITLE
求加入rhcloud.com 

### ISSUE THREAD

**Issue by wushilong** [racaljk/hosts#367]
求加入rhcloud.com

**Comment by Too-Naive** [comment]
是关键字屏蔽吗? @imcaffrey

**Comment by imcaffrey** [comment]
的确是跳转的吧

**Comment by Too-Naive** [comment]
那应该可以直接连接到嘛....(之前我连接也是ERROR_CONNECTION_ABORT)

**Comment by lautis0503** [comment]
没被墙啊，直接跳转openshift了

**Comment by Typl** [comment]
我这边有一台电脑在UAC提权的时候直接跳过了，没有进行询问然后script_tool_for_windows.bat就不能用了，这是怎么回事呢？

**Comment by Too-Naive** [comment]
已经确认没有被墙啦 如果还是连不上的话 换个DNS吧...........
