### ISSUE TITLE
[May not an issue]About hosts_tools 文件夹排布

### ISSUE THREAD

**Issue by Too-Naive** [racaljk/hosts#368]
如果我要是再加个linux C++的tool 那tool的文件夹要怎么命名阿qwq 
`HostsToolForLinux`滋磁吗 
可是我还是觉得那README.md文字排版有点..乱...阿...强迫症吗....qwq

**Comment by imcaffrey** [comment]
说实话我感觉没必要，现在用sh脚本已经足够方便了

**Comment by Too-Naive** [comment]
嘿嘿嘿 那就不写了 我close掉好了

**Comment by racaljk** [comment]
的确有点乱了，可以统一一个文件夹命名规范如Appname@author
eg. HostsMinerForLinux@github

**Comment by Too-Naive** [comment]
阿 @能放在里面吗… 没试过呢
