### ISSUE TITLE
bug, for windows version

### ISSUE THREAD

**Issue by wang20150419** [racaljk/hosts#370]
hosts_tool.cpp, line 441
      _stprintf(szline, "%s %s",buf2,szParameters[11]),
compile using vs2015, error: 
     error C2664: 'int _swprintf(wchar_t *const ,const wchar_t *const ,...)': cannot convert argument 2 from 'const char [6]' to 'const wchar_t *const '

fixed:
       _stprintf(szline, _T("%s %s"),buf2,szParameters[11]),

**Comment by imcaffrey** [comment]
cc @Too-Naive

**Comment by Too-Naive** [comment]
我讨厌VS @imcaffrey

**Comment by Too-Naive** [comment]
Thank you for the feedback. @wang20150419

**Comment by imcaffrey** [comment]
可啪……我怎么了

**Comment by Too-Naive** [comment]
不 就单单吐槽VS
BTW 不可啪 不可啪qwq|･ω･｀)

**Comment by Too-Naive** [comment]
Solved, Thanks again @wang20150419 .

**Comment by qwerty258** [comment]
这是C++语法检查吧，传参类型不同肯定报错，g++我觉得也会报错，和VS有什么关系……

**Comment by Too-Naive** [comment]
@qwerty258 VS预定义UNICODE

**Comment by qwerty258** [comment]
UNICODE定义只是决定了_stprintf和_T这两个宏是由那个函数来替换，宏替换后语法是否合法还是由编译器检查。
@Too-Naive

**Comment by Too-Naive** [comment]
这我知道呀... @qwerty258
