### ISSUE TITLE
Hosts Tool bug report 

### ISSUE THREAD

**Issue by Too-Naive** [racaljk/hosts#372]
@Typl :
>我这边有一台电脑在UAC提权的时候直接跳过了，没有进行询问然后script_tool_for_windows.bat就不能用了，这是怎么回事呢？

**Comment by Too-Naive** [comment]
@Typl 我把你原来在另一个issue下的问题移到这里来了
您能不能详细说说是怎么回事 关于这个"我这边有一台电脑在UAC提权的时候直接跳过了" ?

**Comment by Typl** [comment]
用批处理命令的时候刚开始是进行UAC提权（WIN），然后会弹出用户账户控制，我同事的电脑没有弹出用户账户控制这一步，然后dos就在从github下载文件那一步停了。可能是刚装的系统hosts文件被隐藏了吧，现在是文件替换失败，用户权限无法修改，还是手动修改hosts文件吧

**Comment by Too-Naive** [comment]
阿 一个可行的方法是用windows console的程序来代替那个脚本 脚本总是有各种奇怪的错误
BTW：您和同事的操作系统是？

**Comment by imcaffrey** [comment]
这波强行安利我给满分

**Comment by Too-Naive** [comment]
@imcaffrey 谢谢 真是不好意思qwq(偷笑(逃

**Comment by Too-Naive** [comment]
@Typl 已经修改了域名 您可以再试试新的bat脚本
