### ISSUE TITLE
A Universal Hosts Tool

### ISSUE THREAD

**Issue by qwerty258** [racaljk/hosts#373]
考虑了下程序跨平台的实现：
搞个轻量级的HTTP库，然后替代WinInet，就是HTTP库源码直接放进工程里；但是这个轻量级的库不好找，我找了些都不满意。
我觉得最可行的是用cURL，反正Linux下源码编译，一般都有cURL；Windows下可以用cURL的静态库，VS编译时用MT，不要用MD，出来的exe我觉得应该在Vista以上的都能用，不会有什么缺少MSVCR120.dll的烂事情出现，出来的exe只需要一个exe，不需要另外杂七杂八的东西。
最主要的是你用了Windows的编程风格，就不好往Linux下搞。
@Too-Naive

**Comment by qwerty258** [comment]
当然，可以自己组HTTP头，用socket发，请求hosts下载，但这样非常花时间和累，就这样的小项目来说不值得，当然如果你想学习HTTP协议，socket编程，这是一个很好的实战练习。

**Comment by Too-Naive** [comment]
```c++
#if (defined _WIN32 || defined  _WIN64)
//...
#else
//...
#endif
```

**Comment by qwerty258** [comment]
不是，你代码里的_T、_stprintf等是Windows为了不同字符集（多字节字符和Unicode）搞的特有宏，Linux下没有……

**Comment by qwerty258** [comment]
然后可以搞个Makefile……
只有没有make的时候才直接敲g++命令编译……

**Comment by Too-Naive** [comment]
可是并不会linux下编程。。。

**Comment by wang20150419** [comment]
linux 下，直接写一个脚本就可以了（用wget或curl下载），然后用定时器执行脚本。

**Comment by fz420** [comment]
http://www.abelhadigital.com/hostsman
希望把文件中TAB 转为空格就好了，hostsman可以自动更新

**Comment by Too-Naive** [comment]
@qwerty258 issue已加入计划 暑假可以实现(就当作练手
到时候还希望您能多多指教

**Comment by Too-Naive** [comment]
now at HostsTools/Haskell-Console
