### ISSUE TITLE
用Python脚本来快速配置是有多作死……

### ISSUE THREAD

**Issue by K-Guan** [racaljk/hosts#38]
@racaljk 你以为Windows用户会为了个2分钟就可以打开文本编辑器手动更改的事情去花5分钟装个Python？

还是Linux用户会用本来只需要10秒一条命令的事、或不去用方便的git而去用你的脚本？
（PS：脚本不写SheBang是在想什么？而且如果用户有时间下载你的脚本他们就有时间下载你的hosts了）

综合上述，你的脚本没人用～

**Comment by smounives** [comment]
然而我不是写了bat，那个不是更简单……

**Comment by K-Guan** [comment]
@smounives Yeah, Python的全平台兼容是不错，可是没有解释器还不是白扯。

**Comment by dodopeng** [comment]
请问大大，Dropbox是不是不能访问了？

**Comment by K-Guan** [comment]
@dodopeng 我这边好像不行。

**Comment by racaljk** [comment]
我的初衷就不是让没有安装python core的用户使用py script，只是多提供一种获取hosts的方式   另这个脚本也并非只是简单get获取源码(唔..虽然现在是如此

**Comment by K-Guan** [comment]
@racaljk 好吧，那我不管咯～
