### ISSUE TITLE
为什么Fb上的视频可能播放Youtube的怎么就不行呐？

### ISSUE THREAD

**Issue by wolfan** [racaljk/hosts#381]
难道因为Youtube是Google的养子问题么？

**Comment by aofall** [comment]
#297

**Comment by aofall** [comment]
fb视频用的Akamai CDN
而不是fb自有ip
YouTube用的Google自有ip以及一些ggc
因为可用于GAE被封的差不多了

**Comment by Too-Naive** [comment]
@imcaffrey 还是把这个常用问题塞在那个issue模板里面吧.... 这玩意已经关闭的问题不能拿出来置顶 而很多人又像我之前一样从来就不看issue的- -
