### ISSUE TITLE
Google: 最近老是出现“连接已重置”问题

### ISSUE THREAD

**Issue by Jnoee** [racaljk/hosts#387]
最近更新了hosts文件，但访问google的时候链接会跳转到以下这个地址：
http://www.google.com.hk/url?sa=p&hl=zh-CN&pref=hkredirect&pval=yes&q=http://www.google.com.hk/%3Fgws_rd%3Dcr&ust=1461115673404263&usg=AFQjCNFMuxFtUQgcVWKhU61Pm-I7Ef14XA
浏览器提示：连接已重置。

不知道这个是什么问题，有人遇到吗？

**Comment by lzjun567** [comment]
该IP已经被封锁

**Comment by Jnoee** [comment]
得等新的hosts吗？
最近发生这种情况的，以前都挺好，一个hosts文件可以用一段时间。
现在哪怕我更新最新两个小时前提交的hosts都有这种问题，基本上就不可用了。

**Comment by imcaffrey** [comment]
@Jnoee `https`

**Comment by Too-Naive** [comment]
#337 #342 如果还是不行的话 请继续反馈

**Comment by andytimes** [comment]
如果您用的是 Chrome dev，可以参考下面的方法：

我手机上的 Chrome dev 51.0.2704.10 (Android) 有同样的问题。
问题出现在最近更新 chrome dev 后，用搜索框搜索出现链接重置。

问题无关 hosts，在于你发的那个链接是 http 方式访问。

你可以在搜索框输入 `chrome://net-internals/#hsts`
在 Input a domain name to add it to the HSTS set: 这一行下面的 Domain: [                     ]
输入 www.google.com.hk 点 Add

这个方法可以让 Chrome 访问 www.google.com.hk 时，强制选择 https 方式。

当然，可能还是会有问题，最好的办法是等 Chrome dev 更新

**Comment by whinamp** [comment]
Facebook已挂，重庆教育网。

**Comment by Too-Naive** [comment]
@whinamp 连接重置？

**Comment by andytimes** [comment]
@whinamp 另开 issue 啊，不然别人看不到

**Comment by Too-Naive** [comment]
@andytimes 干脆我帮他下吧…………

**Comment by davymai** [comment]
我系统重装后也有这个问题,用https://www.google.com/ncr 方式访问，禁止国别跳转后,无论是.com还是.com.hk都秒开了...

**Comment by BehAppyBoy** [comment]
chrome->设置->管理搜索引擎--->删除google搜索引擎  
我折腾了好久，亲测有效

**Comment by spyflying** [comment]
使用https方式访问，亲测有效

**Comment by eelve** [comment]
一样

**Comment by Lix1993** [comment]
管理搜索引擎-https://www.google.com/#safe=off&q=%s
然后就可以了

**Comment by Lix1993** [comment]
强制使用https也可以
