### ISSUE TITLE
Stars over 4k Celebration

### ISSUE THREAD

**Issue by imcaffrey** [racaljk/hosts#392]
> To celebrate that our project's stars over 4k, this issue will be closed in one week.

为庆祝我们的hosts项目Stars到达四千，特开此Issue，为让大家也放松下。  

所以诸位维护本项目也都辛苦了，我刚刚看了下Commits也到达了419，大家在本Issue里面想说什么就说什么吧（But please don't trash this celebration or let it on fire, just relax）。

祝大家愉快。

最后说一个无关这个 issue 的话，我还是希望更多朋友用 hosts 来学习，不要做多余的事情。

// 传统项目 #142

**Comment by imcaffrey** [comment]
截止本comment，我们的：

- Stars: 4,022
- Commits: 419

-------------------

再次感谢各位对我们的项目持续的维护和支持！

**Comment by Too-Naive** [comment]
~~mdzz~~ 
其实我们应该感到悲哀…… 
不是只有你我在qiang下战斗

**Comment by imcaffrey** [comment]
您教育的是

**Comment by Too-Naive** [comment]
仰慕

**Comment by lautis0503** [comment]
多余的事情指什么……

**Comment by Too-Naive** [comment]
我需要安慰
I need ~~AV~~

**Comment by K-Guan** [comment]
等等，这个是什么时候开的？

**Comment by K-Guan** [comment]
*话说能不能……模仿我的口吻就罢了，居然直接照搬……*

**Comment by Too-Naive** [comment]
~~懒成这样~~手动斜眼

**Comment by K-Guan** [comment]
同意 ^^^

**Comment by d-bluedreams** [comment]
hosts受众路过，顺带恭喜突破4000∠( ᐛ 」∠)＿

**Comment by Too-Naive** [comment]
谢谢>..<

**Comment by imcaffrey** [comment]
@K-Guan 当然要继承前辈的光荣传统咯

**Comment by Too-Naive** [comment]
我觉得ls都会比我大了|･ω･｀)

**Comment by K-Guan** [comment]
@imcaffrey 我怎么又成“前辈”了？感觉瞬间老了20……
