### ISSUE TITLE
能不能开个branch只有hosts文件的？

### ISSUE THREAD

**Issue by outsinre** [racaljk/hosts#393]
我目前只需要hosts文件，其他的工具暂时用不上。

如果有个branch专门针对hosts文件，我clone时，方便店儿。

**Comment by imcaffrey** [comment]
你不需要clone，直接获取hosts文件就行了

**Comment by Too-Naive** [comment]
不过可以考虑这位小哥的建议- - 只是其他的东西再修改有点麻烦

**Comment by imcaffrey** [comment]
@Too-Naive 我想你现在没有时间来为这个”branch“实时更新
没有任何必要单独开一个branch
`https://coding.net/u/scaffrey/p/hosts/git/raw/master/hosts` 在这写着
`bash -c 'wget https://raw.githubusercontent.com/racaljk/hosts/master/hosts -qO /tmp/hosts && sudo mv /tmp/hosts /etc/hosts'` 这也在这写着

**Comment by Too-Naive** [comment]
好的 谢谢指教
BTW 如何create一个空的branch？

**Comment by Too-Naive** [comment]
反馈…… issue基本实现了 迁移了除脚本以外的tools
