### ISSUE TITLE
建议维护一份DNS server

### ISSUE THREAD

**Issue by outsinre** [racaljk/hosts#394]
hosts方法和dns server方法差不多。如果能另外单独维护一份dns server，也是大有好处的。

**Comment by Too-Naive** [comment]
We'd love to, but we haven't server.

**Comment by imcaffrey** [comment]
@Too-Naive 这个不是没有server的原因，是增加维护成本的问题

**Comment by Too-Naive** [comment]
希望在未来能有大咖来做这个Dns服务器吧~~(比如我|･ω･｀)~~

**Comment by aofall** [comment]
如果你用的是DNSmasq的话直接把hosts丢进去就可以了 又不是不兼容hosts的写法
还有 这个项目叫做hosts，而不是DNS

**Comment by Too-Naive** [comment]
(afraid

**Comment by Too-Naive** [comment]
DNS其实是可用…… 但是 因为gfw的原因 它可以抢答你的dns请求
详情参见 http://drops.wooyun.org/papers/10177
所以在公网上架DNS服务器 理论上是不行的 @outsinre

**Comment by outsinre** [comment]
好文章，我去看看。我也听说了是DNS污染。

**Comment by K-Guan** [comment]
其实免费服务器四处都是，不过 DNS 污染是个问题。

**Comment by xiaofami** [comment]
是我too naive了…… 只看了open issue 😆
