### ISSUE TITLE
HostTool能不能加上一个自定义添加其他hosts文件至末尾功能？

### ISSUE THREAD

**Issue by JackieMium** [racaljk/hosts#400]
因为种种原因hosts文件里除了/racaljk/hosts还需要在末尾添加一些其他的内容：
```
127.0.0.1 activate.adobe.com
127.0.0.1 practivate.adobe.com
127.0.0.1 lmlicenses.wip4.adobe.com
127.0.0.1 lm.licenses.adobe.com
127.0.0.1 lmlicenses.wip4.adobe.com
127.0.0.1 lm.licenses.adobe.com
...
```
所以我每次都是hosts替换完了还得来一次复制粘贴。请问HostTool里面工具能不能添加上一个类似于替换完了还有一个追加某文件到新的hosts末尾的功能？ie: `echo tail >> hosts`
平台： Windows 10 Pro x86_64

**Comment by Too-Naive** [comment]
您用的是bat脚本吗...
我会尽快地在exetool中加入这个特性

**Comment by JackieMium** [comment]
@Too-Naive `script_tool_for_windows.bat`脚本直接用记事本复制粘贴发现在我的系统上直接打不开，闪退了。想了一下可能是编码问题，所以另存为`UTF-8`之后才能用。这个编码问题建议可以写在wiki或者README。
上面提到的追加功能，目前发现Hozz貌似提供了类似功能，不过仍然希望其他工具也加入这项支持。

**Comment by Too-Naive** [comment]
谢谢您的反馈 
README还需要修改- - 这个我们在等老大哥 @racaljk 的意见才能合并那个PR...
(bat好像并不能添加这个功用???

**Comment by JackieMium** [comment]
@Too-Naive 我不知道bat怎么写交互式，直接类似于`Linux`的`BASH`下面写`shell`交互脚本那样应该是可以实现的吧。不过这样感觉还是有点增加这个bat的复杂性而且易用性有所降低。可能这个还是在GUI下面实现起来现实一点吧。我现在先用着`Hozz`了。

**Comment by Too-Naive** [comment]
交互脚本? 能具体说明一下吗?

**Comment by JackieMium** [comment]
@Too-Naive 额....这个你们应该比我懂啊。类似输入`任意键继续`、`请输入选择项然后按ENTER：`这样都是简单的交互式啊，我想加入一个类似于`请输入要追加到hosts末尾的文件`这样的貌似可以实现，但是Windows下没有自动补全，输入路径和文件名也是挺烦的，只能复制粘贴吧。

**Comment by Too-Naive** [comment]
噢噢.....还是比较easy的...但是我不会写bat.....(hhhhhhhhhh
<del>明明exe比较好用 您们就是要用Bat(虽然也没有这个功能)</del>

**Comment by JackieMium** [comment]
@Too-Naive 其实我也不会写啊，我就只能瞎指挥23333333
我这大概是做产品经理的料吧 :100:

**Comment by Too-Naive** [comment]
对于用户~~合理~~的建议 我们会认真考虑的(x

**Comment by JackieMium** [comment]
@Too-Naive 嗯，收到你这么**官方**的答复我就放心了:)
暂时就Hozz用着了。可以Close了。

**Comment by imcaffrey** [comment]
静静强行安利exe*2 :smile:

**Comment by Too-Naive** [comment]
本来就是exe好用嘛！(认真脸

**Comment by Too-Naive** [comment]
@JackieMium console tool已经添加了这个功能 详情请参阅/tools/WinConsole/README.md

**Comment by Too-Naive** [comment]
回头看了一下这个issue 这个不是所谓的...绕过adobe激活吗...

**Comment by JackieMium** [comment]
@Too-Naive 生活已经如此艰难，何必还要互相伤害呢 : (

**Comment by Too-Naive** [comment]
@JackieMium hhh 话说用过了之后感觉如何啊

**Comment by JackieMium** [comment]
@Too-Naive Defender一直报毒，添加排除都不管用，烦死，还是乖乖复制粘贴可能会方便一点.....

**Comment by PW-Chen** [comment]
@JackieMium 要运行的时候先关掉防毒，跑完再开也可啊：3

**Comment by JackieMium** [comment]
@Too-Naive 咦，你到底说的哪个工具？Choose.exe、Tool.exe没发现有这个功能；Haskell-Console_win64闪退

**Comment by Too-Naive** [comment]
有 啊= = 你要加载前面 不是加在后面啊 @JackieMium

**Comment by JackieMium** [comment]
@Too-Naive What？（黑人问号）

**Comment by Too-Naive** [comment]
`加载前面` "加在"

**Comment by JackieMium** [comment]
@Too-Naive 啥加在前面啊，别说话说一半啊

**Comment by Too-Naive** [comment]
需要保留的hosts地址 @JackieMium

**Comment by JackieMium** [comment]
还是话说一半....
比如现在路径`C:\Windows\System32\drivers\etc`，有文件`hosts`、`tail`，`tail`是自定义hosts部分；`Choose.exe`、`Tool.exe`也在这个路径。然后呢？

**Comment by Too-Naive** [comment]
啥tail 你就直接把 你自定义的东西塞在那个什么 `#copyright ...`什么的前面就好了

**Comment by JackieMium** [comment]
哦，终于懂了你的意思：放到hosts开头的自定义的部分(`#copyright ...`以上)，在用`Tool.exe`的时候不会给我覆盖掉是吧？我试了，很好！

**Comment by Too-Naive** [comment]
好噢
