### ISSUE TITLE
关于Soundcloud的问题

### ISSUE THREAD

**Issue by AlexDialga** [racaljk/hosts#401]
首先这两个网站无法使用
**https://on.soundcloud.com
https://blog.soundcloud.com/**
其次是里面的歌曲听不到
难不成听歌的机制和水管一样？
如果是的话那就日了哈士奇了_(:3」∠)_
本人使用广东电信校园网
hosts版本是昨天的
另外求眼熟ww⁄(⁄ ⁄•⁄ω⁄•⁄ ⁄)⁄

**Comment by lautis0503** [comment]
两个网站确实上不去，不过我这里soundcloud随便点首歌能播放

**Comment by lautis0503** [comment]
部分歌无法播放是因为存到aws了

**Comment by lautis0503** [comment]
试试这个能不能用
https://github.com/lautis0503/hosts/blob/master/hosts
