### ISSUE TITLE
能否加入Google新出的Save to Google服务的IP

### ISSUE THREAD

**Issue by imcaffrey** [racaljk/hosts#405]
Google Save extension https://chrome.google.com/webstore/detail/meoeeoaohbmgbocpdpnjklmfmjjagkkf

```
现在使用这个会直接转向到com而非com.hk，因为并无中文语言支持
```

cc @murazi (https://github.com/racaljk/hosts/commit/4437b7e6dc4ef93fdec382cec719a8de825bfd13#commitcomment-17192961)

**Comment by andytimes** [comment]
www.google.com
hosts 里提供了啊，Save to Google 这个又不是单独的域名。

**Comment by imcaffrey** [comment]
我好方，并不太清楚这个插件在干什么……

**Comment by andytimes** [comment]
@imcaffrey Google 啊，关键词 "save to google 用法"
搜索一下，貌似没有正式推出服务，功能类似于印象笔记

**Comment by Too-Naive** [comment]
插件不是也可以审查元素吗233 ~~有您们在我终于可以不用插手host的修改了~~

**Comment by LGA1150** [comment]
chrome://net-internals/#dns 
可以看到Chrome发起的DNS请求

**Comment by lautis0503** [comment]
这个插件我原来用过，没问题啊
