### ISSUE TITLE
Android 6.0.1上替换hosts文件失效

### ISSUE THREAD

**Issue by WeihuaGu** [racaljk/hosts#409]
我是通过
```bash
mount -o rw,remount /system
tmppath="/sdcard/tmp"
cd $tmppath
curl -O https://raw.githubusercontent.com/racaljk/hosts/master/hosts 
if
diff $tmppath/hosts /system/etc/hosts
then
exit 1
fi
mv $tmppath/hosts /system/etc/
chmod a+r /system/etc/hosts
exit 0
```
来在手机上获取hosts文件的。也不是每次都不能用，通常会有几次能用，大多时候更新的都无法使用，hosts文件不生效。我把这个hosts文件提取出来，和ubuntu下的hosts 用diff显示是一致的。
所以为什么会出现，大多时候，ubuntu 可以用，而手机不能使用？

**Comment by Too-Naive** [comment]
帮您修改了一下issue标题… 手头没有那么高版本的安卓手机无法测试 看看其他人有没有同样的情况吧…

**Comment by WeihuaGu** [comment]
我把手机中的Hosts文件再复制出来，hosts: ASCII text。所以可以排除是编码问题。

**Comment by Too-Naive** [comment]
会不会换成UTF8就正常？

**Comment by lautis0503** [comment]
都是英文，UTF-8和ANSI一样的

**Comment by Too-Naive** [comment]
好吧...我还是不插嘴了.. 要不试试这个android软件(我在4.x上测试可用 [download](https://github.com/crianzy/AndroidGoogleHost/blob/master/%E7%A7%91%E5%AD%A6Host.apk?raw=true)

**Comment by WeihuaGu** [comment]
感谢提供apk :) 不过依然无作用。手机上星期自动生了下级，用的是CM13，不知道有没有关系。之前也是android 6.0 ,过去没有生效时，只保留部分内容，比如google和twitter的，会生效。这回是只使用部分也不行。
通常hosts文件不生效就是，读取权限，编码不对，换行符，ip与域名中的空格。这回好像都不是，还有人也是android 6.0的吗？也许是因为是CM13的问题。我这个应该是个例。

不过android6.0会大部分更新不行，少数更新可以用，应该是普遍的。现在也没有查到有新的机制，不过android6.0的确是收紧了一些权限，比如调用wifi查看mac地址，会返回虚假固定的mac等等……

**Comment by andytimes** [comment]
@WeihuaGu 如果你的 Android 系统不是自己编译的，那么肯定不是系统的问题。
我认为你的操作有两个地方可能出会问题，
第一，最好不要把下载的文件放在 /sdcard 里，这个可能会造成权限问题（应该不是这个问题）；
第二，最后那个的权限操作可能会出现问题 `chmod a+r /system/etc/hosts` ，最好这样写 `chmod 0644 /system/etc/hosts`

还有这个
```shell
if
diff $tmppath/hosts /system/etc/hosts
then
exit 1
fi
```
diff 不相同直接退出脚本，diff 相同继续操作是什么逻辑？

**Comment by WeihuaGu** [comment]
下载的在/sdcard/tmp/hosts文件与/system/etc/hosts相同就推出，不同的话，就更新hosts文件。
linux 以命令执行后的状态判断真假，test或[可以测试一个条件是否成立，如果测试结果为真，则该命令的Exit Status为0，如果测试结果为假，则命令的Exit Status为1（注意与C语言的逻辑表示正好相反）。
因为两个文件相同，所以difff返回了状态码0，你可以试试，不同的话，会返回1。所以脚本退出返回1（因为没有更新成功）
如果两个文件不通，则替换hosts文件，并且返回0（更新了hosts,文件，我就算成功）

**Comment by WeihuaGu** [comment]
另外权限的话，ls -all 结果：
 root@cancro:/system/etc # ls -all hosts
 -rw-rw-r-- 1 root sdcard_rw 144369 2016-04-26 12:04 hosts

**Comment by andytimes** [comment]
@WeihuaGu 感谢指正！shell 的返回值倒不让人迷惑，是我对 diff 命令有误解。

一般 hosts 的权限是 -rw-r-r-- (0644) 或 -rw-rw-rw-- (0666) (不少 CM 系 ROM hosts 是这个权限)

可以试试在手机上 `ping -c 4 www.google.com` 看看 IP 是不是 220.255.2.153
这样能知道 hosts 是否生效。

另外，替换后开一下飞行模式，再联网，看看如何。

**Comment by WeihuaGu** [comment]
谢谢你。这些都有试过，不行（：ping 返回的是DNS 服务器返回的被污染的ip 37.61.54.158。 还是没有生效。

**Comment by andytimes** [comment]
确实有些奇怪，保险起见在手机上运行一下 `busybox dos2unix /system/etc/hosts` 看看，

还有 CM 现在自带 dnsmasq，hosts 确实用不了，可以用它替代

**Comment by Too-Naive** [comment]
插个嘴 @andytimes 快来PR婊我阿QAQ

**Comment by imcaffrey** [comment]
@Too-Naive issue无关请不要spam

**Comment by WeihuaGu** [comment]
adb shell 运行了下  dos2unix /system/etc/hosts，并且用上面的脚本更新下了27号的更新，竟然ping通了。
然后为了看是不是换行符的问题，我rm /system/etc/hosts 文件。
然后用
curl -O https://raw.githubusercontent.com/racaljk/hosts/master/hosts 
chmod a+r /system/etc/hosts
下载了hosts文件，并且不执行 dos2unix命令，也ping通了。
也就是说，27号的更新可用了。

**Comment by Too-Naive** [comment]
@andytimes 会不会是下载的hosts文件换行符问题？ 
我自己写的程序下载以后需要自己转换换行符
不过 我下下来是unix换行符结尾………

**Comment by WeihuaGu** [comment]
感谢@andytimes!
查看了这个版本的hosts文件权限和用户与组，与过去完全一致。
过去版本的hosts文件用vi 打开，没有见到，^M 。也许是在整个Hosts文件中会有一两个偶发的换行符，有的版本有，有的版本没有。所以造成了时而可用时而不可用。
我最疑惑的是，同一个文件，在ubuntu中却总是生效的。是不是不通系统对hosts文件的“容忍度”不一样？

**Comment by WeihuaGu** [comment]
另外也感谢@Too-Naive，我会把dos2unix /system/etc/hosts加入到脚本最后，如果后续版本依然出现时灵时不灵的现象再来反馈。

**Comment by Too-Naive** [comment]
不过我是win环境啦.... 
You're welcome.

**Comment by andytimes** [comment]
@WeihuaGu “容忍度” 这个我真不懂。
关于混合换行符，如果 hosts 在 Windows 平台 Github 网页上被编辑，有可能会引入混合换行符。
至于更新后 hosts 生效，我猜测应该是有人用 git 客户端操作了 hosts，.gitattributes 会把检出的文件换行符归一化，就不会有混合换行符问题了。

其实，避免这个问题可以修改脚本，替换 hosts 建议弃用 `mv [file1] [file2]` 指令
可以用 `cat [file1] > [file2] ` 替代，这个能 "自动转化" 换行符。

**Comment by imcaffrey** [comment]
我用的git客户端……

**Comment by WeihuaGu** [comment]
明白了，用拼接命令会比移动命令好一些：）

**Comment by K-Guan** [comment]
@andytimes 唉？ `cat` 还有这个功能？

**Comment by andytimes** [comment]
@WeihuaGu @K-Guan 刚刚我试了一下 `cat` 不带参数，好像不能抛弃 ^M 字符，明明这个是不可打印字符啊，我没加 `-v` 参数 `^M` 还是被重定向到另一个文件里面了，所以还是用 dos2unix 比较保险。

以下是测试：
```shell
$ echo "test" > t1 && cat -e t1
test$

$ unix2dos t1 && cat -e t1
unix2dos: converting file t1 to DOS format ...
test^M$

$ cat t1 > t2 && file t2 && cat -e t2
t2: ASCII text, with CRLF line terminators
test^M$

$ cat -v t1 > t2 && file t2 && cat t2
t2: ASCII text
test^M
```
 最后一个指令比较有意思，cat -v 把 `^M ( '\r' ) ` 转化成了 `^` 和 `M` ，这样倒是把换行符干掉了，
不过放在 hosts 里面，更有可能让 hosts 失效。

还是实践出真理，下次得出结论前，我得好好去测试下可行性了、、、

**Comment by K-Guan** [comment]
@andytimes 没错……
