### ISSUE TITLE
windows.bat 指定资源下载失败

### ISSUE THREAD

**Issue by 7310C7310C** [racaljk/hosts#413]
下载不稳定。有时脚本无法正常下载默认链接里的 hosts，提示“指定资源下载失败”。有时能下载成功。
下载链接改成 coding 的是能正常下载的。

**Comment by imcaffrey** [comment]
这是网络问题吧……我们要不要把scripts的链接都改成coding的？

**Comment by Too-Naive** [comment]
同步的话就滋磁啊………
