### ISSUE TITLE
请添加 Medium hosts

### ISSUE THREAD

**Issue by tisyang** [racaljk/hosts#414]
[Medium](https://medium.com) 已经被墙了，有些技术文章在墙内就不再那么容易看到。

但是通过修改 hosts 测试发现，是可以通过修改 hosts 来实现访问的，[Medium](https://medium.com) 已经 HTTPS 全覆盖了。

不知道直接把可用 IP 贴在 Issue 里是否合适，经过测试，只需要添加如下 domain 的 hosts IP 即可浏览 Medium 文章了。

```text
medium.com
cdn-static-1.medium.com
cdn-images-1.medium.com
cdn-images-2.medium.com
```

**Comment by imcaffrey** [comment]
我这里还可以打开……

**Comment by Too-Naive** [comment]
福建电信 ERROR_CONNECTION_TIME_OUT

**Comment by K-Guan** [comment]
山东（忘了运营商了） This site can’t be reached - medium.com took too long to respond.

**Comment by andytimes** [comment]
安徽移动（手机） 无法访问，测试被指向 37.61.54.158 这个无效 IP

**Comment by oif** [comment]
晚上回去我试着折腾下交个 request

**Comment by Too-Naive** [comment]
@oif Thx

**Comment by lautis0503** [comment]
测试出IP了不应该直接PR么

**Comment by HanderWei** [comment]
有可用的hosts吗？

**Comment by tisyang** [comment]
@HanderWei 当前 hosts 已经支持 Medium 了

**Comment by kekemao00** [comment]
成功，谢谢！

**Comment by yiakwy** [comment]
无人车的很多文章，也是在medium上发布，求更新hosts地址

**Comment by lrinQVQ** [comment]
@yiakwy https://github.com/googlehosts/hosts/blob/master/hosts-files/hosts#L2793

**Comment by yiakwy** [comment]
@lrinQVQ 不起作用

**Comment by lrinQVQ** [comment]
@yiakwy 欸我这里https://medium.com 能开的说
