### ISSUE TITLE
Scripts download links don't work reporting

### ISSUE THREAD

**Issue by K-Guan** [racaljk/hosts#417]
正在研究怎样保留脚本的可执行权限的问题，所以链接是暂时性的失效了（因为正在进行不断的测试嘛）。具体什么时候能用得看我什么时候搞好，看来比较麻烦…… cc @andytimes 。

因此，如果为大家带来不便，还请谅解。

**Comment by Too-Naive** [comment]
~~我们不能谅解不给我们下载脚本的人(大雾~~

**Comment by K-Guan** [comment]
*You can still copy-paste the scripts on GitHub Raw yourself.*

**Comment by Too-Naive** [comment]
拒绝 我有exe为何要用bat!(逃

**Comment by K-Guan** [comment]
@Too-Naive Linux is always the best system!

**Comment by Too-Naive** [comment]
辣鸡*nux 用Windows保平安
人在做 天在看 软件不兼容留隐患

**Comment by K-Guan** [comment]
Well:

> Open-source is safe,
> because there's a thief.
> They're going to get your password,
> and do your work.

**Comment by Too-Naive** [comment]
我不听 我不听 我不听 (大雾

**Comment by K-Guan** [comment]
（不可救药）

**Comment by Too-Naive** [comment]
![](https://cloud.githubusercontent.com/assets/16496671/14854755/80a24440-0cc3-11e6-90c8-549f0c052ef3.jpg)

**Comment by K-Guan** [comment]
@Too-Naive  Agree.

And by the way, host the scripts use my site seems is a good idea...which gives me a high traffic:

![2016-04-27-205144_332x198_scrot](https://cloud.githubusercontent.com/assets/13862535/14854888/19fe10a6-0cc4-11e6-986f-0eb89ebb5f81.png)

<sub>*should I put some ads then?*</sub>

**Comment by Too-Naive** [comment]
~~And then I will delete them.~~

**Comment by K-Guan** [comment]
[Just posted a question on SO anyway.](http://stackoverflow.com/q/36892852/5299236)

**Comment by andytimes** [comment]
@K-Guan wget 报错
$ `wget http://keving.pythonanywhere.com/hosts_scripts/lhosts`
Connecting to keving.pythonanywhere.com (50.19.109.98:80)
wget: server returned error: HTTP/1.1 500 INTERNAL SERVER ERROR

cURL 正常

**Comment by andytimes** [comment]
@K-Guan 我有一个不完美的想法，把脚本压缩成 *.zip 或 *.tar.gz， 这样可以保留文件权限。
目前还没有想到更好的办法。

**Comment by K-Guan** [comment]
看来果然还是不行。

问题在于：http://stackoverflow.com/a/36894957/5299236
@andytimes 这个我也确实知道，不过太过麻烦。顺便一提这个方法在 SO 上也有人提到：http://stackoverflow.com/questions/36892852/how-do-i-keep-the-files-permission-using-send-file/36894957#comment61354939_36892852

总之……你说怎么办吧。我还是觉得直接下载后再 `bash lhosts` 比较方便。

**Comment by Too-Naive** [comment]
弱弱问一句 脚本不能自己修改自己的权限吗……
~~Title: Should be "doesn't work" ???~~

**Comment by K-Guan** [comment]
@Too-Naive 可以，前提是得先执行了才是。而执行需要可执行权限。

~~你说我的 Title 主语是 *Scripts* 还是 *download links* ？~~

**Comment by Too-Naive** [comment]
~~The download link of scripts dorsn't work~~
好像也对 谢谢扫盲

**Comment by K-Guan** [comment]
@Too-Naive 说起来我还真不知道这里到底应该用 link 还是 links 。@imcaffrey suggestions?

**Comment by Too-Naive** [comment]
s
不是有两个吗…

**Comment by K-Guan** [comment]
这个嘛…… *The download link of scripts dorsn't work* 看起来好像也没错……I'm not sure.

**Comment by Too-Naive** [comment]
dors满分

**Comment by K-Guan** [comment]
*@Too-Naive 其实那是直接复制你的上面写的那个。*

**Comment by Too-Naive** [comment]
什么嘛！！

**Comment by K-Guan** [comment]
> Too-Naive commented an hour ago • ***edited***

GitHub 新功能在此，别想狡辩！

**Comment by Too-Naive** [comment]
(:３っ　)へ我不听我不听我不听

**Comment by K-Guan** [comment]
（反正这次我还是赢了）

**Comment by Too-Naive** [comment]
我不管 我故意编辑的

**Comment by K-Guan** [comment]
懒得理你……

**Comment by Too-Naive** [comment]
你就舍得欺负我这么可爱善良的女孩子吗【沉默】

**Comment by K-Guan** [comment]
@Too-Naive 你……作为一个 Linux 发行版，我认为我应该是不会说话的，自然就不可能有“欺负”这一说法了。

**Comment by imcaffrey** [comment]
@K-Guan idk....

**Comment by Too-Naive** [comment]
可这是事实阿【沉默】

**Comment by K-Guan** [comment]
@imcaffrey 还以为你的水平多高呢……好吧我还是找别人问问去。

**Comment by K-Guan** [comment]
@Too-Naive 证据？

**Comment by imcaffrey** [comment]
@K-Guan hhh, im a noob

**Comment by K-Guan** [comment]
@imcaffrey me?

**Comment by imcaffrey** [comment]
`im --> i am` Qrz.

**Comment by K-Guan** [comment]
@imcaffrey me?

**Comment by K-Guan** [comment]
@imcaffrey 唉？我还以为你是故意那样拼的（a noob always does that =p）。

**Comment by imcaffrey** [comment]
是故意的啊，你看不懂就改回来了

**Comment by K-Guan** [comment]
@imcaffrey 哦，你误解了。我前面的意思是“那我呢？”。

**Comment by Too-Naive** [comment]
事实！不需要证据【沉默】

**Comment by K-Guan** [comment]
@Too-Naive Why I should trust you? （唉？换头像了？）

**Comment by Too-Naive** [comment]
【沉默】干嘛！要泡我???

**Comment by K-Guan** [comment]
@Too-Naive 当一个人不跟你讲理时，你就没法跟他进行辩论……

<sub>*所以我还是不理你了*</sub>

**Comment by andytimes** [comment]
@Too-Naive 以前，我有一个很好的办法去判断一个人的性别：
如果一个人对女生的称呼是 “妹子”，那么基本可以断定是男性。

然而，现在这个方法已经不管用了，女生也开始称呼女生为 “妹子” 了、、、

@K-Guan 实际上，我还没有看过不用 压缩 / 归档 的方式，就能保存文件可执行权限的方法，直接下载可能还是需要手动修改权限。

**Comment by K-Guan** [comment]
@andytimes 

1. 实际吧……在编程 论坛/网站 你想看到女生是门都没有的。将大家的默认性别都设定为男性就好（什么？你说你是女生？想改变自己的默认性别？ **Permission denied**）。

2. Meh, 那还是不研究了吧。

**Comment by Too-Naive** [comment]
(x

**Comment by imcaffrey** [comment]
**Permission denied**

**Comment by Too-Naive** [comment]
![](https://cloud.githubusercontent.com/assets/16496671/14873063/cd15c35e-0d24-11e6-81ec-9f97b2c120da.JPG)

**Comment by K-Guan** [comment]
> Note: I've fixed the links to the scripts.

**Comment by andytimes** [comment]
@K-Guan 是有的哦！

Kevin Guan <notifications@github.com>于2016年4月28日周四 下午6:40写道：

**Comment by K-Guan** [comment]
@andytimes （话说明明是男生却去装成女生还是觉得好无聊）

**Comment by Too-Naive** [comment]
~~噫 你在说你自己吗~~
![](https://cloud.githubusercontent.com/assets/16496671/14747730/62dc54fc-08e8-11e6-8e09-12005c61b21b.jpg)

**Comment by K-Guan** [comment]
@Too-Naive 你不要跟我说话……

**Comment by Too-Naive** [comment]
I can Lock Conversation....

**Comment by K-Guan** [comment]
@Too-Naive I can be a Collaborator again if I want to be...

**Comment by Too-Naive** [comment]
![](https://cloud.githubusercontent.com/assets/16496671/14888118/453fdeb2-0d8b-11e6-93e9-b3f586f1f98c.jpg)
