### ISSUE TITLE
Gitter 无法正常显示页面元素

### ISSUE THREAD

**Issue by Too-Naive** [racaljk/hosts#418]
福建电信 无法解析如下地址
```
cdn01.gitter.im
cdn02.gitter.im
```
添加以下行之后即可正常访问gitter
```
54.192.123.222 cdn02.gitter.im
54.192.123.222 cdn01.gitter.im
```

**Comment by K-Guan** [comment]
第一次：普通 ping 测试。
第二次：挂 VPN 后 ping 测试。
地点：山东。

![2016-04-28-190537_924x408_scrot](https://cloud.githubusercontent.com/assets/13862535/14883996/8d040d70-0d74-11e6-94ab-57308492a3ac.png)

**Comment by Too-Naive** [comment]
您的DNS是？

**Comment by K-Guan** [comment]
```
# PIA servers
nameserver 209.222.18.222
nameserver 209.222.18.218
```

我用的 VPN 提供的 DNS ，实际不用这个 DNS 根本就没法用我那个 VPN 。

**Comment by Too-Naive** [comment]
有毒阿。。。 我用的是电信的

**Comment by K-Guan** [comment]
@Too-Naive 我的……忘了，懒得去查了。

**Comment by Too-Naive** [comment]
有毒 @imcaffrey 您那边有没有出现这问题阿…

**Comment by imcaffrey** [comment]
我这里常年打不开……

**Comment by lautis0503** [comment]
我这里Github和Gitter不定期会出现这样的情况

**Comment by aofall** [comment]
这域名并没有被DNS污染
估计是高峰期辣鸡电信骨干网撑不住给Qos丢包了
DNS：192.168.1.1（上级DNS是 211.138.156.66 211.138.151.161）、223.5.5.5

**Comment by Too-Naive** [comment]
218.85.157.99 = =我把hosts改回来试试

**Comment by Too-Naive** [comment]
诶 成功了- - 那我关掉

**Comment by Too-Naive** [comment]
|･ω･｀)如果有出问题的话 手动把hosts改一下吧
