### ISSUE TITLE
flipboard打不开了

### ISSUE THREAD

**Issue by ziking** [racaljk/hosts#420]
flipboard打不开了
还有fb今天怎么也不可以

**Comment by Too-Naive** [comment]
福建电信 fb 可用

**Comment by DaleXiao** [comment]
no problem here with fb.

**Comment by imcaffrey** [comment]
flipboard貌似是间歇性出问题吧

**Comment by AutuanLiu** [comment]
这个不支持wolfram网站吗？最近都不能下载mathematica啦，好桑心 😹 好像被墙好久了，不过去年是可以的。

**Comment by imcaffrey** [comment]
www.wolfram.com 一直没事啊？

**Comment by AutuanLiu** [comment]
可以进是可以进，就是不能下载，不知道是不是我这边网的问题！

**Comment by andytimes** [comment]
@ziking @AutuanLiu 把具体的网址发来看看，我这里能访问 https://flipboard.com/

**Comment by imcaffrey** [comment]
@andytimes @AutuanLiu 说的是mathematica的下载问题……

**Comment by andytimes** [comment]
@imcaffrey wolfram 安徽联通可访问，记得上次圣诞节，有人用这个画了一棵圣诞树，刚刚我找出来了。

http://codegolf.stackexchange.com/questions/15860/make-a-scalable-christmas-tree/16428#16428

如图：
![img](http://i.stack.imgur.com/OGv5a.gif)
