### ISSUE TITLE
请求将文件中TAB转换为空格

### ISSUE THREAD

**Issue by fz420** [racaljk/hosts#421]
> 是否可以请求将文件中TAB转换为空格（虽然我手工可以处理），hostsman就可以自动更新了

**Comment by Too-Naive** [comment]
TAB是更加整齐美观? @imcaffrey @andytimes

**Comment by andytimes** [comment]
@fz420 在 hosts 中，tab 应该被优先使用。个人觉得 tab 比空格好一些。

空格
```txt
64.233.188.109 gmail-imap.l.google.com
64.233.188.16 googlemail-imap.l.google.com
64.233.188.108 gmail-smtp.l.google.com
64.233.188.16 googlemail-smtp.l.google.com
64.233.188.109 gmail-pop.l.google.com
64.233.188.16 googlemail-pop.l.google.com
64.233.188.109 imap.gmail.com
64.233.188.16 imap.googlemail.com
64.233.188.109 smtp.gmail.com
64.233.188.16 smtp.googlemail.com
64.233.188.109 pop.gmail.com
64.233.188.16 pop.googlemail.com
64.233.188.109 gmail-smtp-msa.l.google.com
64.233.188.27 gmail-smtp-in.l.google.com
64.233.188.14 gmr-smtp-in.l.google.com
```

TAB
```txt
64.233.188.109	gmail-imap.l.google.com
64.233.188.16	googlemail-imap.l.google.com
64.233.188.108	gmail-smtp.l.google.com
64.233.188.16	googlemail-smtp.l.google.com
64.233.188.109	gmail-pop.l.google.com
64.233.188.16	googlemail-pop.l.google.com
64.233.188.109	imap.gmail.com
64.233.188.16	imap.googlemail.com
64.233.188.109	smtp.gmail.com
64.233.188.16	smtp.googlemail.com
64.233.188.109	pop.gmail.com
64.233.188.16	pop.googlemail.com
64.233.188.109	gmail-smtp-msa.l.google.com
64.233.188.27	gmail-smtp-in.l.google.com
64.233.188.14	gmr-smtp-in.l.google.com
```

推荐使用本项目的 Hosts 工具 https://github.com/racaljk/hosts/tree/master/tools

Android 用这个 app http://soft.shouji.com.cn/down/31276.html
添加源：
https://raw.githubusercontent.com/racaljk/hosts/master/hosts
或
https://coding.net/u/scaffrey/p/hosts/git/raw/master/hosts
即可更新。

**Comment by imcaffrey** [comment]
hostman不能处理tab吗……不太清楚

**Comment by andytimes** [comment]
@imcaffrey ping 这个网址的结果
```shell
$ ping www.abelhadigital.com
PING ghs.l.google.com (64.233.189.121) 56(84) bytes of data.
64 bytes from tl-in-f121.1e100.net (64.233.189.121): icmp_seq=11 ttl=127 time=56.7 ms
64 bytes from tl-in-f121.1e100.net (64.233.189.121): icmp_seq=16 ttl=127 time=93.8 ms
64 bytes from tl-in-f121.1e100.net (64.233.189.121): icmp_seq=18 ttl=127 time=57.5 ms
64 bytes from tl-in-f121.1e100.net (64.233.189.121): icmp_seq=24 ttl=127 time=1172 ms
^C
--- ghs.l.google.com ping statistics ---
27 packets transmitted, 4 received, 85% packet loss, time 26003ms
rtt min/avg/max/mdev = 56.724/345.180/1172.600/477.947 ms, pipe 2
```

丢包好严重，而且让人好奇的是，
> www.abelhadigital.com.  1636    IN      CNAME   ghs.google.com.

**Comment by Too-Naive** [comment]
(:３っ　)へ和上次我添加的那个啥域名来着也是ghs的……

**Comment by K-Guan** [comment]
@andytimes *Yay!*

![2016-04-30-124025_752x404_scrot](https://cloud.githubusercontent.com/assets/13862535/14933900/c34491e0-0ed0-11e6-8026-018026283900.png)

**Comment by imcaffrey** [comment]
Kguan的dns是啥来着……我找不到了

**Comment by K-Guan** [comment]
# PIA servers
    nameserver 209.222.18.222
    nameserver 209.222.18.218

让你不保存。

**Comment by aofall** [comment]
用TAB还是imouto.host那边带出来的
1是整齐美观 2可能是在vi/vim下的习惯
空格和tab并没有什么差别 *nix和Windows都可以识别
其他网站CNAME到Google并不奇怪，他们用的Google hosted，Google为了方便管理域名解析和分地区加速就让他们用CNAME了，就像www.aofall.com CNAME 到 jx.yge.me 一样
只要最后的ip解析正确就行了

**Comment by K-Guan** [comment]
@aofall 我的 vim 设定是自动将 Tab 转换成四个空格……导致每次编辑 hosts 的时候都得禁用这个功能。

**Comment by andytimes** [comment]
@K-Guan 加上这一条在 .vimrc

`autocmd Filetype conf set noexpandtab`

即可

**Comment by andytimes** [comment]
@aofall http://www.aofall.com 首页赞

> 如果我会变成恶魔，那就随他吧。我会接受放逐，一切只为了保护她。

貌似首页文字是随机的。

**Comment by imcaffrey** [comment]
这些话都好赞

**Comment by imcaffrey** [comment]
@andytimes http://hitokoto.us/api.html 太强了！

**Comment by andytimes** [comment]
@imcaffrey 不懂 js

**Comment by K-Guan** [comment]
@imcaffery `<script type="text/javascript" src="http://api.hitokoto.us/rand?encode=js&charset=utf-8&length=40"></script>` 原来哦。

**Comment by K-Guan** [comment]
@andytimes 居然之前没发现 hosts 的类型也是 conf 。Nice.

**Comment by andytimes** [comment]
@K-Guan 这个不用记，而且记了也不一定准确，应该用 :set filetype 检测。

其实，可以只把 Python 的 tab 转空格开启。这样更好一点。

之前我的 vim 配置混乱，万恶之源就是给 vim 装了插件，几个月前尝试用了几个插件，后来发现挺累赘，全卸了很清静（不知道 Python，JS 的
vim 插件是什么情况，我是不会再装插件了）。

最近发现 subsurface 的 vim 配置不错（C++），抛个链接：

https://github.com/torvalds/subsurface/blob/master/CodingStyle
我稍微改一改，放 Coding 的 IDE 试试发现效果不错，当前配置：
https://gist.github.com/andytimes/3d3c6cca799705c5f53b1d6f4bfb8996

Kevin Guan <notifications@github.com>于2016年4月30日周六 下午6:21写道：

**Comment by K-Guan** [comment]
@andytimes 这个嘛……

![2016-04-30-190015_599x238_scrot](https://cloud.githubusercontent.com/assets/13862535/14935487/d961512c-0f05-11e6-9c64-25aea6738a7f.png)

这些插件陪我少说得有半年了，都是挺不错的。如果有兴趣的话建议去 [Vim Awesome](http://vimawesome.com/) 看看。当然了，这些只有很少的几个是语言相关的。比如 Vim Airline 是美化的， Rainbow Parentheses 负责让嵌套的括号变得漂亮些（另外的好处是，少个括号的话直接就能从颜色上看出来）。Vim Multiple Cursors 提供了多光标的功能等等。

**Comment by aofall** [comment]
看你们玩插件玩的挺嗨的，弱鸡我apt-get install vim 后就直接用了
虽然没学过python 但还是知道python中空格和TAB是不能混用的

**Comment by imcaffrey** [comment]
弱鸡我直接用了spf13-vim……

以及……这个issue下的讨论是不是话题偏离了

**Comment by Too-Naive** [comment]
我们有gitter!

**Comment by andytimes** [comment]
@K-Guan 我觉得美化倒是无所谓（虽然可以改善心情），配置简单一些，可以直接贴到其他电脑里，比较方便。（虽然可以用 U 盘作镜像来快速安装，但觉得没必要，不装插件就没有心理负担了）

**Comment by andytimes** [comment]
@aofall 我也是没有配置用了很久，只是自从听说 vim 有插件这种东西，才慢慢在意 vim 这些。
实际有些属性确实应该在 .vimrc 设置一下，虽然不是必须的，但会带来不少便利。

**Comment by andytimes** [comment]
@imcaffrey http://vim.spf13.com/
# The Ultimate Vim Distribution
看到这句介绍就知道插件肯定堆成山了，很可能出现开一个文件都要 2 s 的情况。

开 Issue 的童靴不出来表态，这个也没办法。主要是 Gitter 在 Gmail 优先级太低
Github 在邮件提醒比较快。

**Comment by Too-Naive** [comment]
Gitter是未读消息才会提醒= =

**Comment by andytimes** [comment]
@Too-Naive 对了，问一个问题。为什么你的程序用 tchar.h ？（这个头文件我见过，但没有接触相关知识，搜索一下，好像和 VC++ 有关）。

**Comment by aofall** [comment]
（摊手）我不用Gitter，能不注册的网站尽量不去注册 就算他支持我已经注册的第三方网站登陆。
至于之前讨论过的利用公开反代过墙的方法我的想法是不加，或者说不加在主分支，另建一个分支然后像[ipv6-hosts][https://github.com/lennylxx/ipv6-hosts/tree/master/snippets] 这么弄，自取所需部分，但反代出的BUG就不是我们能管的了，对于使用反代出问题的bug是直接关issue还是啥？

**Comment by K-Guan** [comment]
@andytimes 因此我不但有备份 home 的习惯，还自己写了 Arch 的 安装/配置 两个脚本。所以每次重装时我可以很轻松的将我的系统还原到我想要的形态。

<sub>*然而我还在努力追求简单，于是就用上了 btrfs （不过：1. 最近懒得去琢磨这货究竟怎么用。 2. 话说……好像因为 btrfs 不支持 swap 的问题，我的 2G 内存有点吃不消……所以一天死机三次已经是家常便饭了。）*</sub>

**Comment by Too-Naive** [comment]
![](https://cloud.githubusercontent.com/assets/16496671/14935874/f2220ec8-0f13-11e6-8910-febad4066da9.png)为了调试tool已经要打算重启了

**Comment by Too-Naive** [comment]
@andytimes 因为兼容VS........

**Comment by andytimes** [comment]
@K-Guan 觉得 ext4 更适合日常使用

**Comment by imcaffrey** [comment]
备份 home是好习惯……

我想起了中国好同学@cjsoft....

**Comment by cjsoft** [comment]
@imcaffrey 啥？

**Comment by andytimes** [comment]
@aofall 只是个人观点：
现在 hosts 足够好用了。既然没有问题，又何必去改呢？
而且目前好像没有太多人要求用反代。

如果确实反代比目前的 hosts 好用，也可以尝试啊，这些都无所谓了，关键是有没有人去弄。

**Comment by Too-Naive** [comment]
VS有毒 定义了UNICODE 
然后 那些什么`CopyFile` `DeleteFile` 都有两个版本
`CopyFileA` (For ANSI) `CopyFileW` (For Unicode)
所以需要tchar.h来转换
`_T("...")` 当define UNICODE时 字符串为`L"..."`而没有定义时为`"..."`

**Comment by imcaffrey** [comment]
@andytimes 我感觉没必要加反代……上回我给加进去的时候当即就出了问题

**Comment by andytimes** [comment]
@Too-Naive 感谢！

我记得去年（或是前年）有人跟我说过这个问题，我找了一下，那位朋友是这样说的：

“...
**即使是商业公司开发的VS也会出现兼容性问题，比如宽字符问题导致我所有的中文字符串都要加_T()，这当时差点让我跪**。
...”

**Comment by Too-Naive** [comment]
然而 我们可以在所有函数前面都加上A

**Comment by K-Guan** [comment]
@andytimes 现在发现了……而且没想到 Chrome 居然如此吃内存。不过我对于内存和硬盘的使用向来“节俭”，所以问题不是太大。

**Comment by K-Guan** [comment]
@imcaffrey 嗯嗯嗯嗯嗯嗯嗯嗯嗯嗯。

**Comment by andytimes** [comment]
@K-Guan Chrome 占内存也没有那么夸张，主要是网页缓存太大。
我觉得电脑卡死的原因，可能是系统用了 tmpfs 文件系统，把这个关掉，或调小可能会有改善。

**Comment by Too-Naive** [comment]
Chrome ![](https://cloud.githubusercontent.com/assets/16496671/14936499/f1d771c6-0f20-11e6-9b30-550aa881901d.png)

**Comment by andytimes** [comment]
@Too-Naive 听你说完这些，觉得程序跨平台可能无望了（虽然 Linux 下也有 MinGW）

**Comment by Too-Naive** [comment]
@andytimes 只要有`#include <windows.h>` 跨平台就无望

**Comment by K-Guan** [comment]
@andytimes （具体没研究，反正我用 `free` 测过，打开 Chrome 后内存占用率直接提升五倍，再开几个标签页就直奔八倍了。）

**Comment by andytimes** [comment]
@K-Guan 这个没办法，只能升级硬件，少开标签。
https://support.google.com/chrome/answer/6152583?hl=zh-Hans
这是 Google 官方的解决方案。

监控进程推荐用 htop （top 也可以）

**Comment by andytimes** [comment]
@K-Guan @Too-Naive 图片来自网络
![img1](http://cdn.pingwest.com/wp-content/uploads/2015/04/Chrome1.gif?imageView2/2/w/750/q/90)

貌似有插件来解决这个问题， 
https://chrome.google.com/webstore/detail/the-great-suspender/klbibkeccnjlkjkiokjodocebajanakg

参见：http://blog.sina.com.cn/s/blog_69f409850101etuf.html

**Comment by Too-Naive** [comment]
8G内存已经不够用了

**Comment by andytimes** [comment]
@Too-Naive 8 G 内存条都是白菜价了，只要电脑支持 DDR3，加一条就是了。

**Comment by Too-Naive** [comment]
而我才4G。。

**Comment by imcaffrey** [comment]
@andytimes chrome占内存真的太厉害了……

以及我要吐槽mingw……它的名字是**Minimalist GNU for Windows**

**Comment by cjsoft** [comment]
16G路过、、、
不过我是O党

**Comment by andytimes** [comment]
@imcaffrey 抱歉，我误解了。Linux 下那些是交叉编译工具链 (cross toolchain)，我误解成 runtime 了。

我记得一次，我开了三十个 Github 的标签后，内存爆到快 2 G。多标签肯定耗内存，少开应该没什么问题。

@cjsoft 我以前用 Symbian 系统就是这个浏览器，速度很快，唯一不好的就是排版有问题（那是中国还出了一个欧朋，不知道现在是否还活着），新版 Opera 已经是 Chromium 内核了

**Comment by cjsoft** [comment]
@andytimes 我看了opera的关于界面、、还真是chromium内核。不过opera给我的体验比chrome要好。所以我半年多以前已经弃chrome投opera了
之前我还用ff，ff的插件生态感觉比chrome和opera都好，插件质量也非常高，但是资源占用实在是太大了，受不了

**Comment by andytimes** [comment]
@cjsoft Firefox 的服务器好烂，加上启动时间太长，虽然插件很强大，但我一般不用。
opera 据说被 360 收购了，感觉挺可惜。

**Comment by andytimes** [comment]
@fz420 建议阁下联系那个软件的作者，我觉得应该让软件作者加上 tab 的识别功能，
而不是让 hosts 文件去迎合工具。

**Comment by K-Guan** [comment]
@andytimes Opera 会被 360 收购？ Opera 是外国公司呀。

**Comment by K-Guan** [comment]
@andytimes 嗯，这个插件好像不错。我之前有用 [OneTab](https://chrome.google.com/webstore/detail/onetab/chphlpgkkbolifaimnlloiipkdnihall)，不过看来“休眠”一个网页要比这个方便些。等会试试看。

**Comment by andytimes** [comment]
@K-Guan 搜索关键字 “opera 360 收购”，我看了评论，好像有一堆人抱怨那个插件崩溃率太高、、、

**Comment by cjsoft** [comment]
@andytimes ←\_←，opera千万别干傻事啊，被大数字qj可不好啊

**Comment by K-Guan** [comment]
@andytimes 嗯，等会我瞧瞧去。

**Comment by K-Guan** [comment]
@andytimes 好吧，居然还真玩。 Google "Opera 360" 就能找到了，甚至连 Qihoo 都不用打……http://techcrunch.com/2016/02/09/chinese-tech-group-led-by-qihoo-360-bids-1-2b-for-browser-maker-opera/

**Comment by andytimes** [comment]
@K-Guan tools/README.md 里面的脚本链接已挂，
点击链接 http://keving.pythonanywhere.com/hosts_scripts/script_tool_for_windows.bat
显示如下内容：
> Not Found
>
> The requested URL was not found on the server. If you entered the URL manually please check your > spelling and try again.

我先加一个 Release 来修复。

**Comment by K-Guan** [comment]
@andytimes 我看到你的 comment ，顿时闪过两个念头：

1. 不可能！！！！明明上次我亲自大幅重写的代码并测试过没问题的。
2. 唉，对呀。上次我大幅重写代码，为了迎合 @Too-Naive 的修改，将链接都分别改成了 `/windows.bat`, `/linux.sh`, 和 `/lhosts`了。比如说：

        http://keving.pythonanywhere.com/hosts_scripts/.bat

**Comment by imcaffrey** [comment]
@andytimes link has changed

script_tool_for_windows.bat --> windows.bat

**Comment by K-Guan** [comment]
@imcaffrey `The [...] been [...].`

**Comment by andytimes** [comment]
@K-Guan 貌似权限问题还是存在，不过，能点击下载就好！

**Comment by K-Guan** [comment]
自然，不是讨论过解决不了了嘛。

**Comment by imcaffrey** [comment]
@K-Guan ???
@andytimes landed now in https://github.com/racaljk/hosts/tree/master/tools

**Comment by K-Guan** [comment]
@imcaffrey 我是说刚才你那句，好像改成 `The link has been changed.` 更好些。
@andytimes 唉？你废弃 `linux.sh` 了？

**Comment by imcaffrey** [comment]
嗯嗯有道理
---
好像是废弃了hhh

**Comment by K-Guan** [comment]
既然如此，我也去把我那边的代码再改改好了。

**Comment by andytimes** [comment]
@K-Guan 没有维护价值了，反正新脚本也是从 linux.sh 改过来的，该有的东西都有。

**Comment by K-Guan** [comment]
嗯，我也赞同。刚刚废了 `/linux.sh` 。

**Comment by Too-Naive** [comment]
自从入坑此项目[一个月](https://cloud.githubusercontent.com/assets/16496671/14942637/1445475e-0ff5-11e6-9892-b11d49b38216.png)

**Comment by K-Guan** [comment]
（看到 @Too-Naive 这样说，感觉颇有股不知天高地厚的样子。想起自己对本项目的贡献很想顺口讥讽 @Too-Naive 一下，不过想想还是算了。

一是 @andytimes 在此，我实在没什么可说的。二是 @Too-Naive 的实力也不容小窥，[虽然离我还有点距离](https://github.com/racaljk/hosts/graphs/contributors)，但是看他这个实力……估摸着我这个第三名的位子也坐不太长，还是别总得罪他为好。

话说 @imcaffrey 明明来的比人家早还让人家给甩下了，不但如此还总去惹事。说起来比起 @Too-Naive 那个不知天高地厚劲是有过之而无不及了，还是不要去效仿的好……）

嗯……唉，我想说什么来着？对了，今晚上这边下雨了，还挺凉快的。所以……我先去码代码，等会还是早睡早起（好像已经不早了……）的好。大家继续慢慢聊啊。

**Comment by Too-Naive** [comment]
Orz 我只是想感叹自己原来能那么有干劲。。并不是什么嘲讽阿喂

**Comment by K-Guan** [comment]
我这不是即兴让大家五一过的快活快活嘛。好不容易来个节日我们别说 party 了，都不热闹热闹。实在很没意思唉。

**Comment by Too-Naive** [comment]
墙一日不倒 无快乐可言阿

**Comment by K-Guan** [comment]
*爆破小组第三中队！任务在即你们干嘛去了？？老方那破墙上面不早就下了通知吗？对，现在就去解决！*

**Comment by andytimes** [comment]
@K-Guan 不解，我怎么有这么多提交？
估计是更新脚本太频繁，还有一段时间 hosts 不稳定，我看到就随手更新了。

新脚本该有的都有了，应该不会有什么提交（其实，我也不想维护脚本了，测试脚本花费了我大量的时间）。

倒是希望闲暇时间去学一学 Lua 或 Python，考后准备去写几个自己的程序。

**Comment by Too-Naive** [comment]
钢筋混凝土掩体 厚度达60Em![](https://cloud.githubusercontent.com/assets/16496671/14873063/cd15c35e-0d24-11e6-81ec-9f97b2c120da.JPG)

**Comment by andytimes** [comment]
> 墙一日不倒 无快乐可言阿

@Too-Naive 然而墙的另一头，并非全都是令人快乐的东西。

**Comment by K-Guan** [comment]
@andytimes 现在有 @Too-Naive 和 @imcaffrey ，脚本之类的我觉得咱们都不用愁了。不是有句古话说什么 “长江后浪推前浪嘛”。作为项目主要领导人之一，我觉得你还是专门处理些大问题就够了。

**Comment by K-Guan** [comment]
@Too-Naive *核弹地毯式轰炸呗*

**Comment by K-Guan** [comment]
@andytimes 比方说？

**Comment by Too-Naive** [comment]
诚然。 墙倒了之后 这个项目也没有存在的意义了吧..

**Comment by K-Guan** [comment]
听起来好像为“了战士们混口饭吃我们绝对不能让世界和平了”似的……

**Comment by andytimes** [comment]
@K-Guan G+, Facebook, Twitter, 维基百科中文，BBC 中文网，看看首页动态就知道了。去 Gitter 聊吧

**Comment by imcaffrey** [comment]
@K-Guan 为啥把我拉进去一起婊……

**Comment by K-Guan** [comment]
@imcaffrey 唉？我记得你喜欢找 @Too-Naive 玩嘛。

**Comment by imcaffrey** [comment]
&#&&%^(%&&*!((#

**Comment by Too-Naive** [comment]
&#&&%^(%&&*!((#

**Comment by K-Guan** [comment]
#((!*&&%(^%&&#&

**Comment by cjsoft** [comment]
@imcaffrey 哈哈哈、心疼你

**Comment by imcaffrey** [comment]
@Too-Naive 您就是heheda吗% 失敬失敬

**Comment by Too-Naive** [comment]
有毒吧
![](https://cloud.githubusercontent.com/assets/16496671/14747730/62dc54fc-08e8-11e6-8e09-12005c61b21b.jpg)

**Comment by Too-Naive** [comment]
smg @imcaffrey

**Comment by imcaffrey** [comment]
哦那不是啊……

**Comment by Too-Naive** [comment]
![](https://cloud.githubusercontent.com/assets/16496671/14873063/cd15c35e-0d24-11e6-81ec-9f97b2c120da.JPG)

**Comment by imcaffrey** [comment]
幸好这里没多少人用uoj群，不知道静静【

**Comment by K-Guan** [comment]
（挑起战火的我还是在旁边慢慢看着……）

**Comment by cjsoft** [comment]
静静抢今日首签！

**Comment by imcaffrey** [comment]
静静抢今日首签！

**Comment by Too-Naive** [comment]
有毒吧 我还只是个孩子
![](https://cloud.githubusercontent.com/assets/16496671/14945197/49ed17c6-103e-11e6-80b8-f9f6b6dd33be.gif)

**Comment by imcaffrey** [comment]
`有你签到的时间可以多给妹子发菊花`

**Comment by Too-Naive** [comment]
![](https://cloud.githubusercontent.com/assets/16496671/14945201/67740a66-103e-11e6-8d04-3ac344217351.png)

**Comment by K-Guan** [comment]
（虽然想再说句话，不过刚刚意识到自己最近有些毒舌，本着“人道主义”……还是算了吧。）

**Comment by Too-Naive** [comment]
有毒

**Comment by Too-Naive** [comment]
@imcaffrey @cjsoft ![](https://cloud.githubusercontent.com/assets/16496671/14946970/e79f3da4-105d-11e6-8436-64f1efdfe25f.png)
