### ISSUE TITLE
google挂了好多

### ISSUE THREAD

**Issue by redapple0204** [racaljk/hosts#422]
一半网页打不开 深圳地区

**Comment by andytimes** [comment]
发来具体域名看看，我这里用 220.255.2.153 正常。

可以替换成 64.233.162.8x 这段看看

**Comment by redapple0204** [comment]
@andytimes 我的意思是：用google搜索一些东西无法打开，例如搜索weather就会出现无法打开

**Comment by andytimes** [comment]
@redapple0204 是不是这个问题？https://github.com/racaljk/hosts/issues/387

**Comment by redapple0204** [comment]
@andytimes 没错，就是这个问题，太感谢了

**Comment by aofall** [comment]
麻烦以后开issue前先自己排查一下或者搜索一下
如果我没记错的话你开了好几个不是我们能解决的issue

**Comment by aofall** [comment]
例如 #315 #316
