### ISSUE TITLE
小建议

### ISSUE THREAD

**Issue by racaljk** [racaljk/hosts#423]
1. 话说License第456条怎么感觉有点废话占页面，关于legal的免责已经在第三条提到了，就表明服务提供者已经履行了义务防止犯罪的责任，后面就没必须赘述了吧
2. tools的子目录命名和逻辑真的很反人类(￣▽￣)
3. README.md中windows平台下
> 用文本编辑器（如记事本等）打开文件：
常会出现换行符等问题导致hosts格式错误，所以应该另作推荐或者提醒一下吧

临近高考实在很忙，一直都没时间用pc，只能提提建议讨论一下

**Comment by K-Guan** [comment]
1. 看到这个 **第四百五十六条** ，我实在是感觉不是我们的 owner 在开玩笑就是我们的 README 的篇幅要……

2. 唉？有什么问题吗？

3. 这个换行符……怎么就不能统一统一？

**Comment by imcaffrey** [comment]
@K-Guan 是4、5、6条

**Comment by K-Guan** [comment]
1. （我要是没看出来就不故意用中文数字了）

2. 嗯…………

3. 不是有 Windows Git 客户端， `git clone` 什么的吗？

**Comment by Too-Naive** [comment]
Reply:
1. 求老大给建议阿...... 小的觉得这样看起来舒服就这样改了...
2. 咱们可以等高考之后找个时间相互讨论一下
3. 默认的换行格式就是unix... 记事本无法显示其实是正常的
4. 无论从何种方面来讨论....个人认为3并不能代替456... (我想咨询律师

以上

**Comment by Too-Naive** [comment]
手抖点错.....

**Comment by registe** [comment]
2. 建议整个tools分拆出去吧，不要集中到hosts这个repo里。用何工具更新可以在readme里提及一下，给个链接过去。
3. 换行符遇到过不止一次，应该是个别collaborator是win环境吧，建议每次他的pull request时，都注意检查下，不要随便merge。

**Comment by lautis0503** [comment]
第五条可删

**Comment by imcaffrey** [comment]
我也感觉……这个repo的方向是什么？
最初的时候是google hosts吧……现在是怎么计划的呢

**Comment by Too-Naive** [comment]
可以考虑分出一个Branch来存放tools那些工具... 这个我是滋磁的

**Comment by Ignotus-CN** [comment]
Making the project into an organization is the best idea in my opinion.

**Comment by Too-Naive** [comment]
~~(这样大大就拿不到star了~~

**Comment by aofall** [comment]
Windows环境并不要紧，我是Ubuntu Windows切着用的
关键是有的人直接拿记事本来编辑hosts，这才会导致换行符出错，好歹也装个Notepad++啊
Ps：记事本是个独立特行的奇葩货

**Comment by andytimes** [comment]
@racaljk Mac 那个 hosts Tool 是由  https://github.com/ZzzM/HostToolforMac 的源码编译来的二进制文件。查明是 https://github.com/racaljk/hosts/pull/239 这个 PRs 合进来的，建议删除。

原因：
1. 无源码，用户无法自行编译;
2. 维护者更新源码后，可能无法及时更新二进制文件（仓库本身就不该存放二进制文件）;
3. 更新二进制文件会增加仓库历史的负担。

Mac 工具占用了很大比例的空间：
```shell
$ du -sh tools/MacOS/
6.5M    tools/MacOS/
```

整个仓库空间（不含 .git 文件夹）：
```shell
$ du -sh hosts LICENSE README.md tools/
144K    hosts
4.0K    LICENSE
4.0K    README.md
6.7M    tools/
```

建议让维护 Mac 工具的作者自己提供二进制的下载地址，写到这边 README 里面。

**Comment by andytimes** [comment]
@aofall 主要是部分 PRs 是在线编辑然后提交过来的，这样导致 hosts 包含混合换行符。
Windows 记事本好久没用了，貌似那么多年也没有什么功能更新。

**Comment by andytimes** [comment]
@Ignotus-CN 工具放在 Organization 倒是可以，hosts 就别移动了，很多人要是用的以前的工具怎么办？

**Comment by redapple0204** [comment]
@andytimes 请用写字板。。。。就不会了

**Comment by andytimes** [comment]
@Ignotus-CN 工具放在 Organization 倒是可以，hosts 就别移动了，很多人要是用的以前的工具怎么办？

**Comment by andytimes** [comment]
> 可以考虑分出一个Branch:tools来存放那些工具... 这个我是滋磁的

@Too-Naive 虽然分 branch 操作是好办法。
但根据你的描述，可能需要创造第二个根提交，以保证这个**工具分支**的干净，
这个虽然不是很麻烦，但不推荐这么做。建议保持现状，就在 tools/ 里面更新。

**Comment by Too-Naive** [comment]
1. 可以移动的其实…… 让大大fork一个(
2. 直接mv出来就好了 这个我已经弄好了 参见 #426 对应的branch
3. 有两个organization名字不错 分别是gfwhosts和googlehosts 看看哪个比较合适的？(请放心 我已经抢注了

**Comment by imcaffrey** [comment]
https://github.com/hostsTools

**Comment by Too-Naive** [comment]
有趣阿。。 可是谁是owner阿。。

**Comment by Too-Naive** [comment]
https://github.com/HostsTool @imcaffrey  @andytimes @racaljk 我已经邀请你们加入组织了

**Comment by racaljk** [comment]
@all_participants

根据各位的反馈加之我之前的建议整合一下：

1.删除License的第五条。其实个人认为第四五六条都是过分的赘述。
2.把tools从repo分离出去，同时README.md中超链接提及即可。目前已由@Too-Naive执行，具体就是建立专门存放hoststool的org。个人建议保留简单的脚本，较大项目再做分离。
3. 关于tools可以考虑规范命名而不是WinConsole QtGui这种无法苟同的命名。
4.
> 用文本编辑器（如记事本等）打开文件： 
修改为
> 用文本编辑器（如notepad++） 打开文件：

反对/补充请指出:-)

**Comment by Too-Naive** [comment]
hhh 比较难以思考的问题是命名方式 因为完全不知道如何命名qwq
![](https://cloud.githubusercontent.com/assets/16496671/14747730/62dc54fc-08e8-11e6-8e09-12005c61b21b.jpg)
另 第一点已经写在pr里了 随时可以合并 @racaljk

**Comment by andytimes** [comment]
@Too-Naive 我不维护 HostsTool，不用邀请我。关于命名，可以平台划分。比如，

macos/    windows/    cross-platform/    之类的。

**Comment by andytimes** [comment]
@racaljk 感觉 README 里面的 License 都是多余，MIT 已经有：
> THE SOFTWARE IS PROVIDED “AS IS”, WITHOUT WARRANTY OF ANY KIND

倒是 CC 发布的东西应该注意一下，CC-BY-NC-SA 这个不是许可证，没有法律效益

**Comment by imcaffrey** [comment]
CC没有法律效益吗？

**Comment by imcaffrey** [comment]
以及不需要的话我把那个hostsTools的org注销掉

**Comment by Too-Naive** [comment]
@imcaffrey 您注销掉我再改个名√ 万事大吉

**Comment by racaljk** [comment]
@Too-Naive
 关于规范命名可以参考@andytimes的建议

@andytimes 嘛...License是一种态度，我觉得越精简越好（但不是以牺牲信息熵为代价

**Comment by Too-Naive** [comment]
@racaljk 已经修改完了 @HostsTool

TODO: README.md at master

**Comment by imcaffrey** [comment]
Done.

**Comment by Too-Naive** [comment]
Good job. @imcaffrey

**Comment by Too-Naive** [comment]
@imcaffrey @andytimes ..求帮我revert最后一个提交.. 我上传错branch了... 电脑没有git客户端没法弄revert

**Comment by andytimes** [comment]
@imcaffrey 我描述错误，不是没有法律效益。
我指的自由软件许可证是对软件的使用无担保。CC 没有。要注意这个问题。

**Comment by K-Guan** [comment]
@Too-Naive 说起你的 NAI，我觉得应该补充一句：“—— @Too-Naive 敬上” 。（当然，我是又闲的了。）

**Comment by Too-Naive** [comment]
不支持右对齐 没法写敬上

**Comment by K-Guan** [comment]
哦

**Comment by Too-Naive** [comment]
教我revert怎么写啊。。。

**Comment by K-Guan** [comment]
（问 @imcaffrey 或 Google，反正我也不会）

**Comment by andytimes** [comment]
@Too-Naive 我上次有传给你一个 pdf，看完后就基本就可以用 git 高效管理代码了。
在线看这个 https://git-scm.com/book/zh/v2/

以下是获取 revert 帮助信息的方式：
Linux:
`man git-revert`

Windows & Linux（通用）:
`git revert --help`

在不会的命令后面加上 --help 一般都能得到帮助。

不建议网络搜，虽然能快速得到答案，但如果看的是半吊子写的博客，贻害无穷。

**Comment by Too-Naive** [comment]
我做个声明阿……
我今天得到消息说我过了初审 所以在将来的时间里 就不会再贡献什么东西了 认真备考 ~~偶尔来水水也是支持的~~
![](https://cloud.githubusercontent.com/assets/16496671/14747730/62dc54fc-08e8-11e6-8e09-12005c61b21b.jpg)

**Comment by K-Guan** [comment]
（既然你都这么说了……今天我就不借题发挥了。）

**Comment by wsdjeg** [comment]
https://github.com/fxckgfw
here is a org which is using same icon

**Comment by Too-Naive** [comment]
I will change the icon. @wsdjeg  thanks.

**Comment by andytimes** [comment]
> License是一种态度，我觉得越精简越好（但不是以牺牲信息熵为代价

@racaljk 记得以前和你讨论过[雨伞道德](http://www.ccln.gov.cn/haiwaifengcai/hwwz/130917.shtml)的问题。实际你表述的 LICENSE 态度，确实起到了这个作用。

**Comment by andytimes** [comment]
> README.md中windows平台下 > 用文本编辑器（如记事本等）打开文件： 常会出现换行符等问题导致hosts格式错误，所以应该另作推荐或者提醒一下吧

已修改记事本为 Notepad++，其他的 @Too-Naive 已经根据你的要求修改了。

**Comment by Too-Naive** [comment]
@racaljk 我记得您以前的头像是一个墙然后旁边一个炸弹？还是我记错了?

**Comment by K-Guan** [comment]
*close all teh thingz*

**Comment by Too-Naive** [comment]
Not pull request, Not issue.

**Comment by racaljk** [comment]
@andytimes 涨姿势。感觉在知乎上看过类似的讨论，现在才知道那个问题来源就是这个雨伞道德。

@Too-Naive 很明显你记错了...
