### ISSUE TITLE
debian替换完hosts出现了这个sudo问题

### ISSUE THREAD

**Issue by redapple0204** [racaljk/hosts#428]
没当输入sudo就会出现
sudo：无法解析主机：bogon

**Comment by Too-Naive** [comment]
?能说得详细一点吗

**Comment by racaljk** [comment]
把hosts复制到你的/etc/hosts中（保留原有内容），并删除下面这一段：
> # Localhost (DO NOT REMOVE)
127.0.0.1	localhost
255.255.255.255	broadcasthost
::1	localhost
fe80::1%lo0	localhost
# Modified hosts start

（但是那只是个warning应该不会影响sudo的使用吧，还是说我记错了..）

**Comment by redapple0204** [comment]
@racaljk 表示一直都是这样子了..(从去年9月开始)

**Comment by fluviusmagnus** [comment]
@redapple0204 你的主机名现在显示的不会就是 bogon 吧？

虽然我不太清楚，但我觉得可能是这样的问题：http://blog.csdn.net/yechaodechuntian/article/details/44337467

然后在 hosts 文件里没有这条解析，故报错。

（以上为猜测）

**Comment by K-Guan** [comment]
我怎么记得这个问题你好久之前问过我一次，然后解决方案是：删除上面 @racaljk 说的，再加上 `127.0.0.1   bogon` ？

**Comment by redapple0204** [comment]
@K-Guan 老方法失效了。。。。。

**Comment by redapple0204** [comment]
@K-Guan 是的，而且不止一次，然而现在老方法失效了。。。。。

**Comment by redapple0204** [comment]
@fluviusmagnus 好的，我看看

**Comment by imcaffrey** [comment]
应该就是127.0.0.1丢了的问题吧……？

**Comment by andytimes** [comment]
把 `hostname` 和 `uname -n` 执行后的输出发来看看。

**Comment by Too-Naive** [comment]
@redapple0204 问题解决？

**Comment by redapple0204** [comment]
@Too-Naive 问题ok了，谢谢
