### ISSUE TITLE
请求添加photobucket网站的ip

### ISSUE THREAD

**Issue by xinconan** [racaljk/hosts#431]
使用移动的网，[photobucket.com](http://photobucket.com/)进不去，做电商需要使用photobucket存储图片。希望能够添加photobucket网站的ip

**Comment by laodcn** [comment]
電信網絡可以進得去.... 
你試試 209.17.80.100
不行還是換網絡運營商吧，移動網牆中牆

**Comment by LGA1150** [comment]
不支持https就无解

**Comment by LGA1150** [comment]
不过你可以试试铁通的缓存服务器，如 122.72.32.40 ，在hosts中把域名指过去即可
不过电信联通无法访问这个IP，所以不太可能整合到本项目中

**Comment by aofall** [comment]
好好的贴图库不用非要用国外图站……
http://www.kekaoyun.com/

**Comment by imcaffrey** [comment]
`loli.io` `sm.ms`
