### ISSUE TITLE
android开发相关的google网站挂了

### ISSUE THREAD

**Issue by OumaSyuu** [racaljk/hosts#432]
您好，跟android开发相关的google网站好像挂了,gmail没挂,可否测试一下,谢谢!

**Comment by DaleXiao** [comment]
work alright here...

**Comment by Too-Naive** [comment]
能不能具体说明一下域名？ @OumaSyuu

**Comment by OumaSyuu** [comment]
https://tools.android.com/recent
然后是android studio check for update 的时候提示connection time out

**Comment by OumaSyuu** [comment]
这么久才回复真是不好意思, 我这边的情况是没有代理,自动获取dns, google搜索引擎可用, gmail可用
https://dl.google.com/android/studio/patches/updates.xml 早上不行,现在可用

**Comment by imcaffrey** [comment]
间歇抽风系列？

**Comment by OumaSyuu** [comment]
现在测试了一下, android studio check for update 已经无connection time out提示...... 难道墙也要休息......

**Comment by LGA1150** [comment]
tools.android.com 只支持http

**Comment by Too-Naive** [comment]
@OumaSyuu 核实了一下正如 @LGA1150 所说 http可以连接 另 https即使挂ss也无法连接 ERROR_CONNECTION_CLOSED

**Comment by OumaSyuu** [comment]
明白了,我这边原来是android.com强转https, 非常感谢!
