### ISSUE TITLE
發現一些FB域名

### ISSUE THREAD

**Issue by laodcn** [racaljk/hosts#433]
如：
https://live.fb.com/
https://work.fb.com
https://messengerplatform.fb.com/
https://nonprofits.fb.com
https://threatexchange.fb.com/
https://techprep.fb.com/
https://managingbias.fb.com/
https://rightsmanager.fb.com/
https://instantarticles.fb.com/
等等...

還有一些沒有採用SSL（https）的域名...

我試了很多https域名，試了很多ip都是會直接轉跳至Facebook首頁。

而使用SS卻正常，理論上https是可以穿過去的...

在此想看看大家有沒有怎麼辦法，或者是我哪裡弄錯了？

**Comment by Too-Naive** [comment]
会不会有这么一种可能… 对中国IP实行跳转？

**Comment by LGA1150** [comment]
可能是你弄错IP了
192.0.78.12
192.0.78.13

**Comment by laodcn** [comment]
@LGA1150 192.0.78.* 都是WordPress的

**Comment by lautis0503** [comment]
LGA1150正解

**Comment by imcaffrey** [comment]
看起来是wordpress的哎

**Comment by laodcn** [comment]
然而並不能用，我試了很多ip都不行

**Comment by aofall** [comment]
[root@PtSG ~]# nslookup live.fb.com
Server:		157.7.180.133
Address:	157.7.180.133#53

Non-authoritative answer:
live.fb.com	canonical name = fbliveblog.wordpress.com.
fbliveblog.wordpress.com	canonical name = lb.wordpress.com.
Name:	lb.wordpress.com
Address: 192.0.78.12
Name:	lb.wordpress.com
Address: 192.0.78.13

被CNAME至WordPress上，可能你搞错ip了
Google都有一些服务不能用同一个ip
Fb自然也有
还有 记得以https的形式访问

**Comment by lautis0503** [comment]
除了messengerplatform.fb.com和threatexchange.fb.com外其他都是192.168.78.12，我这里至少能打开首页

**Comment by aofall** [comment]
192.0.78.12 live.fb.com
192.0.78.12 work.fb.com
192.0.78.12 techprep.fb.com
192.0.78.12 nonprofits.fb.com
192.0.78.12 managingbias.fb.com
192.0.78.12 rightsmanager.fb.com
192.0.78.12 instantarticles.fb.com
192.0.66.2 messengerplatform.fb.com
199.201.64.67 threatexchange.fb.com

**Comment by laodcn** [comment]
192.0.78.12 居然可以了，上星期是不行的

**Comment by Too-Naive** [comment]
now in 74b2f2d9b1cad7249c1f55c0271f00fdca070b66

**Comment by Too-Naive** [comment]
There is something wrong with github?
