### ISSUE TITLE
Why do we need an English version of README?

### ISSUE THREAD

**Issue by K-Guan** [racaljk/hosts#434]
That's useless I think, since all the users of hosts are Chinese.

**Comment by K-Guan** [comment]
And by the way, I'm not sure that use *checks* here is correct. @imcaffrey any ideas?

> Great Firewall checks IPs or keywords to blocks people who live in China visit some "harmful" website.

*I think we should **avoid use avoid** anyway.*

**Comment by imcaffrey** [comment]
Why do we speak in English?
That's useless I think, since all the users of hosts are Chinese.

**Comment by imcaffrey** [comment]
啊我才发现是静静刚加上去的wiki…… @Too-Naive

**Comment by K-Guan** [comment]
@imcaffrey 敢跟我顶嘴……

**Comment by imcaffrey** [comment]
GFW 是 he 还是 she 呢？

**Comment by K-Guan** [comment]
总之该用 `is` 就对了。

**Comment by Too-Naive** [comment]
.... No no no. Some foreigner found this project but doesn't how it work. And help foreigner who live in China to visit Google website and so on
![](https://cloud.githubusercontent.com/assets/16496671/15182852/174f4ea8-17c1-11e6-99b2-192b51bf2fb0.gif)
![](https://cloud.githubusercontent.com/assets/16496671/15182976/a6bd5b48-17c1-11e6-8eb3-3718dd4eb8b5.gif)
![](https://cloud.githubusercontent.com/assets/16496671/15183015/d74c0c6e-17c1-11e6-83c4-cedb962e08e5.gif)

**Comment by imcaffrey** [comment]
有毒啊……

**Comment by Too-Naive** [comment]
没有毒

**Comment by Too-Naive** [comment]
@K-Guan 不是It吗……

**Comment by K-Guan** [comment]
@Too-Naive 

> .... No no no. Some foreigner**s** found this project but doesn't **know** how it work. And help foreigner**s** who live in China to visit Google website and so on.

另外好像确实是 It 。

**Comment by Too-Naive** [comment]
.... 我手太快了
![](https://cloud.githubusercontent.com/assets/16496671/14747730/62dc54fc-08e8-11e6-8e09-12005c61b21b.jpg)
上次不是有外国人在gitter问吗…

**Comment by imcaffrey** [comment]
>* Some foreigners found this project but **didn't** know how it work

**Comment by K-Guan** [comment]
@imcaffrey *哦*

**Comment by K-Guan** [comment]
@Too-Naive 唉？有吗？

**Comment by Too-Naive** [comment]
有噢

**Comment by K-Guan** [comment]
@Too-Naive 好吧没注意，可是你在 Wiki 里扔个 README 别人真的能看到吗？

**Comment by K-Guan** [comment]
哦，刚刚找到一个不错的网站，测 DNS 用的：https://www.dnsleaktest.com/

**Comment by Too-Naive** [comment]
@K-Guan 我在README里面标明了啊.. English Version

**Comment by Too-Naive** [comment]
![](https://cloud.githubusercontent.com/assets/16496671/15204682/a8a4a048-1842-11e6-8de7-943c15714027.png)

**Comment by K-Guan** [comment]
1. 这个……我还是觉得如果真的有必要的话，还是将 README 扔在根目录吧。（English version? English version of what?）

2. 检测结果出来了，你的 DNS 绝对有问题。

**Comment by Too-Naive** [comment]
218.85.157.99 这是学校的DNS

**Comment by K-Guan** [comment]
@Too-Naive 反正我的 DNS 可以免 VPN 访问那个网址的。

**Comment by Too-Naive** [comment]
有毒吧。。

**Comment by Too-Naive** [comment]
无所谓根不根目录嘛 把那个放在显眼一点的链接就可以了

**Comment by Too-Naive** [comment]
@imcaffrey 相比之下我觉得应该开一个PR 把这条写进去
    127.0.0.1 girigiri.love

**Comment by K-Guan** [comment]
@Too-Naive 刚刚打开了下……半个字也不认识。

**Comment by Too-Naive** [comment]
是让你听歌|･ω･｀)

**Comment by imcaffrey** [comment]
127.0.0.1 baidu.com

**Comment by Too-Naive** [comment]
我建议把google重置那些什么的 也写到readme上。。。 我已经收到了十几个问题饿了
