### ISSUE TITLE
Mac OS复制hosts后没有翻墙表现

### ISSUE THREAD

**Issue by sumlitLin** [racaljk/hosts#435]
把hosts复制到你的/etc/hosts中（保留原有内容） 就可以翻墙Google Facebook 了吗？我的貌似没反应啊

**Comment by Too-Naive** [comment]
您有试过"重置网络"吗?

**Comment by sumlitLin** [comment]
mac 怎么“重置网络”。。  表示刚才重新启动 hosts文件又还原了

**Comment by Too-Naive** [comment]
您确定您有保存成功吗

**Comment by sumlitLin** [comment]
ok 了 不知道为什么刚才不行 现在可以了 谢谢

**Comment by redapple0204** [comment]
@Too-Naive 然而我都是用https://google.com.hk 。。。。。

**Comment by Too-Naive** [comment]
@redapple0204 无所谓 能用就行
