### ISSUE TITLE
请求支持telegram

### ISSUE THREAD

**Issue by gameclamp** [racaljk/hosts#438]
telegram.org和web.telegram.org

**Comment by Ignotus-CN** [comment]
web.telegram.org 可以访问。

**Comment by makosolo** [comment]
我的网比较烂，移动和WIFI都不行

**Comment by Too-Naive** [comment]
那么是否有必要添加到项目中呢

**Comment by imcaffrey** [comment]
我这里打不开

**Comment by aofall** [comment]
#406

**Comment by lautis0503** [comment]
我这里也打不开

**Comment by Too-Naive** [comment]
> 最近的PR有瞎忙活的节奏啊……
Telegram不用加，因为加了也没用
和YouTube一样是靠所在地重定向的（还是靠电话号码？）
而且是重定向到IP
亚太区的IP已经被封了
只能上个官网干瞪眼有毛用啊 还不如不加

@aofall

**Comment by aofall** [comment]
149.154.167.99 telegram.org
    149.154.167.99 www.telegram.org
    149.154.167.99 desktop.telegram.org
    149.154.169.99 core.telegram.org
    149.154.167.80 updates.tdesktop.com
    149.154.167.120 web.telegram.org
    149.154.171.22 flora.web.telegram.org
    149.154.167.118 telegram.me
    149.154.167.118 www.telegram.me

**Comment by wp5z** [comment]
@aofall  core.telegram.org IN A 149.154.167.99

**Comment by andytimes** [comment]
https://servers.blog.ustc.edu.cn/2016/10/add-telegram-web-service/

前两天中科大的 LUG 增加了了网页版 Telegram 服务，
Github 上的源码 https://github.com/ustclug/telegram-web
