### ISSUE TITLE
深圳这边android开发的hosts基本全挂了

### ISSUE THREAD

**Issue by cikichen** [racaljk/hosts#439]
google首页能开，但是会经常出现连接重置。
Android开发相关的比如android studio,sdk更新等全挂了。
https://dl.google.com/android/studio/patches/updates.xml  ERR_CONNECTION_TIMED_OUT

**Comment by 769344359** [comment]
修改到镜像服务器，或者改vpn吧

**Comment by cikichen** [comment]
@769344359 公司开发机各种限制，用不了vpn，麻烦更新下dl.google.com的hosts，谢谢

**Comment by 769344359** [comment]
不能换成国内镜像吗？

**Comment by imcaffrey** [comment]
64.233.162.8x?

**Comment by aofall** [comment]
联通用
61.49.62.49 dl.google.com
电信直接删掉dl.google.com的记录

**Comment by cikichen** [comment]
电信用 64.233.162.82	dl.google.com
