### ISSUE TITLE
希望增加站点

### ISSUE THREAD

**Issue by fun5rt** [racaljk/hosts#44]
http://googlechromereleases.blogspot.com/
使用了host之后，上面的站点还是不能打开，希望可以增加。

**Comment by andytimes** [comment]
这个无解，googlechromereleases.blogspot.com貌似只能http方式访问，hosts的IP地址只能用https方式访问资源，
如果只看内容，可以直接https://translate.google.com.hk把网址输进去，当然图片就没有了

fun5rt <notifications@github.com>于2015年9月24日周四 下午11:10写道：

**Comment by racaljk** [comment]
上blogspot还是考虑其它fANqiAng方式吧

**Comment by fun5rt** [comment]
谢谢了原来是不能https的原因，看来还是得连vpn了

**Comment by wyj2046** [comment]
明白了, 谢谢
