### ISSUE TITLE
依旧无法打开so的登录

### ISSUE THREAD

**Issue by redapple0204** [racaljk/hosts#441]
这次用了https，但是依旧不行
![2016-05-16 19 56 13](https://cloud.githubusercontent.com/assets/16254644/15288886/b0d2f5e2-1ba0-11e6-8c5e-fd91edb9ad9f.png)

**Comment by imcaffrey** [comment]
吉林+1

**Comment by laodcn** [comment]
深圳電信表示正常

**Comment by Too-Naive** [comment]
F12 查看加载失败的资源
福建电信success
![](https://cloud.githubusercontent.com/assets/16496671/15291498/cfabb732-1bb0-11e6-8207-24926abcd934.png)

**Comment by imcaffrey** [comment]
哎……表示又好了
我觉得还是认定为间歇性抽风系列吧
v2ex.com/go/bb

**Comment by aofall** [comment]
我觉得你开的issue可以用模版式回复了

1.查阅本项目的wiki和issue
2.换宽带换DNS

**Comment by Too-Naive** [comment]
@aofall 我发现最常问的也就那几个问题嘛

**Comment by imcaffrey** [comment]
快快快、复习去
