### ISSUE TITLE
战地4和origin全部挂了

### ISSUE THREAD

**Issue by whinamp** [racaljk/hosts#443]
战地4和origin全部挂了，我在想能不能添加一下与此相关的内容呢？

**Comment by imcaffrey** [comment]
“”“
最后说一个无关这个 issue 的话，我还是希望更多朋友用 hosts 来学习，不要做多余的事情。
”“”

···
racaljk/hosts
:statue_of_liberty:最新可用的google hosts文件。
···

**Comment by Too-Naive** [comment]
We use this project to visit some "useful but block" website. If you want to visit some "useless" website, Please use VPN.

**Comment by imcaffrey** [comment]
不是说战地4和origin useless……

**Comment by Too-Naive** [comment]
我当然知道不是 只是相对于google而言 
![](https://cloud.githubusercontent.com/assets/16496671/14945197/49ed17c6-103e-11e6-80b8-f9f6b6dd33be.gif)

**Comment by imcaffrey** [comment]
放在这看看有没有人有解决方案吧

**Comment by whinamp** [comment]
呃。这个也确实没什么卵用，只是方便偶尔娱乐一下。先看看有没有人能解决的，如果没有的话就关了吧。谢谢。

**Comment by Pioneer-Linzi** [comment]
你们有没有别的host ，推荐一下

2016-05-20 16:11 GMT+08:00 whinamp <notifications@github.com>:

**Comment by imcaffrey** [comment]
@Pioneer-Linzi 

> 你们有没有别的host ，推荐一下

**Comment by Too-Naive** [comment]
@whinamp 虽然说这里不在国内 但是open issue也要按照基本法

**Comment by imcaffrey** [comment]
一脸茫然= =我发现我看不懂静静在说什么了

**Comment by Too-Naive** [comment]
![](https://cloud.githubusercontent.com/assets/16496671/14873063/cd15c35e-0d24-11e6-81ec-9f97b2c120da.JPG)
他一开始issue的名字

**Comment by imcaffrey** [comment]
![](https://cloud.githubusercontent.com/assets/16496671/14873063/cd15c35e-0d24-11e6-81ec-9f97b2c120da.JPG)

**Comment by whinamp** [comment]
@Too-Naive 当然，项目维护者的决定权也是很重要的。😂

**Comment by BROBIRD** [comment]
你们不要出了事情就跑得比香港记者还快

**Comment by Too-Naive** [comment]
任何事情都要按照基本法 @BROBIRD 
于是我就念了两句诗 叫做 苟利国家生死以 岂因祸福避趋之
![](https://cloud.githubusercontent.com/assets/16496671/14747730/62dc54fc-08e8-11e6-8e09-12005c61b21b.jpg)

**Comment by gisphm** [comment]
莫名其妙就膜起来了，这破站吃枣药丸。:joy_cat: 
![qq 20160524134345](https://cloud.githubusercontent.com/assets/3512120/15493288/9cfc8af4-21b5-11e6-9d9b-e2068016554d.gif)

**Comment by smounives** [comment]
是这样的，曾经，大概一年多前我有加过Steam、Origin、Uplay、Rockstar的相关hosts，当时只是为了加速，并且当时Origin在部分地区就存在被封的情况，而且即使修改成正确的IP也没用，只能用反代服务器代替，Steam部分好多都用的akamai的CDN，IP老在变所以后来全都删了

**Comment by BROBIRD** [comment]
@Too-Naive 你这ID吃枣药丸，赶紧滚去复习去
