### ISSUE TITLE
google搜索打不开

### ISSUE THREAD

**Issue by Lemonjay** [racaljk/hosts#444]
学校里的网，经常换hosts，最近google搜索一直打不开，不知道什么原因

**Comment by Too-Naive** [comment]
Have you ever try "https://google.com/ncr"?
If you found something wrong, please search in issue first.

**Comment by imcaffrey** [comment]
@Too-Naive 静静你该去复习英语了= =

**Comment by Too-Naive** [comment]
嘿嘿嘿 你怎么知道下午考英语噢
![](https://cloud.githubusercontent.com/assets/16496671/14747730/62dc54fc-08e8-11e6-8e09-12005c61b21b.jpg)

**Comment by shanyuxiyun** [comment]
@Too-Naive  
https://google.com/ncr
too slowly

**Comment by Too-Naive** [comment]
所有的域名都是指向同一个IP的 无所谓

**Comment by LGA1150** [comment]
如果有IPv6环境，你应该去 https://github.com/lennylxx/ipv6-hosts
