### ISSUE TITLE
google 开发者平台创建的项目模块打不开

### ISSUE THREAD

**Issue by clq123clq** [racaljk/hosts#447]
https://console.developers.google.com/iam-admin/projects
在google 开发者平台创建的项目模块打不开。
![image](https://cloud.githubusercontent.com/assets/10397865/15458187/6d933048-20c9-11e6-8949-f9186e693e29.png)

**Comment by Too-Naive** [comment]
We need the following IP:
```
cloudconsole-pa.clients6.google.com
servicemanagement.clients6.google.com
```

**Comment by clq123clq** [comment]
how to solve it？ @Too-Naive

**Comment by haowg** [comment]
找到这个域名对应的ip，加到hosts里面就行了 @clq123clq 。但是我不知道怎么找，是不是挂vpn，ping一下这个域名？

**Comment by haowg** [comment]
servicemanagement.clients6.google.com
172.217.25.74
cloudconsole-pa.clients6.google.com
216.58.221.10

**Comment by clq123clq** [comment]
好像还是不可以呢 @haowg

**Comment by haowg** [comment]
我没做错这个，猜是这样弄

**Comment by haowg** [comment]
你改完hosts重启一下网络呢？

**Comment by clq123clq** [comment]
我没重启我再试试

**Comment by clq123clq** [comment]
还是不行

**Comment by Too-Naive** [comment]
```
172.217.25.74 servicemanagement.clients6.google.com
216.58.221.10 cloudconsole-pa.clients6.google.com
```
加了之后就可用啊..

**Comment by clq123clq** [comment]
你那可以么？我试了咋不可以，是不是要重启电脑？

**Comment by Too-Naive** [comment]
重启试试吧..

**Comment by imcaffrey** [comment]
@Too-Naive 滚去复习

**Comment by laodcn** [comment]
我這裡直接用220.255.2.153就可以呀

**Comment by clq123clq** [comment]
还是打不开呀，220.255.2.153怎么用？

**Comment by clq123clq** [comment]
220.255.2.153 servicemanagement.clients6.google.com
220.255.2.153 cloudconsole-pa.clients6.google.com

 @laodcn 我这样用的，确实可以了，厉害。你怎么知道这个ip的？

**Comment by imcaffrey** [comment]
@clq123clq hosts里现在用的就是这个laod提供的Google IP
