### ISSUE TITLE
android下替换了/etc下的hosts，但是无效果

### ISSUE THREAD

**Issue by ShookGao** [racaljk/hosts#450]
同样的替换方式，直接下载hosts，然后替换/etc/hosts，在我的Linux电脑上就可以正常使用，但是替换到我的android手机上就不能用，为什么？

**Comment by clq123clq** [comment]
你是怎么替换的？我操作不了手机里的hosts文件

**Comment by ShookGao** [comment]
先要root，然后用RE文件管理器替换

**Comment by Too-Naive** [comment]
重启过了吗？ 重启过再看看有没有替换成功
如果嫌麻烦 可以用 [Hosts工具](https://github.com/hoststools/android)

**Comment by andytimes** [comment]
先用电脑转换下换行符，或者等更新

**Comment by imcaffrey** [comment]
@ShookGao 可以再测试下吗

**Comment by ShookGao** [comment]
Hosts工具也试过了，还是不行，重启什么的当然也是做过的，都不行;
我都不知道是不是现在的android手机不再使用/etc/hosts了啊，我的手机是三星NOTE5，系统是Android6.0.1;
用电脑转换换行符没试过，这个应该没关系吧？

**Comment by ShookGao** [comment]
@imcaffrey 我刚才重新更新了最新的hosts，手机可以用了！是为什么？是hosts文件本身有问题么？

**Comment by Too-Naive** [comment]
@ShookGao 看起来是的… 换行符替换了一次
