### ISSUE TITLE
请求添加iobit.com的域名

### ISSUE THREAD

**Issue by yy0535** [racaljk/hosts#451]
您好，
iobit.com  这个网站打不开，能添加吗？？

**Comment by imcaffrey** [comment]
群主！！群主！！群主！！群主！！群主！！群主！！群主！！群主！！群主！！群主！！群主！！群主！！群主！！群主！！群主！！群主！！群主！！群主！！

**Comment by Too-Naive** [comment]
ls在干嘛
![](https://cloud.githubusercontent.com/assets/16496671/14747730/62dc54fc-08e8-11e6-8e09-12005c61b21b.jpg)

**Comment by yy0535** [comment]
??什么意思？？

On Wed, May 25, 2016 at 1:00 PM, +1s <notifications@github.com> wrote:

> ls在干嘛
>
> <https://cloud.githubusercontent.com/assets/16496671/14747730/62dc54fc-08e8-11e6-8e09-12005c61b21b.jpg>
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/racaljk/hosts/issues/451#issuecomment-221473423>
>



-- 









panl,software Engineer

1800 Amphitheate Parkwary .Mountain View.CA 94043

**Comment by Too-Naive** [comment]
@yy0535 安心等大佬(@imcaffrey )添加域名吧

**Comment by imcaffrey** [comment]
@yy0535 哪位是群主？

**Comment by aofall** [comment]
我一副见了鬼的样子
又是edgecast cdn
110.232.178.193 iobit.com
110.232.178.193 www.iobit.com
顺便还有firebase.google.com ip可以用ggc也可以gws

**Comment by aofall** [comment]
W3Schools的那部分可以直接删掉了 不用edgecast cdn了

**Comment by Too-Naive** [comment]
@aofall 您不是ignore了吗233

**Comment by yy0535** [comment]
那iobit 软件还没有办法更新怎么办？？群主？

On Wed, May 25, 2016 at 9:03 PM, aofall <notifications@github.com> wrote:

> 我一副见了鬼的样子
> 又是edgecast cdn
> 110.232.178.193 iobit.com
> 110.232.178.193 www.iobit.com
> 顺便还有firebase.google.com ip可以用ggc也可以gws
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/racaljk/hosts/issues/451#issuecomment-221568494>
>



-- 









panl,software Engineer

1800 Amphitheate Parkwary .Mountain View.CA 94043

**Comment by imcaffrey** [comment]
谁叫群主 站出来一下

**Comment by Too-Naive** [comment]
@racaljk

**Comment by aofall** [comment]
Ignore是不收提醒啊喂

**Comment by Too-Naive** [comment]
砸了手机

**Comment by yy0535** [comment]
砸了手机










panl,software Engineer

1800 Amphitheate Parkwary .Mountain View.CA 94043
