### ISSUE TITLE
请求添加tumblr.com的域名 

### ISSUE THREAD

**Issue by mcxinyu** [racaljk/hosts#453]
求。现在真心上不了汤不热了...谢谢

**Comment by imcaffrey** [comment]
撕烤熊……这是要做什么呢………………

**Comment by Too-Naive** [comment]
汤不热233

**Comment by imcaffrey** [comment]
@mcxinyu https://github.com/racaljk/hosts/commit/6882c910702fd38252f0b2f18ebcec6d7a2dad6a#diff-85cf4e6d42a71e693fd780c8b29accddR3532

**Comment by mcxinyu** [comment]
@imcaffrey 为啥用 一键hosts 更新的不是你这个版本？

**Comment by Too-Naive** [comment]
@mcxinyu 因为并没有合并

**Comment by cnAnonymous** [comment]
tumblr.com一个帐号一个子域名，子域名没采用https链接。墙对tumblr.com不仅dns污染，还url检查，故不支持修改hosts Dnsmasq 等访问，就是修改也就是看看首页

**Comment by DaleXiao** [comment]
Try these

# Tumblr Start
66.6.42.30	tumblr.com
66.6.42.30	www.tumblr.com
66.6.42.34	mx.tumblr.com
66.6.42.34	assets.tumblr.com
66.6.41.34	px.srvcs.tumblr.com
54.192.98.136	31.media.tumblr.com
54.192.98.136	32.media.tumblr.com
209.197.3.20	33.media.tumblr.com
68.232.35.63	secure.assets.tumblr.com
54.192.86.85	media.tumblr.com
66.6.43.21	cynicallys.tumblr.com
209.197.3.20	67.media.tumblr.com
54.230.75.48	65.media.tumblr.com
192.229.237.98	66.media.tumblr.com
54.230.74.143	vt.tumblr.com
66.6.43.23	api.tumblr.com
66.6.41.34	ls.srvcs.tumblr.com
54.230.74.176	secure.static.tumblr.com
54.230.75.191	media.tumblr.com
54.182.4.222	media.tumblr.com
54.230.75.191	31.media.tumblr.com
54.230.74.176	assets.tumblr.com
54.230.213.24	assets.tumblr.com
54.192.111.4	secure.assets.tumblr.com
66.6.41.23	api.tumblr.com
54.230.74.216	vt.tumblr.com
54.230.151.138	vt.tumblr.com
52.84.189.141	vt.tumblr.com
66.6.42.34	ls.srvcs.tumblr.com
54.230.75.191	65.media.tumblr.com
54.192.111.6	secure.static.tumblr.com
54.230.213.90	secure.static.tumblr.com
54.230.74.143	secure.static.tumblr.com
# Tumblr End
