### ISSUE TITLE
Google 两步验证失效

### ISSUE THREAD

**Issue by fffb** [racaljk/hosts#454]
Gmail 已开两步验证，但登录的时候不会提示要求验证码，仅仅通过密码就可以登录。 IP 对应 220.255.2.153。不知是何原因

**Comment by imcaffrey** [comment]
Thx for informing.

**Comment by fffb** [comment]
如楼上所说，找到原因所在了。补充一点：在两步验证的界面只有取消信任的设备，而不显示设备。而且据我实验了一下，应该是浏览器 cookie 有关，和 IP 无关。因为拨号上网，IP 随时变。
当时大概是在 firefox 上点了个“记住设备”。。。。
麻烦关闭此 issue ，抱歉给大家造成困扰

**Comment by imcaffrey** [comment]
话说 自己是可以关闭自己的issue的

**Comment by K-Guan** [comment]
@imcaffrey 话说，这下服了吧？你刚才还在那儿 Thx 呢。

**Comment by imcaffrey** [comment]
@K-Guan smg= =
Thx 是感谢反馈啊，人家来开个issue然后没有人理 多尴尬= =

**Comment by K-Guan** [comment]
@imcaffrey （感觉你好像在强词夺理呀……）

**Comment by Too-Naive** [comment]
@K-Guan 就是在强词夺理啊
![](https://cloud.githubusercontent.com/assets/16496671/14747730/62dc54fc-08e8-11e6-8e09-12005c61b21b.jpg)

**Comment by imcaffrey** [comment]
你俩随意理解好了 不重要

**Comment by K-Guan** [comment]
@imcaffrey 那么什么重要呢？

**Comment by imcaffrey** [comment]
Everybody's looking for that something
One thing that makes it all complete
You'll find it in the strangest places
Places you never knew it could be
:smile:

**Comment by Too-Naive** [comment]
@imcaffrey 学弟太强了

**Comment by Too-Naive** [comment]
@K-Guan 大大能不能给我一个联系方式- - 邮箱什么的

**Comment by K-Guan** [comment]
@imcaffrey 倒是压点韵嘛，还是看我的吧：https://github.com/SO-Close-Vote-Reviewers/socvr-poetry

（好吧我承认我的诗在这里面属于最差的……还是老外厉害。）

**Comment by K-Guan** [comment]
@Too-Naive 唉？有什么事情不能在 Github 说吗？

**Comment by imcaffrey** [comment]
@K-Guan 静静学姐要约你

**Comment by K-Guan** [comment]
@imcaffrey （出去吐了一会……）

……等等，你说什么？

**Comment by imcaffrey** [comment]
兹鉴定……

**Comment by Too-Naive** [comment]
@K-Guan 不喜欢直接问

**Comment by K-Guan** [comment]
@Too-Naive 额……这个……我不还是不想挖 @imcaffrey 的墙脚嘛。

**Comment by Too-Naive** [comment]
我要泡你@K-Guan 
![](https://cloud.githubusercontent.com/assets/16496671/15640057/e121db12-2665-11e6-8a1c-8996a647eecb.jpg)

**Comment by imcaffrey** [comment]
@K-Guan wtf

**Comment by K-Guan** [comment]
@imcaffrey 世人谁人不知汝与 @Too-Naive 关系甚为密切？因而鄙人为表敬重之意，特不与 @Too-Naive 深交，特此告知。

**Comment by Too-Naive** [comment]
神经病啊 我直接问了
加密的ssh私钥上传到网上(别人可以看到)会不会有安全风险？ @K-Guan

**Comment by K-Guan** [comment]
@Too-Naive 你早说你真有问题嘛……

“加密的”？经过什么方式的加密吗？还是直接生成的文本格式？如果是通过 `ssh-keygen` 直接生成的私钥那么千万不要直接放到网上。

**Comment by K-Guan** [comment]
@Too-Naive 哦，另外如果你说的是生成时设置的密码，嗯……http://security.stackexchange.com/q/62455

**Comment by Too-Naive** [comment]
@K-Guan 也就是说不安全咯？

**Comment by imcaffrey** [comment]
应该是吧……

**Comment by K-Guan** [comment]
@Too-Naive 那个只是不会显示在你的 Gists 里（也就是说没法在 https://gist.github.com/Too-naive 看到），如果你的链接泄漏还是比较麻烦的。不过相对来说，只要保证你的 Keys gist 不会被泄漏，应该就没问题了。

**Comment by Too-Naive** [comment]
ss帐号密码233
![](https://cloud.githubusercontent.com/assets/16496671/15651196/9d3d6678-26b0-11e6-8099-f72117310462.png)

**Comment by K-Guan** [comment]
@Too-Naive 提到这个：我的 VPN 账户和密码都在 Last Pass，而安装 Chrome 时必须启动 VPN。但我每次重装系统时都忘记在本地备份下……

这就成了“想用 VPN 得先装上浏览器，想装浏览器得先用上 VPN”。幸亏家里电脑多，不然真就没治了。

**Comment by imcaffrey** [comment]
@K-Guan chrome有离线安装包

**Comment by K-Guan** [comment]
@imcaffrey 我要是能想起先把包下载好的话还能不备份下 VPN 账户么？

```bash
# install Google Chrome
cd /tmp
wget 'https://aur.archlinux.org/cgit/aur.git/snapshot/google-chrome.tar.gz'
tar xzf google-chrome.tar.gz
rm google-chrome.tar.gz

cd /tmp/google-chrome 
makepkg -sricC --noconfirm
cd /tmp 

rm -rf google-chrome
```

**Comment by Too-Naive** [comment]
所以就是说 上github要用ss
然而不用ss根本上不了github咯 @K-Guan 
![](https://cloud.githubusercontent.com/assets/16496671/14747730/62dc54fc-08e8-11e6-8e09-12005c61b21b.jpg)

**Comment by K-Guan** [comment]
@Too-Naive （我记得 gist 确实给墙了来着，不过有 hosts 问题不大。）

**Comment by Too-Naive** [comment]
噫 我觉得没有任何危害啊
![](https://cloud.githubusercontent.com/assets/16496671/14945197/49ed17c6-103e-11e6-80b8-f9f6b6dd33be.gif)

**Comment by K-Guan** [comment]
@Too-Naive 哦，那么你的问题问完了？

**Comment by Too-Naive** [comment]
en

**Comment by K-Guan** [comment]
@Too-Naive 哦，那我就 ~~不理你了~~ 先走了。

**Comment by Too-Naive** [comment]
你倒是留下邮箱啊 @K-Guan 
![](https://cloud.githubusercontent.com/assets/16496671/15676983/e82ce4cc-277a-11e6-85e4-4652a0c4f3ef.png)

**Comment by K-Guan** [comment]
@Too-Naive 唉？你到底要我的邮箱干嘛？

**Comment by imcaffrey** [comment]
**如果这都不是爱**

**Comment by K-Guan** [comment]
@Too-Naive 嗯……这我到不怕，大不了 Report for Spam 直接给 Ban 掉就是。不过我还是想知道你要去干嘛？

**Comment by Too-Naive** [comment]
有问题可以直接问大大啊 @K-Guan

**Comment by imcaffrey** [comment]
https://github.com/racaljk/hosts/issues/454#issuecomment-222871862

**Comment by K-Guan** [comment]
@Too-Naive （那怎么就不能直接用 GitHub了……）好吧，可是我不太想直接公开（防人之心不可无……比如说 @imcaffrey 这样的人）。给个 GPG 公钥，我加密下发给你。

**Comment by imcaffrey** [comment]
-----BEGIN PGP PUBLIC KEY BLOCK-----
Version: GnuPG v1

mQENBFckmYEBCAD9mJ1onSB7HuVTcZ0MQd3G/rRLFzG12uG79Gh6uYzGPDKy7Dcc
xexi5UOtLysk1/e4TyOxqV5nCCfSDzbKIOD+wj0aeSftNDcp5NwaBBdtcl6tJwGZ
b7LT2hc3GLLqVpg6qI7sqDGVmkSHgpodhf9EoI6Ob838HWrxwnjFLzz3JIEOYm+J
et9gVN9Z0q811S5fj1GoXVWVWDzqnkMm4PIChdClaaA4r5s3chsBdp4xrcaMl+E6
zhRaV5x+PHVGN+GvSTD40uzmzdurC2UVpQm/O/kokSRV/ojaTvttpzQkUWnDcRZv
FP0XuxvVR0+wWs/EfQapB1xkDHGfU9h4WSNBABEBAAG0KVNpcml1cyBDYWZmcmV5
IDxzaXJpdXMuY2FmZnJleUBnbWFpbC5jb20+iQE4BBMBAgAiBQJXJJmBAhsDBgsJ
CAcDAgYVCAIJCgsEFgIDAQIeAQIXgAAKCRB3aR0R1g1Nn9YAB/9R1bEpsCb0ojN6
kB0YPwfgU5wsHi6/Z1VsI1UJIlHWGV9lKSa7cgD2vj1O7QeOyeETbc8v3Muz2mjz
vHaH6qPErPo9a1vLVWW9NabFjMU2kC9t15Ud6uFtxx0hDEjB/my0TwLel/cWYvXj
ZySAbudn4n7XPV5Jo1lemqj1AXiqP/oGkewcKOaLB85uct2rOnprlKmaY4hmUn2z
gDBkUxD03XhH6y29q+sd6T/TIyH9tk2dmXaXVZOmlyQJ0eMsFmiO8BBRA5unioWf
iMC3ye8axVIXk8y5kBTpmfEeJKy7CyUGbkzyxz0Mtuppum/gcxDOGTjPWopXYXXe
sDYCujXNuQENBFckmYEBCAC5Gzkqwc3FLbw8MLzxo/7MAukapsR8pbWQDyX/qjP/
PzIIf9Svk0sO/5c5OOD6GfXEl82bG9dBaKYdy25ZVOF3Vda+VDXsGPaMPMzlqrlu
/fylfRozlBh+S4tgqLJ04uGSNNDntOFUovj1j2fdS1XnohFwOeKGQBkhUs8gzlzZ
0Z+Q5ysDkQrDrQ3pLKYefqM5n9k0UNABlpSCZGLuE+XtyT8EIvONWk91LFciAFi3
CniRx82KOsjHO+JmzgU6PL7cZxAYTtCY1M2u2XjaPC/Nxe6Jsex75Jtda/0MIYF6
HrSVBag4VVf4UMaqW2iI8TxiKUVnZC3DWsc66WxS/BDtABEBAAGJAR8EGAECAAkF
AlckmYECGwwACgkQd2kdEdYNTZ9m1ggA2SB9E/j+xnCxoFhspi20KoKiPj1zde5/
y/sLPuCwELJ8OBmwaZ8ka6LevBg1zXlBBWm+8owVJCfrNN2gEPMvWTOKBHytdh6z
vJo4WUkzBrUAqv9kgIRq+WpRHVjVKgj6auXgYiadHXgcIRULtOIktVEO5N94AfgY
FtIswTXryPAfpxdgOr38yVCYkLZAJZ8P9qOk0qKFttY3J60JxniedWJGIeLzXv06
kUStJeItPaZVDwXJQpKM+Sil2pBTgmwo4uz32qA09TCJYffxZtsbEYHbGkkp45Pa
ajSrBOnemSg/NIBzc82z/6sYy6dFI7Ujz2UejijPZl/K3+wORE3b4g==
=lGqS
-----END PGP PUBLIC KEY BLOCK-----
楼上好人一生平安

**Comment by Too-Naive** [comment]
没有GPG
sometimes.naive@hotmail.com 你直接发给我一封邮件不就好了 @K-Guan

**Comment by K-Guan** [comment]
@imcaffrey 去去去，一边站着去。
@Too-Naive Done.

**Comment by K-Guan** [comment]
顺便热烈庆祝 @Too-Naive 已经成功将 @imcaffrey 狠狠的甩在了后面，估计这辈子是追不上了：

![screenshot-github com 2016-06-01 23-14-27](https://cloud.githubusercontent.com/assets/13862535/15714891/fee4aab8-284e-11e6-8d50-c09dff80e69e.png)

**Comment by Too-Naive** [comment]
@K-Guan 别D我qwq(~~andy抢我人头~~
