### ISSUE TITLE
请求添加blogspot.com域名.

### ISSUE THREAD

**Issue by wsdjeg** [racaljk/hosts#459]
你好,感谢分享这一项目,目前部分博客位于`blogspot.com` 域名下面,无法打开,请帮忙添加hosts信息,谢谢!

**Comment by imcaffrey** [comment]
`https://`

https://github.com/racaljk/hosts/blob/a3115fa36ddbdb197f447af948c441525da4b8ba/hosts#L545

**Comment by wsdjeg** [comment]
@imcaffrey 不好意思,不过不知道为什么,我无法访问这个网站.

**Comment by wsdjeg** [comment]
不好意思,我的hosts fork的有点问题, 已 修复
