### ISSUE TITLE
分享一个OpenWRT路由器的自动更新hosts方法，无需脚本

### ISSUE THREAD

**Issue by forver8023** [racaljk/hosts#46]
01 06 * * * wget -q https://raw.githubusercontent.com/racaljk/hosts/master/hosts -O /etc/hosts --no-check-certificate ; /etc/init.d/dnsmasq restart

对于openwrt用户来说直接复制到计划任务页就可以，每天早上6：01可以更新一次hosts，不用下载脚本。

同时感谢作者的辛勤更新！连google比我爬梯子还快

另外问一个问题，google play的下载速度改了hosts之后只有8kb/s，翻墙了似乎也是这速度，请问在hosts里关于play的下载是哪几条记录？

**Comment by racaljk** [comment]
感谢提供，已经添加至[wiki](https://github.com/racaljk/hosts/wiki/OpenWRT%E8%B7%AF%E7%94%B1%E5%99%A8%E5%A6%82%E4%BD%95%E8%87%AA%E5%8A%A8%E6%9B%B4%E6%96%B0hosts%3F)

google play的相关记录是*.c.android.clients.google.com

**Comment by daniuer** [comment]
唉，我添加后无法自动更新。

**Comment by CHN008** [comment]
这个方法不错 DD-WRT也可以用这个方法吧?

**Comment by zhout26** [comment]
能不能改一个http的，很多openwrt没加with-ssl

**Comment by Too-Naive** [comment]
包括镜像在内 全站都用的是ssl吧

**Comment by cscq** [comment]
好用，不过要升级 WGET 否则不支持，还需要安装证书

**Comment by bobbyliujb** [comment]
遇到openssl错误的朋友可能需要升级一下喔
opkg update
opkg install wget

**Comment by duc233** [comment]
00 06 * * * root curl -k https://raw.githubusercontent.com/racaljk/hosts/master/hosts -o /etc/hosts && stopservice cron && startservice cron
我用的是DDWRT的，添加到Cron里就行。
