### ISSUE TITLE
www.w3schools.com 请求超时

### ISSUE THREAD

**Issue by twocold0451** [racaljk/hosts#460]
只有我一人是这样吗？

**Comment by Too-Naive** [comment]
您可以把hosts文件的末尾处(或直接搜索w3schools)条目中的`#`删除
我们会继续跟踪w3schools的情况
(其实我这里也没法访问)

**Comment by DaleXiao** [comment]
Try this:
72.21.91.8	www.w3schools.com
72.21.91.8	w3schools.com

**Comment by Too-Naive** [comment]
hosts文件中已经有现成的但是把他注释掉了

**Comment by imcaffrey** [comment]
报告：我这里可以啊

**Comment by Too-Naive** [comment]
![](https://cloud.githubusercontent.com/assets/16496671/15741855/24bb06c0-28ee-11e6-948b-66d3322a80bd.png)

**Comment by aofall** [comment]
@DaleXiao 尽量用亚洲地区的DNS而不是美国的
例如台湾HiNet的168.95.1.1

--------

W3Schools在中国大陆的解析切到一组美国服务器上了而不用Edgecast cdn了，但DNS污染的情况依旧存在 

66.29.212.100 w3schools.com
66.29.212.100 www.w3schools.com

还打不开说明国际出口又炸锅了

**Comment by aofall** [comment]
打错ip了 66.29.212.100 
Sometimes naive的帮我改一下 顺便删掉这条

**Comment by Too-Naive** [comment]
没有错啊..

**Comment by aofall** [comment]
٩(๑`^´๑)۶看来是中午写考卷写傻了
66.29.212.110

**Comment by Too-Naive** [comment]
![](https://cloud.githubusercontent.com/assets/16496671/14873063/cd15c35e-0d24-11e6-81ec-9f97b2c120da.JPG)
