### ISSUE TITLE
ChromeBook上用crouton安装Ubantu失败

### ISSUE THREAD

**Issue by CHN008** [racaljk/hosts#461]
**请添加在ChromeBook上用crouton安装Ubantu时要使用的某些IP地址:74.125.204.82 或者74.125.23.82**

在ChromeBook上用crouton 安装Ubantu时每次到了最后一步由于这个地址链接(74.125.204.82:443)超时导致安装失败,看它提示是连接不上这个地址的某一部分? :https://chromium.googlesource.com/

![ip-1](https://cloud.githubusercontent.com/assets/16646697/15767559/949026dc-297b-11e6-9f7a-4e1126d1d20b.jpg)

![ip cs](https://cloud.githubusercontent.com/assets/16646697/15767569/a39284ae-297b-11e6-8d94-55ef8ee9652c.jpg)

**Comment by LGA1150** [comment]
`220.255.2.153	chromium.googlesource.com` 已经在hosts中了，是不是没生效？

**Comment by aofall** [comment]
@LGA1150 确定不是软件不认hosts？或者SNI的问题？
看问题描述像是不认hosts直接用DNS解析的结果

**Comment by K-Guan** [comment]
其实我还是觉得最近两天别急着翻，我的 VPN 就全线挂掉（几十个服务器呀……这 GFW 用的是什么新科技？能连接上却不能收到回应。）

**Comment by Too-Naive** [comment]
好像今天是特殊的节日噢... vpn不是可以检测报头吗

**Comment by redapple0204** [comment]
@Too-Naive 一张直白的图片
![default](https://cloud.githubusercontent.com/assets/16254644/15797417/07a098c2-2a4a-11e6-9bfd-858fe32e2a43.PNG)

**Comment by Too-Naive** [comment]
我用ss啊- - @redapple0204

**Comment by redapple0204** [comment]
@Too-Naive ss没挂？

**Comment by Too-Naive** [comment]
ss 理论上不可能被封啊- - @redapple0204

**Comment by redapple0204** [comment]
@Too-Naive 事实上我从上次的就挂了。。。。

**Comment by CHN008** [comment]
@LGA1150  是的换了Hosts,Google网站可以打开 直接在浏览器打开https://chromium.googlesource.com/也是没问题的,但是就是安装时它自己好像不用这个Hosts解析,所以没办法.太奇怪了.

**Comment by CHN008** [comment]
@aofall  我比赞同你的说法,不知道后续有没有好的解决办法,而且这个资源的IP地址是变化的.

**Comment by Too-Naive** [comment]
@redapple0204 不是用很久所以不能判断--

**Comment by Too-Naive** [comment]
@CHN008 您有多台电脑吧。。 直接设置网络代理可以？

**Comment by K-Guan** [comment]
@Too-Naive 我怎么知道……还是等就是咯，过了这几天估计就行了。

**Comment by Too-Naive** [comment]
有检测特征。。 那篇fqrouter的文章被墙了 @K-Guan

**Comment by Too-Naive** [comment]
![](https://cloud.githubusercontent.com/assets/16496671/15800187/19a7659a-2aa5-11e6-9d96-abe7c455084a.png)
依旧健在啊
[你要的文章](https://github.com/YoungIsSimple/Object-Release/blob/251/%E7%BF%BB%E5%A2%99%E8%B7%AF%E7%94%B1%E5%99%A8%E7%9A%84%E5%8E%9F%E7%90%86%E4%B8%8E%E5%AE%9E%E7%8E%B0.zip?raw=true)

**Comment by BROBIRD** [comment]
@Too-Naive #(滑稽)

**Comment by aofall** [comment]
@CHN008 ip变化不要紧 关键是得让他可以走指定的ip 我估计你得在局域网内自建DNS服务才可以解决这个问题
你可以试试DNSmasq

**Comment by CHN008** [comment]
谢谢上面几位热心的建议,我用其它电脑设置了局域网代理一样成功不了(Lantern,XXNET,psiphon3 都试过了).

其实还有一个SoftEther VPN肯定是可以的,但是很难找到几个可以连上的服务器,速度也不稳定,所以不折腾了.

后面用U盘启动镜像把Ubuntu 14.04 LTS安装在高速SD卡上,可以用了,但是不太流畅.

**Comment by andytimes** [comment]
@CHN008  刚刚看了 crouton 的[Git 仓库](https://github.com/dnschneid/crouton)，是在 ChromeBook 上实现一个 chroot 环境（看了截图也是如此），所以不读系统配置，只读取 chroot 环境里面的东西，可以尝试把 ChromeBook 系统的 hosts (应该是在 /etc/hosts) 复制到 `chronos@localhost` 这个环境对应的 /etc/ 目录中。

当然我不是很确定这个 chroot 环境是否支持读取 hosts，但我很确定这个环境可支持代理（[见此链接](https://github.com/dnschneid/crouton/blob/master/targets/core)），
你挂代理，然后把代理地址设置成环境变量就行了。

export http_proxy=http://xxxx:xx
export https_proxy=https://xxx:xx

XX-NET 的代理服务器好像默认是 127.0.0.1:8085，可以自测。

**Comment by CHN008** [comment]
@andytimes  谢谢你的解答,我去试试. 不过看起来有点麻烦,呵呵.

**Comment by aofall** [comment]
这个issue可以关闭了
