### ISSUE TITLE
请求增加smartdnsproxy.com

### ISSUE THREAD

**Issue by mixool** [racaljk/hosts#463]
103.28.248.96 www.smartdnsproxy.com
184.72.50.35 support.smartdnsproxy.com
移动网络无法直接访问网址。

**Comment by Too-Naive** [comment]
谢谢反馈

**Comment by Too-Naive** [comment]
@imcaffrey 老司机啊，`git commit --author=<author>` 怎么用啊

**Comment by imcaffrey** [comment]
git commit --author "sc imcaffrey@sc.sc"

**Comment by Too-Naive** [comment]
如果不知道email呢 @imcaffrey

**Comment by imcaffrey** [comment]
@Too-Naive 看git log可以知道email

**Comment by Too-Naive** [comment]
@imcaffrey 没提交过的哪来的email
