### ISSUE TITLE
已经更改了hosts，突然打不开facebook，ping了以后ip是74.117.178.97，之前还可以打开的

### ISSUE THREAD

**Issue by winloongLam** [racaljk/hosts#464]
Pinging facebook.com [74.117.178.97] with 32 bytes of data:                                                             Request timed out.
Request timed out.
Request timed out.

**Comment by imcaffrey** [comment]
等几天

**Comment by winloongLam** [comment]
可以用了。。好像是不小心把hosts文件的权限改了，改回来了之后就可以顺利上网了
