### ISSUE TITLE
windows bat 执行报错

### ISSUE THREAD

**Issue by dengdairiluo** [racaljk/hosts#465]
downloadhosts.vbs  缺少对象“sGet” 代码800A01A8

**Comment by Too-Naive** [comment]
错误无法重现 请告知操作系统

**Comment by dengdairiluo** [comment]
操作系统 win10 x64 企业版 
操作： 双击弹出cmd窗口，显示 正在进行UAC提权，弹出提权窗口。 选“是” 弹出新的cmd窗口，显示文字：“日志文件： C:\Users\******\AppData\Local\Temp\HostsGeter_log.txt” 开始从 GitHub 中下载 hosts 文件...
======================
错误：hosts 文件下载失败.
已打开日志文件
按任意键关闭

日志文件：
==========[2016/06/04 周六 23:53:27.68]========== 
开始从 GitHub 中下载 hosts 文件... 
删除文件 - C:\Users\JiangLu\AppData\Local\Temp\downloadhosts.vbs
错误：hosts 文件下载失败.

**Comment by Too-Naive** [comment]
代码不是我编写的 等有关方面修改后会反馈给您的
您可以试试[Hosts tool for windows](https://github.com/HostsTools/Windows)

**Comment by K-Guan** [comment]
cc @redapple0204

**Comment by redapple0204** [comment]
@dengdairiluo 你确定你的windows不是精简版或者文件缺失，按理说应该是自带sget的啊。。。

**Comment by dengdairiluo** [comment]
@redapple0204 win10企业版 下载网站 msdn i tell you

**Comment by Too-Naive** [comment]
明天我来复审代码 别慌
![](https://cloud.githubusercontent.com/assets/16496671/14747730/62dc54fc-08e8-11e6-8e09-12005c61b21b.jpg)

**Comment by redapple0204** [comment]
@Too-Naive 好像bat还是有很多问题的

**Comment by redapple0204** [comment]
@dengdairiluo 奇怪了

**Comment by Too-Naive** [comment]
垃圾bat 用exe保平安 人在做天在看 没人维护留隐患
![](https://cloud.githubusercontent.com/assets/16496671/14945197/49ed17c6-103e-11e6-80b8-f9f6b6dd33be.gif)

**Comment by redapple0204** [comment]
@Too-Naive 你这顺口溜接得好

**Comment by Too-Naive** [comment]
测试结果正常:
![](https://cloud.githubusercontent.com/assets/16496671/16544332/c4ef2884-4134-11e6-8d5c-327907c2561c.png)
操作系统版本:
![](https://cloud.githubusercontent.com/assets/16496671/16544318/23978e0e-4134-11e6-8815-a0feceb9a457.png)

感谢 @0xMeansHexadecimal 提供测试环境w

另:
如果还有其他问题 请尽可能使用win下的可执行文件版本 参见:[Hosts Tools](https://github.com/HostsTools)

**Comment by imcaffrey** [comment]
Win7 SP1 不正常
![](http://r6.loli.io/mENz2q.png)

**Comment by Too-Naive** [comment]
utf-8?

**Comment by YiliaLee** [comment]
==========[2016-08-18 16:36:22.30]========== 
开始从 GitHub 中下载 hosts 文件... 
错误：hosts 文件下载失败. 
 
==========[2016-08-18 16:37:40.48]========== 
错误：downloadhosts.vbs 文件创建/写入失败. 


downloadhosts.vbs
这个文件是在哪一个路径下创建的？

**Comment by Too-Naive** [comment]
%temp%
请使用exe版本的[hosts工具](https://github.com/HostsTools/Windows)

**Comment by YiliaLee** [comment]
@Too-Naive 已经搞定了，发现是360杀毒软件的锅，杀毒软件直接查杀了那个文件。

另外，日志提示的文件路径如果能显示成完整路径，会更好一些

**Comment by Too-Naive** [comment]
为啥甩锅都甩我头上啊...明明不是我写的
