### ISSUE TITLE
windows bat已经不支持xp

### ISSUE THREAD

**Issue by redapple0204** [racaljk/hosts#466]
因为xp ie8被github停止支持，所以bat将无法下载hosts文件

**Comment by Too-Naive** [comment]
invalid?
![](https://cloud.githubusercontent.com/assets/16496671/15803308/f87749c0-2b09-11e6-93e5-f2cb360d9341.png)

**Comment by redapple0204** [comment]
@Too-Naive 

>>>C:\Documents and Settings\Administrator\桌面>1.bat
'C:\Documents' 不是内部或外部命令，也不是可运行的程序
或批处理文件。

C:\Documents and Settings\Administrator\桌面>

**Comment by Too-Naive** [comment]
空格的问题啊。。

**Comment by redapple0204** [comment]
@Too-Naive 在根目录运行也是一样。。。

**Comment by Too-Naive** [comment]
...可是我不能复现啊。。 我在桌面上运行的

**Comment by redapple0204** [comment]
@Too-Naive 那就很奇怪了，到底是我系统问题还是bat问题

**Comment by Too-Naive** [comment]
你把`@echo off`去掉
文件头留一行空行

**Comment by redapple0204** [comment]
@Too-Naive 那玩意就是隐藏操作的
不过
去掉以后执行出现这个问题
>>>
C:\>1.bat

C:\>锘?
'锘?' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
C:\>if defined converted goto :converted
C:\>set ConverterPath=C:\Documents and Settings\Administrator\Local Settings\T
p\HostsGeter_CodeConverter.vbs
C:\>set ConverterOutput=C:\Documents and Settings\Administrator\Local Settings
emp\HostsGeter_GBK.bat
C:\>echo inputpath="1.bat"  and Settings\Administrator\Local Settings\Temp\Hos
Geter_CodeConverter.vbs 1>C:\Documents
C:\>echo outputpath="C:\Documents and Settings\Administrator\Local Settings\Te
\HostsGeter_GBK.bat"  and Settings\Administrator\Local Settings\Temp\HostsGete
CodeConverter.vbs 1>>C:\Documents
C:\>echo set stm2=createobject("ADODB.Stream")  and Settings\Administrator\Loc
 Settings\Temp\HostsGeter_CodeConverter.vbs 1>>C:\Documents
C:\>echo stm2.Charset ="utf-8"  and Settings\Administrator\Local Settings\Temp
ostsGeter_CodeConverter.vbs 1>>C:\Documents
C:\>echo stm2.Open  and Settings\Administrator\Local Settings\Temp\HostsGeter_
deConverter.vbs 1>>C:\Documents
C:\>echo stm2.LoadFromFile inputpath  and Settings\Administrator\Local Setting
Temp\HostsGeter_CodeConverter.vbs 1>>C:\Documents
C:\>echo readfile = stm2.ReadText  and Settings\Administrator\Local Settings\T
p\HostsGeter_CodeConverter.vbs 1>>C:\Documents
C:\>echo stm2.Close  and Settings\Administrator\Local Settings\Temp\HostsGeter
odeConverter.vbs 1>>C:\Documents
C:\>echo Set Stm1 =CreateObject("ADODB.Stream")  and Settings\Administrator\Lo
l Settings\Temp\HostsGeter_CodeConverter.vbs 1>>C:\Documents
C:\>echo Stm1.Type = 2  and Settings\Administrator\Local Settings\Temp\HostsGe
r_CodeConverter.vbs 1>>C:\Documents
C:\>echo Stm1.Open  and Settings\Administrator\Local Settings\Temp\HostsGeter_
deConverter.vbs 1>>C:\Documents
C:\>echo Stm1.Charset ="GBK"  and Settings\Administrator\Local Settings\Temp\H
tsGeter_CodeConverter.vbs 1>>C:\Documents
C:\>echo Stm1.Position = Stm1.Size  and Settings\Administrator\Local Settings\
mp\HostsGeter_CodeConverter.vbs 1>>C:\Documents
C:\>echo Stm1.WriteText "set converted=y" & vbcrlf  and Settings\Administrator
ocal Settings\Temp\HostsGeter_CodeConverter.vbs 1>>C:\Documents
C:\>echo Stm1.WriteText readfile  and Settings\Administrator\Local Settings\Te
\HostsGeter_CodeConverter.vbs 1>>C:\Documents
C:\>echo Stm1.SaveToFile outputpath,2  and Settings\Administrator\Local Settin
\Temp\HostsGeter_CodeConverter.vbs 1>>C:\Documents
C:\>echo Stm1.Close  and Settings\Administrator\Local Settings\Temp\HostsGeter
odeConverter.vbs 1>>C:\Documents
C:\>C:\Documents and Settings\Administrator\Local Settings\Temp\HostsGeter_Cod
onverter.vbs   && C:\Documents and Settings\Administrator\Local Settings\Temp\
stsGeter_GBK.bat
'C:\Documents' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
C:\>goto :eof
C:\>

**Comment by Too-Naive** [comment]
就是没有引号咯…… 目录有空格的话必须要有引号
您的xp sp什么版本的？

**Comment by redapple0204** [comment]
@Too-Naive 我试试手动把vbs改成存放到根目录下
我的xp是sp3

**Comment by Too-Naive** [comment]
觉得是%tmp%的锅

**Comment by redapple0204** [comment]
@Too-Naive 肯定是，我用了我以前制作的版本（不是放在temp里）就可以
感觉这个有可能会成为一个小小的bug

**Comment by Too-Naive** [comment]
等我高考完看看如何解决一下…… 不是很懂`echo`

**Comment by redapple0204** [comment]
@Too-Naive 这应该是偶发事件吧，毕竟重装了上百次系统只有一次是这样的

**Comment by Too-Naive** [comment]
您可以用[Hosts tool for Windows](https://github.com/HostsTools/Windows)

**Comment by redapple0204** [comment]
@Too-Naive 嗯，我现在只好用这个了

**Comment by Too-Naive** [comment]
话不多说 只求一个star

**Comment by redapple0204** [comment]
@Too-Naive star是肯定的！

**Comment by K-Guan** [comment]
> 'C:\Documents' 不是内部或外部命令，也不是可运行的程序或批处理文件。

你的程序正在尝试运行 `C:\Documents`，和 IE 有半毛钱的关系？
（话说……有空学学程序的 debugging ……）

**Comment by redapple0204** [comment]
@K-Guan 1.标题打错了，其实我想说的是这个问题
![2cd2fb43ad4bd113ba7b924f5dafa40f4afb05e4](https://cloud.githubusercontent.com/assets/16254644/15854460/859bfdae-2cdc-11e6-92bd-d933a57cc8bf.jpg)
xp的ie8貌似已经不支持github的协议了（压根就打不开），所以下载也失败了。
但是刚好有遇到了一楼的这个问题，因为一楼的问题先困扰我的使用，所以就先提问喽

**Comment by K-Guan** [comment]
好吧，那我就不知道了。

**Comment by Too-Naive** [comment]
没有这个vbs文件

**Comment by redapple0204** [comment]
@Too-Naive vbs是有的（我看过了），但是因为协议不支持，所以自然无法下载。

**Comment by Too-Naive** [comment]
奇怪阿…为什么我没有呢

**Comment by racaljk** [comment]
其实按照我个人的看法,XP基本不在问题考虑范围内..
