### ISSUE TITLE
祝高考考生一切顺利！

### ISSUE THREAD

**Issue by imcaffrey** [racaljk/hosts#467]
心想事成

**Comment by Too-Naive** [comment]
invalid

**Comment by lautis0503** [comment]
这应该改readme.md吧

**Comment by Too-Naive** [comment]
刷1000条issue即可

**Comment by K-Guan** [comment]
嗯，这个 Label 用的好。

**Comment by K-Guan** [comment]
@lautis0503 同意，加在：

> English version
>  [here]
> 使用本项目之前，请先阅读此 README 及下方的许可协议

**Comment by Too-Naive** [comment]
手调label颜色 @K-Guan 
![](https://cloud.githubusercontent.com/assets/16496671/14747730/62dc54fc-08e8-11e6-8e09-12005c61b21b.jpg)

**Comment by K-Guan** [comment]
@Too-Naive （这些我也懂）
