### ISSUE TITLE
虚拟机里用这个hosts替换了，还是不能访问google

### ISSUE THREAD

**Issue by clq123clq** [racaljk/hosts#469]
虚拟机里用这个hosts替换了，还是不能访问google，要怎么办？

**Comment by clq123clq** [comment]
解决了，在手机里的hosts，末尾需要有个\n,直接用这个hosts替换不行，需要在Notepad++里替换下换行符。详见我的博客：http://blog.csdn.net/chenliqiang12345678/article/details/51604975

**Comment by clq123clq** [comment]
真机里的也需要这样操作

**Comment by imcaffrey** [comment]
讲道理 我修复过换行符啊？
