### ISSUE TITLE
It seems the Google IP '220.255.2.153' is down.

### ISSUE THREAD

**Issue by DaleXiao** [racaljk/hosts#470]
As captioned, 220.255.2.153 doesn't work.

Tested 64.233.162.84, this one works well so far.

**Comment by Too-Naive** [comment]
可以复现 我这里已经上不去了

**Comment by aofall** [comment]
https://www.v2ex.com/t/284529
因为电信出国线路炸了

**Comment by CHN008** [comment]
我这里两小时前恢复了

**Comment by DaleXiao** [comment]
220.255.2.153 is back to normal now.
