### ISSUE TITLE
chrome打开新的标签页自动跳转

### ISSUE THREAD

**Issue by iTaster** [racaljk/hosts#474]
http://www.google.com.hk/url?sa=p&hl=zh-CN&pref=hkredirect&pval=yes&q=http://www.google.com.hk/_/chrome/newtab%3Fespv%3D2%26ie%3DUTF-8%26gws_rd%3Dcr&ust=1465627996586020&usg=AFQjCNHsoXs_T_churlqH5oFaR9srf-rAg

**Comment by iTaster** [comment]
这是神马鬼┏┛墓┗┓...(((m -__-)m

**Comment by redapple0204** [comment]
我也是...

**Comment by imcaffrey** [comment]
自己过一会就好了……我也不知道为啥

**Comment by Too-Naive** [comment]
很正常 我跟踪过 挂上ss 新安装的浏览器如果没有google账号会自动跳转到Google账户登陆 而也只有那个页面才有链接 "不了谢谢"

**Comment by andytimes** [comment]
@iTaster https://github.com/racaljk/hosts/issues/387#issuecomment-212439981

**Comment by iTaster** [comment]
@andytimes 谢谢，等下试试😶

**Comment by Too-Naive** [comment]
dev和正式版都会跳

**Comment by TinyZzh** [comment]
关键是新建标签都这么跳，浏览器都没法好好用啦。。能解决不？

**Comment by TinyZzh** [comment]
[#387](https://github.com/racaljk/hosts/issues/387#issuecomment-212439981)  问题解决。多谢

**Comment by iTaster** [comment]
在搜索框输入 chrome://net-internals/#hsts
在 Input a domain name to add it to the HSTS set: 这一行下面的 Domain: [ ]
输入 www.google.com.hk 点 Add

每次都要跳到#387才能看到解决方法，干脆黏贴过来啦！

**Comment by Too-Naive** [comment]
背下地址不就完事了。。 @iTaster

**Comment by ansiqu** [comment]
请问哈是怎么跟踪的，想学习哈 @Too-Naive
