### ISSUE TITLE
请求添加github的hosts

### ISSUE THREAD

**Issue by redapple0204** [racaljk/hosts#475]
表示我这里只能通过挂vpn上github，好麻烦！能不能添加个github的hosts

**Comment by imcaffrey** [comment]
https://github.com/racaljk/hosts/issues/286#issuecomment-197342611

**Comment by redapple0204** [comment]
@imcaffrey 这个无效啊

**Comment by Too-Naive** [comment]
192.30.252.131

**Comment by andytimes** [comment]
192.30.252.128-131 好像都可以

**Comment by LGA1150** [comment]
https

**Comment by K-Guan** [comment]
#316, Again?

**Comment by redapple0204** [comment]
@K-Guan 不行了
@LGA1150 已经用了
@Too-Naive 似乎。。。不行

**Comment by Too-Naive** [comment]
那你还是老老实实挂vpn吧

**Comment by redapple0204** [comment]
@Too-Naive 嗯。。也只能这样了
