### ISSUE TITLE
谷歌api管理器里面的credential(凭证)是否需要添加hosts？

### ISSUE THREAD

**Issue by tingbob** [racaljk/hosts#477]
https://console.developers.google.com/apis/credentials?project=******
始终打不开，不知是不是需要添加？

**Comment by Too-Naive** [comment]
https://github.com/racaljk/hosts/blob/master/hosts#L630

**Comment by tingbob** [comment]
虽然访问里面的credential仍然刷不出来。不过也非常感谢。

**Comment by Too-Naive** [comment]
F12 看看缺了什么域名咯

**Comment by tingbob** [comment]
https://console.developers.google.com/apis/credentials?project=*
https://console.developers.google.com/apis/credentials/consent?project=*
https://console.developers.google.com/iam-admin/iam/project?project=*
https://console.developers.google.com/iam-admin/serviceaccounts/project?project=*
https://console.developers.google.com/iam-admin/labels/project?project=*
https://console.developers.google.com/iam-admin/quotas?project=*
星号代表一个name

**Comment by Too-Naive** [comment]
这些是从F12console中拿到的吗?
