### ISSUE TITLE
Facebook部分域名所对应的IP错误

### ISSUE THREAD

**Issue by Hongnanjing** [racaljk/hosts#479]
facebook错误太多，像 fb.me 对应的IP都是错误的，手机端messenger没法用语音和视频

**Comment by andytimes** [comment]
错误可以提交 Pull Request 和 Issue 报正确 IP
这里主要是 google hosts，其他没大问题都不影响。

**Comment by imcaffrey** [comment]
至少发现了问题还是好的呐

**Comment by andytimes** [comment]
@imcaffrey 然而找不到 IP 😢

**Comment by Too-Naive** [comment]
![](https://cloud.githubusercontent.com/assets/16496671/14747730/62dc54fc-08e8-11e6-8e09-12005c61b21b.jpg)
你们不能找不到ip就钦定其他问题都不影响

**Comment by andytimes** [comment]
@imcaffrey @Too-Naive 
https://github.com/racaljk/hosts/issues/207#issuecomment-180947944

总之 Facebook 的问题看看有没有人能解决，不然还是挂代理访问吧。

**Comment by Hongnanjing** [comment]
用了第三方hosts Facebook一切正常

**Comment by Too-Naive** [comment]
which 第三方？ 我们恳请您如果得到了好用的hosts的话 务必提交一个pull request来帮助我们解决问题

**Comment by Hongnanjing** [comment]
地址https://github.com/cnAnonymous/hosts

**Comment by imcaffrey** [comment]
`小众hosts，请低调使用`

**Comment by Too-Naive** [comment]
`小众hosts，请低调使用`

**Comment by jetbe** [comment]
https://github.com/cnAnonymous/hosts 挂了，https://github.com/racaljk/hosts更新比较慢，还有其他选择吗？谢谢！
