### ISSUE TITLE
Instagram可以打开，无法加载图片

### ISSUE THREAD

**Issue by eianslight** [racaljk/hosts#481]
采用https在网页端可以打开网站，但是不显示任何网页元素 （chrome ， IE  ， Edge 均测试过）

手机端android app ， 可以打开应用刷新动态，但是不显示图片和视频

今天上午发现的，不知道具体什么时候，之前一直都能用 

---------------------------

**Comment by Too-Naive** [comment]
#291 试试其他的域名

**Comment by eianslight** [comment]
instagr.am   使用这个域名也不行，会跳转到instagram.com下面，然后页面全白

我理解的您说的域名是同一个网站的不同网址，不知是否正确

**Comment by DaleXiao** [comment]
try this, i partially fixed some, works alright on browser and app.

# Instagram
52.20.140.226	instagram.com
23.61.203.218	www.instagram.com
23.61.203.218	i.instagram.com
31.13.70.52	api.instagram.com
23.61.203.218	help.instagram.com
23.61.203.218	blog.instagram.com
74.117.178.40	graph.instagram.com
23.61.203.218	logger.instagram.com
23.61.203.218	badges.instagram.com
31.13.95.48	platform.instagram.com
23.61.203.218	maps.instagram.com
23.61.203.218	scontent.cdninstagram.com
23.61.203.218	scontent-a.cdninstagram.com
23.61.203.218	scontent-b.cdninstagram.com
184.51.15.142	igcdn-photos-a-a.akamaihd.net
184.51.15.142	igcdn-photos-b-a.akamaihd.net
184.51.15.142	igcdn-photos-c-a.akamaihd.net
184.51.15.142	igcdn-photos-d-a.akamaihd.net
184.51.15.142	igcdn-photos-e-a.akamaihd.net
184.51.15.142	igcdn-photos-f-a.akamaihd.net
184.51.15.142	igcdn-photos-g-a.akamaihd.net
184.51.15.142	igcdn-photos-h-a.akamaihd.net
184.51.15.142	igcdn-videos-a-0-a.akamaihd.net
184.51.15.142	igcdn-videos-a-1-a.akamaihd.net
184.51.15.142	igcdn-videos-a-2-a.akamaihd.net
184.51.15.142	igcdn-videos-a-3-a.akamaihd.net
184.51.15.142	igcdn-videos-a-4-a.akamaihd.net
184.51.15.142	igcdn-videos-a-5-a.akamaihd.net
184.51.15.142	igcdn-videos-a-6-a.akamaihd.net
184.51.15.142	igcdn-videos-a-7-a.akamaihd.net
184.51.15.142	igcdn-videos-a-8-a.akamaihd.net
184.51.15.142	igcdn-videos-a-9-a.akamaihd.net
184.51.15.142	igcdn-videos-a-10-a.akamaihd.net
184.51.15.142	igcdn-videos-a-11-a.akamaihd.net
184.51.15.142	igcdn-videos-a-12-a.akamaihd.net
184.51.15.142	igcdn-videos-a-13-a.akamaihd.net
184.51.15.142	igcdn-videos-a-14-a.akamaihd.net
184.51.15.142	igcdn-videos-a-15-a.akamaihd.net
184.51.15.142	igcdn-videos-a-16-a.akamaihd.net
184.51.15.142	igcdn-videos-a-17-a.akamaihd.net
184.51.15.142	igcdn-videos-a-18-a.akamaihd.net
184.51.15.142	igcdn-videos-a-19-a.akamaihd.net
184.51.15.142	igcdn-videos-b-0-a.akamaihd.net
184.51.15.142	igcdn-videos-b-1-a.akamaihd.net
184.51.15.142	igcdn-videos-b-2-a.akamaihd.net
184.51.15.142	igcdn-videos-b-3-a.akamaihd.net
184.51.15.142	igcdn-videos-b-4-a.akamaihd.net
184.51.15.142	igcdn-videos-b-5-a.akamaihd.net
184.51.15.142	igcdn-videos-b-6-a.akamaihd.net
184.51.15.142	igcdn-videos-b-7-a.akamaihd.net
184.51.15.142	igcdn-videos-b-8-a.akamaihd.net
184.51.15.142	igcdn-videos-b-9-a.akamaihd.net
184.51.15.142	igcdn-videos-b-10-a.akamaihd.net
184.51.15.142	igcdn-videos-b-11-a.akamaihd.net
184.51.15.142	igcdn-videos-b-12-a.akamaihd.net
184.51.15.142	igcdn-videos-b-13-a.akamaihd.net
184.51.15.142	igcdn-videos-b-14-a.akamaihd.net
184.51.15.142	igcdn-videos-b-15-a.akamaihd.net
184.51.15.142	igcdn-videos-b-16-a.akamaihd.net
184.51.15.142	igcdn-videos-b-17-a.akamaihd.net
184.51.15.142	igcdn-videos-b-18-a.akamaihd.net
184.51.15.142	igcdn-videos-b-19-a.akamaihd.net
184.51.15.142	igcdn-videos-c-0-a.akamaihd.net
184.51.15.142	igcdn-videos-c-1-a.akamaihd.net
184.51.15.142	igcdn-videos-c-2-a.akamaihd.net
184.51.15.142	igcdn-videos-c-3-a.akamaihd.net
184.51.15.142	igcdn-videos-c-4-a.akamaihd.net
184.51.15.142	igcdn-videos-c-5-a.akamaihd.net
184.51.15.142	igcdn-videos-c-6-a.akamaihd.net
184.51.15.142	igcdn-videos-c-7-a.akamaihd.net
184.51.15.142	igcdn-videos-c-8-a.akamaihd.net
184.51.15.142	igcdn-videos-c-9-a.akamaihd.net
184.51.15.142	igcdn-videos-c-10-a.akamaihd.net
184.51.15.142	igcdn-videos-c-11-a.akamaihd.net
184.51.15.142	igcdn-videos-c-12-a.akamaihd.net
184.51.15.142	igcdn-videos-c-13-a.akamaihd.net
184.51.15.142	igcdn-videos-c-14-a.akamaihd.net
184.51.15.142	igcdn-videos-c-15-a.akamaihd.net
184.51.15.142	igcdn-videos-c-16-a.akamaihd.net
184.51.15.142	igcdn-videos-c-17-a.akamaihd.net
184.51.15.142	igcdn-videos-c-18-a.akamaihd.net
184.51.15.142	igcdn-videos-c-19-a.akamaihd.net
184.51.15.142	igcdn-videos-d-0-a.akamaihd.net
184.51.15.142	igcdn-videos-d-1-a.akamaihd.net
184.51.15.142	igcdn-videos-d-2-a.akamaihd.net
184.51.15.142	igcdn-videos-d-3-a.akamaihd.net
184.51.15.142	igcdn-videos-d-4-a.akamaihd.net
184.51.15.142	igcdn-videos-d-5-a.akamaihd.net
184.51.15.142	igcdn-videos-d-6-a.akamaihd.net
184.51.15.142	igcdn-videos-d-7-a.akamaihd.net
184.51.15.142	igcdn-videos-d-8-a.akamaihd.net
184.51.15.142	igcdn-videos-d-9-a.akamaihd.net
184.51.15.142	igcdn-videos-d-10-a.akamaihd.net
184.51.15.142	igcdn-videos-d-11-a.akamaihd.net
184.51.15.142	igcdn-videos-d-12-a.akamaihd.net
184.51.15.142	igcdn-videos-d-13-a.akamaihd.net
184.51.15.142	igcdn-videos-d-14-a.akamaihd.net
184.51.15.142	igcdn-videos-d-15-a.akamaihd.net
184.51.15.142	igcdn-videos-d-16-a.akamaihd.net
184.51.15.142	igcdn-videos-d-17-a.akamaihd.net
184.51.15.142	igcdn-videos-d-18-a.akamaihd.net
184.51.15.142	igcdn-videos-d-19-a.akamaihd.net
184.51.15.142	igcdn-videos-e-0-a.akamaihd.net
184.51.15.142	igcdn-videos-e-1-a.akamaihd.net
184.51.15.142	igcdn-videos-e-2-a.akamaihd.net
184.51.15.142	igcdn-videos-e-3-a.akamaihd.net
184.51.15.142	igcdn-videos-e-4-a.akamaihd.net
184.51.15.142	igcdn-videos-e-5-a.akamaihd.net
184.51.15.142	igcdn-videos-e-6-a.akamaihd.net
184.51.15.142	igcdn-videos-e-7-a.akamaihd.net
184.51.15.142	igcdn-videos-e-8-a.akamaihd.net
184.51.15.142	igcdn-videos-e-9-a.akamaihd.net
184.51.15.142	igcdn-videos-e-10-a.akamaihd.net
184.51.15.142	igcdn-videos-e-11-a.akamaihd.net
184.51.15.142	igcdn-videos-e-12-a.akamaihd.net
184.51.15.142	igcdn-videos-e-13-a.akamaihd.net
184.51.15.142	igcdn-videos-e-14-a.akamaihd.net
184.51.15.142	igcdn-videos-e-15-a.akamaihd.net
184.51.15.142	igcdn-videos-e-16-a.akamaihd.net
184.51.15.142	igcdn-videos-e-17-a.akamaihd.net
184.51.15.142	igcdn-videos-e-18-a.akamaihd.net
184.51.15.142	igcdn-videos-e-19-a.akamaihd.net
184.51.15.142	igcdn-videos-f-0-a.akamaihd.net
184.51.15.142	igcdn-videos-f-1-a.akamaihd.net
184.51.15.142	igcdn-videos-f-2-a.akamaihd.net
184.51.15.142	igcdn-videos-f-3-a.akamaihd.net
184.51.15.142	igcdn-videos-f-4-a.akamaihd.net
184.51.15.142	igcdn-videos-f-5-a.akamaihd.net
184.51.15.142	igcdn-videos-f-6-a.akamaihd.net
184.51.15.142	igcdn-videos-f-7-a.akamaihd.net
184.51.15.142	igcdn-videos-f-8-a.akamaihd.net
184.51.15.142	igcdn-videos-f-9-a.akamaihd.net
184.51.15.142	igcdn-videos-f-10-a.akamaihd.net
184.51.15.142	igcdn-videos-f-11-a.akamaihd.net
184.51.15.142	igcdn-videos-f-12-a.akamaihd.net
184.51.15.142	igcdn-videos-f-13-a.akamaihd.net
184.51.15.142	igcdn-videos-f-14-a.akamaihd.net
184.51.15.142	igcdn-videos-f-15-a.akamaihd.net
184.51.15.142	igcdn-videos-f-16-a.akamaihd.net
184.51.15.142	igcdn-videos-f-17-a.akamaihd.net
184.51.15.142	igcdn-videos-f-18-a.akamaihd.net
184.51.15.142	igcdn-videos-f-19-a.akamaihd.net
184.51.15.142	igcdn-videos-g-0-a.akamaihd.net
184.51.15.142	igcdn-videos-g-1-a.akamaihd.net
184.51.15.142	igcdn-videos-g-2-a.akamaihd.net
184.51.15.142	igcdn-videos-g-3-a.akamaihd.net
184.51.15.142	igcdn-videos-g-4-a.akamaihd.net
184.51.15.142	igcdn-videos-g-5-a.akamaihd.net
184.51.15.142	igcdn-videos-g-6-a.akamaihd.net
184.51.15.142	igcdn-videos-g-7-a.akamaihd.net
184.51.15.142	igcdn-videos-g-8-a.akamaihd.net
184.51.15.142	igcdn-videos-g-9-a.akamaihd.net
184.51.15.142	igcdn-videos-g-10-a.akamaihd.net
184.51.15.142	igcdn-videos-g-11-a.akamaihd.net
184.51.15.142	igcdn-videos-g-12-a.akamaihd.net
184.51.15.142	igcdn-videos-g-13-a.akamaihd.net
184.51.15.142	igcdn-videos-g-14-a.akamaihd.net
184.51.15.142	igcdn-videos-g-15-a.akamaihd.net
184.51.15.142	igcdn-videos-g-16-a.akamaihd.net
184.51.15.142	igcdn-videos-g-17-a.akamaihd.net
184.51.15.142	igcdn-videos-g-18-a.akamaihd.net
184.51.15.142	igcdn-videos-g-19-a.akamaihd.net
184.51.15.142	igcdn-videos-h-0-a.akamaihd.net
184.51.15.142	igcdn-videos-h-1-a.akamaihd.net
184.51.15.142	igcdn-videos-h-2-a.akamaihd.net
184.51.15.142	igcdn-videos-h-3-a.akamaihd.net
184.51.15.142	igcdn-videos-h-4-a.akamaihd.net
184.51.15.142	igcdn-videos-h-5-a.akamaihd.net
184.51.15.142	igcdn-videos-h-6-a.akamaihd.net
184.51.15.142	igcdn-videos-h-7-a.akamaihd.net
184.51.15.142	igcdn-videos-h-8-a.akamaihd.net
184.51.15.142	igcdn-videos-h-9-a.akamaihd.net
184.51.15.142	igcdn-videos-h-10-a.akamaihd.net
184.51.15.142	igcdn-videos-h-11-a.akamaihd.net
184.51.15.142	igcdn-videos-h-12-a.akamaihd.net
184.51.15.142	igcdn-videos-h-13-a.akamaihd.net
184.51.15.142	igcdn-videos-h-14-a.akamaihd.net
184.51.15.142	igcdn-videos-h-15-a.akamaihd.net
184.51.15.142	igcdn-videos-h-16-a.akamaihd.net
184.51.15.142	igcdn-videos-h-17-a.akamaihd.net
184.51.15.142	igcdn-videos-h-18-a.akamaihd.net
184.51.15.142	igcdn-videos-h-19-a.akamaihd.net
184.51.15.142	instagramimages-a.akamaihd.net
184.51.15.142	instagramstatic-a.akamaihd.net
184.51.15.142	photos-a.ak.instagram.com
184.51.15.142	photos-b.ak.instagram.com
184.51.15.142	photos-c.ak.instagram.com
184.51.15.142	photos-d.ak.instagram.com
184.51.15.142	photos-e.ak.instagram.com
184.51.15.142	photos-f.ak.instagram.com
184.51.15.142	photos-g.ak.instagram.com
184.51.15.142	photos-h.ak.instagram.com
184.51.15.142	videos-a-0.ak.instagram.com
184.51.15.142	videos-a-1.ak.instagram.com
184.51.15.142	videos-a-2.ak.instagram.com
184.51.15.142	videos-a-3.ak.instagram.com
184.51.15.142	videos-a-4.ak.instagram.com
184.51.15.142	videos-a-5.ak.instagram.com
184.51.15.142	videos-a-6.ak.instagram.com
184.51.15.142	videos-a-7.ak.instagram.com
184.51.15.142	videos-a-8.ak.instagram.com
184.51.15.142	videos-a-9.ak.instagram.com
184.51.15.142	videos-a-10.ak.instagram.com
184.51.15.142	videos-a-11.ak.instagram.com
184.51.15.142	videos-a-12.ak.instagram.com
184.51.15.142	videos-a-13.ak.instagram.com
184.51.15.142	videos-a-14.ak.instagram.com
184.51.15.142	videos-a-15.ak.instagram.com
184.51.15.142	videos-a-16.ak.instagram.com
184.51.15.142	videos-a-17.ak.instagram.com
184.51.15.142	videos-a-18.ak.instagram.com
184.51.15.142	videos-a-19.ak.instagram.com
184.51.15.142	videos-b-0.ak.instagram.com
184.51.15.142	videos-b-1.ak.instagram.com
184.51.15.142	videos-b-2.ak.instagram.com
184.51.15.142	videos-b-3.ak.instagram.com
184.51.15.142	videos-b-4.ak.instagram.com
184.51.15.142	videos-b-5.ak.instagram.com
184.51.15.142	videos-b-6.ak.instagram.com
184.51.15.142	videos-b-7.ak.instagram.com
184.51.15.142	videos-b-8.ak.instagram.com
184.51.15.142	videos-b-9.ak.instagram.com
184.51.15.142	videos-b-10.ak.instagram.com
184.51.15.142	videos-b-11.ak.instagram.com
184.51.15.142	videos-b-12.ak.instagram.com
184.51.15.142	videos-b-13.ak.instagram.com
184.51.15.142	videos-b-14.ak.instagram.com
184.51.15.142	videos-b-15.ak.instagram.com
184.51.15.142	videos-b-16.ak.instagram.com
184.51.15.142	videos-b-17.ak.instagram.com
184.51.15.142	videos-b-18.ak.instagram.com
184.51.15.142	videos-b-19.ak.instagram.com
184.51.15.142	videos-c-0.ak.instagram.com
184.51.15.142	videos-c-1.ak.instagram.com
184.51.15.142	videos-c-2.ak.instagram.com
184.51.15.142	videos-c-3.ak.instagram.com
184.51.15.142	videos-c-4.ak.instagram.com
184.51.15.142	videos-c-5.ak.instagram.com
184.51.15.142	videos-c-6.ak.instagram.com
184.51.15.142	videos-c-7.ak.instagram.com
184.51.15.142	videos-c-8.ak.instagram.com
184.51.15.142	videos-c-9.ak.instagram.com
184.51.15.142	videos-c-10.ak.instagram.com
184.51.15.142	videos-c-11.ak.instagram.com
184.51.15.142	videos-c-12.ak.instagram.com
184.51.15.142	videos-c-13.ak.instagram.com
184.51.15.142	videos-c-14.ak.instagram.com
184.51.15.142	videos-c-15.ak.instagram.com
184.51.15.142	videos-c-16.ak.instagram.com
184.51.15.142	videos-c-17.ak.instagram.com
184.51.15.142	videos-c-18.ak.instagram.com
184.51.15.142	videos-c-19.ak.instagram.com
184.51.15.142	videos-d-0.ak.instagram.com
184.51.15.142	videos-d-1.ak.instagram.com
184.51.15.142	videos-d-2.ak.instagram.com
184.51.15.142	videos-d-3.ak.instagram.com
184.51.15.142	videos-d-4.ak.instagram.com
184.51.15.142	videos-d-5.ak.instagram.com
184.51.15.142	videos-d-6.ak.instagram.com
184.51.15.142	videos-d-7.ak.instagram.com
184.51.15.142	videos-d-8.ak.instagram.com
184.51.15.142	videos-d-9.ak.instagram.com
184.51.15.142	videos-d-10.ak.instagram.com
184.51.15.142	videos-d-11.ak.instagram.com
184.51.15.142	videos-d-12.ak.instagram.com
184.51.15.142	videos-d-13.ak.instagram.com
184.51.15.142	videos-d-14.ak.instagram.com
184.51.15.142	videos-d-15.ak.instagram.com
184.51.15.142	videos-d-16.ak.instagram.com
184.51.15.142	videos-d-17.ak.instagram.com
184.51.15.142	videos-d-18.ak.instagram.com
184.51.15.142	videos-d-19.ak.instagram.com
184.51.15.142	videos-e-0.ak.instagram.com
184.51.15.142	videos-e-1.ak.instagram.com
184.51.15.142	videos-e-2.ak.instagram.com
184.51.15.142	videos-e-3.ak.instagram.com
184.51.15.142	videos-e-4.ak.instagram.com
184.51.15.142	videos-e-5.ak.instagram.com
184.51.15.142	videos-e-6.ak.instagram.com
184.51.15.142	videos-e-7.ak.instagram.com
184.51.15.142	videos-e-8.ak.instagram.com
184.51.15.142	videos-e-9.ak.instagram.com
184.51.15.142	videos-e-10.ak.instagram.com
184.51.15.142	videos-e-11.ak.instagram.com
184.51.15.142	videos-e-12.ak.instagram.com
184.51.15.142	videos-e-13.ak.instagram.com
184.51.15.142	videos-e-14.ak.instagram.com
184.51.15.142	videos-e-15.ak.instagram.com
184.51.15.142	videos-e-16.ak.instagram.com
184.51.15.142	videos-e-17.ak.instagram.com
184.51.15.142	videos-e-18.ak.instagram.com
184.51.15.142	videos-e-19.ak.instagram.com
184.51.15.142	videos-f-0.ak.instagram.com
184.51.15.142	videos-f-1.ak.instagram.com
184.51.15.142	videos-f-2.ak.instagram.com
184.51.15.142	videos-f-3.ak.instagram.com
184.51.15.142	videos-f-4.ak.instagram.com
184.51.15.142	videos-f-5.ak.instagram.com
184.51.15.142	videos-f-6.ak.instagram.com
184.51.15.142	videos-f-7.ak.instagram.com
184.51.15.142	videos-f-8.ak.instagram.com
184.51.15.142	videos-f-9.ak.instagram.com
184.51.15.142	videos-f-10.ak.instagram.com
184.51.15.142	videos-f-11.ak.instagram.com
184.51.15.142	videos-f-12.ak.instagram.com
184.51.15.142	videos-f-13.ak.instagram.com
184.51.15.142	videos-f-14.ak.instagram.com
184.51.15.142	videos-f-15.ak.instagram.com
184.51.15.142	videos-f-16.ak.instagram.com
184.51.15.142	videos-f-17.ak.instagram.com
184.51.15.142	videos-f-18.ak.instagram.com
184.51.15.142	videos-f-19.ak.instagram.com
184.51.15.142	videos-g-0.ak.instagram.com
184.51.15.142	videos-g-1.ak.instagram.com
184.51.15.142	videos-g-2.ak.instagram.com
184.51.15.142	videos-g-3.ak.instagram.com
184.51.15.142	videos-g-4.ak.instagram.com
184.51.15.142	videos-g-5.ak.instagram.com
184.51.15.142	videos-g-6.ak.instagram.com
184.51.15.142	videos-g-7.ak.instagram.com
184.51.15.142	videos-g-8.ak.instagram.com
184.51.15.142	videos-g-9.ak.instagram.com
184.51.15.142	videos-g-10.ak.instagram.com
184.51.15.142	videos-g-11.ak.instagram.com
184.51.15.142	videos-g-12.ak.instagram.com
184.51.15.142	videos-g-13.ak.instagram.com
184.51.15.142	videos-g-14.ak.instagram.com
184.51.15.142	videos-g-15.ak.instagram.com
184.51.15.142	videos-g-16.ak.instagram.com
184.51.15.142	videos-g-17.ak.instagram.com
184.51.15.142	videos-g-18.ak.instagram.com
184.51.15.142	videos-g-19.ak.instagram.com
184.51.15.142	videos-h-0.ak.instagram.com
184.51.15.142	videos-h-1.ak.instagram.com
184.51.15.142	videos-h-2.ak.instagram.com
184.51.15.142	videos-h-3.ak.instagram.com
184.51.15.142	videos-h-4.ak.instagram.com
184.51.15.142	videos-h-5.ak.instagram.com
184.51.15.142	videos-h-6.ak.instagram.com
184.51.15.142	videos-h-7.ak.instagram.com
184.51.15.142	videos-h-8.ak.instagram.com
184.51.15.142	videos-h-9.ak.instagram.com
184.51.15.142	videos-h-10.ak.instagram.com
184.51.15.142	videos-h-11.ak.instagram.com
184.51.15.142	videos-h-12.ak.instagram.com
184.51.15.142	videos-h-13.ak.instagram.com
184.51.15.142	videos-h-14.ak.instagram.com
184.51.15.142	videos-h-15.ak.instagram.com
184.51.15.142	videos-h-16.ak.instagram.com
184.51.15.142	videos-h-17.ak.instagram.com
184.51.15.142	videos-h-18.ak.instagram.com
184.51.15.142	videos-h-19.ak.instagram.com
184.51.15.142	images.ak.instagram.com
184.51.15.142	static.ak.instagram.com
184.51.15.142	distilleryimage0.ak.instagram.com
184.51.15.142	distilleryimage1.ak.instagram.com
184.51.15.142	distilleryimage2.ak.instagram.com
184.51.15.142	distilleryimage3.ak.instagram.com
184.51.15.142	distilleryimage4.ak.instagram.com
184.51.15.142	distilleryimage5.ak.instagram.com
184.51.15.142	distilleryimage6.ak.instagram.com
184.51.15.142	distilleryimage7.ak.instagram.com
184.51.15.142	distilleryimage8.ak.instagram.com
184.51.15.142	distilleryimage9.ak.instagram.com
184.51.15.142	distilleryimage10.ak.instagram.com
184.51.15.142	distilleryimage11.ak.instagram.com
220.250.64.225	telegraph-ec2proxy.instagram.com
# Instagram

**Comment by eianslight** [comment]
@DaleXiao 
It worked . Thanks very much for your help !

**Comment by fishyub** [comment]
解决方法：在ss设置，把代理服务器信息那里把ipv6路由器的选项关闭，就ok了。
