### ISSUE TITLE
It seems there is something wrong in travis-ci status icon

### ISSUE THREAD

**Issue by Too-Naive** [racaljk/hosts#485]
![image](https://cloud.githubusercontent.com/assets/16496671/16148982/09f7f31a-34c0-11e6-8d33-cede5a8cfe70.png)

**Comment by andytimes** [comment]
@Too-Naive 我的错、、、、地址写错了

**Comment by Too-Naive** [comment]
[![Build Status](https://travis-ci.org/racaljk/hosts.svg?branch=master)](https://travis-ci.org/racaljk/hosts)

**Comment by Too-Naive** [comment]
....直接复制过来就这样。。。

**Comment by andytimes** [comment]
@Too-Naive 好奇怪，这个图片时好时坏的，等几分钟再看看

**Comment by andytimes** [comment]
![](https://api.travis-ci.org/racaljk/hosts.svg?branch=master)

**Comment by Too-Naive** [comment]
有毒吧

**Comment by imcaffrey** [comment]
http://shields.io/

**Comment by andytimes** [comment]
@Too-Naive 我估计是 Github 的问题。因为我们看到的是 Github 缓存的

**Comment by andytimes** [comment]
赞！可以试试这个 https://img.shields.io/travis/racaljk/hosts/master.svg

**Comment by andytimes** [comment]
我去改了

**Comment by Too-Naive** [comment]
改完了..

**Comment by andytimes** [comment]
、、、@Too-Naive 你的手速好快

**Comment by Too-Naive** [comment]
正常啊233 复制粘帖的事情
![](https://cloud.githubusercontent.com/assets/16496671/14945197/49ed17c6-103e-11e6-80b8-f9f6b6dd33be.gif)
