### ISSUE TITLE
new issue

### ISSUE THREAD

**Issue by mifia** [racaljk/hosts#486]
是想问，地图那里无法打开时间轴，地图和卫星图不重合，有解决办法吗？

**Comment by Too-Naive** [comment]
?

**Comment by mifia** [comment]
就是地图偏移的问题，时间轴打不开

**Comment by Too-Naive** [comment]
不是很懂你在说什么

**Comment by racaljk** [comment]
这个你应该到相关的webapp去反馈

**Comment by imcaffrey** [comment]
Google地图？

**Comment by mifia** [comment]
是的呀，偏移，同时时间轴无法打开，看样子我的贡献也是没联网的

SCaffrey <notifications@github.com>于2016年6月18日周六 12:52写道：

> Google地图？
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/racaljk/hosts/issues/486#issuecomment-226921979>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/ATEYe1RZcFfR4_Chw9U_LpqdE9rY6DiOks5qM3mcgaJpZM4I4URg>
> .
>
-- 

mifia

**Comment by Too-Naive** [comment]
Google地图应该不在本repo讨论的范畴吧....软件问题

**Comment by aofall** [comment]
时间轴应该是域名 需要你自己抓包
但是位置稍微偏移或者严重偏移就不是hosts能解决的问题了，你自己去搜索就会知道有关部门颁布相关条令规定地图必须要有偏移，说是为了国家安全。

**Comment by Too-Naive** [comment]
附议ls
