### ISSUE TITLE
hosts 最后修改时间的检测

### ISSUE THREAD

**Issue by andytimes** [racaljk/hosts#487]
刚刚发现 Travis 关于时间的检测，报错了。

对于时间的检测我是这样考虑的：
先用 find 命令的 -printf 选项找出 hosts 的最后修改时间，然后和 hosts 里面的 Last updated
的时间比较。

猜测可能是 git clone 的时候，hosts 的最后修改时间被认为是 clone 的时间，
我觉得应该从 git 的指令中获取 hosts 文件的最后修改时间，这样能准确一点，但是还不太清楚
怎么去获取，各位有想法吗？

**Comment by andytimes** [comment]
想法：

`$ git log hosts`

获取 hosts 的变更 commit，提取第一个的 Date

`$ date -d "Fri Jun 17 18:41:35 2016" "+%Y-%m-%d"`

输出：
`2016-06-17`

**Comment by andytimes** [comment]
`git log --date=short`

**Comment by Too-Naive** [comment]
date不够 
最坏情况分析 一天修改50次呢

**Comment by andytimes** [comment]
@Too-Naive 没理解你的意思

**Comment by andytimes** [comment]
@Too-Naive https://github.com/racaljk/hosts/commit/9f00eaa9b822b976b0ab8e02295f1576306edacf

**Comment by Too-Naive** [comment]
我看不懂 不过想问 获得的是只有date还是date 和time？

**Comment by andytimes** [comment]
```shell
$ git log --date=short

commit 3ae0d2791bfda5751ffa09b9e4afc008136d863f
Author: Dale Xiao <DaleXiao@users.noreply.github.com>
Date:   2016-06-17

    Fixed the Image Broken Issue of Instagram (#484)

    As captioned, a temporary solution to fix the Image Broken Issue of Instagram, testing on Browser and Apps on Mobile, works well so far.

commit aaca82175762a214a74a553176cf8c24654211fd
Author: Andy Deng <theandy.deng@gmail.com>
Date:   2016-06-17

    travis: add a script for hosts format checking

    由于 hosts 文件对换行符十分敏感，所以加入脚本进行如下检测：

    - 换行符测试
    - hosts 格式测试（可选）
    - hosts 更新时间检测（可选）

    设置环境变量 STRICT_HOSTS_FORMAT，从而开启所有选项，默认只开启“换行符测试”

    Signed-off-by: Andy Deng <theandy.deng@gmail.com>

... （已截断）

$ git log --date=short hosts | grep -o "[0-9]\+-[0-9]\+-[0-9]\+"

2016-06-17
2016-06-17
2016-06-14
2016-06-10
2016-06-10
2016-06-10
2016-06-04
2016-06-04
2016-05-31
2016-05-31
2016-05-25
2016-05-24
2016-05-24
... （已截断）
使用 grep 的正则表达式提取日期 （这里其实可以做更精确的匹配不过没必要）

$ git log --date=short hosts | grep -o "[0-9]\+-[0-9]\+-[0-9]\+" -m 1

2016-06-17

仅提取第一个匹配项
```

也就是，如果有人修改了 hosts，并且生成 commit，就用 commit 的时间和 hosts 文件内
Last updated 这一行的时间进行比较。
相同： All fine！
不同：警告

**Comment by andytimes** [comment]
相关指令的介绍：
`man grep`
`git log --help`

**Comment by Too-Naive** [comment]
一天修改50次 那时间不也一样吗

**Comment by imcaffrey** [comment]
只需要last commit的date？

**Comment by andytimes** [comment]
@Too-Naive 所以，这本来就是无所谓的，我认为 git log 比 hosts 文件内记录要好得多，
你可以看一下 hosts 的修改历史，以前的时间表示是这样的
> Sat Jun 18 14:17:23 2016 CST

后来嫌麻烦，就改成现在这样了。

@imcaffrey 检测的是 hosts 的 last commit

**Comment by imcaffrey** [comment]
似乎可以git blame hosts然后获取那一行

**Comment by Too-Naive** [comment]
还是没懂...............................................
这样问吧 一天修改50次 能不鞥你检测得出来？

**Comment by imcaffrey** [comment]
#69 只加个日期对于目前hosts来说已经足够了

如果修改50次那为什么不在一个commit里一起提交

**Comment by Too-Naive** [comment]
![](https://cloud.githubusercontent.com/assets/16496671/14873063/cd15c35e-0d24-11e6-81ec-9f97b2c120da.JPG)

**Comment by andytimes** [comment]
@imcaffrey 我记得 Travis 可以加 gpg key，这样可以自动修改格式，
不过我现在不想弄了，虽然很有趣。

> 似乎可以git blame hosts然后获取那一行

git blame 我还没什么好的想法，这个用来查恶意修改，或者代码归属权比较好，对于其他的，用处不大

**Comment by imcaffrey** [comment]
git blame里不是有时间吗233

**Comment by andytimes** [comment]
@imcaffrey 那是代码片段的最后修改时间，和 Last updated 是一样的，要提取还是要 grep 截断。
如果我有误解你的意思，请指正

**Comment by imcaffrey** [comment]
嗯一样的

**Comment by andytimes** [comment]
@imcaffrey 加了一个脚本自动格式化 hosts
https://github.com/racaljk/hosts/commit/082509351725e5a434db1e6880d8c1754283f7dd
