### ISSUE TITLE
[Not an issue] Suggestion

### ISSUE THREAD

**Issue by Too-Naive** [racaljk/hosts#495]
我是觉得说 我们是不是应该单独维护一个关于google的hosts文件呢?

> :statue_of_liberty:最新可用的google hosts文件

我想 随着hosts文件里面包含的网站越来越多 我们是不是为了维护项目的初衷 维护一个单独的google hosts文件 而把包含其他东西的hosts放到另一个地方呢

只是小建议 不喜请尽可能喷我

**Comment by redapple0204** [comment]
@Too-Naive 感觉没啥必要，免得用户还要在下载一次。。变得更麻烦。

**Comment by Ignotus-CN** [comment]
更妥当的办法是联系菊苣修改 description

**Comment by imcaffrey** [comment]
@racaljk 拍板决定下吧 方向性的东西

**Comment by racaljk** [comment]
没什么必要，反而不方便

..comment消失系列

**Comment by Too-Naive** [comment]
233 好的
