### ISSUE TITLE
关于YouTube视频无法播放的解决方案

### ISSUE THREAD

**Issue by CindyYang8** [racaljk/hosts#499]
大家都知道，仅修改hosts文件是无法实现YouTube视频播放的。
要想观看YouTube视频必须使用代理。
因此，我想在readme.md中附加代理的广告，
广告内容如下：
<img src="https://ifanqie.cc/1.jpg">

同时，在hosts中加入广告备注：
`# Watch youtube videos all in https://iFanQie.cc`

大家的意见如何？

**Comment by billhhh** [comment]
最好不要加入广告

**Comment by billhhh** [comment]
写明需要用代理就好

**Comment by idvr** [comment]
免费的可以加进来

**Comment by billhhh** [comment]
刚刚试了一下，在IE内核的情况下，我关了所有代理，是可以直接看YouTube视频的

**Comment by CindyYang8** [comment]
<img src="https://ifanqie.cc/%E6%8D%95%E8%8E%B7.PNG" width="871" height="466">

**Comment by CindyYang8** [comment]
在IE内核的情况下。关了所有代理，不可以直接看YouTube视频。

**Comment by billhhh** [comment]
我是可以的~~这就奇怪了，我的确关掉了所有代理，我可能用的另一个github上的hosts

**Comment by CindyYang8** [comment]
另一个github上的hosts分享一下

**Comment by billhhh** [comment]
我比对了一下，应该是 https://raw.githubusercontent.com/cnAnonymous/hosts/master/hosts 这个，你试一下，不论是否可以看都回复一下

**Comment by CindyYang8** [comment]
可以播放

**Comment by billhhh** [comment]
ok，低调使用

**Comment by Too-Naive** [comment]
此项目不在本repo的讨论范围之内 毕竟代理和hosts是没有直接的联系的 
从其他问题的issue已经有体现出需要使用代理的成分
但本项目不会加入任何与项目无关的东西

> 🗽最新可用的google hosts文件。

**Comment by Hongnanjing** [comment]
广告都到这里了！
