### ISSUE TITLE
Google is not accessible anymore

### ISSUE THREAD

**Issue by shade7480** [racaljk/hosts#5]
Did China block all the ips already?

**Comment by 21paradox** [comment]
+1
216.58.220.220 is blocked.
 Looking forward for an updated hosts.

**Comment by racaljk** [comment]
**Hosts File for Google**  has been updated just now,try again to connect [www.google.com](https://www.google.com)

**Comment by 21paradox** [comment]
@racaljk  64.233.189.91 这个ip还是打不开,你那里可以吗？

**Comment by racaljk** [comment]
@21paradox 刷新试试吧
![img](http://www.racalinux.cn/3.png)

**Comment by 21paradox** [comment]
感谢，虽然还是不行.. 
我现在用 202.152.192.181 这个ip

**Comment by whinamp** [comment]
麻烦LZ把youtube的域名单独归为一项，一目了然的话方便。youtube又挂了，这里是被GFW认证了吗？

**Comment by whinamp** [comment]
还有oschina这里jiange1236 提供的ip为啥都用不了呢？莫非是死的太快？

**Comment by racaljk** [comment]
@whinamp 下次更新会把YouTube单独归类

**Comment by whinamp** [comment]
多谢。@racaljk 4月18日，最新一版为什么无效呢？google主页以及相关服务全打不开。是哪里的问题?

**Comment by whinamp** [comment]
![image](https://cloud.githubusercontent.com/assets/7509444/7275142/ac58147e-e934-11e4-9433-cc39e3d08c31.png)

**Comment by shade7480** [comment]
google, youtube and etc are not accessible once again even with the latest files, i can get on facebook though.

**Comment by racaljk** [comment]
@shade7480 @whinamp  已更新

**Comment by shade7480** [comment]
Gmail went down once again, seems like they are going down really quickly

**Comment by cw881014** [comment]
亲，天津地区联通用户表示google不行了。。。但是fb和twitter是可以的~

**Comment by LangleyChang** [comment]
Youtube is no longer accessible.

**Comment by whinamp** [comment]
挂得越来越快了。。

**Comment by 21paradox** [comment]
试试 http://64.233.162.83/

**Comment by chenshengzhi** [comment]
新的github变得很慢, 上一个版本的就比较快而且还能用

**Comment by SMoUNiVeS** [comment]
@chenshengzhi  已更新

**Comment by chenshengzhi** [comment]
@SMoUNiVeS 谢谢！

**Comment by ihead** [comment]
丢进安卓机，发现 Google Play 商店的软件 ICON 和截图都无法显示...

**Comment by racaljk** [comment]
@ihead PC上面没有任何问题，检查你是否关闭了“图片显示”之类的设置吧

**Comment by ihead** [comment]
@racaljk 神奇就神奇在有些能加载，有些不能加载_(:зゝ∠)_，Play 是没有关闭图片显示之类选项的呢... http://ww1.sinaimg.cn/large/3fa581afgw1etapzgzscmj20u01hcdlh.jpg 我也觉得奇怪，不就都是些 ggpht，怎么安卓机反而不能加载。

**Comment by SMoUNiVeS** [comment]
@racaljk  @ihead Android的Play Store用的端口不一样不是443的所以部分图片不能加载，Android不推荐改hosts……还是Shadowsocks或者免费的赛风3吧

**Comment by whinamp** [comment]
真奇怪，之前一直好好的。今早android端google相关全挂，PC上却好好地。

![Uploading QQ图片20150716140242.png…]()

**Comment by whinamp** [comment]
真奇怪，之前一直好好的。今早android端google相关全挂，PC上似乎一切正常。但是请看下图。
![qq 20150716140242](https://cloud.githubusercontent.com/assets/7509444/8716639/c5723204-2bc5-11e5-8a97-44b9e229e7b6.png)

**Comment by andrewchen5678** [comment]
你是改hosts后才试ip吗？因为直接输入ip的话会重定向到www.google.com.

**Comment by andrewchen5678** [comment]
新的64.233.162.83现在可以用. 
![screenshot 2015-07-17 19 01 37](https://cloud.githubusercontent.com/assets/2096114/8759901/71a2a810-2cb6-11e5-8bdd-00e33108c642.png)

**Comment by whinamp** [comment]
这次的hosts文件似乎和之前的很不一样。替换以后Android上Google相关的客户端全挂，挂上shadowsocks都没用。但是在chrome里都可以正常使用。

**Comment by whinamp** [comment]
这次更新的文件有些问题，Android端Google相关服务的客户端全挂，开shadowsocks都无法解决。IP倒是完全有效，在chrome里可以正常打开和使用Google各种服务。

**Comment by shade7480** [comment]
Some issues I have encountered, cannot get on the US google, cannot get on youtube, also a website named macgamestore is also unaccessible for some reason

**Comment by andrewchen5678** [comment]
64.233.162.83挂了，建议以后Google的IP不要放在这么公开的地方，这样很容易被封杀。
![screenshot 2015-07-21 08 24 15](https://cloud.githubusercontent.com/assets/2096114/8804636/07868dba-2f82-11e5-9acb-7a08112437e2.png)
:(

**Comment by andrewchen5678** [comment]
建议Google的IP不要放在这么公开的地方，这样很容易被封杀。

**Comment by SMoUNiVeS** [comment]
@andrewchen5678 无所谓了，反正已经快封完了，公不公开也只是时间的问题，而且不会太久了
