### ISSUE TITLE
是否可以添加bit.ly的IP到hosts里？

### ISSUE THREAD

**Issue by Zhouxing-Su** [racaljk/hosts#501]
虽说这个 repo 的介绍说是 google 的 ip ，但是似乎也有很多其他网站的，所以想问下是否可以添加 bit.ly 的 ip 到 hosts 里？

**Comment by Too-Naive** [comment]
短网址……劲阿

**Comment by imcaffrey** [comment]
https://bitly.com/

**Comment by LGA1150** [comment]
强制HTTPS即可，暂不需添加
