### ISSUE TITLE
Error Code 451

### ISSUE THREAD

**Issue by imcaffrey** [racaljk/hosts#502]
FYI: https://github.com/programthink/zhao

且行且珍惜

https://zhuanlan.zhihu.com/p/21432458

**Comment by Hongnanjing** [comment]
挂代理就能正常访问
![doodles](https://lh3.googleusercontent.com/unBtj68FiEf02vUWMvMJAc3UmdtpQrFF6i4Pm2RYv-v-nhg615nM6WqvKGs_kH72u9L6ioNl1Gf0vPimr-IzdxuFxSWRif5Et5bS_1UpcEIBwxB8aNQFdAI0mbz2H3cmVQE5iJ_NaoL4NXG7vFYRSpIj1cmuD_T5Ytpc-1NJOXTl_XrnRBlLuHYwsoCgJJyXqnIRj95dLXwPZ7vGK4-6e440bpH9hhxi4o1cZG24sPkGOl1qJLr8Q3IkdLSOZyI8VuxJBujpdxv21XIN7ZHxcRkVwH5ujFjRWmY_e8VEbdl6kwjNk1BbfsCTG91XL-8DPznR42EL9iW8Cwh_DZiSVuAFzrliw-bHuxLGFJBSeHIc9HLbbMicrN6XVCavuXkWRs1-WxgdgUodFXGxzFR1VV0nPnGXigT6tNvd8ru2J-9VWyEUVwHYF1EGk81uUUJ7Zae4ruxc3BkXSTMF6ChyDtzFn6_8gtvNQ3KYuVtvCe0xnxJcH4XfmDzlR2QmDotITnj4t-ZEr59ErW-Da1nltSo-GQkhs-4isAM_6TNHHSF11OOoN2myHjehVTLGvt5Ke2T5u-rIuDyMtnGuxzbxpODba-JCA_M=w993-h637-no)

**Comment by Hongnanjing** [comment]
github早晚被墙

**Comment by Too-Naive** [comment]
有些sb总爱搞事 gtmd

**Comment by imcaffrey** [comment]
有时我无法理解为什么有人要特别喜欢打奇怪的label

**Comment by Too-Naive** [comment]
求要喷我直接喷行不 为什么要用"有人"这个称谓呢？

**Comment by racaljk** [comment]
有故事的repo

我也有点慌

**Comment by andytimes** [comment]
好吧，第一次见到 451，涨知识了。

自己躲在国外，在 Github 上面存这些东西，这不是坑人吗、、、
直接到中南海去刚，这样才值得点赞。

**Comment by straightdave** [comment]
请不要在Github上这么做，自建博客吧。
有人愿意说，有人愿意听，都可以；可Github上也有人也不愿意听，或者不感兴趣；要是却被你的行为影响到Github正常使用，那你是侵犯了他们的自由和权力。
这么想，这不是个自私和粗鲁的做法吗？这么做又能带来什么好的结果吗？
还请正反两面冷静思考。

**Comment by redapple0204** [comment]
github我已经上传不了文件了
中国吃枣药丸

**Comment by Too-Naive** [comment]
是不是和长相有关？




-------- 原始邮件 --------
发件人： redapple0204 <notifications@github.com>
日期: 2016-07-02 07:51 (GMT+08:00)
收件人： racaljk/hosts <hosts@noreply.github.com>
抄送： Unostvisal <sometimes.naive@hotmail.com>, Comment <comment@noreply.github.com>
主题： Re: [racaljk/hosts] Error Code 451 (#502)


github我已经上传不了文件了
中国吃枣药丸

―
