### ISSUE TITLE
Gmail能登陆，但谷歌搜索用不了

### ISSUE THREAD

**Issue by csyezheng** [racaljk/hosts#505]
Facebook、Twitter、Gmail 都能打开，但谷歌搜索不能打开。
好奇怪啊。。。

**Comment by Too-Naive** [comment]
#387 ?

**Comment by csyezheng** [comment]
This site can’t be reached

The connection was reset.
Try:
Reloading the page
Checking the connection
Checking the proxy and the firewall
ERR_CONNECTION_RESET

这样显示的呀，没有什么#387啊，不懂。。。〒_〒

**Comment by csyezheng** [comment]
已解决，谢谢
