### ISSUE TITLE
Google无法访问

### ISSUE THREAD

**Issue by cxxly** [racaljk/hosts#509]
访问www.google.com.hk，提示以下信息：
```
www.google.com.hk 网页无法正常运作

www.google.com.hk 未发送任何数据。
```

**Comment by coolrc136** [comment]
陕西移动，联通，电信都挂了

**Comment by Too-Naive** [comment]
https?

**Comment by coolrc136** [comment]
好吧，我这今天下午又能用了。。。

**Comment by cxxly** [comment]
依然不能用

**Comment by Too-Naive** [comment]
https://google.com/ncr
如果还不能用 请过一段时间再尝试

**Comment by imcaffrey** [comment]
64.233.162.8x

**Comment by Hongnanjing** [comment]
@cxxly 中科院的？听说有些部门有专用光纤直通海外

**Comment by cxxly** [comment]
@Hongnanjing, ..., 不知道啊

**Comment by racaljk** [comment]
使用https访问

**Comment by andytimes** [comment]
@cxxly Chrome 浏览器在某个版本以后，访问首页就有点问题，最好详细发下连接的信息。
> www.google.com.hk 网页无法正常运作
>
> www.google.com.hk 未发送任何数据。

这样的语言提示有点像是 Chrome 的，可以看下是不是这个问题 https://github.com/racaljk/hosts/issues/474

如果不是，发一下 `ping google.com` 的结果，再分析下是什么情况。
