### ISSUE TITLE
在网上截个图，大家怎么看

### ISSUE THREAD

**Issue by imcaffrey** [racaljk/hosts#512]
http://r5.loli.io/MFB3mu.png

![IMG](http://r5.loli.io/MFB3mu.png)

**Comment by Too-Naive** [comment]
啊 您居然吸毒

**Comment by Hongnanjing** [comment]
哈哈哈，这标题
我想问问 如何成为contributor

**Comment by andytimes** [comment]
@imcaffrey 至少比以前那个小黄鸭好多了

**Comment by Too-Naive** [comment]
哈哈哈哈哈哈哈哈哈哈哈哈哈哈 @imcaffrey 求您来指导头像



Sent from my Samsung device


-------- Original message --------

**Comment by Too-Naive** [comment]
有努力 就有收获





-------- Original message --------
