### ISSUE TITLE
希望添加onedrive地址，它也会不定时抽风，地址在正文中

### ISSUE THREAD

**Issue by ShookGao** [racaljk/hosts#514]
134.170.108.26	onedrive.live.com
134.170.109.48	skyapi.onedrive.live.com

**Comment by Too-Naive** [comment]
为何不用pr呢.

**Comment by ShookGao** [comment]
@Too-Naive 我不懂pr是什么，不过我在用onenote，它存在onedrive上

**Comment by ShookGao** [comment]
@Too-Naive 啊，我明白pr是什么了，github还不太会用，见谅:)

**Comment by Too-Naive** [comment]
233 并没有关系

-------- Original message --------
