### ISSUE TITLE
能否添加jcenter的host？

### ISSUE THREAD

**Issue by tingbob** [racaljk/hosts#516]
jcenter的host能否添加下？之前不用host还能访问。现在貌似访问不了了。
https://bintray.com/bintray/jcenter

**Comment by imcaffrey** [comment]
```
PING bintray.com (119.81.184.206) 56(84) bytes of data.
64 bytes from ce.b8.5177.ip4.static.sl-reverse.com (119.81.184.206): icmp_seq=5 ttl=45 time=304 ms
64 bytes from ce.b8.5177.ip4.static.sl-reverse.com (119.81.184.206): icmp_seq=7 ttl=45 time=970 ms
64 bytes from ce.b8.5177.ip4.static.sl-reverse.com (119.81.184.206): icmp_seq=14 ttl=45 time=290 ms
64 bytes from ce.b8.5177.ip4.static.sl-reverse.com (119.81.184.206): icmp_seq=18 ttl=45 time=275 ms
^C
--- bintray.com ping statistics ---
20 packets transmitted, 4 received, 80% packet loss, time 19118ms
rtt min/avg/max/mdev = 275.137/460.225/970.379/294.726 ms
```

**Comment by Too-Naive** [comment]
福建电信 访问正常

**Comment by tingbob** [comment]
`20 packets transmitted, 4 received, **80%** packet loss, time 19118ms'
郁闷了，浙江电信完全打不开。

**Comment by Too-Naive** [comment]
?$BQ\E7:F4G4G!)(B?$B@'0x(B?$B2r@OE*(BIP$BITF1!)(B

On Jul 7, 2016, at 11:46, tingbob <notifications@github.com<mailto:notifications@github.com>> wrote:


`20 packets transmitted, 4 received, 80% packet loss, time 19118ms'
$B0j(B?$BN;!$^69>(B?$B?.40A4BGIT(B?$B!#(B

-

**Comment by tingbob** [comment]
Sorry，不知为何你们那里看起来是乱码。
我上个评论如下：
80% packet loss
郁闷了，浙江电信完全打不开。

**Comment by imcaffrey** [comment]
评论是没有问题的（可能是因为劲劲的网络出了故障才总是看错的）

**Comment by Too-Naive** [comment]
日噢 这iPad直接回复不行233 
我原来的回复是 过几天再看看 要不您那验证一下IP是不是我们解析到的这个
我叫静静！

**Comment by tingbob** [comment]
IP是同一个

**Comment by racaljk** [comment]
四川电信访问正常
