### ISSUE TITLE
关于最近很火爆的Pokemon Go

### ISSUE THREAD

**Issue by AlexDialga** [racaljk/hosts#519]
其开发团队的网页似乎无法进入= =
https://www.nianticlabs.com/

**Comment by racaljk** [comment]
这个服务器间歇性抽风，之前还可以进入限制无法连接了。

如果仅仅是访问它的网页可以考虑使用在线网页代理:69.30.217.157(虽然这并不安全，不过话又说回来真正安全的proxy几乎不存在，2层反代加vpn要给你破坏也不是难事)

**Comment by aofall** [comment]
64.233.188.121 www.nianticlabs.com

**Comment by Too-Naive** [comment]
早讲啊............

**Comment by aofall** [comment]
Google:ghs

**Comment by PowerOlive** [comment]
.....................................
