### ISSUE TITLE
可否加入谷歌云硬盘证书host地址

### ISSUE THREAD

**Issue by iTaster** [racaljk/hosts#527]
如题

**Comment by Too-Naive** [comment]
域名?

**Comment by iTaster** [comment]
安装谷歌云硬盘PC端会出现证书错误，看到有说hosts可以解决，其实也不是多大问题。最后查了一下，把IE选项 高级里面的【 “对证书地址不匹配发出警告”+“检查发行商的证书是否吊销”+“检查服务器证书是否吊销”】 取消勾选就可以里，但感觉安全性不是多好。

**Comment by Too-Naive** [comment]
证书拦截
