### ISSUE TITLE
请问下你们是如何获取host的？

### ISSUE THREAD

**Issue by sunqb** [racaljk/hosts#528]
请问下你们是如何获取host的？

**Comment by Too-Naive** [comment]
不可说 不可说啊

**Comment by Too-Naive** [comment]
我可以说无可奉告 但你们又不高兴 那怎么办

**Comment by racaljk** [comment]
gogotester跑ip段，反正我是这么干的

**Comment by sunqb** [comment]
@Too-Naive 别闹，自己搭的vpn好贵，舍不得用，还是host好

**Comment by Too-Naive** [comment]
那直接用这个repo不就好了。。。

**Comment by imcaffrey** [comment]
@sunqb 怎么就好贵了呢 你是缺少发现的眼睛

**Comment by Shineee** [comment]
https://github.com/getlantern/lantern
这个挺好用，就是偶尔封那么一下，过几天就好了，80-90%都是稳定的，毕竟免费，比goagent,自由门都强，速度快，而且不用老换host,个人觉得host是没办法中的办法，能不用就不用，没招了再用。

**Comment by Too-Naive** [comment]
这破网站吃枣药丸

**Comment by sunqb** [comment]
@imcaffrey  vps一年一百多不贵嘛？你们都好有钱。。。

**Comment by sunqb** [comment]
@Too-Naive ss速度还是没法和vpn比的，带宽60M下测试结果。

**Comment by Too-Naive** [comment]
不用ss 你就吃枣药丸

-------- Original message --------

**Comment by andytimes** [comment]
可以去学学 BIND 系列工具，被 DNS 污染域名，可以用 dig 找到正确 IP，被 GFW 关键字过滤的，可能就需要你有国外主机来辅助查找了。

Google IP 一般都是跑指定 IP 段，其他的我也不会了。

**Comment by White99** [comment]
@Shineee  别说你不知道 这个已经收费了

**Comment by Shineee** [comment]
@White99 最近确实改版了，但是有免费版的，
免费版每月800m流量限制，超过之后链接速度将限制在20K/s。
专业版售价180元/年，两年版320元
ps:本人不做广告，你可以用免费版或者不用

**Comment by White99** [comment]
@Shineee  现在随便一个网页都超过1M。20k/s .....我刚升级到最新版, 直接提示流量已经用完, 而且根本无法连接,别说20k/s了....

**Comment by Too-Naive** [comment]
够了够了 不要在本项目讨论无关的问题

**Comment by imcaffrey** [comment]
有个chat room嘛
这里issue tracker发东西会推送到好多人的邮箱里的

**Comment by White99** [comment]
@sunqb 没错正如racaljk 说的 checkgoogleip 、gogotester 、gscan 都可以扫IP
@Too-Naive  哈哈，这双标挺有趣…行你聊ss vpn，就不行别人聊 lantern？这里本来就是开放的公共平台供大家交流，并不是你们家啊
@imcaffrey  chat room 也会推送到更多人邮箱吧，若不想接收这种邮件都可以设置啊

**Comment by Too-Naive** [comment]
。。。不是很懂你在说什么 
"给你点阳光就灿烂" ？
讲道理啊 本来只是说个vpn服务器 然后又讲到ss 接着开始说lantern了 那这样后来是不是还要吧**w批判一番啊 Excuse me ?

**Comment by Too-Naive** [comment]
请自己看一下聊天室 我是不是也说过类似的话? @White99

**Comment by imcaffrey** [comment]
watch这个repo大多是为了获取hosts的更新而不是为了收到这种issue里的讨论的吧
chat room的初衷似乎就是为了更广泛的话题讨论
希望repo中不要讨论过多与本项目无关的内容
希望大家不要吵起来了

**Comment by Too-Naive** [comment]
我操 这还怪我了 我刹住这种风气 然后ls还说我不对???
讲道理啊 Excuse me?

**Comment by redapple0204** [comment]
@Shineee 2.x版本x好像没有限制，不知到什么时候药丸

**Comment by racaljk** [comment]
@Too-Naive 文明点可好

**Comment by sunqb** [comment]
-- 我欣赏技术牛脾气坏的人，这种人心思都很善良，都很好交往，交往。。。。
