### ISSUE TITLE
Add new hosts

### ISSUE THREAD

**Issue by soakit** [racaljk/hosts#529]
#google firebase
220.255.2.153 securetoken.googleapis.com
220.255.2.153 firebasestorage.googleapis.com
64.233.188.121 code.getmdl.io
#google blogspot
220.255.2.153 program-think.blogspot.com
220.255.2.153 developers.googleblog.com

**Comment by Too-Naive** [comment]
为何不用pr呢。。。

**Comment by soakit** [comment]
fork的项目太多了, 前儿还删了一批呢。。

**Comment by Too-Naive** [comment]
.......

**Comment by theratlesnake** [comment]
@Too-Naive 请问下，为啥我ping【program-think.blogspot.com】的ip是172开头的，而楼主这个220.255.2.153 是怎么弄来的哦？

**Comment by imknown** [comment]
@theratlesnake @soakit 不要在这个项目中, 讨论 `program-think` 这个人.

**Comment by sqc1999** [comment]
这算是挖坟吗 😄

**Comment by theratlesnake** [comment]
好吧，其实我只是想请教一下，如何把一个网站的所有可用ip挖出来，然后自己填入hosts里，有方法吗？各位大神

**Comment by sqc1999** [comment]
@theratlesnake 你这样说得有点模糊啊。。找IP的话之前已经有不少issue讨论过了 #685

**Comment by theratlesnake** [comment]
@sqc1999 好的，我去看看，另外，还有一个问题，就是youtube可以打开，但是播放不了，有办法解决吗？

**Comment by sqc1999** [comment]
@theratlesnake 这个在[Wiki](https://github.com/racaljk/hosts/wiki/The-hosts-FAQ#%E4%B8%BA%E4%BB%80%E4%B9%88-github-%E6%9C%89%E6%97%B6%E6%89%93%E5%BC%80%E7%BC%93%E6%85%A2%E7%94%9A%E8%87%B3%E6%89%93%E4%B8%8D%E5%BC%80)中也有说明了除非利用SNI proxy之类的第三方代理，是没有办法解决的。

**Comment by theratlesnake** [comment]
@sqc1999  哦哦！谢谢
