### ISSUE TITLE
Can't connect to 103.7.200.79(www.google.com)  now

### ISSUE THREAD

**Issue by K-Guan** [racaljk/hosts#53]
Do only I have this issue? @racaljk Could you fix this?
![screenshot from 2015-10-16 21-47-16](https://cloud.githubusercontent.com/assets/13862535/10543206/ab5a6ddc-744f-11e5-9946-aa50c297818d.png)

**Comment by andytimes** [comment]
一个多小时前，push了hosts，后来发现没push上，原因是push的时候没输入账号密码、、、因为在家惯用ssh连接。这个Google IP被封锁真的是可惜了，dl.google.com之前下载可以达到宽带最高速度，刚刚试了一下，速度很悲催

**Comment by K-Guan** [comment]
@andytimes 哦，看到新commit了。我试试看再说吧。

**Comment by K-Guan** [comment]
@andytimes 不错，至少能用了。我是不是应该写个脚本自动检测哪个IP挂了然后自动提示方便即时修复？ :smile:
