### ISSUE TITLE
哎~? gist.github.com 变成废猫了?

### ISSUE THREAD

**Issue by imknown** [racaljk/hosts#535]
https://gist.github.com 打不开

**Comment by racaljk** [comment]
打开gist都是随缘，还不如创建private repo

也可以用类似的网站替代[[+]](http://codepad.org/)

**Comment by imknown** [comment]
嗯 谢谢 我主要是 看老外写的代码 Y _ T

**Comment by imcaffrey** [comment]
codepad会不会定期清空东西啊
paste.ubuntu.com会清东西真是心烦= =

**Comment by mraandtux** [comment]
以下测试没问题，联通广东，估计ISP问题：
192.30.253.119 gist.github.com
（已包含在本h05t5中，本人因安全为由不用Push）

**Comment by imcaffrey** [comment]
安全为由 :fearful:

**Comment by andytimes** [comment]
192.30.253.118

安徽电信可用。

貌似 gist 存了很多不和谐内容，既然 block 那么快，暂时就不要解锁了。

关于代码片段，貌似国内也有很多站点提供类似服务。
上次发现 CSDN 也提供了代码片段 https://code.csdn.net/snippets_manage 还没仔细用，但觉得还不错。

**Comment by andytimes** [comment]
CSDN 代码片段效果：https://code.csdn.net/snippets/1712184

**Comment by imknown** [comment]
我在两台 Win10 已测试 两个大连联通宽带, 都打不开.
但是 手机 连接 这两个 宽带 就可以打开. 为什么...

P.S.: 大连联通4G 或者 大连移动4G 也可以打开... :crying_cat_face:

**Comment by imcaffrey** [comment]
csdn 必须得登陆……

**Comment by racaljk** [comment]
@imcaffrey 应该不会清空吧，现在都能访问2011年创建的snippet

**Comment by imknown** [comment]
坑爹 192.30.253.119 自己好用了, 还是需要写的.. #539
