### ISSUE TITLE
可否在host文件添加google patents和dropbox的访问？

### ISSUE THREAD

**Issue by cahndengbin** [racaljk/hosts#537]

**Comment by andytimes** [comment]
解锁新技能的后果就是，遇到更 BUG 的 BOSS。@racaljk

**Comment by racaljk** [comment]
@andytimes 怎么了

**Comment by andytimes** [comment]
@racaljk 只是开个玩笑，觉得解锁网站太多，好像会让 GFW 关注，感觉不是很好，当然只是猜测一下。

dropbox IP 之前好像都封得差不多了，如果没有新开的 IP 段，更新起来应该比较痛苦。所以你怎么看这个 issue？

**Comment by racaljk** [comment]
@andytimes 我觉得如果有人贡献再添加吧，我反正是找不到Dropbox ip Orz...
