### ISSUE TITLE
丢盒子ip

### ISSUE THREAD

**Issue by panpando** [racaljk/hosts#538]
网页可正常使用，客户端还要抓抓地址

218.254.1.13 db.tt
218.254.1.13 dropbox.com
218.254.1.13 m.dropbox.com
218.254.1.13 www.v.dropbox.com
162.125.66.1 www.dropbox.com
108.160.172.193 d.dropbox.com
108.160.172.193 d.v.dropbox.com
108.160.172.193 api-d.dropbox.com
108.160.172.237 api.dropboxapi.com
108.160.172.237 api.dropbox.com
108.160.172.237 api.v.dropbox.com
108.160.172.237 api-notify.dropbox.com
108.160.172.233 www.dropboxstatic.com
104.16.100.29 cfl.dropboxstatic.com
108.160.172.201 dbxlocal.dropboxstatic.com
199.47.217.36 api-content.dropbox.com
199.47.217.36 api-content-photos.dropbox.com
108.160.172.207 photos.dropbox.com
162.125.34.129 bolt.dropbox.com
162.125.17.129 photos-thumb.dropbox.com
162.125.17.129 photos-thumb.x.dropbox.com
199.47.217.97 block.dropbox.com
199.47.217.97 block.v.dropbox.com
54.230.214.100 cf.dropboxstatic.com
54.192.108.33 client-cf.dropbox.com
45.58.69.38 dl.dropbox.com
219.76.4.4 dl-web.dropbox.com
45.58.69.37 dl.dropboxusercontent.com
162.125.18.2 photos-1.dropbox.com
162.125.18.2 photos-2.dropbox.com
162.125.18.2 photos-2.dropbox.com
162.125.18.2 photos-3.dropbox.com
162.125.18.2 photos-4.dropbox.com
162.125.18.2 photos-5.dropbox.com
162.125.18.2 photos-6.dropbox.com
54.192.213.118 status.dropbox.com
54.192.213.118 marketing.dropbox.com
54.192.213.118 blogs.dropbox.com
54.192.213.118 forums.dropbox.com
54.192.213.118 snapengage.dropbox.com
162.125.32.129 notify.dropbox.com
108.160.172.236 client-lb.dropbox.com
108.160.172.236 client-web.dropbox.com
108.160.172.236 client.dropbox.com
108.160.172.236 client.v.dropbox.com
219.76.4.4 dl-debug.dropbox.com
219.76.4.4 log.getdropbox.com

**Comment by myguybetter** [comment]
You used 2 sniproxy ip?

**Comment by kang000feng** [comment]
@myguybetter 你是指哪两个? 谢谢

**Comment by beyondroot** [comment]
218.254.1.13  219.76.4.4

**Comment by myguybetter** [comment]
@panpando As what @beyondroot said.

**Comment by kang000feng** [comment]
@beyondroot @myguybetter 第二个已经用不了了 403

**Comment by myguybetter** [comment]
@kang000feng No, it is still usable. Errors like '403 forbidden' or 'ERROR: The requested URL could not be retrieved' are unique points which shown by this kind of proxies. You can see more from 219.76.4.3, 219.76.4.11, 182.239.95.136, 182.239.127.136. You can add more domains which support https with these ips into your hosts and you will find they are working perfectly.

**Comment by kang000feng** [comment]
@myguybetter thank you. it works.
