### ISSUE TITLE
不能使用Google play 商店

### ISSUE THREAD

**Issue by LyCrystals** [racaljk/hosts#54]
安卓5.1，更换过hosts后不能使用play商店

**Comment by K-Guan** [comment]
好像网页没问题

**Comment by LyCrystals** [comment]
网页没问题，play商店，Gmail客户端，文档，drive，不能使用。

**Comment by K-Guan** [comment]
话说我的_Checker Plus for Gmail_ （自动提示新邮件的Chrome插件）可以使用。

**Comment by LyCrystals** [comment]
网页版确实可用，Gmail客户端不能用（设备Mi3，Android 5.1，cm12，1015每夜版）

**Comment by whinamp** [comment]
iOS9修改hosts已经不管用了吗？还是我应该重刷？

**Comment by K-Guan** [comment]
这样的话我就没法测试了。可是这不正常呀。

**Comment by LyCrystals** [comment]
如果有安卓机可以测试一下,如果没有的话可以教我一下怎么抓log,我来测试

**Comment by andytimes** [comment]
Google Play已经无法使用hosts访问了，需要去除hosts中无用规则，把android.clients.google.com
去除基本就没问题了，但是是否影响网页版这个要测试才行，如果你是挂V|||PN，需要清理hosts，如果是用ss就没问题

LyCrystals <notifications@github.com>于2015年10月17日周六 下午3:19写道：

**Comment by K-Guan** [comment]
@andytimes 等等，什么叫 _hosts中无用规则_ ？既然无用干嘛还放着？（话说我刚刚才注释掉了OpenShift的hosts）……

**Comment by andytimes** [comment]
有一些hosts规则对网页版有用，对手机客户端却有很大的害处。openshift这个不用注释，直接删除就OK，一般解封的网站是不会再次被封锁了

Kevin Guan <notifications@github.com>于2015年10月17日周六 下午3:29写道：

**Comment by K-Guan** [comment]
原来还有这个问题，那么openshift的hosts我就去删掉好了。

**Comment by andytimes** [comment]
嗯嗯，android.clients.google.com也帮忙删除吧，刚刚试了一下，确实这个是没什么用的！

Kevin Guan <notifications@github.com>于2015年10月17日周六 下午3:38写道：

**Comment by K-Guan** [comment]
唉？刚刚看了下好像当时就删掉了……好吧我够晕的。

**Comment by andytimes** [comment]
64.233.162.84 v1.lscache1.c.android.clients.google.com类似这样的规则都可以删除

Kevin Guan <notifications@github.com>于2015年10月17日周六 下午3:42写道：

**Comment by iKirby** [comment]
网页版能用但客户端不能用好像是因为浏览器支持SNI，客户端不支持
https://en.wikipedia.org/wiki/Server_Name_Indication

**Comment by andytimes** [comment]
@LyCrystals Google Play用hosts的基本不可能了，sn域名都被污染了，而且sn用得还是固定IP，基本无解。只能挂V|||PN或ss，现在的IP只能勉强打开看看评论之类，能够看到软件截图的都很少。

电脑上下载apk给手机安装比较方便，
方法：在chrome浏览器上安装APK Downloader，里面有教程，Device ID的获取，可以下载教程附带的APK，在手机上打开就行了，之后在电脑上打开Google Play，挂上代理，之后下载把安装包弄到手机里就OK了，当然会用adb install就更方便了。


抓包可以在Windows下用Fiddler4，教程：http://blog.csdn.net/roland_sun/article/details/30078353
不过手机挂代理，Fiddler4就不好抓包了，所以也可以找一些vpn或ss的软件，在WIFI下共享给手机，然后用软件监听

**Comment by LyCrystals** [comment]
@andytimes 谢谢啦
