### ISSUE TITLE
HumbleBundle失效

### ISSUE THREAD

**Issue by LuHaoPeng** [racaljk/hosts#540]
[HumbleBundle](https://www.humblebundle.com) 貌似是失效了，昨天还能用的。

> \# HumbleBundle Start
> 5.153.35.171	humble.pubnub.com
> 198.41.186.33	humblebundle.com
> 203.69.81.33	humblebundle-a.akamaihd.net
> 52.36.140.12	pubnub.com
> 74.125.34.32	www\.humblebundle\.com
> \# HumbleBundle End

**Comment by racaljk** [comment]
四川电信访问正常.
