### ISSUE TITLE
不知道为啥还是用不了

### ISSUE THREAD

**Issue by gaqzcb** [racaljk/hosts#541]
您好，感谢您开issue来反馈信息，在提交前，请确保您已经检查了以下内容!
- 如有关"Google无法连接/"YouTube视频无法播放"等问题 请参阅[常见问题解答](https://git.io/vrHaS)
- 已经阅读了[Wiki页面](https://github.com/racaljk/hosts/wiki)
- 已经搜索过之前的相关[issues](https://github.com/racaljk/hosts/search)
- 如果是报告问题，请确认问题可以复现并且没有重复报告同一个问题；如果是向hosts提供新的信息，请确认所提供信息的来源以及相关许可协议

如果您有其他附言，例如问题只在某个页面发生，或者是一般性讨论、提出新功能，请一定添加

或者您也可以卖个萌

我们同时有一个[Gitter Room](https://gitter.im/racaljk/hosts)，以及一个[在coding上的镜像](https://coding.net/u/scaffrey/p/hosts)

**Comment by racaljk** [comment]
我只能猜测你是google无法使用，如果确保hosts已经复制到本地hosts文件中且格式没问题，请使用https进行访问 e.g. https://www.google.com.hk

~~另附[[+]](https://book.douban.com/subject/25806793/)~~
