### ISSUE TITLE
跪求，谁有cnAnonymous 的最新folk大约7月20号左右的

### ISSUE THREAD

**Issue by mzryry** [racaljk/hosts#542]
不知道什么情况删了，我想folk一个副本自己修改，谢谢

**Comment by andytimes** [comment]
看情况是没有了，我在 Github 上全文搜索 "https://github.com/cnAnonymous" 没有发现 fork，好像只有修改过的版本。https://github.com/joeshu/For-ADM  你参考这个修改吧。

**Comment by mzryry** [comment]
找了很久非常感谢  对比一下 cnAnonymous 这hosts 中的错误66.29.212.110      w3schools.com
还有缺少myactivity.google.com 等，还有建议谷歌香港和谷歌台湾的IP采用备用，××. 2.153有时抽风，可以用谷歌台湾避难

**Comment by jetbe** [comment]
cnAnonymous为什么没有啦？

**Comment by Too-Naive** [comment]
抢不过本repo自己和谐了

-------- Original message --------

**Comment by lautis0503** [comment]
https://github.com/superliaoyong/hosts
7-10
