### ISSUE TITLE
我的 Windows 没有安装到 C盘...

### ISSUE THREAD

**Issue by imknown** [racaljk/hosts#544]
是否可以把 [`README.md`][README] 里面的
``` txt
C:\Windows\System32\drivers\etc\hosts
```
换成
``` txt
%systemroot%\System32\drivers\etc\hosts
```
或者 
``` txt
%windir%\System32\drivers\etc\hosts
```
以匹配 [`windows.bat`][WinCmd] .

[README]: https://github.com/racaljk/hosts/blob/master/README.md#windows
[WinCmd]: https://github.com/racaljk/hosts/blob/master/tools/windows.bat#L46-L48

**Comment by Too-Naive** [comment]
还不如用hoststool

-------- Original message --------

**Comment by imknown** [comment]
en, thx.
