### ISSUE TITLE
请修改维基百科的 hosts

### ISSUE THREAD

**Issue by techyanWP** [racaljk/hosts#548]
在 hosts 文件中，维基百科的手机版页面 zh.m.wikipedia.org 被指向 198.35.26.97 。维基媒体基金会已经不再区分桌面版和手机版 IP ，所有访问都指向了 < https://zh.wikipedia.org/wiki/Help:%E5%A6%82%E4%BD%95%E8%AE%BF%E9%97%AE%E7%BB%B4%E5%9F%BA%E7%99%BE%E7%A7%91#Hosts.E6.96.87.E4.BB.B6 > 中提到的三个 IP 。请将其统一为 198.35.26.96 。谢谢。

（南海是中国的那是什么鬼。。

**Comment by Too-Naive** [comment]
对于这种情况 您可以提交pull request
