### ISSUE TITLE
如何把hosts添加到360自定义Host中

### ISSUE THREAD

**Issue by atumu** [racaljk/hosts#549]
先说下360路由器，它支持自定义Host，可以不必在每台设备做映射，方便配置；但只支持1000行，我平时只需要google来搜索，也没有国外朋友，所以像亚马逊、雅虎之类的网站接触会很少，请问怎么筛选hosts来满足日常搜索？ 能否维护一个简化版?

**Comment by Too-Naive** [comment]
其实hosts有分块 google部分留下即可… 不过我觉得 从网站的名字就可以判断出大体意思了… 从分离出的google域名再精简即可…
我想 这应该不是什么难事
维护个精简的hosts需要多一份工作 况且从现在来看的话 应该算是少数人的要求吧


-------- Original message --------

**Comment by imknown** [comment]
用到啥域名 就从 [hosts][hosts] 找出来?
只有搜索引擎的话, 应该不会很多吧. (雾
[hosts]: https://github.com/racaljk/hosts/blob/master/hosts#L392

**Comment by Too-Naive** [comment]
Google先找出来 然后那些比如doc的不会用到的话就删掉 我的意思是这个

-------- Original message --------

**Comment by atumu** [comment]
嗯 能用 谢谢

**Comment by racaljk** [comment]
每个块都有这样的标签:
# Amazon AWS Start
# Amazon AWS End
可以按你所说的按需添加
