### ISSUE TITLE
github的资源无法下载是什么原因

### ISSUE THREAD

**Issue by ElfSundae** [racaljk/hosts#562]
例如项目下的 release 文件，`https://github-cloud.s3.amazonaws.com/releases/...` 解析到的 IP `54.231.34.41` 能 ping 通，但是每次下载到 10% 左右就不下了，是什么原因呢？

**Comment by Too-Naive** [comment]
国际出口爆炸是正常的事情 请使用vpn

**Comment by ElfSundae** [comment]
好吧
