### ISSUE TITLE
windows.bat无法使用

### ISSUE THREAD

**Issue by fangxu622** [racaljk/hosts#563]
![1](https://cloud.githubusercontent.com/assets/16681534/17406637/da1ed512-5a96-11e6-83ac-63c3dbe865dc.png)
![2](https://cloud.githubusercontent.com/assets/16681534/17406640/dcf4ffc8-5a96-11e6-9358-4b0bc5b8e101.png)
tool 工具 windows.bat 无法使用，可能跟我的电脑有关，但在另外一台电脑上能用

**Comment by Too-Naive** [comment]
对于windows 我们有[Hosts Tool](https://github.com/HostsTools/Windows)
您可以选择使用exe工具 而弃用~~过时的~~bat脚本
