### ISSUE TITLE
我按步骤操作，还是上不了google.com

### ISSUE THREAD

**Issue by hongzhensheng** [racaljk/hosts#569]
我按步骤操作，还是上不了google.com

**Comment by Too-Naive** [comment]
see also:https://github.com/racaljk/hosts/wiki/%E4%B8%BA%E4%BB%80%E4%B9%88%E6%9B%B4%E6%96%B0hosts%E5%90%8E%E8%BF%98%E6%98%AF%E6%97%A0%E6%B3%95%E4%BD%BF%E7%94%A8Google%E5%8F%8A%E7%9B%B8%E5%85%B3%E6%9C%8D%E5%8A%A1%3F

**Comment by laodcn** [comment]
用https（SSL）了么？
如： https://www.google.com/ncr
        https://www.google.com.hk/ncr

**Comment by hongzhensheng** [comment]
今天试一下了~ 可以了 
thx~ :smile:
