### ISSUE TITLE
Yahoo奇摩新闻手机版域名缺失

### ISSUE THREAD

**Issue by Makebignew** [racaljk/hosts#573]
68.142.240.68   tw.mobi.yahoo.com
且该域名已被dns污染，希望能尽快完善

**Comment by Makebignew** [comment]
另外y.analytics.yahoo.com  这条域名全球DNS解析已经host not found，没有存在的必要

**Comment by DaleXiao** [comment]
116.214.11.98 tw.mobi.yahoo.com

but my questions is who is still using yahoo...

**Comment by Too-Naive** [comment]
233
