### ISSUE TITLE
可以添加qq屏蔽广告的host吗？

### ISSUE THREAD

**Issue by liguge** [racaljk/hosts#574]
0.0.0.0 fodder.qq.com
0.0.0.0 adshmct.qq.com
0.0.0.0 hm.l.qq.com
0.0.0.0 adshmmsg.qq.com
0.0.0.0 q.i.gdt.qq.com
0.0.0.0 v.gdt.qq.com
0.0.0.0 s.gdt.qq.com
0.0.0.0 imc.l.qq.com
0.0.0.0 client.show.qq.com
0.0.0.0 user1.game.qq.com
0.0.0.0 c.gdt.qq.com
0.0.0.0 q.i.gdt.qq.com
0.0.0.0 tj.b.qq.com
0.0.0.0 dir.minigame.qq.com
0.0.0.0 if.mingxing.qq.com
0.0.0.0 showwxml.qq.com
0.0.0.0 2052.flash2-http.qq.com
0.0.0.0 img1.sj.qq.com
0.0.0.0 ws.sj.qq.com
0.0.0.0 scdown.qq.com
0.0.0.0 img1.gtimg.com
0.0.0.0 pinghot.qq.com
0.0.0.0 pingfore.tenpay.com
0.0.0.0 jqmt.qq.com
0.0.0.0 gu.qlogo.cn
0.0.0.0 py.qlogo.cn
0.0.0.0 py2.qlogo.cn
0.0.0.0 bugreportv2.qq.com
0.0.0.0 ex.qq.com
0.0.0.0 cgi.connect.qq.com

这个是代码~

**Comment by izhangzhihao** [comment]
同求去广告版

**Comment by Too-Naive** [comment]
我认为是没有必要的: `:statue_of_liberty:最新可用的google hosts文件`
不过还是@racaljk 请老大给出指导意见

**Comment by beyondroot** [comment]
给个地址 https://github.com/vokins/yhosts

**Comment by racaljk** [comment]
可以新建branch维护屏蔽广告的hosts，但是贡献的屏蔽广告目前还太少没有必要这样做。

**Comment by laodcn** [comment]
不建议使用hosts来屏蔽广告，因为会加剧hosts的维护成本，还有就是可能会出现网页乱版情况（我以前遇到过）再者就是等于屏蔽了某些国内域名了（虽然只是广告用的域名）
