### ISSUE TITLE
请问能否在README.md中添加以下这段话？

### ISSUE THREAD

**Issue by cjsoft** [racaljk/hosts#575]
请问能否在README.md中添加以下这段话？

> ## 有关中国的互联网
> 网络审查在各个国家都普遍存在着，它并不仅存在于中国。在全球的局势对中国都不利的当下，当局会过滤掉影响、危害到中国长远发展的信息，此时国家安全的意义更加重大。
> 
> 互联网上存在着大量终究不现实的、不客观的，甚至自相矛盾的抹黑当局政府言论，它们背后一般有西方政府或非政府组织资金支持。这些媒体包括但不限于一些港媒、境外网站。
> 
> 我们希望您能在遇到此类言论和见解时，不要不加思考地、情绪一度被煽动而不能克制地、盲目地相信这些片面或者歪曲事实的东西，而是要事实求是地思考，要摆脱情绪绑架的怪诞思维去理解。
> 
> 我们需要了解到，中国的发展总基调是“稳中求进”，中国社会的最核心问题就是稳定。失去稳定的中国将会是一盘散沙，面临分裂和肢解的危险。我们希望您了解当今中国发展的根本保证是什么，发展的过程中哪部分是主旋律，哪些是噪音；哪些是进取的，哪些是会开历史倒车的。
> 
> 我们应该清醒和全面地认识问题，偏信西方媒体的言论、缺乏对国家的信任是不可取的。您的数据安全和隐私对您尤为重要。若这些信息不应当被西方掌握时，它对国家和民族的命运更为重要。出于此原因，当局可能会限制您的行为，我们不会也无法干预当局的任何政策和决定。
> 
> 所以，我们希望您在使用此服务时，不要盲目地攻击当局的做法。

此段话的原作者是netsh.org，我已取得原作者的授权：
![](http://i1.piimg.com/567571/6d8a66d80a4c4d9e.png)
![](http://cjsoft.me:81/S60813-09184699.jpg)

racaljk/hosts的README.md使用CC BY-NC-SA 4.0，是满足要求的。

**Comment by racaljk** [comment]
你完全可以把这段话保存在wiki中，同时在README.MD->更多中超链接至wiki。全部复制到README.MD太过臃肿而且不合README.MD主要是介绍hosts如何使用的主题。

**Comment by cjsoft** [comment]
谢谢！:smile:

**Comment by racaljk** [comment]
:smile: 嘛...反正现在README.MD已经够乱了，再多加一句话也没什么

**Comment by cjsoft** [comment]
我觉得这段话超级帅而且有意义，因为涉及项目立场问题，所以先发个issue来问问。已新建wikipage，稍后我发pr加链接

**Comment by cjsoft** [comment]
#576

**Comment by racaljk** [comment]
~~不过我还是忍不住要说一下这段话把国家等同于政府本质上是错误~~

**Comment by cjsoft** [comment]
~~中国嘛~~

**Comment by vizogood** [comment]
多年老网民表示理解，但是希望建立透明的互联网审查制度，eg：跳转到官方声明页面而不是一味遮掩，这样并不利于国家发展和稳定。

**Comment by dajbd** [comment]
对此描述，我个人表示疑问。


1、很多抹黑当局的言论（这个的确是存在的现象，我没争议）

2、除了抹黑当局的现象，我们再想想，除了抹黑，我问一句：当局自身难道没有问题？

3、全球的局势对中国都不利的当下（不能摆个观点在，不去论证这个观点）

4、面对开放的网络环境，当局在做封锁的工作，美其名曰是避免别人掌控到我们的信息，影响我们的发展。我问一句，USA是否会考虑CN过渡掌控USA的信息，建立一道 土蔷？建立封锁？

5、我们有着历史悠久的文明，但是，我们老百姓是被奴役了几千年。我们是否继续为了好好活着，继续忍气吞声？我们可否争取一点言.论`自.由？


这是每个人的认知的差异，形成观念的差异，可以讨论各自的见解。
我的这个发言是为了避免一面之词，提出另一种另一种看法。
如果有人喷我，我不会在意。
如果一起讨论，非常欢迎。

**Comment by racaljk** [comment]
@dajbd 台面上政治正确是活下来的保证，所以另一方面的声音放到qq群地方吧

**Comment by dajbd** [comment]
这么说，我就理解了。
谢谢。

**Comment by BROBIRD** [comment]
@dajbd 

> 当局在做封锁的工作，美其名曰是避免别人掌控到我们的信息，影响我们的发展。
这句话已经说明你根本没有理解墙是用来干什么的，你还是需要学习一个

**Comment by Too-Naive** [comment]
To reply @dajbd 

>避免别人掌控到我们的信息

首先 这个说法就是错误的 显然你忘记了是谁被屏蔽

> 我们可否争取一点言论自由？

任何言论自由都是相对的 没有什么绝对的言论自由

我是见识得多了 身经百战了 有些事情之所以没有摆在台面上 是因为没有必要 与其一直闹腾 不如在背后悄悄的做好

-----

**倘若当局这样做没有意义** 
* 为什么 某高校可以直连国外网站？
* 为什么 某高校设立班级ss服务器？
* 为什么 某高校提供vpn？

---
所以 你还是 Too young too simple啊 你还是要提高自己的知识水平 识得不识得啊？

**Comment by dajbd** [comment]
@BROBIRD 我当然知道，墙主要是为了国内维稳、为了控制言论。

**Comment by dajbd** [comment]
我说“避免别人掌控到我们的信息”，仅仅因为帖子原文，就是这个意思。

**Comment by BROBIRD** [comment]
@dajbd 那只是很小的一部分。主要的作用还是净化社会（文化和政治）环境。如果你知道和平演变和颜色革命你就应该理解为什么政府要这么做。

**Comment by dajbd** [comment]
@Too-Naive 即使你很吊，你这种教育别人的方式，是否考虑换个说话的语气？
摆出一副自己身经百战样子，别人都是蠢的跟猪一样？
言论自由当然是相对的，但是我们的言论、报纸、图书、网络、电视处于什么状态？

能不能摆出平等交流的样子，不要一副大爷的模样。
各种装逼的觉得都还好，但是这样教训别人的方式，合适吗？

**Comment by Too-Naive** [comment]
@dajbd 这梗还开不起玩笑了咯？

**Comment by BROBIRD** [comment]
@dajbd 看来你不是膜法师啊，算了= =@Too-Naive

**Comment by Too-Naive** [comment]
所以我还是不理解我他妈一句话都没有骂人搞得好像我操了他十八代祖宗一样？

**Comment by Ir1d** [comment]
不是每个人都那么喜欢玩梗 充分了解到你说的具体是什么意思

**Comment by Too-Naive** [comment]
所以你的意思就是我的错咯？

**Comment by Ir1d** [comment]
怎么说呢 大概就是 naive 这个词不属于 3500 词吧
