### ISSUE TITLE
强烈建议恢复以前linux更换hosts的一条命令

### ISSUE THREAD

**Issue by redapple0204** [racaljk/hosts#577]
以前只用输一条命令，结果现在却要打开hosts，复制里面的内容，sudohosts文件，复制进去，多麻烦啊！

**Comment by Stephen-Chen** [comment]
你试试看这个:
```bash
$ sudo wget https://github.com/racaljk/hosts/raw/master/hosts -P /etc/ -N
```

**Comment by Stephen-Chen** [comment]
@redapple0204

**Comment by imcaffrey** [comment]
https://github.com/racaljk/hosts/pull/364/files

**Comment by redapple0204** [comment]
@Stephen-Chen @imcaffrey 谢谢你们两位！

**Comment by Too-Naive** [comment]
...用脚本不好吗

**Comment by Too-Naive** [comment]
似乎重担又要交给我了？(雾

-------- Original message --------

**Comment by Too-Naive** [comment]
我咸鱼两个月了

-------- Original message --------
