### ISSUE TITLE
IOS怎么自动更新host呢？

### ISSUE THREAD

**Issue by iam3ddy** [racaljk/hosts#578]
IOS有什么软件能自动更新您的host吗？

试了cydia里的AdBlock 2 v1.1不成功

**Comment by Too-Naive** [comment]
没有自动更新工具 有辅助更新工具
https://github.com/HostsTools/OSX


-------- Original message --------

**Comment by iam3ddy** [comment]
@Too-Naive 哪是OSX用的。不是IOS (iPhone/iPad)

OS X 还是Switchhost好用 
https://oldj.github.io/SwitchHosts/

**Comment by Too-Naive** [comment]
阿 不好意思 看错了
ios上的 也要越狱才可以用吧


-------- Original message --------

**Comment by iam3ddy** [comment]
我已经越狱了。
还是没找到可用的越狱软件。
如果有个repo再使用Flipswitch能更新
像Repo “Http://xkaosx.x10.MX”里的Basic Adblocker 9软件

**Comment by Too-Naive** [comment]
不过 不用那么经常换hosts吧

-------- Original message --------

**Comment by iam3ddy** [comment]
@Too-Naive 是的。只是更新方便，不需要电脑。

**Comment by Too-Naive** [comment]
文件管理器

-------- Original message --------

**Comment by fluviusmagnus** [comment]
不怕麻烦的话，我记得越狱的 iOS 里可以用终端。

**Comment by Too-Naive** [comment]
问个题外话 ios有没有busybox阿

-------- Original message --------

**Comment by fluviusmagnus** [comment]
@Too-Naive 应该是有办法用的，我记不得了，上次越狱已经是快五年前的事了……

**Comment by DaleXiao** [comment]
IFTTT

**Comment by michaelmou** [comment]
我在ios装了个git，用来更新，然后copy到etc目录
