### ISSUE TITLE
可以加入dmm等网站的hosts？

### ISSUE THREAD

**Issue by Henta1** [racaljk/hosts#583]
来自其他网站 不确定是不是有版权保护
106.186.27.62 www.dmm.com
106.186.27.62 www.dmm.co.jp
106.186.27.62 sp.dmm.com
106.186.27.62 sp.dmm.co.jp
106.186.27.62 actress.dmm.co.jp
106.186.27.62 book.dmm.com
106.186.27.62 book.dmm.co.jp
106.186.27.62 www.akabeesoft2.com
106.186.27.62 www.akabeesoft3.com
106.186.27.62 www.akatsukiworks.com
106.186.27.62 www.alicesoft.com
106.186.27.62 www.cosmiccute.com
106.186.27.62 www.hibiki-site.com
106.186.27.62 www.minori.ph
106.186.27.62 erogamescape.ddo.jp
106.186.27.62 tenco.cc
106.186.27.62 wheel-so

**Comment by Henta1** [comment]
http://www.crystalacg.com/list/
来源

**Comment by Too-Naive** [comment]
为何不直接提交pull request-------- Original message --------

**Comment by evolot** [comment]
我觉得在不影响加载速度的前提下 把GFWl屏蔽了的都该加上 说不定以后那天用到了呢

**Comment by racaljk** [comment]
四川电信正常访问

**Comment by aofall** [comment]
>您输入的IP: 106.186.27.62
日本东京都东京 linode.com
时区：Asia/Tokyo UTC+9 该地区中心经纬度：139.6917064 / 35.6894875
该 IP 段为 IDC 机房使用，可能包括部分骨干网数据。购买此数据
该 IP 为代理的概率为：40%

看见linode用脑子想想都知道是反代

dmm不是防火墙屏蔽，是主动屏蔽除日本以外的地区
