### ISSUE TITLE
可以增加 nytimes.com 的host吗？

### ISSUE THREAD

**Issue by liuyutao** [racaljk/hosts#588]
可以增加 nytimes.com 的host吗？

**Comment by laodcn** [comment]
纽约时报并不支持https，就算支持，那也得有支持的对应ip

**Comment by racaljk** [comment]
..暂时没找到可用IP，只有花钱买vps架设飞机了

**Comment by Too-Naive** [comment]
![](https://cloud.githubusercontent.com/assets/16496671/14945197/49ed17c6-103e-11e6-80b8-f9f6b6dd33be.gif)~~前排售卖服务器~~

**Comment by imknown** [comment]
确实 试了一下, 确实没有 ip, 连接都超时..

**Comment by racaljk** [comment]
找到了nytimes的手机版..
