### ISSUE TITLE
谷歌仍然各种不能用。。

### ISSUE THREAD

**Issue by Usb233** [racaljk/hosts#59]

**Comment by K-Guan** [comment]
山东电信，Arch Linux，Google Chrome 46.0.2490.71 表示正常。

**Comment by andytimes** [comment]
请具体描述一下，有哪些不能用

**Comment by Usb233** [comment]
Android 。Google搜索，Google地图,keep,Wikipedia, Twitter等等都不起效果哈

**Comment by andytimes** [comment]
Google地图（中国）并没有被封锁，Wikipedia和Twitter（手机版网页）一直没什么问题。下载最新的hosts，然后保证换行符是LF。

**Comment by Usb233** [comment]
你指的是网页版吧？我是用客户端的 
还有Android上怎么看换行符格式..

**Comment by Roller44** [comment]
Android 可以直接下载这个 hosts 文件的吗？我都是在电脑上复制下来再转格式然后才塞进手机里的。


 

-------- 原始邮件 --------
发件人：Usb <notifications@github.com>
时间：周日 10月18日 10:23
收件人：racaljk/hosts <hosts@noreply.github.com>
主题：Re: [hosts] 谷歌仍然各种不能用。。 (#59)

**Comment by Usb233** [comment]
我以前改hosts也是直接用手机覆盖的诶

**Comment by andytimes** [comment]
最好先复制到电脑，用 文本编辑器 转换 换行符 再放入手机。（具体怎么操作网页搜索一下就行）

也可以在手机上访问这个hosts项目主页，点击README -> hosts <-这个链接，用UC浏览器直接保存为网页，网页格式选择txt，之后把.txt后缀去掉，就OK了。

如果是点击Download ZIP，里面的hosts文件默认是CRLF（Windows）

我也发现手机的Inbox by Gmail连接有问题，这个有些无解，暂时就用网页浏览器打开移动版gmail吧。

**Comment by Usb233** [comment]
按你说的做了，但Android还是不行。
window倒是可以~

**Comment by andytimes** [comment]
@Usb233 是IP问题，刚刚在手机上测试了一下，换了一个IP就正常了，我在线编辑下hosts。

**Comment by kightdgithub** [comment]
��������
������4727 
������12
����240
��������9
����170
����53.1

------------------ �������� ------------------


    
        ������: Andy Deng  <notifications@github.com>;
    
    
        ��������: 2015-10-18 10:57:23
    
    
        ������: racaljk/hosts  <hosts@noreply.github.com>; 
    
    
        ����: (��); 
    
    
        ����: Re: [hosts] ���������������������� (#59)
    

�������������������� ���������� ���� ������ ��������������������������������������������  ����������������������hosts��������������README -> hosts <-������������UC����������������������������������txt��������.txt������������OK����  ����������Download ZIP��������hosts����������CRLF��Windows��  ��������������Inbox by Gmail������������������������������������������������������gmail����  ��Reply to this email directly or view it on GitHub.

**Comment by andytimes** [comment]
@kightdgithub 乱码
