### ISSUE TITLE
捐赠算盈利活动吗

### ISSUE THREAD

**Issue by coderstory** [racaljk/hosts#590]
我开发了一个app 也是开源的

使用了你的hosts

软件本身没任何限制 只是关于页面有个捐赠的连接

**Comment by Too-Naive** [comment]
[HostsTools](https://github.com/HostsTools/)
据我所知 上面的那些工具集里面 都是没有包含捐赠链接的

**Comment by coderstory** [comment]
那就换个没协议的...

**Comment by coderstory** [comment]
我感觉非营利性和商业，还是有区别的

**Comment by Too-Naive** [comment]
好的 回头我也去搞一个二维码来捐赠

**Comment by coderstory** [comment]
你会惊喜的发现 你得到了大量的1毛，1分，5毛，1元的捐赠  .....

**Comment by racaljk** [comment]
:sob: 我狭隘的认为算是
