### ISSUE TITLE
hosts是否支持Google Duo

### ISSUE THREAD

**Issue by llsf** [racaljk/hosts#593]
中文： 修改I啊host可以支持google duo？

**Comment by DaleXiao** [comment]
gays...please gays step out to support google duo.

**Comment by Too-Naive** [comment]
![](https://cloud.githubusercontent.com/assets/16496671/17828062/95155038-66ba-11e6-83c3-d2edd5bbcec5.gif)

**Comment by imcaffrey** [comment]
Btw.... Let's welcome the 6666th star. // off topic

**Comment by Too-Naive** [comment]
6666th
![](https://cloud.githubusercontent.com/assets/16496671/17864424/a3501bde-68d0-11e6-8073-8f4c43a8d620.png)
![](https://cloud.githubusercontent.com/assets/16496671/17864444/b5eca42e-68d0-11e6-8bf5-4a01d540fe7d.png)

**Comment by llsf** [comment]
instantmessaging-pa.googleapis.com

**Comment by lfnot** [comment]
#596  i think this would work! 
So let's just duo it!
