### ISSUE TITLE
我感觉 dl.google.com 还是不要加到 hosts 比较好

### ISSUE THREAD

**Issue by imknown** [racaljk/hosts#594]
#589 
很久之前 https://dl.google.com 就可以正常满速下载了.
现在写上去之后 下载速度奇慢, 还经常失败...

**Comment by DaleXiao** [comment]
203.208.40.34 dl.google.com

try this

**Comment by imknown** [comment]
@DaleXiao :laughing: 谢谢你 我试了一下, 错误 405

**Comment by laodcn** [comment]
那我有时间在改回来吧，dl.google.com可能只是少部分地区访问不了

**Comment by Too-Naive** [comment]
我来吧= =
