### ISSUE TITLE
'# Localhost' 分组里面 需不需要 加入 `ip6-localhost`?

### ISSUE THREAD

**Issue by imknown** [racaljk/hosts#595]
用来给 Linux 或者 Android...

``` bash
# Localhost
127.0.0.1	ip6-localhost
```

**Comment by racaljk** [comment]
linxu用户一般都会自定义主机名吧...

**Comment by imknown** [comment]
https://github.com/StevenBlack/hosts/issues/139 :frowning: 懵逼中

**Comment by racaljk** [comment]
至少我现在用的default setting就是这样的,当然如果你觉得很有必要也是可以开PR的

**Comment by imknown** [comment]
@racaljk 嗯 我再查查资料先

**Comment by racaljk** [comment]
@imknown 有没有兴趣加入collaborator,我这里欢迎长期活跃的用户(metabolism..:smile:

**Comment by imknown** [comment]
@racaljk LOL, 谢邀, 荣幸啊~ 有什么具体的要求吗?

**Comment by racaljk** [comment]
@imknown 唯一要求就是保护好github账号,另外希望能尽量帮助解决Issue的问题（其实就是保持一下activity:smile:）

**Comment by racaljk** [comment]
现在很多都靠@Too-Naive，我实在有点羞耻了...

**Comment by imknown** [comment]
嗯, 谢谢你, 我尽量回馈. :joy_cat: 倒是 经常能在这里 看到他的身影..

**Comment by Too-Naive** [comment]
咸鱼了好久 想淡圈QAQ

**Comment by imknown** [comment]
嗯, 查了一下, 还是参考 系统原始的hosts, 按需添加吧.

**Comment by baobao1270** [comment]
江苏电信正常，但是打开较慢
