### ISSUE TITLE
为什么有一个项目可以改hosts文件观看youtube视频

### ISSUE THREAD

**Issue by Porigure** [racaljk/hosts#598]
fengixng/google-hosts（https://github.com/fengixng/google-hosts）就是这个项目，里面的hosts改了后看youtube视频1080P无压力。本人电脑小白，想来请教各位大神

**Comment by Porigure** [comment]
就是直接添加了hosts，没有进行别的操作

**Comment by jiangtiandao** [comment]
@Porigure 
人家readme说了“修改hosts无法完美观看youtube，完美观看youtube请使用dnsmasq配置文件”

**Comment by Too-Naive** [comment]
See also:https://git.io/v6HfW

**Comment by Porigure** [comment]
@jiangtiandao 但是实际上只添加hosts就行了，并没有别的操作

**Comment by Porigure** [comment]
@Too-Naive 那是和你给的那个原理一样用反代吗？我也试过添加你的这个https://gist.github.com/Too-Naive/4dc14b9b0737cffc0862e47a40108b98链接，就是感觉速度没那么快，是因为这个hosts给的条数更多吗

**Comment by Too-Naive** [comment]
不懂 大概是代理服务器线路的问题

________________________________

**Comment by beyondroot** [comment]
一提及youtube，为什么立马close 呢？况且@Porigure说的项目可以正常观看，是怕别人用其他项目？Naive !

**Comment by Too-Naive** [comment]
请问您有去看我发的链接？
Naive?

**Comment by Too-Naive** [comment]
没看？
![image](https://cloud.githubusercontent.com/assets/16496671/17915798/2955c2e6-69e0-11e6-9136-599cbd2d4e26.png)
![image](https://cloud.githubusercontent.com/assets/16496671/17915801/2eed242e-69e0-11e6-91b4-c2821764d928.png)
老师有没有教过你尊重他人？

**Comment by Stephen-Chen** [comment]
@Too-Naive 不要去尝试和喷子讲道理
@Porigure 不要随便使用别人的反代服务器，毕竟安全性没有保障。还有，别人使用这个开源项目， @Too-Naive 应该是没有任何利益可图的，没有所说的怕别人使用其他项目的说法。

**Comment by Porigure** [comment]
@Too-Naive 其实提出这个问题本意只是想探讨下这种方法的原理，因为我是光猫直连电脑并没有用路由器的，所以想问一下没按照上面说的去配置路由器文件单单只用hosts文件更改就能看油管视频是什么原理。若带来不必要的矛盾，在此表示抱歉！

**Comment by Too-Naive** [comment]
= =我的链接你们到底有没有去看啊
反向代理服务器啊...

**Comment by Porigure** [comment]
@Too-Naive 那是不是原理和之前提过的那个
[https://gist.github.com/Too-Naive/4dc14b9b0737cffc0862e47a40108b98](url)
用反代服务器原理一样？如果我用这个方法看1080P的视频会不会用到其它服务器的流量？

**Comment by Too-Naive** [comment]
会 你指向的这个服务器的ip并不是真正所谓Google服务器的IP
所有你过的流量也还是要走别人的服务器
我提到的那个就是反代

**Comment by Porigure** [comment]
那用别人的服务器这么做如果不考虑安全问题，在道义上来说这样做是否被允许？
因为我看到了一个回答是“1. 我认为用户使用本项目产生的法律问题和安全问题都应由用户自己承担
2. 本项目当前 Google IP 已使用了非官方的缓存服务器 220.255.2.153”

**Comment by Too-Naive** [comment]
你说我要上网 然后和你用同一个电话卡
那当然 我只上网 跑的是你的流量 你认为允不允许？

**Comment by Porigure** [comment]
学习了~

**Comment by andytimes** [comment]
大概是这个缓存服务器缓存了 Youtube 视频，所以可以看。

收集速度快的缓存服务器确实要费一点功夫，但不是做不到。不过，这些反代早晚会失效的，自己去更新这些，会比较繁琐。既然你发现了有人去收集并维护这类 hosts，你用就是了，但记得，视频网站跑的流量是很大的，维护服务器的成本很昂贵，别人没有向你提供"免费"的服务，所以使用的时候请记住这一点。
如果真的需要每天看 Youtube，还是去网上买个 Shadowsocks 账号吧。

@beyondroot 这里的贡献者没有那么虚荣，而且想要添加 Youtube 也就分分钟的事情。@Too-Naive 已经解释过了原因，close Issue 很正常。请不要随便揣测别人的想法。

**Comment by fengixng** [comment]
我是作者，我回复下吧
这是澳门CTM运营商的sni proxy服务器，本身是让自己的用户使用的，但是因为没有做限制，所以可以所有人使用。

**Comment by CHN008** [comment]
这个也还不错,只看看视频应该没什么风险,收藏一下!
![image](https://cloud.githubusercontent.com/assets/16646697/18417898/222a372a-786f-11e6-8c9e-9058b836e5ef.png)

**Comment by buttonXin** [comment]
用的很好 ，基本的查询都可以！谢谢

**Comment by firesh** [comment]
我做了个docker镜像，youtube暂时可以看，有兴趣的可以试试看：[https://github.com/firesh/dns](https://github.com/firesh/dns)

**Comment by kgfw** [comment]
这里有个 [hosts翻墙](https://github.com/bannedbook/fanqiang/wiki/hosts%E7%BF%BB%E5%A2%99)  ，可以看youtube  不知是啥情况
