### ISSUE TITLE
ixquick-proxy.com 请求修复

### ISSUE THREAD

**Issue by rafaelyine** [racaljk/hosts#6]
首先非常感谢作者，一直在享受着你的劳动成果，再次表示敬意。

hosts列表中有维护ixquick.com，能正常访问。但是ixquick-proxy.com却一直不能访问，chrome提示为“您的连接不是私密连接”。
尝试过为ixquick-proxy.com添加和ixquick.com一样的IP，无效，显示依旧。
登VPN后测试能正常使用。

ixquick-proxy.com是使用ixquick.com和startpage安全隐私搜索经常能用到的一个好功能，所以特此反馈，希望大牛能修复该问题。

谢谢您的时间和劳动！

**Comment by racaljk** [comment]
下次更新会注意

**Comment by rafaelyine** [comment]
最新版2015年4月18日的还是没有支持ixquick-proxy.com，下一版有打算吗？
