### ISSUE TITLE
mac怎么使用呢？

### ISSUE THREAD

**Issue by WuKongCoo1** [racaljk/hosts#60]
谢谢

**Comment by racaljk** [comment]
和linux一样 `sudo vi /etc/hosts`
或者参考https://briian.com/6148/mac-hosts.html

**Comment by whinamp** [comment]
@racaljk 那么iOS设备上又该怎么用呢？有相应的文章可提供指导吗？

**Comment by andytimes** [comment]
@whinamp https://github.com/cssmagic/blog/issues/28参考这个，我没有IOS设备，无法测试可行性，2013年的文章，现在不一定有效，最好https://www.google.com，利用好这个学习利器！

**Comment by whinamp** [comment]
@andytimes 我是实在Google不到解决方案才问的，升级iOS9以后之前的方法似乎已经失效了。不过还是谢谢了。

**Comment by andytimes** [comment]
嗯，毕竟是新系统，如果没有越狱就更麻烦了。不过IOS用Google服务比较少，如果你需要，可以修改你的路由器配置，然后用WIFI连接，就不用修改手机上的hosts了。具体方法你可以自己Google

2015年10月19日星期一，whinamp <notifications@github.com> 写道：

**Comment by whinamp** [comment]
@anytimes 真神奇，最新这一版hosts居然让twitter复活了，Google相关和fb等等依然不行。真是百思不得其解。

**Comment by Roller44** [comment]
不同地区不同运营商的效果是不一样的，我这边 Google 可以用 Twitter 比较慢但仍然可以用。


 

-------- 原始邮件 --------
发件人：whinamp <notifications@github.com>
时间：周二 10月20日 02:58
收件人：racaljk/hosts <hosts@noreply.github.com>
主题：Re: [hosts] mac怎么使用呢？ (#60)

**Comment by andytimes** [comment]
@whinamp 有的时候是运营商问题，浏览器，地区等等都会有影响，你可以自己回滚Google的IP，好像近几次IP都还是可用的。
