### ISSUE TITLE
facebook.com挂了

### ISSUE THREAD

**Issue by HzDSN** [racaljk/hosts#602]
如题

**Comment by imknown** [comment]
感觉像是 Windows 的锅, Windows 打开 奇慢无比, 手机 hosts 秒开..

**Comment by Too-Naive** [comment]
怎么可能和windows有关。。。

**Comment by Too-Naive** [comment]
你要想 手机版是不是比桌面版要求更少文件？

**Comment by imknown** [comment]
@Too-Naive 可能是insider的问题, 我用另一台正式版电脑 就没问题..

**Comment by Too-Naive** [comment]
![](https://cloud.githubusercontent.com/assets/16496671/17828062/95155038-66ba-11e6-83c3-d2edd5bbcec5.gif)
......

**Comment by HzDSN** [comment]
题主补充一下。我用电脑（Win10 14393）和安卓手机（Nexus 6P）都连不上。浙江电信

**Comment by Too-Naive** [comment]
谢反馈

**Comment by Too-Naive** [comment]
为何关了

**Comment by baobao1270** [comment]
江苏电信正常，但是打开较慢
