### ISSUE TITLE
邮件客户端无法访问Gmail

### ISSUE THREAD

**Issue by fun5rt** [racaljk/hosts#604]
Mac上使用Airmail，从8.27号开始就无法收发gmail了，更新了8.28号的最新host也是不行，但是chrome网页版的gmail就可以访问，这大概是什么原因呢？改如何排查呢？

**Comment by imknown** [comment]
之前是可以的?

**Comment by fun5rt** [comment]
对的，之前都是可以的。8.27号收到了最后一封邮件，到现在就一直不能收发了，但是网页的gmail是可以的

**Comment by imknown** [comment]
别的客户端也有这个问题?

**Comment by fun5rt** [comment]
只有这一个客户端呀，你mac上还有其他的推荐么？自带的mail我添加不上gmail

**Comment by imknown** [comment]
@fun5rt 没怎么用过 MacOS 不太了解.. 谷歌找找试试..

**Comment by andytimes** [comment]
检查下从
https://github.com/racaljk/hosts/blob/master/hosts#L3018
到
https://github.com/racaljk/hosts/blob/master/hosts#L3034

1. 这几段 IP 是否生效（ping 下面两个域名看看）：

```shell
ping -c4 imap.gmail.com
ping -c4 smtp.gmail.com
```

2. 检查下 Airmail 的 IMAP 和 SMTP 服务器设置：

-----

收件服务器：
服务器：imap.gmail.com
端口：993
安全类型：SSL/TLS（接受所有证书）

发件服务器：
服务器：smtp.gmail.com
端口：465
安全类型：SSL/TLS（接受所有证书）

-----

可以参考以上设置，我手机上的邮件客户端是这样设置的，服务器端口还有其他几组，一般没问题不用改成别的。

**Comment by fun5rt** [comment]
@andytimes 

按照说明我测试了下

host里面是有下面两条的：
64.233.188.109	imap.gmail.com
64.233.188.109	smtp.gmail.com

但是我ping smtp.gmail.com 和 imap.gmail.com 的时候返回的ip地址却都是64.233.188.108
我看了下64.233.188.108 这个ip在hosts 里仅仅对应一条：gmail-smtp.l.google.com

这个很奇怪啊，为什么出现了 ping域名出现的ip地址不与hosts里对应的情况？
第二，gmail-smtp.l.google.com 对应的ip怎么与其他的都不相同是64.233.188.108呢？

**Comment by fun5rt** [comment]
问题解决了，详见https://github.com/racaljk/hosts/issues/617
