### ISSUE TITLE
t.co IP was down.

### ISSUE THREAD

**Issue by myguybetter** [racaljk/hosts#609]
104.244.42.5 had been blocked. Please change.

**Comment by imknown** [comment]
我这里 twitter 的 相关 ip 都被土啬了

**Comment by HaloWang** [comment]
<img width="603" alt="screen shot 2016-09-09 at 6 09 41 pm" src="https://cloud.githubusercontent.com/assets/7344724/18383538/a20d5566-76b8-11e6-872f-8030c54b3fb0.png">
https://t.co/05A9AlMboK
也是无法打开

**Comment by Too-Naive** [comment]
…这不是github页面吗
请具体描述是什么问题



Sent from my Mi phone
On WangCe <notifications@github.com>, Sep 9, 2016 6:12 PM wrote:

[screen shot 2016-09-09 at 6 09 41 pm]<https://cloud.githubusercontent.com/assets/7344724/18383538/a20d5566-76b8-11e6-872f-8030c54b3fb0.png>
https://t.co/05A9AlMboK
也是无法打开

**Comment by HaloWang** [comment]
具体就是：
这是 github 某个 repo 的 Twitter 账号发送的推文，推文中附带了某个 github 的链接，该链接本身没有被墙，但是我在
twitter 点击该链接后，“https://t.co/05A9AlMboK” 这个短链接不能跳转到指定的 github 页面，而翻墙后可以。

2016-09-10 0:03 GMT+08:00 Unostvisal <notifications@github.com>:

> …这不是github页面吗
> 请具体描述是什么问题
>
>
>
> Sent from my Mi phone

**Comment by HaloWang** [comment]
host 已更换，google 也是可以上的

2016-09-11 3:26 GMT+08:00 Ce Wang <halowang1991@gmail.com>:

> 具体就是：
> 这是 github 某个 repo 的 Twitter 账号发送的推文，推文中附带了某个 github 的链接，该链接本身没有被墙，但是我在
> twitter 点击该链接后，“https://t.co/05A9AlMboK” 这个短链接不能跳转到指定的 github 页面，而翻墙后可以。
>
> 2016-09-10 0:03 GMT+08:00 Unostvisal <notifications@github.com>:
>
>> …这不是github页面吗
>> 请具体描述是什么问题
>>
>>
>>
>> Sent from my Mi phone

**Comment by c02y** [comment]
t.co 还是打不开

**Comment by lyflyflxf** [comment]
@c02y 在这个问题被正式解决之前，可以把t.co对应的IP手动修改为twitter.com的IP，并在浏览器中忽略由此产生的证书不对应问题
