### ISSUE TITLE
是否可以添加一下telegram的host

### ISSUE THREAD

**Issue by zsenliao** [racaljk/hosts#610]
是否可以添加一下以下host:

149.154.167.99    telegram.org
149.154.167.99    desktop.telegram.org
149.154.167.99    core.telegram.org

**Comment by Too-Naive** [comment]
请使用pull request

On Aug 31, 2016 6:23 PM, zsenliao <notifications@github.com> wrote:

是否可以添加一下以下host:

149.154.167.99 telegram.org
149.154.167.99 desktop.telegram.org
149.154.167.99 core.telegram.org

**Comment by Too-Naive** [comment]
Thx.

**Comment by daniuer** [comment]
我这里添加了也用不了，只能用SS。

**Comment by andytimes** [comment]
https://servers.blog.ustc.edu.cn/2016/10/add-telegram-web-service/

前两天中科大的 LUG 增加了了网页版 Telegram 服务，
Github 上的源码 https://github.com/ustclug/telegram-web

**Comment by imcaffrey** [comment]
已 star 太劲了！

**Comment by andytimes** [comment]
@imcaffrey LUG 经常出各种各样的服务，开源镜像很好用。
