### ISSUE TITLE
增加 Mac OSX 系统正常运行所需要的项

### ISSUE THREAD

**Issue by Fezreal** [racaljk/hosts#612]
osx 的 mac app store 和 mail.app 以及icloud 等等，平日里不开全局模式会非常的卡，请求增加这些地址。

**Comment by Too-Naive** [comment]
卡 和 无法访问 没有关系吧

**Comment by c02y** [comment]
哎哟，apple的服烂的又不是一年两年了，竟然还有人来求hosts解决

**Comment by imknown** [comment]
apple cdn 的锅

**Comment by Too-Naive** [comment]
~~我在国外 非常快！~~

**Comment by imcaffrey** [comment]
劲劲你这样说话就是你很有趣了

**Comment by Too-Naive** [comment]
![](https://cloud.githubusercontent.com/assets/16496671/14873063/cd15c35e-0d24-11e6-81ec-9f97b2c120da.JPG)
墙就是内和外！

**Comment by imcaffrey** [comment]
算了 我也不和你争了 毕竟你在那个位置也就应该那么说话

**Comment by laodcn** [comment]
问下，怎么解除邮箱绑定... 你们在这里聊天 我手机快炸了

**Comment by lautis0503** [comment]
我记得可以设置不发送邮件的

**Comment by imcaffrey** [comment]
unsubscribe 或者改settings 里面notification 设置

**Comment by c02y** [comment]
话说这里的更新蛮活跃的嘛，我之前的hosts源那边提交已经一个星期了都还没反映（主要是Twitter的挂了）作者在回复页面已经2个月没动静了，在V站偶然看到这边的更新竟然可用，以后转到这了，多谢各位

**Comment by Too-Naive** [comment]
![image](https://cloud.githubusercontent.com/assets/16496671/18417401/37541af6-7862-11e6-91a9-4e6b2bf546fd.png)

**Comment by Too-Naive** [comment]
![image](https://cloud.githubusercontent.com/assets/16496671/18417403/6c364ea6-7862-11e6-8ba4-bed252ba34fe.png)
