### ISSUE TITLE
Google无法连接

### ISSUE THREAD

**Issue by aleen42** [racaljk/hosts#613]
Failed to connect to Googe, bu Facebook is OK.

**Comment by Too-Naive** [comment]
Have you ever try this: https://github.com/racaljk/hosts/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98%E8%A7%A3%E7%AD%94

**Comment by aleen42** [comment]
@Too-Naive Sorry, I have not checked the Wiki. That problem is because of HTTPS.

**Comment by imcaffrey** [comment]
Try ..> tried @Too-Naive :thought_balloon:

**Comment by Too-Naive** [comment]
快去读书 哼唧



Sent from my Mi phone
On SCaffrey <notifications@github.com>, Sep 3, 2016 3:25 PM wrote:

Try ..> tried @Too-Naive<https://github.com/Too-Naive> 💭
