### ISSUE TITLE
用tools工具安装出错了；

### ISSUE THREAD

**Issue by liuxsen** [racaljk/hosts#618]
![2](https://cloud.githubusercontent.com/assets/12598696/18211333/ba4739a6-716f-11e6-9a5d-148a5b03384a.png)

出错信息，如上图；
有遇到相同情况的人吗？
系统环境： win10；

**Comment by Too-Naive** [comment]
请检查防火墙......

**Comment by liuxsen** [comment]
关闭防火墙之后，可以了，那防火墙还可以再次开启吗？有什么影响吗？

**Comment by imknown** [comment]
加到例外

**Comment by Too-Naive** [comment]
加到例外去就好了
On Sep 4, 2016 8:57 PM, "imknown J. Kimu" <notifications@github.com> wrote:

加到例外

―

**Comment by liuxsen** [comment]
恩恩，可以了；谢谢
