### ISSUE TITLE
希望增加Box的访问支持

### ISSUE THREAD

**Issue by murazi** [racaljk/hosts#621]
前面几个版本都可以访问，最近几个版本就开始无法访问Box.com了~

**Comment by racaljk** [comment]
四川电信正常访问,使用https试试

**Comment by andytimes** [comment]
Box.com 有被封吗？我没加这段 hosts 也能正常访问。而且 Box 那几段 IP 估计有很久都没动过了。

**Comment by murazi** [comment]
没错BOX近几个版本都打不开，而且一个设计类的网站Dribbble也打不开了，最近怎么了

**Comment by andytimes** [comment]
@murazi 
```lua
# Box.com Start
74.112.184.90	box.com
74.112.184.228	www.box.com
74.112.184.82	m.box.com
74.112.184.87	app.box.com
74.112.184.89	app.boxcloud.com
74.112.184.85	account.box.com
74.112.184.100	account.boxcn.net
74.112.184.74	services.box.com
104.218.203.34	support.box.com
# Box.com End
```

请阁下先当小白鼠测试下... 把原来 hosts 文件里的 Box 相关条目删去，然后粘贴上面那几段到 hosts 里面，看看能否顺利访问（因为还是同一个 IP 段，可能不会有太大的改善、、、）。

访问 Box 异常，可能是这个 CDN 地址的影响: `cdn03.boxcdn.net` ，:

```lua
C:\Users\xxxx> nslookup cdn03.boxcdn.net

服务器:  XiaoQiang
Address:  192.168.31.1

非权威应答:
DNS request timed out.
    timeout was 2 seconds.
名称:    cdn03.boxcdn.net.cdn.cloudflare.net
Addresses:  104.16.114.148
          104.16.117.148
          104.16.115.148
          104.16.116.148
          104.16.118.148
Aliases:  cdn03.boxcdn.net
```

ping 了一下，104.16.114.148 和 104.16.118.148 丢包率较高，104.16.116.148 比前面两个IP稳定点，
但我这里却经常解析为前两个IP，这种情况可以在 hosts 里加一段 `104.16.116.148	cdn03.boxcdn.net`，
可以根据本地网络情况来筛选稳定点的 IP，说不定可以解决访问的问题。

如果还是不行，那就挂代理吧、、、
