### ISSUE TITLE
Google 失效？

### ISSUE THREAD

**Issue by lautis0503** [racaljk/hosts#622]
220.255.2.153 ping不通
浙江广电

**Comment by Too-Naive** [comment]
~~ping正常 台湾省~~
暂时未有其他人反馈问题

**Comment by Too-Naive** [comment]
~~ping正常 台湾省~~
暂时未有其他人反馈问题

**Comment by racaljk** [comment]
四川电信正常访问(听同学说可能和G20有关...

**Comment by Too-Naive** [comment]
may



Sent from my Mi phone
On Cthulhu <notifications@github.com>, Sep 6, 2016 1:50 PM wrote:

四川电信正常访问(听同学说可能和G20有关...

**Comment by lautis0503** [comment]
G20好像很有道理，可是昨天还能访问……

**Comment by wangxiaofei** [comment]
北京联通可访问

**Comment by aixiu** [comment]
湖北电信，正常访问。

**Comment by lautis0503** [comment]
嗯……我这里也突然好了……原因不明

**Comment by imcaffrey** [comment]
祝劲劲一路平安以及早日*****

**Comment by lautis0503** [comment]
应该是广电的锅，最近连msdn也不让好好上了

**Comment by imknown** [comment]
时快时慢 完全看颜值...

**Comment by Too-Naive** [comment]
肉身fq 再也不用担心被墙
