### ISSUE TITLE
维基百科的host地址希望能够补充完整

### ISSUE THREAD

**Issue by DannyVim** [racaljk/hosts#625]
现有的host文件中对于维基百科只有中文的主站地址，而缺少例如图片资源、维基媒体、以及其它语言维基的地址。希望能够补充完整。

**Comment by Too-Naive** [comment]
忘记reply了…
据我所知 在某个commit中指出 根据长期观察 其他域名的DNS污染已经解除
但是不清楚目前有没有恢复污染(commit找不到了  大概在3-5月之间的commit)



Sent from my Mi phone
On Danny Vim <notifications@github.com>, Sep 8, 2016 10:15 AM wrote:

现有的host文件中对于维基百科只有中文的主站地址，而缺少例如图片资源、维基媒体、以及其它语言维基的地址。希望能够补充完整。

**Comment by DannyVim** [comment]
@Too-Naive 可是如果没有host当中写入相应的地址，发现还是无法连接资源呢

**Comment by Too-Naive** [comment]
不懂【趴



On Danny Vim <notifications@github.com>, Sep 22, 2016 12:38 wrote:

@Too-Naive<https://github.com/Too-Naive> 可是如果没有host当中写入相应的地址，发现还是无法连接资源呢

**Comment by sansna** [comment]
> @Too-Naive 可是如果没有host当中写入相应的地址，发现还是无法连接资源呢
我这里其实wiki本来就能连上，我加的这个ip也只为了加速连接。对于你那儿有没有帮助我也是不知道的。

**Comment by Too-Naive** [comment]
~~我也能连上... 我google都能直接访问~~

**Comment by xuan-72** [comment]
非常感谢你！我自己将文件搞乱，也不懂得如何修改和修正，真的乱七八糟毫无方向，一切都搞砸了！

2016-09-22 18:49 GMT+08:00 Unostvisal <notifications@github.com>:

**Comment by xuan-72** [comment]
非常感谢你！现在加载host文件都可以访问谷歌，只不过没完成github储存文件，我自己将文件搞乱，也不懂得如何修改和修正，
真的乱七八糟毫无方向，一切都搞砸了。非常感谢，虽然没有完成，但学到了不少！

2016-09-22 18:49 GMT+08:00 Unostvisal <notifications@github.com>:

**Comment by DannyVim** [comment]
我现在处在的网络环境的基本是在教育网的IPV6和IPV4之间不断切换。IPV6的连接基本上都不会有问题（虽然说这两天发现Y2B的视频连接开始出问题），就是IPV4不行

**Comment by Too-Naive** [comment]
…y2b的视频链接和本项目无关吧



On Danny Vim <notifications@github.com>, Sep 24, 2016 1:06 PM wrote:

我现在处在的网络环境的基本是在教育网的IPV6和IPV4之间不断切换。IPV6的连接基本上都不会有问题（虽然说这两天发现Y2B的视频连接开始出问题），就是IPV4不行

**Comment by DannyVim** [comment]
我现在处在的网络环境的基本是在教育网的IPV6和IPV4之间不断切换。IPV6的连接基本上都不会有问题（虽然说这两天发现Y2B的视频连接开始出问题），就是IPV4不行

**Comment by andytimes** [comment]
@DannyVim 维基媒体除了维基百科中文首页其他都未被DNS污染:
https://zh.wikipedia.org/wiki/Help:%E5%A6%82%E4%BD%95%E8%AE%BF%E9%97%AE%E7%BB%B4%E5%9F%BA%E7%99%BE%E7%A7%91#Hosts.E6.96.87.E4.BB.B6 

出现无法连接的情况，可以稍微等一等，多刷新就 OK

**Comment by andytimes** [comment]
@sansna 其实每个地区速度都不太一样，项目里面的 en.wikipedia.org IP 也不算最优，
我这里 198.35.26.96 速度最快。其实也不用纠结这些，能用就好。
