### ISSUE TITLE
cannot visit android developer website 

### ISSUE THREAD

**Issue by still-ben** [racaljk/hosts#63]
i've update the hosts right now.
i can not visit the android deleloper site "developer.android.com", show an error "ERROR 403.Your client does not have permission to get URL /preview/ from this server. That’s all we know."

BTW,www.android.com work good.

i've tried both http and https.

does anybody any idea about that?

**Comment by K-Guan** [comment]
On my Arch Linux/Chrome, I can connect to developer.android.com. Check the image.
So are you on Linux or Windows or Phone? 

![screenshot from 2015-10-20 09-34-16](https://cloud.githubusercontent.com/assets/13862535/10595710/06a8d0aa-770e-11e5-8750-0ca3d59b6f48.png)

**Comment by still-ben** [comment]
the same as yours.

**Comment by K-Guan** [comment]
Hmm...try `wget` or `curl`?

**Comment by still-ben** [comment]
nothing but 403 forbidden returned.

**Comment by K-Guan** [comment]
*403 Error* means that you don't have permission to access the server, but that's impossible. 
Maybe @andytimes has some ideas.

**Comment by still-ben** [comment]
Thanks anyway[@K-Guan](https://github.com/K-Guan).
Could you give me a hand plz ,[@andytimes](https://github.com/andytimes)?
Environment:
  Unbuntu 14.04,
  Linux 3.13.0-65-generic,
  chrome  45.0.2454.101 (64-bit)

 www.google.com and www.android.com work good,but not do developer.android.com.
![google](https://cloud.githubusercontent.com/assets/12825822/10596023/bfa55012-7711-11e5-8f4b-2076d0a61424.png)
![developer](https://cloud.githubusercontent.com/assets/12825822/10596024/bfaca92a-7711-11e5-97b1-d6d34245fd10.png)
![www](https://cloud.githubusercontent.com/assets/12825822/10596025/bfb9e0ae-7711-11e5-9712-043f6465d4c3.png)

**Comment by andytimes** [comment]
IP全能性差，可能需要搜索特定IP地址，现在更新了hosts，能访问了，不过，图片资源还是有些问题，下载倒是没有问题。还是需要搜索特定IP才能彻底解决，希望各位积极贡献

**Comment by whinamp** [comment]
这个hosts源已经被挂到各大翻墙网站了，他们这样搞下去不好吧？

**Comment by K-Guan** [comment]
@whinamp 反正 @racaljk 喜欢～

**Comment by andytimes** [comment]
@whinamp 在Google 搜索 hosts，这个项目排名第二；百度搜不到。其实hosts只是很单纯的工具，没有什么好不好的。

**Comment by whinamp** [comment]
还是要吸取一下imouto.hosts的教训

**Comment by andytimes** [comment]
@K-Guan 你的ARCH装的KDE，是5.3还是5.4

**Comment by whinamp** [comment]
小白拿着在墙内冒充大神到处乱传。

**Comment by andytimes** [comment]
@whinamp 这个imouto.hosts怎么了

**Comment by whinamp** [comment]
那时候hosts翻墙还很流行，小白们拿着在贴吧 机锋等等地方大肆传播，最后可能是被功夫网认证了吧，到后来Github上更新半小时之内IP全部失效。再后来作者也就停止维护了。

**Comment by andytimes** [comment]
@whinamp 确实，以前经常能看到提供hosts更新的apk。
Google的全范围IP段其实早公之于众，想全封完早就封完了，G||||FW估计是为了不想激起民愤，用温水煮青蛙的方法一点一点封锁。现在主要针对的还是提供直接穿越的工具。

现在74段的IP基本全挂了，64段还有不少，所以64开头的那个IP才能活这么久（速度很慢）。
目前使用的216段ping的时候不稳定，但是访问速度特别快，也是比较幸运的。

实际上G|||FW最无耻的地方，在于把IP指向其他存在的国外IP，导致一些网站禁止中国访问；域名解析污染到其他国家等。
还有从前封Github，真的是莫名其妙。

刚刚Google了一下你说的那个hosts，README.md充满个人色彩，比较奇葩、、

**Comment by whinamp** [comment]
到那时天朝IP的访问者被国外当成瘟疫避之不及也就用不着当局来墙了。

**Comment by andytimes** [comment]
我个人倒是认为这个墙早晚有一天会倒的。

2015-10-20 22:08 GMT+08:00 whinamp <notifications@github.com>:

**Comment by still-ben** [comment]
thanks ,@andytimes & @K-Guan , 
i've checked that problem has been settled.

**Comment by andytimes** [comment]
图片资源依旧有问题，日后再解决吧，不影响使用。Enjoy，Android developer.

2015-10-20 22:12 GMT+08:00 still-ben <notifications@github.com>:
