### ISSUE TITLE
希望增加 getlantern.org 的访问 IP

### ISSUE THREAD

**Issue by lxylxy123456** [racaljk/hosts#632]
希望增加 getlantern.org 的访问 IP
IP地址: 54.192.119.19
来自 host 8.8.8.8 命令产生的结果

**Comment by Too-Naive** [comment]
能ping通吗

**Comment by Too-Naive** [comment]
能ping通吗

**Comment by lxylxy123456** [comment]
可以

发自我的 iPhone

**Comment by lautis0503** [comment]
我get的IP是52.84.7.225，试了下两个都能用

**Comment by imknown** [comment]
我觉得 这种软件,
还是 不要加到这个 项目比较好.
感觉 有敏感的话题.

**Comment by Too-Naive** [comment]
同意



Sent from my Mi phone
On "imknown J. Kimu" <notifications@github.com>, Sep 10, 2016 4:03 PM wrote:

我觉得 这种软件,
还是 不要加到这个 项目比较好.
感觉 有敏感的话题.

**Comment by Too-Naive** [comment]
需要自取
