### ISSUE TITLE
打不开dartpad.dartlang.org

### ISSUE THREAD

**Issue by creatint** [racaljk/hosts#633]
dartpad.dartlang.org 求助，这个网址打不开T_T
ping dartpad.dartlang.org，提示的是 “正在 Ping ghs.l.google.com [216.58.199.115]”。请求超时

**Comment by creatint** [comment]
ping dartpad.dartlang.org，提示的是 “正在 Ping ghs.l.google.com [216.58.199.115]”，请求不到数据

**Comment by Too-Naive** [comment]
Fix in #635
