### ISSUE TITLE
希望增加youtube的访问支持

### ISSUE THREAD

**Issue by yeshuopp123** [racaljk/hosts#638]
希望增加youtube的访问支持

**Comment by yeshuopp123** [comment]
希望增加youtube的访问支持

**Comment by Too-Naive** [comment]
不是可以访问吗。。。

**Comment by imknown** [comment]
不知道 你是不是想问这个, 提问之前 要先进行搜索. 
https://github.com/racaljk/hosts/issues?utf8=%E2%9C%93&q=youtube

**Comment by Too-Naive** [comment]
#297

**Comment by CHN008** [comment]
目前用这个Hosts可以全速看Youtube视频,不过作者说安全性不高.

https://github.com/fengixng/google-hosts

**Comment by HaloWang** [comment]
现在我只能打开 youtube，但是无法加载视频流

**Comment by Too-Naive** [comment]
正常啊……… 你到底有没有看comment啊

**Comment by HaloWang** [comment]
#297 好吧看来是这个 comment 了~

**Comment by Too-Naive** [comment]
想要看 就要用反代 也可以用hosts 但是 不安全 所以不会添加到这个项目
