### ISSUE TITLE
是否应该在 README 加入 如何贡献 以及 写好的 Wiki链接 等.

### ISSUE THREAD

**Issue by imknown** [racaljk/hosts#639]
现在感觉很松散. 自己找起来 也不方便~  :octocat:

**Comment by Too-Naive** [comment]
You can you up? (没有贬义)

**Comment by imknown** [comment]
嗯, 有时间 我也整理整理.

**Comment by Too-Naive** [comment]
on https://github.com/racaljk/hosts/issues/577#issuecomment-239659788

**Comment by Too-Naive** [comment]
你可以参考下这个

**Comment by imcaffrey** [comment]
以前写过contribution.md的
后来出了issue_template和pr_template就决定删掉那个来写这个= =因为并没有多少人去看之前的那个
有兴趣的话把template改成第一人称好不好= = :thought_balloon:

**Comment by imcaffrey** [comment]
btw, @racaljk Github 出了review新功能 https://help.github.com/articles/about-pull-request-reviews/

**Comment by Too-Naive** [comment]
我好困

**Comment by imknown** [comment]
Github 出了 Project 这个新功能, 是不是 可以转化一下了?  
https://github.com/racaljk/hosts/projects/

**Comment by Too-Naive** [comment]
project是做啥的



Sent from my Mi phone
On "imknown J. Kimu" <notifications@github.com>, Sep 16, 2016 5:14 PM wrote:

Github 出了 Project 这个新功能, 是不是 可以转化一下了?

https://github.com/racaljk/hosts/projects/

**Comment by imknown** [comment]
@Too-Naive 
和 [zenhub][zenhub] 差不多吧

[zenhub]: https://zenhub.io

**Comment by Too-Naive** [comment]
原来是通过Add card 来添加啊= =

**Comment by imcaffrey** [comment]
trello 即视感

**Comment by chuanzhongliu** [comment]
不能在Google商店里更新怎么回事

**Comment by Too-Naive** [comment]
请另开新的issue

**Comment by imcaffrey** [comment]
手机上么= =

**Comment by omaidb** [comment]
我赞成这个提议，我也想贡献
