### ISSUE TITLE
怎么Google商店里不能更新

### ISSUE THREAD

**Issue by chuanzhongliu** [racaljk/hosts#642]

**Comment by imknown** [comment]
https://github.com/racaljk/hosts/search?utf8=%E2%9C%93&q=play&type=Issues

**Comment by Too-Naive** [comment]
没有重复啊= =是同一个人啊。。

**Comment by imknown** [comment]
@Too-Naive 其实我想说 的是 这个问题 反复 重复 被问 :cry:

**Comment by Too-Naive** [comment]
捂脸】并没有啊

**Comment by andytimes** [comment]
建议使用 Shadowsocks 去更新 Play 商店的应用，Play 商店的情况和 Youtube 一样，主要问题是没有可用 IP，其次域名搜索也有些繁琐。

hosts 里面也提供了 Apkpure 的访问，也可以用它来更新，但是无代理情况时，下载速度很慢。

**Comment by Too-Naive** [comment]
其实apk mirror之类的那些都可以下载....

**Comment by andytimes** [comment]
@Too-Naive 对于我这种不玩游戏，不折腾手机的轻度用户，用用手机乐园更新应用就足够了。如果不是某些应用需求 Play 商店，就不会装这些 Google 服务了、、、

**Comment by cnfor404** [comment]
顺着hosts文件里的名字来找大神，我用的是你以前的hosts，在htcui论坛里找的，为什么我的可以正常在Google play客户端下载软件，而且能够看油管视频gmail正常接收邮件，只不过昨天把play severe清除数据了，结果就导致账号死活登陆不上，一直显示与Google服务器通信时出现错误，我把hosts文件一删除挂上VPN就又可以了，不明觉厉(°ー°〃)…另外网页版使用您的hosts还是能够访问登录gp等，只是客户端不行，大神你知道这是什麽原因造成的吗？

**Comment by andytimes** [comment]
@cnfor404 
> Google play客户端下载软件，而且能够看油管视频

从这一句就可以判断阁下用的hosts是他人改进过的，这里hosts内没有提供Play下载和Youtube视频解析的地址。

账号无法登陆，有可能是连接了客户端专有域名来认证设备，而hosts缺失了这些地址的解析规则。

网页版一直能登陆，但是不能下载。
