### ISSUE TITLE
对于域名storage.googleapis.com，https访问失败，http访问成功，通过hsots能解决吗

### ISSUE THREAD

**Issue by creatint** [racaljk/hosts#647]
如题

**Comment by laodcn** [comment]
http://storage.googleapis.com/
https://storage.googleapis.com/
都正常呀，南方电信

**Comment by creatint** [comment]
房东办的北方的方正宽带，访问不了https的，真是艰难。。

**Comment by imcaffrey** [comment]
宽带症候群 默哀

**Comment by imknown** [comment]
打开之后, 刷新一下 就打不开了, `且用且珍惜`.

**Comment by Too-Naive** [comment]
![](https://cloud.githubusercontent.com/assets/16496671/17828062/95155038-66ba-11e6-83c3-d2edd5bbcec5.gif)

**Comment by andytimes** [comment]
@creatint 刚刚用在线ping扫了一下，找到一个 IP，但没找到能测试 Google Storage 的网址，不知道能不能用，你可以测试下。

**Comment by aofall** [comment]
其实这个子域本来就没墙，因为IP的问题
可以试试
216.58.221.112
172.217.17.48
HTTP可以https不行又是方正宽带则说明运营商为了节约成本直接封IP搞了内网缓存，最有效的办法就是换个宽带

**Comment by andytimes** [comment]
好吧，我这里确实被墙了，解析出来的是这个 IP 74.125.203.128
