### ISSUE TITLE
[已解决] 请更新tumblr的hosts

### ISSUE THREAD

**Issue by lyflyflxf** [racaljk/hosts#650]
湖北联通

66.6.44.4连接失败，某些media.tumblr.com也无法连接

**Comment by imknown** [comment]
移动联通电信各试了一下 都能秒开

**Comment by Too-Naive** [comment]
小包厢系列？

**Comment by lyflyflxf** [comment]
谢谢imknown提示，hosts本身没问题，貌似现在必须用https了。明明之前http也有反应的。ping貌似也被封了

P.S. 小包厢是什么鬼，别吓我……我只是一介草民
