### ISSUE TITLE
ampproject.org域名缺失

### ISSUE THREAD

**Issue by Makebignew** [racaljk/hosts#652]
220.255.2.153 cdn.ampproject.org
220.255.2.153 ampproject.org
Google某个团队搞出来优化移动设备访问效果的，既然是Google家的添上没坏处。

**Comment by Too-Naive** [comment]
请使用pull request来提交 谢谢



On Makebignew <notifications@github.com>, Sep 24, 2016 12:51 PM wrote:

220.255.2.153 cdn.ampproject.org
220.255.2.153 ampproject.org
Google某个团队搞出来优化移动设备访问效果的，既然是Google家的添上没坏处。

**Comment by laodcn** [comment]
https://www.ampproject.org/
https://cdn.ampproject.org/v0.js
秒开...并不需要添加...

**Comment by imcaffrey** [comment]
的确秒开。。。 需要的自取吧
