### ISSUE TITLE
安装自动更新服务，但是更新失败，附日志

### ISSUE THREAD

**Issue by ioperat** [racaljk/hosts#654]
Hosts_Tool_log.log
2016/09/05 11:25:58 LICENSE:General Public License
                    Copyright (C) 2016 Too-Naive
                    Bug report:sometimes.naive[at]hotmail.com
                               Or open new issue.(https://github.com/HostsTools/Windows)
2016/09/05 11:26:58 Start replace hosts file.
2016/09/05 11:27:04 Fatal Error:
                    DownLoad hosts file Error! (GetLastError():183)
                    Please contact the application's support team for more information.
2016/09/05 11:57:04 Start replace hosts file.
2016/09/05 11:57:34 Fatal Error:
                    DownLoad hosts file Error! (GetLastError():183)
                    Please contact the application's support team for more information.
2016/09/05 12:27:34 Start replace hosts file.

请问该如何解决？

**Comment by Too-Naive** [comment]
download过程错误的话....似乎没有什么解决的法子?
手动更新可以成功吗？
(另:您可以去项目中提问....)

**Comment by ioperat** [comment]
@Too-Naive   手动更新没有问题

**一、我尝试运行choose.exe-->>7-->>结果如下：**
[http://p1.bqimg.com/1949/c387ff45f8ee82bb.png](url)

**二、我运行tool.exe，结果如下：**
[http://p1.bqimg.com/1949/2d0fb690db3282e2.png](url)

**Comment by Too-Naive** [comment]
这就很奇怪了233

**Comment by Too-Naive** [comment]
会不会是防火墙限制什么的？ 还是有360之类？
(看样子操作系统应该是xp或2003家族

**Comment by Too-Naive** [comment]
(而且这个版本好早的啊.........)

**Comment by andytimes** [comment]
https://msdn.microsoft.com/en-us/library/windows/desktop/ms681382(v=vs.85).aspx

> ERROR_ALREADY_EXISTS
183 (0xB7)
Cannot create a file when that file already exists.

是不是 hosts 属性没有勾选 “写入”？
![image](https://cloud.githubusercontent.com/assets/7419875/18814527/541b81a6-8348-11e6-9fbb-e74143f51778.png)

**Comment by Too-Naive** [comment]
= =不是啊 手动都可以

**Comment by ioperat** [comment]
系统是server 2008 r2 x64，hosts文件可写，手动更新没有任何问题

**Comment by Too-Naive** [comment]
不知道怎么讲 您更新一下？

**Comment by ioperat** [comment]
更新之后，新版本依然报错，日志如下：
2016/09/26 15:33:59 Open log file.
2016/09/26 15:33:59 LICENSE:General Public License
                    Copyright (C) 2016 Too-Naive
                    Bug report:sometimes.naive[at]hotmail.com
                               Or open new issue.(https://github.com/HostsTools/Windows)
2016/09/26 15:34:59 Start replace hosts file.
2016/09/26 15:35:14 Fatal Error:
                    DownLoad hosts file Error! (GetLastError():183)
                    Please contact the application's support team for more information.
2016/09/26 16:36:14 Start replace hosts file.
2016/09/26 16:36:29 Fatal Error:
                    DownLoad hosts file Error! (GetLastError():183)
                    Please contact the application's support team for more information.
2016/09/26 17:06:29 Start replace hosts file.
2016/09/26 17:06:39 Fatal Error:
                    DownLoad hosts file Error! (GetLastError():183)
                    Please contact the application's support team for more information.

**Comment by Too-Naive** [comment]
嗨呀…好气啊…



On ioperat <notifications@github.com>, Sep 27, 2016 9:08 AM wrote:

更新之后，新版本依然报错，日志如下：
2016/09/26 15:33:59 Open log file.
2016/09/26 15:33:59 LICENSE:General Public License
Copyright (C) 2016 Too-Naive
Bug report:sometimes.naive[at]hotmail.com
Or open new issue.(https://github.com/HostsTools/Windows)
2016/09/26 15:34:59 Start replace hosts file.
2016/09/26 15:35:14 Fatal Error:
DownLoad hosts file Error! (GetLastError():183)
Please contact the application's support team for more information.
2016/09/26 16:36:14 Start replace hosts file.
2016/09/26 16:36:29 Fatal Error:
DownLoad hosts file Error! (GetLastError():183)
Please contact the application's support team for more information.
2016/09/26 17:06:29 Start replace hosts file.
2016/09/26 17:06:39 Fatal Error:
DownLoad hosts file Error! (GetLastError():183)
Please contact the application's support team for more information.

**Comment by Too-Naive** [comment]
可以尝试一种新的模式…加在启动项中 然后以后台形式运行

**Comment by Too-Naive** [comment]
晚上可以填坑w

**Comment by aofall** [comment]
楼上你这个坑填的真久

**Comment by Too-Naive** [comment]
QAQ 这两天都在出门…

**Comment by ioperat** [comment]
已经找到替代方法，加到计划任务中，每天定时运行一次。

**Comment by Too-Naive** [comment]
→_→ 更新的版本添加了用注册表启动的功能



On ioperat <notifications@github.com>, Oct 28, 2016 9:00 AM wrote:

已经找到替代方法，加到计划任务中，每天定时运行一次。
