### ISSUE TITLE
www.agi.com

### ISSUE THREAD

**Issue by p0mp0k0** [racaljk/hosts#658]
https://www.agi.com/ ，无法正常打开，百度快照和google的快照都正常

**Comment by Too-Naive** [comment]
~~正常访问 台湾~~

**Comment by lautis0503** [comment]
被墙了

**Comment by andytimes** [comment]
这个应该无解，确实是被墙了，而且开代理访问也很慢，站点没有做 CDN。

**Comment by aofall** [comment]
又看见二楼说台湾了
这次台风又来了我们连着国庆放了十天假，请问你被吹走了没

**Comment by Too-Naive** [comment]
接到报告说四点要停水 台北市的供水出故障了

**Comment by imcaffrey** [comment]
我们国庆放1.2.7三天（

**Comment by Too-Naive** [comment]
还不错嘛 柯文哲说明天不用上课

**Comment by BROBIRD** [comment]
国庆1-9号放假的路过= =

**Comment by Too-Naive** [comment]
…没放假的路过

**Comment by imknown** [comment]
什么鬼...

**Comment by BROBIRD** [comment]
@Too-Naive 你们双十不是放假吗

**Comment by Too-Naive** [comment]
才一天啊

**Comment by BROBIRD** [comment]
@Too-Naive 哈哈哈哈哈哈

**Comment by Too-Naive** [comment]
笑什么 我在放假



On BROBIRD <notifications@github.com>, Oct 9, 2016 7:18 PM wrote:

@Too-Naive<https://github.com/Too-Naive> 哈哈哈哈哈哈
