### ISSUE TITLE
youtube上视频不能播

### ISSUE THREAD

**Issue by find-happiness** [racaljk/hosts#66]
youtube上视频不能播

**Comment by K-Guan** [comment]
[更改hosts后还是无法使用Google,Facebook,Twitter等服务怎么办？](https://github.com/racaljk/hosts/wiki/%E6%9B%B4%E6%94%B9hosts%E5%90%8E%E8%BF%98%E6%98%AF%E6%97%A0%E6%B3%95%E4%BD%BF%E7%94%A8Google,Facebook,Twitter%E7%AD%89%E6%9C%8D%E5%8A%A1%E6%80%8E%E4%B9%88%E5%8A%9E%EF%BC%9F)
