### ISSUE TITLE
dns服务器求推荐

### ISSUE THREAD

**Issue by lishoujun** [racaljk/hosts#660]
pc改hosts很方便，但是android和ios不越狱无法修改，所以我萌生了搭个dns服务器自用的想法。
请有经验的同学推荐一下。

打扰之处还请包涵，无论有没有推荐，一周内我会关闭这个issues。

**Comment by laodcn** [comment]
以前用过一些翻墙DNS，然后神秘组织“有关部门”约谈就关闭开放了，现在只有一些人自用而已，好久没关注了...
（hellodns好像用的是阿里云香港云服务器搭建的）

**Comment by lautis0503** [comment]
app.arukas.io自己搭，反正现在不要钱。搭什么dns，直接ss

**Comment by Too-Naive** [comment]
= =服务器抢答啊...只要是公网的服务器 都会经过gfw的骨干服务器筛选包
然后被gfw"抢答"DNS记录

**Comment by lautis0503** [comment]
曾经dnscrypt可以跑，后来也被干掉了，不知道自己搭能不能用

**Comment by imknown** [comment]
在大陆还能玩出什么花花? (/手动斜眼)

**Comment by Too-Naive** [comment]
用DNS服务器来做的话 在内网还可以 但是要是在公网搭 想太多了 DNS查询又不加密 任何中间人攻击都可以伪造
拿衣服

**Comment by andytimes** [comment]
我建议你可以买个支持刷 OpenWRT 的路由器，刷好系统后配置 dnsmasq。
如果因为要共享给别人用而自搭 DNS，那可以到这里去提问看看： https://bbs.sspanda.com/t/dns

**Comment by registe** [comment]
如果自用，完全可以用阿里云，甚至一个公司内部用也可以，就是不能public用
用docker拉dnsmasq+dnscrypt-proxy即可，我就是这么做的

**Comment by lishoujun** [comment]
谢谢大家的热情回复，收获了很多知识，因为家里刚好有一太闲置的debian笔记本，计划拿出来发挥余热。
