### ISSUE TITLE
添加两个条目

### ISSUE THREAD

**Issue by Pictor** [racaljk/hosts#664]
项目维护者：

Hosts 中缺少两个 Google 的子域名：

apikeys.clients6.google.com 来自页面 https://console.developers.google.com/apis/credentials

apis-explorer.appspot.com 来自页面 https://developers.google.com/admin-sdk/directory/v1/reference/asps/get

请考虑添加。

谢谢！

**Comment by laodcn** [comment]
https://github.com/racaljk/hosts/pull/665
