### ISSUE TITLE
如何更新racaljk/hosts时保留自有hosts

### ISSUE THREAD

**Issue by lishoujun** [racaljk/hosts#670]
有一些hosts是开发时自己用的，在后面加了racaljk/hosts的hosts
所以结构如下：

默认host
自己的host1、2、3
racaljk/hosts

这样怎么自动单独更新racaljk/hosts的hosts？

**Comment by andytimes** [comment]
更新的时候把 racaljk/hosts 放下面就行了，hosts文件优先解析最上面的规则。
需要自动更新的话，Windows 下用可以尝试这个 [终端工具](https://github.com/HostsTools/Windows) Linux 下，可以试试这个[脚本](https://github.com/racaljk/hosts/blob/master/tools/lhosts)，手动或用 crontab 定时执行都可以。

**Comment by imcaffrey** [comment]
不是有定位头么= =
https://github.com/racaljk/hosts/blob/master/hosts#L1
https://github.com/racaljk/hosts/blob/master/hosts#L3958

**Comment by Too-Naive** [comment]
对于Windows 您可以使用tool
