### ISSUE TITLE
修改Hosts后生效的方法 （通过命令行无需找飞行模式开关）

### ISSUE THREAD

**Issue by DvilAwn** [racaljk/hosts#673]
Windows

> 开始 > 运行 > CMD > 在 CMD 窗口输入

- `ipconfig /flushdns`

Linux

> 终端输入

- `sudo rcnscd restart`

> 对于systemd发行版，请使用命令

- `sudo systemctl restart NetworkManager`

> 如果不懂请都尝试下

Mac OS X终端输入

- `sudo killall -HUP mDNSResponder`

From LaoD.cn

**Comment by Too-Naive** [comment]
。。。飞行模式开关不是更快吗

**Comment by DvilAwn** [comment]
@Too-Naive From 小白 ,And 一眼喵不到飞行模式开关的童鞋\

**Comment by imknown** [comment]
拔网线最快..

**Comment by andytimes** [comment]
https://github.com/racaljk/hosts/blob/a1b66e4d5f5d363f8ee5aaec539ea71a4a5747f2/README.md

https://github.com/racaljk/hosts/commit/597a42e299331f6056012e46562a2bbc549500a9

This has been deprecated for a long time.

**Comment by hunterMG** [comment]
Write "ipconfig /flushdns" to a .bat file and double click it every time.
