### ISSUE TITLE
Is hosts secure?

### ISSUE THREAD

**Issue by 8thchef** [racaljk/hosts#674]
想问问如何检测hosts文件里面的ip是否安全，我是新手。
感谢你们的工作

**Comment by DaleXiao** [comment]
一路向西，少侠珍重。

**Comment by imcaffrey** [comment]
is hosts secure的含义和原问题不符吧。。。 还是我又理解错静静了。。。。

**Comment by Too-Naive** [comment]
= =安全性就和ip地址有关啊 难道不是吗

**Comment by imknown** [comment]
一直在裸奔

**Comment by andytimes** [comment]
hosts 只是重定向了主机和 IP 的映射。如果很注重网络安全，请防止骇客入侵路由器，不要随意连接陌生WIFI，不要点击不明链接。

**Comment by imcaffrey** [comment]
我感觉问的是如何识别反代这种吧

**Comment by racaljk** [comment]
安全我们不能保证,所以用前请自行斟酌

**Comment by cjkzwe** [comment]
@andytimes 同上

**Comment by andytimes** [comment]
@cjkzwe 已修改

**Comment by don2ccc** [comment]
。

**Comment by andytimes** [comment]
@8thchef 不好意思，答非所问了。之前没有仔细看问题描述。
问题描述问的是“如何”，我之前的回答是“是否”。

关于如何检测 hosts 里的 IP 是否安全，可以这样做：

先把 hosts 中的 IP 提取出来，然后从网络上获取 IP 信息。
比如，站长工具有一个批量查询 IP 的功能就很不错，地址： http://ip.chinaz.com/ipbatch

```shell
#!/bin/bash

curl -s https://raw.githubusercontent.com/racaljk/hosts/master/hosts |
                cut -f 1 | sort -u | sed "/#\|::/d"

```

用上面脚本可以筛选本项目的 IP，这里是我刚刚运行后，筛选出的 IP：[ip.txt](https://github.com/racaljk/hosts/files/524898/ip.txt)

把里面的 IP 复制到 http://ip.chinaz.com/ipbatch 批量查询，“IP的物理位置” 这一栏提供了 IP
的信息，根据显示的内容，大致可以知道 hosts 里面的 IP 安不安全了。

**Comment by myguybetter** [comment]
Most ips used in this file are secure. They were often found by dns resolution, and that's official. However, some ips used in this file are sniproxy ip (like 218.254.1.13 and 219.76.4.4, used in dropbox's domain). Though dropbox used ssl to encrypt the transmission, but your data will not be transferred to its official servers directly. Personally I think that might be a security problem.

**Comment by sqc1999** [comment]
First of all you should trust TLS. If you consider TLS something not secure, This issue won't be related to hosts files, you'll face MITM attacks even without hosts files.
Then TLS was designed to mitigate MITM attacks, so men in the middle(e.g. the SNI proxy) won't have any chance to know what you're doing or pretend to act like the actual server. The only thing they know is that when you tried to connect to it.
Finally, as you mentioned, your data isn't transfered directly, so there isn't any guarantee that your data will be transfered to the official server. But it is guaranteed that any data you received is from the official server as long as you use TLS.

**Comment by myguybetter** [comment]
@sqc1999 
I understand. I surely trust TLS :)
So what I mean is that, depending on this file's position and this project's sensitivity, I think it might be better not to use 3rd-party proxy services to fix the connectivity issues, even though there isn't any available ips to one domain. 
Just like the commit #689, by replacing blocked ip to an sni, FB can be connected, as long as this proxy ip not to be blocked. 
But, that's not a permanent solution. After all, this kind of service is provided by those ISPs, and we don't know when it would become invalid. Then some mobile apps don't recognize sni, so there would be problems when using these apps. 
So, personally I think sni can just be a temporary plan, not a long-time solution.

**Comment by sqc1999** [comment]
I agree that it's not a good idea to use SNI proxies in such a project.
But there is something to clarify.
- The current hosts file also relies on the compatibility with SNI. There are a lot of DNS names pointed to a single IP. In the case TLS won't work without SNI.
- The IP addresses in this project also have probability of being blocked.

Furthermore, I think all kinds of ways to get across the GFW are temporary plans. As far as I know, all these ways are able to be blocked in theory(but may cost too much). In critical situations, the government can even disconnect from the Internet physically.

**Comment by myguybetter** [comment]
@sqc1999 
Agree with you :)
I worried too much.

**Comment by wenglanmin** [comment]
@andytimes 工作量有点大，怎样才算不安全呢

**Comment by andytimes** [comment]
2016-10-16 16:03 GMT+08:00 wlm <notifications@github.com>:

> @andytimes <https://github.com/andytimes> 工作量有点大，怎样才算不安全呢
>
好像也就 200+ ip，批量查询三次即可。如何检测 ip 安全性，这个我也没有什么好的想法。

Andy

**Comment by JoneYong** [comment]
一般被qiang的网站都用的是https连接，浏览器会负责检查网站证书是不是和公司相符，当被替换证书是浏览器会提醒，所以用安全的浏览器，拉黑cnnic证书，平时不往钥匙里面添加证书信任证书就没问题

**Comment by woyaojizhu8** [comment]
可以查下whois
