### ISSUE TITLE
IE8 的 SNI 补丁链接失效

### ISSUE THREAD

**Issue by redapple0204** [racaljk/hosts#675]
http://www.microsoft.com/zh-cn/download/details.aspx?id=19257
这个网站已经无法下载==
![2016-10-04 07 06 41](https://cloud.githubusercontent.com/assets/16254644/19057250/1d79afb4-8a01-11e6-9268-d7d61ac8473a.png)

**Comment by imknown** [comment]
ID = 19257 的是什么软件? (话说 这个问题 跟 这个 hosts 有什么关系..)

**Comment by andytimes** [comment]
我 Google 到的相关问题： http://serverfault.com/questions/438637/ie8-complains-about-ssl-name-mistmatch

有一个回答提到
> no version of IE on Windows XP support SNI

**Comment by redapple0204** [comment]
@andytimes 那wiki却写着有......

**Comment by andytimes** [comment]
@redapple0204 在 XP 用 Firefox/Chrome，或者用代理访问外网。

如果愿意折腾，去下面链接找找吧：
https://www.google.com.hk/search?q=XP+IE+SNI
http://cn.bing.com/search?q=XP+IE+SNI

**Comment by andytimes** [comment]
@aofall https://en.wikipedia.org/wiki/Server_Name_Indication#Support 
这是 Wikipedia 上统计的 SNI 支持情况。里面没有提到 Windows XP 上 IE 8 可支持 SNI，
是否要修改下[为什么不推荐在移动设备上使用hosts](https://github.com/racaljk/hosts/wiki/%E4%B8%BA%E4%BB%80%E4%B9%88%E4%B8%8D%E6%8E%A8%E8%8D%90%E5%9C%A8%E7%A7%BB%E5%8A%A8%E8%AE%BE%E5%A4%87%E4%B8%8A%E4%BD%BF%E7%94%A8hosts%EF%BC%9F) 这个页面？

**Comment by aofall** [comment]
我补充上去的，说是不支持，实际上打完补丁就好了
XP早就停止提供技术支持了，这个页面被删除也是意料之中。
建议换系统，如果因为电脑太旧不能用建议换电脑，当然这是你个人的事情，我只能提个建议。(用着win7都装不了的电脑你确定你这样工作还有效率？用着都来气吧

**Comment by aofall** [comment]
哦突然想起来你还可以用国产管家卫士来打补丁

**Comment by redapple0204** [comment]
@andytimes thx!
@aofall 说实话我早都不用win了，只是无聊发现失效了而已..
