### ISSUE TITLE
github release 的github-cloud.s3.amazonaws.com实在太慢，下载老在10几k徘徊

### ISSUE THREAD

**Issue by WeihuaGu** [racaljk/hosts#677]
您好，感谢您开 Issue 来反馈信息，在提交前，请确保您已经检查了以下内容!
- 如有关" Google 无法连接" / " YouTube 视频无法播放"等问题 请参阅[常见问题解答](https://git.io/vrHaS)
- 已经阅读了 [Wiki 页面](https://github.com/racaljk/hosts/wiki)
- 已经搜索过之前的相关 [Issues](https://github.com/racaljk/hosts/search)
- 如果是报告问题，请确认问题可以复现并且没有重复报告同一个问题；如果是向 hosts 提供新的信息，请确认所提供信息的来源以及相关许可协议；欢迎使用 Pull Requests 功能（可以通过[直接编辑文件](https://github.com/racaljk/hosts/edit/master/hosts)的方式来提交）
如果您有其他附言，例如问题只在某个页面发生，或者是一般性讨论、提出新功能，请一定注明

或者您也可以卖个萌

用mtr看，从第五跳之后，基本上都是超过80%的loss。实在是受不了了，怎么破。

我们同时有一个 [Gitter Room](https://gitter.im/racaljk/hosts)，以及一个[在 Coding 上的镜像](https://coding.net/u/scaffrey/p/hosts)

**Comment by Makebignew** [comment]
都是美国ip怎么快，挂代理或者试试sni proxy
219.76.4.4 github-cloud.s3.amazonaws.com
（需要https）

**Comment by andytimes** [comment]
@WeihuaGu 访问 AWS 在国内确实很慢，还是挂代理吧。

**Comment by imknown** [comment]
我这里 经常 0.. 能下实为满足..

**Comment by Too-Naive** [comment]
似乎并不能解决这个问题吧

**Comment by redapple0204** [comment]
我这里1k/s，你算好了...

**Comment by WeihuaGu** [comment]
哎……人穷。本身下东西用axel,可是axel,aria2c 都不管用，只能用wget慢慢下，有没有什么多线程的工具是支持这个的？

**Comment by imcaffrey** [comment]
可以用c9或者coding ide之类的东西中转一下（

**Comment by WeihuaGu** [comment]
看来只能采用代理，或者中转或者离线的方法了。感谢@imcaffrey  @Makebignew提供的方法。
