### ISSUE TITLE
tumblr 视频无法播放

### ISSUE THREAD

**Issue by Mao-jiawei** [racaljk/hosts#682]
您好，感谢您开 Issue 来反馈信息，在提交前，请确保您已经检查了以下内容!
- 如有关" Google 无法连接" / " YouTube 视频无法播放"等问题 请参阅[常见问题解答](https://github.com/racaljk/hosts/wiki/The-hosts-FAQ)
- 已经阅读了 [Wiki 页面](https://github.com/racaljk/hosts/wiki)
- 已经搜索过之前的相关 [Issues](https://github.com/racaljk/hosts/search?type=Issues)
- 如果是报告问题，请确认问题可以复现并且没有重复报告同一个问题；如果是向 hosts 提供新的信息，请确认所提供信息的来源以及相关许可协议；欢迎使用 Pull Requests 功能（可以通过[直接编辑文件](https://github.com/racaljk/hosts/edit/master/hosts)的方式来提交）

如果您有其他附言，例如问题只在某个页面发生，或者是一般性讨论、提出新功能，请一定注明

或者您也可以卖个萌

我们同时有一个 [Gitter Room](https://gitter.im/racaljk/hosts)，以及一个[在 Coding 上的镜像](https://coding.net/u/scaffrey/p/hosts)

**Comment by DaleXiao** [comment]
I fixed it a couple of days ago, while my changes got reverted by people somehow.

Tumblr Video, 因缺思婷。

**Comment by andytimes** [comment]
@DaleXiao 61fc410c130037 这个 commit 是我 Revert 的。

我想申明一点，这里不会无故 Revert commit，是我懒惰没有在 6914a25ba98742a81 写 Revert 的原因。

这里的维护者都会很感激来贡献的人，扫 IP 是很繁琐的苦力活，我没有不尊重阁下的成果，但

> 31.13.66.6	tumblr.com

31.13.66.0/24 是 Facebook IP range，我不懂这是什么情况，而且实测也是打不开 Tumblr 的。
由于之前的 IP 可用，所以我 Revert 了。

如果阁下对此还有什么疑惑，可以继续讨论。

**Comment by DaleXiao** [comment]
No worries, I didn't blame anyone actually, I am also taking benefit from all of you guys, big thanks again.

When I say interesting, I was referring the people who can't live without some of the tumblr videos, lol, stay young, stay hungry.
