### ISSUE TITLE
dropbox无法预览office文件，用gmail打开邮件中的链接，会无法访问

### ISSUE THREAD

**Issue by digicolor** [racaljk/hosts#684]
dropbox预览不了office，需要添加
162.125.18.132 dl-doc.dropbox.com 才可以。
gmail一直都是可以打开邮件中的链接地址的，现在打开会无法访问，不管是不是加了https://都一样 不知道哪里有问题

**Comment by Too-Naive** [comment]
brocken和request是不一样的…

**Comment by digicolor** [comment]
谁帮忙加一下

**Comment by andytimes** [comment]
@digicolor https://github.com/racaljk/hosts/commit/375cb8a6aa00ab6f0f84485b1d2071c45bef24b9
