### ISSUE TITLE
我想请教一下  大家是怎么知道能用的ip的  

### ISSUE THREAD

**Issue by Mao-jiawei** [racaljk/hosts#685]

**Comment by Too-Naive** [comment]
我记得以前就有issue里面有提过…请善用搜索功能

**Comment by Mao-jiawei** [comment]
我是一个小白

**Comment by imknown** [comment]
* #116 
* #251 
* #258 
* #265 
* #528

**Comment by imcaffrey** [comment]
**请确保您已经检查了以下内容**

**Comment by imknown** [comment]
其实 我用的方法比较粗暴简单, 
就是 连接上 可用 VPN, 
然后 通过下面命令得到 ip 若干:
``` cmd
nslookup <host name>
```
断开VPN, 再使用 `ping` 或者 `nslookup` 验证一下 可用性.
然后 写入 `hosts` 真正验证一下 效果, 
浏览器访问可用的话, 基本说明 `ip 有效`.
ip 有问题的话, 可以尝试 多试几个 `VPN`.  
**此法不保证 `100%` 有效.**

**Comment by sqc1999** [comment]
但是这样的话是不是只能针对被DNS劫持/污染了或者做了CDN而且IP地址没有被封杀完的网站呢？

**Comment by imknown** [comment]
@sqc1999 :D 平时我用的 腾讯DNS, 还有 此法 并不是万能的. 会有很多局限性. 只是我觉得比较简单, 没有电脑也能搞, 便总结出来了 :laughing: .

**Comment by andytimes** [comment]
> 其实 我用的方法比较粗暴简单, 
就是 连接上 可用 VPN, 
然后 通过下面命令得到 ip 若干:
`nslookup <host name>`
断开VPN, 再使用 ping 或者 nslookup 验证一下 可用性.

@imknown 你的方法太麻烦了，一般在线 ping 都有国外主机，你在上面 ping 即可。

@Mao-jiawei 小白就不代表你就可以不自己去寻找问题的答案，至少先 Google 一下，提问的时候，
展示自己所做的努力，有诚意才有人肯回答你的问题

https://github.com/aofall/How-To-Ask-Questions-The-Smart-Way

建议阅读一遍上面的内容。

现在 Google IP 暂时未挂掉，我说一个搜索 Google IP 的办法：

1. 移除 hosts 的 Google 规则。访问 https://flowmemo.github.io/can-i-reach-google/
2. 里面会有一些国家的 Google 域名可访问，ping 域名即可得到 Google IP

相关博客：https://flowmemo.github.io/2016/06/11/can-i-reach-google/

@imcaffrey 我觉得可以用这个测试 hosts 是否生效。

**Comment by racaljk** [comment]
以后类似问题直接ref这个issue吧,每次都回答挺麻烦的

**Comment by imknown** [comment]
@racaljk Issues 什么时候有置顶功能就好了 (逃

**Comment by Makebignew** [comment]
@andytimes 这个方法似乎并不可行，因为现在dns污染扩大到google.* 根本找不到ip

**Comment by SimpleSimple** [comment]
如何收藏这个issue啊? 好像没看到可以收藏的地方.

**Comment by sqc1999** [comment]
@SimpleSimple 据我所知GitHub没有提供Issue收藏之类的功能。。你可以选择加到浏览器的收藏夹里。。

**Comment by tangkunyin** [comment]
@Mao-jiawei 楼主可以试试这个：
[host.sh](https://github.com/tangkunyin/DevShell/blob/master/host.sh
)
配置在环境变量中，每次使用时： sudo host.sh git

**Comment by Ir1d** [comment]
@lrinQVQ 泥说把它变成一个wiki page怎么样啊
