### ISSUE TITLE
关于Issue的模板

### ISSUE THREAD

**Issue by sqc1999** [racaljk/hosts#687]
我发现这里好多Issue的就直接带着说明用的模板发出来了，这样感觉有点奇怪啊。。
是不是应该在模板里注明一下发出来的时候把它删掉呢？

**Comment by imknown** [comment]
好像很有道理, 我居然信了.

**Comment by imcaffrey** [comment]
只是单纯地%一发绍兴大爷
99年的OIer吗

**Comment by sqc1999** [comment]
快退役的OIer。。去年联赛打残了。。

**Comment by Too-Naive** [comment]
然而并没有什么卵用 有的人完全不看模板

**Comment by sqc1999** [comment]
@Too-Naive 确实是这样，我在watch的另外一个repo也用了Issue模板，也提醒了要删除说明，结果还是有很多人看也不看就直接发出来了。。

**Comment by Too-Naive** [comment]
所以并没有必要加啊…

**Comment by sqc1999** [comment]
@Too-Naive
加了总比不加好。。
不过我也就提个建议，大家觉得不好的话就算了。。

**Comment by Too-Naive** [comment]
(个人认为是没必要……也不差这个(还不如直接去掉模板



On Stalker <notifications@github.com>, Oct 11, 2016 9:36 AM wrote:

@Too-Naive<https://github.com/Too-Naive>
加了总比不加好。。
不过我也就提个建议，大家觉得不好的话就算了。。

**Comment by sqc1999** [comment]
或者把说明放到`CONTRIBUTING.md`里面？这样的话开Issue或者PR的时候GitHub会提示你去看这个。
虽然个人感觉这个提示不太显眼。。

**Comment by imcaffrey** [comment]
之前在contributing里面 现在移除了

**Comment by lautis0503** [comment]
完全不看的人太多了，youtube相关issue已被开了N个

**Comment by Too-Naive** [comment]
#730 嗯

**Comment by Too-Naive** [comment]
我都在认为到底模板有没有用了
