### ISSUE TITLE
Is it possible to add an entity which shows the version or editing time in the hosts file?

### ISSUE THREAD

**Issue by cvca** [racaljk/hosts#69]
It has been a little bit hard to manage different kinds of versions of the hosts file.

Um...I'm wondering whether it's applicable to add an entity or line which shows the current version or last editing time in the hosts file...

I do think it will be very convenient for users or co-editors to manage these historical files in their local environment in this way.

**Comment by K-Guan** [comment]
I think this is a good idea.

**Comment by andytimes** [comment]
Github有一个release功能，比较好的管理版本。不过，我觉得没必要那么麻烦，git本身就很不错了，需要直观一些用gitg查看，Github也可以网页blame hosts，基本改动都能看到了。

**Comment by racaljk** [comment]
关于版本信息可以查看https://github.com/racaljk/hosts/commits/master/hosts

**Comment by cvca** [comment]
Thanks.

As a elementary user, my standpoint is that it will be much better if i could manage all versions of hosts releases by means of unique identities which could be added to the hosts itself  as a single line without possession of any knowledge concerning Git. And personally i do think this is a middle point which allows both users and developers to share the information itself and contribute to it.

**Comment by andytimes** [comment]
点击hosts文件，在代码框标题有 “Raw Blame History” 这几个按钮，点击Blame，可以查看改动。
本身git就是版本控制工具，再向hosts中添加这些信息，有以下几个问题。

第一：hosts文件混乱，影响心情。
第二：长此以往下去，更新记录就会占很大一部分。

**Comment by andytimes** [comment]
如下图
![00](https://cloud.githubusercontent.com/assets/7419875/10722491/ba4a24ce-7beb-11e5-88e0-18257da70a5e.png)
![01](https://cloud.githubusercontent.com/assets/7419875/10722524/029e2482-7bec-11e5-9c68-2020df91823d.png)
@cvca

**Comment by cvca** [comment]
Thanks.

We have different standpoints.

As a user, I constantly obtain the file through https://raw.githubusercontent.com/racaljk/hosts/master/hosts.

And through the file itself, by no means could I know whether the version I will download is the same with its local counterpart. I am not able to know whether it's a new release or not. So I have to log on in to GitHub to know the changes and the exact release date. Personally I think it will improve users' experience to some extent if we add the new feature.

And it won't be occupying much space if we just add a SINGLE line such as

Update : Tue, 27 Oct 2015 04:56:52 +0800                  
or
;version=201510231419

every time we issue a new version.

**Comment by andytimes** [comment]
IP失效比较快，简略的描述无意义。
下次更新，会加上一行
# last update: $date

具体要不要在hosts添加更新记录，问@racaljk （ps：最近一个星期是联系不到他的）

**Comment by fun5rt** [comment]
确实host里面加一个日期比较好啊，我也都是从https://raw.githubusercontent.com/racaljk/hosts/master/hosts 
这里直接复制host的，就会出现不知道网页上与自己系统的host是否一致的问题。

最上方加个日期就好多了。

**Comment by racaljk** [comment]
加个日期倒是没问题，更新的历史记录就没必要了吧
