### ISSUE TITLE
2016-10-11 hosts 第11行内容貌似有错？“::1	localhostfe80::1%lo0	localhost”

### ISSUE THREAD

**Issue by gjbg1989** [racaljk/hosts#690]
您好，感谢您开 Issue 来反馈信息，在提交前，请确保您已经检查了以下内容!
- 如有关" Google 无法连接" / " YouTube 视频无法播放"等问题 请参阅[常见问题解答](https://github.com/racaljk/hosts/wiki/The-hosts-FAQ)
- 已经阅读了 [Wiki 页面](https://github.com/racaljk/hosts/wiki)
- 已经搜索过之前的相关 [Issues](https://github.com/racaljk/hosts/search?type=Issues)
- 如果是报告问题，请确认问题可以复现并且没有重复报告同一个问题；如果是向 hosts 提供新的信息，请确认所提供信息的来源以及相关许可协议；欢迎使用 Pull Requests 功能（可以通过[直接编辑文件](https://github.com/racaljk/hosts/edit/master/hosts)的方式来提交）

如果您有其他附言，例如问题只在某个页面发生，或者是一般性讨论、提出新功能，请一定注明

或者您也可以卖个萌

我们同时有一个 [Gitter Room](https://gitter.im/racaljk/hosts)，以及一个[在 Coding 上的镜像](https://coding.net/u/scaffrey/p/hosts)

**Comment by Too-Naive** [comment]
Fixed in 4a6e831e1ebbc932ebe14840c12b9aa0f7b57f14
