### ISSUE TITLE
lhosts 脚本里为什么要更新其中的 localhost 为 `hostname`

### ISSUE THREAD

**Issue by tigerZhang86** [racaljk/hosts#691]
<code>lhosts</code>脚本里为什么要更新其中的<code>localhost</code> 为<code>hostname</code>
我在使用其他一些软件的时候，有些配置默认的是<code>http://localhost:xxx/xxxx/</code>,但是因为<code>hosts</code>里面127.0.0.1 对应的值被改为<code>hostname</code>，会导致一些不必须要的修改，想请问作者这么做的意义在于？

**Comment by sqc1999** [comment]
Linux下hosts文件里如果没有hostname到回环地址的映射的话会有奇怪的错误的。。

**Comment by sqc1999** [comment]
而且如果我没记错的话就算hosts里不加，localhost也是默认解析到回环地址。

**Comment by tigerZhang86** [comment]
@sqc1999 我使用 Mac OS X 10.11.6，如果<code>hosts</code>里不加<code>localhost</code>确实解析不到回环地址<code>127.0.0.1</code> ,不知道是否本机哪里配置有问题，遇到过两款软件出现问题都是因为在访问localhost地址异常导致。
我觉得可以不用替换,直接在<code>hosts</code>加入<code>127.0.0.1 localhost</code> 即可.

**Comment by sqc1999** [comment]
Mac OS我不熟悉，反正WIndows和Linux都是没问题的。。
这样的话看起来还是加上的好。

**Comment by andytimes** [comment]
@tigerZhang86 之前有人反馈 [localhost](https://github.com/racaljk/hosts/issues/428) 相关问题，
所以做了把 localhost 更新为 `hostname` 的操作。但最后也不知道他是怎么解决的。

刚刚网上搜了一下相关 man 手册和文章：
http://what-is-what.com/what_is/127.0.0.1.html

目前大多数操作系统，localhost 一般是 127.0.0.1 的别名，正常情况 DNS 也把 localhost 解析为
127.0.0.1

出现阁下所述的问题，应该是这样：
```hosts
# Localhost (DO NOT REMOVE)
127.0.0.1	xxxx
255.255.255.255	broadcasthost
::1	localhost
```

由于 localhost 被修改成 xxxx，所以真正解析的应该是这一条（可以用 `ping localhost` 检验）
`::1        localhost`

这样确实不好，脚本应该取消替换 hostname 操作。

**Comment by tigerZhang86** [comment]
@andytimes 脚本在执行后，是把所有的 <code>localhost</code>全部替换为了<code>hostname</code>，也就是这样：
<code>
127.0.0.1       xxxx.local
255.255.255.255 broadcasthost
::1             xxxx.local
fe80::1%lo0     xxxx.local
</code>

**Comment by andytimes** [comment]
@tigerZhang86 不好意思，我忘了执行的是全局替换，那 localhost 由 DNS 解析，应该也没什么问题，
除非机器是断网状态。稍后我会抽时间检查脚本。
