### ISSUE TITLE
Google play store 可以打开，访问都没有问题，但是软件下载不了（随便一个很小的软件，显示一直在安装）

### ISSUE THREAD

**Issue by jake450544590** [racaljk/hosts#692]
Google play store 可以打开，访问都没有问题，但是软件下载不了（随便一个很小的软件，显示一直在安装），是不是Google play store 浏览 和 下载软件用的地址不一样，hosts文件里只有浏览的地址，没有下载的地址呢？或者是其他原因？希望能解决一下或给一个答复。
**感谢你们的无私付出！**

**Comment by imknown** [comment]
跟 YouTube 不能看 视频一个道理.
https://github.com/racaljk/hosts/issues?utf8=%E2%9C%93&q=play
https://github.com/racaljk/hosts/wiki/The-hosts-FAQ

**Comment by gjbg1989** [comment]
APKPure 替代 Google play store https://m.apkpure.com

**Comment by CHN008** [comment]
APKPure上面的版本和GooglePlay还是有差别的

**Comment by lautis0503** [comment]
Google Play Store中的部分应用会根据安卓版本和地区来决定该下载哪个版本（虽然我只见过官方应用这样做），APKpure肯定是不会这样的，而且更新频率也不明。

**Comment by aofall** [comment]
这个也是 @imcaffrey

**Comment by liangyuteng0927** [comment]
GooglePlay下҉载҉app还是用ss吧，hosts基本上不行的，而且国内ip容易被锁国区或者封号（购买的话）

**Comment by gjbg1989** [comment]
“APKpure肯定是不会这样的”？
APKpure已更新shadowsocks 3.2.5 版给安卓4.4.4，在安卓4.2.2上新装的是shadowsocks 3.0.4

**Comment by yinyachao** [comment]
我也是 在家移动网可以下载  来亲戚家电信网不能下载了  找到一个备用商店应用还挺全地址:[uptodown][](https://uptodown-android.cn.uptodown.com/android)

**Comment by beyondgfw** [comment]
@yinyachao 项目已迁移至新仓库：googlehosts/hosts，本仓库不再更新，开新Issues/Pull requests请前往新仓库，谢谢。

另：Google家的最近的确不太能用。

@racaljk 方便的话可以把这个仓库 archive 一下
