### ISSUE TITLE
hosts在Mac OS生效但是在Windows不生效？是闪讯的原因吗？

### ISSUE THREAD

**Issue by ewnit** [racaljk/hosts#693]
已经更新到最新hosts文件。尝试过ipconfig/flushdns。
因为Mac在公司使用，windows PC在学校使用。所以想来想去是闪讯的问题或是windows防火墙问题？有人遇到过相同的情况吗？

**Comment by racaljk** [comment]
检查一下hosts文件格式，还真不太清楚防火墙是否会影响hosts，你可以去百度搜索一下

**Comment by verlen** [comment]
禁用了防火墙，文件格式也改过，也禁用了DNS Client 还是没啥用。

**Comment by Too-Naive** [comment]
用hosts工具试试

**Comment by outnnn** [comment]
先把电脑hosts改成默认，然后把 google hosts替换，注意编码格式
