### ISSUE TITLE
关于项目内的 Google IP

### ISSUE THREAD

**Issue by andytimes** [racaljk/hosts#696]
```shell
PING 220.255.2.153 (220.255.2.153) 56(84) bytes of data.
64 bytes from 220.255.2.153: icmp_seq=1 ttl=41 time=211 ms
64 bytes from 220.255.2.153: icmp_seq=2 ttl=41 time=210 ms
64 bytes from 220.255.2.153: icmp_seq=3 ttl=41 time=211 ms
64 bytes from 220.255.2.153: icmp_seq=4 ttl=41 time=208 ms

--- 220.255.2.153 ping statistics ---
4 packets transmitted, 4 received, 0% packet loss, time 3003ms
rtt min/avg/max/mdev = 208.018/210.372/211.806/1.497 ms
```

这个新加坡 GGC IP 连接速度较慢，是否可以考虑更换 Google IP。

```shell
PING 64.233.188.214 (64.233.188.214) 56(84) bytes of data.
64 bytes from 64.233.188.214: icmp_seq=1 ttl=35 time=54.1 ms
64 bytes from 64.233.188.214: icmp_seq=2 ttl=35 time=53.9 ms
64 bytes from 64.233.188.214: icmp_seq=3 ttl=35 time=53.6 ms
64 bytes from 64.233.188.214: icmp_seq=4 ttl=35 time=54.0 ms

--- 64.233.188.214 ping statistics ---
4 packets transmitted, 4 received, 0% packet loss, time 3004ms
rtt min/avg/max/mdev = 53.653/53.945/54.105/0.333 ms
```

在线 ping 发现，电信宽带使用新加坡 GGC，速度普遍较慢，64.233.188.214 的 ping 值普遍较低。

虽然没有问题就不必更新，但是对于电信宽带，新加坡 GCC 的 ping 值确实有些高了。

是否需要更换 Google IP？
@racaljk @Too-Naive @imcaffrey @imknown

**Comment by Too-Naive** [comment]
主要是考虑ISP出口 个人认为的话 这点延迟还是可以忍受的

**Comment by imcaffrey** [comment]
说实话很好奇为什么现在这个ip一直很稳
关于要不要换呢 个人观点是要留下快的

**Comment by andytimes** [comment]
SCaffrey <notifications@github.com>于2016年10月13日周四 下午11:01写道：

> 说实话很好奇为什么现在这个ip一直很稳
>
可能 IP 也不是想封就封，需要考虑其他因素，或者就是懒得动。

> 关于要不要换呢 个人观点是要留下快的
>
用新加坡 GGC，Google 搜索时，跳转到目标网页较慢，更新 hosts 后，
我一般都是换成其他 Google 官方 IP，个人认为新加坡 GGC 完全可以
留做备用。

Andy

>

**Comment by racaljk** [comment]
可以，那就现在这个留作备用吧

**Comment by laodcn** [comment]
說實話，現用的ip是我用過最久的，最穩定的。

**Comment by andytimes** [comment]
laodcn <notifications@github.com>于2016年10月14日周五 下午2:19写道：

> 說實話，現用的ip是我用過最久的，最穩定的。
>
不好意思，忘记 at 你了。

我个人觉得这个新加坡 GGC IP 作为 *默认* 选项并不合适。

可能不少缓存服务器带宽确实会比 Google 官方 IP 要高，也不易被
GFW 干扰。但是，此 IP 在电信带宽上，延迟明显偏高。如果没记错，
这个 IP 曾经因为这个缘故被弃用过。

其实高质量的 GGC IP 有很多，完全不用过于留恋某一个。

hosts 提供给了多数人用，不同宽带延迟差距过大的情况应该是要
避免的。而且 hosts 能提供的 Google 网页服务，虽然消耗不了多少
流量，但如果可以，也应该优先使用官方 IP。之前出现的访问 Google
搜索需要输入验证码的情况，也让人有些质疑是不是因为使用 GGC 的
缘故。

另外提一下，64.233.188.214 不够稳定，如果要替换，
推荐使用 172.217.24.238 （带宽高，延迟低）

这两枚官方 IP 证书是 *.google.com，220 开头的证书应该是 google.com

当然，也可以不用在意我的观点，我看了 git log，这个 GGC IP 之前是
被我移除的，这么久了，也没有人反馈 Google 慢速，可能改不改都没
所谓的。

Andy

>

**Comment by lautis0503** [comment]
陕西联通 
172.217.24.238不稳定，Google首页有时打不开
64.233.188.214暂时没发现问题，ping值最低
220.255.2.153跳转慢，ping值最高

**Comment by andytimes** [comment]
Lautis Sun <notifications@github.com>于2016年10月15日周六 下午3:32写道：

陕西联通
172.217.24.238不稳定，Google首页有时打不开
64.233.188.214暂时没发现问题，ping值最低
220.255.2.153跳转慢，ping值最高

这样看来，选择合适的 Google 官方 IP，确实让人困扰。

说一个无关话题，之前一直没注意，Windows 10 解析 hosts 和 Linux
解析 hosts 的方式不一样。如果单条域名存在多 IP，
Linux 将域名解析为最先出现在 hosts 中的 IP，而Windows 10（没测试
其他Win版本）似乎是更加“智能”，往往可以将域名解析到比较合适的 IP

Andy

**Comment by aofall** [comment]
GGC的话是看ISP之间的路由表配置 简单来说就是有没有合作或者交钱。

GWS的话我国三大运营商都有直接的接入，所以不论是哪个运营商丢包和延迟都很低，但因为IP段固定且公开的原因被受防火墙的关注，时不时会出现延迟或者丢包突高的情况，不是很稳定。

而GGC的带宽就需要看持有者的主机的配置了，有的挺大的有的是小水管，比如印尼有一段延迟丢包很低，但是带宽很低(用HK的VPS测试，排除墙和国际出口QoS的干扰了)，而GWS不用说，既然是谷歌官方的肯定是杠杠的。

至于你提到的使用GGC出现验证码的问题，我想应该是三级运营商或者部分地区的NAT惹得祸，因为即使是用GGC谷歌也是可以知道你的公网IP的，这点和那些SNIProxy 完全不同

--------

在XX-Net里出现验证码的原因有很多，这些综合起来验证码频出也是正常

1是XX NET用的Google APP engine，出口是统一的，人一多不论是哪个网站都会认为是spam吧

2是和XX NET(GoAgent)的工作模式有关，在最早的GoAgent里有一个东西就是将数据包连接分包传输，优点就是在进行TCP长连接的时候避免干扰断流而造成影响(在看YouTube的时候特别明显)，不过分包传输如果有bug的而被认为是异常流量的话也会被触发验证码

3是XX NET的丢包重传，传多了就被当作是DDoS了，实在无解

**Comment by andytimes** [comment]
@aofall  👍
所以说，在 hosts 项目里用 GWS 还是不够稳定，使用 GGC 肯定稳定一些，但引用
进来就容易被封，那就等 220.255.2.153 挂了再考虑更换吧。

XX-Net 我记得默认的 appid 是共用的。其实我很不解，GAE 一直被用作爬墙，
Google 好像都没有作出什么反应。

**Comment by woyaojizhu8** [comment]
@aofall @andytimes 我使用新加坡gcc ip也经常出现要求输验证码的界面，而且我是电信，有公网ip，那出现这种情况会是什么原因呢？

**Comment by andytimes** [comment]
@woyaojizhu8 不是很清楚，如果还有出现验证码的情况，可以替换成谷歌官方 IP，
64.233.188.214
172.217.24.238
