### ISSUE TITLE
Tumblr比较快的host

### ISSUE THREAD

**Issue by alexhua** [racaljk/hosts#699]
```
tumblr.com = 66.6.33.193
tumblr.co = 66.6.32.4
api.tumblr.com = 66.6.32.4
www.tumblr.com = 66.6.32.4
cynicallys.tumblr.com = 66.6.32.22
mx.tumblr.com = 66.6.32.22
vt.tumblr.com = 66.6.33.22
ls.srvcs.tumblr.com = 66.6.32.162
px.srvcs.tumblr.com = 66.6.32.162
assets.tumblr.com = 119.160.254.197
secure.assets.tumblr.com = 119.160.254.215
secure.static.tumblr.com = 54.182.6.6
media.tumblr.com = 66.6.44.4
```
别的host粘过来的， 比现在这个速度快很多，能否考虑更新一下?

**Comment by andytimes** [comment]
@alexhua 不是别的 hosts 粘过来的，是这里之前的：

https://github.com/racaljk/hosts/commit/f459b29327e93bdda0583c32bc0b5a8a0004601d

但之前的 media 部分域名有问题。

**Comment by alexhua** [comment]
好吧 现在是彻底上不去了，用我贴的这个还能上。有时视频被定向到vtt.tumblr.com会打不开 因为hosts里没这个dns记录。网络环境 BJ联通 移动效果一样。

**Comment by andytimes** [comment]
> 有时视频被定向到vtt.tumblr.com

@alexhua 域名开头是 vtt 还是 vt？

**Comment by alexhua** [comment]
vtt.tumblr.com 无误

**Comment by andytimes** [comment]
@alexhua 麻烦你测试下刚刚更新的 hosts，我没有 Tumblr 账号。

**Comment by alexhua** [comment]
好的

**Comment by alexhua** [comment]
@andytimes 速度没问题了 vtt也没问题了 不过vt不行了 建议用这条vt.tumblr.com=54.230.74.143

**Comment by imcaffrey** [comment]
54.230.74.143 landed.
