### ISSUE TITLE
建议给个已经整理好格式的可以直接下载的txt文件，爪机无力，复制4000行真心辛苦，还没有换行

### ISSUE THREAD

**Issue by sabbc7** [racaljk/hosts#7]
建议给个已经整理好格式的可以直接下载的txt文件，爪机无力，复制4000行真心辛苦，还没有换行

**Comment by sabbc7** [comment]
先行谢过

**Comment by sabbc7** [comment]
最好能给个windows和linux格式的

**Comment by yy1300326388** [comment]
非常的赞同

**Comment by whinamp** [comment]
这是有多懒，用notepad改换行符有那么费事啊？

**Comment by racaljk** [comment]
@sabbc7 @yy1300326388 如果增加txt文件那每次都需要更新hosts和hosts.txt文件，多此一举

你可以直接访问https://raw.githubusercontent.com/racaljk/hosts/master/hosts
