### ISSUE TITLE
The latest hosts caused the GoAgent can't work

### ISSUE THREAD

**Issue by daviestang** [racaljk/hosts#70]
The latest hosts updated on 22-Oct-2015 caused the GoAgent can't work. It displays "403. That’s an error. Your client does not have permission to get URL". After revert to previous days hosts file, it worked again. I guess some gae related ip address were changed and that introduced this issue.

**Comment by andytimes** [comment]
最近更新的IP不可以用在Goa|||gent上，仅提供谷歌服务，只有64.233.162.81-87这7个IP可以。

Davies Tang <notifications@github.com>于2015年10月23日周五 下午11:42写道：

**Comment by daviestang** [comment]
Another question: Where did you get these hosts IP address ? I checked the code in this repo, That's only an updated tool which used to get hosts file from this github repo. Can you share the method of how to get hosts IP address ? Or some google IP scanner ?

**Comment by andytimes** [comment]
去Google官方网站查询Google IP范围，然后用nslookup和dig这两个工具寻找IP，加上站长工具ping全国测试，Google IP段是有规律的，比如64段的125和188这两个IP，提供google服务。

**Comment by wuxufang** [comment]
既然普通人能查到google ip范围，那GFW为什么不把这些公开的ip全封了？还是像楼上说的，作者用的其他方法。

**Comment by whinamp** [comment]
@wuxufang 这有什么难理解的？彻底封死是最愚蠢的办法，这只会推动翻墙技术的不断变化发展，变得越来越难监控和引导。留出渠道让朝廷可以随时监控难道不比把大家逼到采用其他更难监管的渠道去大海捞针似的找和堵更聪明？

**Comment by LiboDing** [comment]
wow....

**Comment by andytimes** [comment]
@wuxufang https://support.google.com/a/answer/60764?hl=zh-Hans 参见这个链接，我寻找Google IP仅仅是通过 gmail邮件相关的IP列表，实际上Google IP的范围很广泛，持有的IP数量巨大，当然这些IP不一定都会公开，而且会根据业务调整。

所以，@whinamp 说的是一方面，另一方面，IP封锁第一存在技术问题，没有想象中那么简单；第二是，也要考虑一些后果，比如误杀之类，还有对国际互联网的影响。
