### ISSUE TITLE
更新维基百科有关的hosts文件

### ISSUE THREAD

**Issue by techyanWP** [racaljk/hosts#706]
根据 Greatfire 的结果，自 10 月 13 日起，吴语和粤语维基百科在中国大陆被封锁。另据编者发现，维基媒体基金会在欧洲的数据中心（91.198.174.192）访问通常比原先在美国西海岸的数据中心更加稳定（原 198.35.26.96 的 IP 曾数次被 GFW 屏蔽），且速度影响不大，因此请求增改这些 hosts 。

91.198.174.192 wuu.wikipedia.org
91.198.174.192 zh-yue.wikipedia.org
91.198.174.192 zh.wikipedia.org
91.198.174.192 zh.m.wikipedia.org

**Comment by Too-Naive** [comment]
您可以使用pr來提交更改



On techyanWP <notifications@github.com>, Oct 18, 2016 11:06 PM wrote:

根据 Greatfire 的结果，自 10 月 13 日起，吴语和粤语维基百科在中国大陆被封锁。另据编者发现，维基媒体基金会在欧洲的数据中心（91.198.174.192）访问通常比原先在美国西海岸的数据中心更加稳定（原 198.35.26.96 的 IP 曾数次被 GFW 屏蔽），且速度影响不大，因此请求增改这些 hosts 。

91.198.174.192 wuu.wikipedia.org
91.198.174.192 zh-yue.wikipedia.org
91.198.174.192 zh.wikipedia.org
91.198.174.192 zh.m.wikipedia.org

**Comment by outnnn** [comment]
123

**Comment by outnnn** [comment]
事实上谷歌应该出更多的ip :-)
