### ISSUE TITLE
最近很多国内可以正常访问com域名网站出现问题

### ISSUE THREAD

**Issue by leoshh** [racaljk/hosts#708]
如新浪微博（有2天都上不去）、geforce论坛（这个也会被封？），还有更多的网站则是一开始上不去，刷新几下才行如apkmirror、远景

**Comment by DaleXiao** [comment]
Location?

**Comment by Too-Naive** [comment]
可能是小包间吧 新疆之类的

**Comment by leoshh** [comment]
是上海电信

**Comment by Too-Naive** [comment]
请咨询ISP

**Comment by YiloPo** [comment]
替换换了hosts文件之后浏览器登录microsoft账号登不上，改回默认hosts文件之后就可以登录。

**Comment by leoshh** [comment]
@YiloPo 同网下微软的我手机APP也是退出后再登陆登不上，电脑倒是没问题的

**Comment by laodcn** [comment]
近期有不少人反映微软账户live、outlook等登录不上，但是我这里正常，不知道是不是地区的问题，貌似Microsoft没有被墙，可以考虑移除。

**Comment by Too-Naive** [comment]
@laodcn 我觉得主要是慢

**Comment by laodcn** [comment]
@Too-Naive 鉴于近期太多类似的问题，我感觉Microsoft完全可以移除，因为很多人默认不使用可以登录，用了Microsoft hosts反而不行。

**Comment by Too-Naive** [comment]
@laodcn onedrive之类的？

**Comment by laodcn** [comment]
@Too-Naive 是的 微软账户

**Comment by Too-Naive** [comment]
@laodcn 现在没在国内没法测试了 以前似乎一直连不上onedrive的说

**Comment by CHN008** [comment]
我这里OneDrive可以打开

**Comment by leoshh** [comment]
更新后好了

**Comment by imcaffrey** [comment]
@andytimes 可以用 'fixes #id' / 'closes #id' 之类的句式:)

**Comment by andytimes** [comment]
2016-10-22 19:06 GMT+08:00 SCaffrey <notifications@github.com>:

> @andytimes <https://github.com/andytimes> 可以用 'fixes #id' / 'closes #id'
> 之类的句式:)
>
提交记录里最好用完整的网址， 仓库存放在别处，或者本地查看都比较方便。

Github 提供的这些自动操作很便捷，链接好像可以被识别成 Issue 号，合适
的情况下，可以这样用，如果 Issue 还在讨论，自动关闭不是很合适。

Andy

**Comment by Too-Naive** [comment]
关闭意味的是 解决了问题吧。。 个人认为关闭并不影响讨论
