### ISSUE TITLE
getHosts.py这个更新程序Mac os 可以使用么？

### ISSUE THREAD

**Issue by fun5rt** [racaljk/hosts#71]
自己尝试了下，不会用。。

**Comment by racaljk** [comment]
只要macos预装了python就可以使用

**Comment by racaljk** [comment]
果然脚本还是对普通用户太难...之后我可能会考虑重写gui

**Comment by fun5rt** [comment]
是的。看不懂，有详细教程照着做差不多能成功。我试了下iSystem这个程序，也是没成功。。

我希望的就是有个一程序可以mac后台运行着，可以自动更新这里的host。目前我都是隔一段时间自己手动替换hosts，有点麻烦。

**Comment by racaljk** [comment]
@fun5rt 那好吧，我试着写一个简洁的图形界面程序，完成后可能会需要你帮忙测试，希望能保持联系

**Comment by fun5rt** [comment]
好的，没问题

**Comment by K-Guan** [comment]
@racaljk 实际呀……你写一个自动配置的脚本，就几行`raw_input()`，然后运行后就可以自动启动并更新不就好了？

**Comment by racaljk** [comment]
gui对用户friendly一些，脚本也不是不行，但现在我什么都做不了了，因为我马上就要走了，估计又会度过一周原始无网生活。

@fun5rt 非常抱歉，现在我没有时间来完成我之前提到的gui，我会考虑设置todo list task，在近期完成它.

**Comment by K-Guan** [comment]
@racaljk 明明今天才周六……是否需要我帮忙？怎么说我也是会点PyQT的，不过我对于Mac一无所知，摸都没摸过是个问题……

**Comment by fun5rt** [comment]
没有gui其实也可以，只要能更新下详细一点的操作步骤也可以，当然有是更好的了。

不敢想象竟然有一周没有网...

**Comment by racaljk** [comment]
@K-Guan GUI考虑用C++ with QtGuiLibrary开发，所以没事去学学C++吧:)

**Comment by K-Guan** [comment]
@racaljk 唉？那么麻烦干嘛？论我对C++一窍不通

**Comment by racaljk** [comment]
@fun5rt 其实已经够详细了...我手头没有macos，所以也不太清楚具体情况，不过我想应该类似于https://github.com/racaljk/hosts#gnulinux的方法，你可以让@K-Guan帮助你写一个定时执行/计划任务获取hosts的脚本，当然如果他有时间而且愿意的话.

**Comment by fun5rt** [comment]
我打开Terminal 输入wget 显示-bash: wget: command not found

输入curl显示：curl: try 'curl --help' or 'curl --manual' for more information

然后输入下面的网址，让我录入密码，结果还是不行显示：No such file or directory

**Comment by racaljk** [comment]
你应该没有安装wget，关于如何安装wget可以参考http://www.zhihu.com/question/19863831

这里有一个简单的教程教你如何修改hosts
http://mtnt2008.iteye.com/blog/888821

**Comment by royJang** [comment]
@fun5rt iSystem哪里没有安装成功，可以联系我。

**Comment by owenyaa** [comment]
@racaljk 我也可以测试mac 的gui
