### ISSUE TITLE
Add armorgames.com

### ISSUE THREAD

**Issue by sqc1999** [racaljk/hosts#711]
93.184.220.39	cache.armorgames.com
    93.184.220.39	gamemedia.armorgames.com
    93.184.220.39	quests.armorgames.com
    93.184.220.39	armatars.armorgames.com
    93.184.220.39	agi.armorgames.com
armorgames的一些静态内容用的是Verizon的CDN服务，我这里似乎上不去（浙江绍兴移动）。
开PR太麻烦了，所以就贴到Issue里来了。。

**Comment by imcaffrey** [comment]
开pr可以直接在hosts文件那里edit
然后会自动给你开一个叫patch的branch的

**Comment by sqc1999** [comment]
@imcaffrey 这个我知道，然而强迫症患者并不想fork这个库。。

**Comment by imcaffrey** [comment]
https://github.com/racaljk/hosts/edit/master/hosts 酱紫？

**Comment by sqc1999** [comment]
算了，fork就fork吧。。
