### ISSUE TITLE
Stars over 8k Celebration

### ISSUE THREAD

**Issue by Ir1d** [racaljk/hosts#715]
> To celebrate that our project's stars over 8k, this issue will be closed in one week.

为庆祝我们的hosts项目Stars到达八千，特开此Issue，为让大家也放松下。  

所以诸位维护本项目也都辛苦了，我刚刚看了下Commits也到达了811，大家在本Issue里面想说什么就说什么吧（But please don't trash this celebration or let it on fire, just relax）。

祝大家愉快。

最后说一个无关这个 issue 的话，我还是希望更多朋友用 hosts 来学习，不要做多余的事情。

// 传统项目 #142 #392

**Comment by imcaffrey** [comment]
截止本comment，我们的：

- Stars: 8,012
- Commits: 811

-------------------

再次感谢各位对我们的项目持续的维护和支持！

**Comment by Too-Naive** [comment]
![](https://cloud.githubusercontent.com/assets/16496671/14854755/80a24440-0cc3-11e6-90c8-549f0c052ef3.jpg)

**Comment by Too-Naive** [comment]
为什么都是放松一下

**Comment by sy618** [comment]
我一直有个疑问：“racaljk“到底是个人账户还是一个团队的总称？一直没看到
racaljk本人出现～

**Comment by Too-Naive** [comment]
是owner

**Comment by sqc1999** [comment]
路过

**Comment by sqc1999** [comment]
@sy618 是个人账户，前段时间还在ta的另外一个仓库里开过issue。。

**Comment by racaljk** [comment]
:sad:
怒刷存在感
最近在写模版库所以没怎么来水...

**Comment by Too-Naive** [comment]
![](https://cloud.githubusercontent.com/assets/16496671/17828062/95155038-66ba-11e6-83c3-d2edd5bbcec5.gif)刷存在不是开10000000000000个issue吗XD

**Comment by sihebi** [comment]
加油！

**Comment by imcaffrey** [comment]
@Too-Naive 因为还是@K-Guan 的那段话
@racaljk scl吗 愿闻其详

**Comment by Too-Naive** [comment]
休息完了 该干活了

**Comment by imknown** [comment]
不明觉厉

**Comment by Ir1d** [comment]
静静的一周只有四天 摊手

**Comment by sqc1999** [comment]
@Ir1d 你怎么改名字了，我乍一看还以为来了一个奇怪的人。。

**Comment by Too-Naive** [comment]
![](https://cloud.githubusercontent.com/assets/16496671/19808549/fc7b50e6-9d57-11e6-8d8e-193b793cf4da.jpg)

**Comment by Ir1d** [comment]
@sqc1999 的确挺怪的 我也不是很懂静静（@Too-Naive）
改名字是因为有天我突然想 SCaffrey 一直是个 OIer 该多好 （笑
