### ISSUE TITLE
我有个疑问，望奢教！

### ISSUE THREAD

**Issue by sy618** [racaljk/hosts#716]
一直以来有这么个疑问一直没搞明白，请教下：
1.在hosts里的汤不热比如说
66.6.32.4	 www.tumblr.com
这条的IP是 66.6.32.4 ，我用ping命令不通的，路由跟踪也无法到达目标服务器。但应用在hosts里汤不热却能正常打开，这是为什么？汤不热服务器端设置禁止ping了吗？
2.假如服务器端禁止ping命令，那么我们该怎样去确认目标IP是否能连通？

**Comment by Too-Naive** [comment]
某些服务器会抛掉请求回应的ICMP包
我的解决办法是tcping(over tcp)
tcping某端口 和icmp一样会回应(但是我并不清楚会不会握手然后建立连接之类的)

初步解答一下疑惑 还请其他项目高人指点一下 提高我的知识水平

**Comment by sy618** [comment]
感谢楼上回答，我刚才也找了些资料，可以用TCP ping得通。
那么若IP被墙了，是不是连TCP ping都无法连通了呢？

**Comment by sy618** [comment]
刚测试了tcping命令，发现已被墙了的IP也可以tcping通，那么这个命令是无法用来分辨IP是否被墙了。
问题是如何分辨IP是否被墙或者被服务器禁止ping呢？

**Comment by sqc1999** [comment]
@Too-Naive 我猜测tcping的原理就是进行TCP的三次握手然后直接发送FIN或RST关掉连接，根据第一个SYN后服务器响应的SYN+ACK来测算延时。
@sy618 我自己试了一下被墙的IP地址是不能tcping通的，能不能给出你从哪里下载的tcping程序以及tcping了哪个IP？

**Comment by sqc1999** [comment]
你们是怎么做到在半夜发comment的。。莫非人在墙外？

**Comment by sy618** [comment]
我已经搞明白了！谢谢以上交流的各位。
此问题关闭！

**Comment by sy618** [comment]
我已经搞明白了！谢谢以上交流的各位。
此问题关闭！

**Comment by sy618** [comment]
我已经搞明白了！谢谢以上交流的各位。
此问题关闭！

**Comment by Too-Naive** [comment]
@sqc1999 我的确在墙外呀(笑

**Comment by Too-Naive** [comment]
重新看了一下 我认为他说的被墙的ip是汤不热的那个ip吧 @sqc1999

**Comment by sqc1999** [comment]
@Too-Naive 这样吗，不知所措。。

**Comment by sqc1999** [comment]
@Too-Naive 不像吧，ta不是自己都说了tumblr是可以打开的

**Comment by sqc1999** [comment]
@sy618 我刚刚想到了另外一个可以判断是否被墙的方法：
用tracert跟踪路由系信息，如果中断的地方是某个国内IP（往往是骨干网IP），那么一般是被墙了，如果中断的地方是墙外，那就是别的原因了

**Comment by Too-Naive** [comment]
有可能在地区就被抛弃了

**Comment by sqc1999** [comment]
@Too-Naive 我好像遇到的都是在骨干网IP地址中断的，讲道理如果是GFW的话应该是放在骨干网上的，如果是地方的ISP封的话应该是就在地方断了吧
