### ISSUE TITLE
gmail有有功能打不开

### ISSUE THREAD

**Issue by jetbe** [racaljk/hosts#717]
gmail中写邮件，从通讯录中添加不了收件人，应该是有域名没有指向，每次添加收件人都要用VPN，求助，各位辛苦了！

**Comment by sqc1999** [comment]
gmail又通讯录功能，在哪里啊，我也要用

**Comment by imcaffrey** [comment]
@sqc1999 有的啊 感觉挺醒目的

**Comment by sqc1999** [comment]
求上图，刚刚找了一圈，完全找不到。。

**Comment by imcaffrey** [comment]
似乎就是什么 add to circles？
上图啊。。。 退役狗做不到啊

**Comment by sqc1999** [comment]
原来那个叫circles啊，所以我就看不懂了嘛，叫contacts多好啊

**Comment by sqc1999** [comment]
@imcaffrey 那个circles不是Google+的东西吗。。
而且并没有找到add to circles，倒是找到了add to contact，然后是能添加到联系人里去的，并没有@jetbe说的现象

**Comment by Too-Naive** [comment]
感觉可以做个测试脚本啥的...

**Comment by imcaffrey** [comment]
不是吧… 不是gmail也可以加的… 说不清

**Comment by outnnn** [comment]
事实我感觉这个功能很鸡肋，大多数人都没有使用email（就目前中国来看）的习惯，在我手机gmail上可以添加联系人，提前你要把通讯录里联系人的email编辑上去
