### ISSUE TITLE
ajax.googleapis.com not working

### ISSUE THREAD

**Issue by sqc1999** [racaljk/hosts#719]
为什么别的googleapis的域名都用的是`220.255.2.153`，就`ajax.googleapis.com`用的是`64.233.188.214`，而且这个IP地址好像是已经被封了的。。
我自己测试了一下把`ajax.googleapis.com`指向`220.255.2.153`是可以正常工作的啊。

**Comment by dencey** [comment]
+1

**Comment by Too-Naive** [comment]
这个不是被墙....我所在的地区也无法ping通
