### ISSUE TITLE
TODO list for hosts project

### ISSUE THREAD

**Issue by racaljk** [racaljk/hosts#72]
- [x] 开发新的GUI图形界面
考虑到之前的[hosts_tool gui](https://github.com/racaljk/hosts/tree/master/hosts_tool/hosts_tool_source)不支持https的GET请求，加之存在这方面的需求(#71，所以想尝试开发一个跨平台的图像界面程序， 需求如下
- 支持从 https://raw.githubusercontent.com/racaljk/hosts/master/hosts 获取最新hosts
- 支持从其它项目获取hosts
- 快捷建立Issue

- [x] 更简洁的README.MD<br>
这个很有必要，我希望README.MD是对不同水平的用户友好，不是非常必要的信息尽量不要体现在README.MD(可作为超链接链至OTHER.MD)

- [x] ~~为hosts project添加一个漂亮的logo~~
 ![](http://cdn-img.easyicon.net/png/11615/1161504.gif)
~~不定期更新时会使用google doodles作为logo，故暂时不使用固定的logo图标。~~

**Comment by owenyaa** [comment]
你好，这个GUI应该怎么运行？

**Comment by racaljk** [comment]
@owenyaa 你可以使用qtlib进行编译;
如果是以使用为目的请直接[下载exe文件](http://pan.baidu.com/s/1hqApcPI)

**Comment by K-Guan** [comment]
唉？效率挺高的嘛。已经写好了？

**Comment by owenyaa** [comment]
真的谢谢，另外，大神有写入openwrt的程序吗？  能够自动获取更新一键写入路由器的神器，。。。 上个google真心不容易啊

**Comment by racaljk** [comment]
@owenya 抱歉，我没用过openwrt
不过这里有一篇关于openwrt自动更新hosts的文章你可以看看https://github.com/racaljk/hosts/wiki/OpenWRT%E8%B7%AF%E7%94%B1%E5%99%A8%E5%A6%82%E4%BD%95%E8%87%AA%E5%8A%A8%E6%9B%B4%E6%96%B0hosts%3F

**Comment by owenyaa** [comment]
@racaljk  你好，刚刚的程序一直报错，>>clear up!
>>开始配置hosts
>>从服务器获取hosts失败，请执行：
·打开网络连接
·检查hosts源是否存在
·更换hosts源
>>有任何疑问请访问https://github.com/racaljk/hosts/blob/master/README.md
大神能看一下吗？

**Comment by racaljk** [comment]
@owenya  估计是openssl问题。

看来是我太着急了，还没通过测试就发布。

**Comment by owenyaa** [comment]
@racaljk  大神，以后可否在源代码的下方附一个编译好的EXE文件的下载链接？  小白从头开始学找教程真的很头大。。。

**Comment by owenyaa** [comment]
@racaljk 另：我的邮箱845848181@qq.com，我可以每次当测试的志愿者啊，  你每次编译好了我可以帮你测试， 我的是教育网

**Comment by K-Guan** [comment]
@racaljk  我觉得owenyaa的建议还行，将编译好的程序的下载链接扔在README下面。

**Comment by owenyaa** [comment]
@racaljk @K-Guan 另外，hosts文件在ios设备上有办法实现吗？  不越狱的情况下

**Comment by racaljk** [comment]
@owenyaa  非常感谢，但是GUI测试得推迟到下周，希望能保持联系(ฅ>ω<*ฅ)

@K-Guan 我会考虑的

**Comment by racaljk** [comment]
@owenyaa 没用过ISO。但估计不可以，hosts权限还是很高的

**Comment by andytimes** [comment]
@owenyaa 假如你升级到最新系统IOS 9，越狱不了，你可以改路由器配置、、好像看到你说了一个“教育网”、、、这个还真的不知道怎么办

**Comment by owenyaa** [comment]
@racaljk 大神，有新版的编译好的EXE的文件么？

**Comment by racaljk** [comment]
@owenyaa 上周一直都在学校没回去  所以根本没时间碰电脑

**Comment by TeacherLiu** [comment]
您好，我想问一下，就是你这个hosts文件中的内容是如何生成的呢？是如何得到这些地址ip的？

**Comment by racaljk** [comment]
@TeacherLiu 可以参考#70点讨论

**Comment by TeacherLiu** [comment]
@racaljk ,难道是你们自己一点一点弄的？每弄专门的工具么？

**Comment by andytimes** [comment]
TeacherLiu <notifications@github.com>于2015-11-25 21:44 周三写道：

> @racaljk <https://github.com/racaljk> ,难道是你们自己一点一点弄的？每弄专门的工具么？
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/racaljk/hosts/issues/72#issuecomment-159611604>.
>
基本都是热心朋友一点点贡献起来的。

**Comment by ppoffice** [comment]
感谢卤煮的工作。另外提一个小建议，卤煮是否方便开启Webhook？这样的话可以方便监听hosts的更新，可以给程序添加自动更新的功能？

**Comment by ppoffice** [comment]
另外可否用CI测试IP是否有效？

**Comment by xubin990510** [comment]
上面的OpenWRT的不要忘了把电脑的DNS设成路由器的IP

**Comment by racaljk** [comment]
@ppoffice 持续集成和webhook还没试过呢，有时间也可以用用

**Comment by racaljk** [comment]
@andytimes
@K-Guan

ppoffice联系我并希望我们使用他的[hosts gui](https://github.com/ppoffice/Hozz)程序作为默认hosts图形界面管理器，我大略看了一下还不错(比起我那个hosts gui)，我也懒得解决之前的依赖问题，所以也考虑使用这个gui，你们看看如何？

**Comment by imcaffrey** [comment]
electron好评！

**Comment by andytimes** [comment]
@racaljk 我不太懂图形化的知识，所以你觉得好用就行。

ps: 看 README 里的截图，感觉挺不错的
https://camo.githubusercontent.com/c54e78bd83a8ab4d19c713ffc4a9991f27e2e136/68747470733a2f2f6f6f6f2e306f302e6f6f6f2f323031362f30312f30312f353638363836393162643237322e706e67

**Comment by K-Guan** [comment]
@racaljk 我表示无意见，同意@andytimes 的看法。

**Comment by K-Guan** [comment]
@racaljk @andytimes 

等等，我又改变主意了。~~为了让我 *看上去像个* 负责任的Collaborator~~ 因为我是一个负责任的Collaborator，我还是写了个很长，很长，很长……的评测：https://gist.github.com/K-Guan/baea864203036e226061

（Only read it when you so boring）
