### ISSUE TITLE
突然发现打不开Github...

### ISSUE THREAD

**Issue by imagainstzy** [racaljk/hosts#721]
&emsp;&emsp;今晚发现github打不开，可能是hosts里的地址**192.30.253.113**崩了，换了**192.30.253.112**就可以打开了，但还是很慢。 
 **新人首问，不懂规矩,有不合适的地方请包涵LOL**
<img src="https://raw.githubusercontent.com/imagainstzy/picturehub/master/%E6%B7%B1%E5%BA%A6%E6%88%AA%E5%9B%BE20161024223551.png"/>

**Comment by sqc1999** [comment]
我这里这个IP是可以ping通的，而且这个hosts文件里的那个IP只是给GitHub Gists用的，对GitHub的其他服务没有影响。

**Comment by imagainstzy** [comment]
@sqc1999 可能是地区问题吧，大陆用github的产品联网网速是硬伤啊_(:з」∠)_

**Comment by Too-Naive** [comment]
aws大陆无解吧

**Comment by imagainstzy** [comment]
何以解忧，唯有SS......

**Comment by sqc1999** [comment]
感觉最近几天github确实变慢了很多，不知道是不是我的错觉。。

**Comment by sqc1999** [comment]
我试了一下把github解析到112那个IP地址，似乎变快了很多

**Comment by Too-Naive** [comment]
→_→ 这个还是看具体问题具体分析吧 aws目前似乎没有办法解决XD
