### ISSUE TITLE
Add a host address

### ISSUE THREAD

**Issue by wongnet** [racaljk/hosts#723]
www.tumblr.com 66.6.33.193
某些地区可能存在IP封禁的情况，可以考虑添加此条host记录

**Comment by andytimes** [comment]
https://github.com/racaljk/hosts/blob/d22a72ab4840cdac9010f2fbd8323610f2e00429/hosts#L3146

hosts 中存在 www.tumblr.com 对应的记录，这条域名对应的 IP 基本被完全屏蔽了，
仅剩的几个 IP 也不稳定，不建议用 hosts 访问 Tumblr。
