### ISSUE TITLE
一键助手，工具分享

### ISSUE THREAD

**Issue by guoruibiao** [racaljk/hosts#727]
嗨，广大好友们。我做了一个实时更新hosts文件的小工具。想贡献出来。下载地址（    https://github.com/guoruibiao/crosswall     ） 喜欢的不妨给小弟star或者自己fork后更改哈，(*^__^*) 嘻嘻……

借助Python语言实现的打包好的exe文件，windows64位右键管理员权限运行即可。

原理就是爬取这个项目的最新的hosts文件，然后更新到您的电脑中，另外会提前做好备份，方便hosts的

重置。

请问，我要怎么才能把这个工具共享出去呢？
![image](https://cloud.githubusercontent.com/assets/12973402/19752471/3423bde0-9c30-11e6-9bbc-2443d9106cdb.png)

**Comment by Too-Naive** [comment]
→_→其实我们已经有了一个完整的[工具库](https://github.com/HostsTools)...

**Comment by guoruibiao** [comment]
额，好吧。刚看到， 不过多一个也无妨了      ~\(≧▽≦)/~啦啦啦

**Comment by Too-Naive** [comment]
那 我把你拉入成员中…然后您把工具源码push上来

**Comment by Too-Naive** [comment]
啊…我直接fork…然后邀请您做collaborator

**Comment by guoruibiao** [comment]
好的啊 太荣幸了(*^__^*) 嘻嘻……
