### ISSUE TITLE
移动版的维基百科不能用😂

### ISSUE THREAD

**Issue by zzseven** [racaljk/hosts#73]
要是移动版的维基百科也可以用那就太好了～

**Comment by andytimes** [comment]
请确认是https方式访问，https://en.m.wikipedia.org亲测有效。

2015-10-25 9:52 GMT+08:00 zzseven <notifications@github.com>:

**Comment by zzseven** [comment]
额，我说的是手机上的中文版页面～😂

**Comment by andytimes** [comment]
@zzseven 已更新

**Comment by zzseven** [comment]
谢谢～😄

**Comment by andytimes** [comment]
@zzseven 不客气。
