### ISSUE TITLE
facebook 異常

### ISSUE THREAD

**Issue by PW-Chen** [racaljk/hosts#731]
facebook 45.64.40.68 
國內外 都  ping 不通

**Comment by p0oo0q** [comment]
台湾人也用这Hosts?你这样不能加速，反而减速
况且此项目中Facebook对应的部分ip错误

**Comment by Too-Naive** [comment]
→_→ 要是人家在大陆呢

**Comment by andytimes** [comment]
45.64.40.1

**Comment by PW-Chen** [comment]
可以了 謝謝

**Comment by andytimes** [comment]
@PW-Chen 
可能是域名蒐集不完善，或是連接被干擾了。
要在大陸穩定使用 Facebook，最好還是代理訪問。
