### ISSUE TITLE
将来会考虑支持bind/dnsmasq吗

### ISSUE THREAD

**Issue by xiaofami** [racaljk/hosts#733]
昨天用群晖上的DNS服务器插件（其实就是bind）自建了一个DNS服务器，通过53端口转发到外网，在外面也能使用到无障碍的网络。bind支持泛域名，配置、维护、使用比hosts方便，不知道未来是否会支持。
![image](https://cloud.githubusercontent.com/assets/4654044/19794950/9c934c90-9d09-11e6-9a38-24a48a9a3280.png)
![image](https://cloud.githubusercontent.com/assets/4654044/19795026/4b395136-9d0a-11e6-8797-412ad50ed89d.png)

**Comment by sqc1999** [comment]
然而bind之类的东西的配置对于小白来说还是有难度的

**Comment by xiaofami** [comment]
群晖上配置还是很简单的，点两下就好了。配置导出来了，感兴趣可以测试。还算满意，一般的Google服务可用，`Youtube`视频能看，`amazon`云正常，`github`也没有大问题。不过`Play Store`下载应用会报403错误，`facebook`完全不能用…… 改天再看看能不能在自己的VPS上搭建SNI Proxy。

[zonefile (3).zip](https://github.com/racaljk/hosts/files/557786/zonefile.3.zip)

**Comment by Too-Naive** [comment]
#660 #394 #248 #135 #203 #446

**Comment by xiaofami** [comment]
配置中的`192.168.1.20`是群晖在我的局域网中的地址，要替换成自己的。另外解析中要开启转发，填两个常用的DNS地址就好。
