### ISSUE TITLE
Tapatalk貌似被封了,作者可以弄弄吗?

### ISSUE THREAD

**Issue by masktao** [racaljk/hosts#736]
前段时间还可以直连,现在只能挂vpn上了

**Comment by PW-Chen** [comment]
40.76.19.42 blog.tapatalk.com
50.17.254.140 siteowners.tapatalk.com
52.4.238.173 www.tapatalk.com

**Comment by masktao** [comment]
用了下2楼的地址,貌似没效果

**Comment by PW-Chen** [comment]
我是重新整理好幾次
都等好久  偶爾會load的下來

**Comment by Too-Naive** [comment]
![](https://cloud.githubusercontent.com/assets/16496671/19827302/bc9bb904-9dd7-11e6-8bd3-94b345512b1c.jpg)
@PW-Chen 有没有联系方式什么的 我可以直接提供免费ss

**Comment by PW-Chen** [comment]
@Too-Naive 我曾經寫信到你的信箱過  昨天下午三點左右

**Comment by xmdhs** [comment]
我也连不上
