### ISSUE TITLE
wp手机上flipboard网页能上，但是客户端显示没有网络

### ISSUE THREAD

**Issue by oilbottle** [racaljk/hosts#738]
只有用了VPN才能浏览。这是什么原因？hosts不全？？？

**Comment by Too-Naive** [comment]
问题已经重复 请不要重复开issue 谢谢。

**Comment by oilbottle** [comment]
额，我看见了也有人反映flipboard客户端的原因了，只是想知道为什么直接网页登陆可以客户端就不可以？

**Comment by Too-Naive** [comment]
应该是缺少条目 目前不太清楚= =不过你都看到有人反映了直接留言即可 **没有必要**再开新的issue了
