### ISSUE TITLE
Gmail无法删除邮件

### ISSUE THREAD

**Issue by poshit123** [racaljk/hosts#74]
删除邮件后过一段时间又会收到，要如何修复呢？

**Comment by andytimes** [comment]
可能是你的网络问题。没有其他人反映这种情况，推荐你使用inbox by gmail， https://inbox.google.com

在 15/10/26，poshit123<notifications@github.com> 写道：

**Comment by poshit123** [comment]
应该不是客户端的问题，完全不用hosts，用SS删除后就不会重新收到，而且用别的hosts也有这个问题，收邮件和发送邮件都没有问题，我猜想是某个域名导致此问题。如果你有思路可能是哪一个或者哪些，就好了，我可以试试。谢谢！

**Comment by whinamp** [comment]
@poshi123 从未遇到也未听说你提到的这个问题。

**Comment by andytimes** [comment]
这个我不清楚，有关Gmail邮件的收发，推荐去 https://support.google.com 查询相关问题。
我个人认为是网络运营商问题，可能一段时间问题会消失。

2015-10-26 16:55 GMT+08:00 whinamp <notifications@github.com>:
