### ISSUE TITLE
有mediafire的hosts吗？ 下载链接无法加载

### ISSUE THREAD

**Issue by LGCaerwyn** [racaljk/hosts#740]
国外的网盘， 可以添加mediafire的hosts吗？

**Comment by myguybetter** [comment]
`mediafire.com/download` had been on the Word Filter List of GFW and connection will be reset through http. Sadly, mediafire hasn't enabled https on its download page, so you can't prevent this by editing hosts. Proxy recommended.
Plus, mediafire's record isn't polluted.
