### ISSUE TITLE
mobile01app可能显示图片吗?

### ISSUE THREAD

**Issue by masktao** [racaljk/hosts#743]
mobile01是个论坛: mobile01.com 已经被封.但是却有一个中国镜像: http://www.5i01.cn这个地址可以看所有内容没有被封
但是mobile01app只能显示文字信息,所有的图片无法显示,手机版地址m.mobile01.com也同样被封
可以让mobile01的app正常打开图片吗?

**Comment by PW-Chen** [comment]
https://www.mobile01.com/
202.39.235.195 www.mobile01.com
hosts 里练加入这一条应该就行了
