### ISSUE TITLE
无法使用git clone

### ISSUE THREAD

**Issue by qshuangwen** [racaljk/hosts#744]
Hi~  非常感谢作者您的分享，我使用了您的hosts来替换我Mac上的hosts，我的电脑无法从github上clone仓库了。一直报错: Failed to connect to github.com port 443: Operation timed out。我使用Lantern来翻墙，git clone的时候，没有使用其他的proxy

**Comment by lautis0503** [comment]
本项目中没有github.com的hosts，请检查代理设置
可能是DNS解析出错

**Comment by andytimes** [comment]
如果蓝灯本地端口是 8787，在终端可以这样用：

```coffee
https_proxy=https://localhost:8787 git clone [repo]
```

**Comment by qshuangwen** [comment]
👍👍👍 多谢，我回去试试看

发自我的 iPhone
