### ISSUE TITLE
无法访问Google

### ISSUE THREAD

**Issue by glory1995** [racaljk/hosts#745]
连带Youtube页面也打开不了，会不会有管理GFW的人专门寻找新IP进行封锁？

**Comment by birdofprey** [comment]
天朝上国肾虚的很

**Comment by mraandtux** [comment]
不知是否和几个月前 #470 某帖所说，是电信的出口堵爆了？还是真·基挨服搭不溜升级？

**Comment by OumaSyuu** [comment]
现在google上不了比较伤

**Comment by nathanatgit** [comment]
貌似是这样的...只有谷歌不能用

**Comment by birdofprey** [comment]
邪恶的XXX

**Comment by Too-Naive** [comment]
难道就没有想过为什么要有墙吗？

**Comment by nathanatgit** [comment]
为了墙某些什么都信的智障😂

**Comment by birdofprey** [comment]
为了安全吧，免得一小撮境内外敌对势力颠覆政权

**Comment by zqWu** [comment]
昨天晚上不能连，然后更新了host 也不行

Connecting to www.google.com.hk (www.google.com.hk)|220.255.2.153|:443... 

一直连不上
GFW升级了？

**Comment by birdofprey** [comment]
谈论ZZ，然后GITHUB也会被墙啦，哈哈哈

**Comment by dogabner** [comment]
github又不是没有被墙过(-｡-;)

**Comment by birdofprey** [comment]
http://www.golang.org/也上不去了。墙外看看是不是美帝的网络因为总统选举导致网络遭受黑客攻击全面瘫痪了。:joy:

**Comment by nathanatgit** [comment]
年度大戏

**Comment by liguge** [comment]
我也遇到了同样的问题了~

**Comment by tsai1993** [comment]
google scholar 用不了了，影响我写论文……党国真是会拉仇恨！

**Comment by birdofprey** [comment]
突然想起了电影里的那句台词：“宁可错杀1000，也不能放过一个”

**Comment by yolenstark** [comment]
卧槽，吃个饭回来，不能用了……

**Comment by xuelianhan** [comment]
刚刚更新了hosts，google还是上不去，是不是被封锁了？

**Comment by Blank65ck** [comment]
我还真是开着vpn上github的orz....

**Comment by steambap** [comment]
求更新啊

**Comment by hurryzeng** [comment]
HOSTS是昨天的版本，居然也不行......

**Comment by sqc1999** [comment]
我不就一个上午没上网吗，怎么Google就不能用了
似乎能ping通，但是网页打不开，不知是封了80和443端口还是直接封了TCP协议
这种现象还是第一次见（也许是我孤陋寡闻）

**Comment by Too-Naive** [comment]
→_→ 昨天没有更新google有关的hosts

**Comment by sqc1999** [comment]
我试了一下`64.233.162.84`暂时可用，有急用的先用这个吧。。
等待更新中。。

**Comment by DaleAndriy** [comment]
我们上税，养了一群一天没事想办法封google的人。。。醉了，我就想问了，他们想招的时候用百度搜技术吗？

**Comment by laodcn** [comment]
我来修吧

**Comment by birdofprey** [comment]
221.183.21.198 223.119.30.130地址丢包非常严重。不知道是不是GFW网络黑洞导致的

**Comment by Too-Naive** [comment]
@DaleAndriy 人家用vpn啊(笑

**Comment by xfhy1822** [comment]
我还以为是我的电脑系统被动手脚篡改了什么文件呢，原来都上不去google了，妈的，这一天天的！！

**Comment by birdofprey** [comment]
更换文件后继续无法访问中。。。。

**Comment by sqc1999** [comment]
更新后的无法访问。。

**Comment by Too-Naive** [comment]
请指明ISP

**Comment by birdofprey** [comment]
CHINA MOUBIL

**Comment by Too-Naive** [comment]
mobile？

**Comment by birdofprey** [comment]
YES

**Comment by laodcn** [comment]
看来这个ip丢包严重啊，有时候快到感觉不到墙的存在，有时候100%的丢包率

要不换成以前那个64.233开头的..

**Comment by Zobeta** [comment]
中国联通，半小时前更新的hosts还是无法访问Google，216.58.221.56这个IP也ping不通

**Comment by Zhu-Zhi-Hao** [comment]
卧了个大槽，我还有一堆Error要调试解决啊，比较伤感....

**Comment by zhoujiealex** [comment]
更新了 还是登录不上去 郁闷

**Comment by birdofprey** [comment]
看来天朝并不愿意让大多数人有进步和判断力

**Comment by lleng** [comment]
早上还Google得好好的，中午回来就上不去了，更新了还是上不去……

**Comment by naodai** [comment]
216.58.199.4	www.google.com

可以试下这个ip.
我可以上,但也有人说不能上,要是能用话,就先用着吧
要是不能用,那就等等吧.

**Comment by birdofprey** [comment]
看来是美帝故意制造天朝和天朝子民的矛盾呀，不过想想也是，一个连民众都糊弄的政府从来都是内心胆寒嘛，所以它得老防着老百姓造反，大宋各位皇帝都这样

**Comment by lautis0503** [comment]
陕西联通
172.217.24.238 我这里现在ping值非常低
64.233.162.84 也能访问

**Comment by laodcn** [comment]
https://github.com/racaljk/hosts/pull/750
请测试这个，我这边多人测试已经可以使用

**Comment by KFAaron** [comment]
我用的3月30日修改的那个hosts的版本好像可以上，用今天新的以及上个版本的都上不了Google系列。

**Comment by KFAaron** [comment]
我也是改用64.233.162.84之后可以用了 @lautis0503

**Comment by birdofprey** [comment]
目前HOSTS已恢复正常使用。好神奇，到底是什么原因。我就在想，把互联网出口关完了。然后就像大明那个时候，到处都是特务机关。那这个世界真是疯狂了

**Comment by liuxiaodongdefault** [comment]
各位大兄弟更新完能用了么？有吊大的说一下。

**Comment by andylee1890** [comment]
靠mirror 应个急吧: http://dir.scmor.com/google/

**Comment by sqc1999** [comment]
@birdofprey 这里只是个维护hosts的地方，政治话题还是不要乱讲

**Comment by 67au** [comment]
广东移动还是上不了😂😂
ping timeout

**Comment by Makebignew** [comment]
@Too-Naive 不如用SNI替换64.233.162.81，比如
110.4.24.170 pccw

**Comment by birdofprey** [comment]
以后不说话

**Comment by birdofprey** [comment]
安心学习

**Comment by wj15github** [comment]
还是不能访问啊，伤心。。。

**Comment by liuxiaodongdefault** [comment]
https://github.com/liuxiaodongdefault/hosts-1
上不去的兄弟可以用下这个...

**Comment by Makebignew** [comment]
@aofall 你确认是ip故障？ipip.net测试国内ping全不通，国外都正常，明显是被block了

**Comment by Makebignew** [comment]
@67au @wj15github 在下次更换ip之前可以把Google ip 替换成110.4.24.170 应急

**Comment by sqc1999** [comment]
@Makebignew 我i这里可以ping通啊。。不知所错

**Comment by wyk-qyf** [comment]
your effort should be appreciate! thanks a lot!

**Comment by robinwar** [comment]
呃 最近一直挂代理 最新的hosts终于能用了 感谢作者

**Comment by wyk-qyf** [comment]
without google search and google scholar, i can't work ! so that's why i appreciate.

**Comment by aofall** [comment]
ping不代表一切
用路由追踪(TCP)来说话

**Comment by 67au** [comment]
@Makebignew 
香港csl的还好，可以做备用

**Comment by sqc1999** [comment]
@aofall 你说的极其有道理

**Comment by zeropy** [comment]
这几天都是连接超时

**Comment by 9527dong** [comment]
上海电信，更新后无法打开谷歌

**Comment by sqc1999** [comment]
我这里是电信连不上，移动可以。

**Comment by FrancisGee** [comment]
现在又连不上Google了，早上刚连过，现在断了

**Comment by sansna** [comment]
正在 Ping 64.233.162.84 具有 32 字节的数据:
请求超时。
请求超时。
请求超时。
请求超时。

64.233.162.84 的 Ping 统计信息:
    数据包: 已发送 = 4，已接收 = 0，丢失 = 4 (100% 丢失)，

**Comment by hytxk** [comment]
吉林联通移动全部上不了google，fb和tw倒正常

**Comment by steambap** [comment]
又上不去了

**Comment by xmdhs** [comment]
64.233.162.84 湖南电信 无法连接

**Comment by birdofprey** [comment]
不说话

**Comment by XADlwx** [comment]
今天又无法访问谷歌了

**Comment by liuxiaodongdefault** [comment]
GFW又更新了。。。不仅连这个，还有之前我发那个host也被封了，我怀疑是不是有GFW的人员打入了github。。。我们之中出了一个叛徒(→_→)

**Comment by idvr** [comment]
哪个死全家的骚逼贱货举报的啊。

**Comment by imknown** [comment]
死得真快.. 又挂掉了几个...

**Comment by EricInBj** [comment]
216.58.200.0 这一堆极好的 IP 地址，也挂了，从路由追踪结果看，是 Google 主动屏蔽。。。

**Comment by zeropy** [comment]
怎么看出来的？

**Comment by EricInBj** [comment]
最后一跳不可达，前几跳都是 Google 自己。
而且，原来216.58.200这些ip 是在香港的，现在看上去不是了。。

12. 202.97.61.34                           14.4%    91  147.5 147.4 143.1 169.0   3.6
13. 202.97.62.214                          13.2%    91  140.8 141.0 139.3 146.3   1.0
14. 108.170.241.70                          3.3%    91  163.0 144.2 140.5 240.1  11.5
15. 209.85.142.185                         11.1%    91  142.7 144.0 141.4 200.5   7.2
16. 216.239.41.207                         22.2%    91  155.4 158.1 152.6 199.0   9.1
17. 209.85.248.241                         21.1%    91  254.5 253.2 232.7 299.5  10.3
18. ???

**Comment by nathanatgit** [comment]
睡了一觉google又不不好使了，只好拔路由器直接走ipv6了😑

**Comment by Too-Naive** [comment]
@idvr 树大招风。

**Comment by gongxijun** [comment]
真是一个忧伤的故事～

**Comment by lautis0503** [comment]
IP挂了一大堆

**Comment by sunzhiguang** [comment]
国内哪些VPN好用一些，求推荐

**Comment by Too-Naive** [comment]
与本repo无关的问题 尽量不要讨论



On sunzhiguang <notifications@github.com>, Nov 7, 2016 4:38 PM wrote:

国内哪些VPN好用一些，求推荐

**Comment by OumaSyuu** [comment]
我们放弃治疗了吗

**Comment by andytimes** [comment]
119.9.76.67
香港 rackspace.com

不保证安全性，有连接重置现象，稳定使用Google请自备SS。

**Comment by SerCom-KC** [comment]
湖南电信表示前几天还行，就今天开始Google、Facebook、Twitter全萎了，看了一眼更新日期这是要弃坑的节奏？

**Comment by Psycho7** [comment]
所以现在如何解决？

**Comment by hurryzeng** [comment]
11-02的版本之前可以，现在又不行了....抓狂，GFW的公务员这么勤奋啊？

**Comment by laodcn** [comment]
表示测试了一天....有几个速度很快，然而我发给童鞋们测试又挂了，不稳定~~~

**Comment by Psycho7** [comment]
讲真 这就很尴尬了...难道我们中出了一个叛徒？

**Comment by testcaoy7** [comment]
110.4.24.170已挂

**Comment by LGCaerwyn** [comment]
11-03 昨天用着还ok， 今天就挂了。。。（厦门电信）

**Comment by testcaoy7** [comment]
之前用的SNI是中国移动的220.255.2.153，大半年没事，前几天挂了，现在PCCW的又挂了（延迟、速度超级好的），求其他SNI的地址

**Comment by jetbe** [comment]
全挂了，只能开VPN了。

有什么软件可以自动识别国内或者国外IP呢？

**Comment by Too-Naive** [comment]
@jetbe gfwlist

**Comment by tsai1993** [comment]
推荐 duckduckgo

**Comment by XADlwx** [comment]
谷歌不能用 一天了。

**Comment by 67au** [comment]
网络安全法在2017年6月1日发布 [doge]

**Comment by mewsf** [comment]
不建议用sni proxy，楼上那个挂了，看路由推测是因为流量过大导致黑洞路由，不过墙外是能正常访问

**Comment by leoxxx** [comment]
问一下这里有没有联通的用户？我用过电信线路有问题，但用的其它的ISP能上，但不稳定。不知道有没有联通的用户。

**Comment by Too-Naive** [comment]
@Psycho7 "中出"

**Comment by Too-Naive** [comment]
@freezer-glp #773 #771

**Comment by sqc1999** [comment]
要不要这么污。。

**Comment by Too-Naive** [comment]
一言不合就污了

**Comment by laodcn** [comment]
https://github.com/racaljk/hosts/pull/771

**Comment by 0915240** [comment]
什么鬼 怎么都变成巫妖王了 求修复

**Comment by mewsf** [comment]
感觉sni proxy都不耐艹啊

**Comment by robinwar** [comment]
更新完好了半个小时就又挂了...挂代理都很慢真是无语

**Comment by Makebignew** [comment]
@laodcn @Too-Naive 看起来gfw采用了证书嗅探的方式自动阻断Google ip，比如我最近扫出来的几十组ggc很快（2分钟）就被黑洞
见：https://gist.github.com/clowwindy/5947691
http://ju.outofmemory.cn/entry/190047
现在嗅探范围估计是扩大到所有ip了，扫出来IP只能是很快黑洞，大概只能用sni

**Comment by Insua** [comment]
202.171.253.111 ping time只有几十毫秒,但是经常打不开,或者几分钟后才刷出来

**Comment by Andero** [comment]
上午还能用现在已经用不了了，PS：请科学上网的童鞋们删掉国产的卫士、助手、管家啥的，明明是间谍软件，偷偷上传VPN

**Comment by birdofprey** [comment]
所以我觉得Gnu创立者是对的，关键是这也太流氓软件了。NSA也没有明目张胆到这个程度。

**Comment by XADlwx** [comment]
昨天晚上刚上去，今天又不行了。

**Comment by leoshh** [comment]
修改了host反而上不了谷歌，唉

**Comment by PW-Chen** [comment]
@leoshh 感觉要找一个 全部的isp都可以用的ip 真有点难度 毕竟 不知道每个地方的 blocked状态
江浙電信是能用的

**Comment by leoshh** [comment]
@PW-Chen 恩，我这边是上海电信

**Comment by Too-Naive** [comment]
@leoshh 如果上一个版本可用 就回退

**Comment by Too-Naive** [comment]
如果目前google可用的话 就不要修改新的hosts了 有可能新的不可用

**Comment by birdofprey** [comment]
国际歌真是种讽刺

**Comment by Zobeta** [comment]
辽宁联通，最新的253.111这个ip勉强可用，ping很低但是实际访问速度实在太差，图片经常加载出不来之类的

**Comment by x2yline** [comment]
唉，由不能用了，失效也太快了吧，最近是不是网络管的得很紧呀

**Comment by leoshh** [comment]
@Too_Navie 好吧，只是我没备份的习惯，只能等更新了

**Comment by sqc1999** [comment]
@leoshh git是版本管理系统，所以你可以再GitHub上找到所有历史版本
https://github.com/racaljk/hosts/commits/master

**Comment by yech1990** [comment]
202.171.253.111  不是google的地址吧？ 感觉是个代理

**Comment by leoshh** [comment]
@Zobeta 见笑，我不太会用。另外， @Too-Naive 我这现在host又能用了。我系统原来的host文件没备份，用工具恢复回去很多正常能上的也上不了了，而且开vpn微软什么的网站还是上不去，逼得我又试了下

**Comment by JohannWong** [comment]
某博客的某人居然发在百毒盘上
然后对比一下，这边应该是源头吧

**Comment by 67au** [comment]
你口中的某人也是该hosts的热心贡献者，详看另一分支→_→ @JohannWong

**Comment by liuxiaodongdefault** [comment]
原来以为是GFW人员打入内部，原来是有的人为了赚一点博客人气把造福大家的hosts文件上传到网盘里了，实在可恶。

**Comment by FrancisGee** [comment]
哪个hosts能用啊？？最新的用不了

**Comment by sqc1999** [comment]
@liuxiaodongdefault 不要搞事情啊。。
你说得好像GFW的人上不了GitHub，只会去查网盘一样的。。人家没那么傻
GitHub上的项目本来就是完全公开的，不是谁家的后花园，无论什么人（包括GFW相关人员）都可以访问，所以不管传到哪里都没什么区别。

**Comment by Too-Naive** [comment]
有什么阴谋论可言呢...本身github就是重点关照对象吧

**Comment by Too-Naive** [comment]
@leoshh 
1. ![](https://cloud.githubusercontent.com/assets/16496671/20161060/f8f142e0-a726-11e6-8f76-bef68f304604.png) 
2. ![](https://cloud.githubusercontent.com/assets/16496671/20161127/4d7126e6-a727-11e6-82f5-10ed20b541df.png)
3. ![](https://cloud.githubusercontent.com/assets/16496671/20161161/722506b0-a727-11e6-8746-e10c4deef1f9.png)
4. ![](https://cloud.githubusercontent.com/assets/16496671/20161176/8df9378a-a727-11e6-8c01-d288564a5ebc.png)
5. ![](https://cloud.githubusercontent.com/assets/16496671/20161205/ca993e4c-a727-11e6-8ec3-d7abc20367a3.png)
然后你就看到你想要的文件了 依此类推

**Comment by FrancisGee** [comment]
访问Google时断时续.....

**Comment by Zhu-Zhi-Hao** [comment]
我也是，时段时续，这几天好受影响....

**Comment by sansna** [comment]
有一种可能，google的ip是代理。不知道有没有人跟我想法一样。

**Comment by leoshh** [comment]
@Too-Naive 麻烦您截了这么多图了

**Comment by XADlwx** [comment]
昨天晚上刚上去，今天又不行了。

**Comment by laodcn** [comment]
@JohannWong 你是在说我么？

**Comment by Makebignew** [comment]
@sansna 应该说是cdn比较合适，是Google和运营商合作建立机房，用来加速访问

**Comment by mobyzhang** [comment]
又又又又又不行了哎

**Comment by githubuser00010** [comment]
本楼上面不是有个兄弟说了吗，１１０．４．２４．１７８。这个可以用，改成这个就行了。麻烦都低调点。。

**Comment by sqc1999** [comment]
目前仓库中最新的hosts似乎是被封端口了，能ping通，tcping 80端口通，443端口不通
这里绍兴电信

**Comment by 67au** [comment]
hosts不行的直接报地区和hosts无效的IP
而且听楼上的，低调暂用😂😂

**Comment by birdofprey** [comment]
最新hosts，陕西电信，联通不能

**Comment by guoyf** [comment]
北京联通求可用的IP。谢谢。

**Comment by guoyf** [comment]
可以了。用楼上的。

**Comment by Zobeta** [comment]
@githubuser00010 这个PC可用，手机不行，好奇怪啊

**Comment by mobyzhang** [comment]
确实应该低调哎 ，懂得人就该默默支持嘛，何必引来敌对势力。。。。。

**Comment by mobyzhang** [comment]
谷歌学术挂了？论文狗伤不起。。。

**Comment by birdofprey** [comment]
墙技术好

**Comment by Too-Naive** [comment]
@mobyzhang 前排卖ss

**Comment by xfhy1822** [comment]
我大天朝有2座世界最牛的墙，一座名为万里长城，一座名为GFW，哇哈哈。。

**Comment by birdofprey** [comment]
上帝使其崩溃必先使其疯狂

**Comment by Too-Naive** [comment]
#792

**Comment by mengyaoss77** [comment]
用SS好麻烦啊。。

**Comment by sqc1999** [comment]
听说ss很麻烦？用obfs4+ptproxy的我不说话。。

**Comment by Too-Naive** [comment]
又不是不能一键= =

**Comment by mengyaoss77** [comment]
主要是用惯了hosts 就懒得开机多点一下鼠标了=。=

**Comment by XADlwx** [comment]
今天又不能访问Google了

**Comment by imknown** [comment]
突然可以访问了, ~~难不成是解封了~~

**Comment by birdofprey** [comment]
其实我就对技术感兴趣。不能总把头埋在沙子里说老子天下第一吧。

**Comment by sqc1999** [comment]
@birdofprey 也不是你说的没有道理，只是这里不适合讨论这个内容。。

**Comment by YouthJie** [comment]
已经可以访问了

**Comment by Too-Naive** [comment]
@birdofprey  #776

**Comment by FrancisGee** [comment]
北京这边访问不了谷歌

**Comment by HaloWang** [comment]
可以用了，感谢！

**Comment by WeihuaGu** [comment]
我能说下twitter吗？（这是谷歌挂了的issues.）
用twitter,最近是二三十分钟刷不出来，然后某一个时刻会唰的一下在刷出来。

**Comment by heham** [comment]
Google商店app打不开，网页可以，好像前一版是可以的

**Comment by heham** [comment]
接楼上，用ss先进去一次就又可以了，可能还是别的什么问题

**Comment by birdofprey** [comment]
twitter无法用

**Comment by neverlous** [comment]
目前可以访问，略慢。各位稍安勿躁，等待更新吧。

**Comment by heham** [comment]
Google商店还是不行

**Comment by mengyaoss77** [comment]
啊 又挂了？

**Comment by xmdhs** [comment]
各位圣诞快乐

**Comment by zhaoxud** [comment]
是不是又挂了？

**Comment by neverlous** [comment]
时好时坏啊

**Comment by mraandtux** [comment]
中移动用户表示：用了泰h05t5，Google时不时会要求输入验证码

**Comment by OumaSyuu** [comment]
一时手贱把Android Studio的缓存清理了，现在google上不了，re-download又报error（requires network），真是想说一句你妈嗨啊！

**Comment by imknown** [comment]
@OumaSyuu 我昨天刚把 `Android Studio 2.2.3` 的 `Cache` 删了... 我是直连 `dl.google.com` 的

**Comment by OumaSyuu** [comment]
谢谢！ @imknown 已经搞定了。

**Comment by andygebb** [comment]
现在更新后访问Google没问题！非常好！

**Comment by zhaosoap** [comment]
上海这边google 已挂。不只是延迟而已啦。

**Comment by ShuYe-CN** [comment]
@zhaosoap 上海移动，没有问题啊orz

**Comment by lrinQVQ** [comment]
移动一切OK电信联通炸了
