### ISSUE TITLE
‘lhosts’ 脚本有问题

### ISSUE THREAD

**Issue by tigerZhang86** [racaljk/hosts#753]
`lhosts` 脚本有问题，mac下执行完毕后，`/etc/hosts` 的文件内容变为空了。

**Comment by Too-Naive** [comment]
→_→或许您可以使用mac对应的工具

**Comment by andytimes** [comment]
我写脚本时没有用 GNU 扩展，理论上是通用的，如果你需要更新时保留本地 hosts 的某些内容，
也许要配合 -r 模式使用（请阅读帮助信息），或者使用目前的脚本，已有人修复这一问题。

Mac 好像有人做过工具，你可以去找找。

如果是其他问题，建议在 lhosts 脚本的开头处加上 set -xv
```bash
#!/bin/bash
set -xv
...
```
执行
```bash
tools/lhosts -m > lhosts_out.txt
```

然后把 lhosts_out.txt 内容粘贴到这里来。

**Comment by tigerZhang86** [comment]
@Too-Naive  一直用 lhosts 工具更新 Mac 下的 hosts，没注意到还有 Mac 专用的，这就去试试。

**Comment by tigerZhang86** [comment]
@andytimes 使用最新的 lhosts 已经没有问题了，感谢你的答复。
