### ISSUE TITLE
twitter, facebook上不去了

### ISSUE THREAD

**Issue by leoshh** [racaljk/hosts#755]
如题，谷歌的是正常的

**Comment by Makebignew** [comment]
ip被封锁了
在找到新ip之前只能用sni了
110.4.24.170替换原来ip

**Comment by leoshh** [comment]
@Makebignew 我是不太懂，还好有个VPN还没到期，谢谢解答

**Comment by laodcn** [comment]
Facebook的有很多，Twitter的找了好久...没找到可用的，估计要先用SNI来应急了

**Comment by andytimes** [comment]
@laodcn twitter.com 已全挂，不用再找了、、、

**Comment by testcaoy7** [comment]
110.4.24.170是谁家的SNI？

**Comment by Makebignew** [comment]
@testcaoy7 香港PCCW
ipip.net 的IP库查询结果https://freeapi.ipip.net/110.4.24.170

**Comment by testcaoy7** [comment]
@Makebignew 谢谢，中国电信延迟很好，但是担心会被封

**Comment by lautis0503** [comment]
陕西联通
110.4.24.170用不了，工具检测结果全国ping均超时

**Comment by heham** [comment]
期待更新

**Comment by PW-Chen** [comment]
@Too-Native 應該是修好了  可以close(>_>)

**Comment by Too-Naive** [comment]
@PW-Chen 您tag错人了
