### ISSUE TITLE
科学Hosts.apk更新不正常

### ISSUE THREAD

**Issue by ChineseTaipei** [racaljk/hosts#764]
手机已通过SuperSU获取root权限并已授权科学hosts.apk。在Lantern软件全局代理情况下，软件更新时出现了网络错误。寻求解决方案。

**Comment by chuanzhongliu** [comment]
Me too

**Comment by chuanzhongliu** [comment]
我的hosts也不能更新

**Comment by CHN008** [comment]
我刚用另一个没有安装过这软件的手机测试了一下,没问题.

![screenshot_2016-11-05-12-33-36](https://cloud.githubusercontent.com/assets/16646697/20027724/a92119da-a356-11e6-831c-204acc0759c4.png)

![screenshot_2016-11-05-12-47-59](https://cloud.githubusercontent.com/assets/16646697/20027727/b5dd738a-a356-11e6-8e71-826e1f649dca.png)

**Comment by ChineseTaipei** [comment]
好，我去试一试。请问hosts最近更新到11月2号的吗？

2016年11月5日 下午12:53，"CHN008" <notifications@github.com>写道：

**Comment by ChineseTaipei** [comment]
已经更新到11月3号 估计是作者还没来得及更新apk里的hosts文件

2016年11月5日 下午12:56，"Paul Ho Au" <au13823007897@gmail.com>写道：

**Comment by Too-Naive** [comment]
= =您可以到相应的Repo下面讨论

**Comment by ChineseTaipei** [comment]
能给出repo的网络地址吗？

2016年11月5日 下午5:22，"Unostvisal" <notifications@github.com>写道：

**Comment by Too-Naive** [comment]
http://github.com/HostsTools/Android

**Comment by chuanzhongliu** [comment]
安卓7.1下不可用

Cthulhu <notifications@github.com>于2016年11月9日周三 20:17写道：
