### ISSUE TITLE
呵呵呵，这里也开启进瓶模式？

### ISSUE THREAD

**Issue by Runcy** [racaljk/hosts#779]
您好，感谢您开 Issue 来反馈信息，在提交前，请确保您已经检查了以下内容!
- 如有关" Google 无法连接" / " YouTube 视频无法播放"等问题 请参阅[常见问题解答](https://github.com/racaljk/hosts/wiki/The-hosts-FAQ)
- 已经阅读了 [Wiki 页面](https://github.com/racaljk/hosts/wiki)
- 已经搜索过之前的相关 [Issues](https://github.com/racaljk/hosts/search?type=Issues)
- 如果是报告问题，请确认问题可以复现并且没有重复报告同一个问题；如果是向 hosts 提供新的信息，请确认所提供信息的来源以及相关许可协议；欢迎使用 Pull Requests 功能（可以通过[直接编辑文件](https://github.com/racaljk/hosts/edit/master/hosts)的方式来提交）

如果您有其他附言，例如问题只在某个页面发生，或者是一般性讨论、提出新功能，请一定注明

或者您也可以卖个萌

我们同时有一个 [Gitter Room](https://gitter.im/racaljk/hosts)，以及一个[在 Coding 上的镜像](https://coding.net/u/scaffrey/p/hosts)

**Comment by Too-Naive** [comment]
@racaljk 请限制issue提出者的权限 可以视情况列blacklist

**Comment by imknown** [comment]
楼主慢走不送

**Comment by racaljk** [comment]
毕竟少数无视之

**Comment by racaljk** [comment]
毕竟少数无视之

**Comment by Too-Naive** [comment]
其实我就很奇怪了 好像是无论什么地方都要搞得和国内的论坛一样 说句实在的 在一个repo下发言就要遵守repo的规矩 不是协助repo的collaborator们的工作而是专门在挑这些眼 有啥用？ 似乎嘴炮赢了之后墙就会自然倒一样。
这里不是*易 也不是*博 你在别的地方骂谁我都不会限制你 但在这里 我作为collaborator 我看不下去

**Comment by racaljk** [comment]
最近忙着造mplc库没什么时间管hosts, issue creator别搞事情好吗
