### ISSUE TITLE
google 已经两天无法访问了

### ISSUE THREAD

**Issue by zuo-tech** [racaljk/hosts#782]

**Comment by LostSmoch** [comment]
我已经好几天了

**Comment by c02y** [comment]
好几天了+1

**Comment by beikehanbao23** [comment]
黄花菜凉了

**Comment by freezer-glp** [comment]
请大家不要在issue区发水comment。欢迎讨论有用的方法

**Comment by sqc1999** [comment]
@freezer-glp
关于Google不能访问的问题已经有一个open issue在讨论了（#745），这种情况下再开新issue不是很好吧。
另外**个人认为**`+1`一类的comment应该不能算水吧，这样有利于maintainers了解此问题的影响大小，此类comment在其他的英文project中也很常见。

**Comment by Too-Naive** [comment]
see also #745 
@freezer-glp 的说法是对的

**Comment by Too-Naive** [comment]
@sqc1999 
对于你的看法 我更希望是在hosts更改的commit下面提出无法连接+1的字样
而且 +1不说出自己的ISP什么的 我认为这样的+1是没有意义的
除了这点以外 我赞同其他的观点
