### ISSUE TITLE
怎样找到自己需要的ip地址呢？

### ISSUE THREAD

**Issue by oilbottle** [racaljk/hosts#783]
这样自己动手自给自足。

一般的方法是什么呢？

**Comment by imknown** [comment]
#685

**Comment by oilbottle** [comment]
不是伸手党，问之前谷歌都查过，没有找到满意的答案。#685 #116 #251 #258 #265 #528 也都查看了，虽然都是求找ip方法的，但没有几个正儿八经答的。只有@imknown 提到的方法具有可行性，但也不是所有人都有VPN的，另外也有提到用gogotester，但貌似只能查谷歌？不具有一般性

比如说，我要查beacon.flipboard.com可用的ip，利用https://asm.ca.com/en/ping.php 丢包率都是100%，那怎么才能找到合适的ip呢

**Comment by imknown** [comment]
@oilbottle 请重新修改标题
