### ISSUE TITLE
go get -x -v golang.org/x/crypto failed

### ISSUE THREAD

**Issue by douglarek** [racaljk/hosts#786]
ping works:

```
$ ping golang.org

PING golang.org (202.171.253.111): 56 data bytes
64 bytes from 202.171.253.111: icmp_seq=0 ttl=48 time=47.760 ms
64 bytes from 202.171.253.111: icmp_seq=1 ttl=48 time=46.002 ms
64 bytes from 202.171.253.111: icmp_seq=2 ttl=48 time=46.670 ms
```

`go get` failed:

```
$ go get -x -v golang.org/x/crypto

Fetching https://golang.org/x/crypto?go-get=1
https fetch failed: Get https://golang.org/x/crypto?go-get=1: dial tcp 202.171.253.111:443: i/o timeout
package golang.org/x/crypto: unrecognized import path "golang.org/x/crypto" (https fetch: Get https://golang.org/x/crypto?go-get=1: dial tcp 202.171.253.111:443: i/o timeout)
```

**Comment by Too-Naive** [comment]
tcping

Sent from my iPhone

On Nov 11, 2016, at 12:11, Lingchao Xin <notifications@github.com<mailto:notifications@github.com>> wrote:


$ ping golang.org<http://golang.org>

PING golang.org<http://golang.org> (202.171.253.111): 56 data bytes
64 bytes from 202.171.253.111: icmp_seq=0 ttl=48 time=47.760 ms
64 bytes from 202.171.253.111: icmp_seq=1 ttl=48 time=46.002 ms
64 bytes from 202.171.253.111: icmp_seq=2 ttl=48 time=46.670 ms


$ go get -x -v golang.org/x/crypto<http://golang.org/x/crypto>

Fetching https://golang.org/x/crypto?go-get=1
https fetch failed: Get https://golang.org/x/crypto?go-get=1: dial tcp 202.171.253.111:443: i/o timeout
package golang.org/x/crypto:<http://golang.org/x/crypto:> unrecognized import path "golang.org/x/crypto<http://golang.org/x/crypto>" (https fetch: Get https://golang.org/x/crypto?go-get=1: dial tcp 202.171.253.111:443: i/o timeout)


-

**Comment by douglarek** [comment]
```
$ tcping golang.org 443

golang.org port 443 open.
```

**Comment by douglarek** [comment]
Latest host 3b5454c resolved this.
