### ISSUE TITLE
console.developers.google.com

### ISSUE THREAD

**Issue by jy02534655** [racaljk/hosts#79]
64.233.160.90   console.developers.google.com
改成下面这个才能用
64.233.162.83   console.developers.google.com

**Comment by andytimes** [comment]
可能是地区问题，我这边测试过可以正常访问，https连接。

[image: 内嵌图片 1]

2015-10-31 15:16 GMT+08:00 jy02534655 <notifications@github.com>:

**Comment by jy02534655** [comment]
有可能，不知道啥时候才能很方便的访问这些不存在的网站哦

**Comment by CCTV-1** [comment]
当你成功肉翻的时候。。。

**Comment by andytimes** [comment]
国内的话，可能会等很长一段时间，毕竟社义国家。
如果你去国外发展，倒是很方便了。
@jy02534655

**Comment by jy02534655** [comment]
可惜没那个资本去国外，英语都不会
@andytimes

**Comment by andytimes** [comment]
@jy02534655 不是这么说的哦，好好学习的话，真的有很多机会，去国外不是你想的那么难。不过，确实需要一定的资本。当然加油的话，会有奖学金之类的，生活是不成问题的。关键是 机遇 + 努力 了。

**Comment by jy02534655** [comment]
@andytimes 已经过了上学的年龄了，哈哈

**Comment by andytimes** [comment]
@jy02534655 那就好好学习|工作呗，其实国内也不差的，认真对待每一件事情，总是会有回报的，机会也总是有的，关键是想不想得到啦。

**Comment by jy02534655** [comment]
@andytimes 这个确实
