### ISSUE TITLE
麻烦修复Chrome书签不能同步的问题~多谢！

### ISSUE THREAD

**Issue by Geek2Sages** [racaljk/hosts#792]
目前Chrome书签不能同步，重新登陆也没用，更何况现在登陆也很困难……屡次重新登陆不成功，连登陆页面都打不开。

**Comment by Too-Naive** [comment]
这个是...google hosts的问题吧

**Comment by Too-Naive** [comment]
#745

**Comment by 67au** [comment]
同理 详见 [#745](https://github.com/racaljk/hosts/issues/745)
请自行关闭issue
