### ISSUE TITLE
为什么要把google的地址指向一个广东的ip

### ISSUE THREAD

**Issue by redapple0204** [racaljk/hosts#795]
我查看hosts文件，发现指向的ip是一个广州的教育ip
而且google还无法打开。
那么问题就来了，请问干啥要把ip指向广州的教育ip？
![2016-11-13 10-13-49](https://cloud.githubusercontent.com/assets/16254644/20243223/e7c33d4c-a989-11e6-9864-5e495c1da127.png)
![2016-11-13 10-14-34](https://cloud.githubusercontent.com/assets/16254644/20243227/fd77b29e-a989-11e6-8d3c-d338c20f9563.png)

**Comment by ZexinHu** [comment]
代理？还是只是简单的路由

**Comment by redapple0204** [comment]
@ZexinHu 如果代理挂到教育网上也太.....

**Comment by xinyue** [comment]
我刚刚也在思考这个问题，不会是在教育网下的 IPV6 代理吧?

**Comment by qiangdezhen** [comment]
安全的吧

**Comment by mengyaoss77** [comment]
我也感觉应该是一个代理 做转发吧 但是从11月开始更新的hosts全部用不成。。。

**Comment by Too-Naive** [comment]
https://github.com/racaljk/hosts/commit/3b5454c36b4978b189e67f2fdfe42e8a1f24140b
