### ISSUE TITLE
有安全隐患吗？

### ISSUE THREAD

**Issue by yxsongbo** [racaljk/hosts#797]
我一下载这个文件，Chrome就提示“这是恶意文件，chrome已将其拦截。”，换个浏览器下载，windows defender也提示有病毒，不给下载，请用过的朋友给点经验。

**Comment by Ir1d** [comment]
我敢打赌你下载的不是这个文件 https://github.com/racaljk/hosts/archive/master.zip
也不是这个 https://github.com/racaljk/hosts/raw/master/hosts

**Comment by spyhole** [comment]
@lr1d 你搞的有毒

**Comment by PW-Chen** [comment]
@Ir1d  我猜他在說 https://github.com/HostsTools/Windows

**Comment by Too-Naive** [comment]
应该是windows.zip吧

**Comment by yxsongbo** [comment]
我下载的是https://github.com/racaljk/hosts.git

**Comment by yxsongbo** [comment]
另外，我还担心hosts文件提供的ip会不会是假的，比如，我访问gmail，输入了我的密码，会不会把我的密码泄露了

**Comment by sqc1999** [comment]
@yxsongbo 从理论上讲只要是HTTPS访问、域名正确且服务器/浏览器的实现没有漏洞就绝对不可能泄密。
可见我的另一个[comment](https://github.com/racaljk/hosts/issues/674#issuecomment-253414455)。

**Comment by sqc1999** [comment]
@yxsongbo 还有一个前提是Google服务器的私钥不能泄露。。

**Comment by Too-Naive** [comment]
#674 
您还需要知道什么

**Comment by Ir1d** [comment]
@yxsongbo 请问您是通过什么方式下载的？请详细说明！谢谢！

**Comment by paperbag** [comment]
@sqc1999 @yxsongbo
我查过这里 host 的 Google IP 的 Whois 信息不是 Google 的，但服务器提供的证书似乎是没问题的。证书没问题应该就没问题了吧。

证书指纹：60 91 94 fa 82 dd 81 4f bf 60 f7 a0 bb 1f e9 56 15 2b 0b d1
https://crt.sh/?q=60+91+94+fa+82+dd+81+4f+bf+60+f7+a0+bb+1f+e9+56+15+2b+0b+d1

**Comment by yjfvictor** [comment]
@Ir1d 
用Chrome下载 https://github.com/racaljk/hosts/raw/master/hosts 是可以的，但是这个确实会报毒https://github.com/racaljk/hosts/archive/master.zip 。我知道这是误报，但是想不通Chrome为什么这么报，难道是检测到压缩包中有hosts文件一律报毒？

@yxsongbo 
浏览器本身的安全机制会负责检测SSL证书，所以不用担心。如果是假的IP，访问网站的时候直接SSL证书校验不通过，出现那个“您的连接不是私密连接”的提示。所以既然没有这个提示，那么自然就是安全的。

**Comment by Ir1d** [comment]
@yjfvictor 不是很清楚QAQ

**Comment by paperbag** [comment]
我在挂代理的时候下载 Chrome 确实会有下面提示，不挂代理不会。我猜是和 [Safe Browsing](https://www.google.com/transparencyreport/safebrowsing/) 功能有关。
![bug](https://cloud.githubusercontent.com/assets/19257585/20460865/998ee8bc-af2c-11e6-81a7-e94ac8a4a489.PNG)

**Comment by paperbag** [comment]
Firefox 用的也是谷歌的 Safe Browsing，一样的状况。
![bug](https://cloud.githubusercontent.com/assets/19257585/20460970/484a71ae-af2e-11e6-8a37-06501a6eca96.PNG)

**Comment by imknown** [comment]
改系统的东西, 对一般用户来说肯定是危险的.

**Comment by Too-Naive** [comment]
hosts一般是劫持的入口

**Comment by Too-Naive** [comment]
很显然啊 如果你相信这个windows.zip 就用 不相信就别用 详情搜索hosts劫持
对于外国人来说 就算源代码摆在这里 但是bin文件他们也不会相信的嘛 毕竟编译出来的文件不可信
嗯 我还是那句话 相信就用 不相信就不要用 只是更方便而已  ~~没有求你用~~

**Comment by yehon** [comment]
@yxsongbo 
我用 chrome 下载这两个文件，没有任何提示。

chrome  版本：58.0.3004.3 dev (64-bit)

**Comment by Too-Naive** [comment]
![](https://cloud.githubusercontent.com/assets/16496671/20557321/f47b3c50-b1a5-11e6-8810-8edc50a65778.png)我也沒有任何提示

**Comment by paperbag** [comment]
谷歌的这个 `61.91.161.217` IP地址，不会是 SNI proxies 吧。这样就可以解释通，为何 IP Whois 不属于谷歌。查了有关资料，SNI proxies 貌似是在应用层的，所以不是中间人攻击。😊
```
WHOIS Results for：61.91.161.217
% [whois.apnic.net]
% Whois data copyright terms http://www.apnic.net/db/dbcopyright.html

% Information related to \'61.91.160.0 - 61.91.167.255\'

inetnum: 61.91.160.0 - 61.91.167.255
netname: TRUE-Corporate
descr: Fix ip for coporate customer
country: TH
admin-c: TIA6-AP
tech-c: TIA6-AP
status: ASSIGNED NON-PORTABLE
changed: ipadmin@trueinternet.co.th 20070320
mnt-by: MAINT-AP-TRUEINTERNET
mnt-irt: IRT-TRUEINTERNET-TH
source: APNIC

irt: IRT-TRUEINTERNET-TH
address: 14th,27 th, floor ,Fortune Town
address: 1 Ratchadaphisek Road, Din Daeng
address: Bangkok 10400
e-mail: abuse@trueinternet.co.th
abuse-mailbox: abuse@trueinternet.co.th
admin-c: TIA6-AP
tech-c: TIA6-AP
auth: # Filtered
mnt-by: MAINT-AP-TRUEINTERNET
changed: abuse@trueinternet.co.th 20101108
source: APNIC

role: TRUE IP ADMINISTRATION
address: 1 Fortune Town, 14th, 27th Floor,
address: Ratchadapisek Road, Din Daeng
address: Din Daeng, Bangkok 10400.
country: TH
phone: +662 6200400
fax-no: +662 6421557
e-mail: ipadmin@trueinternet.co.th
remarks: abuse@trueinternet.co.th
admin-c: AC1013-AP
admin-c: WP1-AP
tech-c: PY184-AP
tech-c: RT271-AP
nic-hdl: TIA6-AP
notify: ipadmin@trueinternet.co.th
changed: ipadmin@trueinternet.co.th 20081105
mnt-by: MAINT-AP-TRUEINTERNET
source: APNIC
changed: hm-changed@apnic.net 20111114

% This query was served by the APNIC Whois Service version 1.69.1-APNICv1r7-SNAPSHOT (WHOIS4)
```

**Comment by Ir1d** [comment]
@paperbag 查询 blame发现https://github.com/racaljk/hosts/commit/3b5454c36b4978b189e67f2fdfe42e8a1f24140b
当时认为是Thailand GGC

以及如果继续讨论请新开issue，与本issue内容无关 谢谢
