### ISSUE TITLE
维基百科崩了

### ISSUE THREAD

**Issue by cjkzwe** [racaljk/hosts#799]
维基百科坏了

**Comment by sqc1999** [comment]
<del>你仿佛在逗我</del>
绍兴移动正常访问。

**Comment by Ir1d** [comment]
中文维基？

**Comment by PW-Chen** [comment]
虽然ping 不能代表什么 还是show 一下
![2016-11-15 4 10 57](https://cloud.githubusercontent.com/assets/22865986/20297963/4e999cb2-ab4e-11e6-9212-414d22883a12.png)

**Comment by YouthJie** [comment]
湖北，可以访问额

**Comment by CHN008** [comment]
广东,正常 :100:
