### ISSUE TITLE
Gmail 客户端问题

### ISSUE THREAD

**Issue by fun5rt** [racaljk/hosts#80]
使用host之后网页打开gmail没问题了，可是客户端使用gmail还是有问题。

我用Airmail，直接使用gmail方式可以认证，是跳转网页的那种，不过就是不下载邮件内容。

使用imap.gmail.com smtp.gmail.com就显示认证失败，说无法建立安全的连接。

使用hosts里面的ip地址填入也是失败，同样提升无法建立连接。

只有网上找一些特殊ip地址才可以。

是不是host里面的gmail IP只支持网页，不支持客户端？

**Comment by waylau** [comment]
我装了 foxmail 客户端，貌似没有啥问题哦~

**Comment by fun5rt** [comment]
你的gmail是怎么设置的呢？imap、smtp还是直接ip地址？

**Comment by waylau** [comment]
@fun5rt   之前 总结过一下 ，你看下  http://www.waylau.com/use-gmail/

**Comment by waylau** [comment]
![001](https://cloud.githubusercontent.com/assets/3233966/10903914/c7ea081a-8249-11e5-8dd8-774d9365473d.jpg)
客户端设置

**Comment by fun5rt** [comment]
你的hosts文件就是使用racaljk的hosts么？
还需要把racaljk hosts里面的以下三条做修改么？
173.194.65.108 imap.gmail.com 
173.194.65.108 pop.gmail.com 
173.194.193.108 smtp.gmail.com

**Comment by waylau** [comment]
我本地的是

64.233.188.109	imap.gmail.com
64.233.188.109	pop.gmail.com
64.233.188.109	smtp.gmail.com

blog 那个地址应该是旧的了。
你用我本地的IP 设置进去试下
忘了这些 IP 是否是来自 racaljk的hosts

**Comment by fun5rt** [comment]
T.T
按照你的ip更新了下host，真的可以了，原来还是ip地址的问题

万分感谢！

**Comment by fun5rt** [comment]
closed

**Comment by Mility** [comment]
为什么我试了 不成功啊？？？

**Comment by waylau** [comment]
@Mility   按照我的IP 来

**Comment by Mility** [comment]
@waylau 是的  我就是换成你的了  我用的是Foxmail客户端  host是这里最新的  就是创建不了  这是为何啊

**Comment by fun5rt** [comment]
刷新dns了嘛？我就是用的这里的host，然后上面三行做了替换，就可以使用了，网页认证和imap/smtp都可以了

**Comment by andytimes** [comment]
@waylau 感谢你提供的IP，另外64.233.162.81-87之间也存在gmail收信的IP

**Comment by Mility** [comment]
@fun5rt 刷新了的 还是不可以 也不知道为何

**Comment by andytimes** [comment]
@Mility 可能是地区问题，74.125.204.108
试试这个IP

**Comment by Mility** [comment]
@andytimes 刚刚改了一下密码 现在用客户端登录不了就是一直提示密码不正确 我也是醉了

**Comment by fun5rt** [comment]
密码不对估计就是没连上，我没连上也是提示密码问题。
你host里改的时候需要把原来的那三条删除啊，不要直接加，这样就冲突了。

**Comment by andytimes** [comment]
在 2015年11月3日 星期二 05:23:05，Mility 写道：
> @andytimes 刚刚改了一下密码 现在用客户端登录不了就是一直提示密码不正确 我也是醉了
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/racaljk/hosts/issues/80#issuecomment-153350583
@Mility 请更新hosts文件，然后刷新dns缓存（或者断网一次），hosts前面的规则会覆盖后面
的规则。

**Comment by whinamp** [comment]
我用spark。经过修改也成功复活了。感谢！

**Comment by dodopeng** [comment]
恭喜！



helloliuchang@live.cn
 
发件人： whinamp
发送时间： 2015-11-04 11:23
收件人： racaljk/hosts
主题： Re: [hosts] Gmail 客户端问题 (#80)
我用spark。经过修改也成功复活了。感谢！

**Comment by aofall** [comment]
@andytimes Gmail的IMAP、POP、SMTP部分我已经解决了，密码错误的问题是因为登陆IP和常用登陆地点不符，这个issue可以关闭了

**Comment by fun5rt** [comment]
close
