### ISSUE TITLE
hosts为html代码

### ISSUE THREAD

**Issue by fpsqdb** [racaljk/hosts#802]
使用windows.zip里的自动更新工具，但是更新后的hosts文件内容是html代码，如下：
`<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <meta content="width=device-width,initial-scale=1,maximum-scale=1,user-scalable=no" name="viewport" id="viewport">
    <title>404 Not Found</title>
    <style type="text/css">
        html, body {
            width: 100%;
            height: 100%;
            margin: 0;
            padding: 0;
            background-color: #000;
            font-family: "PingFang SC", "Helvetica Neue", "Hiragino Sans GB", "Segoe UI", "Microsoft YaHei", "微软雅黑", sans-serif;
            overflow: hidden;
        }
        h1, div, p, a {
            color: #fff;
        }
        a {
            text-decoration: none;
        }
        .circle {
            height: 100px;
            width: 100px;
            display: inline-block!important;
            border-radius: 100px;
            background-color: #fdfdfe;
            float: right;
            margin-top: 260px;
        }
        .forgive {
            color: #262626;
            font-size: 14px;
            display: block;
            width: 60px;
            margin-top: 27px;
            margin-left: 23px;
        }
        .eye {
            background-color: #262626;
            height: 20px;
            width: 20px;
            display: inline-block!important;
            border-radius: 20px;
            position: relative;
        }
    </style>
</head>

<body>
<div style="width: 960px; margin: 10% auto">
    <div style="width: 40%;float: left">
        <div class="eye" style="left: 125px; top: -140px"></div>
        <div class="eye" style="left: 250px; top: -140px"></div>
        <img src="https://dn-coding-net-production-static.qbox.me/static/4fed99a3dc1af35300cc96113ba332bb.png" alt="404 Not Found" style="width: 85%">
    </div>
    <div style="float: left; color: #000; width: 60%">
        <div style="margin-left: 50px">
            <div style="font-size: 500%">404!</div>
            <div style="font-size: 150%">页面，我找不到你，我找不到你啊~</div>
        </div>
    </div>
    <div class="circle">
        <a href="https://coding.net/"><span class="forgive" style="margin-top:38px">返回首页</span></a>
    </div>
</div>
</body>
</html>`

**Comment by liangyuteng0927** [comment]
404了，我也发了Issues：#803
虽然基本上上google都用ss，但是有时候hosts也挺方便的

**Comment by Too-Naive** [comment]
不好意思 因为获取镜像比较快 所以直接走镜像通道 这个会马上修复
