### ISSUE TITLE
coding 镜像404

### ISSUE THREAD

**Issue by liangyuteng0927** [racaljk/hosts#803]
## 前天好好的，今天就404了
https://coding.net/u/scaffrey/p/hosts/git/raw/master/hosts

**Comment by Too-Naive** [comment]
确认404 @Ir1d

**Comment by liangyuteng0927** [comment]
嗯谢谢，我去google一般都是挂ss的，用hosts上play商店怕锁区（有了解锁区方面的事吗？酷安有人说用了hosts上几次play商店被锁了，所以不敢在手机上用，但是ss又很耗电），这两天试了试hosts，真心好用~谢谢你们。 @Too-Naive

**Comment by Too-Naive** [comment]
= =没有fix没有必要close fix完自然会close= =

**Comment by Too-Naive** [comment]
至少要等 @Ir1d 给个答复

**Comment by liangyuteng0927** [comment]
好的，加油↖(^ω^)↗

**Comment by Ir1d** [comment]
#797 related

**Comment by Too-Naive** [comment]
不懂和那个有什么关系

**Comment by tvvocold** [comment]
Hi,
我是 @Coding 的 Ray，这个项目被删除是因为我们收到了 Google 的安全警告 [1]，Google 在这个项目 http://coding.net/u/scaffrey/p/hosts/git 中检测到了恶意软件或垃圾软件，这导致 #797 中的问题，即无论用户在 GitHub 还是 Coding 下载这个项目时都会收到 Chrome 的安全警告，由于这个项目同时影响了其他用户的项目正常下载 [2]， 根据我们的使用条款，我们对这个项目进行了删除操作，并发送删除原因及项目备份文件给其作者 @Ir1d 。

这个项目被视为恶意软件的原因是修改用户 hosts 文件，这可能被用来钓鱼等 （虽然其项目的本意是善意的），详见 Google 的垃圾软件政策。 [3] 

[1] https://dn-coding-net-production-pp.qbox.me/ced37a39-908a-4afd-a5ae-4208f4316fdb.png
[2] https://coding.net/u/thelastwolf/pp/135496
[3] https://www.google.com/about/company/unwanted-software-policy.html

如果大家对此有任何意见或建议，请回复我；）

Regards,
Ray
Coding.net

**Comment by Too-Naive** [comment]
@tvvocold 好噢 那这个就是我的锅 但是问题是 代码的源代码在 https://github.com/HostsTools/Windows 任何发布的软件的bin文件和sha1都在release页面中 能不能恳请Google方面对源代码进行review 项目的本意只是方便用户进行更新 别无什么"劫持hosts文件"的功能 而替换的hosts文件还是从本项目上下载的 所以 如果方便的话可以向他们提出review请求 在此表示感谢
(如果你要说让我提供源代码即可 事实上许多人不会用编译器 所以才有二进制文件一说)

**Comment by Ir1d** [comment]
决定就是你了！做一点微小的工作吧！静静你来给Google发个邮件吼不吼
https://www.v2ex.com/t/321844

**Comment by Too-Naive** [comment]
他爱删就删啊 没空做这个事情
