### ISSUE TITLE
求助，host文件内容自动变HTML，替换几次都自动改变，这个怎么解决？

### ISSUE THREAD

**Issue by fayewonghz** [racaljk/hosts#807]
自动变成这个内容：

<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <meta content="width=device-width,initial-scale=1,maximum-scale=1,user-scalable=no" name="viewport" id="viewport">
    <title>404 Not Found</title>
    <style type="text/css">
        html, body {
            width: 100%;
            height: 100%;
            margin: 0;
            padding: 0;
            background-color: #000;
            font-family: "PingFang SC", "Helvetica Neue", "Hiragino Sans GB", "Segoe UI", "Microsoft YaHei", "微软雅黑", sans-serif;
            overflow: hidden;
        }
        h1, div, p, a {
            color: #fff;
        }
        a {
            text-decoration: none;
        }
        .circle {
            height: 100px;
            width: 100px;
            display: inline-block!important;
            border-radius: 100px;
            background-color: #fdfdfe;
            float: right;
            margin-top: 260px;
        }
        .forgive {
            color: #262626;
            font-size: 14px;
            display: block;
            width: 60px;
            margin-top: 27px;
            margin-left: 23px;
        }
        .eye {
            background-color: #262626;
            height: 20px;
            width: 20px;
            display: inline-block!important;
            border-radius: 20px;
            position: relative;
        }
    </style>
</head>

<body>
<div style="width: 960px; margin: 10% auto">
    <div style="width: 40%;float: left">
        <div class="eye" style="left: 125px; top: -140px"></div>
        <div class="eye" style="left: 250px; top: -140px"></div>
        <img src="https://dn-coding-net-production-static.qbox.me/static/4fed99a3dc1af35300cc96113ba332bb.png" alt="404 Not Found" style="width: 85%">
    </div>
    <div style="float: left; color: #000; width: 60%">
        <div style="margin-left: 50px">
            <div style="font-size: 500%">404!</div>
            <div style="font-size: 150%">页面，我找不到你，我找不到你啊~</div>
        </div>
    </div>
    <div class="circle">
        <a href="https://coding.net/"><span class="forgive" style="margin-top:38px">返回首页</span></a>
    </div>
</div>
</body>
</html><!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <meta content="width=device-width,initial-scale=1,maximum-scale=1,user-scalable=no" name="viewport" id="viewport">
    <title>404 Not Found</title>
    <style type="text/css">
        html, body {
            width: 100%;
            height: 100%;
            margin: 0;
            padding: 0;
            background-color: #000;
            font-family: "PingFang SC", "Helvetica Neue", "Hiragino Sans GB", "Segoe UI", "Microsoft YaHei", "微软雅黑", sans-serif;
            overflow: hidden;
        }
        h1, div, p, a {
            color: #fff;
        }
        a {
            text-decoration: none;
        }
        .circle {
            height: 100px;
            width: 100px;
            display: inline-block!important;
            border-radius: 100px;
            background-color: #fdfdfe;
            float: right;
            margin-top: 260px;
        }
        .forgive {
            color: #262626;
            font-size: 14px;
            display: block;
            width: 60px;
            margin-top: 27px;
            margin-left: 23px;
        }
        .eye {
            background-color: #262626;
            height: 20px;
            width: 20px;
            display: inline-block!important;
            border-radius: 20px;
            position: relative;
        }
    </style>
</head>

<body>
<div style="width: 960px; margin: 10% auto">
    <div style="width: 40%;float: left">
        <div class="eye" style="left: 125px; top: -140px"></div>
        <div class="eye" style="left: 250px; top: -140px"></div>
        <img src="https://dn-coding-net-production-static.qbox.me/static/4fed99a3dc1af35300cc96113ba332bb.png" alt="404 Not Found" style="width: 85%">
    </div>
    <div style="float: left; color: #000; width: 60%">
        <div style="margin-left: 50px">
            <div style="font-size: 500%">404!</div>
            <div style="font-size: 150%">页面，我找不到你，我找不到你啊~</div>
        </div>
    </div>
    <div class="circle">
        <a href="https://coding.net/"><span class="forgive" style="margin-top:38px">返回首页</span></a>
    </div>
</div>
</body>
</html>

您好，感谢您开 Issue 来反馈信息，在提交前，请确保您已经检查了以下内容!
- 如有关" Google 无法连接" / " YouTube 视频无法播放"等问题 请参阅[常见问题解答](https://github.com/racaljk/hosts/wiki/The-hosts-FAQ)
- 已经阅读了 [Wiki 页面](https://github.com/racaljk/hosts/wiki)
- 已经搜索过之前的相关 [Issues](https://github.com/racaljk/hosts/search?type=Issues)
- 如果是报告问题，请确认问题可以复现并且没有重复报告同一个问题；如果是向 hosts 提供新的信息，请确认所提供信息的来源以及相关许可协议；欢迎使用 Pull Requests 功能（可以通过[直接编辑文件](https://github.com/racaljk/hosts/edit/master/hosts)的方式来提交）

如果您有其他附言，例如问题只在某个页面发生，或者是一般性讨论、提出新功能，请一定注明

或者您也可以卖个萌

我们同时有一个 [Gitter Room](https://gitter.im/racaljk/hosts)，以及一个[在 Coding 上的镜像](https://coding.net/u/scaffrey/p/hosts)

**Comment by fayewonghz** [comment]
我把host文件改成只读解决了

**Comment by fayewonghz** [comment]
貌似改了只读都没用，自动会改成非只读，没搞清原因

**Comment by mrlittlenew** [comment]
你是不是用了自动替换服务？关闭，因为自动那个会下载coding的host文件，但是coding那边的项目已经失效，所以获取的host内容有问题。直接关闭自动更新服务，手动替换就好了。

**Comment by mrlittlenew** [comment]
参考 #802

**Comment by Too-Naive** [comment]
请更新
