### ISSUE TITLE
谷歌身份验证器无法与服务器通讯

### ISSUE THREAD

**Issue by Vstory** [racaljk/hosts#809]
校正谷歌身份验证器时，无法与Google服务器通讯。

**Comment by jasonyankees** [comment]
开了hosts还是无法通过验证？

vsix <notifications@github.com>于2016年11月17日星期四 11:00写道：

**Comment by Vstory** [comment]
是的，之前可以，最近失败的。

**Comment by andytimes** [comment]
@Vstory 你可以试试 Authy
Android: https://play.google.com/store/apps/details?id=com.authy.authy&hl=zh_CN
iOS: https://itunes.apple.com/cn/app/authy/id494168017?mt=8
