### ISSUE TITLE
搬瓦工VPS官网被墙

### ISSUE THREAD

**Issue by lrinQVQ** [racaljk/hosts#812]
http://ping.chinaz.com/bandwagonhost.com
![1](https://cloud.githubusercontent.com/assets/12861134/20445428/ff932bfa-ae0f-11e6-81b2-776fcf4a8ff6.png)

全红orz
所有UDP的DNS查询都被污染到93.46.8.89
dig bandwagonhost.com @8.8.8.8  

; <<>> DiG 9.10.3-P4-Ubuntu <<>> bandwagonhost.com @8.8.8.8
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 13698
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;bandwagonhost.com.		IN	A

;; ANSWER SECTION:
bandwagonhost.com.	2188	IN	A	93.46.8.89

;; Query time: 39 msec
;; SERVER: 8.8.8.8#53(8.8.8.8)
;; WHEN: Sat Nov 19 04:15:06 CST 2016
;; MSG SIZE  rcvd: 68

使用TCP的DNS查询能够查询正确的IP
dig +tcp bandwagonhost.com @8.8.8.8  

; <<>> DiG 9.10.3-P4-Ubuntu <<>> +tcp bandwagonhost.com @8.8.8.8
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 35875
;; flags: qr rd ra; QUERY: 1, ANSWER: 2, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;bandwagonhost.com.		IN	A

;; ANSWER SECTION:
bandwagonhost.com.	299	IN	A	104.20.6.63
bandwagonhost.com.	299	IN	A	104.20.7.63

;; Query time: 228 msec
;; SERVER: 8.8.8.8#53(8.8.8.8)
;; WHEN: Sat Nov 19 04:15:12 CST 2016
;; MSG SIZE  rcvd: 78

这是Ping测试:
ping -c 4 104.20.6.63
PING 104.20.6.63 (104.20.6.63) 56(84) bytes of data.
64 bytes from 104.20.6.63: icmp_seq=1 ttl=52 time=205 ms
64 bytes from 104.20.6.63: icmp_seq=2 ttl=52 time=205 ms
64 bytes from 104.20.6.63: icmp_seq=3 ttl=52 time=205 ms
64 bytes from 104.20.6.63: icmp_seq=4 ttl=52 time=205 ms

--- 104.20.6.63 ping statistics ---
4 packets transmitted, 4 received, 0% packet loss, time 3004ms
rtt min/avg/max/mdev = 205.488/205.651/205.919/0.482 ms
http://ping.chinaz.com/104.20.6.63
![2](https://cloud.githubusercontent.com/assets/12861134/20445836/b664ae98-ae11-11e6-9c82-2221f8b65a78.png)

**Comment by Ir1d** [comment]
@racaljk 拍板一下吧 我们要不要做 Open China

**Comment by racaljk** [comment]
我们不是一直都这么做的么....

名为google hosts，然而口嫌体正直

**Comment by lrinQVQ** [comment]
233333噗嗤

**Comment by lrinQVQ** [comment]
_(:з」∠)_所以要不干脆尽力的将所有被墙的网站都收录如何？ 2333 @racaljk

**Comment by lrinQVQ** [comment]
_(:з」∠)_所以 你们觉得可以把搬瓦工官网添加进去么2333 我觉得…毕竟国内用的人还是挺多的…价格低廉 …速度也挺快的 可以加入 你们怎么看 @racaljk @Too-Naive @Ir1d

**Comment by imknown** [comment]
说好的 `google hosts` 哪...

**Comment by lrinQVQ** [comment]
@imknown 其实google hosts 也可以理解为谷歌能够搜索到的网站的hosts嘛 对不对orz

**Comment by lrinQVQ** [comment]
当然我也只是提个意见2333 项目名字是叫hosts嘛orz 所以加入一些其他的貌似也没有问题咩?

**Comment by Too-Naive** [comment]
`🗽最新可用的google hosts文件。`
