### ISSUE TITLE
中国移动的节点有问题吗？

### ISSUE THREAD

**Issue by 67au** [racaljk/hosts#819]
中国移动的cmwap的10.0.0.172:80上不了Google,但是cmnet可以上

**Comment by imknown** [comment]
cmwap... 自从 塞班不行了之后, 这个就没有再用过了..

**Comment by lrinQVQ** [comment]
cmwap...好像除了免流...很少有人用了吧 
你可以试试用https://www.google.com/ncr

**Comment by LGA1150** [comment]
使用HTTP代理会忽略本地hosts，因为DNS解析都是在HTTP代理服务器上进行的
你只能修改代理服务器上的hosts，但显然不现实
