### ISSUE TITLE
建议OneDrive的ip替换下

### ISSUE THREAD

**Issue by yym0924** [racaljk/hosts#821]
134.170.108.26 onedrive.live.com
134.170.108.152 skyapi.onedrive.live.com
替换成这个会比较好
现在的并不能完全正常访问。
注：四川电信

**Comment by lrinQVQ** [comment]
+1 确实存在这个问题

**Comment by oilbottle** [comment]
确实是好点，不过我的onedrive客户端依然不能用\哭

**Comment by yym0924** [comment]
@oilbottle 不能吧，我之前本地同步即使不改Hosts也能用，但是UWP版看不到有哪些文件。改了Hosts之后是都正常了

**Comment by oilbottle** [comment]
@yym0924 OneDrive UWP电脑版和手机版都试了，都不行，连个700K的pdf都下不下来。坐标深圳，移动和联通。已经持续一个多月了

**Comment by yym0924** [comment]
@oilbottle 用Win32客户端呢

**Comment by yym0924** [comment]
@oilbottle 下载涉及到的是下面这两个
204.79.197.213 ######files.storage.live.com

204.79.197.213 *.######.livefilestore.com

这个的话系统自己的Hosts不支持通配符啊，每个的地址都不一样，你的每个目录也不一样

**Comment by Too-Naive** [comment]
把所有的地址塞进来?(雾

**Comment by yym0924** [comment]
@Too-Naive 不太可能啊，那些地址是一串至少肉眼看起来就是随机字符。╮(╯▽╰)╭只能用Acrylic DNS Proxy了。我这边是不加这两个地址下载速度很慢，但是还是可以用的。加了之后接近满速。

**Comment by Too-Naive** [comment]
身在墙外的我并不知道那些是什么(



On yym0924 <notifications@github.com>, Nov 21, 2016 16:49 wrote:

@Too-Naive<https://github.com/Too-Naive> 不太可能啊，那些地址是一串至少肉眼看起来就是随机字符。╮(╯▽╰)╭只能用Acrylic DNS Proxy了。我这边是不加这两个地址下载速度很慢，但是还是可以用的。加了之后接近满速。

**Comment by yym0924** [comment]
@Too-Naive 一个本地DNS代理的软件，支持有通配符的Hosts文件。

**Comment by yym0924** [comment]
@Too-Naive 不过自己多试几次，把自己的地址都试出来再加上IP好像也行。但是我之前这么做了，过段时间地址会变。

**Comment by oilbottle** [comment]
@yym0924 不太懂，是把
204.79.197.213 ######files.storage.live.com
204.79.197.213 *.######.livefilestore.com
放到AcrylicHosts里面吗？那是不是所有改动的hosts都要放在AcrylicHosts里？

还有我试了下134.170.108.26 onedrive.live.com ping不通，但确实是有用，这是为什么呢0.0

**Comment by lrinQVQ** [comment]
@oilbottle 某些服务器是禁PING的丫

**Comment by oilbottle** [comment]
@lrinQVQ 哦谢谢哈

**Comment by lrinQVQ** [comment]
@oilbottle 我看下了昂 客户端登陆的时候会连接ssw.live.com

**Comment by oilbottle** [comment]
@IrinQVQ thx

**Comment by Too-Naive** [comment]
@oilbottle ping over tcp

**Comment by yym0924** [comment]
@oilbottle 我试了下，似乎应该这么写
204.79.197.213 *.storage.live.com
204.79.197.213 *.livefilestore.com
