### ISSUE TITLE
outlook的邮箱服务器都不行了

### ISSUE THREAD

**Issue by tingbob** [racaljk/hosts#824]
outlook的两个收发服务器都不可以了
imap-mail.outlook.com
smtp-mail.outlook.com
直接表现就是用邮件客户端设置结果是离线状态

**Comment by Too-Naive** [comment]
outlook不是在国内只是慢吗。。 不是很懂为什么要增加这个outlook的域名

**Comment by lrinQVQ** [comment]
@Too-Naive 貌似==已经不止是慢了

**Comment by Too-Naive** [comment]
ISP?

**Comment by lrinQVQ** [comment]
移动+联通

**Comment by Too-Naive** [comment]
地区。。

**Comment by lrinQVQ** [comment]
outlook.live.com 开始丢包

**Comment by lrinQVQ** [comment]
重庆移动+重庆联通

**Comment by Too-Naive** [comment]
没在国内没法测试 我记得我出来之前很正常

**Comment by lrinQVQ** [comment]
@Too-Naive 我也是看到这个issues才测试了下的23333

**Comment by Too-Naive** [comment]
丢包是一个问题 但是能不能打开 如果可以打开的话 其实没有必要添加hosts..

**Comment by lrinQVQ** [comment]
@Too-Naive orz 可以打开主页2333然后其他的gg 233

**Comment by Too-Naive** [comment]
我挂国内ss试试

**Comment by lrinQVQ** [comment]
嗯嗯

**Comment by lrinQVQ** [comment]
等了10分钟了==
![qq 20161123094545](https://cloud.githubusercontent.com/assets/12861134/20557036/b534a370-b1a4-11e6-9f95-9f0c063042f0.png)

**Comment by Too-Naive** [comment]
= =我这个ss本身有问题 等其他国内用户来评论吧

**Comment by Too-Naive** [comment]
开了ss我啥都开不了 百度用了4分钟

**Comment by lrinQVQ** [comment]
23333心疼

**Comment by lrinQVQ** [comment]
![qq 20161123095154](https://cloud.githubusercontent.com/assets/12861134/20557209/8e95e430-b1a5-11e6-832f-d4521c030462.png)
终于出来了

**Comment by lrinQVQ** [comment]
刚刚给自己的QQ邮箱发了个邮件== 看多久能收到

**Comment by lrinQVQ** [comment]
无法发送邮件啧

**Comment by lrinQVQ** [comment]
![qq 20161123095154](https://cloud.githubusercontent.com/assets/12861134/20557271/cfc6de6e-b1a5-11e6-8aea-e40e9bd2a2a7.png)
看来收发服务器的问题确实存在

**Comment by Too-Naive** [comment]
![](https://cloud.githubusercontent.com/assets/16496671/20557321/f47b3c50-b1a5-11e6-8810-8edc50a65778.png)

**Comment by lrinQVQ** [comment]
滑稽

**Comment by lrinQVQ** [comment]
ss全局代理秒发//滑稽

**Comment by lrinQVQ** [comment]
一个有趣的消息 重庆移动秒开 秒发@Too-Naive @tingbob

**Comment by tingbob** [comment]
浙江电信，而且是邮件客户端，使用的收发服务器。

Peter Lv

在 2016年11月23日，18:01，lrin <notifications@github.com<mailto:notifications@github.com>> 写道：


一个有趣的消息 重庆移动秒开 秒发@Too-Naive<https://github.com/Too-Naive> @tingbob<https://github.com/tingbob>

―

**Comment by lrinQVQ** [comment]
@tingbob 那你试试
40.96.18.130 outlook.live.com
207.46.10.10 imap-mail.outlook.com

**Comment by lrinQVQ** [comment]
![screenshot_2016-11-23-18-17-02-771_com android email](https://cloud.githubusercontent.com/assets/12861134/20558043/3506c462-b1a9-11e6-9436-dec994510b67.png)
![screenshot_2016-11-23-18-16-55-856_com android email](https://cloud.githubusercontent.com/assets/12861134/20558047/3986480a-b1a9-11e6-8e97-77128722bf1c.png)
![screenshot_2016-11-23-18-16-48-954_com android email](https://cloud.githubusercontent.com/assets/12861134/20558049/3bdd8262-b1a9-11e6-959a-b74027582c87.png)

**Comment by tingbob** [comment]
郁闷了。移动可以，电信不可以。试了下在电信上还是不可以。
在 2016年11月23日，下午6:19，lrin <notifications@github.com<mailto:notifications@github.com>> 写道：


[screenshot_2016-11-23-18-17-02-771_com android email]<https://cloud.githubusercontent.com/assets/12861134/20558043/3506c462-b1a9-11e6-9436-dec994510b67.png>
[screenshot_2016-11-23-18-16-55-856_com android email]<https://cloud.githubusercontent.com/assets/12861134/20558047/3986480a-b1a9-11e6-8e97-77128722bf1c.png>
[screenshot_2016-11-23-18-16-48-954_com android email]<https://cloud.githubusercontent.com/assets/12861134/20558049/3bdd8262-b1a9-11e6-959a-b74027582c87.png>

**Comment by lrinQVQ** [comment]
@tingbob 心疼max 2333

**Comment by Ir1d** [comment]
又看到静静说不在国内了
不知道该说些什么

**Comment by aofall** [comment]
<del>台湾很多青年不都这样嘛</del>

**Comment by lrinQVQ** [comment]
@aofall ==

**Comment by lucf1103** [comment]
Gmail现在访问不了了？之前可以的内

**Comment by sqc1999** [comment]
浙江电信网页版和客户端都正常诶。。

**Comment by tingbob** [comment]
今天真的可以了。我也不知道什么情况了。

**Comment by lrinQVQ** [comment]
@tingbob 神奇的事情2333

**Comment by Too-Naive** [comment]
为什么要一直纠结一些奇怪的问题 不是很懂你们到底重点在看哪里

**Comment by Too-Naive** [comment]
整天纠结一些没有任何意义的事情 真的是有这种必要吗？

**Comment by BROBIRD** [comment]
……有点偏题了吧，静静只是说了一下事实，他测不了，我们测不就好了吗……

**Comment by lrinQVQ** [comment]
嘛= = 好好讨论hosts 不要撕逼 不要搞事情嘛,我也是刚回国不久来着啊==

**Comment by wanrui** [comment]
都想把事情搞大

**Comment by lucf1103** [comment]
也不知道为什么 Chrome上不了Google， Safari就可以了～

**Comment by bithugfan** [comment]
看新闻，貌似是微软自己的问题。
http://tech.sina.com.cn/i/2016-11-24/doc-ifxyawmn9959107.shtml

**Comment by andytimes** [comment]
目前 Outlook 访问不稳定，我直接设置转发到 Gmail 了。
