### ISSUE TITLE
osx 上面无法正常使用 telegram

### ISSUE THREAD

**Issue by Fezreal** [racaljk/hosts#828]
![image](https://cloud.githubusercontent.com/assets/6703674/20637453/c3797142-b3c3-11e6-922d-9a60262a45d9.png)

这样填在 ss 的规则列表里了, 可是还是不正常, 有填错吗

**Comment by BROBIRD** [comment]
telegram收发信息使用的是内置的IP地址，你需要手动把Telegram的IP段加到ss的规则里

**Comment by p0oo0q** [comment]
IP段 
91.108.4.0/22
91.108.56.0/22
109.239.140.0/24
149.154.160.0/20
194.14.177.0/24
194.68.28.0/23
194.68.30.0/24
194.132.172.0/24
194.132.162.0/24
193.182.7.0/24

**Comment by p0oo0q** [comment]
另外 网页版
 # Telegram start
149.154.167.99    telegram.org
149.154.167.99    www.telegram.org
149.154.167.99    macos.telegram.org
149.154.167.99    core.telegram.org
149.154.167.120   web.telegram.org
149.154.167.118   telegram.me
149.154.167.118   www.telegram.me
149.154.167.99    desktop.telegram.org
149.154.167.57    venus.web.telegram.org
149.154.167.57    venus-1.web.telegram.org
149.154.167.124   vesta.web.telegram.org
149.154.167.124   vesta-1.web.telegram.org
149.154.171.22    flora.web.telegram.org
149.154.171.22    flora-1.web.telegram.org
149.154.175.16    pluto.web.telegram.org
149.154.175.16    pluto-1.web.telegram.org
149.154.175.115   aurora.web.telegram.org
149.154.175.115   aurora-1.web.telegram.org
# Telegram end
