### ISSUE TITLE
可否添加pixnet.net的hosts？hosts-request

### ISSUE THREAD

**Issue by icybergking** [racaljk/hosts#838]
之前可以強加https來打開，現在不行了。
拜託各位。

**Comment by lrinQVQ** [comment]
_(:з」∠)_确实打不开

**Comment by lrinQVQ** [comment]
回家看看_(:з」∠)_

**Comment by sqc1999** [comment]
绍兴移动正常访问。。

**Comment by lrinQVQ** [comment]
103.23.108.107 这个IP可以 orz 目测有些地区被DNS污染了@icybergking

**Comment by icybergking** [comment]
103.23.108.107 我這個打不開，直接加https可以看到主頁，但是其他的文章什麼的就看不了了。@IrinQVQ

**Comment by lrinQVQ** [comment]
欸 我在看看

**Comment by sqc1999** [comment]
我刚才没细看，我也是能打开首页但打不开文章。
我观察了一下，发现www.pixnet.net这个域名是启用https的所以能打开，但是文章什么的是在各个博客的独立域名下的，而且这些域名如果用https访问的话，是会直接302跳转到http的，所以没什么办法。

**Comment by icybergking** [comment]
@sqc1999 我之前大概一個月還能看呢，現在完全不行了。之前也是自己手動添加https就行了
