### ISSUE TITLE
是否考虑添加pcbeta的hosts

### ISSUE THREAD

**Issue by redapple0204** [racaljk/hosts#849]
pcbeta不知怎么的最近无法访问，但是通过修改下面的hosts仍然可以：
>#pcbeta Start
218.93.127.136 bbs.pcbeta.com
218.93.127.136 www.pcbeta.com
218.93.127.136 uc.pcbeta.com
218.93.127.136 cdn.pcbeta.static.inimc.com
218.93.127.136 cdn.pcbeta.css.inimc.com
218.93.127.136 static.template.pcbeta.com
218.93.127.136 i.pcbeta.com
218.93.127.136 cdn.pcbeta.attachment.inimc.com
218.93.127.136 mac.pcbeta.com
218.93.127.136 cdn.pcbeta.img.inimc.com
#pcbeta End

**Comment by racaljk** [comment]
应该暂时无法访问吧，留待以后决定
