### ISSUE TITLE
安卓6.0，用你这个hosts，谷歌mail和drive能正常使用，但是play商店只能浏览无法下载安装应用

### ISSUE THREAD

**Issue by tulip33** [racaljk/hosts#850]
用vpn能下载play应用，但不方便，希望能通过hosts即可正常下载安装应用，谢谢！

**Comment by webfans** [comment]
把hosts里面的~~广告屏蔽部分~~去掉，应该就可以了！

**Comment by racaljk** [comment]
[为什么不推荐在移动设备上使用hosts？](https://github.com/racaljk/hosts/wiki/%E4%B8%BA%E4%BB%80%E4%B9%88%E4%B8%8D%E6%8E%A8%E8%8D%90%E5%9C%A8%E7%A7%BB%E5%8A%A8%E8%AE%BE%E5%A4%87%E4%B8%8A%E4%BD%BF%E7%94%A8hosts%EF%BC%9F)
