### ISSUE TITLE
Android端实测YouTube可以播放 PC不能

### ISSUE THREAD

**Issue by tianrking** [racaljk/hosts#851]
为什么Android端使用hosts YouTube可以播放  不是说YouTube视频服务器是固定IP么  ？ 能否利用修改UA实现PC端播放

**Comment by andytimes** [comment]
可能和修改 UA 无关，Youtube 视频服务器确实是固定 IP，应该是你用了别的 hosts, 里面把 googlevideo.com 域名指向了反向代理，但域名有缺失，所以只有部分可以看，建议你去
联系提供这部分 hosts 的人。
