### ISSUE TITLE
Host Request balatarin.com

### ISSUE THREAD

**Issue by nxp1024** [racaljk/hosts#853]
https://www.balatarin.com has been blocked, add it in hosts.

**Comment by racaljk** [comment]
广西电信正常访问..

另外这是什么奇怪的网址..confused..

**Comment by Too-Naive** [comment]
这不清真



On Cthulhu <notifications@github.com>, Dec 12, 2016 07:14 wrote:

Closed #853<https://github.com/racaljk/hosts/issues/853>.
