### ISSUE TITLE
新增的 OneDrive 部分导致 Mac OneNote 无法同步，OneDrive 页面打开偶尔空白，无内容

### ISSUE THREAD

**Issue by qinwf** [racaljk/hosts#855]
删除 OneDrive 部分以后回复正常。

OneNote 同步提示 0x803D000A 错误，Google 的搜索结果似乎提示是与证书错误有关。

**Comment by panpando** [comment]
这部分我找的IP，确实有证书问题，但onedrive速度快了不少
我不用OneNote，你方便抓一下地址发上来吧

**Comment by mcxinyu** [comment]
使用 hosts 后会导致 Android 版 OneDrive 上传失败，删除 OneDrive 部分 hosts 后正常。建议删除，因为国内剋正常访问，用了 hosts 后反而出问题了。

**Comment by linxiaocong** [comment]
OneDrive确实有问题强烈建议删掉

**Comment by yym0924** [comment]
@panpando 
204.79.197.213 *.livefilestore.com
204.79.197.213 *.files.1drv.com 
涉及这两类域名如果不用通配符其实是无解的，以为会因为人和目录变化。
这次的修改加的很多域名其实对大家并没有用

**Comment by redapple0204** [comment]
深圳地区移除OneDrive就没法开了，哎...

**Comment by oilbottle** [comment]
@redapple0204 是这样，深圳不能用大概有两个月了

**Comment by aofall** [comment]
@panpando 这就是为什么Microsoft的hosts我只做了Onedrive的解析
MS大部分的分地区解析已经做的非常好了，除了 onedrive.live.com （因为DNS污染）
有中国大陆的网宿CDN，有美国Akamai，还有他自己自建的机房，所以不需要做多余的解析，还有的二级域名每个人或者不同地区是不一样的
不然就会出现证书错误之类的情况，有些在网页上没问题的在客户端上不一定能用（SNI支持，不需要多说什么）

    # OneDrive
    204.79.197.217 onedrive.live.com
    204.79.197.217 skyweb.skyprod.akadns.net
    204.79.197.217 webedgegeo.skyprod.akadns.net

**Comment by andytimes** [comment]
在 2017年1月27日 上午12:27，aofall <notifications@github.com>写道：

> @andytimes 修改后可把 #824 一同关闭
>
> # Microsoft
> 204.79.197.217 onedrive.live.com
> 204.79.197.217 skyweb.skyprod.akadns.net
> 204.79.197.217 webedgegeo.skyprod.akadns.net
> 13.107.42.11 outlook.live.com

好的，我现在来修改，不过接下来一段时间要回亲戚家，可能没法碰电脑，
回家时大概就开学了。

Thanks,
Andy

**Comment by Ir1d** [comment]
@andytimes 开学了？？？

**Comment by andytimes** [comment]
@Ir1d 是的，因为一些事要回去一段时间，我老家比较远。
