### ISSUE TITLE
wordpress问题

### ISSUE THREAD

**Issue by wongnet** [racaljk/hosts#857]
68.232.44.111	s0.wp.com
68.232.44.111	s1.wordpress.com
68.232.44.111	s1.wp.com
等存在问题：
404 - Not Found
显示的wordpress网页有问题（可能是脚本或者css未正确下载）

**Comment by sy618** [comment]
试试把IP 68.232.44.111改为192.0.77.32

**Comment by andytimes** [comment]
已改，wordpress 现在不用 hosts 也可以正常解析
https://github.com/racaljk/hosts/commit/5fed2f250c0bc305fd01e54ddb0a0ac01af5d405

**Comment by andytimes** [comment]
已改，wordpress 现在不用 hosts 也可以正常解析
https://github.com/racaljk/hosts/commit/5fed2f250c0bc305fd01e54ddb0a0ac01af5d405
