### ISSUE TITLE
README中对于GNU\Linux下的脚本地址更新

### ISSUE THREAD

**Issue by fangd123** [racaljk/hosts#86]
我看到脚本的实际地址已经改了，但是再README中还没改，麻烦作者改一下咯～

```wget https://raw.githubusercontent.com/racaljk/hosts/master/scripts/script_tool_for_linux.sh -O - | sudo bash - ```

**Comment by racaljk** [comment]
其实我觉得用wget获取script再用script获取hosts很奇怪..

**Comment by K-Guan** [comment]
哦，等下我改了。

**Comment by K-Guan** [comment]
@racaljk 我看还行呀，不这样？

**Comment by fangd123** [comment]
@racaljk 毕竟hosts文件是跨平台的，这样写相当于针对Linux平台~~

**Comment by racaljk** [comment]
已修改
