### ISSUE TITLE
谷歌总是定位到香港，不开心啊

### ISSUE THREAD

**Issue by qiangdezhen** [racaljk/hosts#862]
改hosts能不能直接定位到https://google.com/ncr 啊？有么有大神看看，现在这个chrome打开新的标签页默认搜索强制根据ip定位好蛋疼，不喜欢被强制用香港谷歌啊，要是实在不行就算了，我就是问问。。。

**Comment by sqc1999** [comment]
从理论上讲用hosts是不能实现这个功能的。。

**Comment by qiangdezhen** [comment]
那可不可以让chrome在新建标签页的时候用google.com/ncr呢？每次新建标签页都是用的香港真的很烦啊，设置里好像也没有以前那个选项了。。。

2016-12-20 9:20 GMT+08:00 Stalker <notifications@github.com>:

**Comment by swimuniverse** [comment]
c到chrome://settings/searchEngines

拷贝默认Google搜索引擎的URL（一般是灰色不能直接改），拉到最底下添加新搜索引擎，粘贴到URL框，把开头{google:baseURL}换成https://www.google.com/，然后设成默认。

如果不行的话可以试下面这个URL：
https://www.google.com/search?q=%s&pws=0&gl=us&gws_rd=cr
（用这个可能会缺失一些功能）

相关资料：
1. http://www.thesempost.com/force-google-chrome-to-use-google-com-not-country-version/
2. https://superuser.com/questions/468794/why-does-google-chrome-ignore-last-known-google-url-property-in-local-state
（里面还有另一种方法，改%localappdata%\Google\Chrome\User Data\Default里Preferences文档的last_known_google_url项，然后把Preferences设成只读，但我没试过行不行）

**Comment by qiangdezhen** [comment]
非常感谢你，果然github牛人出没，非常感谢你完美的解决了我的问题。

2016-12-20 15:39 GMT+08:00 swimuniverse <notifications@github.com>:
