### ISSUE TITLE
gist IP 失效请更换IP

### ISSUE THREAD

**Issue by silascript** [racaljk/hosts#864]
gist的IP **192.30.253.113**早失效

![113](https://cloud.githubusercontent.com/assets/13313323/21353593/b14f8e7e-c701-11e6-9158-4db17ab2e164.jpg)

以下两个ip可用：
192.30.253.118 
192.30.253.119 

![118119](https://cloud.githubusercontent.com/assets/13313323/21353602/bab95f12-c701-11e6-807d-d423bfb03659.jpg)

**Comment by imknown** [comment]
我这里是可以的

**Comment by jiangtiandao** [comment]
tcping?

**Comment by neverlous** [comment]
目前几个ip我这里都可以ping通。

**Comment by andytimes** [comment]
IP 确实变动了，谁有电脑就顺便改一下吧。

192.30.253.118
192.30.253.119

**Comment by silascript** [comment]
之前测试是在联通下进行的。今天换成电信的线测，192.30.253.113只能说是“半通”:
![pinggist](https://cloud.githubusercontent.com/assets/13313323/21422428/87323cd2-c872-11e6-87b9-46ab3828b875.jpg)

所以192.30.253.113这个IP肯定是有问题的。

**Comment by jiangtiandao** [comment]
try  http://ping.chinaz.com/
@silascript
