### ISSUE TITLE
请问在Windows下使用什么软件可以获取程序所访问的域名

### ISSUE THREAD

**Issue by yym0924** [racaljk/hosts#866]
我想自己研究下OneNote同步所访问的域名，不知道在Windows下可以使用哪些工具呢？
如果用防火墙的话似乎只能获取到访问的IP而不是域名

**Comment by andytimes** [comment]
http://www.telerik.com/fiddler

**Comment by yym0924** [comment]
@andytimes 十分感谢^_^
