### ISSUE TITLE
建议加个ipv4.google.com吧

### ISSUE THREAD

**Issue by bstaint** [racaljk/hosts#87]
建议把ipv4.google.com加上吧，有时候被限制了要输入验证码总是访问不了，得自己加。

**Comment by andytimes** [comment]
一般都不会从这个地址访问的，你自己添加吧
64.233.160.90 ipv4.google.com.hk


2015-11-14 20:29 GMT+08:00 bstaint <notifications@github.com>:

**Comment by bstaint** [comment]
好吧，我这里直接访问com的。
