### ISSUE TITLE
各位大佬好，能否增加twitch的hosts呢？

### ISSUE THREAD

**Issue by SchraderZhang** [racaljk/hosts#871]
如题，如果那位大佬能帮忙是极好的，如果考虑到这是个小众需求不好添加我也能理解。XD
另外，有没有大佬能教我如何制作hosts呢？万分感激。

**Comment by runtul** [comment]
我也想知姐找能用的IP ，网络上的教程没看太明白？

2016年12月24日 03:42，"SchraderZhang" <notifications@github.com>寫道：

**Comment by xmdhs** [comment]
twitch是什么 网址呢

**Comment by sqc1999** [comment]
@xmdhs 自己查一下不就知道了。。
@SchraderZhang
- 我这里绍兴移动是可以打开的，你的网络环境是什么？
- 你的第二个问题参看#685。

**Comment by SchraderZhang** [comment]
网址：https://www.twitch.tv/
好的谢谢楼上大佬的解答XD辛苦了，平安夜快乐。

**Comment by xmdhs** [comment]
为和我可以直接访问 
顺便圣诞节快乐

**Comment by SchraderZhang** [comment]
啊，各位大佬圣诞快乐。
生活工作学习愉快XD
