### ISSUE TITLE
現在hosts沒有get.google.com這個地址哦

### ISSUE THREAD

**Issue by xinlingcheng** [racaljk/hosts#873]
現在hosts沒有get.google.com這個地址哦 
今天無法打開get.google.com，原來hosts沒有這個地址，加上后就可以訪問了哦
https://get.google.com/apptips/apps/?utm_source=google&utm_campaign=owned-desktop-pushup-holidays&utm_medium=promo#!/all

**Comment by imknown** [comment]
https://github.com/racaljk/hosts/blob/master/hosts#L326

**Comment by xinlingcheng** [comment]
可以了，我是用的# Last updated: 2016-11-13的版本，现在有了
