### ISSUE TITLE
Facebook Messenger域名缺失补充！

### ISSUE THREAD

**Issue by sy618** [racaljk/hosts#874]
添加后，Messenger可以正常聊天，发照片。@racaljk
157.240.7.16 edge-mqtt.facebook.com

**Comment by lrinQVQ** [comment]
网页版测试不需要添加此域名也可以正常聊天发照片啊orz

**Comment by sy618** [comment]
在我群里有人反馈说Facebook messenger app使用异常，有些图片刷不出来，经过我排查确定就是缺失以上域名。添加后就好了。
如果觉得不需要，那么请无视此条反馈。

**Comment by TomHeaven** [comment]
根据我的测试，android手机Messenger确实需要这个域名才能正常显示用户头像等；否则app会一直提示“等待网络”或者“连接中”。 （测试于四川联通）
