### ISSUE TITLE
补充一个网址吧

### ISSUE THREAD

**Issue by imba-tjd** [racaljk/hosts#875]
`enterprise.google.com`

**Comment by imba-tjd** [comment]
貌似这个网址不再直接使用了……
打开后会自动跳转到https://www.google.com/cloud/
不过不加的话应该连跳转不会
是否添加你们自己决定吧

**Comment by Too-Naive** [comment]
验证确认跳转
![](https://cloud.githubusercontent.com/assets/16496671/21503148/0d568ba8-cc90-11e6-8f8b-54ee9a75f573.png)
