### ISSUE TITLE
关于Clipconverter不能使用的备用下载工具

### ISSUE THREAD

**Issue by AlexDialga** [racaljk/hosts#879]
由于本机在校园网中使用Clipconverter下载Youtube视频时，
发现在按下第二个Download（下载）后链接被重置，
似乎是googlevideo的问题，
于是在网上翻了下下载方法。
其中发现
https://www.onlinevideoconverter.com/
比较好用。

不是广告。不是广告。不是广告。重要的事情说三遍！

它和Clipconverter同样是网页型的视频转换下载工具，
而且还是https，安全性比前者强，
便推荐一下。

另外似乎Vimeo也可以用的样子。

**Comment by Too-Naive** [comment]
不过不是很懂你开这个issue的用意是什么 是想解决连接被重置的问题吗

**Comment by AlexDialga** [comment]
不算是。
因为有时候想搬一些视频，
而在Q&A中推荐的下载工具似乎失效了，
所以就自行推荐这个youtube视频下载工具。
另外希望在Q&A中提供多种安全的视频下载网址，
这样也方便看视频的人使用。

**Comment by Too-Naive** [comment]
噢噢。。。好 (你们好像可以直接改吧

**Comment by AlexDialga** [comment]
不是啦Σ(っ°Д°;)っ
知道怎么Edit，
然而不懂该怎么排版，
所以就这样搁着了，
希望编辑Q&A的大大能看看ww

**Comment by lrinQVQ** [comment]
欸其实可以自己试下的啦233 不难的@AlexDialga

**Comment by andytimes** [comment]
已改，wiki 好像可以公共编辑，可以自行修改。

**Comment by AlexDialga** [comment]
@andytimes
谢谢大大辣！
