### ISSUE TITLE
GAE 部分二级域名缺失

### ISSUE THREAD

**Issue by lumixx** [racaljk/hosts#881]
GAE最近改版，用GAE自己代理过去都不能设置了

尝试了一下hosts，发现还是不行，proxy switchyomega提示有 *.goole.com的资源未加载，查看了一下网页源代码，对比hosts发现有部分缺失

cloudusersettings-pa.clients6.google.com
cloudpersonalization-pa.clients6.google.com
bigtableadmin.clients6.google.com
googleapis.sandbox.google.com
datahub.clients6.google.com
storage.cloud.google.com
logging.clients6.google.com
appengine.clients6.google.com
dataflow.clients6.google.com
clouddebugger.clients6.google.com
memcache.clients6.google.com
cloudsupport.clients6.google.com
ml.clients6.google.com

另外有个 {apiName}.clients6.google.com  ，但是目前没遇到相关问题...

**Comment by lrinQVQ** [comment]
貌似得确需要的域名 马上弄下

**Comment by lumixx** [comment]
还有一个缺
gaming.youtube.com


另外，如果没有特殊用途
建议去除
analytics.google.com
analytics.pinterest.com
analytics.twitter.com
sp.analytics.yahoo.com

**Comment by Pictor** [comment]
这个也是缺失的域名：
`explorer.apis.google.com`

**Comment by Pictor** [comment]
我刚才发的一个 issue 也建议去除 sp.analytics.yahoo.com，因为此域名是可以正常访问的。

不过 analytics.google.com、analytics.pinterest.com、analytics.twitter.com 不应该删除，这些是网站向用户提供的统计功能的管理平台，不是用来采集访客信息的域名。例如著名的 Google Analytics 的管理面板就是通过 analytics.google.com 访问的，而用于采集信息的域名 www.google-analytics.com 在国内是可以顺畅访问的，hosts 中也没有这一条目。所以我想 @lumixx 是你理解错了。

**Comment by DDoSolitary** [comment]
Fixed 5341e7da35077bdf8d487cd1d35ffe3778292070

**Comment by DDoSolitary** [comment]
@peridot `explorer.apis.google.com`已添加
a2dc8cc8592c4a21da5c2fe5876e3be1fbff50e7
