### ISSUE TITLE
hosts 无法修改

### ISSUE THREAD

**Issue by leekunhwee** [racaljk/hosts#883]
LICENSE:General Public License
    **********************************************
    *                                            *
    *                                            *
    *                                            *
    *     Welcome to use racaljk/hosts tool!     *
    *                                            *
    *                                            *
    *                    Powered by: @Too-Naive  *
    **********************************************
    Copyright (C) 2016 @Too-Naive
    Project website:https://github.com/HostsTools/Windows
    Bug report:[hidden]
               Or open new issue

    Start replace hosts file:
    Step1:Download hosts file...
    There seems something wrong in download file, we will retry after 5 seconds.
        Download hosts file...
    There seems something wrong in download file, we will retry after 5 seconds.
        Download hosts file...  Done.
    Step2:Change Line Endings...        Done.
    Step3:Replace Default Hosts File...
Fatal Error:
CopyFile() Error on copy hosts file to system path (GetLastError():2)
Please contact the application's support team for more information.

[Debug Message]
C:\WINDOWS\system32\drivers\etc\hosts
C:\WINDOWS\system32\drivers\etc\hosts.20170102.103659.bak
C:\WINDOWS\system32

This application has requested the Runtime to terminate it in an unusual way.
Please contact the application's support team for more information.
Please check anti-virus software then open this program again.
Please check anti-virus software then open this program again.
Please check anti-virus software then open this program again.

已经关闭了杀毒软件，不知道为什么会出现这种状况。。
而且hosts中几乎所有IP前面都出现了“#”号

**Comment by Ir1d** [comment]
几乎所有ip都出现井号我也遇到过 （xp）

**Comment by leekunhwee** [comment]
@Ir1d 你后来解决了么？

**Comment by leekunhwee** [comment]
后来发现是因为杀毒软件误删了文件导致，恢复后，IP前的“#”号消失，可以继续上网，但是运行tools.exe时仍然出现上述问题。是否可以通过tools.exe的卸载后重装？该如何操作？

**Comment by Too-Naive** [comment]
最近忙于期末作业。。等我回大陆之后再着手解决这个问题吧

**Comment by Ir1d** [comment]
@leekunhwee 并没有。。。不过似乎的确是和杀毒软件有关

**Comment by neverlous** [comment]
C:\WINDOWS\system32\drivers\etc\hosts  拷贝出来编辑好后再复制进去覆盖。有提示就确定。有安全软件提示，信任放过就行。

**Comment by imknown** [comment]
`大数字` 就有 `一键SharpKey` 的功能 (逃
