### ISSUE TITLE
Google Photos访问奇慢

### ISSUE THREAD

**Issue by cyp0633** [racaljk/hosts#884]
山东联通百兆
一个2.2M的GIF需要加载2-3分钟
Google搜索页面加载不慢

**Comment by lrinQVQ** [comment]
重庆联通秒开= =

**Comment by laodcn** [comment]
南方电信上传跟查看都没问题

**Comment by imknown** [comment]
地域差异, 慢很正常...

**Comment by Too-Naive** [comment]
如果觉得慢还是挂ss比较好....地域差异除非全面解禁不然就要选最优节点
另:百兆是国内网百兆 国际出口也就那么点

**Comment by EricInBj** [comment]
@lrinQVQ  用这份 hosts 你能看 Google Photos 里的视频吗？

**Comment by lrinQVQ** [comment]
能orz
