### ISSUE TITLE
需要用Line的朋友看这里

### ISSUE THREAD

**Issue by bobbyliujb** [racaljk/hosts#886]
添加以下字段即可
#Line
203.104.153.1	gd2.line.naver.jp
203.104.153.129	gd2.line.naver.jp
203.104.150.2	gd2.line.naver.jp
125.209.222.202	gd2w.line.naver.jp
125.209.222.59	gd2w.line.naver.jp
203.104.150.2	gw.line.naver.jp
203.104.153.1	gw.line.naver.jp
203.104.153.129	gw.line.naver.jp
125.209.222.59	gww.line.naver.jp
125.209.222.202	gww.line.naver.jp
125.209.222.59	gwx.line.naver.jp
125.209.252.41	gwx.line.naver.jp
125.209.252.42	gwx.line.naver.jp
125.209.252.43	gwx.line.naver.jp
125.209.252.44	gwx.line.naver.jp
203.104.150.3	gwx.line.naver.jp
203.104.153.130	gwx.line.naver.jp
203.104.153.2	gwx.line.naver.jp
203.104.160.31	gwx.line.naver.jp
203.104.160.32	gwx.line.naver.jp
203.104.174.14	gwx.line.naver.jp
203.104.174.15	gwx.line.naver.jp
203.104.174.16	gwx.line.naver.jp
203.104.174.17	gwx.line.naver.jp
203.104.174.18	gwx.line.naver.jp
203.104.142.52	lan.line.me
23.32.5.48	lan.line.me
125.209.210.239	lcp-checkout.line.me
203.104.138.138	line.me
125.209.238.181	obs.line-apps.com
125.209.238.209	obs.line-apps.com
125.209.238.181	obs-cn.line-apps.com
125.209.238.209	obs-cn.line-apps.com
203.104.153.135	obs-tw.line-apps.com
203.104.150.4	obs-tw.line-apps.com
203.104.153.7	obs-tw.line-apps.com
23.32.5.48	scdn.line-apps.com
23.219.132.153	scdn.line-apps.com
23.2.27.60	scdn.line-apps.com
104.121.240.61	scdn.line-apps.com
23.205.217.59	scdn.line-apps.com
23.205.217.59	scdn.line-apps.com
104.70.135.244	scdn.line-apps.com
23.57.196.158	scdn.line-apps.com
23.57.244.158	scdn.line-apps.com
69.192.179.250	scdn.line-apps.com
104.98.19.185	scdn.line-apps.com
104.98.19.185	scdn.line-apps.com
23.63.22.24	scdn.line-apps.com
104.74.169.189	w.line.me
23.0.130.177	w.line.me
125.209.238.186	xcdn-cn-prf.line-apps.com
125.209.238.186	xcdn-cn-shp.line-apps.com
125.209.238.186	xcdn-cn-stk.line-apps.com
125.209.222.202	gd2w.line.naver.jp
23.215.103.24	dl.profile.line.naver.jp
23.215.103.40	dl.stickershop.line.naver.jp
203.104.153.129	gd2.line.naver.jp
125.209.252.17	gd2g.line.naver.jp
125.209.252.18	gd2i.line.naver.jp
125.209.222.59	gd2k.line.naver.jp
125.209.222.202	gd2w.line.naver.jp
203.104.174.12	gd2s.line.naver.jp
203.104.160.11	gd2u.line.naver.jp
203.104.174.13	gd2v.line.naver.jp
125.209.238.209	obs-cn.line-apps.com
125.209.238.186	xcdn-cn-stk.line-apps.com
125.209.248.6	xcdn-cn-prf.line-apps.com

**Comment by SakuraSa233** [comment]
万分感谢！！

**Comment by lrinQVQ** [comment]
@bobbyliujb 您可以直接提交pull requests

**Comment by njxxdx** [comment]
tks

**Comment by Too-Naive** [comment]
![](https://cloud.githubusercontent.com/assets/16496671/20557321/f47b3c50-b1a5-11e6-8810-8edc50a65778.png)

**Comment by zxzxvic** [comment]
希望可以添加进去

**Comment by sqc1999** [comment]
这个没问题吧，我开个PR？
@lrinQVQ

**Comment by imknown** [comment]
说好的 `Google Hosts` 哪 (被打肿的认真脸)

**Comment by lrinQVQ** [comment]
@sqc1999 干脆开吧2333

**Comment by sqc1999** [comment]
那我开咯，到时候别说我，去说这个人吧 => @lrinQVQ

**Comment by lrinQVQ** [comment]
@sqc1999 好好好2333

**Comment by zxzxvic** [comment]
line的这些我这里不能用啊。ip好像不行

**Comment by lrinQVQ** [comment]
哪里0.0

**Comment by sqc1999** [comment]
我没有line账号，没法测试。。

**Comment by lrinQVQ** [comment]
我这能用2333

**Comment by zxzxvic** [comment]
福建联通的无法ping部分ip

**Comment by imknown** [comment]
同上, `203.104.153.1` 联通 `ping` 不同, 用了一下多个 `VPN`, 也是 不行..

**Comment by EMLVIRUS** [comment]
移动ping不通+1
![image](https://cloud.githubusercontent.com/assets/16912240/22860249/31950234-f133-11e6-8073-b7b470fefdf8.png)

**Comment by sqc1999** [comment]
刚刚仔细看了一下才发现，这些条目实在是乱得可以，不光有单个域名加了多个IP，甚至还有不少完全是重复的，再加上有不少人报告失效
真的要支持line的话还是重新找IP整理吧。。
谁来reopen一下？ @lrinQVQ ？

**Comment by lrinQVQ** [comment]
@sqc1999 ok

**Comment by lrinQVQ** [comment]
@sqc1999 我去找找IP

**Comment by lrinQVQ** [comment]
69.192.179.250	scdn.line-apps.com 日本的全国延迟都比较低
http://ping.chinaz.com/69.192.179.250
其他还在看
--------------------------------------------------------------------------------------------

**Comment by sqc1999** [comment]
:smirk:

**Comment by lrinQVQ** [comment]
2333没网了明天弄

**Comment by bobbyliujb** [comment]
sorry各位，这个也是我从那个湾湾的博客以及贴吧搜集来的，不像racaljk大大这样定期维护哇（向大佬低头）
其实一直好奇，racaljk大大是怎么把IP和域名抠出来的？？收集可用hosts是怎么收集的？？？

**Comment by Ir1d** [comment]
#685
