### ISSUE TITLE
tumblr 视频卡,很难播放

### ISSUE THREAD

**Issue by Mao-jiawei** [racaljk/hosts#887]
tumblr 视频卡,很难播放

**Comment by letu81** [comment]
二级域名无法访问，ooxxx.tumblr.com 怎么破？

**Comment by lrinQVQ** [comment]
啧

**Comment by lrinQVQ** [comment]
二级域名问题存在= =

**Comment by lrinQVQ** [comment]
播放卡可能是vt.media.tumblr.com的问题

**Comment by lrinQVQ** [comment]
@Mao-jiawei 能否看下这样会不会好些
87.248.116.14	vt.media.tumblr.com

**Comment by lrinQVQ** [comment]
二级域名发现static.tumblr.com貌似存在问题- -

**Comment by lrinQVQ** [comment]
@Mao-jiawei 视频播放问题已解决

**Comment by Mao-jiawei** [comment]
@lrinQVQ  谢谢问题解决了   这个ip是怎么找到的呢

**Comment by lrinQVQ** [comment]
@Mao-jiawei 可以利用全球ping 一个一个测试 也可以查这个域名所有Ipi

**Comment by Mao-jiawei** [comment]
@lrinQVQ   能加下qq吗  详细请教一下

**Comment by Ir1d** [comment]
@lrinQVQ 好像有个经验分享帖 你可以写进去

**Comment by lrinQVQ** [comment]
orz在哪里

**Comment by Mao-jiawei** [comment]
@lrinQVQ   vt.media.tumblr.com 这个域名是哪里找到的  还有全球ping 是什么

**Comment by lrinQVQ** [comment]
@Mao-jiawei Chrome F12 调试模式Network
全球ping就是利用全球服务器ping这个域名得出ip

**Comment by Mao-jiawei** [comment]
@lrinQVQ 非常感谢

**Comment by lrinQVQ** [comment]
小意思啦～

**Comment by Mao-jiawei** [comment]
@lrinQVQ  还想请教下   如果禁ping了 怎么找到呢   比如tumblr.com  全球ping  都是超时的

**Comment by lrinQVQ** [comment]
@Mao-jiawei 带入hosts测试喽

**Comment by Ir1d** [comment]
@imknown 经验帖哪去了……

**Comment by lrinQVQ** [comment]
2333不知道

**Comment by jiangtiandao** [comment]
tcping
@Mao-jiawei

**Comment by Mao-jiawei** [comment]
@jiangtiandao 大神 全球ping 有没有好点的工具推荐

**Comment by jiangtiandao** [comment]
@Mao-jiawei  
ping.chinaz.com

**Comment by Mao-jiawei** [comment]
@jiangtiandao @lrinQVQ  我发现ping延迟不高的ip  但是视频加载很慢

**Comment by lrinQVQ** [comment]
@Mao-jiawei 这个orz跟自己的宽带或者网络情况也有关系

**Comment by Mao-jiawei** [comment]
@lrinQVQ  
vtt.tumblr.com  vt.media.tumblr.com  测试了一天 想找更优的ip 最后结果还是hosts里的ip是最优的，有没有更加高效一点的办法呢。

**Comment by lrinQVQ** [comment]
@Mao-jiawei…全球不同国家地区ping出来的结果最高效
