### ISSUE TITLE
material.google.com

### ISSUE THREAD

**Issue by Jack-Works** [racaljk/hosts#890]
希望可以加入此域名的 hosts 谢谢

**Comment by lrinQVQ** [comment]
https://github.com/racaljk/hosts/blob/master/hosts#L603

**Comment by Jack-Works** [comment]
@lrinQVQ 抱歉= = 打错域名了，material.io，这个也被 Google 在用，但是我搜了一下，并没有

**Comment by lrinQVQ** [comment]
@Jack-Works OK ==

**Comment by lrinQVQ** [comment]
@Jack-Works 欢迎再来反馈咩~已经提交啦
