### ISSUE TITLE
Googleplay无法下载

### ISSUE THREAD

**Issue by SakuraSa233** [racaljk/hosts#893]
在隔壁的Gohost都可以下载的来着，搞个host还要到处合并好麻烦的样子…顺便添加一下LINE的host好吗？

**Comment by lrinQVQ** [comment]
LINE我这一切正常欸…Google Play的话尽量不使用反代

https://github.com/racaljk/hosts/pull/889

**Comment by SakuraSa233** [comment]
使用反向代理有什么不好的方面吗？因为LINE直连不能正常收发图片…

**Comment by lrinQVQ** [comment]
@SakuraSa233 https://zh.wikipedia.org/wiki/%E4%BB%A3%E7%90%86%E6%9C%8D%E5%8A%A1%E5%99%A8#.E5.AF.B9.E7.BD.91.E7.BB.9C.E5.AE.89.E5.85.A8.E7.9A.84.E7.A0.B4.E5.9D.8F 看下这条2333

**Comment by lrinQVQ** [comment]
LINE西北西南电信联通一切正常欸...是因为dns转发+chinadns的原因嘛..

**Comment by aofall** [comment]
那就去用隔壁的吧

**Comment by heham** [comment]
play应用都打不开登录，网页版play可以但是没什么卵用，同求

**Comment by Too-Naive** [comment]
老老实实用代理嘛 也没什么不好 现在代理便宜如白菜![](https://cloud.githubusercontent.com/assets/16496671/20557321/f47b3c50-b1a5-11e6-8810-8edc50a65778.png)

**Comment by sqc1999** [comment]
@Too-Naive 便宜是便宜，然而我并无办法付款:sweary:

**Comment by jiangtiandao** [comment]
try [XX-net](https://github.com/XX-net/XX-Net) @sqc1999

**Comment by sqc1999** [comment]
@jiangtiandao 现在网上随便找找ss服务器凑合着用，想当年我可是开Linode搭建ptproxy+obfs4的。。

**Comment by Too-Naive** [comment]
@sqc1999 如果真的有需要 可以找我![](https://cloud.githubusercontent.com/assets/16496671/20557321/f47b3c50-b1a5-11e6-8810-8edc50a65778.png)

**Comment by lrinQVQ** [comment]
楼上+1

**Comment by sqc1999** [comment]
@Too-Naive 暂时不用，现在看来网上分享的ss服务器有不少的
