### ISSUE TITLE
添加Tor和赛风官网？

### ISSUE THREAD

**Issue by sqc1999** [racaljk/hosts#896]
加这个应该没什么问题吧。
没问题的话我就开PR了。

**Comment by Too-Naive** [comment]
好久没碰项目都不知道会有啥问题了(

**Comment by lrinQVQ** [comment]
干脆加上好了2333 做个China Hosts2333

**Comment by sqc1999** [comment]
`torproject.org`为什么会有一大坨乱七八糟的二级域名。。
