### ISSUE TITLE
github下载文件没速度

### ISSUE THREAD

**Issue by redapple0204** [racaljk/hosts#899]

**Comment by aofall** [comment]
日常炸系列 目前没有找到更好的 解决方案(毕竟再怎么找都是美西

**Comment by imknown** [comment]
很正常, 建议花钱买时间 你懂的.

**Comment by lrinQVQ** [comment]
Github的下载服务器
我记得code里面的文件下载 raw.githubusercontent.com(和CDN一个ip段)
还有就是releases里面的下载 为亚马逊的服务器(不解释亚马逊服务器在天朝的速度了吧…)
So 无解…

**Comment by dhqdqk** [comment]
github下载的话，我的经验是后半夜到早上下载速度挺好。

**Comment by redapple0204** [comment]
@dhqdqk me too
