### ISSUE TITLE
现在googleplay市场软件无法下载

### ISSUE THREAD

**Issue by kgdyinpv** [racaljk/hosts#90]
现在googleplay市场软件无法下载，找到了图片缩略图ip但是依然无法下载。不知道下载服务器是哪个！！！
![screenshot_2015-11-15-14-47-10](https://cloud.githubusercontent.com/assets/7057811/11167660/e9da9f18-8ba7-11e5-9352-a0c529077f6d.png)

**Comment by andytimes** [comment]
Google Play，Youtube这类资源使用的是静态 IP ，下载请挂代理。

2015-11-15 14:48 GMT+08:00 kgdyinpv <notifications@github.com>:

**Comment by aofall** [comment]
@andytimes 在挂代理的同时还要还原hosts，GooglePlay不支持SNI会导致预览图之类的无法显示

**Comment by andytimes** [comment]
用 SS 不用还原。

2015-11-15 15:18 GMT+08:00 aofall <notifications@github.com>:

**Comment by aofall** [comment]
@andytimes 那是Root之后的才不用。没有Root时SS是转为VPN的

**Comment by kgdyinpv** [comment]
在考虑把
64.233.162.83	clients1.google.com
64.233.162.83	clients2.google.com
64.233.162.83	clients3.google.com
64.233.162.83	clients4.google.com
64.233.162.83	clients5.google.com
64.233.162.83	clients6.google.com
64.233.162.83	clients7.google.com
写入路由器dnsmasq，不知能不能解决软件下载问题

**Comment by aofall** [comment]
@kgdyinpv 不支持SNI的软件写入也没用的
SNI是什么东西？参考↓
https://en.wikipedia.org/wiki/Server_Name_Indication
