### ISSUE TITLE
您好，能否添加个域名

### ISSUE THREAD

**Issue by zhunghwa** [racaljk/hosts#900]
您好，能否添加iobit.com这个域名
国内一直很难访问，谢谢

**Comment by xmdhs** [comment]
访问正常

**Comment by lrinQVQ** [comment]
访问正常+1

**Comment by Too-Naive** [comment]
访问正常..

**Comment by sqc1999** [comment]
哇，为什么你们都访问正常。。
我完全上不去啊，移动电信都不行

**Comment by imknown** [comment]
我打不开, 大连联通.

试一下这个
```
110.232.178.193 iobit.com
110.232.178.193 www.iobit.com
```

**Comment by lrinQVQ** [comment]
现在貌似这个域名已经全国DNS污染了- -

**Comment by zhunghwa** [comment]
thinks

2017-01-15 12:59 GMT+08:00 imknown J. Kimu <notifications@github.com>:

**Comment by EMLVIRUS** [comment]
测试使用国外DNS即可访问

**Comment by weiyichen2011** [comment]
无法访问，安徽电信

**Comment by lrinQVQ** [comment]
仅为DNS污染 没有封IP 换DNS即可解决orz

**Comment by sqc1999** [comment]
应该是DNS污染
我绍兴移动用114解析出来是`46.82.174.68`
查了一下，还是比较高端的污染。。（https://twitter.com/multiple1902/status/396354835311652864）
我前几天解析出来明明还不是这个的说。。

**Comment by sqc1999** [comment]
@lrinQVQ
我换用DNSCrypt.org Franch(使用dnscrypt加密)以后就可以正常访问了，要不我扫一下子域名开PR吧
不过这种没有HTTPS还是用DNS污染来封锁的域名我还是第一次见。。这种情况一般都是关键字过滤+TCP RST重置连接的吧。。

**Comment by lrinQVQ** [comment]
2333是的 我用SS配合DNS转发为TCP DNS 可以扫下子域名开个RP 这个网站不涉及太多敏感的东西

**Comment by sqc1999** [comment]
@lrinQVQ 然而我刚刚发现IObit的产品似乎有很多负面评价，感觉像收费版的360/腾讯/百度全家桶什么的。

**Comment by lrinQVQ** [comment]
@sqc1999 啥！！垃圾360这些的 不加了！

**Comment by Too-Naive** [comment]
![](https://cloud.githubusercontent.com/assets/16496671/20557321/f47b3c50-b1a5-11e6-8810-8edc50a65778.png)

**Comment by sqc1999** [comment]
而且还是家国内公司做的，只是针对国外用户而已。。

**Comment by EMLVIRUS** [comment]
@sqc1999 请先行使用再评价 大部分负面评价没有明确的点或针对旧版软件运行于新系统（无理取闹）

**Comment by lrinQVQ** [comment]
orz 我去看看

**Comment by sqc1999** [comment]
@EMLVIRUS
关于负面评价，我只是指出有而已，我个人认为这些评价不是无理取闹，但我也确实没有验证过它们的真实性。
至于说它像360，只是针对它的软件提供的功能
说对它被墙感到高兴，是因为我非常反感360之类的全家桶

**Comment by sqc1999** [comment]
@EMLVIRUS 确实是国内公司：http://zhengxinde.co/aboutus-events.php

**Comment by lrinQVQ** [comment]
体验一天看看orz 我也反感360这类的

**Comment by sqc1999** [comment]
让我们向伟大的小白鼠致敬🐁

**Comment by lrinQVQ** [comment]
![default](https://cloud.githubusercontent.com/assets/12861134/22152191/943039ec-df5c-11e6-9049-af72e19271ab.png)

![1](https://cloud.githubusercontent.com/assets/12861134/22152242/dc9b6846-df5c-11e6-942d-1438f8767c2d.png)

欸...果然全家桶 体验下free版看看

**Comment by lrinQVQ** [comment]
![4](https://cloud.githubusercontent.com/assets/12861134/22152639/d7fa95e4-df5e-11e6-9bdc-5a248e0faa3c.png)

![5](https://cloud.githubusercontent.com/assets/12861134/22152670/02789366-df5f-11e6-9b2a-8e58c5da6ea2.png)

下载加速需要pro版?  试用加速..自动下载需要pro

**Comment by sqc1999** [comment]
为什么出现了百度云风格。。:flushed:

**Comment by sqc1999** [comment]
不看直播了，先睡了。。

**Comment by EMLVIRUS** [comment]
不用试了 我用了三年了.....

**Comment by lrinQVQ** [comment]
23333我感觉

**Comment by Too-Naive** [comment]
![](https://cloud.githubusercontent.com/assets/16496671/20557321/f47b3c50-b1a5-11e6-8810-8edc50a65778.png)

**Comment by lrinQVQ** [comment]
为什么看到了百度云的感觉+1 2333

**Comment by lrinQVQ** [comment]
@Too-Naive 日常滑稽

**Comment by Too-Naive** [comment]
![](https://cloud.githubusercontent.com/assets/16496671/20557321/f47b3c50-b1a5-11e6-8810-8edc50a65778.png)

**Comment by lrinQVQ** [comment]
@Too-Naive 23333 滑稽日常*2

**Comment by Too-Naive** [comment]
我不知道该说什么 反正![](https://cloud.githubusercontent.com/assets/16496671/20557321/f47b3c50-b1a5-11e6-8810-8edc50a65778.png)就对了

**Comment by lrinQVQ** [comment]
orz 欸多

**Comment by Too-Naive** [comment]
![](https://cloud.githubusercontent.com/assets/16496671/20557321/f47b3c50-b1a5-11e6-8810-8edc50a65778.png)ls这位dalao有没有其他的联系方式啊

**Comment by lrinQVQ** [comment]
欸我是小菜鸡

**Comment by lrinQVQ** [comment]
啧

**Comment by lrinQVQ** [comment]
好像github私信被取消了2333

**Comment by Ir1d** [comment]
劲劲啊 善用搜索引擎哦（这话好耳熟

**Comment by lrinQVQ** [comment]
23333

**Comment by Too-Naive** [comment]
辣鸡啊 没事情查别人做什么

**Comment by lrinQVQ** [comment]
Orz 没必要查我啊2333信息都有的

**Comment by Too-Naive** [comment]
![](https://cloud.githubusercontent.com/assets/16496671/20557321/f47b3c50-b1a5-11e6-8810-8edc50a65778.png)你说什么我听不见

**Comment by lrinQVQ** [comment]
啧2333

**Comment by Too-Naive** [comment]
![](https://cloud.githubusercontent.com/assets/16496671/20557321/f47b3c50-b1a5-11e6-8810-8edc50a65778.png)说了那么多我还是不知道怎么联系..

**Comment by lrinQVQ** [comment]
QQ？微信？还是啥2333

**Comment by Too-Naive** [comment]
´_>`人家就是不知道你邮箱啊

**Comment by lrinQVQ** [comment]
@Too-Naive cqlrin@gmail.com呀

**Comment by lrinQVQ** [comment]
等等我没公开嘛orz

**Comment by Too-Naive** [comment]
没有 快滚
![](https://cloud.githubusercontent.com/assets/16496671/20557321/f47b3c50-b1a5-11e6-8810-8edc50a65778.png)

**Comment by lrinQVQ** [comment]
2333咳咳

**Comment by lrinQVQ** [comment]
失误orz忘了自己并没有公开过

**Comment by aofall** [comment]
这锅得 Edgecast CDN来背
裸域 iobit.com 没有CDN，所以没问题，不过网站设置了 iobit.com 跳转至 www.iobit.com
而 iobit.com 使用了在中国大陆被全线DNS污染的Edgecast CDN所以才打不开（hosts里面大部分记录都是这家CDN的锅）

    110.232.178.193 www.iobit.com

**Comment by andytimes** [comment]
2017-01-27 0:26 GMT+08:00 aofall <notifications@github.com>:

> 这锅得 Edgecast CDN来背
> 裸域 iobit.com 没有CDN，所以没问题，不过网站设置了 iobit.com 跳转至 www.iobit.com
> 而 iobit.com 使用了在中国大陆被全线DNS污染的Edgecast CDN所以才打不开（hosts里面大部分记录都是这家CDN的锅） @andytimes
>
> 110.232.178.193 www.iobit.com

nslookup 查询确实如此，但暂时没必要增加 www.iobit.com 这个域名到 hosts 内,
如有需要，应该自行添加。

Andy
