### ISSUE TITLE
[hosts request] DeviantArt

### ISSUE THREAD

**Issue by EMLVIRUS** [racaljk/hosts#905]
Please add http://www.deviantart.com/
Plus, I use Guangdong Mobile. Error occurs as connection reset.

**Comment by Ir1d** [comment]
大连电信正常（:confused:

**Comment by sqc1999** [comment]
我现在http都打得开，然而我明明记得以前是必须翻墙的啊。。

**Comment by Too-Naive** [comment]
访问正常 秒开

**Comment by lrinQVQ** [comment]
访问正常 秒开 +1

**Comment by lrinQVQ** [comment]
54.230.73.90 www.deviantart.com @EMLVIRUS 
这个域名的IP有点奇怪 同一个IP有些能开 有些不能开 你试试这个IP

**Comment by EMLVIRUS** [comment]
都说中文？ 好吧 中文吧
我的广东移动 主页http会重置 https可以访问
但是无论如何搜索都会挂

**Comment by lrinQVQ** [comment]
@EMLVIRUS 都是国人说英文干啥orz 搜索会挂指的是？

**Comment by EMLVIRUS** [comment]
就是DA主页的搜索 还是无法访问

**Comment by lrinQVQ** [comment]
我去试试

**Comment by lrinQVQ** [comment]
@EMLVIRUS 搜索正常啊

**Comment by lrinQVQ** [comment]
![screenshot_20170119-180552](https://cloud.githubusercontent.com/assets/12861134/22102416/5f0b4468-de72-11e6-8e8a-027fc3d63d78.png)

正常欸

**Comment by Ir1d** [comment]
可以尝试强制https一波？@EMLVIRUS

**Comment by EMLVIRUS** [comment]
确认 必须HTTPS才能访问 但是浏览器好像默认不访问这页面的HTTPS 目测服务器设置问题

**Comment by lrinQVQ** [comment]
@EMLVIRUS Chrome? 我http也没问题的orz

**Comment by EMLVIRUS** [comment]
FF.........我现在用chrome试试

**Comment by EMLVIRUS** [comment]
情况跟FF一样.............

**Comment by lrinQVQ** [comment]
欸

**Comment by sqc1999** [comment]
强制https的话可以设置hsts来解决：[chrome://net-internals/#hsts](chrome://net-internals/#hsts)
