### ISSUE TITLE
[Advice]请求增加github域名覆盖面

### ISSUE THREAD

**Issue by loststar** [racaljk/hosts#910]
只有gist不够啊。。。很多时候登录和首页都抽风。。。

**Comment by lrinQVQ** [comment]
orz 这个

**Comment by lrinQVQ** [comment]
登录界面的话主要是CDN
assets-cdn.github.com 这个问题 我开个issues问问大家有没有一个好的建议

**Comment by imknown** [comment]
https://github.com/racaljk/hosts/search?q=github&type=Issues&utf8=%E2%9C%93

一搜索 发现 还真不少

**Comment by lrinQVQ** [comment]
是啊233挺多的

**Comment by lrinQVQ** [comment]
@racaljk 
@Too-Naive 
@Ir1d 
@imknown 
关于github的issues…要不要再开issues的时候加个说明？

**Comment by Too-Naive** [comment]
加就是了= =
感觉加了也没人看

**Comment by Ir1d** [comment]
@lrinQVQ 可以尝试写到templates 里，尽管效果不是想象的那么好

**Comment by lrinQVQ** [comment]
昂

**Comment by lrinQVQ** [comment]
试试吧2333

**Comment by Too-Naive** [comment]
给个经验贴序号 直接扔readme里面

**Comment by sqc1999** [comment]
@我这种SB干什么。。
没人看+1

**Comment by lrinQVQ** [comment]
@sqc1999 都是贡献者啊…问问你们的意见

**Comment by lrinQVQ** [comment]
请看常见问题解答orz

**Comment by Too-Naive** [comment]
统一回复: see also [FAQ](https://github.com/racaljk/hosts/wiki/The-hosts-FAQ#%E4%B8%BA%E4%BB%80%E4%B9%88-github-%E6%9C%89%E6%97%B6%E6%89%93%E5%BC%80%E7%BC%93%E6%85%A2%E7%94%9A%E8%87%B3%E6%89%93%E4%B8%8D%E5%BC%80)

**Comment by lrinQVQ** [comment]
23333 +1

**Comment by Too-Naive** [comment]
可以用那个 saved reply feature了

**Comment by lrinQVQ** [comment]
好主意！
