### ISSUE TITLE
duckduckgo图片

### ISSUE THREAD

**Issue by EMLVIRUS** [racaljk/hosts#911]
images.duckduckgo.com跟icons.duckduckgo.com的host IP似乎无效
使用当前IP访问无法显示
清空hosts使用DNSCrypt访问正常

**Comment by lrinQVQ** [comment]
DNS污染喽orz

**Comment by EMLVIRUS** [comment]
目前我这里是的 要不你试试？

**Comment by lrinQVQ** [comment]
一会看看2333

**Comment by lrinQVQ** [comment]
好像确实失效了

**Comment by lrinQVQ** [comment]
54.229.110.205 全站通用 @EMLVIRUS

**Comment by EMLVIRUS** [comment]
这个好像可以 不过我怎么好像开不了PR改一下...........

**Comment by lrinQVQ** [comment]
@EMLVIRUS 不会吧啧
