### ISSUE TITLE
论Google没挂吧……

### ISSUE THREAD

**Issue by K-Guan** [racaljk/hosts#92]
http://www.google.com/ 能用，然而 http://www.google.com.hk/ 打不开……（默认的……）

另外translate.google.com也打不开了，并且我的翻译插件和Gmail插件挂了……

**Comment by MarcoQin** [comment]
google全线阵亡= =！幸亏还有vpn顶着。。

**Comment by jy02534655** [comment]
谷歌翻译没挂，其他貌似都挂了，用xx-net上着

**Comment by coolrc136** [comment]
试试这个216.239.38.124
来自www.findspace.name

**Comment by zzseven** [comment]
我也打不开～

**Comment by K-Guan** [comment]
我的天……原来大家都这样……

**Comment by K-Guan** [comment]
@coolrc136 哦？好像还行。

**Comment by xrlin** [comment]
原来我不是一个人......

**Comment by K-Guan** [comment]
@xrlin 嗯，我也想这么说……

**Comment by 782595450** [comment]
国际发生了大事，害的Google都打不开了

**Comment by andytimes** [comment]
不大清楚，显示连接超时，不是连接重置。等到晚上再看，另外124,125都试试看呗，我记得应该能用的。
@K-Guan 这个 https://www.google.com/ncr 能访问是因为 这个用的不是 216的 IP，你自己看 hosts 就明白了

**Comment by K-Guan** [comment]
@andytimes Wow, 刚刚尝试了下全线替换成@coolrc136 给的IP，好像都可用。

**Comment by andytimes** [comment]
@K-Guan 嗯嗯，123-125都是全 Google 服务可访问。

**Comment by K-Guan** [comment]
@andytimes 那就太好了。

**Comment by cdroad** [comment]
谷歌翻译一直没被墙的吧，我没用hosts之前一直能使用的。

**Comment by K-Guan** [comment]
@cdroad http://translate.google.com or http://translate.google.cn

**Comment by K-Guan** [comment]
@andytimes 有没有脚本做替换工作……还是得我自己写？

**Comment by andytimes** [comment]
@cdroad 国内一直有 Google 翻译和地图服务，不过，少部分功能被阉割了。

**Comment by andytimes** [comment]
@K-Guan `sed -i 's/216.239.38.123/216.239.38.125/g' hosts`

我建议不要更新这么频繁，如果晚上还没有修复，再更新。

**Comment by racaljk** [comment]
@cdroad 翻译和地图一直都能用，只是时不时抽一下

**Comment by K-Guan** [comment]
@andytimes 哦，原来就这一个挂了。Hey @racaljk 。

**Comment by K-Guan** [comment]
顺便一提，为什么我们的hosts分割符不一样……有用`\t`分割的，有用空格分割的……

**Comment by racaljk** [comment]
@K-Guan 中午回来吃个饭就看到notification center messages爆表

**Comment by andytimes** [comment]
我的建议是更新这个 IP
sed -i 's/216.239.38.123/64.233.162.82/g' hosts
这个 IP 存在了很长时间了。
关于分隔符，你手动替换一下吧，vim 有列操作的。

**Comment by K-Guan** [comment]
@racaljk 祝贺～

**Comment by K-Guan** [comment]
@andytimes 列操作也不是这么个列操作法……得，我用正则吧。那么是都用空格还是Tab？

**Comment by andytimes** [comment]
@K-Guan 肯定是用 Tab，以前更新一直都是 Tab。
话不多说，我得去吃饭了。更新就交给你啦

**Comment by K-Guan** [comment]
好的～

**Comment by K-Guan** [comment]
[***Finished.***](https://github.com/racaljk/hosts/commit/ac19d7a6de9203a0eebc632241d6e144a41dfbcc)

**Comment by aofall** [comment]
我想吐槽 换个IP需要写脚本吗……
如果你的Linux没装GUI可以理解
但是有GUI的直接拿编辑器Ctrl+H批量替换不就好了。
以及Readme针对Linux用户真不友好，NotePad++我记得是Windows only，为何不让他们用dos2unix

**Comment by NagaseMinato** [comment]
@aofall K-Guan是想同时统一转义符，但正则写得还有点问题..

README中关于linux我之前是想直接wget hosts，但是看到大家用这个也挺high的所以也没改了

**Comment by racaljk** [comment]
用成test小号了..

@aofall K-Guan是想同时统一转义符，但正则写得还有点问题..
README中关于linux我之前是想直接wget hosts，但是看到大家用这个也挺high的所以也没改

**Comment by K-Guan** [comment]
@racalijk *转义符*
