### ISSUE TITLE
twitter的短域名t.co不能解析

### ISSUE THREAD

**Issue by p0mp0k0** [racaljk/hosts#921]
twitter的短域名t.co不能解析
另外，能否加上域名openjailbreak.org

**Comment by andytimes** [comment]
t.co 这个域名无解，只能挂代理，openjailbreak.org 这个域名没法查询到对应 IP

**Comment by lrinQVQ** [comment]
openjailbreak.org 还没有解析= = t.co有点费力

**Comment by Makebignew** [comment]
@lrinQVQ @andytimes 185.45.5.47 t.co
最后一组IP

**Comment by andytimes** [comment]
@Makebignew 确实可以 👍 你可以去开 PRs

**Comment by aofall** [comment]
openjailbreak.org 的持有人把它停止解析了

**Comment by lrinQVQ** [comment]
已修复

**Comment by qa003qa003** [comment]
还是不能访问 t.co 啊~
