### ISSUE TITLE
可以加一行这个，刚刚用手机抓包出来的，解决部分youtube视频

### ISSUE THREAD

**Issue by wsz2074480** [racaljk/hosts#924]
61.91.161.217	r6---sn-aiglln7k.googlevideo.com

**Comment by lrinQVQ** [comment]
待测试orz

**Comment by jiangtiandao** [comment]
@lrinQVQ 
YouTube 原则上不加吧 
https://github.com/racaljk/hosts/wiki/The-hosts-FAQ

**Comment by lrinQVQ** [comment]
@jiangtiandao 如果不是反代的话orz 并且稳定性ok我觉得还是可以加的

**Comment by jiangtiandao** [comment]
youtube ip 早全完了
这是个泰国ip 拥有者 似乎是个泰国的isp  是不是泰国反代→_→
dnsyo解析不出来这个
@lrinQVQ

**Comment by lrinQVQ** [comment]
@jiangtiandao orz 说不定youtube新加了IP 23333我是这么想的2333

**Comment by lrinQVQ** [comment]
好像... manifest.googlevideo.com也是这个IP

**Comment by lrinQVQ** [comment]
等下关于YOUTUBE我发现了一个新世界

**Comment by jiangtiandao** [comment]
这个按照sn编码是伦敦的ip
so 是个sni
https://github.com/lennylxx/ipv6-hosts/wiki/YouTube#4-sn-%E7%BC%96%E7%A0%81%E5%9C%B0%E5%9D%80
@lrinQVQ

**Comment by lrinQVQ** [comment]
@jiangtiandao 嘛= =我发现了一个新世界

**Comment by Makebignew** [comment]
@lrinQVQ  这个原理在于Google通过你访问youtube时的IP确定你的国家和运营商，并根据IP解析到运营商ggc（如果可能），所以只改redirector.googlevideo.com无效，你可以尝试用运营商sni，代理youtube.com,ytimg.com等泛域名，这样可以将你分配到运营商ggc，而这些视频服务器GFW从来不封锁

**Comment by lrinQVQ** [comment]
@Makebignew 并不是运营商ggc 全部测试为谷歌官网IP

**Comment by lrinQVQ** [comment]
我拒绝sni- -

**Comment by WeihuaGu** [comment]
谷歌商店里有个应用叫Go Hosts。这个也是替换hosts,然后youtube可以流畅的观看。

**Comment by Too-Naive** [comment]
![](https://cloud.githubusercontent.com/assets/16496671/20557321/f47b3c50-b1a5-11e6-8810-8edc50a65778.png)

**Comment by mrj1018** [comment]
是不是真的加上了？我现在可以流畅地观看YouTube 1080p 60fps的视频

**Comment by Ir1d** [comment]
@mrj1018 并没有加

统一回复楼上相关 请善用搜索引擎 GitHub自带搜索功能 可以找到相关内容诸如 https://github.com/racaljk/hosts/issues/297#issuecomment-199318299
如果找到的hosts是反代，反代原则上不会添加进来 之前也有过相关讨论
最后感谢大家的分享 在这里开issue之后需要的人看到了就会自取

**Comment by tec1987** [comment]
可以确定的说，这是泰国的GGC，不是SNI。。。

**Comment by Ir1d** [comment]
@tec1987 是的 这个ip是现在项目里使用的Google ip

**Comment by lautis0503** [comment]
这种方法我用过，使用反代是可以的，但是看视频会分配不同的服务器，所以需要添加所有相同格式的*.googlevideo.com，得有上万条。再说这是反代= =

**Comment by lautis0503** [comment]
@WeihuaGu Go Hosts使用的是本项目以及sy618的源，使用本方法添加了上千行googlevideo.com的hosts，使用的是反代
