### ISSUE TITLE
关于Youtube视频播放,求测试

### ISSUE THREAD

**Issue by lrinQVQ** [racaljk/hosts#925]
61.91.161.217	redirector.googlevideo.com
貌似这个域名为一个重定向域名 功能未知
突然发现Youtube视频播放貌似依赖于此域名 加入后一切正常
虽然还不确定原理但是确实如此
本人青海电信 DNS转发+ChinaDNS 部分正常部分无法播放 求更多人测试orz

**Comment by lrinQVQ** [comment]
@jiangtiandao

**Comment by lrinQVQ** [comment]
![2017-01-24 19-38-44](https://cloud.githubusercontent.com/assets/12861134/22245795/c7a60294-e26c-11e6-9d07-deacb8e302e7.png)
确实如此= =

**Comment by lrinQVQ** [comment]
稳定性不算太好的样子 继续测试ing

**Comment by sqc1999** [comment]
我加了这个还是放不出欸。。

**Comment by lrinQVQ** [comment]
@sqc1999 还是不行的嘛0.0

**Comment by lrinQVQ** [comment]
@sqc1999 https://www.youtube.com/watch?v=itz9pwhalYI

**Comment by sqc1999** [comment]
放不出，xxx.googlevideo.com全部ERR_CONNECTION_CLOSED

**Comment by sqc1999** [comment]
你是不是忘记关什么翻墙软件了。。。

**Comment by jiangtiandao** [comment]
@lrinQVQ 
你加的这个不对 人家原来给的是
r6---sn-aiglln7k.googlevideo.com

←_←
看看这个[youtube规则](https://github.com/lennylxx/ipv6-hosts/wiki/YouTube#4-sn-%E7%BC%96%E7%A0%81%E5%9C%B0%E5%9D%80) 基本确认是反代了

**Comment by lrinQVQ** [comment]
@jiangtiandao 不是那个= =

**Comment by lrinQVQ** [comment]
@sqc1999 应该没有

**Comment by lrinQVQ** [comment]
@sqc1999 ss关掉了 只有ChinaDNS和DNS转发

**Comment by sqc1999** [comment]
@lrinQVQ 我DNS还是用114的，我切到DNSCrypt试试

**Comment by lrinQVQ** [comment]
@sqc1999 好

**Comment by lrinQVQ** [comment]
![2017-01-24 20-05-23](https://cloud.githubusercontent.com/assets/12861134/22246587/791df0c4-e270-11e6-9d2c-4eb0e8f45aa8.png)

![2017-01-24 20-06-31](https://cloud.githubusercontent.com/assets/12861134/22246632/9fd1f4fe-e270-11e6-935e-57515c5ef4bb.png)

自家路由状态= = 貌似不少都可以放 有一些不行

**Comment by sqc1999** [comment]
还是不行，现在是连接超时了。。

**Comment by lrinQVQ** [comment]
@sqc1999 欸多 这样嘛

**Comment by lrinQVQ** [comment]
![2017-01-24 20-12-10](https://cloud.githubusercontent.com/assets/12861134/22246794/75f37760-e271-11e6-8552-16954bd3bfdf.png)

挺多都OK的
青海电信

**Comment by sqc1999** [comment]
听说移动自带墙。。

**Comment by lrinQVQ** [comment]
@sqc1999 欸多 心疼orz 移动可以不可以还不知道 我是电信欸

**Comment by lrinQVQ** [comment]
绝大多数视频播放正常orz

**Comment by lrinQVQ** [comment]
貌似是一个重定向域名 具体未知

**Comment by lrinQVQ** [comment]
@sqc1999 你看看你的redirector.googlevideo.com 是不是正常的0.0
我测试了挺多视频了
![2017-01-24 20-22-20](https://cloud.githubusercontent.com/assets/12861134/22247070/e25c76e4-e272-11e6-97d8-4a6ad1e65aa5.png)

**Comment by sqc1999** [comment]
redirector是正常的

**Comment by lrinQVQ** [comment]
欸 那就奇怪了 移动的问题吗...

**Comment by lrinQVQ** [comment]
r1---sn-npoeen7d.googlevideo.com	209.85.229.151 @sqc1999

**Comment by aofall** [comment]
redirector.googlevideo.com 是YouTube SN domains的第一步，先获取到你的IP然后把你重定向到 *.googlevideo.com 的视频地址
你可以播放部分视频是因为ChinaDNS的功劳，解决了DNS污染的问题，然后又被分配到了IP没被封锁的SN domain上，部分视频不能播放是因为IP封锁，而且不同地区分配到的SN domain不一定相同，有些地区可能分配到的是全封锁的段上，作用不大。

**Comment by lrinQVQ** [comment]
@aofall soga 感谢 那这样我就可以找到没有被封锁并且官网的ip

**Comment by lrinQVQ** [comment]
暂时关闭 寻找一下官网IP

**Comment by aofall** [comment]
不用费那个时间找，上xx-net看一下就有一堆了

**Comment by aofall** [comment]
还有一点就是 你找出来的应该是基本都是gvs IP，不能用于hosts

**Comment by lrinQVQ** [comment]
@aofall 可以用的Orz

**Comment by lrinQVQ** [comment]
@aofall 没问题可用

**Comment by CNMan** [comment]
![2017-01-24_221704](https://cloud.githubusercontent.com/assets/8692234/22250764/17b91fd0-e283-11e6-905c-aba192bd8cfe.png)

**Comment by aofall** [comment]
清空DNS缓存 或者 等24小时 或者 重启电脑路由 你就知道这是China DNS的功劳了
gvs的段里面很少有gws IP，费力不讨好

**Comment by aofall** [comment]
@CNMan 泰国ggc

**Comment by lrinQVQ** [comment]
@aofall = =这点基础知识我还是有的 关掉ChinaDNS 并且清空DNS缓存后 马上无法播放 我get 了所有无法播放的域名 打开ChinaDNS 接着清空DNS缓存 获取ip ok

**Comment by jiangtiandao** [comment]
按照sn是英国的ggc  是不是sni？
gvs 是啥 半天搜不到意思
@aofall

**Comment by lrinQVQ** [comment]
@aofall PS:推荐看看ChinaDNS和DNS转发原理

**Comment by aofall** [comment]
？？ʕ•̀ω•́ʔ？？ 如果我现在还要去看这个东西的话我就白在这边混了

**Comment by lrinQVQ** [comment]
@aofall 好吧23333 不过对于YouTube我想试试233

**Comment by jiangtiandao** [comment]
我现在是用Acylic DNS 本地搭一个dns
支持通配符  youtube用的别人给的一个的sni

ggc的ip 而且是有规律的 whois查询应该是google的吧
这个61.   whois是个泰国isp 总觉得是sni proxy
@lrinQVQ

**Comment by lrinQVQ** [comment]
@jiangtiandao +1 目测反代

**Comment by aofall** [comment]
(我怎么感觉你理解错我的意思了)
我指的 不能用于hosts 的意思是不能用于Google Web service，就是搜索之类的服务…(搜索可以，但是其他服务会出现403或者500错误)

**Comment by lrinQVQ** [comment]
![default](https://cloud.githubusercontent.com/assets/12861134/22252015/c4be24ec-e287-11e6-9a80-94f11267cc0d.png)

http://tool.chinaz.com/ipwhois?q=173.194.22.204
可以正常使用 @aofall 说不定有希望哦

**Comment by lrinQVQ** [comment]
@aofall 你该@一下那位骚年2333

**Comment by lrinQVQ** [comment]
@racaljk 
@Too-Naive 
@sqc1999 
@Ir1d 
@andytimes 
@aofall 你们觉得可以新建一个branch 用来尝试解决Youtube视频服务器的内容如何0.0

**Comment by aofall** [comment]
ggc不一定要有规律，你只需要有一个 0/24 段的IP的所有权就可以去申请
举个例子：香港移动的ggc 182.239.95.76 (r1.cmhk-hkg1.gvt1.com)
182.239.95.0/24 这个段既有Akamai CDN，也有sniproxy(现在关闭了好像)
你只需要保证你有这个 0/24 IP段的所有权和 提交你的公司的材料，Google审核通过后你想全部都做成ggc也行，只做一个IP为ggc也行，没有严格的限制

**Comment by racaljk** [comment]
一般情况下是：长期无人维护，卒

**Comment by lrinQVQ** [comment]
@aofall 我觉得2333 还是以官网的为准

**Comment by aofall** [comment]
你的建议 很早之前就讨论过了 自己去搜索
还有就是参考 #297 
如果你有长期的决心去做，那就做吧

**Comment by lrinQVQ** [comment]
@racaljk @aofall 啧 好 我试试2333 //悲伤的故事貌似发生过233

**Comment by sqc1999** [comment]
又被无辜地@了😳
我正沉浸在今天怎么只写了这么一点代码的自责和今天怎么这么快就过完了的不爽中。。

**Comment by lrinQVQ** [comment]
@sqc1999  orz 心疼 嘛因为脸熟所以想@看看你们的意见喽2333

**Comment by sqc1999** [comment]
我讨厌多线程调试
![image](http://wx1.sinaimg.cn/large/005L6vvQly1fbx5421nbag308v06ckjl.gif)

**Comment by lrinQVQ** [comment]
@sqc1999 23333 心疼max

**Comment by aofall** [comment]
能用gws 当然用gws
可现实情况是 官方IP的gws IP 被封完了或者很容易中断
算了我不想解释了你去看历史issue吧，我都有详细的解释过。搜索是个好东西希望你善用他
总之就是 能完整流畅的看视频，很难，只能解决部分，而且IP一封只能用sniproxy了，而我是反对在这种人多的项目里用sniproxy的

**Comment by sqc1999** [comment]
反对+1

**Comment by lrinQVQ** [comment]
反对+2

**Comment by lrinQVQ** [comment]
所以我说我要单独开一个branch 在不使用sni的情况下尝试解决视频播放233

**Comment by lrinQVQ** [comment]
看了看IPV6的hosts
貌似好几万2333 我先开始部分解决 看看会不会大部分都无法使用 这样的话就没啥必要开一个新的branch了

**Comment by aofall** [comment]
稍微修改这个[脚本](https://github.com/lennylxx/ipv6-hosts/blob/master/update_hosts.py)和参考[这个](https://github.com/lennylxx/ipv6-hosts/blob/master/snippets/08_googlevideo.txt)很快就能完成相关工作

**Comment by lrinQVQ** [comment]
好嘞 感谢@aofall

**Comment by lrinQVQ** [comment]
173.194.22.204	r6---sn-npoe7n7z.googlevideo.com
209.85.229.154	r4---sn-npoe7n7s.googlevideo.com
换系统之前记录一下orz

**Comment by sqc1999** [comment]
@aofall 刚刚才发现你居然不是collaborator欸。。

**Comment by lrinQVQ** [comment]
貌似他没被加入orz

**Comment by CNMan** [comment]
我去年在vps上扫了几个月IP，累积下来：
```
google.com gws 证书的有46088个
*.googlevideo.com gvs 证书的有106391个
*.google.com gws 证书的只有4651个
```
国内能用的*.google.com gws就更少了

**Comment by lrinQVQ** [comment]
@CNMan Thanks 我改下脚本233

**Comment by lrinQVQ** [comment]
反正服务器还有一年233

**Comment by aofall** [comment]
类似 #298 总之你搜索就对了

**Comment by Too-Naive** [comment]
![](https://cloud.githubusercontent.com/assets/16496671/20557321/f47b3c50-b1a5-11e6-8810-8edc50a65778.png)

**Comment by sqc1999** [comment]
谁来告诉我带预读取、随机访问、硬盘缓存的HTTP下载器怎么写。。:scream:

**Comment by Too-Naive** [comment]
或许你需要迅雷的源代码

**Comment by sqc1999** [comment]
@Too-Naive 关键是随机访问和预读取，支持类似作为文件系统驱动的操作

**Comment by Too-Naive** [comment]
![](https://cloud.githubusercontent.com/assets/16496671/20557321/f47b3c50-b1a5-11e6-8810-8edc50a65778.png)我能怎么办啊 我只是个滑稽啊

**Comment by aofall** [comment]
@jiangtiandao  如何区分这些IP刚好今天写了文章 ，你可以参考一下 https://blog.aofall.com/archives/7.html

**Comment by lrinQVQ** [comment]
= =跑了5/10 可用 2/10

**Comment by aofall** [comment]
所以说不用做这些无意义的事情

**Comment by lrinQVQ** [comment]
不怂23333

**Comment by lrinQVQ** [comment]
我多跑几次233

**Comment by Ir1d** [comment]
#110 真是害怕 高清重制

**Comment by lrinQVQ** [comment]
2333 可以

**Comment by Too-Naive** [comment]
![](https://cloud.githubusercontent.com/assets/16496671/20557321/f47b3c50-b1a5-11e6-8810-8edc50a65778.png)
