### ISSUE TITLE
duckduckgo 部分 IP 失效

### ISSUE THREAD

**Issue by EMLVIRUS** [racaljk/hosts#927]
![image](https://cloud.githubusercontent.com/assets/16912240/22248961/f64f88ae-e27b-11e6-845f-7af7a9609925.png)
之前找到的IP 还行
![image](https://cloud.githubusercontent.com/assets/16912240/22248983/1324f3ec-e27c-11e6-9887-233d3b8d9928.png)

**Comment by lrinQVQ** [comment]
= =失效嘛

**Comment by lrinQVQ** [comment]
貌似..

**Comment by sffxzzp** [comment]
50.18.192.250我也提供一个

**Comment by EMLVIRUS** [comment]
你们要相信我啊 有ping为证

**Comment by lrinQVQ** [comment]
52.50.207.201 我找到了这个2333

**Comment by lrinQVQ** [comment]
@EMLVIRUS 知道2333 解决了

**Comment by lrinQVQ** [comment]
@sffxzzp 你的速度快些 你提交RP么233 还是我直接改了

**Comment by sffxzzp** [comment]
@lrinQVQ 不是PR么？你直接改吧。懒得clone了再改。

**Comment by lrinQVQ** [comment]
@sffxzzp 行

**Comment by lrinQVQ** [comment]
解决了
