### ISSUE TITLE
基于此项目的防污染、广告过滤、分流解析本地DNS

### ISSUE THREAD

**Issue by CNMan** [racaljk/hosts#930]
项目地址：https://github.com/CNMan/unbound.conf

基于：
https://github.com/NLnetLabs/unbound
https://github.com/jedisct1/dnscrypt-proxy
https://github.com/felixonmars/dnsmasq-china-list
https://github.com/racaljk/hosts
https://github.com/missdeer/blocklist

除hosts域名(`localdns\unbound\unbound.local-zone.hosts.conf`)本地解析外，国内域名(`localdns\unbound\unbound.forward-zone.China.conf`)由114和阿里DNS（可替换为当地运营商DNS）解析，其他域名由DNSCrypt OpenDNS解析。

为方便使用，搞了个适用于Windows的傻瓜包:

* 若有其他占用53、8953和9999端口的软件，请停用。

* 下载[localdns_32bit.zip](https://dl.cnlic.com/localdns_32bit.zip)或[localdns_64bit.zip](https://dl.cnlic.com/localdns_64bit.zip)，必须解压`localdns`目录到`C`盘根目录，运行`localdns.cmd`，在网络设置里面把DNS服务器设置成127.0.0.1即可。

* `localdns.cmd`放到`C:\ProgramData\Microsoft\Windows\Start Menu\Programs\StartUp\`(Vista+)或`C:\Documents and Settings\All Users\Start Menu\Programs\Startup`(XP-)可开机就启动。

* 运行`localdns-update.cmd`更新配置，一日三更(项目北京时间每天5:09、13:09、21:09与上游同步)

Linux用户可参考[树莓派安装unbound和dnscrypt-proxy全记录](https://github.com/CNMan/unbound.conf/issues/13)进行配置，大同小异。

可对局域网或公网服务

**Comment by Too-Naive** [comment]
这是啥

**Comment by sqc1999** [comment]
看似是个unbound的配置文件？

**Comment by lrinQVQ** [comment]
貌似= =就是一个基于unbound和dnscrypt的本地DNS

**Comment by sqc1999** [comment]
其实我本来一直想装个unbound玩一玩，然而一直没空。。

**Comment by CNMan** [comment]
@Too-Naive @sqc1999 @lrinQVQ 是基于unbound和dnscrypt的本地DNS

**Comment by lrinQVQ** [comment]
给你一个提示 目前GFW已经污染了所有UDP协议 53端口的DNS 推荐你关掉UDP强制使用TCP

**Comment by CNMan** [comment]
@lrinQVQ dnscrypt已强制TCP了，unbound这里就不用了

**Comment by lrinQVQ** [comment]
@CNMan orz才看到
