### ISSUE TITLE
Dropbox新IP

### ISSUE THREAD

**Issue by Makebignew** [racaljk/hosts#931]
52.29.64.168 www.dropbox.com
dropbox新上线的德国服务器，其他域名IP也能扫出来（手机不方便）

**Comment by lrinQVQ** [comment]
啧

**Comment by andytimes** [comment]
👍 确实可用，可以考虑替换。

**Comment by lrinQVQ** [comment]
Thx 留为备用

**Comment by andytimes** [comment]
@lrinQVQ https://github.com/racaljk/hosts/blob/master/hosts#L98
目前 hosts 内对应 IP 是香港移动缓存服务器 IP

**Comment by lrinQVQ** [comment]
@andytimes chekcout this issues create a PR

**Comment by Makebignew** [comment]
@andytimes 108.160.173.233 db.tt

**Comment by andytimes** [comment]
@Makebignew 谢，我等下改。
