### ISSUE TITLE
请帮忙看看XDA的IP是不是改了，访问特别慢而且很多网页打不开

### ISSUE THREAD

**Issue by wsz2074480** [racaljk/hosts#932]
，如题。感谢感谢

**Comment by wsz2074480** [comment]
补充：是XDA论坛

**Comment by wsz2074480** [comment]
比如这个进不去：

https://forum.xda-developers.com/s7-edge/development

**Comment by lrinQVQ** [comment]
xda的啊

**Comment by sqc1999** [comment]
我能进去

**Comment by sqc1999** [comment]
我发现虽说盛传移动有自带墙，但是很多国外网站的访问速度移动比电信要快很多

**Comment by wsz2074480** [comment]
@sqc1999 的确。

**Comment by jiangtiandao** [comment]
我就秒开xda 怀疑是移动搞了cache

**Comment by lrinQVQ** [comment]
forum-lw-1.xda-cdn.com
viglink.com
貌似这两个的原因= =

**Comment by Makebignew** [comment]
@lrinQVQ 185.28.71.53 forum-lw-1.xda-cdn.com
香港IP或许不稳定
