### ISSUE TITLE
2017大家新年快乐

### ISSUE THREAD

**Issue by lrinQVQ** [racaljk/hosts#934]
祝大家新年快乐~

**Comment by sqc1999** [comment]
我不快乐，我仍然在多线程调试的深渊中

**Comment by lrinQVQ** [comment]
@sqc1999 我正在和女朋友过春节233

**Comment by sqc1999** [comment]
我今年才发现WOC春晚好恶心啊

**Comment by lrinQVQ** [comment]
@sqc1999 +1 orz 什么掏粪== 一堆无聊的东西= =

**Comment by Too-Naive** [comment]
![](https://cloud.githubusercontent.com/assets/16496671/20557321/f47b3c50-b1a5-11e6-8810-8edc50a65778.png)

**Comment by lrinQVQ** [comment]
@Too-Naive 滑稽日常

**Comment by lgengsy** [comment]
google不能用啊 。你们的也是不能用么 。

**Comment by sqc1999** [comment]
可以的说

**Comment by imknown** [comment]
@lgengsy https://github.com/racaljk/hosts/issues/745 这里聊

**Comment by dyphoenix** [comment]
我这边能用的啊

**Comment by lrinQVQ** [comment]
可以用+1

**Comment by Too-Naive** [comment]
![](https://cloud.githubusercontent.com/assets/16496671/20557321/f47b3c50-b1a5-11e6-8810-8edc50a65778.png)

**Comment by lrinQVQ** [comment]
@Too-Naive 日常滑稽

**Comment by Ir1d** [comment]
快乐快乐 祝大家心想事成

**Comment by sqc1999** [comment]
@Ir1d 怎么这就close了。。等到元宵节嘛。。

**Comment by lrinQVQ** [comment]
啧 这就close了吗orz 好吧2333 没事

**Comment by lrinQVQ** [comment]
可以可以2333 我开始沉迷bug = =

**Comment by sqc1999** [comment]
前段时间也是，调bug调到无法自拔。。

**Comment by sqc1999** [comment]
话说大家有什么好的有声书推荐吗，开学以后碰不了电脑，能碰到的电子产片只有一块电子表和一只音频播放器。。

**Comment by lrinQVQ** [comment]
昂 有声书

**Comment by sqc1999** [comment]
`昂`是什么鬼。。

**Comment by lrinQVQ** [comment]
就是思考中2333

**Comment by Ir1d** [comment]
喜马拉雅f m？网易云音乐高中必备篇目系列？

没注意到等到元宵节… 真是抱歉 主要是高三对于过年完全没有概念QAQ

**Comment by lrinQVQ** [comment]
个人觉得orz 网易云音乐

**Comment by Too-Naive** [comment]
![](https://cloud.githubusercontent.com/assets/16496671/20557321/f47b3c50-b1a5-11e6-8810-8edc50a65778.png)

**Comment by sqc1999** [comment]
哇，GitHub导航栏居然更新了，感觉新的导航栏有点帅呢
然而好像和整个网站的UI风格不太搭。。

**Comment by sqc1999** [comment]
马上就要Build 2017了诶，好想去啊，哪位土豪送我张门票。。

**Comment by imknown** [comment]
@sqc1999 我喜欢白色. 黑色 白天看不清.

**Comment by Ir1d** [comment]
https://www.v2ex.com/t/339716
以及如果没啥事的话建议去gitter room水
在这里发的话watch的人大多会收到邮件 不是每个人都希望收到yi dui

**Comment by socalledtwobee** [comment]
说的对，天天一堆邮件

2017年2月11日 上午11:08，"SCaffrey" <notifications@github.com>写道：

**Comment by sqc1999** [comment]
好吧好吧，我错了 😫

**Comment by imknown** [comment]
@Ir1d 嗯 我下次注意.
