### ISSUE TITLE
hosts 2 pac

### ISSUE THREAD

**Issue by tianrking** [racaljk/hosts#939]
有没有什么方式可以利用hosts生成 pac配置的方法

**Comment by sqc1999** [comment]
它们不是一个东西吧。。

**Comment by tianrking** [comment]
@sqc1999 本来就不是一个东西啊  T.T 我想把hosts放到服务器上 无奈dnsmasq 53端口污染  不过pac可行  就是只会一点c++ 还没能力自己实现  就是打算做个软件 将host 里面地址与域名一一对应的关系变成pac的格式

**Comment by sqc1999** [comment]
@tianrking PAC我不是很熟，然而我记得没错的话它是把域名对应到代理服务器，并不支持对应到真实服务器的IP吧。。DNS污染的话你可以试试DNSCrypt，就是本地也要用专门软件，麻烦一点。

**Comment by jiangtiandao** [comment]
本地搭一个 acrylic dns 就是
@tianrking

**Comment by tianrking** [comment]
@jiangtiandao 谢谢你推荐的方案。 不过可能我没表述清我的意思。  我是想实现云端同步hosts(在vps上)然后用户修改下dns或者在浏览器里添加pac 就可以方便的使用谷歌之类的服务。 而不是在客户端安装相应的程序，就像dnscrypt 或者acrylicdns 。关键就是直接在外国vps上无论是开bind或者dnsmasq国内使用后都会出现53端口被污染 无法查询的情况 。 不过貌似pac可以实现。而且pac配置可以放在任意主机上开放不同的端口。

**Comment by sqc1999** [comment]
@tianrking 如果我没弄错的话PAC无法实现这种帮助DNS解析的功能（如果我弄错了，给我看个例子，让我长长知识😃），如果你在国外服务器上配置好DNSCrypt的服务器端的话，只要在客户端的DNSCrypt中指向你的服务器，不用特别配置，也支持不同端口。这样只是在你服务器端的dnsmasq和客户端的操作系统之间用DNSCrypt做了一下加密，我认为是和你想要的最接近的方案。

**Comment by tianrking** [comment]
@sqc1999  谢谢你的耐心回复+小调侃  PAC是proxy auto-config只能返回代理或者直连，我完全想错了。那么貌似只有用国内服务器直接搭建dns配合hosts和在国外vps上搭建dns服务器配置dnscryp(t或类似的dns加密)这两种方案。 好吧我选择了直接用shadowsocks 😃😃。 原先一直在想有没有什么可以直连的方式。用树莓派配置dnscrypt的话因为家里长宽 没有公网ip在外面还是不能用。
