### ISSUE TITLE
发现一个 谷歌未被■的 域名 `crbug.com`

### ISSUE THREAD

**Issue by imknown** [racaljk/hosts#942]
相关域名
1. https://bugs.chromium.org/p/chromium/issues/list
2. https://chromium-build.appspot.com/p/chromium/console

**Comment by lrinQVQ** [comment]
这好像是chromium的issues列表= =

**Comment by imknown** [comment]
@lrinQVQ 是的

**Comment by Makebignew** [comment]
这种域名指向的是GHS，不是gws 有成片没被墙，不能用来做hosts

**Comment by jiangtiandao** [comment]
https://blog.aofall.com/archives/7.html

**Comment by imknown** [comment]
楼上好评, 其实我只是今天工作用了这个域名而已 :D

**Comment by lrinQVQ** [comment]
@imknown 最近会有空吗2333 https://github.com/lrinQVQ/android_kernel_tcl_q39 还差一个格式的bug应该就ok了= =

**Comment by imknown** [comment]
@lrinQVQ Hi, 还可以吧, 不过 底层开发我不懂额.

**Comment by lrinQVQ** [comment]
@imknown 2333 没事 会fastboot flash boot boot.img就好啦

**Comment by lrinQVQ** [comment]
@imknown 顺便问下你现在用的系统是cm的吗

**Comment by imknown** [comment]
@lrinQVQ 是 CM. 其他方式聊吧,
