### ISSUE TITLE
tumblr二级域名不能访问

### ISSUE THREAD

**Issue by letu81** [racaljk/hosts#945]
深圳电信，tumblr搜索页面，关键词任意，点击用户名，连接ERR_CONNECTION_TIMED_OUT
但能直接在当前／搜索结果显示页面播放视屏，查看图片。。

**Comment by sqc1999** [comment]
这是没办法的吧。。hosts又不支持通配符
话说Disqus也是这个情况吧。。

**Comment by EricInBj** [comment]
tumblr 二级域名不支持 https ，通配符倒不是啥致命的问题。

**Comment by sqc1999** [comment]
哪里不致命了。。不支持通配符的话只能通过自建DNS之类方法解决，对于hosts这个方法来说是无解的吧。。
不过我没用过tumblr，就刚才去看了一眼，没注意这个不支持HTTPS。。这样的话就更加麻烦了。。
不过如果只是针对个别域名，有没有敏感词的话，自己个别添加不就好了

**Comment by letu81** [comment]
@sqc1999,  单个加了，可行，多谢
