### ISSUE TITLE
项目中 tools里的windows.zip 链接失效

### ISSUE THREAD

**Issue by redapple0204** [racaljk/hosts#947]

**Comment by imknown** [comment]
https://github.com/racaljk/hosts/tree/master/tools 里面有写:
> **除脚本外，其他工具已迁移至  [HostsTools](https://github.com/HostsTools)（不含 Hozz）**

https://github.com/HostsTools/Windows#%E4%B8%8B%E8%BD%BD%E5%9C%B0%E5%9D%80v2119

**Comment by Ir1d** [comment]
https://github.com/HostsTools/Windows/releases
Landed. Thx.
