### ISSUE TITLE
github-cloud.s3.amazonaws.com 失效了

### ISSUE THREAD

**Issue by doghap** [racaljk/hosts#948]
github-cloud.s3.amazonaws.com 失效了

**Comment by sqc1999** [comment]
我这里正常，GitHub Releases的文件可以正常下载

**Comment by jiangtiandao** [comment]
ISP是？
@doghap

**Comment by doghap** [comment]
新疆电信 @jiangtiandao

**Comment by sqc1999** [comment]
新疆啊。。

**Comment by EMLVIRUS** [comment]
GG 新疆无条件屏蔽~gayhub~

**Comment by Too-Naive** [comment]
![](https://cloud.githubusercontent.com/assets/16496671/20557321/f47b3c50-b1a5-11e6-8810-8edc50a65778.png)

**Comment by oilbottle** [comment]
深圳联通貌似也不行

**Comment by imknown** [comment]
` 54.231.80.232` 试试
