### ISSUE TITLE
Ubuntu 下 command not found

### ISSUE THREAD

**Issue by Roller44** [racaljk/hosts#95]
在 README 里 Linux 下建议修改完 host 文件之后输入：
```
sudo systemctl restart NetworkManager
```
或
```
sudo rcnscd restart
```
但是我在 Ubuntu 下输入都反馈 `command not found `。

根据 Windows 下的规律，我猜测这两条命令都是清除 DNS 缓存的，那么如果这样，在 Ubuntu 下应该是：
```
sudo /etc/init.d/networking restart
```
如果我猜对了，建议加上去。

还有，别的发行版我不知道在 `hosts` 文件内如果不在 `127.0.01` 后面加上本机名字，会出现 `unable to resolve host` 提示，有没有办法解决呢？

**Comment by K-Guan** [comment]
1. 实际是重启网络服务而已。拿Windows举例：禁用网络适配器，开启网络适配器。没错就是这样。`sudo /etc/init.d/networking restart` 在Ubuntu下有用吗？
2. 我们有提供脚本解决这个问题，要不也可以手动加进去。

**Comment by Roller44** [comment]
sudo /etc/init.d/networking restart
在 Ubuntu 就是这么用的。
我的意思就是通过脚本解决这个问题，因为我觉得通过输入命令一下子更新 hosts，脚本在哪里？

**Comment by K-Guan** [comment]
正解
