### ISSUE TITLE
gcm-http.googleapis.com 的ip似乎不正确

### ISSUE THREAD

**Issue by NianSan** [racaljk/hosts#952]
gcm-http.googleapis.com的ip和其它的gcm域名ip好像不是同一个

**Comment by aofall** [comment]
不然为什么要HTTP

**Comment by NianSan** [comment]
不是，我没说清楚，mtalk.google.com 用的是64.233.188.188
gcm-http.googleapis.com 用的不应该是64.233.188.188 ，连不上

**Comment by 10089** [comment]
用的普通gws

**Comment by NianSan** [comment]
普通gws可以@10089，谢谢
