### ISSUE TITLE
[host request] gitter IP 缺失

### ISSUE THREAD

**Issue by EMLVIRUS** [racaljk/hosts#957]
又双叒叕有IP失效了

**Comment by sqc1999** [comment]
hosts里没有gitter的条目吧。。

**Comment by EMLVIRUS** [comment]
阿列 好像是啊

**Comment by lrinQVQ** [comment]
gitter 能够正常访问啊0.0 @EMLVIRUS

**Comment by sqc1999** [comment]
能正常访问+1
开学前最后的comment
永别了 😶

**Comment by lrinQVQ** [comment]
@sqc1999 加油2333

**Comment by lrinQVQ** [comment]
@sqc1999 等你回来233

**Comment by EMLVIRUS** [comment]
阿列 真的唉 你们就当没看见╮(╯▽╰)╭

**Comment by Too-Naive** [comment]
![](https://cloud.githubusercontent.com/assets/16496671/20557321/f47b3c50-b1a5-11e6-8810-8edc50a65778.png)
