### ISSUE TITLE
请教该 host 如何在 Surge 中使用

### ISSUE THREAD

**Issue by yehon** [racaljk/hosts#958]
如题…

先感谢所有回答和帮助这个问题的人，Surge 类软件在 iOS 当中很流行，若能直接在线更新 Surge 配置文件，那这个列表会造福更多人。

感谢大家。^_^

_— — 来自一个非程序员在 GitHub 上的第一个 issues_

**Comment by lrinQVQ** [comment]
IOS ==

**Comment by yehon** [comment]
@lrinQVQ 您这个是 iOS 等一等的意思，还是 表情符号？

**Comment by imknown** [comment]
第一次听说 Surge, 一搜 搜出来 这些, 不知道满不满足需求
- https://github.com/huanz/surge-hosts
- https://github.com/ifyour/Hosts-for-Surge

**Comment by yehon** [comment]
@imknown 它们的安全么……

**Comment by imknown** [comment]
@yehon 他们的数据 都是从 这个项目里面来的. 
ip 什么的, 安不安全 不敢保证. 参看:
> https://github.com/racaljk/hosts/issues/797
> https://github.com/racaljk/hosts/issues/674

请楼主自行斟酌.

**Comment by sqc1999** [comment]
@yehon 那你又怎么能保证这个库的hosts文件安全呢
@Ir1d @imknown @lrinQVQ 话说似乎有不少issue都是要求提供格式相近的类似hosts功能的文件，是不是可以利用在CI时用脚本自动转化成各种格式的文件呢？appveyor是提供artifacts作为文件存储的，travis我不知道。。
PS:这只是一次回光返照 :smile:

**Comment by yehon** [comment]
@sqc1999 好吧，我还是老老实实用 ss 吧…

**Comment by sqc1999** [comment]
@yehon 安全性的话我并不觉得ss有任何保证，真的追求安全性的话应该去考虑tor之类的

**Comment by sqc1999** [comment]
我刚才看了一下travis的文档，它似乎并不提供单独的存储服务，只能部署到别的地方去，不过真的要搞的话可以利用GitHub的Releases功能
这个提案我放到单独的issue里去吧

**Comment by yehon** [comment]
@sqc1999 之前一直不知道 tor，刚才在你的建议下，搜索了一下，发现这才是我要的…哈哈哈，感谢！

**Comment by Too-Naive** [comment]
Surge不是贼贵吗...

**Comment by yehon** [comment]
那是现在的价格，最早发布的时候68还是很便宜的。

**Comment by EMLVIRUS** [comment]
Tor这么慢你也能忍.................

**Comment by 20141211** [comment]
厉害啦
