### ISSUE TITLE
ingress客户端问题

### ISSUE THREAD

**Issue by houfukude** [racaljk/hosts#959]
首先感谢各位的努力维护一份可用的hosts

但目前已经有玩家因为使用hosts导致 Ingres账号被ban
所以在这里提出一个警示！

> forge any TCP/IP packet header or any part of the header information in any email or newsgroup posting, or in any way use the Services or Content to send altered, deceptive, or false sourceidentifying information;

来源 [Ingress TOS](https://www.ingress.com/terms)

已知的是 Ingress Android客户端是不支持SNI [(SNI WIKI)](https://github.com/racaljk/hosts/wiki/%E4%B8%BA%E4%BB%80%E4%B9%88%E4%B8%8D%E6%8E%A8%E8%8D%90%E5%9C%A8%E7%A7%BB%E5%8A%A8%E8%AE%BE%E5%A4%87%E4%B8%8A%E4%BD%BF%E7%94%A8hosts%EF%BC%9F)的。

同样其他三方的游戏，应用等请谨慎使用！

**Comment by imknown** [comment]
技术本无错, 且用且珍惜.

**Comment by lrinQVQ** [comment]
+1

**Comment by Too-Naive** [comment]
@houfukude 您有被ban嗎..
玩ingress還是老實用ss等代理工具吧

**Comment by wangyw15** [comment]
谢谢，没有
----- 原始邮件 -----
发件人：Unostvisal <notifications@github.com>
收件人：racaljk/hosts <hosts@noreply.github.com>
抄送人：Subscribed <subscribed@noreply.github.com>
主题：Re:_[racaljk/hosts]_ingress客户端问题_(#959)
日期：2017年02月13日 15点24分

@houfukude 您有被ban嗎..

玩ingress還是老實用ss等代理工具吧

&mdash;

**Comment by sy618** [comment]
这个问题已解决。

目前hosts里使用的是官方IP，可以放心使用。

**Comment by Too-Naive** [comment]
建议还是用ss→_→这种东西 到一定程度的话 被ban很难过的
