### ISSUE TITLE
报个BUG

### ISSUE THREAD

**Issue by seozed** [racaljk/hosts#962]
ubuntu 16.04 64bit
用lhost更新hosts文件完了之后，如果使用sudo 命令会提示无法解析主机名称
````
zed@zed-To-be-filled-by-O-E-M:~/文档/tools$ sudo ls
sudo: 无法解析主机：zed-To-be-filled-by-O-E-M

````
在hosts里添加上这一行就解决了。
`
127.0.0.1 zed-To-be-filled-by-O-E-M
`

建议在拉取远程hosts文件的时候，追加一行配置，主机名可以通过hostname来获取

**Comment by lrinQVQ** [comment]
= =这是你的主机名吧

**Comment by Ir1d** [comment]
你好 感觉范围模式怎么样？

**Comment by redapple0204** [comment]
这™问题很严重啊，linux都会出现这个bug

**Comment by Ir1d** [comment]
@redapple0204 @seozed 配置myname呢？

**Comment by seozed** [comment]
> 你好 感觉范围模式怎么样？
> 
> https://github.com/racaljk/hosts/blob/master/tools/lhosts#L47

这个正常工作;)

**Comment by seozed** [comment]
> 你好 感觉范围模式怎么样？
> 
> https://github.com/racaljk/hosts/blob/master/tools/lhosts#L47

这个正常工作;)
