### ISSUE TITLE
小小的建议，能不能加入kobo同步的url

### ISSUE THREAD

**Issue by WeihuaGu** [racaljk/hosts#964]
穷人用不起kindle,就用kobo看书。可是kobo 同步不了了，有时会看些免费的英文书……

**Comment by lrinQVQ** [comment]
哪些0.0

**Comment by WeihuaGu** [comment]
从kobo touch配置文件中找到的网址：
[OneStoreServices]
api_endpoint=https://storeapi.kobo.com
autocomplete=https://storeapi.kobo.com/v1/products/autocomplete
book=https://storeapi.kobo.com/v1/products/books/{ProductId}
book_btb=
book_landing_page=https://store.kobobooks.com/ebooks
categories=https://storeapi.kobo.com/v1/categories
category=https://storeapi.kobo.com/v1/categories/{CategoryId}
category_products=https://storeapi.kobo.com/v1/categories/{CategoryId}/products
discovery_host=https://discovery.kobobooks.com
eula_page="https://www.kobo.com/termsofuse?style=onestore"
featured_list=https://storeapi.kobo.com/v1/products/featured/{FeaturedListId}
featured_lists=https://storeapi.kobo.com/v1/products/featured
feedback=
fte_feedback=https://storeapi.kobo.com/v1/products/ftefeedback
image_host=//kbimages1-a.akamaihd.net/
kobo_superpoints_enabled=false
love_data=@ByteArray(\0\0\0\x1\0\0\0\x10\0\x42\0\x65\0n\0\x65\0\x66\0i\0t\0s\0\0\0\b\0\0\0\0\0)
love_points_redemption_page="https://store.kobobooks.com/{culture}/KoboSuperPointsRedemption?productId={ProductId}"
magazine_detail_page=
magazine_issue=
magazine_landing_page=https://store.kobobooks.com/emagazines
magazine_subscription=
password_retrieval_page=https://www.kobobooks.com/passwordretrieval.html
privacy_page="https://www.kobo.com/privacypolicy?style=onestore"
product_recommendations=https://storeapi.kobo.com/v1/products/{ProductId}/recommendations
product_reviews=https://storeapi.kobo.com/v1/products/{ProductIds}/reviews
purchase_buy_templated=https://store.kobobooks.com/{culture}/purchase/buy/{ProductId}
registration_page="https://secure.kobobooks.com/auth/register?redirectUrl=https://store.kobobooks.com/"
review=https://storeapi.kobo.com/v1/products/reviews/{ReviewId}
review_sentiment=https://storeapi.kobo.com/v1/products/reviews/{ReviewId}/sentiment/{Sentiment}
search=
sign_in_page="https://secure.kobobooks.com/auth/login?redirectUrl=https://store.kobobooks.com/"
social_authorization_host=https://social.kobobooks.com:8443
social_host=https://social.kobobooks.com
stacks=
stacks_host_productId=https://store.kobobooks.com/collections/byproductid/
store_host=store.kobobooks.com
taste_profile=https://storeapi.kobo.com/v1/products/tasteprofile
user_ratings=https://storeapi.kobo.com/v1/user/ratings
user_recommendations=https://storeapi.kobo.com/v1/user/recommendations
user_reviews=https://storeapi.kobo.com/v1/user/reviews


[Services]
ContactUsURL=http://webstore.kobobooks.com/90104/contact.html
EulaURL=http://webstore2.kobobooks.com/boutique/webstoretermsofuse
FirstTimeUXURL="https://secure.kobobooks.com/90104/ftux?pwspid={0}&wsa={1}&pwsdid={2}&pwsav={3}&pwsdm={4}&pwspos={5}&pwspov={6}"
ForgotPasswordURL=https://www.kobobooks.com/passwordretrieval.html
ImageHandlerURL=http://ecimages.kobobooks.com/Image.ashx
PartnerProxyHandlerURL=https://mobilepartner.kobobooks.com/90104/mobileRequest.ashx
PrivacyURL=http://webstore2.kobobooks.com/boutique/webstoreprivacypolicy
PurchaseURL=https://partner.kobobooks.com/checkout.html
RequestURL=https://mobile.kobobooks.com/90104/mobilerequest.ashx
SecureURL="https://secure.kobobooks.com/90104/Purchase/Index?wscid=&ctype=&wsukey=&wsuid=&pwspid=&wsa=&IsGift=False&isfte="
ServiceDomain=.kobobooks.com
ServicesURL=https://services.kobobooks.com
SignInURL=
SocialAuthorizationURL=https://social.kobobooks.com:8443
SocialURL=https://social.kobobooks.com
WebsiteURL=http://www.kobobooks.com
WebstoreProxyURL=https://partner.kobobooks.com/90104
WebstoreURL=http://webstore2.kobobooks.com/90104

**Comment by DDoSolitary** [comment]
好像只是普通的DNS污染的样子，我来搞吧

**Comment by WeihuaGu** [comment]
@DDoSolitary :+1:

**Comment by DDoSolitary** [comment]
@WeihuaGu 我不用kobo，麻烦测试一下https://github.com/DDoSolitary/hosts/tree/patch-kobo-%23964

**Comment by DDoSolitary** [comment]
下午一边补番一边搞这个，所以搞了很久

**Comment by WeihuaGu** [comment]
@DDoSolitary 太感谢了。用kobo touch实测，已经可以浏览书店，同步出书库中有哪些书了，并且更新书籍封面。但是还是不能下载书库中书籍，这已经很好了。再次感谢 :)

**Comment by DDoSolitary** [comment]
@WeihuaGu 有几个下载相关的域名不支持HTTPS，就算指向了正确的IP也直接被关键字过滤了，所以无解
