### ISSUE TITLE
关于账号变更的告知

### ISSUE THREAD

**Issue by sqc1999** [racaljk/hosts#967]
我换了个账号，新账号是 @DDoSolitary ，以后都用新账号活动，旧账号估计不会再用了

**Comment by DDoSolitary** [comment]
新账号就是我 😄

**Comment by EMLVIRUS** [comment]
![image](https://cloud.githubusercontent.com/assets/16912240/23090208/33c1aebe-f5d3-11e6-8fe2-d5f6a10e917c.png)
=.=

**Comment by sqc1999** [comment]
我说我在把旧帐号的repo全都transfer到新账号上，但是我新账号关联邮箱里收到的链接打开来显示server error，有没有人有这方面的经验。。

**Comment by lrinQVQ** [comment]
欸多

**Comment by lyq1996** [comment]
贼6

**Comment by Ir1d** [comment]
改个名不就好了吗
