### ISSUE TITLE
Google 再次无法访问

### ISSUE THREAD

**Issue by zhaosoap** [racaljk/hosts#968]
google 又被墙了。求更新

**Comment by lzh984294471** [comment]
速度是慢了点，但还是可以上的啊

**Comment by Ir1d** [comment]
可以翻一翻hosts里分享过的历史ip

**Comment by imknown** [comment]
https://github.com/racaljk/hosts/issues/745 建议在这里讨论

**Comment by lrinQVQ** [comment]
延迟太高了= =

**Comment by lrinQVQ** [comment]
一会找下新的看看

**Comment by Ir1d** [comment]
你们不感觉745太长了点吗……

**Comment by DDoSolitary** [comment]
然而我见过更长的。。

**Comment by Kenwangxr** [comment]
我的一直无法使用，google搜索

发自我的 iPhone

**Comment by hackasc** [comment]
google was gone...

**Comment by wolfan** [comment]
报告，湖南联通，此时此刻又一次墙掉。

**Comment by Too-Naive** [comment]
![](https://cloud.githubusercontent.com/assets/16496671/20557321/f47b3c50-b1a5-11e6-8810-8edc50a65778.png)

**Comment by csrgxtu** [comment]
我一直不能用google搜索，host文件里的ip地址对我的isp没有作用

**Comment by lrinQVQ** [comment]
xd

**Comment by lrinQVQ** [comment]
@csrgxtu 你的IPS是0.0

**Comment by mraandtux** [comment]
测试时间：2017/03/20
ISP：联通广州
泰IP无法访问
ISP：移动广州
泰IP可以访问

**Comment by imknown** [comment]
我除了 `https://www.google.com/ncr` 打不开, 
剩下的 `http://www.google.com/` `http://d.android.com` 等 都能打开.

**Comment by laodcn** [comment]
我这里正常使用

**Comment by Pictor** [comment]
61.91.161.217 这个 IP 这几天不好用了，延迟太高（>500ms），Google 页面很难打开。我看到 XX-Net 会找出一些 IP，我试了有少部分可以用在 hosts 里面。目前我用的 202.88.157.218，速度较为理想，Google 页面都可以正常打开。

**Comment by lrinQVQ** [comment]
目前这个IP偶尔抽风一下orz还算好

**Comment by Pictor** [comment]
顺便问问 Google 的官方 IP 是随时受到监控的么？之前找到两个可用的，十分钟内 ping 了三次都是通的，但是放到 hosts 里面加载 Google 网页后，过一两分钟就不可用了。

**Comment by lrinQVQ** [comment]
@Pictor 不不不线路问题

**Comment by lrinQVQ** [comment]
@Pictor 我之前也是这样 traceroute后发现基本上都断在国外

**Comment by Pictor** [comment]
@lrinQVQ 这样啊，明白了。

**Comment by lrinQVQ** [comment]
@Pictor 比如你的这个orz
traceroute 202.88.157.218
traceroute to 202.88.157.218 (202.88.157.218), 30 hops max, 60 byte packets
 1  LEDE.lan (192.168.1.1)  0.565 ms  0.786 ms  1.038 ms
 2  123.147.84.1 (123.147.84.1)  7.072 ms  7.078 ms  7.068 ms
 3  221.5.232.221 (221.5.232.221)  8.232 ms 221.5.232.225 (221.5.232.225)  7.295 ms 221.5.232.221 (221.5.232.221)  8.454 ms
 4  221.5.232.205 (221.5.232.205)  8.859 ms 221.5.239.57 (221.5.239.57)  8.162 ms 221.5.239.209 (221.5.239.209)  7.253 ms
 5  219.158.12.97 (219.158.12.97)  37.597 ms 219.158.16.149 (219.158.16.149)  34.772 ms 219.158.12.97 (219.158.12.97)  37.869 ms
 6  219.158.99.98 (219.158.99.98)  36.403 ms 219.158.13.106 (219.158.13.106)  102.264 ms 219.158.97.94 (219.158.97.94)  106.771 ms
 7  219.158.103.94 (219.158.103.94)  106.464 ms  109.828 ms 219.158.97.46 (219.158.97.46)  103.592 ms
 8  * 219.158.39.194 (219.158.39.194)  116.911 ms *
 9  * ae-2.r25.osakjp02.jp.bb.gin.ntt.net (129.250.5.51)  130.514 ms  128.402 ms
10  ae-8.r20.sngpsi05.sg.bb.gin.ntt.net (129.250.3.110)  280.910 ms  281.191 ms  200.400 ms
11  ae-2.r00.sngpsi02.sg.bb.gin.ntt.net (129.250.3.147)  189.565 ms  212.850 ms  214.316 ms
12  xe-0-5-0-31.r00.sngpsi02.sg.ce.gin.ntt.net (116.51.27.218)  323.482 ms * *
13  * * 182.79.255.170 (182.79.255.170)  386.035 ms
14  * * 59.145.146.90 (59.145.146.90)  357.678 ms
15  * * *
16  * * *
17  * * *
18  * * *
19  * * *
20  * * *
21  * * *
22  * * *
23  * * *
24  * * *
25  * * *
26  * * *
27  * * *
28  * * *
29  * * *
30  * * *

**Comment by Pictor** [comment]
@lrinQVQ 原来 IP 还不能通用啊，目前我依然可用。我在 XX-Net 的 IP 列表里面找了多个，就这个最可靠。其余的许多不能加载网页，有些只能打开 www.google.com.hk 但是打不开 google.com 的页面。

**Comment by lrinQVQ** [comment]
@Pictor 是啊233 正常2333 你可以试试https://www.google.com/ncr

**Comment by Pictor** [comment]
@lrinQVQ 是的，我这里 202.88.157.218 这个 IP 能够打开 www.google.com 页面。我也用的联通，也是到了 59.145.146.90 这个节点，接下来一跳就是 www.google.com [202.88.157.218] 了。

**Comment by lrinQVQ** [comment]
@Pictor 那你运气不错2333 我这GG了

**Comment by Makebignew** [comment]
@lrinQVQ  202.38.64.9 這個是中科大自己搭設的服務器，原理就是利用教育網ipv6直連Google，然後在這臺伺服器上坐了Port forwarding，對於部分網絡環境這是最後的辦法。
不建議作為項目的IP，安全性需要自行考量

**Comment by Pictor** [comment]
202.86.162.172 这一澳门 IP 的连接速度很快。

**Comment by mobyzhang** [comment]
Google上不去了？？？？
