### ISSUE TITLE
话说发生了什么 github又被墙了吗

### ISSUE THREAD

**Issue by xmdhs** [racaljk/hosts#975]
![](https://ooo.0o0.ooo/2017/02/23/58aede489d654.png)
![](https://ooo.0o0.ooo/2017/02/23/58aede48ac4dc.png)

**Comment by Moriaty911** [comment]
似乎是的，我这边反正ping不通了，上交给gfwlist吧

**Comment by xmdhs** [comment]
那上个github 也要用代理  又在搞什么

**Comment by Moriaty911** [comment]
14年还是什么时候的就屏蔽过一次，然后好多程序员就不高兴了，李开复也发微博反对，后来过了几天就解除了，不知道这次又要多久。

**Comment by EMLVIRUS** [comment]
维基上写13年，这次我估计够呛。我不知道这个项目的wiki还能摆多久............

**Comment by xmdhs** [comment]
好像又正常了

**Comment by Too-Naive** [comment]
![](https://cloud.githubusercontent.com/assets/16496671/20557321/f47b3c50-b1a5-11e6-8810-8edc50a65778.png)

**Comment by norfish** [comment]
terminal 里面还是不好使，折腾terminal代理去了

**Comment by maoturing** [comment]
@xmdhs 这是什么网站啊

**Comment by imknown** [comment]
@maoturing 站长工具 http://ping.chinaz.com
