### ISSUE TITLE
notifications.google.com请求超时

### ISSUE THREAD

**Issue by DDoSolitary** [racaljk/hosts#976]
绍兴移动
对应IP `66.249.94.85`
浏览器访问`ERR_CONNECTION_TIMEOUT`，ping不通，路由跟踪断在`66.249.94.85`

**Comment by lrinQVQ** [comment]
0.0回家看下

**Comment by Makebignew** [comment]
海外一样超时

**Comment by LGA1150** [comment]
查无此域名

**Comment by DDoSolitary** [comment]
@LGA1150 有的，至少Gmail网页版有用到

**Comment by DDoSolitary** [comment]
额，好像应该是notification**s**.google.com
