### ISSUE TITLE
dropbox无法连接~~

### ISSUE THREAD

**Issue by stefanielyq** [racaljk/hosts#980]
恩 好像用了hosts即使开着vpn我也连不上 去掉了就好了~~

**Comment by imknown** [comment]
Win 10 吗?

**Comment by stefanielyq** [comment]
win7 x64~

**Comment by imknown** [comment]
我的 V.P.N IPSEC 连接的时候 会改 `hosts`, 不知道是不是 这个问题. 但是我绝大部分的时候 都是 可以同时用的. 偶尔不能同时用. 删掉 `hosts` 正常.

**Comment by imknown** [comment]
对了.. 连上 V*P*N 之后 尝试 `ipconfig /flushdns` .. 虽然不抱太大希望..

**Comment by lrinQVQ** [comment]
嘛貌似dropbox现在的ip是反代orz

**Comment by jicknan** [comment]
Chrome 会提示：

您的连接不是私密连接

攻击者可能会试图从www.dropbox.com窃取您的信息（例如：密码、通讯内容或信用卡信息）。 NET::ERR_CERT_COMMON_NAME_INVALID

**Comment by Wows233** [comment]
https://github.com/racaljk/hosts/issues/1075

**Comment by DDoSolitary** [comment]
@Ir1d 怎么close了？dropbox并没有修复吧。。
