### ISSUE TITLE
目前项目还是不用sniproxy ip的吧？是怎么判断一个ip是ggc还是反代的

### ISSUE THREAD

**Issue by woyaojizhu8** [racaljk/hosts#985]

**Comment by lrinQVQ** [comment]
IP WHOIS查询

**Comment by lrinQVQ** [comment]
拒绝反代orz

**Comment by woyaojizhu8** [comment]
@lrinQVQ whois里面很多时候并不会显示出Google Global Cache吧？仅通过它属于某个运营商就说它是ggc,  也并不准确吧？
这个办法可不可以：
用这个 ip 加入 hosts 或者 dnsmasq ，然后直接访问 https://redirector.googlevideo.com/report_mapping ，如果显示的是自己的ip，就是 ggc ，如果显示该 ip 就是 反代。
参考： https://www.v2ex.com/t/343343#reply18

**Comment by lrinQVQ** [comment]
欸多IP WHOIS就是显示出这个IP的归属者啊.. 如果归属者不是Google orz那就是反代了啊orz

**Comment by jiangtiandao** [comment]
两种判断的方法就是看 IP 的证书，前者是没有证书的，或者的证书是 google 的，证书类型是 GWS 
例如你说的 IP ，可以这样检测， curl -Ik https://61.91.161.217 
其中输出里面有一条显示 
Server: gws 
这就是 GGC 的证明

**Comment by woyaojizhu8** [comment]
@lrinQVQ ggc往往归属者不是google，只有谷歌自己的ip，归属者才一定是google

**Comment by woyaojizhu8** [comment]
@jiangtiandao 我给的那个参考链接里有说的，sni 同样可以配置成 google gws 证书，虽然运营商的 sniproxy 一般不会这么配置，但想这么配置理论上还是可以实现的。

**Comment by lrinQVQ** [comment]
@woyaojizhu8 orz所以我自己找IP只要google官网的

**Comment by wangchunming** [comment]
在手机上必须得用官方ip，但是在电脑上可以用代理，你可以来我这边看看，我这边就是这么做的。https://github.com/wangchunming/2017hosts

**Comment by wangchunming** [comment]
手机上所有域名如果盲目的用代理的话会导致大量app工作不正常。

**Comment by Too-Naive** [comment]
此時應該  @aofall

**Comment by aofall** [comment]
https://blog.aofall.com/archives/3.html

因为谷歌套件版本的差别，SNI支持程度不同，有些手机版本较新可以支持，有些较旧不支持，有些App则从未支持过。

**Comment by aixiu** [comment]
讲解的还是很细的！

**Comment by wangchunming** [comment]
可以找到的，*.googleusercontent.com 218.56.220.33
