### ISSUE TITLE
那个。。。android-studio不能用你的hosts下载了，能不能添加个

### ISSUE THREAD

**Issue by yangxins** [racaljk/hosts#987]
以前都是用你的hosts下载安装Android-studio的sdk，但是现在好像不行了。我的代理要么下载慢要么下载到一半卡住，希望能注意下，谢谢了：）

**Comment by imknown** [comment]
`dl.google.com` 可以直连, 别忘了使用 `Settings` 中的 `Secure Conntection`.

**Comment by yangxins** [comment]
@imknown 这是我android studio启动时的信息`[  92896]   WARN - s.RepoProgressIndicatorAdapter - Failed to download any source lists! 
[ 113071]   WARN - s.RepoProgressIndicatorAdapter - java.net.SocketTimeoutException: connect timed out `看样子不能连上啊，以前只要改了hosts就能满速下载，没改就不能下载。现在却不行了，好蛋疼啊...

**Comment by imknown** [comment]
SDK Tools 什么版本? 用的是 Https 吗?

**Comment by yangxins** [comment]
@imknown 我系统是linux mint，sdk tools好像没有安装。。。https应该没有问题。。

**Comment by yangxins** [comment]
@imknown 还有什么办法能满速下载安装不，好蛋疼。。

**Comment by yangxins** [comment]
@imknown 我还是用ss将就算了，太慢了。。。

**Comment by imknown** [comment]
=_ = Android SDK 不是 Linux 的自带库.
