### ISSUE TITLE
Can you add a mirror of a composer?

### ISSUE THREAD

**Issue by istrwei** [racaljk/hosts#988]
Since coming to China, it was found that composer was particularly slow

**Comment by lrinQVQ** [comment]
V2EX https://www.v2ex.com/member/strwei
twitter https://twitter.com/kaiku300strwei
strwei.com
orz骚年你= =

**Comment by Too-Naive** [comment]
什么情况..

**Comment by Ir1d** [comment]
https://pkg.phpcomposer.com/ 
// for future reference
