### ISSUE TITLE
论更正常的gcm

### ISSUE THREAD

**Issue by mewsf** [racaljk/hosts#993]
额外的一些域名(谷歌你同一个服务搞这么多域名真的好吗，让我纠结好久)
64.233.188.188 mobile-gtalk4.l.google.com
64.233.188.188 mtalk4.google.com
64.233.188.188 alt4-mtalk.google.com
64.233.188.188 alt4.mobile-gtalk4.l.google.com

(可能还是不全,我也没什么办法全查到,如果有高手还补充)

另 gcm-http.googleapis.com 这个按道理应该是解析到gws上才对
另另 gcm 有不少ip, 应该都是正常的(嘘)

**Comment by Too-Naive** [comment]
![](https://cloud.githubusercontent.com/assets/16496671/20557321/f47b3c50-b1a5-11e6-8810-8edc50a65778.png)

**Comment by wangchunming** [comment]
这个ip其实是被墙的。

**Comment by DDoSolitary** [comment]
并没有完全被墙，访问不稳定，经常丢包。。

**Comment by DDoSolitary** [comment]
@mewsf 你给出的这些域名的解析并没有被干扰啊
