### ISSUE TITLE
can not install software by chocolatey

### ISSUE THREAD

**Issue by chucklu** [racaljk/hosts#994]
choco install git-lfs
https://github.com/git-lfs/git-lfs/issues/2011

Is it possible cross the gfw when using the choco?

**Comment by lrinQVQ** [comment]
github的问题的话 你可以看下 https://github.com/racaljk/hosts/wiki/The-hosts-FAQ#%E4%B8%BA%E4%BB%80%E4%B9%88-github-%E6%9C%89%E6%97%B6%E6%89%93%E5%BC%80%E7%BC%93%E6%85%A2%E7%94%9A%E8%87%B3%E6%89%93%E4%B8%8D%E5%BC%80

**Comment by lrinQVQ** [comment]
还有git-lfs 没有安装成功不是因为gfw

**Comment by lrinQVQ** [comment]
http://ping.chinaz.com/chocolatey.org
chocolatey.org一切正常并且没有DNS污染

**Comment by lrinQVQ** [comment]
PS:国人就说中文嘛= =

**Comment by chucklu** [comment]
所以，是choco的问题？

**Comment by lrinQVQ** [comment]
昂 估计是的

**Comment by lrinQVQ** [comment]
@chucklu 你检查下安装了.NET Framework 4以上版本没有= =

**Comment by lrinQVQ** [comment]
104.20.73.28 虽然一切正常 但是偶尔会出现丢包的问题

**Comment by lrinQVQ** [comment]
@chucklu  你可以尝试这样104.20.74.28  chocolatey.org

**Comment by imknown** [comment]
我这里 是 `104.20.73.28`

**Comment by lrinQVQ** [comment]
@imknown 这个丢包严重233 我就没选

**Comment by chucklu** [comment]
尴尬，104.20.73.28和104.20.73.28这个2个ip都会丢包

104.20.74.28 的 Ping 统计信息:
    数据包: 已发送 = 21，已接收 = 15，丢失 = 6 (28% 丢失)，
往返行程的估计时间(以毫秒为单位):
    最短 = 185ms，最长 = 206ms，平均 = 188ms

104.20.73.28 的 Ping 统计信息:
    数据包: 已发送 = 7，已接收 = 4，丢失 = 3 (42% 丢失)，
往返行程的估计时间(以毫秒为单位):
    最短 = 187ms，最长 = 192ms，平均 = 189ms

**Comment by lrinQVQ** [comment]
@chucklu 恭喜你orz 代.理吧

**Comment by chucklu** [comment]
@lrinQVQ 那这个算什么情况呢，是被墙了吗？

**Comment by lrinQVQ** [comment]
@chucklu 不是被墙orz是你那里IPS的问题 我这一切OK的2333

**Comment by Too-Naive** [comment]
![](https://cloud.githubusercontent.com/assets/16496671/20557321/f47b3c50-b1a5-11e6-8810-8edc50a65778.png)
