### ISSUE TITLE
Twitter is down

### ISSUE THREAD

**Issue by DaleXiao** [racaljk/hosts#995]
Twitter is seemingly down, anyone else has this same issue?

**Comment by lrinQVQ** [comment]
twitter不行了嘛0.0

**Comment by myguybetter** [comment]
Same problem. That ip might be blocked.

**Comment by lrinQVQ** [comment]
I try to find new ip

**Comment by twitterguale** [comment]
挂了。
谁又在搞事情？

**Comment by Too-Naive** [comment]
![](https://cloud.githubusercontent.com/assets/16496671/20557321/f47b3c50-b1a5-11e6-8810-8edc50a65778.png)我很喜欢说英文 因为老外看得懂

**Comment by lrinQVQ** [comment]
orz 我一般中英文各来一份

**Comment by twitterguale** [comment]
不要学某2B领导人啊，一天到晚想讲几句洋文，天天以学狗叫为荣。

**Comment by Too-Naive** [comment]
→_→不要总是把政治引入到这里可好？
三句不离政治真有意思

**Comment by twitterguale** [comment]
说别人“引入政治”，不知道有些人用户名其来何自。

**Comment by Too-Naive** [comment]
那有怎樣 我似乎像你開口閉口都政治一樣XD

**Comment by twitterguale** [comment]
我如果是“开口闭口都政治”，那有些人恐怕就是脸上都写着政治。

**Comment by zhuweijia** [comment]
who has new ip for twitter ？？

**Comment by lrinQVQ** [comment]
try to find ing

**Comment by laodcn** [comment]
推特好像已经没有可用的ip了，找了好久

**Comment by lrinQVQ** [comment]
楼上+1

**Comment by twitterguale** [comment]
203.210.7.38 这个好像能用，网上找的。低调，低调。

**Comment by DDoSolitary** [comment]
SNI proxy?

**Comment by twitterguale** [comment]
不知道，先用着吧。

**Comment by lrinQVQ** [comment]
然而推特我开代理都上不去= =

**Comment by Nyovelt** [comment]
推特好像的确挂了

**Comment by lrinQVQ** [comment]
是的

**Comment by CNMan** [comment]
我这里也挂了：）

**Comment by nxtreaming** [comment]
No!

-----------------------------------------
Productive. Reliable. Fast.

**Comment by derekwei** [comment]
abs.twimg.com/*.twimg.com 相关域名的 IP 似乎也挂掉了

**Comment by lrinQVQ** [comment]
已找到可用IP 过会commit

**Comment by myguybetter** [comment]
@lrinQVQ ガンバって！　(๑ •̀ω•́)۶

**Comment by lrinQVQ** [comment]
@myguybetter 可用吗233

**Comment by myguybetter** [comment]
@lrinQVQ First ip (199.59.150.47) can't be accessed in my place.

**Comment by derekwei** [comment]
The first ip address is also blocked in my area, Internet service of which is provided by China Telecom.

**Comment by lrinQVQ** [comment]
thanks i'm China Unicom
i will keep try to find a work ip

**Comment by lijiangt** [comment]
来源: https://raw.githubusercontent.com/wangchunming/2017hosts/master/hosts-pc

# Twitter Start
219.76.4.4    static.ads-twitter.com
219.76.4.4	twitter.com
219.76.4.4	www.twitter.com
219.76.4.4	t.co
219.76.4.4	api.twitter.com
219.76.4.4	mobile.twitter.com
219.76.4.4	support.twitter.com
219.76.4.4	upload.twitter.com
219.76.4.4	tweetdeck.twitter.com
219.76.4.4	syndication.twitter.com
219.76.4.4	platform.twitter.com
219.76.4.4	about.twitter.com
219.76.4.4	blog.twitter.com
219.76.4.4	betastream.twitter.com
219.76.4.4	dev.twitter.com
219.76.4.4	pic.twitter.com
219.76.4.4	search.twitter.com
219.76.4.4	status.twitter.com
219.76.4.4	assets0.twitter.com
219.76.4.4	assets1.twitter.com
219.76.4.4	assets2.twitter.com
219.76.4.4	assets3.twitter.com
219.76.4.4	assets4.twitter.com
219.76.4.4	static.twitter.com
219.76.4.4	help.twitter.com
219.76.4.4	ton.twitter.com
219.76.4.4	s.twitter.com
219.76.4.4	analytics.twitter.com
219.76.4.4	urls-real.api.twitter.com
219.76.4.4	userstream.twitter.com
219.76.4.4	sitestream.twitter.com
219.76.4.4	stream.twitter.com
219.76.4.4	tdweb.twitter.com
219.76.4.4	twitpic.com
219.76.4.4	m1.twitpic.com
219.76.4.4	web1.twitpic.com
219.76.4.4	web10.twitpic.com
219.76.4.4	web2.twitpic.com
219.76.4.4	web3.twitpic.com
219.76.4.4	web4.twitpic.com
219.76.4.4	web5.twitpic.com
219.76.4.4	web6.twitpic.com
219.76.4.4	web7.twitpic.com
219.76.4.4	web8.twitpic.com
219.76.4.4	web9.twitpic.com
219.76.4.4	a0.twimg.com
219.76.4.4	a1.twimg.com
219.76.4.4	a2.twimg.com
219.76.4.4	a3.twimg.com
219.76.4.4	a4.twimg.com
219.76.4.4	a5.twimg.com
219.76.4.4	video.twimg.com
219.76.4.4	abs.twimg.com
219.76.4.4	g.twimg.com
219.76.4.4	o.twimg.com
219.76.4.4	p.twimg.com
219.76.4.4	r.twimg.com
219.76.4.4	ma.twimg.com
219.76.4.4	pbs.twimg.com
219.76.4.4	ton.twimg.com
219.76.4.4	syndication.twimg.com
219.76.4.4	syndication-o.twimg.com
219.76.4.4	image-proxy-origin.twimg.com
219.76.4.4	tweetdeck.com
219.76.4.4	api.tweetdeck.com
219.76.4.4	web.tweetdeck.com
219.76.4.4	www.tweetdeck.com
219.76.4.4	downloads.tweetdeck.com
219.76.4.4	cdn.syndication.twimg.com
219.76.4.4	cdn.syndication.twitter.com
219.76.4.4	apps.twitter.com
219.76.4.4	debates.twitter.com
# Twitter End

**Comment by derekwei** [comment]
219.76.4.4 这个似乎也是反代？

**Comment by lijiangt** [comment]
不确定，但确实好用。

如果是反代就不能用吗？

**Comment by derekwei** [comment]
原来我也曾考虑过添加反代替换现有IP 但是考虑到安全问题还是放弃了。。。

**Comment by lijiangt** [comment]
https访问应该问题不大吧？除非有人签发了假证书，可能性太小。
http访问会被reset，所以应该没有实质影响

**Comment by carlsora007** [comment]
thx guys very useful!

**Comment by derekwei** [comment]
@lijiangt 我也觉得问题不大，反正我最近也在用反代。但不知这个项目是不是只能放进去官方 IP

**Comment by xueyatou** [comment]
推特就这样挂了？

**Comment by lrinQVQ** [comment]
有点忙不过来orz

**Comment by lrinQVQ** [comment]
fix now
以修复
并且墙了我还有3个IP

**Comment by lrinQVQ** [comment]
@myguybetter twitter work now this is officially ip*٩(๑´∀`๑)ง*

**Comment by myguybetter** [comment]
@lrinQVQ Thanks for your hard work~

**Comment by lrinQVQ** [comment]
@mygutbetter  nothing～ it's so easy～

**Comment by DDoSolitary** [comment]
@lrinQVQ `officially`是副词吧，应该是`official IP`？
强迫症发作别管我。。

**Comment by EMLVIRUS** [comment]
@DDoSolitary  没毛病老铁

**Comment by zhuweijia** [comment]
最新的3月27号版本，我的twitter还是不能访问啊？大家的有问题吗？

**Comment by derekwei** [comment]
@zhuweijia 同，中国电信 104.***.45.248 已崩

**Comment by derekwei** [comment]
已经提交 commit 更新可用 ip

**Comment by zhuweijia** [comment]
ok 楼上
