### ISSUE TITLE
能用来play下载应用、youtube播放视频的ip肯定不会是google官方的吗？

### ISSUE THREAD

**Issue by imbear** [racaljk/hosts#996]
一直用的是这里的hosts，只能提供基本网页访问，play无法下载应用、youtube无法播放视频——FAQ也是如此讲的——不过间歇的发生过提示应用自动升级完成的通知，总以为是灵异事件。

昨天用play装一个hosts应用，发现用它的hosts，居然可以不开vpn直接下载应用播放视频了，打开它的hosts，发现有关google基本用了一个ip：219.76.4.3

我现在想想，这不会是个代理ip吧，这么牛？ 希望这里有懂行的能点拨一下，谢谢！

**Comment by imknown** [comment]
`219.76.4.3` 貌似是 香港的代理.

**Comment by lrinQVQ** [comment]
219.76.4.3得确是代理 而且时不时屏蔽大陆IP
官网IP也有可用的 不过Youtube和 Google Play的服务器编码地址 你也看到了 我自己也利用我的技术不需要任何代理 可以观看部分视频 那是因为DNS解析到了没有被墙的IP上

**Comment by myguybetter** [comment]
That ip is an sniproxy. You can find more in netblock 219.76.4.0/24.
