### ISSUE TITLE
www.w3schools.com is wrong?

### ISSUE THREAD

**Issue by lyflyflxf** [racaljk/hosts#997]
用68.232.44.251访问www.w3schools.com提示证书错误

> www.w3schools.com 使用了无效的安全证书。 该证书仅对下列域名有效： gp1.wac.edgecastcdn.net, wac.edgecastcdn.net, ne.wac.edgecastcdn.net, swf.mixpo.com, cdn.traceregister.com, s.tmocache.com, s.my.tmocache.com, e1.boxcdn.net, e2.boxcdn.net, e3.boxcdn.net, static.woopra.com, assets-secure.razoo.com, ec.pond5.com, images.esellerpro.com, use.typekit.com, static.iseatz.com, static.www.turnto.com, inpath-static.iseatz.com, secure.avelleassets.com, static.dubli.com, cdn1.fishpond.co.nz, cdn1.fishpond.com.au, cdn.optimizely.com, cdn.whois.com.au, ne1.wac.edgecastcdn.net, gs1.wac.edgecastcdn.net, edgecast.onegrp.com, cdn.psw.net, cdn.gaggle.net, fast.fonts.com, ec.xnglobalres.com, images.vrbo.com, cdcssl.ibsrv.net, player.vzaar.com, framegrabs.vzaar.com, thumbs.vzaar.com, content.aqcdn.com, content.ebgames.com.au, content.ebgames.co.nz, images.allsaints.com, cdn2-b.examiner.com, cdn.trtk.net, ec.dstimage.disposolutions.com, welcome2.carsdirect.com, s1.card-images.com, update.alot.com, www.outsystems.com, www.drwmedia.com, cdn.taxact.com, cdn.taxactonline.com, cdn.200581.com, img.vxcdn.com, js.vxcdn.com, www.cloudwords.com, images.skincarerx.com, ssl.cdn-redfin.com, cdn.foxycart.com, ssl.booztx.com, p.typekit.net, use.typekit.net, cdn.thewatershed.com, b2bportal.disneylandparis.com, b2bportal.disneytravelagents.co.uk, assets.zendesk.com, a.cdnkic.com, s.cdnkic.com, cdn.cartrawler.com, secure.33across.com, static.teamtreehouse.com, www.edgecast.com 错误代码: `SSL_ERROR_BAD_CERT_DOMAIN`

貌似从没人反映过这种问题。
另外，66.29.212.110	w3schools.com 超时，湖北联通。
我现在用192.229.173.207	www.w3schools.com ，是美国亚特兰大的解析结果。不报错，速度也还可以。

**Comment by lrinQVQ** [comment]
确实 直接被DNS污染到国外了

**Comment by DDoSolitary** [comment]
这种网站都封，真是。。

**Comment by lrinQVQ** [comment]
我是一脸mdzz的

**Comment by Too-Naive** [comment]
![](https://cloud.githubusercontent.com/assets/16496671/20557321/f47b3c50-b1a5-11e6-8810-8edc50a65778.png)

**Comment by Ir1d** [comment]
@Too-Naive 静静啊 建议你不要到处发滑稽
以为有啥事点卡然后发现没有任何意义

**Comment by paperbag** [comment]
嗯，微软的 CDN 的 IP 地址是经常会变动的，大概三四天吧（具体我没留意过）。
也就意味着通过修改 Hosts 文件的方式访问它，是要时不时修改一下 Hosts 文件。

**Comment by DDoSolitary** [comment]
@paperbag SMG。。这关微软什么事。。

**Comment by paperbag** [comment]
搞错了:-(一直感觉 Microsoft Azure 和 Edgecast 有关，但是并不是一个公司。

我记得有些 CDN 分配的 IP 地址有时候会变动，像 Akamai 这种的。
